### ISSUE TITLE
Alignment bug in 2.5

### ISSUE THREAD

**Issue by dstarbuc** [mathjax/MathJax#1000]
I found that equations that were centered in the column in 2.4 are now setting flush left in 2.5.

![2-4_ok](https://cloud.githubusercontent.com/assets/10466756/5684232/86422dc6-97fc-11e4-8d1b-7fe7cb3858ce.jpg)
![2-5_bad](https://cloud.githubusercontent.com/assets/10466756/5684231/8641622e-97fc-11e4-8d18-cf809bfb5f98.jpg)

**Comment by dpvc** [comment]
Can you point to a live page that illustrates the problem?  Otherwise, you will need to give more details about your configuration, the format used for input and output, and the browser and OS you are using.

**Comment by dstarbuc** [comment]
OS X 10.9.5, Chrome 39.0.2171.71 (64-bit). Plain-TeX input. I can email you the actual file and our defaul.js and macros file.

**Comment by dstarbuc** [comment]
Attached is our default.js file and the TeX macro extension that is called
from default.js and the source .html file.

On Fri, Jan 9, 2015 at 12:52 PM, Davide P. Cervone <notifications@github.com
> wrote:

> Can you point to a live page that illustrates the problem? Otherwise, you
> will need to give more details about your configuration, the format used
> for input and output, and the browser and OS you are using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mathjax/MathJax/issues/1000#issuecomment-69371174>.
>



-- 
------------------------------------------------------
David Starbuck
Programmer/System Analyst
IEEE Publications
d.starbuck@ieee.org
1+ 732 465 6484 (office)
-------------------------------------------------------

**Comment by dpvc** [comment]
I didn't get any attachments.  :-(
Can you try again?

Davide

**Comment by pkra** [comment]
Please note that GitHub strips attachements if you reply by email. Either email them directly or put a minimal sample up on something like jsbin, jsfiddle, codepen etc.

**Comment by dpvc** [comment]
OK, I found the issue.  There was a variable name conflict:  the one used to compute the `displayIndent` when it was not the default of `"0"` was already in use for another purpose, and so when `displayIndent` was specified, it blew away the original value for that variable.  That caused the centering to get messed up.

I have fixed the issue in the `issue1000` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> In Testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1000-1.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue1000-2.html
