### ISSUE TITLE
SVG output: replace black with currentColor

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1002]
Could the SVG output set stroke and fill to `currentColor`? That would allow the SVG output to inherit text color.

I was experimenting with the SVG output and came up with http://codepen.io/pkra/pen/emgeyJ. Here are [some cross-platform screenshots](http://app.crossbrowsertesting.com/public/icbcbd43afaa1974/screenshots/z6d2bcb00ed6d7b8943f0).

It seems to be a one-liner at https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/SVG/jax.js#L2000 ?

What do you think, @dpvc?

**Comment by dpvc** [comment]
Makes sense.  I wasn't aware of this setting when the SVG output was written (it was my first use of SVG).  I have made the change in the `issue1002` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by pkra** [comment]
Yay. Awesome. Will come up with a test.

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/General/Colors/issue1002.html
