### ISSUE TITLE
An mtable with rowlines=" " is treated as rowlines="solid"

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1004]
If an mtable has `rowlines=""` or `rowlines=" "` is treated as having `rowlines="solid"` in HTML-CSS and SVG output, whereas it should probably be treated as `rowlines="none"`.

**Comment by pkra** [comment]
CommonHTML is fine btw. Could the fix be adopted easily?

**Comment by dpvc** [comment]
> CommonHTML is fine btw. Could the fix be adopted easily?

No, but it is easy enough to fix in other ways.  The `issue1004` branch of my fork of MathJax does that.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1004.html
