### ISSUE TITLE
Formula not centered

### ISSUE THREAD

**Issue by garnakolegovitc** [mathjax/MathJax#1008]
Hallo,
in a forum (http://www.matematicamente.it/forum/index.php) I have the following problem:

![immagine8](https://cloud.githubusercontent.com/assets/5780696/5790783/f054f06a-9ea8-11e4-8e9c-9957e4c3ce4f.png)

the code of my post is:

>>[quote="Frink"]Se ho capito la domanda (la seconda): il monoide non richiede la condizione Abeliana.[/quote] si esatto!! [quote="Frink"]Un monoide può non essere abeliano[/quote] ja, jenao!
[quote="Frink"]Invece requisito necessario per la denominazione di Monoide è la proprietà associativa e il possesso di elemento neutro (il prodotto per l'elemento neutro è sempre commutativo però).[/quote] si ok, ma la condizione sull'elemento neutro \(e\) (nella definizione) [i]non gode di certi principi di economia[/i], ovvero è [u]sovrabbondante[/u].. si può dimostrare che: $$e \cdot x=x  \Rightarrow x \cdot e=x \Rightarrow e \text{ ed }x \text{ sono permutabili }, \forall x \in A$$ [spoiler]\(e\cdot x=x \to x\cdot(e \cdot x)=x \cdot x \to (x \cdot e) \cdot x= x\cdot(e \cdot x)=x \cdot x \Rightarrow x \cdot e=x , \forall x \in A\)[/spoiler] ergo non ti conviene pensare come ad una commutativa perchè questa gode su due qualunque elementi di \(A \), cosa che non si ha nella definizione di elemento neutro!!!<<

I resolve the problem with other users with the following code:

>>[quote="Frink"]Se ho capito la domanda (la seconda): il monoide non richiede la condizione Abeliana.[/quote] si esatto!! [quote="Frink"]Un monoide può non essere abeliano[/quote] ja, jenao!
[quote="Frink"]Invece requisito necessario per la denominazione di Monoide è la proprietà associativa e il possesso di elemento neutro (il prodotto per l'elemento neutro è sempre commutativo però).[/quote] si ok, ma la condizione sull'elemento neutro \(e\) (nella definizione) [i]non gode di certi principi di economia[/i], ovvero è [u]sovrabbondante[/u].. si può dimostrare che: 
\[e \cdot x=x  \Rightarrow x \cdot e=x \Rightarrow e \text{ ed }x \text{ sono permutabili }, \forall x \in A\] [spoiler]\(e\cdot x=x \to x\cdot(e \cdot x)=x \cdot x \to (x \cdot e) \cdot x= x\cdot(e \cdot x)=x \cdot x \Rightarrow x \cdot e=x , \forall x \in A\)[/spoiler] ergo non ti conviene pensare come ad una commutativa perchè questa gode su due qualunque elementi di \(A \), cosa che non si ha nella definizione di elemento neutro!!!<<

in fact I have:

![kuqf9](https://cloud.githubusercontent.com/assets/5780696/5790791/5b5b5f7a-9ea9-11e4-97b6-9ce126820a53.png)

Mathjax is implemented in forum , why the formula is not centered with first code?

**Comment by pkra** [comment]
Was this closed intentionally?

**Comment by garnakolegovitc** [comment]
I am sorry, I thought it was useless!... Is it useless?

**Comment by pkra** [comment]
> Is it useful?

It's hard to tell at this point. We would need a live example exhibiting the error and possibly additional information (i.e., browser and OS versions). Are you able to provide an example?

**Comment by dpvc** [comment]
The page in the screen shot is [here](http://www.matematicamente.it/forum/viewtopic.php?f=26&t=142215&p=899825#p899825).  It appears the only change he made was in the delimiters used.  There should be no difference as far as rendering goes for that.   I'm wondering if reloading the page produces the correct centering, or if it persists.  It is not clear from the original post.
