### ISSUE TITLE
error message in the CD environment

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1013]
When using the AMScd extension, a math processing error message occurs when a keyboard prime is placed just before the structure that draws an arrow.  Adding curly braces helps fix the immediate problem.  Here is an example: http://jsfiddle.net/w17j1rzb/    Happens in both 2.4 and 2.5-beta.  Using FF 31.4 in Windows.  Not sure if this is expected behavior, so I thought I'd let you know.

**Comment by dpvc** [comment]
@orangeplanet, thanks, this is not expected behavior, so we appreciate the report.  I'm looking into it.

**Comment by dpvc** [comment]
OK, found it.  MathJax was using a pointer to the wrong object under certain circumstances (when a cell is not yet closed when the arrow command is read, as is the case with `A'`, since there might be another prime yet to come).

This is resolved in the `issue1013` branch of my fork of MathJax.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/AMScd/issue1013.html
