### ISSUE TITLE
Equation render fails somtimes

### ISSUE THREAD

**Issue by devon** [mathjax/MathJax#1014]
There is an editable div in the html page. The equation will render with Typeset each time lose focus:

```
function renderEquation($element){
    setTimeout(function() {
        MathJax.Hub.Queue(["Typeset", MathJax.Hub, $element[0]]);
    }, 500); 
}
```

But it fails sometimes with same equation, not alwyas. The equation didn't show, and there is no error information. 

Wrong render:
```
<span class="MathJax_Preview"></span><span class="MathJax" id="MathJax-Element-1-Frame" role="textbox" aria-readonly="true"></span>
    <script type="math/tex" id="MathJax-Element-1">\prod^{ }_{ }</script>
```

Correct render:
```
<span class="MathJax_Preview"></span><span class="MathJax" id="MathJax-Element-10-Frame" role="textbox" aria-readonly="true"><nobr><span class="math" id="MathJax-Span-37" style="width: 1.292em; display: inline-block;"><span style="display: inline-block; position: relative; width: 1.023em; height: 0px; font-size: 126%;"><span style="position: absolute; clip: rect(1.682em 1000.001em 2.785em -0.067em); top: -2.488em; left: 0.001em;"><span class="mrow" id="MathJax-Span-38"><span class="munderover" id="MathJax-Span-39"><span style="display: inline-block; position: relative; width: 1.01em; height: 0px;"><span style="position: absolute; clip: rect(1.749em 1000.001em 2.852em -0.067em); top: -2.555em; left: 0.001em;"><span class="mo" id="MathJax-Span-40" style="font-family: STIXGeneral-Regular; vertical-align: 0.001em;">∏</span><span style="display: inline-block; width: 0px; height: 2.556em;"></span></span>
</span>
</span>
</span><span style="display: inline-block; width: 0px; height: 2.489em;"></span></span>
</span><span style="border-left-width: 0.001em; border-left-style: solid; display: inline-block; overflow: hidden; width: 0px; height: 1.323em; vertical-align: -0.338em;"></span></span>
</nobr>
</span>
<script type="math/tex" id="MathJax-Element-10">\prod^{ }_{ }</script>
</div>
```

Config:

```
<script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            jax: ["input/TeX","output/HTML-CSS"],
            tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
            messageStyle: "normal",
            TeX: {
                noErrors: {disabled: true}, // Show error messages
                MAXBUFFER: 25*1024, // Set size of buffer in bytes
              },
            imageFont: null,
            showMathMenu: true,
            skipStartupTypeset: true,
            showProcessingMessages: true,
            TeX: {noErrors: {disabled: true}}
        });
</script>
```

Any tips? thank you.

**Comment by pkra** [comment]
Could you create a live sample on codepen, jsbin etc. that reproduces the problem?

**Comment by devon** [comment]
I tried a very simple demo on codepen, mathjax works great. I guess it's because there are a lot of equations in one document in our system. You may try the system with steps:

1. visit demo.hejiao.com, login with demo@hejiao.com demo123, with safari or chrome.
2. visit a new page at http://demo.hejiao.com/presentations/61988476-0ca7-4964-8f3a-a2bbca0ba9cd/edit
3. There are three buttons at the top tool bar(under blue color), click the centre one to add a equation.

The equation rendering will fail sometimes. But it works with small document(less pages).

Thank you.

**Comment by pkra** [comment]
Thanks but we would need a more minimal example that exhibits the problem.

**Comment by devon** [comment]
How to trace render process? I will try to debug by myself

**Comment by mfguasti** [comment]
same problem here.
Some times renders fine and some others it does not, without giving any message.

**Comment by mfguasti** [comment]
I switched from the mathjax server to mathjax in my own serverand it now renders fine always

#$wgMathJaxUrl = 'http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML';
$wgMathJaxUrl = '/usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS_HTML';

**Comment by mfguasti** [comment]
Please ignore my previous comment.
Even if rendering is done locally it still sometimes renders nicely and sometimes it does not.

**Comment by devon** [comment]
I think I found the code for this problem.

```
GetID: function() {
   this.ID++;
   return "MathJax-Element-" + this.ID
 },
```

MathJax use self increment for Div ID. But we cached the rendered data into database. After page refresh, MathJax will start ID from 0,  but the 0 Element already exist.

It works after I modify the ID to UUID.

**Comment by pkra** [comment]
@mfguasti could you file a separate issue and provide a minimal example that reproduces the issue?

@devon glad you could track it down. MathJax uses the IDs to link the interal representation to the DOM output (which can change for a number of reasons). Unfortunately, MathJax's HTML-CSS output cannot be reasonably cached (it's very client dependent, differing across browsers, browser versions, OS, OS versions, available local fonts etc) but if you want to do this despite these reasons then you need to strip at least the ids.

**Comment by devon** [comment]
So, use SVG output will be better if we cached the render result?

You may close this issue.

**Comment by pkra** [comment]
> So, use SVG output will be better if we cached the render result?

Yes, the SVG output is stable across browsers and platforms. However, the SVG output relies heavily on `<use>` elements (for speed and size) and you'll have to either resolve those yourself or use MathJax-node on the server. If you resolve them yourself, you'll still have to remove the `MathJax-Element-*` ids.

**Comment by mfguasti** [comment]
The way I solved it is to put 'no cache' in LocalSettings.php

$wgParserCacheType = CACHE_NONE;
