### ISSUE TITLE
Referring to labels defined in an expression with "split" or "aligned" environments seems broken

### ISSUE THREAD

**Issue by timtylin** [mathjax/MathJax#1020]
Here's a summary screenshot:

![](https://www.evernote.com/shard/s145/sh/b73757e0-e409-4c44-b085-9ad0957ae36f/24f6c11e6a946e9a6770bc205ea35aac/deep/0/Edit-fiddle---JSFiddle.png)

[…and the corresponding jsFiddle example](http://jsfiddle.net/smxxz1xh/2/)

As far as I can tell, this applies to cases where a `split` (as shown above) or `aligned` environment [(seen here)](http://jsfiddle.net/smxxz1xh/3/) is used inside an `equation` environment. The numbering on the equation itself displays fine, but using either `ref` or `eqref` to refer to the label would produce the "reference not found" question marks.

According to internal testing records, this issue seems to exist in 2.4 as well.

**Comment by pkra** [comment]
Thanks for reporting this. (It's unfortunately a bit late in the beta so it's unlikely we'll get this into 2.5.)

**Comment by dpvc** [comment]
As a temporary work-around, you can get the label and reference to operate by putting the label at the bottom rather than at the top, as in

```
\begin{equation}
  \begin{split}
    y=ax\\
    g=by
  \end{split}
  \label{multiline-label}
\end{equation}
```

Note also that you don't have to use `\[...\]` around these environments, as MathJax will pick up `\begin{xyz}...\end{xyz}` as math delimiters automatically.

**Comment by dpvc** [comment]
This is fixed in v3.
