### ISSUE TITLE
\middle preceded by primed symbol gives an error.

### ISSUE THREAD

**Issue by nberth** [mathjax/MathJax#1023]
The following code gives me an error "\middle must be within \left and \right" when I render it in my browser (Firefox 21.0, MathJax v2.4.0):

- `\left\{q\in Q \middle| P(q)\right\}` works;
- `\left\{q\in Q' \middle| P(q)\right\}` doesn't, nor `\left\{q\in Q'' \middle| P(q)\right\}` incidentally.
This also happens when `Q'` is the result of macro expansion:
- `\newcommand{\Q}{Q} \left\{q\in \Q \middle| P(q)\right\}` works;
- `\newcommand{\Q}{Q'} \left\{q\in \Q \middle| P(q)\right\}` doesn't.

The error is reproducible (though no error message is displayed) on the dynamic rendering page [1], yet I did not try it on the development branch for lack of time to install it (can anyone try?).

[1] http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html

**Comment by pkra** [comment]
Thank you for reporting the issue! (I've modified your posting to escape the TeX). We'll look into it.

**Comment by dpvc** [comment]
For now you can use 

    \left\{q\in {Q'} \middle| P(q)\right\}

to get the result you are looking for.  There is a problem with how `\middle` detects whether it is within `\left...\right` (obviously).

**Comment by dpvc** [comment]
The `issue1023` branch of my fork of MathJax resolves this issue (as well as a potential spacing problem with `\middle`).

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/delimiters/issue1023.html
