### ISSUE TITLE
[mml3.js] collection of failed MML test suite tests

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1025]
Just a quick pass. Some of these seem like bugs but most seem to be missing features.

Live demo: http://codepen.io/pkra/pen/WbRzOm
## Open (by priority)

Sorted  by priority / feasability.
- [x]  #1252 complete failure on MS Edge.
### Elementary math
- [ ] [longdivision-rtl2-full](http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/longdivision-rtl2-full.xhtml)
  -- main "line" extends far too the left. (why is that test marked RTL in the MathML suite?)
- [ ] [ElementaryMathExamples-msline01-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-msline01-full.xhtml), [ElementaryMathExamples-msline02-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-msline02-full.xhtml) 
  -- msline position is off by 1 -- simple bug?
- [ ] [ElementaryMathExamples-mstack04-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack04-full.xhtml)
  -- stackalign="decimalpoint" cuts off msline -- bug?
- [ ] [ElementaryMathExamples-mstack20-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack20-full.xhtml)
  -- align="baseline -2" fails (other align tests look basically ok -- simple bug?)
- [ ] [ElementaryMathExamples-mscarries07-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mscarries07-full.xhtml), [ElementaryMathExamples-mscarry10-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mscarry10-full.xhtml), [ElementaryMathExamples-mscarry11-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mscarry11-full.xhtml)
  -- spacing issues in subsequent carries (also, msline segmented) -- fixable?
- [ ] [ElementaryMathExamples-msline03-full.](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-msline03-full.xhtml)
  -- leftoverhang / rightoverhang fails
- [ ] [ElementaryMathExamples-mstack05-full.](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack05-full.xhtml) (etc.)
  - charspacing fails
- [ ] [ElementaryMathExamples-mstack10-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack10-full.xhtml)
  -- charalign fails
- [ ] [ElementaryMathExamples-mstack24-full](http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack24-full.xhtml)
  -- align="axis" fails.
### RTL
- [ ] Elementary math seems to ignore directions but the rendering is generally RTL? (see ltr "copies" of RTL examples on codepen)
- [ ] [longdivision-rtl1-full](http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/longdivision-rtl1-full.xhtml)
  -- Long division example is missing a linebreak (third line is on the second line) and suffers from extended "main line" mentioned above.
- [ ] [Maghreb-1-full](http://www.w3.org/Math/testsuite/build/mathml3/Topics/BiDi/Complex/Maghreb1-full.xhtml) Sigma is not flipped. Probably other characters as well? (IIRC, the xslt used to us an SVG transform; CSS transforms could play a similar role in the HTML-CSS output but this probably needs to happen in a proper implementation in the output jax).
### Elementary Math
- [x] http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mstack02-full.xhtml
  - stackalign="center" fails (left, right are ok) -- bug?
- [x] http://www.w3.org/Math/testsuite/build/main/Topics/ElementaryMathExamples/ElementaryMathExamples-mscarries13-full.xhtml
  - scriptsizemultiplier fails
### RTL
- [x] **HTML-CSS output & browsers interference** MathJax passes `dir` to the output and some browsers to rearrange the output (cf. complex layout and ligatures).
  -- **Override by CSS**: `.MathJax span { direction: ltr ! important; display: inline-block !important; }` (needs detailed testing but quick test across browsers seems fine). Example: http://codepen.io/pkra/pen/rOBWPP
  - [x] http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/mfenced2-full.xhtml 
  - [x] http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/mixednumbers-rtl1-full.xhtml 
  - [x] http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/mmultiscripts3-full.xhtml 
  - [x] http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/mmultiscripts2-full.xhtml 
  - [x] http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/thearithmeticmean1-full.xhtml 
- [x]  [subtraction-rtl1-full](http://www.w3.org/Math/testsuite/build/main/Topics/BiDi/RTL/subtraction-rtl1-full.xhtml)

**Comment by davidcarlisle** [comment]
Thanks for that, I'll see what I can do....

**Comment by davidcarlisle** [comment]
I added support for scriptsizemultiplier= and stackalign=center to the
upstream googlecode sources.

https://code.google.com/p/web-xslt/source/list

I hope to do some more during the week, so you could pick up the
mml3.js or wait, depending which works best for you.

David

**Comment by pkra** [comment]
Note to self: browsers are "interfering" in RTL behavior. E.g., the first test at http://codepen.io/pkra/pen/WbRzOm will render correctly in SVG but not HTML-CSS.

**Comment by davidcarlisle** [comment]
On 4 February 2015 at 09:34, Peter Krautzberger <notifications@github.com>
wrote:

> Note to self: browsers are "interfering" in RTL behavior. E.g., the first
> test at http://codepen.io/pkra/pen/WbRzOm will render correctly in SVG
> but not HTML-CSS.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mathjax/MathJax/issues/1025#issuecomment-72820726>.
>



Yes I had wondered about injecting bidi isolation characters into token
elements in mml3mml2's rtl support  but most appropriate is probably U+2069
but that's Unicode 6 and produces missing glyph markers if the browser/font
not expecting it. The mathml spec says that each token element should be
isolated for bidi so arguably mathjax could? be using <bdi>   or a css CSS
rule  using unicode-bidi: on token elements although they are a similar
vintage: bdi, being introduced in html5  so I don't know....

**Comment by pkra** [comment]
Thanks, David. I suspect we're just getting to the end of the line of hacking RTL support this way.

**Comment by davidcarlisle** [comment]
Just a note to say that since googlecode is being killed the upstream repository is now also on github at

https://github.com/davidcarlisle/web-xslt

**Comment by pkra** [comment]
Thanks for the heads up, @davidcarlisle

**Comment by pkra** [comment]
I've updated the OP with the latest results.

**Comment by pkra** [comment]
Another update to the OP, noting the improvements to the RTL tests. We should probably add that CSS hack to the extension.

**Comment by pkra** [comment]
Added  #1252
