### ISSUE TITLE
\alignedat spacing

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1028]
\alignedat still has a problem like the one described in issues #811 and #982 in some cases.  Seems to happen if the math that comes before the equals has subscripts or if there is an accented character somewhere in the string.  Maybe it is getting confused on a curly brace?  

See http://jsfiddle.net/9pu72jkr/

**Comment by pkra** [comment]
Thanks for reporting this. We'll look into it.

**Comment by dpvc** [comment]
It looks like I missed the `alignedat` when I did `aligned` and `aligned*` (there is an if-then that affects it that I didn't spot).  It is a simple fix, but we've just today finished the v2.5 release candidate, so I don't think the fix will make it into v2.5.

You probably already know this, but you can work around this in the meantime by adding `{}` between the `&` and `=`.  I can probably give you a pre-filter that would insert those automatically for you, if the fix doesn't make it into v2.5.

**Comment by dpvc** [comment]
This is resolved in the `issue1028` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> in testsuite

LaTeXToMathML/environments/issue1028.html
