### ISSUE TITLE
Spacing reserved for number tags need reevaluating after adjusting math font metric from scaling

### ISSUE THREAD

**Issue by timtylin** [mathjax/MathJax#1031]
Hey guys, thanks for all the work on v2.5, it's an amazing release. I'm just reporting on the remaining bugs that I see in our publication collection.

This one concerns the spacing in an expression usually reserved for number tags. Let's start with a long expression with a numbering tag on the left (or right, doesn't matter), so that the expression is already uncomfortably butting against the numbering:

![](https://www.evernote.com/shard/s145/sh/25102656-ac2e-4b7b-a22b-526826f71329/5f28678066d0043db65abf6a6908380c/deep/0/Edit-fiddle---JSFiddle.png)  
[jsFiddle source](http://jsfiddle.net/smxxz1xh/4/)

Now, let's bring in a font that is larger than normal (or just has a large x-height). Note that now the expression got bigger since the font size got adjusted up. In fact, it now squishes into the numbering, which should never happen. I'm *guessing* this is because the spacing needs re-calculation after the scaling, but it isn't done:

![](https://www.evernote.com/shard/s145/sh/c336912e-808e-43b4-ab35-3a0f480b0ac9/922c8f766e78aa8f57eb2d50d9e3ea7b/deep/0/Edit-fiddle---JSFiddle.png)  
[jsFiddle source](http://jsfiddle.net/smxxz1xh/5/)

The reason why this is semi-serious is because `matchFontHeight` is turned on by default, so any CSS have the potential to trigger this behavior. Turning off `matchFontHeight` solves this issue:

![](https://www.evernote.com/shard/s145/sh/937442b7-5360-4f91-a129-17f47fee784b/13ffa4d0e640f74926372aafc2285953/deep/0/Edit-fiddle---JSFiddle.png)  
[jsFiddle source](http://jsfiddle.net/smxxz1xh/6/)

And just to show that adjusting the `scale` property in the `HTML-CSS` writer also causes this problem:

![](https://www.evernote.com/shard/s145/sh/17380f26-9f43-45c7-9eff-4e99f0efd570/cc911d8a9d2ee59afd1a54f27a364ac6/deep/0/Edit-fiddle---JSFiddle.png)  
[jsFiddle source](http://jsfiddle.net/smxxz1xh/8/)

**Comment by pkra** [comment]
This is expected behavior, I'm afraid.

> In fact, it now squishes into the numbering, which should never happen

Actually, [MathML spec](http://www.w3.org/Math/draft-spec/chapter3.html#presm.mlabeledtr) suggests to shift the equation label down. But that's very complicated and not yet implemented. (This is also not new to 2.5 btw.)

**Comment by timtylin** [comment]
> (This is also not new to 2.5 btw.)

That's the thing--this didn't happen with v2.4 with CSS-HTML output, whether intended or not. [Here's the example I posted but using v2.4 instead.](http://jsfiddle.net/smxxz1xh/10/)

**Comment by timtylin** [comment]
I should add that this still happens when you enable scrolling behavior for the `overflow-x` property on the enclosing block element, which is how I've traditionally dealt with long equations on small viewports prior to v2.4. That strategy used to work great.

**Comment by pkra** [comment]
Thanks for the additional information. I'm wondering if this is a side effect of various alignment and indentation issues we fixed in 2.5. For now you might want to add some indentation via `displayIndent`.

**Comment by timtylin** [comment]
Thanks for getting back to this. Is this now a duplicate of some other spacing/metric issue?

**Comment by pkra** [comment]
Sorry, this was accidentally closed as expected behavior.

**Comment by pkra** [comment]
This was fixed in v2.6.
