### ISSUE TITLE
Inline math width = 0.002em after upgrading to mathjax 2.5

### ISSUE THREAD

**Issue by benweet** [mathjax/MathJax#1034]
As you can see here, on this instance of StackEdit with MathJax upgraded:
http://54.152.115.207/editor

At least for me, on Chrome/OSX, the inline block width is not calculated properly, which provoques the math to overlap the text in the paragraph:

![screen shot 2015-01-31 at 12 28 04](https://cloud.githubusercontent.com/assets/1005257/5988019/ae53b114-a944-11e4-9f39-2a468f8c2f98.png)

It only happens at startup. The width is set properly after modifying the text.
This is not happening with previous version of MathJax.

**Comment by dpvc** [comment]
Does this persist if you reload the page?

**Comment by benweet** [comment]
Yes it does.

**Comment by benweet** [comment]
I can switch to the unpacked version of MathJax if you need. Let me know if you want me to change something on that page.

**Comment by dpvc** [comment]
I'm not actually able to reproduce the problem, so that won't help at the moment, but thanks.  What version of Chrome and OSX are you using?

**Comment by benweet** [comment]
Chrome: 40.0.2214.94 (64-bit)
OSX: 10.10.2 (14C109)

Same problem on Chrome 42.0.2292.0 canary (64-bit)

**Comment by dpvc** [comment]
From your screen shot, it looks like you are using local STIX fonts (that would make sense since OSX comes with those installed).  Can you try switching to web based fonts?  To do that, add

```
"HTML-CSS": {
   availableFonts: [],
   preferredFont: null
}
```
 to your MathJax configuration.  I'm running an older version of OSX, and still can't reproduce the issue.

**Comment by benweet** [comment]
Indeed, disabling the STIX font in the system fixes the issue.

**Comment by dpvc** [comment]
Thanks, that is useful information. I'll see if I configure out what is going on.

**Comment by benweet** [comment]
I'm going to switch off the VM. Please tell me if you need me to switch it back.

**Comment by pkra** [comment]
Is the original issue still occurring in 2.6? We never reproduced this in an example, I think. 

=> marked abandoned (for now)

**Comment by pkra** [comment]
Closed as abandoned.
