### ISSUE TITLE
Fractions not properly formatted in WebKit and IE in CommonHTML

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1035]
See http://mathhelpboards.com/math-notes-49/pell-sequence-2905.html#post14276

and the discussion [here](https://groups.google.com/forum/?fromgroups#!topic/mathjax-users/MUrkEJO6X24).

**Comment by pkra** [comment]
This is marked fixed in #1051 is that correct?

**Comment by dpvc** [comment]
Yes, this is fixed in the `chtml` branch of my fork of MathJax.  But if we keep the current CHTML as a fast preview, I will need to fix it in that setting.  I'm moving to the 2.6 milestone.

**Comment by dpvc** [comment]
This is fixed in the `develop` branch.
