### ISSUE TITLE
Improve CDN rollover behavior

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1036]
As per discussion elsewhere, let's go back to `cdn.mathjax.org/mathjax/latest` only serving `MathJax.js` which re-routes all other resources to `/N.m-latest`.

**Comment by dpvc** [comment]
The `issue1036` branch of my fork of MathJax resolves this.  Also, it removes the old roll-over from rackspace to the new can address, since that is no longer active.

**Comment by dpvc** [comment]
==> Merged
