### ISSUE TITLE
Documentation for Fast Html

### ISSUE THREAD

**Issue by infro42** [mathjax/MathJax#1037]
Hi,

I was not able to find documentation for Fast Html mode, only some comment from ago, that Fast Html is lower quality than Html-Css. Also was not able to find how to set it as default. I am not sure if we can use it in production or not. We don't want to use Html-Css + Fast Preview, because then math changes style 2 times, and it seems like flickering. Fast Html looks fine and switches only one time, but as I said I did not find if it can be used and displays everything correctly.

**Comment by pkra** [comment]
As discussed in the [release announcement](http://www.mathjax.org/mathjax-v2-5-now-available/), the preview mode was included in the combined configuration files but both author and user can override this. For  documentation, see [our documentation](http://docs.mathjax.org), in particular the [CHTML-preview extension](http://docs.mathjax.org/en/latest/options/CHTML-preview.html) and the [CommonHTML output](http://docs.mathjax.org/en/latest/options/CommonHTML.html).

**Comment by davidcarlisle** [comment]
On 3 February 2015 at 07:36, Peter Krautzberger <notifications@github.com>
wrote:

> As discussed in the release announcement
> <http://www.mathjax.org/mathjax-v2-5-now-available/>, the preview mode
> was included in the combined configuration files but both author and user
> can override this. For documentation, see our documentation
> <http://docs.mathjax.org>, in particular the CHTML-preview extension
> <http://docs.mathjax.org/en/latest/options/CHTML-preview.html> and the CommonHTML
> output <http://docs.mathjax.org/en/latest/options/CommonHTML.html>.
>
Probably the new common HTML output should be listed  here?

http://docs.mathjax.org/en/latest/output.html

as the link you give above

http://docs.mathjax.org/en/latest/options/CommonHTML.html

is how to customise it rather than documenting it exists.

David

**Comment by pkra** [comment]
Ah, we missed that page... 

I've filed a but upstream at https://github.com/mathjax/MathJax-docs/issues/91. Closing this here.

**Comment by pkra** [comment]
PS.

>  Fast Html looks fine and switches only one time, but as I said I did not find if it can be used and displays everything correctly.

FYI, the CommonHTML output is not yet on par with HTML-CSS or SVG, neither in terms of features nor in terms of layout quality.
