### ISSUE TITLE
Cleaning up outdated branches

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1038]
I think we can delete the following branches

* 2.5-i18n
* 2.3-beta
* 2.4-beta
* 2.5-beta

Any objections?

**Comment by dpvc** [comment]
No, I was hoping to remove the beta branches also.

Davide

**Comment by pkra** [comment]
Ok, I removed those.

Do we need a v2.5-latest branch?

**Comment by dpvc** [comment]
Yes.  That should branch from master at the v2.5 tag.

**Comment by pkra** [comment]
Done.
