### ISSUE TITLE
No QED symbol

### ISSUE THREAD

**Issue by AlexandreZani** [mathjax/MathJax#1052]
I think it would be really useful if you could provide a QED symbol. I'm using MathJax to share proofs and having to copy around the unicode QED symbol is just not a great experience.

**Comment by pkra** [comment]
=> Labeled as feature request. 

>  it would be really useful if you could provide a QED symbol

A little bit more information would be helpful. I suspect you mean http://www.fileformat.info/info/unicode/char/220e/index.htm? What shoul the macro look like? (I admit I've never used qed manually; best practice is to have the proof environment add it, no?)

> having to copy around the unicode QED symbol is just not a great experience.

In general, our policy is to not add macros in the MathJax core which create Unicode characters that our fonts do not cover (don't have a glyph for). So I'm adding this to the "future font release" milestone when we'll consider adding new glyphs; there's not ETA on that though.

To get you going right now you could define your own qed macro using `\newcommand` and the [unicode](http://docs.mathjax.org/en/latest/tex.html#unicode-support) extension.

**Comment by davidcarlisle** [comment]
On 12 February 2015 at 11:30, Peter Krautzberger <notifications@github.com>
wrote:

> => Labeled as feature request.
>
> it would be really useful if you could provide a QED symbol
>
> A little bit more information would be helpful. I suspect you mean
> http://www.fileformat.info/info/unicode/char/220e/index.htm? What shoul
> the macro look like? (I admit I've never used qed manually; best practice
> is to have the proof environment add it, no?)
>
> having to copy around the unicode QED symbol is just not a great
> experience.
>
> In general, our policy is to not add macros in the MathJax core which
> create Unicode characters that our fonts do not cover (don't have a glyph
> for). So I'm adding this to the "future font release" milestone when we'll
> consider adding new glyphs; there's not ETA on that though.
>
> To get you going right now you could define your own qed macro using
> \newcommand and the unicode
> <http://docs.mathjax.org/en/latest/tex.html#unicode-support> extension.
>
>
The ams classes actually use an open square like \square (which is
supported by mathjax) as \qedsymbol.

**Comment by pkra** [comment]
> The ams classes actually use an open square like \square (which is supported by mathjax) as \qedsymbol.

Sure but the OP mentioned Unicode specificallty so I'm guessing U+220E but I've also seen other symbols. There's just not enough information to go on.

**Comment by AlexandreZani** [comment]
Sorry. The unicode char was merely a suggested implementation. I just want a way to put a little black square to indicate qed.

**Comment by pkra** [comment]
@AlexandreZani no problem. Is `\qedsymbol` enough for your use case?

**Comment by AlexandreZani** [comment]
Yes. It's good enough for me.

**Comment by pkra** [comment]
Thanks. Closing this then.
