### ISSUE TITLE
Multiple subscripts

### ISSUE THREAD

**Issue by asgerix** [mathjax/MathJax#1054]
In previous versions of MathJax it was possible to write:

    \sum_{i=1}_{i \le n}i

to get two lines below the summation sign. This does not work in the newest version. I'm not sure if this is actually a bug, or if it's just a question of undefined behaviour.

I realize that I can write:

    \sum_{\substack{ i=1 \\ i \le n }}i

to get the same result, but for the sake of backwards compatability it would be nice if the first method worked.

**Comment by dpvc** [comment]
TeX does not allow this construct, and MathJax as *supposed* to produce an error for this as well, but the check wasn't being performed properly, and so it was allowed through unintentionally.   This has been corrected in v2.5.  It was never intended to be allowed as valid notation, so unfortunately you have been taking advantage of a bug in MathJax that has now bee fixed.  

If you have a lot of legacy code that includes this, it would be possible for you to add a TeX input jax pre-filter that would convert it to the `\substack` notation.

**Comment by asgerix** [comment]
Thank you for your quick reply!
Luckily, I don't have that much legacy code using this "feature", so I will just fix it manually.
