### ISSUE TITLE
MathJax breaks in IE

### ISSUE THREAD

**Issue by aahdahl** [mathjax/MathJax#1055]
Hello,

We are running MathJax2.5 and have found that it breaks in IE with our solution. Through debuggin, we have found that it breaks when function EVAL is called with the input variable code with the value ";\n1;".
We fixed this issue by changing the EVAL function as follows:

var EVAL = function (code) {
    if(code == ";\n1;") {
        return eval.call(window, "")
    } else {
        return eval.call(window, code)
    }
};

However, I imagine that there must be a better way to resolve this issue, and we have no understanding why the solution fails when code is ";\n1;", nor why code is ever  ";\n1;".

**Comment by pkra** [comment]
Please provide [more detailed information](https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports) and a live sample that exhibits the problem.
