### ISSUE TITLE
Weird Delta Break

### ISSUE THREAD

**Issue by BHouwens** [mathjax/MathJax#1057]
I'm experiencing strange breakouts of a delta character. I get this in the browser:

![offending-triangle](https://cloud.githubusercontent.com/assets/5681674/6168118/02d60dc4-b2cb-11e4-95b3-1160cafd09d6.png)

Which looks like a styling issue, until I looked at the HTML:

![offended-code](https://cloud.githubusercontent.com/assets/5681674/6168199/cb6955fc-b2cb-11e4-9c93-af8b15e45e3f.png)

Unfortunately there doesn't seem to be a means to reproduce this problem -- it's erratic -- and I don't have the original HTML file to actually provide a link to.

**Comment by pkra** [comment]
We would need more information, at the very least the MathJax configuration, the browser and OS versions, and almost always  a live sample, even if it's erratic. Thanks.

**Comment by dpvc** [comment]
What Peter has requested is really important, as we can't tell much about the situation without it.

The screen shot you provide suggests that you are using MathML input, and that that MathML includes an <mi> that contains the character U+20E4, COMBINING ENCLOSING UPWARD-POINTING TRIANGLE.  The combining characters have zero width and extend backward over the character that precedes them.  In your case, there is no preceding character within the math, and so the triangle extends into the space before the math.

This seems to be an error in your original MathML, not in MathJax's rendering, so I'd look at whatever is producing your MathML for the problem.

Davide

**Comment by BHouwens** [comment]
Thanks guys what you've suggested is already helpful. As mentioned I have no access to the original MathML, but it is worth investigating on my side. It's unfortunately one of those errors that behaves badly on everything tested, but in an erratic manner.

**Comment by dpvc** [comment]
You can get the original MathML using the contextual menu (right-click on the typeset expression, and choose "Show Math As" -> "Original MathML").  The HTML page contains the original MathML, as your screen shot shows.  After all, MathJax is processing *something* on the page, and that is one of the things we would need to see in order to be able to help you.
