### ISSUE TITLE
Don't render on page load

### ISSUE THREAD

**Issue by 57even** [mathjax/MathJax#1062]
I want to render MathJax dynamically. My textarea is empty at the beginning but as I'm typing math it should render. I'm doing this with `MathJax.Hub.Queue(["Typeset",MathJax.Hub,"output"]);` and it's really great! However, when MathJax is loaded it looks for math to render on page load. I want to save this rendering as I'm sure there wont be any math.

I've found that I can add `class="tex2jax_ignore"` to the `<body>` tag and `class="tex2jax_process"` to the output `<div>` tag. But is this really necessary? Can't I just tell MathJax not to do anything before I ask it to render myself with `MathJax.Hub.Queue(["Typeset",MathJax.Hub,"output"]);`?

**Comment by pkra** [comment]
> Can't I just tell MathJax not to do anything before I ask it to render myself with MathJax.Hub.Queue(["Typeset",MathJax.Hub,"output"]);?

Yes, you can. Set `skipStartupTypeset in the core configuration options, see http://docs.mathjax.org/en/latest/options/hub.html
