### ISSUE TITLE
Font changes after rendering

### ISSUE THREAD

**Issue by 57even** [mathjax/MathJax#1063]
My math first renders to a normal font weight and then 're-renders' to a more bold font weight. Is this intended behaviour or do I need to specify a font or something in order to not letting the engine determine the font itself?

The same thing happens at http://cdn.mathjax.org/mathjax/latest/test/sample-tex.html

**Comment by hubgit** [comment]
Perhaps the perceived font weight is changing at the point when the web fonts finish loading?

**Comment by pkra** [comment]
We'd really need more information but you are probably referring to the effect of the [CHTML-preview extension](http://docs.mathjax.org/en/latest/options/CHTML-preview.html) which we introduced in MathJax v2.5 and which is [included in all combined configuration files](http://docs.mathjax.org/en/latest/config-files.html).
