### ISSUE TITLE
Computer Modern font rendering

### ISSUE THREAD

**Issue by PeterBocan** [mathjax/MathJax#1067]
Is there any option to use classic Computer Modern font in MathJax? It would help a lot.

**Comment by pkra** [comment]
The MathJax "TeX" fonts are actually derived from Computer Modern (including many of their oddities). 
What improvements are you hoping for?

**Comment by PeterBocan** [comment]
Performance and the strangest thing in this all is that SVG renderer and HTML-CSS renderer does look totally different (what's the difference?).

**Comment by pkra** [comment]
Fonts don't impact performance beyond their download (which wouldn't change much with a different variant of CM). 

I'm not sure what you mean with "totally different". The HTML-CSS output uses fonts, the SVG output uses SVG paths. If you just mean the thickness, try setting the `blacker` option to 1; see http://docs.mathjax.org/en/latest/options/SVG.html.

**Comment by dpvc** [comment]
If you have the STIX fonts installed locally (on the computer where you are running the browser), then MathJax will use those in preference to downloading web fonts (for performance reasons).  The STIX fonts look different from Computer Modern.  If that is the case for you, you could either disable or delete the STIX fonts, or download and install the MathJax TeX fonts (as MathJax uses those before the STIX fonts).

**Comment by pkra** [comment]
Ah yeah, there's that...
