### ISSUE TITLE
weird spacing for inline formula when font-size is set for <span>

### ISSUE THREAD

**Issue by mx237** [mathjax/MathJax#1071]
The following html code produces weird spacing on my machine, tested under chrome 40.0.2214.115 m and IE 11.0.9600.17420(x64). My OS is windows 7 x64, and system default language is English.
```
<!DOCTYPE html>
<html>
<head>
<style>
body { font-family: sans-serif; }
span { font-size: 16px; }
</style>      
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-
full"></script>
</head>
<body>
Test symbols: \(a, b, c\), and \(x, y, z\).
</body>
</html>
```
The symbols look good but the spacing looks weird.
However, if I delete ```span { font-size: 16px; }```, everything looks fine.

Since I am new to MathJax, I am sorry if this is a known issue or I did not configure it properly.

**Comment by pkra** [comment]
Thanks for reporting. We'll look into it.

**Comment by pkra** [comment]
This is causd by MathJax trying to match the ex-height of the surrounding content and the HTML-CSS output using spans to build its output. 

You can work around this problem by using the SVG output or by deactivating the  `matchFontHeight`, see the http://docs.mathjax.org/en/latest/options/HTML-CSS.html

@dpvc is this expected behavior on our end?

**Comment by dpvc** [comment]
As Peter points out, MathJax uses spans all over the place to create its output, so styling raw span tags can definitely interfere with MathJax in unpredictable ways.

A solution in this case is to add

    .MathJax span {font-size: inherit}

to your `<style>` section to override the `font-size` setting within MathJax output.  While we have tried to protect MathJax's output from external CSS changes, we can not anticipate everything that you could do that would interfere with MathJax.

**Comment by mx237** [comment]
Thank both of you for your solutions. I have tried ```.MathJax span {font-size: inherit}``` and
```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {
    matchFontHeight: false
  }
});
</script>
```
Both works fine.

I would suggest to fix this issue (e.g., adding ```.MathJax span {font-size: inherit}``` to MathJax css), if it will not cause side effects.
