### ISSUE TITLE
right-justify prescripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1072]
The MathML spec has been clarified to say that prescripts should be right-justified.

Cf. #956

**Comment by dpvc** [comment]
The `issue1072` branch of my fork of MathJax includes the fix for SVG and HTML-CSS output.  The new CommonHTML in the `chtml` branch already does this.  The old CommonHTML didn't implement `mmultiscript`.

I have added 956 to the 2.6 milestone, since I haven't yet changed it to use `mmultiscript`.

**Comment by dpvc** [comment]
==> Merged

**Comment by akotynski** [comment]
This example still does not work with develop: https://jsfiddle.net/1va6y0xf/2/
(fraction in prescript)

**Comment by pkra** [comment]
This change will ship 2.6, i.e., has not shipped yet so it's not surprising that it doesn't work with 2.5 (which is what the fiddle links to)

**Comment by akotynski** [comment]
But it doesn't work with develop. When there is simple number (not a fraction) it works but this example still does not work.

**Comment by pkra** [comment]
Ah! Thanks for following up. I can confirm the problem on `develop`. @dpvc?

**Comment by dpvc** [comment]
OK, the code was relying on a scaling factor being set that wasn't set for fractions (so the computation for the shift returned NaN).  I have resolved the issue in the `issue1072` branch of my fork of MathJax.

**Comment by pkra** [comment]
Great. Thanks again, @akotynski for catching that!

**Comment by dpvc** [comment]
=> in testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mmultiscripts/issue1072.html
