### ISSUE TITLE
Extra space at the right of TeX matrices

### ISSUE THREAD

**Issue by Klortho** [mathjax/MathJax#1073]
When there are superfluous ampersands at the end of each line of a matrix, MathJax inserts extra space on the right side, before the matrix delimiter, as though it expects another column.

When I render this with LaTeX:

```tex
\documentclass[12pt]{minimal} 
\usepackage{amsmath} 
\begin{document}
$$\left(\begin{matrix}V&\\r&\end{matrix}\right)$$
\end{document}
```

I get: 

![screen shot 2015-02-27 at 10 52 15 am](https://cloud.githubusercontent.com/assets/77226/6415779/1c508888-be6f-11e4-8ada-e8be10d9ab91.png)

But in MathJax, for the same thing:

```tex
\[ \left(\begin{matrix}V&amp;\\r&amp;\end{matrix}\right) \]
```

I get: 

![screen shot 2015-02-27 at 10 52 01 am](https://cloud.githubusercontent.com/assets/77226/6415796/41ab7aca-be6f-11e4-97d4-e28b1a5d3803.png)

**Comment by pkra** [comment]
Without much testing, this seems to be affected by the document class -- changing `minimal` to `article` gives me the extra column in pdflatex?

**Comment by pkra** [comment]
FWIW http://tex.stackexchange.com/questions/42114/why-should-the-minimal-class-be-avoided

**Comment by dpvc** [comment]
As Peter points out, this depends on the document class.  MathJax uses `article` as the source for what it emulates, so the extra space is correct from our perspective.

**Comment by dpvc** [comment]
You could probably create an extension that trims the blank entries from the array when it is created by the TeX input jax, however, if you really wanted.

**Comment by Klortho** [comment]
Thanks!
