### ISSUE TITLE
Feature request: TeX environment like flalign

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1075]
[Archiving from this dev-list posting https://groups.google.com/forum/#!topic/mathjax-dev/dCngNgqHDi8.]

Temporarily changing the alignment of a display equation might be a nice TeX extension. flalign does this and it's not hard to implement via `indentalign="left"`. Should probably start on as a third party extension.

**Comment by jason-s** [comment]
Is there any way to achieve this now (Feb 2017) using the latest MathJax? I have the same need to do this.

**Comment by pkra** [comment]
> Is there any way to achieve this now (Feb 2017) using the latest MathJax? I 

No, this remains an open feature request. 

> I'm not sure why there has to be a third-party extension;

It could end up in the core; that depends on the complexity and thus maintenance costs it would add.

**Comment by dpvc** [comment]
For the moment, you can use 

```
\begin{multline}
\shoveleft
\begin{aligned}
    A &= \pi r^2\\
   &=\text{area}
\end{aligned}
\end{multline}
```

to get something like that.  But note that bad default the `multline` environment uses 85% of the container width in MathJax.  If you are able to set the configuration of the page, you can do

```
MathJax.Hub.Config({
  TeX: {
    MultLineWidth: "100%"
  }
});
```

to change that.

**Comment by Nathan-Furnal** [comment]
Any update on this ? I'm also looking to do that !

**Comment by pkra** [comment]
The third party extension at https://github.com/AmerMathSoc/mathjax-xalign includes flalign.
