### ISSUE TITLE
[TeX fonts] upright lower case Greek letters missing

### ISSUE THREAD

**Issue by archels** [mathjax/MathJax#1076]
See https://github.com/mathjax/MathJax-docs/wiki/Non-italic-%28upright%29-greek-letters

**Comment by pkra** [comment]
Just for the record, that thread predates v2.3 which added more font options. E.g., STIX do have upright lower case Greek letters.

**Comment by archels** [comment]
Thanks for the info! Typing the character as unicode µ renders nicely when using the STIX-Web font. I'm not sure if it's possible to add support for \mathrm{\mu}, or whether this is desirable.

**Comment by pkra** [comment]
IUUC `\mathrm{\mu}` won't have the desired effect because `\mu` switches the font face back. You can use the Unicode character `μ` directy or build a custom macro using our Unicode macro `\unicode{x3BC}`.

**Comment by dpvc** [comment]
Version 3.2 includes the `upgreek` extension, which provides access to upright Greek letters from TeX.
