### ISSUE TITLE
Signal message doesn't always include DOM element that caused the problem

### ISSUE THREAD

**Issue by Klortho** [mathjax/MathJax#1082]
Background:

I've got a lot of TeX content that I'm trying to use Mathjax for, and there are a lot of things MathJax doesn't support.  I have a script that generates test pages, with a few hundred equations on each, and captures [MathJax signals](http://docs.mathjax.org/en/latest/signals.html) to find the errors. Per the example, I have a callback that takes the `message` argument, which is an array.

Problem:

I've found that only some of the `message`s contain a link back to the script that caused the problem. Specifically, "parse error" messages do; but "undefined control sequence" messages don't. (That's not an exhaustive list, obviously).

If it's easy, could you make the `message` array the same for all these types of errors?

**Comment by pkra** [comment]
Not a reply but have you looked at https://github.com/mathjax/MathJax-node?

**Comment by Klortho** [comment]
I hadn't seen it, that looks nice. It looks like a replacement for svgtex?

**Comment by dpvc** [comment]
It could be used as a substitute for svgtex, yes  MathJax-node includes command-line tools, and is designed so that it could serve as a back-end for a web service, though it doesn't include a server component itself.  Recently, one was made available by a third party, however.

**Comment by dpvc** [comment]
MathJax v3 no longer uses signals, so closing this issue.
