### ISSUE TITLE
Menu icons improvements

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1088]
Triggered by https://github.com/readium/SDKLauncher-iOS/issues/49

A few thoughts (that I apparently never posted on the tracker before)

* the icons do not show on IE8 (or IE6 for that matter)
* the icons do not show on Android Chrome (last I checked; the menu doesn't work well anymore)
* the icons force extra HTTP requests
* the icons make single-file builds slightly difficult 

So my propsal would be:

* switch to base64 encoding or straight to inline SVGs.

How does that sound?

**Comment by pkra** [comment]
Correction, I was looking at the wrong thing on IE and Android. It's the horizonta menu arrows that do not show on IE and Android; and those are done via Unicode (so it just means taht the VMs lack a font covering those Unicode points).

So I suppose another option is to switch to Unicode for the CloseX and the MenuArrow as well.

It seems this is a two liner -- inserting base64 URIs at these two locations.

* https://github.com/mathjax/MathJax/blob/55df93cdf8eb06d132613266f4ab8ca1d099f98a/unpacked/extensions/MathEvents.js#L48
* https://github.com/mathjax/MathJax/blob/55df93cdf8eb06d132613266f4ab8ca1d099f98a/unpacked/extensions/MathEvents.js#L48

We could also insert [plain SVG into the URI](https://css-tricks.com/probably-dont-base64-svg/) nowadays; fancy.

**Comment by pkra** [comment]
Ah, I did file the Android bug at #335

**Comment by dpvc** [comment]
Note that the MenuArrow is part of the discoverability interface, so isn't currently used in practice.  But both could due done as data URI's, certainly.  A straight SVG would not help the IE8 (or IE6) situation. 

An alternative to relying on the OS fonts is to use a small font as a data URI that contains the characters needed for the menus (the arrow, checkmark, x-mark, close-x, etc).  It would only need those characters, so could be pretty small.

**Comment by pkra** [comment]
> Note that the MenuArrow is part of the discoverability interface, so isn't currently used in practice.

Yes.

>  A straight SVG would not help the IE8 (or IE6) situation. 

Right. (data URIs also don't work on IE<8 without extra leg work).

> An alternative to relying on the OS fonts is to use a small font as a data URI that contains the characters needed for the menus (the arrow, checkmark, x-mark, close-x, etc).

Ah, cool idea! The trouble is that this won't work on IE8 (it can't handle data URIs for fonts).

I might play around with the ideas so far and make a PR.

**Comment by dpvc** [comment]
> Ah, cool idea! The trouble is that this won't work on IE8 (it can't handle data URIs for fonts).

Sigh.  Well, I think it does do data URIs for images, so one could use those for IE8, I guess.

**Comment by pkra** [comment]
>  Well, I think it does do data URIs for images, so one could use those for IE8, I guess. 

Yup, I have that set up and will test some before starting a PR. 

base64 adds ~1/3 of size due to the inefficient encoding. I'll see if I can find some smaller equivalent PNG (if that's ok). SVG would just be a few bytes...

**Comment by dpvc** [comment]
There was a reason that it was larger than displayed, but I no longer recall.  Presumably, it had to do with display quality on mobile devices at the time.  That has probably changed since then.  We could certainly scale down the current image (and change the CSS that controls it).

**Comment by pkra** [comment]
I think this is fixed? Do we need tests?

**Comment by dpvc** [comment]
Yes, it is merged at this point.  I don't think we need tests (and am not sure how to do a test for it anyway).

**Comment by pkra** [comment]
Awesome.
