### ISSUE TITLE
doesn't work on one page with firefox/chrome but works with safari/konqueror

### ISSUE THREAD

**Issue by mimoo** [mathjax/MathJax#1090]
Check my last article here: http://cryptologie.net/

And then click on the article: http://cryptologie.net/article/241/implementation-of-boneh-and-durfee-attack-on-rsas-low-private-exponents/

It's almost exactly the same page, except one displays the latex, the other not. Except the other page works on safari/konqueror

note that I had to use data-cfasync="false" to use it with cloudflare (I think you should advertise that in your landingpage) 
```
<script data-cfasync="false" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

**Comment by pkra** [comment]
Interesting. I see this on Chrome 41 as well. Hard-reloading the page (shift+F5) fixes the problem but normal reloading earlier or later does not.

In general, MathJax does not work well with Rocket Loader and similar optimization tools since such tools interfere with MathJax's own resource loader.

We'll look into it but if anybody knows how to debug Rocket Loader's behavior in general, we're interested in hearing about it.

**Comment by mimoo** [comment]
Sometimes I reload the page, or go to the page through a link and there latex is here. But then I refresh and it disappear. Really strange!

**Comment by dpvc** [comment]
it looks like Rocket Loader includes a rocket.js file into your page, and it seems to replace `<script>` tags with its own object class (presumably to handle the loading of scripts through the rocket loader channel).  Unfortnately, they don't implement their replacement in a fully compatible way, and so `script.text` does not return the text of the script.  MathJax uses scripts to store information about the mathematics on the page, and this mis-implementation by rocket.js causes MathJax to not be able to retreive the mathematics, and thinks all the math elements are blank.

I'm not sure why it works for some browsers and not others.  It may be that in some cases MathJax runs before rocket.js does and the script tags are not yet changed, and so it succeeds, while other times rocket.js runs first, and MathJax gets empty math strings.
