### ISSUE TITLE
How can I disable automatic rendering completely

### ISSUE THREAD

**Issue by ahmedmohiduet** [mathjax/MathJax#1096]
In my application I am showing mathematical notation with modal flashcards.I am trying to completely disable automatic rendering by setting skipStartupTypeset: true in config. But I found on each click on my divs it renders automatically all residing latex notation. I have removed all my MathJax.Hub.Queue(["Typeset",MathJax.Hub]); codes from my project. But still dont know how typesetting is triggered automatically?

I found that calling MathJax.Hub.Queue(["Typeset",MathJax.Hub]); too many times  my equations get displayed twice and sometimes vanishes. However this always happens with bootstrap modal divs. So for now I am trying to keep a flag and always call MathJax.Hub.Queue(["Typeset",MathJax.Hub]); myself.

**Comment by pkra** [comment]
If you set `skipStartupTypeset: true` then MathJax will not typeset (anything) automatically. So I suspect there's some other piece of code triggering MathJax. Without having a live sample, there's not much else to say.
