### ISSUE TITLE
Neo-Euler does not properly render text (uses math font instead).

### ISSUE THREAD

**Issue by mforbes** [mathjax/MathJax#1098]
When using the Neo-Euler font, constructs like the following are problematic: the surrounding text font should be used in each of these cases:

* Operators: ``\sin``
* Text boxes: ``\text{this is text}`` and ``\mathrm{this is also text}``
* Equations tags: ``\tag{this is text too}``

Here is what appears instead:

```latex
\int \mathrm{d}{x} \sin(x) = -\cos(x) + \mathrm{\text{h.c.}}  \tag{A simple identity}
```

![screen shot 2015-03-16 at 7 58 30 pm](https://cloud.githubusercontent.com/assets/1028433/6680626/45538d56-cc17-11e4-8522-ee6e0acce82e.png)

This is what it should look like (output from LaTeX with surrounding Palatino font)

![screen shot 2015-03-16 at 8 01 04 pm](https://cloud.githubusercontent.com/assets/1028433/6680638/5afea726-cc17-11e4-8cef-166c7daaef3a.png)

```latex
\documentclass{article}
\usepackage{mathpazo}
\usepackage[small]{eulervm}
\usepackage{amsmath}
\begin{document}
\begin{equation}
  \int \mathrm{d}{x} \sin(x) = -\cos(x) + \mathrm{\text{h.c.}}  \tag{A simple identity}
\end{equation}
\end{document}
```

**Comment by pkra** [comment]
This can be configured via `mtextFontInherit`, see http://docs.mathjax.org/en/latest/options/HTML-CSS.html

**Comment by mforbes** [comment]
Yes this works.  Why is ``mtextFontInherit`` false by default?

**Comment by pkra** [comment]
No problem. @dpvc will correct me but I think for the same reasons MathJax cannot support arbitrary fonts (see http://docs.mathjax.org/en/latest/font-support.html): the lack of bounding box information for arbitrary fonts means MathJax cannot ensure the layout is correct. I suspect this is less of a problem today than it was for v2.0 and in turn would only change at v3.0.

**Comment by mforbes** [comment]
Actually, there still seems to be a problem with operators like ``\sin`` and ``\ln`` (see below).  I think that ``\mathrm{}`` for Neo-Euler is using the math font when it should also use the surrounding text font.  ``\textrm{}`` works correctly as shown below in the ``d``, ``h.c.`` and the tag.

![screen shot 2015-03-17 at 3 47 20 pm](https://cloud.githubusercontent.com/assets/1028433/6699219/08f5a834-ccbd-11e4-8a17-ca667cab6b95.png)

**Comment by pkra** [comment]
>  I think that \mathrm{} for Neo-Euler is using the math font when it should also use the surrounding text font.

I think MathJax is replicating TeX/LaTeX behavior correctly here, i.e., it should be using the configured font in `\mathrm`.

Again, arbitrary fonts cannot be used with MathJax for lack of browser font APIs. At most, something like #1121 could help at some point.

**Comment by mforbes** [comment]
Where is ``\mathrm`` configured and how can I change that?  Whatever it is, it is critical that it is not the same as the math font since ``\cos`` is not ``c*o*s``.  The ``eulervm`` package for sure inserts the text font for operators.

**Comment by mforbes** [comment]
@pkra Should I open this as a new issue?  ``\mathrm`` should really not use the math font, even if it is upright as in Neo-Euler.
