### ISSUE TITLE
revisit annotation-xml support

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1105]
One of the more curious items from the backlog:
- embed annotations in a more HTML5 way (OpenAnnotation, ARIA, data-\* etc)

I think I added this before I realized that the OAWG does not specify a serialization. Probably falls into the "spec limitation" area.

**Comment by pkra** [comment]
This was partially fixed in v2.6 (MathML is now added as data attribute in the MathML if the AssitiveMML extension is present). I still like the idea and we might come back to this for the revamp of the menu.

**Comment by pkra** [comment]
There's also the context of the scholarly html W3C community group, there's schema.org microdata and RDFa.

**Comment by dpvc** [comment]
Can you say more about what annotations you have in mind?  Do you mean things like the original TeX code that is currently added in a <semantic> element in the MathML?

**Comment by pkra** [comment]
I was actually thinking that this should be closed as too vague / general. At the very least it should be a meta issue.

Anyway, iirc, this started out as a thought about the new OpenAnnotation spec and about the fact that annotation-xml does not fit together with other standards (like ARIA or data-*) and suffers from only having a chance to work on the web if browsers cared about MathML in the first place. (Of course that last point is now somewhat wrong since Chrome accepted code to add this weird behavior of rendering the first annotation-xml instead of MathML -- sigh.) 

Anyway, then I think I starte thinking about exposing things like sources in the data tags to make it easier to build tools on top of MathJax output without needing to understand its APIs. But there's also ARIA mentioned which now connects to the semantic enrichment project etc.

Hence my thought I should close this as not really an issue but a wide ranging topic of discussion.

**Comment by pkra** [comment]
Oh, and there's also a schema.org thread requesting some format for exposing mathematics. And this connects to things like the sorely outdated Units note from the MathWG and the siunitx&physics package etc.

**Comment by pkra** [comment]
https://github.com/schemaorg/schemaorg/issues/236

**Comment by dpvc** [comment]
> I start thinking about exposing things like sources in the data tags to make it easier to build tools on top of MathJax output without needing to understand its APIs.

This is one of the reasons I was thinking about pushing everything into the DOM for 3.0 (via elements that would be hidden from view, but that would contain the data in various forms needed by MathJax).

**Comment by pkra** [comment]
> This is one of the reasons I was thinking about pushing everything into the DOM for 3.0 (via elements that would be hidden from view, but that would contain the data in various forms needed by MathJax).

Right. I just have a different point of view on the "via elements" part, I think. For me, the data should to stay on the critical elements, i.e., the elements realizing the visual rendering. Something worth discussing with the TC once we're further along, I'm sure.
