### ISSUE TITLE
Improve CSS inheritance

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1107]
Improve CSS inheritance, e.g.,
- option to use getComputedStyle to map MathML stylesheets to MathJax output

**Comment by dpvc** [comment]
Note that `getComputedStyle()` causes page reflow, so this would have to be handle very carefully.  To make it with the fewest reflows, MathJax would have to build the MathML tree within the DOM for all the equations, then go through and to `getComputedStyle()` on every MathML element that it created, then remove all the MathML and build the HTML or SVG output using the cached style information.  That seems like a lot of overhead, but it could be done.
