### ISSUE TITLE
linebreaking for responsive design

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1110]
Ideas that could improve responsive design integration (e.g., as dedicated extensions).
- lazy typesetting after viewport size changes (tablet rotation etc)
- leveraging server-side preprocessing: using MathJax-node to produce MathML line-broken for desired viewport sizes, pick up viewport size before rendering, render the fitting equation

**Comment by doubtnut** [comment]
I would like to contribute in this feature  if it is still pending .  can any official confirm it ?

**Comment by v29neil** [comment]
I would like to contribute in this feature if it is still pending . can any official confirm it ?

**Comment by dpvc** [comment]
We have not done any work on this feature.  If you want to work on a third-party extension that implements one of Peter's ideas, or one of you own, then that would probably be useful for others.
