### ISSUE TITLE
investigate potential for local storage etc

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1113]
Ideas from the backlog.
- load components into local storage
- save rendering (or some helpful speed-up info) in local storage
  - XSS problems ensue

**Comment by pkra** [comment]
Looking at further discussions from elsewhere in the backlog, it seems like this should be dropped from the backlog.

**Comment by pkra** [comment]
By the above I meant the second bullet point in the OP (storing rendering data for the page). 

The first one (storing MathJax components) might still be worthwhile, e.g., for invalidating the cache during updates.

**Comment by qbolec** [comment]
Could you provide a link to the "elsewhere in the backlog" - I'm really interested in the reasons behind dropping this idea

**Comment by pkra** [comment]
Well, it is in the backlog (see the milestone here). The reason we haven't pursued this ourselves is a) lack of time b) lack of clarity (store what? Output? Components? Something in between?) and c) use cases.  We're happy to help anyone who wants to try something out though.

**Comment by lonelykid** [comment]
@pkra Sorry to bring this up. A use case would be if you have to re-render a page frequently. e.g. working on a markdown document with live preview. Caching output would be fine. Even latex compiler usually caches equation rendering output. But there might be other difficulty I'm not aware of?
Mathjax 3 is already much faster than Mathjax 2. So this functionality might not be worth the time to add though.

**Comment by pkra** [comment]
@lonelykid for caching output the main difficulty would be the stylsheet for CSS and the "font cache" for SVG as both grow over time. But just also store those in indexdb (or whatever) and inject them back in. It's not really hard, but not really something that belongs in the core, I think.
