### ISSUE TITLE
Add canvas output jax

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1125]
One of the more challenging items from the backlog.

**Comment by pkra** [comment]
Some more notes from the backlog.

* the SVG output would be a good place to start
* http://diveintohtml5.info/canvas.html#text

**Comment by nickkolok** [comment]
html2canvas is a way to do this in some browsers, but fractions sometimes look not good enough: they are truncated at bottom.

**Comment by friksa** [comment]
@pkra Would you accept a bounty on this one?  If so, how much?  Thanks!

**Comment by pkra** [comment]
> @pkra Would you accept a bounty on this one? If so, how much? Thanks!

We have never done bounties, I'm afraid. If you're looking for a developer to hire to contribute code, we might be able to suggest someone; feel free to contact me by email.

> I need MathJax formulas added to a FabricJs canvas.

You could connect MathJax's SVG output with FabricJS's `loadSVGFromString` but I guess it depends on what you really need.

**Comment by SlowBubble** [comment]
I am looking into converting SVG output into PNG using
1. the <img> HTML (https://stackoverflow.com/a/58142441)
2. canvg (https://canvg.github.io/canvg/demo/index.html).

For some SVG without Mathjax, both solutions work. But when I add in some Mathjax content, they failed.
1. img HTML refuses to load.
2. canvg simply skip the Mathjax content.

**Comment by SlowBubble** [comment]
Solution 1 actually works now, after removing 'xlink:' from 'xlink:href' from the MathJax SVG output:
https://jsfiddle.net/kxwj6agm/

**Comment by SlowBubble** [comment]
FYI, this is the MathJax version I'm using:
https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

**Comment by dpvc** [comment]
@SlowBubble, If you set the SVG output option `fontCache: 'none'`, then I think it will work in both situations for you.  This will avoid the xlink references entirely.  Using this output in the canvg and your jsfiddle both work for me, though the resolution of the resulting images is pretty poor.  You might get better results by scaling up the SVG to get a larger image, and then either scaling down in the browser (by setting what width to half the size, for example), or using an image tool like ImageMagick.  If you are able to do your processing via the command line (using node to dune MathJax, and any of the command-line based image conversion tools), that might get you better results as well.

**Comment by SlowBubble** [comment]
Good to know, thanks!
