### ISSUE TITLE
Meta: requested TeX packages

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1127]
- LaTeX macros for MathML constructs (e.g., mtable)
  - options for TeX packages to benefit from things that are easier in MathML, e.g, equalcolumns/rows
- braket
- siunitx [#447]
- Cyrillic macros [cf #1369]
- stmaryrd macros [#1143]
- bordermatrix (needs colspan/rowspan?; requested on various SE sites)
- [algorithmcx](http://www.ctan.org/tex-archive/macros/latex/contrib/algorithmicx/), [listings](http://ctan.org/pkg/listings)
  - google's prettify can guess programming languages. https://github.com/google/code-prettify
- babel macros (e.g., [Russian (see 6.4)](http://www.ctan.org/tex-archive/macros/latex/contrib/babel-contrib/russian) via twitter)
- fontpackages (stmaryd, wasysym etc) (via `\unicode`?)
-  Q-circuit (via xyjax?) see [this discussion](https://groups.google.com/forum/?fromgroups#!searchin/mathjax-users/macros/mathjax-users/ORLZ3Fm1qIs/8kNkSYz_XWgJ)
- mathapedia (pstricks)
- SageTeX + SageCell
- chemfig
- Feynman diagrams (cf. http://photino.github.io/jquery-feyn/index.html)
- improve handling of unicode characters (e.g., U+03B1 being treated as `\alpha`, and so on)
- something like `\turn[deg]{math}`, cf. http://ctan.org/pkg/rotating
- stix package (#1371)

**Comment by burnpanck** [comment]
For `siunitx`: see #447 and my unfinished implementation at https://github.com/burnpanck/MathJax-third-party-extensions/tree/add-siunitx-tex-extension.

**Comment by pkra** [comment]
Thanks, @burnpanck -- I've added a link in the OP.

**Comment by hpvd** [comment]
**+1 for units!**
Having perfect looking units at all there numbers with always the perfect space between number and unit but never a linebreak is one of the reasons engineers use latex!
And engineers would adore to have this on their websites too :-)
