### ISSUE TITLE
MathJax sporadically loading via CDN

### ISSUE THREAD

**Issue by BHouwens** [mathjax/MathJax#1133]
I'm having an issue where MathJax only sporadically loads via CDN. On occasions when it doesn't load, the console (in Chrome) displays `Failed to load resource: net::ERR_NAME_NOT_RESOLVED`. Is this due to something happening on my side, such as a bad connection?

Sometimes a refresh fixes this issue, sometimes it doesn't, and it occurs on a variety of browsers and operating systems.

**Comment by pkra** [comment]
Our provider is under attack; see https://groups.google.com/forum/#!topic/mathjax-users/kR6qnNLoiIA for updates.

**Comment by pkra** [comment]
For lack of a better alternative marking this "expected behavior" :-(

**Comment by BHouwens** [comment]
Okay great thanks! Hope it gets sorted soon

**Comment by pkra** [comment]
This was resolved according to our CDN hoster. We hope this problem has disappeared.
