### ISSUE TITLE
CHTMLpreview should detect IE<8 [was: MathJax 2.5 has broken IE 6/7 compatibility on Windows XP/Vista (v2.4 works, Win 7+ okay)]

### ISSUE THREAD

**Issue by thomastan** [mathjax/MathJax#1137]
Math is getting replaced with _[Math Processing Error]_'s.

IE 8 on XP/Vista/7+ is fine. Problem is occurring on http://math.stackexchange.com/questions as well as my own site.  I previously had a problem with IE 6-8 in v2.3 which got a speedy fix: mathjax/MathJax#672

Problems on: IE 6 XP; IE7 XP; IE7 Vista. IE8+ is unaffected.

**Comment by pkra** [comment]
Can you try deactivating the Fast Preview mode via the MathJax menu? That mode is the default on stackexchange but does not support IE6/7.

**Comment by thomastan** [comment]
That works. I also loaded in `menuSettings: { CHTMLpreview: false }` to my own sites and math rendering has been restored.

Since Fast Preview is broken in IE 6-8, can we make it disabled by default on those browsers and enabled on others?  Otherwise, MathJax is not backwards compatibility with existing sites (when using IE 6-8).  Moreover, even though the `CHTMLpreview: false` configuration setting can be added to existing sites, it will disable Fast Preview on browsers that do support it. Keeping it enabled depending on the browser is possible through JavaScript on the website side, but this is better if done in MathJax, especially since MathJax already does IE detection.

**Comment by pkra** [comment]
> Since Fast Preview is broken in IE 6-8 [...]

There's nothing broken here. The FastPreview does not support IE<8 (much like the SVG output does not support IE<9). The difference is that in v2.5+ the pre-compiled configuration files include the CHTML extension. Keep in mind that the purpose of the pre-compiled configuration files is not to be the ideal solution but to provide a good baseline to build upon -- almost all authors tweak the configuration one way or another. 

> can we make it disabled by default on those browsers and enabled on others?

I've renamed the issue and labeled this a feature request. PRs are always welcome.

**Comment by dpvc** [comment]
It turns out that the problem in IE < 8 is in the `CHTML-preview.js` file where it sets the color to `"inherit"`.  Apparently, this is not supported in IE < 8, and rather than failing silently (as it would in CSS), IE throws an error when you set the value.  So rather than disabling the preview, that change could be made conditional.  

Of course, IE < 8 doesn't handle some of the CSS that CommonHTML uses, so the results of the preview can be pretty jumbled.  So perhaps disabling it is the right thing.

**Comment by dpvc** [comment]
@pkra, do you have any thoughts on my comment above?  A small change to `CHTML-preview.js` allows the CHTML preview to run in IE < 8 (though the results are not great).  Is it better to run the preview and allow it to show what it can, or to disable it entirely?  It might also be possible to improve the results for IE < 8 by not using certain kinds of CSS selectors.

**Comment by pkra** [comment]
Making the new output better on IE <8 seems the wrong direction; disabling it makes more sense.

**Comment by dpvc** [comment]
OK. Should this be part of 2.5.2?

**Comment by pkra** [comment]
SGTM.

**Comment by dpvc** [comment]
==> Merged
