### ISSUE TITLE
form input with HTML-CSS  in 2.5+

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1139]
I was updating https://github.com/mathjax/MathJax-docs/wiki/MathJax-and-form-input and it looks like the HTML-CSS output does not handle this trick well in 2.5+. Probably due to the dropped measurements. Not sure if there's an easy fix. SVG output and `dpvc/chtml` look good so not a high priority, I think.

**Comment by dpvc** [comment]
I came across this last week when working on the corresponding part of CommonHTML, and fixed it in the develop branch.  I hadn't pushed the change, but have done so.  You are correct that it was due to the lack of measuring.

**Comment by dpvc** [comment]
==> In test suite.
