### ISSUE TITLE
Mathjax error [Math Processing Error]

### ISSUE THREAD

**Issue by lovesh** [mathjax/MathJax#1142]
I am using mathjax with require.js. My mathjax url looks like this(i am using the latest version)
http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full&amp;delayStartupUntil=configured

I get the error `[Math Processing Error]` when my mathml is 
```
<math display='block'>
 <mrow>
  <mrow><mo>|</mo> <mrow>
   <mover accent='true'>
    <mi>a</mi>
    <mo stretchy='true'>&#x2192;</mo>
   </mover>
   </mrow> <mo>|</mo></mrow><mo>=</mo><mn>3</mn></mrow>
</math>
```

When i look in the console i see this error

```
Uncaught TypeError: Cannot read property 'hover' of null   TeX-AMS-MML_HTMLorMML-full.js?rev=2.5.1:54

c.Event.ContextMenu                                     TeX-AMS-MML_HTMLorMML-full.js?rev=2.5.1:54 

c.Event.Handler                                              TeX-AMS-MML_HTMLorMML-full.js?rev=2.5.1:54 

c.Event.Menu                                                  TeX-AMS-MML_HTMLorMML-full.js?rev=2.5.1:54 
```

But when i change my mathjax  version to 2.4-latest so that the url is
http://cdn.mathjax.org/mathjax/2.4-latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full&amp;delayStartupUntil=configured
the `[Math Processing Error]` is no longer there and i can see the equation.
I have encountered several problems with Mathjax and a lot of them vanish when i switch the version from 2.4-latest to latest(which is 2.5) or vice versa. Which is the recommended version of MathJax?

**Comment by pkra** [comment]
Can you share a live sample?

**Comment by lovesh** [comment]
I have already shared the mathml. I am sorry i dont have a public webpage where i see this error.

**Comment by pkra** [comment]
The MathML sample works fine on http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html so the problem very likely lies elsewhere. Without a minimal example reproducing the problem (e.g., hosted on jsbin, codepen etc) there's not much we can do.

**Comment by lovesh** [comment]
Ok i will try to upload a jsbin shortly. But what is the recommended version of mathjax?

**Comment by pkra** [comment]
We always recommend the latest version -- v2.5.1 is the current release, https://github.com/mathjax/MathJax/releases.

The biggest change betwen 2.4 and 2.5 was the introduction of the fast preview mode and a new output that drives this. Please check https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports for some general advice on what kind of information we need.
