### ISSUE TITLE
Basic demo page does not work in Safari 8.0.4 / Mac

### ISSUE THREAD

**Issue by rblazek** [mathjax/MathJax#1146]
The "Getting Started" page in the docs refers to a basic example which is located at http://cdn.mathjax.org/mathjax/2.1-latest/test/sample-tex.html

This demo does not work correctly in Safari 8.0.4 on Mac (the latest as of today). The square root is missing the horizontal line over the expression (b^2-4ac) inside it. See the screenshot.

Thanks
Rudy

![screen shot 2015-03-31 at 3 06 57 am](https://cloud.githubusercontent.com/assets/6569904/6910429/1eee9f38-d753-11e4-8f82-954703c0fd5f.png)

**Comment by pkra** [comment]
MathJax v2.1 is over 2 years old, in particular, much older than Safari 8. Please try the latest version of MathJax.

**Comment by rblazek** [comment]
I understand, but I wonder how I can use a different version of MathJax on YOUR OWN documentation web site. Maybe someone should review and fix your site. Here is how you replicate the problem:

1. Go to http://www.mathjax.org
2. Click on "Documentation" (http://www.mathjax.org/#docs)
3. Click on "Check our overview" (http://docs.mathjax.org/en/latest/misc/browser-compatibility.html)
4. Click on "Getting Started with MathJax" (http://docs.mathjax.org/en/latest/start.html)
5. Click on "Putting mathematics in a web page" (http://docs.mathjax.org/en/latest/start.html#putting-mathematics-in-a-web-page)
6. Scroll down to find the text "Here is a complete sample page containing TeX mathematics (also available in the test/sample-tex.html file)"
7. Click on the "test/sample-tex.html" link (http://cdn.mathjax.org/mathjax/2.1-latest/test/sample-tex.html)
8. Another example is a bit lower: "Here is a complete sample page containing MathML mathematics (also available in the test/sample-mml.html file)" (http://cdn.mathjax.org/mathjax/2.1-latest/test/sample-mml.html)

The two offending pages I have found are listed below, but there might be more:
http://cdn.mathjax.org/mathjax/2.1-latest/test/sample-tex.html
http://cdn.mathjax.org/mathjax/2.1-latest/test/sample-mml.html

I am just trying to help.
Rudy

**Comment by pkra** [comment]
Ah! Thanks for catching that! That's a bug in our documentation -- I've opened https://github.com/mathjax/MathJax-docs/issues/99 to track it.

Thanks again for following up.

**Comment by rblazek** [comment]
Glad it helped. 

Best of luck
Rudy
