### ISSUE TITLE
Self-closing tags not detected correctly

### ISSUE THREAD

**Issue by danez** [mathjax/MathJax#1177]
We have a mathml markup like this:
```
<m:math alttext="{}_{\rm Y}" display="inline" xmlns:m="http://www.w3.org/1998/Math/MathML">
<m:msub><m:mi/><m:mi mathvariant="normal">Y</m:mi></m:msub>
</m:math>
```

MathJAX is then rendering this in our case in Google Chrome:

![bildschirmfoto 2015-04-29 um 12 41 43](https://cloud.githubusercontent.com/assets/231804/7389333/3c056634-ee6d-11e4-8f9a-9980973866a6.png)

(I added red boxes around the invalid rendering)

When I do "Show Math" ->  "as original Mathml" in the menu I get:
```
<m:math alttext="{}_{\rm Y}" display="inline" xmlns:m="http://www.w3.org/1998/Math/MathML">
                        <m:msub>
                           <m:mi>
                           <m:mi mathvariant="normal">Y</m:mi>
                        </m:mi></m:msub>
                     </m:math>
``` 
Which is obviously not the same as the input.

When I change the Input to (no self-closing tag)
```
<m:math alttext="{}_{\rm Y}" display="inline" xmlns:m="http://www.w3.org/1998/Math/MathML">
<m:msub><m:mi></m:mi><m:mi mathvariant="normal">Y</m:mi></m:msub>
</m:math>
```
It works.

**Comment by davidcarlisle** [comment]
On 29 April 2015 at 12:12, Daniel Tschinder <notifications@github.com>
wrote:

> We have a mathml markup like this:
>
> <m:math alttext="{}_{\rm Y}" display="inline" xmlns:m="http://www.w3.org/1998/Math/MathML">
> <m:msub><m:mi/><m:mi mathvariant="normal">Y</m:mi></m:msub>
> </m:math>
>
>
>
Irrespective of mathjax that should parse as intended if served as
application/xml or another XML mime type
if served as text/html the HTML parser is specified as treating /> the same
as >
so it will nest the mi closing them both at the </m:msub


To get XML style interpretation of /> with an HTML parser then you need to
use <math> (or <svg>)
with no prefix, as just those two element names are defined to trigger the
"foreign content" handling.

David

**Comment by pkra** [comment]
@davidcarlisle's reason is correct. MathJax can only access what the browser puts in the DOM and the browser modifies this before MathJax ever gets to it. Nothing we can do about it unless you want to pre-process yourself and use our custom script tags.

See also our docs.

* http://docs.mathjax.org/en/latest/mathml.html#mathml-in-html-pages
* http://docs.mathjax.org/en/latest/model.html#how-mathematics-is-stored-in-the-page

**Comment by danez** [comment]
Thanks, I see

**Comment by dpvc** [comment]
In addition to David and Peter's suggestions, another alternative would be to use `<m:mi></m:mi>` instead.
