### ISSUE TITLE
How to target specific version on CDN

### ISSUE THREAD

**Issue by scaljeri** [mathjax/MathJax#1178]
Today our formula rendering seems to be broken and I think that it might have todo with the new version of MathJax released yesterday. Currently we load MathJax as follows:

    <script src="//cdn.mathjax.org/mathjax/latest/MathJax.js?delayStartupUntil=configured"></script>

Now I would like to load v2.5.1 (I assume that latest here is v2.5.2). I've tried things like

    <script src="//cdn.mathjax.org/mathjax/2.5.1/MathJax.js?delayStartupUntil=configured"></script>

but that doesn't work. Is the version notation incorrect or is this just not possible ?

**Comment by pkra** [comment]
There's no way, I'm afraid, since we do not differentiate patch versions on the CDN, just minor versions.

If there's a bug, could you report it please?

**Comment by scaljeri** [comment]
Here is a demo of the issue we have: http://jsfiddle.net/1hLvdbm2/

I haven't tested this problem agains an older version of MathJax yet, but because we see this problem since today, I assumed that it might have todo with the new version!

**Comment by pkra** [comment]
This seems to be a timining issue. Could you file a new issue please?

**Comment by scaljeri** [comment]
done: https://github.com/mathjax/MathJax/issues/1179
