### ISSUE TITLE
mmultiscripts with odd number of post-scripts doesn't render correctly

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1188]
If the number of post-scripts in an `<mmultiscripts>` element is odd, then the pre-scripts are rendered to the right (i.e., the `<mprescripts/>` acts as `<none/>`).  E.g.

``` html
<mmultiscripts>
<mi>X</mi>
<mi>a</mi><mi>b</mi>
<mi>c</mi>
<mprescripts/>
<mi>x</mi><mi>y</mi>
<mi>z</mi>
</mmultiscripts>
```

puts all the scripts as post-scripts.  I.e.,

```
  b y
X
  acxz
```

**Comment by pkra** [comment]
I wasn't sure when we want to fix this so I added it to the 2.6 milestone (so that we don't forget about it but can move it out again when 2.6 is finalized)

**Comment by dpvc** [comment]
This is resolved in the `issue1188` branch of my fork of MathJax for both HTML-CS and SVG output.  Also corrected in the CommonHTML output in the `chtml` branch.

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> in testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mmultiscripts/issue1188.html
