### ISSUE TITLE
Autonumbering and binomial coefficient

### ISSUE THREAD

**Issue by Kaba2** [mathjax/MathJax#1194]
In the TeX converter, using autoNumber: "all" garbles the binomial coefficient \binom{k}{i}:

![binomial](https://cloud.githubusercontent.com/assets/2399754/7787480/e0fef17a-0216-11e5-9bd9-ed760c69a21d.png)

There is even an additional equation number. The source is:

    <script type="math/tex; mode=display">\binom{k}{i}</script>

The problem is fixed by removing autoNumber: "all".

**Comment by pkra** [comment]
Thanks for reporting. Please check https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md for future reports.

@dpvcs I can reproduce this on FF38 and Chrome 43 with http://jsbin.com/qiyucagume/2/edit. Both HTML-CSS and SVG output are affected. I'm guessing this is a problem with mathchoice?

**Comment by dpvc** [comment]
It's actually not the `\mathchoice` directly, but the handling of a parsing process internally to setting up the `\mathchoice` calls for the parentheses.  Here is a temporary work-around: put

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {Augment: {
    mathPalette: function (fence,side) {
      if (fence === '{' || fence === '}') {fence = "\\"+fence}
      var D = '{\\bigg'+side+' '+fence+'}', T = '{\\big'+side+' '+fence+'}';
      return MathJax.InputJax.TeX.Parse('\\mathchoice'+D+T+T+T,{}).mml();
    }
  }}
});
</script>
```

before the script that loads `MathJax.js` itself.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> in testsuite

LaTeXToMathML/references/issue1194.html
