### ISSUE TITLE
First use of macro fails

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1195]
This page

http://cdi2tp.math.tecnico.ulisboa.pt/mathjax_test.php

defines several macros (very simple to allow for Portuguese of common mathematical functions). One of them is \sen. The first use of the macro (on the formula on the line following the line starting with "Tomemos para parametrização") fails and nothing is shown. Latter usage works.

This is hard to reproduce or include in a minimal example as a one line page with just one use of the macro seems to work. It has been observed in other pages with relatively complex content.

This happens with version 2.5 latest updated today.

This is observed in the current versions of Firefox, Opera and Chrome on Linux and Windows. Also on IE11.

**Comment by dpvc** [comment]
You macros are defined incorrectly.  You have

```
Macros: {
  sen: "{\\newcommand{\\sen}{\\operatorname{ sen}}}",
  tg: "{\\newcommand{\\tg}{\\operatorname{ tg}}}",
  arctg: "{\\newcommand{\\arctg}{\\operatorname{ arctg}}}",
  div: "{\\renewcommand\\div{\\operatorname{ div}}}"
},
```

which make `\sen` expand to `\newcommand{\sen}{\operatorname{ sen}`, so the first use of `\sen` redefines `\sen` to be `\operatorname{ sen}`, with no output.  So MathJax is doing exactly what it is supposed to.  What you probably want is

```
Macros: {
  sen: "\\operatorname{sen}",
  tg: "\\operatorname{tg}",
  arctg: "\\operatorname{arctg}",
  div: "\\operatorname{div}"
},
```

which makes `\sen` produce `\operatorname{sen}` for its first (and all subsequent) uses.
