### ISSUE TITLE
subscripts in inline mode with \varprojlim, \varinjlim, ... , \mathop

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1197]
With \varprojlim, \varinjlim, \varliminf and \varlimsup, MathJax places a subscript below the symbol for inline math as well as displays, but shouldn't it move to the right for inline mode?

It appears that \mathop behaves like this in some inline contexts, too.

See http://jsfiddle.net/w29nnjok/

**Comment by pkra** [comment]
Yes, that's a bug. Thanks for concise report!

**Comment by dpvc** [comment]
The `issue1197` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> In test suite

LaTeXToMathML/issue1197.html
