### ISSUE TITLE
Cherry pick 'Round height and depth of final SVG...' to branch MathJax-node-2.5.1

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax#1201]
In https://phabricator.wikimedia.org/T34694 @gwicke proposed a change to enhance the SVG rendering. The same change was already done in the current development branch.
@pkra Do you think it's a good idea to just cherry pick that change (
https://github.com/mathjax/MathJax/commit/c5b2aa2515259020c5b319d6cb82af4014bb0108)  or would it be better to create mathjaxnode252 instead?

**Comment by pkra** [comment]
I don't know. @dpvc what do you think?

**Comment by dpvc** [comment]
The commit in question isn't part of 2.5.2, it is only in `develop` at the moment, so creating a 2.5.2 MathJax-node branch won't help.

If they want to cherry pick that one commit into their own fork, that should work, as the change does not depend on anything else from `develop`.
