### ISSUE TITLE
after the math is typeset, a copy of the latex code is typeset next right to it

### ISSUE THREAD

**Issue by timbusken** [mathjax/MathJax#1206]
The math renders okay, but then after the math is typeset, a copy of the latex code is typeset next right to it. Please advise...

Here is my jsfiddle

http://jsfiddle.net/timbusken1/uL8gqu3r/

**Comment by pkra** [comment]
This looks like bad JS interaction. Something is turning MathJax's script elements into regular nodes which leads to the duplication. I'd try to build a more minimal example; my guess would be that the DOM is being re-arranged by the search tool while MathJax is trying to typeset and this screws up the DOM, so a bit of synchronization between the different libraries should fix it.

**Comment by timbusken** [comment]
Hi Peter

Thanks so much again for looking at the code!! I was able to find the offensive code snippet in my css. 
tb

**Comment by pkra** [comment]
Thanks for the update, @timbusken. Glad to hear you could fix it.
