### ISSUE TITLE
reconfigure a page?

### ISSUE THREAD

**Issue by grofit** [mathjax/MathJax#1213]
I have a scenario where the math symbols used may change without a postback/page refresh, so is there a way after mathjax has been configured to reconfigure it with new values or to delete the existing mathjax instance and create a new one with a new configuration?

**Comment by dpvc** [comment]
I doubt that you really need to clear out MathJax and load it again.  You probably just need to tell it to look through the page for new math to typeset.  Read the documentation on [dynamic pages](http://docs.mathjax.org/en/latest/typeset.html) in MathJax, and see if that doesn't tell you what you need to know.

**Comment by pkra** [comment]
>  is there a way after mathjax has been configured to reconfigure it with new values

Could you be more specific as to what you need to reconfigure?

**Comment by grofit** [comment]
mainly it was the tags being used for latex content, but I have found a way to sidestep the issue, so it is no longer a problem.

**Comment by pkra** [comment]
> mainly it was the tags being used for latex content,

I'm not sure I understand what you mean by that.

> I have found a way to sidestep the issue

Ok.

**Comment by grofit** [comment]
```
MathJax.Hub.Config({
        jax: ["input/TeX", "output/SVG"],
        extensions: ["tex2jax.js"],
        tex2jax: {
            displayMath: [ ['$$','/$$'] ],
            processClass: "latex-section"
        },
        SVG: { scale: 150 }
    });
MathJax.Hub.Configured();
```
So that there will look for `$$somemath/$$`, but now lets say I then change flavours and need to support `{$$}somemath{/$$}`, I was wanting to be able to change the `text2jax` config (and potentially other config vars) at runtime.

**Comment by pkra** [comment]
@dpvc what do you think?

**Comment by dpvc** [comment]
Some items can be reconfigured on the fly.  The `tex2jax` delimiters are one of them, so you can start with `displayMath: [['$$','/$$']]`, and later do

    MathJax.Hub.Config({tex2jax: {displayMath:[['{$$}','{/$$}']]}});

Then the next `MathJax.Hub.Queue(["Typeset",MathJax.Hub])` will use the new delimiters.  Note however, that if your page contained both `$$somemath/$$` and `{$$}some math{/$$}` initially, the initial delimiters of $$.../$$ would match *both* of these (and the math would be `}some math{` in the second case, which would produce an unbalanced brace error).  So you do have to be a little careful about switching the delimiters if you aren't replacing the text that is being processed.

Alternatively, you can include both sets of delimiters initially,

    displayMath: [['$$','/$$'],['{$$}','{/$$}']],

and both would be found correctly (the search algorithm will match the longer delimiter first).

**Comment by grofit** [comment]
thats good to know, can SVG scale be changed too?

**Comment by dpvc** [comment]
Yes, if you change `SVG: {scale: nnn}` the next typeset will use the new scale factor.

**Comment by grofit** [comment]
brilliant, those are the 2 main things I cared about, thanks for the info guys.
