### ISSUE TITLE
semi-slim official mathjax for bower

### ISSUE THREAD

**Issue by minrk** [mathjax/MathJax#1214]
It's great to see the ability to install mathjax as a dependency with bower. Unfortunately, one consequence of this is that the majority of our install time is now bower extracting the mathjax tarball, and it seems a lot of this is the image fonts, which we don't actually use. I am aware of [the guide](https://github.com/mathjax/MathJax-docs/wiki/Guide%3A-reducing-size-of-a-mathjax-installation), which we use to slim the deployments, but doesn't help us at the bower stage.

Is there a reasonable way to make an official slightly-slim "modern browsers" release that excludes the really heavyweight parts of the repo only needed by old browsers, such as the image fonts? It would be great if there were an official bower package that doesn't take minutes to extract.

**Comment by pkra** [comment]
We plan to drop the picture fonts (which I suspect is the root of the problem) and possibly restructure our repositories for v3.0 next year but that's quite a while away.

In the mean time, I don't know how we could accomplish this, practically speaking. IIUC, bower picks up on git tags and fetches the corresponding archive. That would mean we would have to provide extra tags/branches stripped of the PNG fonts; this seems problematic to me. If anyone knows a practical way around this, please share.

**Comment by minrk** [comment]
@pkra for popular projects that have build steps or large source repos, it is common to make a dedicated repo on the [components org](https://github.com/components). It doesn't have to be there, it could be another repo on your own org. This does add a maintenance burden to you folks, since you have to push everything minus whatever is slimmed out to a different repo on each release. I'd be happy to take responsibility for that if you would like the help, or I can wait for 3.0. I would prefer that someone more official decide what's appropriate to slim out, though.

Then users would depend on `components/MathJax#~2.5` instead of `MathJax#~2.5` if they want the slim repo.

**Comment by pkra** [comment]
>  it is common to make a dedicated repo on the components org

Ah! That's nifty.

>  I'd be happy to take responsibility for that if you would like the help,

Thank you for offering!

> I would prefer that someone more official decide what's appropriate to slim out, though.

That's a separate discussion, I suppose. I suspect that the PNG fonts will be enough (it's usually the number of files that's the bottleneck but it also brings down zip size) but the `unpacked` folder might be dropped as well for bower? One caveat might be that even on modern browsers the PNG fonts can be useful (e.g., when users block webfonts); ideally, when the PNG font is dropped, the MathJax configuration should reflect that. (There's also #878)

@dpvc @zorkow what do you think?

**Comment by dpvc** [comment]
I don't have a problem with having a components repo, but I'm just not sure what slimmed-down version should be used.  One equivalent to the TeX-AMS_HTML configuration?  Or the MML_HTMLorMML configuration?  Or TeX-AMS-MML_HTMLorMML?  Or something new?

If it is just the removal of the image fonts and the unpacked stuff, that would give the most flexibility, but  still leaves a larger-than-needed install for many people.

I'm not sure what is best.

**Comment by pkra** [comment]
> I don't have a problem with having a components repo, 

Me too :-)

> but I'm just not sure what slimmed-down version should be used. 

Me too :-(

> If it is just the removal of the image fonts and the unpacked stuff, that would give the most flexibility, but still leaves a larger-than-needed install for many people.

@minrk you described "extracting the tarball" as the bottleneck, which would indicate the PNG fonts are enough (and the unpacked possible icing on the cake). Is that just a reasonable guess or have you tested this by any chance?

**Comment by minrk** [comment]
I will do some benchmarks to be sure, but based on my understanding just removing the image fonts would produce enough of an improvement that leaving everything else is okay for flexibility. I think it's diminishing returns after that.

**Comment by minrk** [comment]
I ran [this simple benchmark](https://gist.github.com/317ea4365398440d3e0a) and found that ~65-80% of the unpacking time is spent on the png fonts.

**Comment by minrk** [comment]
And I pushed a copy of mathjax minus png fonts to a [temp repo](https://github.com/minrk/mathjax-component), which can be tested with:

```
$> time bower install MathJax#2.5.3
bower MathJax#*                 cached git://github.com/mathjax/MathJax.git#2.5.3
bower MathJax#*               validate 2.5.3 against git://github.com/mathjax/MathJax.git#*
bower MathJax#~2.5.3           install MathJax#2.5.3

MathJax#2.5.3 bower_components/MathJax

real	1m1.699s
user	0m41.793s
sys	0m23.146s

$> time bower install minrk/mathjax-component#2.5.3
bower mathjax-component#2.5.3   cached git://github.com/minrk/mathjax-component.git#2.5.3
bower mathjax-component#2.5.3 validate 2.5.3 against git://github.com/minrk/mathjax-component.git#2.5.3
bower MathJax#2.5.3            install MathJax#2.5.3

MathJax#2.5.3 bower_components/MathJax

real	0m9.643s
user	0m7.677s
sys	0m2.599s
```

So again, that's about an 85% reduction in install time, just by removing the png fonts. Those times are after the first run, so the download has been cached. I'm not entirely sure what bower does that makes it take so long beyond extracting the tarball. Maybe it extracts to a temp location then copies the whole thing, which would be particularly rough given MathJax's uncompressed size and file count. 

This would also be nice because there are a few dev operations that stat the whole file tree, which would be significantly improved if the png files were absent.

**Comment by pkra** [comment]
@minrk awesome! Thanks for investigating this further! Would you say that the gain is sufficient?

**Comment by minrk** [comment]
I think it is. It makes a pretty big difference for my usage, anyway.

**Comment by pkra** [comment]
Yay. Let's work this out then. 

I think all this would entail is 

a) drop the PNG folder
b) change https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/HTML-CSS/config.js#L44 to `null`.

Seem like adding https://www.npmjs.com/package/grunt-regex-replace to https://github.com/mathjax/MathJax-grunt-cleaner and creating a specialized task should do the trick?

**Comment by pkra** [comment]
Or whatever else you want, @minrk, if you're still offering to maintain the components.org copy.

**Comment by jasongrout** [comment]
+1 to having the component @minrk describes above, with just the png fonts gone.  I've wanted this a long time, and I'm glad to see it will be happening.

**Comment by minrk** [comment]
I opened mathjax/MathJax-grunt-cleaner#5 which does the cleaning you described. I haven't received a response on components/components#35 to create the repo, yet, but hopefully they will let me create a repo over there. I'm already a maintainer on a couple. If for some reason they don't or are slow, we could always make the component repo on the mathjax org.

**Comment by minrk** [comment]
I've made a [simple script](https://github.com/minrk/mathjax-component-builder) to easily keep the component repo up-to-date once it exists. In the meantime, I'm pushing the results [here](https://github.com/minrk/components-mathjax).

**Comment by pkra** [comment]
Thanks again, @minrk! We really appreciate the initiative and your help!

**Comment by minrk** [comment]
You can now `bower install components/MathJax`

**Comment by pkra** [comment]
:tada: :fireworks: :+1: 

Thank you for pushing this forward (and through), @minrk!
