### ISSUE TITLE
can i get the SVG string?

### ISSUE THREAD

**Issue by macarthor** [mathjax/MathJax#1215]
hi community,

i wonder if i could get the mathjax output SVG as a string? such as `<svg>xxxxxx</svg>`.

i wanna do this because i wanna cache the formula SVG in my APP, so that the user can read some content while offline.

many thx~

**Comment by pkra** [comment]
That's not enough information to go on, I'm afraid. Since you [double posted on the MathJax User Group](https://groups.google.com/forum/#!topic/mathjax-users/ZmECrLI9F_M), please provide more details over there.

**Comment by macarthor** [comment]
@pkra hi, i'm developing an android app which render formula in a webview with mathjax.

here's a code snippet:

'''
String mathml =
    "<script type='text/x-mathjax-config'>\n" +
    "    MathJax.Hub.Config({\n" +
    "        showMathMenu: false,\n" +
    "        jax: ['input/MathML','output/SVG'],\n" +
    "        extensions: ['mml2jax.js'],\n" +
    "        TeX: { extensions: ['noErrors.js','noUndefined.js'] },\n" +
    "        'SVG' : { scale: 300, blacker: 30, styles: { path: { 'shape-rendering': 'crispEdges' } } }\n" +
    "    });\n" +
    "    MathJax.Hub.Queue(\n" +
    "        function () {\n" +
    "            var jax = MathJax.Hub.getAllJax()[0]; if (!jax) return;\n" +
    "            var svg = jax.SourceElement().previousSibling.getElementsByTagName(\"svg\")[0];\n" +
    "            svg.setAttribute(\"xmlns\",\"http://www.w3.org/2000/svg\");\n" +
    "            console.log(\"svg innerHTML = \" + svg.innerHTML);" +
    "            console.log(\"svg outerHTML = \" + svg.outerHTML);" +
    "            var svgdata = svg.outerHTML.replace(/><([^/])/g,\">\\n<$1\").replace(/(<\\/[a-z]*>)(?=<\\/)/g,\"$1\\n\").replace(/(<use [^>]*)(href=)/g,' $1xlink:$2');\n" +
    "            console.log(\"svg = \" + svgdata);\n" +
    "        }\n" +
    "    );" +
    "</script>\n" +
    "<script type='text/javascript' src='MathJax/MathJax.js'>\n" +
    "</script>\n" +
    "\n" +
    "<math xmlns=\"http://www.w3.org/1998/Math/MathML\"> <msqrt> <mi>x</mi> </msqrt> </math>";

mWvFormula.loadDataWithBaseURL("file:///android_asset/", mathml, "text/html", "UTF-8", "");
'''

in logcat, i can see:

'''
"svg innerHTML = undefined", source:  (14)
"svg outerHTML = undefined", source:  (14)
'''

but the '''svg.setAttribute''' is executed, so the '''svg''' DOM object is successfully obtained from mathjax output, i think.

i wonder what to do to get the svg string or file.

**Comment by dpvc** [comment]
It may be that SVG elements don't implement innerHTML and outerHTML (since they are in the SVG namespace not the HTML one), so you might try `svg.parentElement.innerHTML` and see if that gets you what you want.
