### ISSUE TITLE
Disable menu and transform only a part of the page

### ISSUE THREAD

**Issue by artur99** [mathjax/MathJax#1218]
Is there any way to disable the contextual menu opened from the right click?
And also how to transform to visual equation only the latex from a div with the class .equation?

Thank you!

**Comment by pkra** [comment]
> Is there any way to disable the contextual menu opened from the right click?

See http://docs.mathjax.org/en/latest/options/hub.html => `ShowMathMenu: false`

> And also how to transform to visual equation only the latex from a div with the class .equation?

See http://docs.mathjax.org/en/latest/options/tex2jax.html => combine `ignoreClass` or`skipTags` with `processClass`.

**Comment by artur99** [comment]
<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        ShowMathMenu: false,
        extensions: ["tex2jax.js"],
        jax: ["input/TeX", "output/HTML-CSS"],
      });
    </script>
    <script type="text/javascript" src="../MathJax.js"></script>

This will still show the menu

**Comment by pkra** [comment]
>  jax: ["input/TeX", "output/HTML-CSS"],

Try removing the trailing comma. If that does not fix it, please create a live sample.

**Comment by artur99** [comment]
Same thing... This is my full code:

http://pastebin.com/9Y3rFBUS

**Comment by pkra** [comment]
Oh well, RTFM at myself. `showMathMenu` not `ShowMathMenu`.

**Comment by artur99** [comment]
Thank you so much! It works :D

But the second one is now the problem... :D

    MathJax.Hub.Config({
      showMathMenu: false,
      extensions: ["tex2jax.js"],
      jax: ["input/TeX", "output/HTML-CSS"],
      tex2jax: {
          skipTags: ["body"],
          processClass: "equation"
      }
    });

This won't build any equation... If I change to `["html"]` insetead of `["body"]`, it will build all the equations on the page :(

**Comment by artur99** [comment]
And now not even this is working: http://pastebin.com/CsVafveA :(

**Comment by pkra** [comment]
Ah, that's not how it works. If you use `skipTags` then `processClass` only disables the skipping on those tags. I.e., skipping divs and then adding a class to prevent the skip. So this approach doesn't work if you're using body or html.

One way around this is to ignoreClass everything (including empty class names).

```
      ignoreClass: ".\*",
      processClass: "equation"
```

Cf. http://jsbin.com/fanubu/3/edit?html,output

**Comment by pkra** [comment]
FYI I'm closing this as expected behavior. Feel free to still follow up with questions.

**Comment by artur99** [comment]
Thank you!
Now this is the problem: it will only convert the equations with $$, it wont work with $
Example: http://jsfiddle.net/artur99/1erzqsy6/

There would be really nice to be a minimalist version of this system...
A simple way to convert the Tex equations without any menu, alert(like the ones on bottom left), language files, plugins, etc...

**Comment by pkra** [comment]
>  Now this is the problem: it will only convert the equations with $$, it wont work with $

I'd suggest to study the documentation in more detail and also search around the web a bit, especially on the MathJax User Group mailing list.

**Comment by artur99** [comment]
Yeah, sorry :) I found the answer on stackexchange. Thank you :D

This is my code, maybe someone will need it once: http://jsfiddle.net/artur99/1erzqsy6/1/

Thanks
