### ISSUE TITLE
LaTeX input: add support for bm package

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1219]
Tracking a feature request from elsewhere. 

Package info: http://ctan.org/pkg/bm

**Comment by nerdDan** [comment]
so `bm` will not be supported?

**Comment by pkra** [comment]
> so bm will not be supported?

The team was not planning on implementing it but contributions are always welcome.

I don't know the package but it seems to be equivalent to setting `mathvariant='bold'` in MathML (which would be very easy to implement). Maybe @davidcarlisle can chime in.

There might also be a font limitations (missing glyphs).

(I also never noticed the amount of :+1 -- no idea how to get notify by GitHub about these.)

**Comment by bfirsh** [comment]
This in your config seems to work as a workaround:

```
TeX: {
  Macros: {
    bm: ["{\\boldsymbol #1}",1],
  }
}
```

**Comment by pkra** [comment]
> This in your config seems to work as a workaround:

This wouldn't quite be sufficient since `\boldsymbol` is not a switch; e.g., `{ \bm aa}` should have both `a` in bold.

Here's an example that @dpvc recently created:

```
MathJax.Hub.Config({
  TeX: {
    extensions: ["boldsymbol.js"],
    Augment: {
      Definitions: {macros: {
        bm: 'myBoldSwitch'
      }},
      Parse: {prototype: {
        myBoldSwitch: function (name) {
          this.stack.env.boldsymbol = true;
        }
      }}
    }
  }
});
```

Note: I have not checked if its behavior will match the `bm` package (as far as it's appropriate to ask that question anyway); @davidcarlisle would know best, of course.

**Comment by davidcarlisle** [comment]
`\bm` takes an argument  In latex, `{\bm aa}` is the same as `{\bm{a}a}` with only the first a bold (and a spurious group around the outside.  Please don't implement `\bm` as a switch making it incompatible with latex usage!

**Comment by pkra** [comment]
Thanks so much for the correction, @davidcarlisle!

**Comment by pkra** [comment]
@davidcarlisle so just

```
 Macros: {
      bm: ["\\boldsymbol{#1}",1]
    }
```
is better -- but not quite compatible as it won't use poor man's bold when needed (IIUC that would require changes in the font fallback behavior which might be doable in v3).

**Comment by pkra** [comment]
I've also added a note to my earlier comment.

**Comment by davidcarlisle** [comment]
yes the difference between \boldsymbol and \bm is mainly one of spacing, \bm takes far more care to get the same math classes so if \foo makes a binary operator or a an opening delimiter or a relation or whatever, then  \bm{\foo} makes the same (if it can) but \boldsymbol is (more or less) just \hbox{\boldmath$...$} so in most cases (apart from some special case relations) loses the distinction.  But probably that's rather tex-implementation distinction that is less relevant here.

**Comment by dpvc** [comment]
Just FYI, because `\boldsymbol` in MathJax simply adds the proper mathvariant to the internal MathML generated from the TeX, the spacing will be the same as without `\boldsymbol` since the spacing is based on the elements (and their content in the case of `<mo>`) not the variant.

**Comment by pkra** [comment]
Also, MathJax sets bold via CSS when falling back to system fonts. 

@dpvc is there's ever a "font-internal" fallback case where MathJax would fall back to a non-bold alternative?

**Comment by dpvc** [comment]
> is there's ever a "font-internal" fallback case where MathJax would fall back to a non-bold alternative?

Yes.  If there is a character not in the bold variant but in the normal variant, `\boldsymbol{}` will still produce the normal variant.  E.g., `\boldsymbol{\boxplus}` is the same as `\boxplus` in the MathJax TeX fonts.  For the most part, this will be characters in the MathJax_AMS-Regular font that are not in the MathJax_Main-Bold font.

**Comment by masi456** [comment]
Why was this issue closed? Has it been implemented?

**Comment by pkra** [comment]
> Why was this issue closed? 

Because there hasn't been interest after six years. 

> Has it been implemented?

https://github.com/mathjax/MathJax/issues/1219#issuecomment-341059843 gives a very reasonable, 1-line implementation.

**Comment by masi456** [comment]
Ok, just wanted to make sure that it wasn't closed because it was implemented without me noticing.
Thanks for the info!

**Comment by funnym0nk3y** [comment]
Is it possible to extend the 1-line implementation #1219  (comment) to make the symbols italic? When using `\boldsymbol` instead of `\bm` in KaTeX a `\Lambda` gets renderd upright.

**Comment by dpvc** [comment]
@funnym0nk3y, `\Lambda` is rendered upright by `\boldsymbol` in MathJax as well.  If you are using version 3 of MathJax, the recent 3.1.3 update added `\mathbfit` that will produce a bold italic `\Lambda`.  Perhaps that is a better replacement for `\bm`.

**Comment by lohfu** [comment]
@pkra @dpvc

`\mathbfit` still doesnt seem to cover all cases that `\bm` does. Right now i am struggling to create a bold and italic digits (more specifically 0). No packages (physics, unicode-math etc) work, even in regular Latex. The only way i have gotten to work right now is `\bm\mathit{0}` and `\pmb`. `\pmb` seems hacky, but perhaps `\bm` actually uses `\pmb` behind the scenes as according to https://tex.stackexchange.com/a/432419 "there are no bold italic mathematical digits in Unicode"?
