### ISSUE TITLE
 LaTeX input: add support for pifont package

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1220]
Tracking a feature request from elsewhere.

Package info: http://ctan.org/pkg/pifont

**Comment by pkra** [comment]
Includes upGreek and dingbats support. More suitable for third-party extension repo?

**Comment by lele3** [comment]
Excuse me, does MathJax support this package now?

**Comment by dpvc** [comment]
This would be a good project for a third party developer.  It is not currently in the core MathJax distribution.  Note, however, that you can access any unicode character via the `\unicode{}` macro.  So for, example, to get ✎, use `\unicode{x270E}`

**Comment by alexreg** [comment]
Sounds like this should be in the core MathJax package really.
