### ISSUE TITLE
Bug: iframe usage causes MathJax config to be ignored

### ISSUE THREAD

**Issue by cjshawMIT** [mathjax/MathJax#1241]
### Issue Summary
When I use MathJax in an iframe, my `tex2jax` config is ignored (both in parent window and in the iframe, even when it is loaded and configured in each one). Configuring `tex2jax` in a window without an iframe seems to work fine. So it seems like just including an iframe in the DOM breaks custom configs.

### Steps to Reproduce
See this fiddle for a broken example with an iframe.
https://jsfiddle.net/a0abhk1j/1/

Just a simple iframe pointing to google:
https://jsfiddle.net/a0abhk1j/2/

This fiddle has the exact same non-iframe code, and works as expected:
https://jsfiddle.net/1dxpp9nm/

* MathJax Version: 2.5.3 (https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML)
* Client OS: Mac OSX 10.9.5
* Browser: Chrome 44 / FF 39
*

**Comment by dpvc** [comment]
The configuration script in your iframe is incorrect.  It should be `type="text/x-mathjax-config"`, not `type="x-mathjax-config"` (it needs to look like a MIME type).  If you change that, the configuration is processed as expected.

**Comment by cjshawMIT** [comment]
Ah, thanks!
