### ISSUE TITLE
Rendering of LaTeX fails after first rendering

### ISSUE THREAD

**Issue by csaintc** [mathjax/MathJax#1243]
This formula renders properly the first fime, but any subsequent renders fails.

You can see this through the editor on stackedit. If you paste this into the text area, and then enter any text, you'll see the behavior.
```
$\begin{equation} \label{eq1}
\begin{split}
A & = \frac{\pi r^2}{2} \\
& = \frac{1}{2} \pi r^2
\end{split}
\end{equation}$
```

**Comment by dpvc** [comment]
This is an issue with the StackExchange (and presumably StackEdit) preview code, which doesn't reset the labels properly when equations are re-rendered.  See [this post](http://meta.math.stackexchange.com/questions/11392/mathjax-preview-broken-when-equations-contain-labels) for some more information on the issue.
