### ISSUE TITLE
MathJax install directory is ignored when showing a page through Google Translator

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1244]
Dear MathJax developers,

In my webserver logs, I sometimes see failed requests for JavaScript files like this one:

    /jax/output/HTML-CSS/config.js?rev=2.5.3

The reason why they fail is that I installed MathJax in the `/mathjax` directory, so the correct path would be:

    /mathjax/jax/output/HTML-CSS/config.js?rev=2.5.3

I investigated the issue and found out that it occurs when people visit my website through the Google Translator. This is the original `<script>` tag:

    <script type="text/javascript" src="mathjax/MathJax.js?1430429173" async></script>

And this is what comes out of the Google Translator:

    <script type=text/javascript src=https://translate.googleusercontent.com/translate_c?depth=2&amp;hl=sv&amp;pok=1&amp;prev=search&amp;rurl=translate.google.com&amp;sl=en&amp;u=http://www.my-website.com/mathjax/MathJax.js%3F1430429173&amp;usg=ALkJrhhZA32GEKT2xBLIgKnqdLNi2xTxtw async></script>

The problem is clear: MathJax is not able to figure out the correct location of the additional JavaScript files to load.

As you see, I don't use the MathJax CDN, since I like to have critical things on my own server. Using the CDN would seem to solve the problem, but as I said, I'd rather not.

Is there a way to manually configure the "base URL" so that the files will be found?

**Comment by kassio** [comment]
I'm with the same problem here. But, in my case, I'm just accessing my page and getting: 
![screen shot 2015-08-27 at 7 38 05 pm](https://cloud.githubusercontent.com/assets/120483/9534965/423ec2ae-4cf3-11e5-8c34-a26b471a89e0.png)

If I change the MathJax load to use CDN it works.

**Comment by kassio** [comment]
In the screenshot above it's 2.4-beta-2, but I tried with 2.5.3 too.

**Comment by kassio** [comment]
After change the `MathJax.Ajax.config.root = MATHJAX_PATH;` the requests worked.

**Comment by kassio** [comment]
I found my problem, I wasn't using a `<script>` tag, I was using a `$.getScript`. :cry:

**Comment by TomasRiker** [comment]
Great, thank you! I couldn't find `MathJax.Ajax.config.root` in the documentation, but `MathJax.Hub.config.root`. Would it be more advisable to change the latter?

**Comment by dpvc** [comment]
In fact, they both point to the same location (`MathJax.Ajax.config` is set equal to `MathJax.Hub.config`  specifically so the Ajax module can use the `root` property).  So it really doesn't matter which you set, as you are setting both either way.
