### ISSUE TITLE
mangled equation numbering when using \choose

### ISSUE THREAD

**Issue by rupertgatti** [mathjax/MathJax#1246]
I obtained an example of using MathJax from [Calibre's website](http://manual.calibre-ebook.com/typesetting_math.html) and was trying to open it in my browser. I found that unless I added the following snippet to the code, the file didn't render correctly in my browser:
```
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```
The result was almost fine but had a pretty bad formatting problem for the equation `\[P(E) = {n \choose k} p^k (1-p)^{ n-k} \]`, you can see this in the attached screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/4866395/9543496/3d3eac14-4d71-11e5-9408-fbc0f886b994.png)

It appears that the formula is initially rendered correctly, but when equation numbers are added (in a second pass, it seems), the formula is mangled and broken up. Scrolling to the right of the screen I can see the rest of the formula, as shown in the following screenshot:
![screenshot2](https://cloud.githubusercontent.com/assets/4866395/9543590/dc75a8e6-4d71-11e5-8e66-e9c46233c172.png)

I tried viewing this using both Firefox 40.0.2 and Chrome "Version 44.0.2403.157 m", and both gave the same output. Do you think this is a bug in MathJax, or is there anything I can do from my end to avoid this behaviour?

**Comment by rupertgatti** [comment]
Quick update: I found that the problem goes away if I remove the following code
```
<!-- This script tag is needed to make calibre's ebook-viewer recpgnize that this file needs math typesetting -->
<script type="text/x-mathjax-config">
    // This line adds numbers to all equations automatically, unless explicitly suppressed.
    MathJax.Hub.Config({ TeX: { equationNumbers: {autoNumber: "all"} } });
</script>
```
at the expense of losing equation numbering. This suggests to me that there's a problem in MathJax's equation numbering, that interferes with the typesetting of some kinds of formulas (involving `\choose` perhaps).

**Comment by dpvc** [comment]
This is issue #1194, for which a fix will appear in the next release.

**Comment by rupertgatti** [comment]
@dpvc Thanks for that - apologies, I hadn't seen the orignal issue
When do you expect to the next release to be made?

**Comment by dpvc** [comment]
We are in the internal testing phase for the release, and will go to beta test soon.  Assuming nothing serious shows up, the release will follow that.  So it is coming soon, but I can't give you an exact date.
