### ISSUE TITLE
update asciimath for v2.6

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1247]
Have we pulled in an update already?

**Comment by dpvc** [comment]
No, so that's something that was left off my its of things to do for v2.6.

**Comment by dpvc** [comment]
The `issue1247` branch of my fork of MathJax includes the updates.

**Comment by pkra** [comment]
For the record: only change is https://github.com/asciimath/asciimathml/issues/31, adding over/underparen to asciimath.

**Comment by dpvc** [comment]
FYI, the commit listed above also shows what the changes are.

**Comment by dpvc** [comment]
=> Merged
