### ISSUE TITLE
mml3js xslt transforms failing on MS Edge [was: Readium on MS Edge:  Unable to get property 'documentElement' ]

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1252]
Via https://github.com/readium/readium-js-viewer/issues/394

On http://development.readium.divshot.io/?epub=epub_content%2Flinear-algebra with Edge, MathJax throws

`Error: Unable to get property 'documentElement' of undefined or null reference`

Probably caused by mml3.js, i.e., https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/MathML/mml3.js#L92-L107 -- that ActiveXObject seems dubious (Edge kicked those kinds of things out, no?)

**Comment by dpvc** [comment]
I would expect Edge to implement `XSLTProcessor`, so the lines you indicate would not be reached.  In any case, they don't contain the `documentElement` call that is causing the error.  That seems to be the section below that, intended for IE8 and below.  If you use the MathJax menu to get the About MathJax box, what browser and version does it think you are using?

If the error is actually from line 116 (you can view `MathJax.Hub.lastError.stack` in the console to see more information about the call stack), then the problem is that the parsing of the original MathML is failing, and the doc at line 58 is null.  There should probably be a line

    if (doc == null) MATHML.Error(["ErrorParsingMathML","Error parsing MathML"]);

after line 58 to check for that.

**Comment by pkra** [comment]
`MathJax.Hub.lastError.stack`points to https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/MathML/mml3.js#L70

```
MathJax.Hub.lastError.stack
"TypeError: Unable to get property 'documentElement' of undefined or null reference
   at Anonymous function (http://192.168.0.161:8080/unpacked/extensions/MathML/mml3.js?rev=2.5.3:70:7)
   at CALLBACK.prototype.execute (http://192.168.0.161:8080/unpacked/MathJax.js:236:9)
   at cb (http://192.168.0.161:8080/unpacked/MathJax.js:218:27)
   at Execute (http://192.168.0.161:8080/unpacked/MathJax.js:419:9)
   at Translate (http://192.168.0.161:8080/unpacked/jax/input/MathML/jax.js?rev=2.5.3:263:7)
   at MathJax.Hub.processInput (http://192.168.0.161:8080/unpacked/MathJax.js:2179:11)
   at CALLBACK.prototype.execute (http://192.168.0.161:8080/unpacked/MathJax.js:236:9)
   at cb (http://192.168.0.161:8080/unpacked/MathJax.js:218:27)
   at AFTER (http://192.168.0.161:8080/unpacked/MathJax.js:367:7)
   at MathJax.Hub.processError (http://192.168.0.161:8080/unpacked/MathJax.js:2331:5)"
```

**Comment by dpvc** [comment]
OK, so it is line 61 that is returning the `null` document.  The seems to indicate that the XSL transform failed in some way.  There should probably be a test similar to the one above, and in that case just return the original MathML I guess.

**Comment by pkra** [comment]
Yup. I'll see if I can learn anything about xslt in Edge later.

**Comment by pkra** [comment]
What would I expect for `doc` on Line 58? It looks empty on Edge.

**Comment by dpvc** [comment]
It should be a DOM document.  If it is empty, then the original MathML is not being parsed properly as XML.  There are several methods by which that could be done, and it might help to check which of the three methods is being used.  These are in the [MathML jax](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/MathML/jax.js#L316-L335) lines 316 through 335, and the code for handing their output is [a few lines earlier](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/input/MathML/jax.js#L291-L299).  You could try doing the earlier lines by hand and see what happens.

**Comment by pkra** [comment]
Oh, nevermind. I just serialized it incorrectly. 

It seems to come down to the xstl. I don't know how to debug that part though. Using a plain xml file with the stylsheet didn't have any effect on Edge but didn't cause any trouble either, so I don't know. I'll have to come back to this some other time.

**Comment by pkra** [comment]
Correction: the xml file does run into an issue (VM is slow....). Will dig into that some time.

**Comment by pkra** [comment]
David C has looked into it and it seems like a bug in Edge wrt xslt. He's trying to see if he can work around it. It's about time we re-implemented this in JS, I suppose.

**Comment by pkra** [comment]
Thanks to @davidcarlisle for tracking down this MS Edge bug.

@dpvc it looks like we would need to sniff out Edge (to modify the xslt string for Edge users). Should I do this in the extension or extend [BROWSERS in MathJax.js](https://github.com/mathjax/MathJax/blob/ba9afeb5a743249acdea17540b48b14ebc95dbe4/unpacked/MathJax.js#L3074)?

**Comment by dpvc** [comment]
Can you test for the failure condition by running a test xslt transform?

If not, what currently shows up as browser and version for Edge in the About MathJax box?  I don't remember what the current condition is for Edge in terms of detection.

**Comment by pkra** [comment]
> Can you test for the failure condition by running a test xslt transform?

I'll give that a try.

> If not, what currently shows up as browser and version for Edge in the About MathJax box? 

I'll check later.

> I don't remember what the current condition is for Edge in terms of detection.

I had found http://stackoverflow.com/questions/30591706/what-is-the-user-agent-string-name-for-microsoft-edge which links to MS Edge where they say they focus on being WebKit-like (and consider failure to be bugs but I guess that's about layout, not xslt).

**Comment by pkra** [comment]
> If not, what currently shows up as browser and version for Edge in the About MathJax box?

Safari 7.0.

**Comment by dpvc** [comment]
It looks like it will identify as Safari, which is what their string is designed to do (tell people it is WebKit).  I suppose we could improve the sniffing and either add a new category for Edge (rather than calling it MSIE), or use MSIE and version number (which doesn't work currently, since it will match Safari, not MSIE).

**Comment by dpvc** [comment]
(I guess our messages crossed)

**Comment by pkra** [comment]
I'm confused. The UA string I get on the official MS Edge VM's is `Mozilla/5.0 (Windows NT 10.0; Win64; x64)` -- not the one advertizd on the MS blog :-( Not sure how to sniff that out reasonably.

I don't see how to efficiently test the xslt without loading up the "wrong" one first. I've hacked something together on http://codepen.io/pkra/pen/MaYeBZ Will continue to play around with that.

**Comment by pkra** [comment]
Oh fun. @davidcarlisle reports the correct UA string from his Win10 installation.

**Comment by pkra** [comment]
Not alone in this: http://stackoverflow.com/questions/32061829/microsoft-edge-user-agent-from-modern-ie

**Comment by pkra** [comment]
Note that the answers on that thread come from Edge personnel. 

So I'd propose to go with `!!AGENT.match(/Edge\//); `.

**Comment by dpvc** [comment]
> I don't see how to efficiently test the xslt without loading up the "wrong" one first.

If you (or David) has identified the part of the XSLT that is failing, then you could use a trimmed down transform that tests of that failure occurs or not (without loading the complete XSLT).  Since I don't know what the nature of the problem is, I can't tell you how to test it specifically, but that is the idea.  you can use your `userAgent` test if you prefer.

That doesn't answer my question about whether to make a new browser category for Edge as opposed to MSIE, since most of what counts for MSIE won't be needed for Edge.  I think it would probably be a good idea.

**Comment by pkra** [comment]
This was actually fixed by https://github.com/mathjax/MathJax/pull/1257, at least as far as we're willing to go at this point (and probably as far as the xslt approach will take us)

**Comment by pkra** [comment]
Any objections to moving this into the milestone and closing this?

**Comment by dpvc** [comment]
Nope.  I'm doing that now.
