### ISSUE TITLE
Examples in test: add viewport  meta tag

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1253]
This keeps bugging me today. As discussed on https://github.com/mathjax/MathJax-docs/issues/98

`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by dpvc** [comment]
Are you asking that MathJax insert this into the page?

First of all, I'm not sure it can be added dynamically after the delay of loading MathJax.

Second, it is not really our place to alter the way that page works in that way.  This is something the page author needs control of, and MathJax should not be mucking around with that.

If you want to add it to the documentation, that's fine, but I don't see MathJax inserting this automatically.

**Comment by pkra** [comment]
> Are you asking that MathJax insert this into the page?

No, I just want to update the html files.

peter.

**Comment by dpvc** [comment]
Ah, now I understand the title.  Sorry.

**Comment by dpvc** [comment]
=> Merged.
