### ISSUE TITLE
Letter tail overlaps with arrowhead in <mover> tag.

### ISSUE THREAD

**Issue by mrozyckiYDP** [mathjax/MathJax#1255]
# Description 
When you place some text, that starts or ends with a letter that contains tail, over the arrow, the tail overlaps with arrowhead.
# Example
Code:
```
<math>
  <mover>
    <mo>←</mo>
    <mn>gone</mn>
  </mover>
</math>
```
Result:
![bugged](https://cloud.githubusercontent.com/assets/10846967/9651744/e0db4da8-5214-11e5-939e-d8bc9a9c083b.PNG)
# Demo
http://codepen.io/anon/pen/QjWRQG
# Technical details:
* MathJax 2.5
* Chrome 44.0.2403.157, Firefox 39.0, Opera 31.0
* Windows 7

**Comment by pkra** [comment]
Thanks for the detailed bug report! If `stretchy=false`, the spacing is different (but it won't be stretchy).

@dpvc is this expected behavior? 

(There's also an issue with the gap in the stretchy construction, but I suppose that's separate).

**Comment by mrozyckiYDP** [comment]
Unfortunately, we do need streching. Currently we are using non-breaking space  symbol to shift the word. e.g. `<mn>&nbsp gone</mn>`

**Comment by pkra** [comment]
> Unfortunately, we do need streching.

Right. That was more a technical observation.

**Comment by dpvc** [comment]
It's a bug in the HTML-CSS output (note that SVG positions better, as does the new CommonHTML renderer).  The height of the stretched arrow is incorrect.

**Comment by pkra** [comment]
Did we want to try to squeeze this into v2.6?

**Comment by dpvc** [comment]
I was thinking about doing that.  It should not be hard.

**Comment by dpvc** [comment]
This is fixed in the `issue1255` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged.
