### ISSUE TITLE
Fraction Clipping issue in version 2.4

### ISSUE THREAD

**Issue by markkellyeire** [mathjax/MathJax#1256]
Hi there,

I am currently experiencing an issue in version 2.4 whereby the top part of fractions is being cut off by the  clip: rect value that is being applied to the wrapping span.

My main goal here is to increase the font-size of fractions to 90% of whole numbers. Initially I applied the change to my own css and noticed this clipping issue. Since then I have attempted to add the css styles as per the documentation here:

http://docs.mathjax.org/en/latest/CSS-styles.html#css-style-objects

Unfortunately this issue still remains. As upgrading to the latest version is not an option at the moment, I am just wondering if you could advise me on the best approach to make such a change.

Thanks in advance.

Mark

**Comment by pkra** [comment]
Thanks for the report.

Are you able test if the problem occurs with v2.5? Could you provide a live sample that exhibits the problem? Either a live page or something codepen, jsbin etc. Please check https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports for further tips on narrowing things down.

In general, you shouldn't use CSS to tweak the layout itself (it easily interferes with the layout itself). But this sounds like a bug so it would be good to know if it has been fixed.

**Comment by markkellyeire** [comment]
Hey Guys,

Thanks for your response. Unfortunately I am not in a position to provide an example of the issue or test in v2.5. To work around the clients request we have added a macro to convert frac to dfrac which renders the fraction as requested.

Thanks again for your help.
