### ISSUE TITLE
Limits in \sum and \int

### ISSUE THREAD

**Issue by alex-mashin** [mathjax/MathJax#1268]
Unless one uses `\limits`, the lower and upper limits for `\sum` and similar operators are placed differently, depending on whether the formula is in inline or display mode: to the right of the ∑ sign in inline mode and directly below and above ∑ in display mode.

However, limits for integrals behave differently: they are always shifted to the right in both modes.

Is this inconsistency a bug or a feature?

**Comment by pkra** [comment]
I'm not totally certain but I'm guessing you mean the difference between $\int_{a}^{b} x^2 dx$ and $\int\limits_{a}^{b} x^2 dx$ (and its displaystyle counterparts). 

That's a feature since it is consistent with both TeX layout and the MathML specification.

**Comment by pkra** [comment]
Forgot some references. E.g., https://en.wikibooks.org/wiki/LaTeX/Mathematics#Sums_and_integrals and "movable limits" here http://www.w3.org/Math/draft-spec/mathml.html#chapter3_presm.mo.dict.attrs.

**Comment by alex-mashin** [comment]
From the links that you provided I can see that there is some tradition behind compactiying sums and integrals vertically in inline mode. But I still don't understand why integrals are shown with limits to their right even in display mode unless `\limits` is used.

I also wonder if there are system-wide MathJax settings that can effectively add `\limits` to any sum or integral operator in both modes. The reason for such setting is that the tradition of compactifying these in inline mode is not universal: I haven't seen such sums/integrals (with limits to the right) in Russian typography.

**Comment by pkra** [comment]
> But I still don't understand why integrals are shown with limits to their right even in display mode unless \limits is used.

Because the MathML operator dictionary does not list integrals as having `movablelimits=true`.

> I also wonder if there are system-wide MathJax settings that can effectively add \limits to any sum or integral operator in both modes. 

You can define your own macros for this.

**Comment by alex-mashin** [comment]
> You can define your own macros for this.
Well, I guess this is the usual solution, just as it was with trigonometric and hyperbolic functions. Thank you for your input. Think the issue can be closed now.
