### ISSUE TITLE
2.6-beta eqnarray spacing issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1272]
Reported on meta.math.SE http://meta.math.stackexchange.com/a/21520/26910

**Comment by dpvc** [comment]
This is fixed in the `issue1272` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
Already in test suite (LaTeXToMathML/environments/eqnarray-*), but these will have to be updated to check for the new MathML.
