### ISSUE TITLE
using Big operator with Times does not work

### ISSUE THREAD

**Issue by LiasBluestone** [mathjax/MathJax#1275]
Paul Halmos in Naive Set Theory uses a large \times sign to indicate cartesian product of a family. However, there appears not to be a convenient way to implement this. \big \times falls over, for example, because \times is not a bracket of any kind. The best I can achieve is \huge \times but that sets all the following text in that LaTeX string to huge, and I don't want that.

Can we have a \bigtimes command?

**Comment by dpvc** [comment]
Try

  \def\bigtimes{\mathop{\vcenter{\huge\times}}}

That should do what you are looking for, I think.

**Comment by LiasBluestone** [comment]
Certainly, that works -- a bit clumsy, but it does the job.  Many thanks.

I still reckon there's room in MathJax for a \bigtimes command.  It seems plenty of authors use it -- I found another one just now.

**Comment by pkra** [comment]
> I still reckon there's room in MathJax for a \bigtimes command.

The general approach would be to submit a custom extension to https://github.com/mathjax/MathJax-third-party-extensions, ideally corresponding to a well known CTAN package.
