### ISSUE TITLE
[2.6-beta]  [CommonHTML] \big with subscript+superscript issues

### ISSUE THREAD

**Issue by szego** [mathjax/MathJax#1287]
Report from Math.SE: http://meta.math.stackexchange.com/a/21724/5531

There seems to be an issue with adding subscripts and superscripts to \big'd elements. Examples are given at the above link.

**Comment by pkra** [comment]
Thanks for reporting this here!

**Comment by dpvc** [comment]
This is fixed in the `issue1287` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/issue1287.html
