### ISSUE TITLE
[2.6-beta1] [CommonHTML] doesn't automatically linebreak long formulas

### ISSUE THREAD

**Issue by szego** [mathjax/MathJax#1288]
When using the HTML-CSS renderer long math expressions are automatically wrapped. With CommonHTML they overflow out of their element.

For example, try

    $$\int_{-\infty}^{\infty} \frac{e^{-t^2}}{t-z}\,dt = \int_{|t-x| < s(z,x)} \frac{e^{-t^2} - e^{-x^2}}{t-z}\,dt + \int_{s(z,x) < |t-x|}  \frac{e^{-t^2}}{t-z}\,dt - i\pi e^{-x^2} - e^{-x^2} \int_{s(z,x) < |t-x|} \left( \frac{1}{t-z} - \frac{1}{t-x} \right) \,dt$$

The output can be seen [on Math SE](http://meta.math.stackexchange.com/a/21740/).

Technical details

- MathJax Version: v2.6-beta1
- Client OS: Windows 7 Home Premium SP1
- Browser: Chrome 46.0.2490.71 m
- Output: HTML-CSS vs CommonHTML

**Comment by pkra** [comment]
Thanks for reporting this here, too. 

It seems to be a configuration issue on math.SE. Their configuration only sets up line-breaking for the HTML-CSS output -- you'll notice that the SVG output also does not line-break on math.SE.
