### ISSUE TITLE
Problems Loading Extensions via CDN

### ISSUE THREAD

**Issue by m0mo0815** [mathjax/MathJax#1291]
Hello,I use the following configuration:
```
<script type="text/x-mathjax-config">

MathJax.Hub.Config({
	extensions: ["jsMath2jax.js", "cancel.js", "color.js", "bbox.js"],
        ...
});

</script>
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>
```
but when trying to load the extension I get the following network error:

```
"NetworkError: 404 Not Found - https://cdn.mathjax.org/mathjax/latest/extensions/color.js?rev=2.5.3"
"NetworkError: 404 Not Found - https://cdn.mathjax.org/mathjax/latest/extensions/cancel.js?rev=2.5.3"
"NetworkError: 404 Not Found - https://cdn.mathjax.org/mathjax/latest/extensions/bbox.js?rev=2.5.3"
```
I have no local copy of mathjax strictly using the CDN - is there something wrong in this configuration?

Kind Regards
Stephan

**Comment by pkra** [comment]
> is there something wrong in this configuration?

Luckily, there is. Extensions are organized by input and output jax they extend. Either make it 

```javascript

MathJax.Hub.Config({
    extensions: ["jsMath2jax.js", "TeX/cancel.js", "TeX/color.js", "TeX/bbox.js"],
        ...
});
```

or add a TeX section in your configuration and move the TeX extensions there (so that MathJax will add the prefix.

```javascript

MathJax.Hub.Config({
    extensions: ["jsMath2jax.js"],
    TeX: {
       extensions: ["cancel.js", "color.js", "bbox.js"],
      },
...
});
```

For reference, the correct sources are at `https://cdn.mathjax.org/mathjax/latest/extensions/TeX/color.js` etc.

**Comment by m0mo0815** [comment]
Hello Peter,
wow, fast response - and what a stupid misstake! Thanks you very much for the explanation.

Kind Regards
Stephan

**Comment by pkra** [comment]
No problem at all. Always happy when it's just a simple user error ;-)
