### ISSUE TITLE
[2.6-beta] CommonHTML, Chrome: macro error leads to repetition on subsequent typesetting

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1293]
As reported on meta.SE http://meta.math.stackexchange.com/questions/21505/mathjax-2-6-beta#comment84812_21535, see also ![mathj.se](http://i.stack.imgur.com/ot6Ec.png)

Looks like the script tag is copied into the `class="mjx-noError"` element, so calling Typeset again leads to repeated rendering.

I can reproduce this on Chrome 46 Windows 10 and Linux (though on Win10 it renders the error twice immediately while on Linux it only doubles if I call typeset manually -- weird).

**Comment by pkra** [comment]
Of course, an edit on SE will trigger a typeset call (apparently on the entire page), so this can grow rapidly.

**Comment by dpvc** [comment]
This is a duplicate of #1285, and it is already fixed in `develop`.

**Comment by pkra** [comment]
Oops. I had missed that. Thanks.
