### ISSUE TITLE
Instruments to reset equation numbering within one page

### ISSUE THREAD

**Issue by s1ddok** [mathjax/MathJax#1294]
I'm currently building e-book for my university on Linear Algebra and it would be one big page with a lot of theorem etc. But it seems there are no way to reset equation numbers for each theorem. 

How can I implement that?

**Comment by pkra** [comment]
Could you provided more details about what you are after? It sounds like you are using MathJax's TeX input with automated equation numbering but beyond that it's not clear what your use case looks like -- as always a live sample (e.g., using jsbin, codepen etc) would be good. 

You might want to check the formatting functions in http://mathjax.readthedocs.org/en/v2.6-latest/options/TeX.html and for a simple `\setCounter` macro this example http://codepen.io/pkra/pen/YXPQxR.

**Comment by s1ddok** [comment]
That's it! Thank you!

I used this pieces of code!
```javascript
MathJax.InputJax.TeX.Definitions.Add({
        macros: {
          setCounter: "setCounter"
        }
      }, null, true);
      MathJax.InputJax.TeX.Parse.Augment({
        setCounter: function(name) {
          var num =  parseInt(this.GetArgument(name));
          MathJax.Extension["TeX/AMSmath"].number = num;
        }
      });
```
