### ISSUE TITLE
MathJax formulas overlap. Can't target them with CSS to set possitions.

### ISSUE THREAD

**Issue by schinalex** [mathjax/MathJax#1298]
How can I target the rendered MathJax formulas with CSS, because they overlap on one another if they div containing them is smaller than the text that will be rendered. 
   What I do is write a few divs with some dimensions (say width:50px; height:50;), in each div I write a math formula (of different sizes). If the formula rendered is bigger than the div then it overlaps on the next div's formula. I could set the div a larger width, but then when the formula is short the text will be too far from one another.
   I want to set something like "position: relative" so they would not overlap (as they would be relative to one another wouldn't they?). Will that work? or is there another solution. 
Anyway... I need to target them directly. But there are so many classes and spans and div, I can't figure out which one represents the rendered text. I have this problem for several weeks now, and still couldn't fix that. 
   Please help!

**Comment by pkra** [comment]
Generally speaking you should avoid targeting MathJax's output with external CSS. But it sounds like you're putting containers around equations so targeting those seems natural and should be enough for what you're describing. 

A live example of what you've tried (on codepen, jsbin etc) usually helps.
