### ISSUE TITLE
Mathjax not rendering matrices properly

### ISSUE THREAD

**Issue by amlwwalker** [mathjax/MathJax#1301]
Hi I am using MacDown markdown editor with maths. When I write a matrix in that with the syntax:

```
$$ \left[\begin{matrix} 00 & 01 & 02 \\ 10 & 11 & 12 \\ 20 & 21 & 22 \end{matrix}\right] $$
```

I get:

![image](https://cloud.githubusercontent.com/assets/2920180/11272593/f16e9d6c-8ec5-11e5-9f89-26dfe12024ff.png)

When rendered in macDown.

When I use Mathjax on the web to render the same matrix, I get:

![image](https://cloud.githubusercontent.com/assets/2920180/11272628/27946796-8ec6-11e5-8736-193b82e50022.png)

All other maths seem to work fine, its just matrices that dont render properly. Any ideas why?

**Comment by amlwwalker** [comment]
Ok, to let anyone know, for some reason the markdown library I am using escapes `\\` to `\`. If I use `\\\` it works perfectly. Sorry for the issue

**Comment by pkra** [comment]
Glad you could figure it out. This is a typical markdown problem and described in our documentation at http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents
