### ISSUE TITLE
Prime and double prime don't work when used together as a superscript

### ISSUE THREAD

**Issue by karoltarasiuk** [mathjax/MathJax#1302]
This LaTex simply doesn't render: `^\prime ^{\prime\prime}`.

I understand that the context of usage of those symbols is not exactly valid, but correct me if I'm wrong: typesetting library shouldn't care about the context. It should just render.

**Comment by dpvc** [comment]
The expression `^\prime ^{\prime\prime}` doesn't compile in LaTeX either, because it is not a valid expression in the LaTeX.  It is a double exponent (the two `^` in a row are not allowed), so LaTeX throws an error for this.  So does MathJax.

Perhaps you mean `^\prime {}^{\prime\prime}`?

**Comment by karoltarasiuk** [comment]
@dpvc thanks for that! I indeed missed this fact, closing the issue then.
