### ISSUE TITLE
[2.6-beta] CommonHTML on IE9: fraction

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1303]
[This example](http://s.codepen.io/pkra/debug/NGojag) on IE9 looks like

![v2_6-chtml-ie9](https://cloud.githubusercontent.com/assets/426686/11298390/e5c13a56-8f7e-11e5-9446-d2e3ff9f75b1.png)

**Comment by dpvc** [comment]
I am not able to reproduce the issue.  I used Windows 7 with IE9, as well as with IE10 in IE9 emulation.

**Comment by pkra** [comment]
Strange. I ran into it this just yesterday, on mathjax.org.

**Comment by pkra** [comment]
![virtualbox_ie9_02_12_2015_21_54_59](https://cloud.githubusercontent.com/assets/426686/11543896/5eb2a9d0-993f-11e5-957f-f2891a138246.png)

**Comment by dpvc** [comment]
This is what I see in IE10 on Windows 7 in IE9 emulation mode.  What version of IE are you running?

![ie9](https://cloud.githubusercontent.com/assets/432782/11544259/f03443cc-990e-11e5-8d7f-21f857fbfdce.png)

**Comment by pkra** [comment]
My screenshot was from the IE9 VM from modern.ie (Win 7)

**Comment by dpvc** [comment]
I also used IE9 in Windows 7, with similar results.  It was in an official Windows 7 (that I own).

**Comment by pkra** [comment]
Huh. Weird. Let me try a fresh VM tomorrow morning and report back to you.

**Comment by dpvc** [comment]
Is it possible that you have the old MathJax fonts installed on that VM?  Can you check via the font test page?

**Comment by pkra** [comment]
> Is it possible that you have the old MathJax fonts installed on that VM? Can you check via the font test page?

That was my suspicion as well. The menu said I'm using webfonts but the test says I'm not. I don't recall installing them. 

Oh well, fresh VM, all good, case closed. Sorry for the noise.

**Comment by dpvc** [comment]
CommonHTML is set up to use both (local if you have them, and web if not), but doesn't know which are actually being used.  HTML-CSS actually detects the fonts and so knows which is used, but CommonHTML doesn't.  if it did, it would not be browser and system independent.

**Comment by pkra** [comment]
Understood. Thanks.

**Comment by dpvc** [comment]
I could make the About box say "using local or web TeX fonts" if that would be better.

**Comment by pkra** [comment]
I think it's fine.
