### ISSUE TITLE
DOM structure for SVG output

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1310]
This is just a question. I noticed that the "global" SVG is a sibling to an empty div with  `id="MathJax_SVG_Hidden"`; is this intentional?

**Comment by dpvc** [comment]
Yes.  The `MathJax_SVG_Hidden` div is used to measure the sizes of characters that are unknown.  The global SVG element is where the shared character paths are stored.  They can't be combined, if that is what you are after.

**Comment by pkra** [comment]
Ah, that makes sense -- thanks! 

> They can't be combined, if that is what you are after.

No, I just couldn't figure it out.
