### ISSUE TITLE
TeX input: improve heuristics for invisible apply

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1312]
From the discussion at https://github.com/mathjax/MathJax/issues/1305#issuecomment-158961615

> The TeX input jax does put invisible times following things like \sin and \dim, but only in certain circumstances, and (unfortunately) that doesn't currently include when \dim is followed by another operator. The heuristic for adding invisible times could be altered to include more situations, and probably should.

**Comment by physikerwelt** [comment]
I think we should collect some reasonable testcases:
```
\arcsin\sin\phi
\operatorname{x}\operatorname{y}
```

**Comment by dpvc** [comment]
You also want 

    \sin\left(x\right)

as a test case (it doesn't currently get the function apply.

**Comment by dpvc** [comment]
The `issue1312` branch of my fork of MathJax implements an improved algorithm for adding the invisible function apply operation, and it does handle the three cases shown above.

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> In testsuite

LaTeXToMathML/issue1312.html

**Comment by physikerwelt** [comment]
@dpvc Yes it works great. I did already cherry pick your change to mathoid.

**Comment by physikerwelt** [comment]
@dpvc have a look at http://math.beta.wmflabs.org:8080/wiki/User:Admin

**Comment by physikerwelt** [comment]
... oh I see the space between ```\dim \mathrm{im}(f)``` is still missing... It sems that I did not check carefully enough this morning

**Comment by dpvc** [comment]
OK, I added some more changes that should handle this and some other situations.

More test cases:

```
\dim\mathrm{im}(f)
\dim\begin{vmatrix}x\end{vmatrix}
````

**Comment by physikerwelt** [comment]
lgtm http://math.beta.wmflabs.org:8080/wiki/User:Admin

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
Test updated to include new cases.
