### ISSUE TITLE
MathML equivalent of LaTeX HTML Extension

### ISSUE THREAD

**Issue by spaetzel** [mathjax/MathJax#1313]
Would be great to get a MathML equivalent of the new [TeX HTML Extension](https://docs.mathjax.org/en/v2.5-latest/tex.html#html)

Probably be implemented via custom attributes on MathML tags. Such as

    <math>
        <mi mjax:class="red">X</mi>
         <mo>=</mo>
        <mi mjax:class="green">3</mi>
    </math>

**Comment by pkra** [comment]
You can use classes already. However, just as in the TeX input case, not all CSS will affect the output and the styles will have to be either MathML agnostic or include suitable styling for HTML and SVG output. For a random example, see http://codepen.io/pkra/pen/MadyNO.

**Comment by spaetzel** [comment]
Great. That solves it for me.
