### ISSUE TITLE
High memory footprint with Firefox 41/42 on Linux

### ISSUE THREAD

**Issue by kaplun** [mathjax/MathJax#1315]
Several users of our service http://inspirehep.net/ are reporting memory-footprint related troubles lately with Firefox 41/42 on Linux to render pages containing several MathJax.

I am indeed able to reproduce the issue. 

E.g. visiting: https://inspirehep.net/author/profile/M.Duerr.1 on Firefox 41/42 is causing the Linux `X` server to consume a lot memory for several seconds. On machine with small RAM this might lead the system to a crash.

The problem is only on these latest versions of Firefox and only on Linux.

**Comment by pkra** [comment]
I don't see any MathJax output on that page and from the MathJax log it looks like it only loaded its configuration file.

Could you clarify how this is related to MathJax?

**Comment by kaplun** [comment]
Indeed I was to look into another record having much more visible MathJax usage, but then realized that when switching off MathJax the memory footprint is still high. So indeed it was a false positive. Sorry for the noise!

**Comment by pkra** [comment]
No problem. Thanks for following up.
