### ISSUE TITLE
SVG output drops a non-breaking space in mtext

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1316]
[From the User Group](https://groups.google.com/forum/#!topic/mathjax-users/Se2mxUysWtk).

The nbsp in `$\text{$x$ y}$` is lost but not in `$\text{$x$ y z}$`.  This only affects the SVG output.

**Comment by dpvc** [comment]
Actually `\text{ x}` is sufficient to show the issue.

**Comment by poulter7** [comment]
Hi Peter, Davide

I attempted to take a look at this issue. It seems like a problem with the old code adjusting the svg width, not having quite the desired effect here. I wasn't able to get the full test suite working from MathJax-Test, so I've not ran any regression.

**Comment by pkra** [comment]
Thanks, Jonathan. Small warning: review will be a bit slow (end of year etc).

**Comment by poulter7** [comment]
No problem 😊

**Comment by dpvc** [comment]
@poulter7, It turns out that the real problem was severe lines lower, where nested groups are removed to simplify the SVG structure.  The spacing was being lost.  I've made a commit that fixes that problem rather than introduce the unneeded rectangle element.  See the commit listed above.

**Comment by poulter7** [comment]
I'll check it out, thanks Davide

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> In testsuite

MathMLToDisplay/Presentation/TokenElements/mtext/issue1316.html
