### ISSUE TITLE
config not loading when rendering thousands of pieces of latex.

### ISSUE THREAD

**Issue by henzestplus** [mathjax/MathJax#1317]
I am accessing the cdn files using http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML

Prior to that, I have added a config block where I use MathJax.Hub.signal.Interest() where I do some action based on the message I get. It has to process hundreds or thousands of latex. but somehow, the cdn config file http://cdn.mathjax.org/mathjax/latest/config/TeX-AMS_HTML.js gives a "file load error". loading the file in a tab in chrome works just fine. also, when just processing a few, the error does not show.

**Comment by pkra** [comment]
Thanks for the bug report. 

Could you provide a live sample that exhibits the problem? Thousands of equations are usually not a problem for MathJax.

Please also take a look at https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports for some advice on additional information you might provide.
