### ISSUE TITLE
TeX input: textrm affects math mode inside its scope

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1321]
[From the user group](https://groups.google.com/d/msg/mathjax-users/GZ2BSfGAYBc/7Moa7XYOBAAJ)

`\textrm{$x$}` produces `<mi mathvariant=normal>x</mi>` which is not consistent with real TeX.

**Comment by dpvc** [comment]
The `issue1321` branch of my fork of MathJax fixes this issue.

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> In testsuite

LaTeXToMathML/mathvariant/issue1321.html
