### ISSUE TITLE
Content-mathml extension doesn't handle empty presentation mathml nodes properly

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1323]
The content-mathml extension turns empty nodes into `<mi>` containing the name of the node (for things like `<sin/>`), but when the nodes are presentation MathML nodes (like '<mrow/>' or `<mo/>`), this causes the name of that node to be inserted into the expression.

**Comment by dpvc** [comment]
The `issue1323` branch of my fork of MathJax fixes this issue.

**Comment by dpvc** [comment]
This turns out to be a duplicate of #1153.  I'm classing that one, since I already made the commit keyed to this one.

**Comment by pkra** [comment]
:+1:

**Comment by dpvc** [comment]
=> Merged.

**Comment by dpvc** [comment]
=> In testsuite

MathMLToDisplay/Content/issue1323.html
