### ISSUE TITLE
NativeMML output is too wide in some cases

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1325]
The output for `\left(x\right)` in NativeMML output in Firefox is too wide.  This appears to be due to a bug in Firefox that gets the width wrong when the container element has `display:inline-block`.  The NativeMML output has two containers marked this way, and removing the `inline-block` causes the spacing to be correct.  The `inline-block` was there originally to get the spacing right in other circumstances, but perhaps that is no longer needed.

**Comment by pkra** [comment]
Closing this as `won't fix`.
