### ISSUE TITLE
simplifying npm workflows

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1328]
Despite MathJax not being a set of CommonJS modules, we could support developers with an npm workflow a bit better.

Besides the obvious -- adding a package.json and publishing it -- I would like to propose to add the PNG fonts to an .npmignore file so as to make the installation bearable.

@dpvc @zorkow any thoughts?

**Comment by dpvc** [comment]
Have you checked that the `.npmignore` file will actually prevent the files from being downloaded originally?  My suspicion is that the whole repository will be cloned, and then the unwanted files removed.

**Comment by pkra** [comment]
> Have you checked that the .npmignore file will actually prevent the files from being downloaded originally?

That's how I understand [their docs](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package): just like `.gitignore`, the files won't be pushed to NPM. 

(I also noticed that I could clean it up a bit given their defaults.)

**Comment by dpvc** [comment]
OK, sounds good.

**Comment by dpvc** [comment]
Is the plan to be able to use this in MathJax-node in place of the current special branch?

**Comment by pkra** [comment]
> Is the plan to be able to use this in MathJax-node in place of the current special branch?

That idea also occurred to me :smile:

**Comment by pkra** [comment]
As per F2F: how to identify that a package is not actually node compatible? 

I've found this ongoing discussion https://github.com/npm/npm/issues/4321. It seems that using keywords like `browser-only` and `browser` are currently the pragmatic choice (easily confirmed in the wild) so I'm adding them. 

(One could use a `browser` property but that is apparently already used by browserify so I'd prefer to avoid that particular confusion.)

**Comment by pkra** [comment]
Testing with `npm pack`, the package is ~20MB and ~60MB unzipped. The PNG fonts are not included as desired.

**Comment by dpvc** [comment]
I have no doubt that the final copy will not include the png images.  My question is about when the package is checkout out, will the entire package be checked out and then the `.npmignore` files removed?  Since the `package.json` lists the repository as

```
"repository": {
   "type": "git",
   "url": "git://github.com/mathjax/MathJax.git"
 },
```

I don't see how loading the png files at least initially will be avoided, as checking out that repository load everything unless the npm service hosts their own copy (I haven't checked whether that is what they do, but that seems to be what you are implying above).

In any case, I guess the only way to check it is to try it.

**Comment by pkra** [comment]
IIUC the `repository` entry is only for documentation purposes, see https://docs.npmjs.com/files/package.json#repository. 

You can simulate what happens when publishing / installing by following https://docs.npmjs.com/misc/developers#before-publishing-make-sure-your-package-installs-and-works. 

NPM generates a tar ball from the folder you run `npm publish` in and uploads it to npm. (Note: ANYTHING will be included so we need to remember to do so from a clean clone without any personal crud around ;-) )

**Comment by dpvc** [comment]
OK, thanks for the clarification.  I just remember the trouble we were having when we tried to do this from github before.  If they are using their own tarball, then that certainly makes sense.

**Comment by dpvc** [comment]
=> Merged
