### ISSUE TITLE
Fetching configs asynchronously via params

### ISSUE THREAD

**Issue by amirmog** [mathjax/MathJax#1334]
I'm trying to reference to the CDN but it seems that the config params that I'm passing to the http call are not able to async fetch the configuration file hence 404ing on the config file (TeX-MML-AM_CHTML.js).

<script type="text/javascript" async src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>

I was wondering if this is a known issue or that if I'm doing anything incorrectly?

Thanks,

**Comment by dpvc** [comment]
The `TeX-MML-AM_CHTML.js` configuration file is part of v2.6 that is currently in beta test, so it is not available at the `cdn.mathjax.org` address yet.  We are in the final stages of testing and expect to make the 2.6 release very soon.

**Comment by dpvc** [comment]
Just to be clear, `TeX-MML-AM_CHTML.js` is not in 2.5 because it uses the new CommonHTML output jax that is part of v2.6.  Note, however, that `TeX-MML-AM_HTML.js` is available in 2.5, so perhaps you could use that for now.

**Comment by amirmog** [comment]
Okay great thanks for the clarification.
Any rough timeline as to when I should expect the 2.6 to be released?

Thanks again.
