### ISSUE TITLE
mhchem doesn't handle decimal numbers properly

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1336]
According to [this post](http://meta.chemistry.stackexchange.com/questions/1636/chemical-formulas-with-fractional-numbers-are-displayed-wrongly/3036), mhchem should handle

    \ce{0.5H2O}

as `0.5` times `H2O`, but currently, it uses the equivalent of `0\cdot 5` instead.

Note, however, that 

    \ce{NEt3.3HF}

should be `NEt` subscripted with 3, with a `\cdot` and `3HF`.  So it is a bit subtler than it might at first appear.

**Comment by pkra** [comment]
Oh fun.

**Comment by mhchem** [comment]
This is the author of the original mhchem LaTeX package. I will create a JavaScript parser for mhchem in 2016 that should yield more compatibility between LaTeX and MathJax.

**Comment by pkra** [comment]
Just a comment to reference @mhchem's awesome ongoing work at https://github.com/mathjax/MathJax/pull/1414

**Comment by dpvc** [comment]
The new version of mhchem (#1414) does resolve this issue.
