### ISSUE TITLE
MathJax Live Demo throws processing error on MathML

### ISSUE THREAD

**Issue by rylan** [mathjax/MathJax#1341]
### Issue Summary 

MathJax Live demo throws an error on MathML equation

### Steps to Reproduce
Enter the following equation into the textarea

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mi>f(x)=</mi>
    <msub>
      <mi>a</mi>
      <mn>0</mn>
    </msub>
    <mo>+<mo><munderover>
  <mo>&#x2211;</mo>
  <mtext>n=1</mtext>
  <mi>&#x221E;</mi>
</munderover><mtext>(<mtext><msub>
  <mi>a</mi>
  <mn>n</mn>
</msub><mtext>cos<mtext>(<mtext><mfrac bevelled="true">
  <mtext>n&#x3C0;x</mtext>
  <mi>L</mi>
</mfrac><mtext>)<mtext><mtext><mo>+</mo><msub>
  <mi>b</mi>
  <mn>n</mn>
</msub><mtext>sin<mtext>(<mtext><mfrac bevelled="true">
  <mtext>n&#x3C0;x</mtext>
  <mi>L</mi>
</mfrac><mtext>)<mtext><mtext><mtext>)<mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mtext></mo></mo>
  </mrow>
</math>
```

### Expected result

In my setup the equation is rendering as follows
![equation](https://cloud.githubusercontent.com/assets/209707/11935583/9b8e7370-a7d6-11e5-8dbd-1abd1d643ccf.png)

**Comment by dpvc** [comment]
Your MathML is invalid.  You have nested `<mtext>` elements, which is not allowed by the MathML spec, and your first `<mo>` is not properly closed, so it produces improperly nested elements as well.
Note the long list of `</text>` at the end, and the `</mo></mo>`.  These indicate improperly nested tags.

It appears that you frequently forget the `/` in the close tags (e.g., `<mo>+<mo>` should be `<mo>+</mo>`, and `<mtext>(<mtext>` should be `<mtext>(</mtext>`).  Fixing that should get you a version that displays properly.  For example, 

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <mi>f(x)=</mi>
    <msub>
      <mi>a</mi>
      <mn>0</mn>
    </msub>
    <mo>+</mo>
    <munderover>
      <mo>&#x2211;</mo>
      <mtext>n=1</mtext>
      <mi>&#x221E;</mi>
    </munderover>
    <mtext>(</mtext>
    <msub>
      <mi>a</mi>
      <mn>n</mn>
    </msub>
    <mtext>cos</mtext>
    <mtext>(</mtext>
    <mfrac bevelled="true">
      <mtext>n&#x3C0;x</mtext>
      <mi>L</mi>
    </mfrac>
    <mtext>)</mtext>
    <mo>+</mo>
    <msub>
      <mi>b</mi>
      <mn>n</mn>
    </msub>
    <mtext>sin</mtext>
    <mtext>(</mtext>
    <mfrac bevelled="true">
      <mtext>n&#x3C0;x</mtext>
      <mi>L</mi>
    </mfrac>
    <mtext>)</mtext>
    <mtext>)</mtext>
  </mrow>
</math>
```

displays correctly for me.

FYI, your use of `<mtext>` is pretty unusual.  I would expect things like `<mtext>)</mtext>` to be `<mo>)</mo>`, `<mtext>n&#x3C0;x</mtext>` to be `<mrow><mi>n</mi><mi>&#x3C0;</mi><mi>x</mi></mrow>`, `<mtext>n=1</mtext>` to be `<mrow><mi>n</mi><mo>=</mo><mn>1</mn></mrow>`, and `<mi>f(x)=</mi>` to be `<mi>f</mi><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow><mo>=</mo>`.  you have completely destroyed any semblance of the semantics of your expression.

**Comment by rylan** [comment]
Thanks @dpvc
