### ISSUE TITLE
Def, providecommand, etc not working

### ISSUE THREAD

**Issue by process91** [mathjax/MathJax#1344]
I'm using the cdn to load the latest (it currently loads 5.3) MathJax, and when trying to use def or providecommand in inline math mode it just turns red. For instance:

$\def{\NN}{\mathbb N}$ and then $\NN$ results in both math items being rendered as red error text.

This can also be seen on StackEdit.io.

**Comment by dpvc** [comment]
Your `\def` command uses incorrect syntax: there should not be braces around the control sequence being defined.  If you use `$\def\NN{\mathbb N}$` then it should work.  (You can use braces with `\newcommand`, but not `\def`.)  So I'm marking this as "expected behavior".

**Comment by process91** [comment]
Ok, thanks for the response.

Just for clarity, is providecommand not supported? (I was getting errors
with this using either syntax.)

Michael Boratko

**Comment by dpvc** [comment]
> is providecommand not supported?

Correct.  Also, the LaTeX commands always act like `\def`, so they don't check whether the macro is defined or not, and never produce errors.
