### ISSUE TITLE
improve npm publication

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1346]
Pushing to npm (see #1328) was botched and we un-published 2.6.0. Sigh. 

Let's improve this using CI.

**Comment by wil93** [comment]
+1

For the moment I'm using this workaround

```json
"dependencies": {
  "mathjax": "github:mathjax/MathJax#master"
}
```

But this causes `npm install` to take a lot of time.

**Comment by pkra** [comment]
FYI, we're wrapping up 2.6.1 https://github.com/mathjax/MathJax/milestones/MathJax%20v2.6.1

**Comment by pkra** [comment]
Succesfully tested.

**Comment by dpvc** [comment]
Great!
