### ISSUE TITLE
Copying and pasting results in duplicate output

### ISSUE THREAD

**Issue by a3nm** [mathjax/MathJax#1350]
When I copy text rendered by MathJax (e.g., on [CSTheory](https://cstheory.stackexchange.com/questions/33054/is-it-p-hard-to-compute-the-number-of-antichains-of-a-distributive-lattice) or on [my website](http://a3nm.net/work/research/questions/)) and paste it in a plain text editor, the contents of equation appear twice, e.g., on the first page:

> An antichain of a poset (P,<)(P,<) is a subset of pairwise incomparable elements, namely, a subset A⊆PA⊆P such that there are no x,y∈Ax,y∈A with x<yx<y. By a result of Provan and Ball, it is known that it is #P-hard, given a poset, to compute its number of antichains.

I can reproduce this with Firefox and Chromium. It appears that the contents of the MJX_Assistive_MathML elements are copied in addition to the rendered contents.

Is there a way to ensure that copying and pasting MathJax rendered text does not result in this?

**Comment by dpvc** [comment]
We should probably add `user-select: none` (and all its browser-specific versions) to the `MJX_Assistive_MathML` CSS to prevent that (plus `unselectable: on` for older IE and Opera).

For now, you can use the MathJax menu to uncheck "Assistive MML" in the "Math Renderer" submenu of the "Math Settings" menu.  That will remove the assistive MathML, so it won't get copied.

**Comment by pkra** [comment]
> We should probably add user-select: none (and all its browser-specific versions) 

[MDN reads terribly](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) but I guess it's supported widely enough.

**Comment by dpvc** [comment]
It looks like it may be a CSS3 property.  Here is a [working draft](http://www.w3.org/TR/2000/WD-css3-userint-20000216#user-select) of a specification that includes it.  My experience is that the dire warnings on the MDN documentation is not always accurate.

**Comment by dpvc** [comment]
The `issue1350` branch of my fork of MathJax should resolve the problem.

**Comment by dpvc** [comment]
=> Merged.
