### ISSUE TITLE
Make `tabindex=0` optional

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1352]
As per F2F.

We will add a menu option to switch off `tabindex=0` on MathJax output. This will allow users to disable it should they want to.

The Menu structure will be: Math Settings => Renderer => checkbox "Include in tab order" (below the AssistiveMML checkbox)

The docs will strongly discourage developers from initially disabling this (by means of configuration) as it will render the menu inaccessible.

**Comment by pkra** [comment]
From https://github.com/mathjax/MathJax/issues/893#issuecomment-173273238

> it's not that I want to remove it necessarily, it's more to be able to manage it myself. If I have a list with tabindex 1,2,3,4 and MathJax comes in the middle and places a 0 giving 1,0,2,3,4 - it is very difficult to manage this

We should consider this use case.

**Comment by pkra** [comment]
> We should consider this use case.

We will not provide any internal functionality for this. Instead, we suggest to hook into the `new math` signal since it passes the actual element name and thus allows developer to then set the tabindex as they see fit.

**Comment by pkra** [comment]
See also https://github.com/mathjax/MathJax/pull/1363

**Comment by dpvc** [comment]
This is handled by PR 1376.

**Comment by dpvc** [comment]
=> In test suite.

Configuration/MathMenu/tabindex-1.html
Configuration/MathMenu/tabindex-2.html
Configuration/MathMenu/tabindex-3.html
