### ISSUE TITLE
Oxford University Press: OSO Math display issue on new content - March updates

### ISSUE THREAD

**Issue by Anastasiouef** [mathjax/MathJax#1355]
Editorial raise the following problem with Maths display on this OSO title on Staging2 (this is a title from the March 2016 release): 

Math Issue - Blocker: 

Chapter 26, math processing error for second half of page. (Chrome and IE and firefox) - 

Looks like up to page 635 displays maths ok, thereafter in this chapter the display is strange or missing. 

Most of the math rendering seems to be fine. However, there are some errors being reported by MathJax? (the javascript MathML renderer). I’ve run the MathML against W3C’s MathML Validator ( http://www.w3.org/Math/validator/ ) and it passes okay, so this looks like an issue with MathJax?. The error seems to be caused by MathJax? not liking the attributes on <mfenced/> elements in the MathML

http://oso.upso-staging2.pubfactory.com/view/10.1093/acprof:oso/9780198736912.001.0001/acprof-9780198736912-chapter-26

Could you please investigate?

Thanks,
Efi

**Comment by pkra** [comment]
Could you please write me an email to peter.krautzberger@mathjax.org?

**Comment by Anastasiouef** [comment]
you will need access details to reproduce the issue. Should I add screen shots?

**Comment by pkra** [comment]
Thanks, @Anastasiouef I'll follow up by email.
