### ISSUE TITLE
Uncaught HierarchyRequestError with Bower in AngularJs with Rails

### ISSUE THREAD

**Issue by xiaopow** [mathjax/MathJax#1357]
Installed through Bower
```bower install --save MathJax```

required in application.js
```//= require MathJax```

runs server and load page, presented with error
```Uncaught HierarchyRequestError: Failed to set the 'body' property on 'Document': The 1st argument provided is either null, or an invalid HTMLElement object.```

coming from 
```
if (!document.body) {
   document.body = document.getElementsByTagName("body")[0]
}
```

**Comment by pkra** [comment]
You might want to post a minimal live sample exhibiting a MathJax specific problem or try a more general forum like StackOverflow where Angular and Rails people might help you narrow the problem down.

**Comment by pkra** [comment]
Was this closed because it was resolved? We're happy to help with any MathJax issue.

**Comment by xiaopow** [comment]
Well, I ended up using the CDN with delay start up until configured and I place the configured line in the page where Mathjax is used, now it works fine. Before using the delay setting, it had the same problem as I mentioned above when I am using CDN.
```
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_CHTML&delayStartupUntil=configured">
  </script>
```
in js of the page where MathJax is used
```
MathJax.Hub.Configured();
```

**Comment by pkra** [comment]
> Well, I ended up using the CDN with delay start up until configured and I place the configured line in the page where Mathjax is used, now it works fine. Before using the delay setting, it had the same problem as I mentioned above when I am using CDN.

Thanks for the follow-up. A document without body will cause problems if you load MathJax without delaying is initial typesetting run. I don't think there's a smarter way for us to fail; @dpvc?

**Comment by pkra** [comment]
> I am not too sure about how to set up MathJax with custom configuration using bower with Angular and Rails. The only configuration I need is delayStartUpUntil=configured.

I'm guessing you'll need to write a custom configuration. Did you see http://docs.mathjax.org/en/latest/configuration.html#using-a-configuration-file?

**Comment by xiaopow** [comment]
> I'm guessing you'll need to write a custom configuration. Did you see http://docs.mathjax.org/en/latest/configuration.html#using-a-configuration-file?

Yes, I did, but angular with rails will acquire JS libraries in application.js I was having troubling adding the following line to head

```
<script type="text/javascript"
   src="path-to-MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML&delayStartupUntil=configured">
</script>
``` 
Can you tell me if the following inline config is correct if i want to add it to my code?
```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    delayStartupUntil: configured
  });
</script>

**Comment by dpvc** [comment]
Basically right, but you need quotation marks around the `configured`, as in

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    delayStartupUntil: "configured"
  });
</script>
```

**Comment by xiaopow** [comment]
Hey guys, so I tried using bower again with rails. I am still getting the error, the reason is the `MathJax.Hub.Conifg` script runs after MathJax is served through the rails asset pipeline. I don't know how else to fix this.

**Comment by xiaopow** [comment]
@dpvc So I managed to add my own configuration file and load it before loading MathJax. I believe I have managed to start MathJax without errors, but it is not processing Ascii Math properly. Am I missing something here?

MathJaxConfig/config.js
```
window.MathJax = {
  config: ["TeX-AMS-MML_HTMLorMML.js"],
  delayStartupUntil: "configured"
};
```

I require the config.js before the rest of the MathJax files.
```
//= require MathJaxConfig/config
//= require MathJax/MathJax
//= require mathJax/extensions/MathMenu
//= require mathJax/extensions/MathZoom
//= require MathJax/config/TeX-AMS-MML_HTMLorMML
```

But it is not rendering my ASCIImath properly.

I run the following code on the page where I need MathJax
```
MathJax.Hub.Queue(["Typeset",MathJax.Hub]);
MathJax.Hub.Configured();
```
![screen shot 2016-02-14 at 10 15 44 pm](https://cloud.githubusercontent.com/assets/10229915/13034150/8fe9893e-d368-11e5-8b12-21bd898354cf.png)

**Comment by xiaopow** [comment]
Nevermind, I am sticking with the working CDN method.

**Comment by dpvc** [comment]
> it is not processing Ascii Math properly

That is because you have used the `TeX-AMS-MML_HTMLorMML` configuration file, which does not include the AsciiMath input format.  This one is TeX with the AMS extension, and MathML input, with HTML or MathML output, depending on the browser (see the [documenttion](http://docs.mathjax.org/en/latest/config-files.html#the-tex-ams-mml-htmlormml-configuration-file)).  You probably want one of the ones that start with `TeX-MML-AM` (see the [documentation](http://docs.mathjax.org/en/latest/config-files.html)).

**Comment by dpvc** [comment]
You also probably don't need

```
//= require mathJax/extensions/MathMenu
//= require mathJax/extensions/MathZoom
//= require MathJax/config/TeX-AMS-MML_HTMLorMML
```

as MathJax will load these itself, but you might have to set the `root` in your `config.js` file so that MathJax knows where its other files are (I'm not sure how Angular handles loading MathJax, but I suspect it may make it hard for MathJax to figure that out).  Something like

```
window.MathJax = {
  config: ["TeX-AMS-MML_HTMLorMML.js"],
  AuthorConfig: function () {
    MathJax.Ajax.config.path = "./MathJax";  // or whatever is the path to MathJax.
  }
};
```

Finally, I don't think you need to set `delayStartupUntil: "configured"`, but if you do, there is no need to use `MathJax.Hub.Queue(["Typeset",MathJax.Hub]);`, as the typesetting will occur automatically when you do the `Mathjax.Hub.Configured()` call.

**Comment by dpvc** [comment]
(Sorry, it should have been 'AuthorInit` not 'AuthorConfig`.  I've changed it above.)

**Comment by xiaopow** [comment]
@dpvc So I followed your suggestions, the only thing that doesn't seem to work is

```
MathJax.Ajax.config.path = "./MathJax";
```

I am getting the following errors.

![screen shot 2016-02-16 at 1 21 12 pm](https://cloud.githubusercontent.com/assets/10229915/13068065/60a839e0-d4b2-11e5-93e0-f5be12d582d7.png)

**Comment by pkra** [comment]
It looks like `MathJax.js` was renamed which breaks things easily.

**Comment by xiaopow** [comment]
I believe it's because MathJax was compiled with other js files into one big minified application.js.

**Comment by pkra** [comment]
> I believe it's because MathJax was compiled with other js files into one big minified application.js.

MathJax cannot handle that use yet, I'm afraid.
