### ISSUE TITLE
[commonHTML, 2.6.0] asciimath input: "vec" arrow position shifted

### ISSUE THREAD

**Issue by beeplin** [mathjax/MathJax#1359]
just open the live demo window on the mathjax homepage and try:
```
`vec x`
$\vec x $
```
the two return different results, the first of which (the asciimath one) has a wrong arrow position. it's a calculation error for the padding-left of the ".mjx-over" span: 
```
<span ... class="mjx-over" style="...padding-left:0.201em...">
```

**Comment by pkra** [comment]
Thanks so much for spotting the issue and concise report. FWIW, comparing to the TeX input is not always useful as they can differ; the underlying MathML is the relevant part which can differ (and does in this case) but strangely that's not the problem either. We'll look into i.

@dvpc this seems specific to the asciimath input jax (not asciimath itself)? Using the underlying MathML does not exhibit the problem.

**Comment by dpvc** [comment]
@pkra, the difference is that the AsciiMath input jax sets the `useMMLspacing` flag, and NativeMML doesn't.  When MathML spacing is in effect, the arrow accent is considered to be in infix position by the operator dictionary rules, and so it gets infix spacing on either side of it.  The CHTML output jax overrides that in its CSS, but didn't take that override into account in its width computations, so got the spacing wrong.  I have a fix and will post it later today.

**Comment by dpvc** [comment]
The `issue1359` branch of my fork of MathJax includes the fix.

**Comment by beeplin** [comment]
U guys r really awesome~!
btw this is my first issue post on github....

**Comment by dpvc** [comment]
=> Merged

**Comment by pkra** [comment]
@beeplin thanks for the kind words and for a good bug report. It takes a village.

**Comment by dpvc** [comment]
=> In test suite

MathMLToDisplay/Presentation/ScriptsAndLimits/mover/issue1359.html
