### ISSUE TITLE
CommonHTML causes error with nested mover having stretchy bases [was: MathML rendering error]

### ISSUE THREAD

**Issue by zopyx** [mathjax/MathJax#1360]
This HTML file renders with a PDF renderer (based on MathJax) with errors. And it is reproducible with Chrome + MathJax.

See tests 19 +21 
[vivliostyle-output.pdf](https://github.com/mathjax/MathJax/files/104902/vivliostyle-output.pdf)

**Comment by dpvc** [comment]
Can you link to the HTML file as well?

**Comment by pkra** [comment]
cc @kwkbtr @frivoal

**Comment by kwkbtr** [comment]
The original issue is here: vivliostyle/vivliostyle-formatter-issues#34

**Comment by dpvc** [comment]
OK, thanks.  I am looking into it.  It is a problem with CHTML when there are nested `munderover` elements.

**Comment by pkra** [comment]
Thanks @kwkbtr !

**Comment by dpvc** [comment]
The `issue1360` branch of my fork of MathJax includes a fix.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> In test suite

MathMLToDisplay/Presentation/ScriptsAndLimits/mover/issue1360.html
