### ISSUE TITLE
[CommonHTML] commutative diagram throws error

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1361]
The following throws a math processing error only with the CommonHTML output. I'll make a more minimal case when I get a chance.

```latex
$\require{AMScd}$
\begin{equation*}
 \begin{CD} \operatorname {Gal}(\bar F/F)@&gt;&gt;&gt;\operatorname {Gal}(F^{un}/F)\\@V\rho VV @VV{\operatorname {Frob}\mapsto \sigma _G}V\\W(\Phi _G)\rtimes \langle \sigma _G\rangle @&gt;&gt;w\rtimes \tau \mapsto \tau &gt; \langle \sigma _G\rangle . \end{CD}
\end{equation*}
```

**Comment by pkra** [comment]
It's not a TeX input problem but the equivalent MathML has the same problem.

**Comment by pkra** [comment]
Hm... This looks like a corrupted cache now. I'll investigate.

**Comment by dpvc** [comment]
This is due to the same source as issue #1360, and the fix I have done for that in the `issue1360` branch resolves this as well.

**Comment by pkra** [comment]
Oh, you're fast -- thanks!
