### ISSUE TITLE
Occurs the error "Math Processing Error" in both MathJax 2.5 and MathJax 2.6

### ISSUE THREAD

**Issue by mycwcgr** [mathjax/MathJax#1368]
I use the field "ForLatext" in default.aspx to display LaTex  MathML, and AsciiMath expresstion which input by user, it worked well in MathJax 2.4.

Now I upgrade MathJax 2.4 to MathJax 2.6 , it will display "Math Processing Error " if I input letter quickly. How to fix it ? Thanks!

MyConfig.js

```
window.MathJax = {
    extensions: ["tex2jax.js", "asciimath2jax.js", "toMathML.js"],
    "HTML-CSS": { imageFont: null },
    showMathMenu: false,
    showMathMenuMSIE: false,   
    TeX: { extensions: ["AMSmath.js", "AMSsymbols.js", "noUndefined.js"] },
    jax: ["input/TeX", "input/AsciiMath", "output/HTML-CSS"]
};

```

Default.aspx
```

<%@ Page Title="HostMath - Online LaTeX formula editor and browser-based math equation editor" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" ValidateRequest="false"  %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">  

  
    <script type="text/javascript" src="Js/MyConfig.js"></script>
    <script type="text/javascript" src="Math/MathJax.js"></script>       
     ...   
</asp:Content>


<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
      ...     
      <div id="ForLatext">\[{}\]</div>

      <div id="ForASC">`{}`</div>        

</asp:Content>
```

--------------------------------------------------------
BTW, if I add "fast-preview.js" to "extensions", it reduce the frequency of the error "Math Processing Error" , but the displayed font of LaTeX expression is changed!

MyConfig.js
```

window.MathJax = {
    extensions: ["tex2jax.js", "asciimath2jax.js", "toMathML.js", "fast-preview.js"],
    "HTML-CSS": { imageFont: null },
    showMathMenu: false,
    showMathMenuMSIE: false,
  
    TeX: { extensions: ["AMSmath.js", "AMSsymbols.js", "noUndefined.js"] },
    jax: ["input/TeX", "input/AsciiMath", "output/HTML-CSS"]
};
```

**Comment by pkra** [comment]
Thanks for the report. Unfortunately, there's not enough information here to make an educated guess. As suggested in https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports, it's best to create a live sample that exhibits the problem.

**Comment by dpvc** [comment]
@pkra, this may be the same as issue #1384, and the solutions there will help.  Also, disabling fast-preview during the editing (like the new editing code for SE) might help.
