### ISSUE TITLE
[TeX input] support for Cyrillic

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1369]
This is closely related to #1120 but could be started without it.

Traditionally, TeX needs macros to support Cyrillic. The standard one seems to be [cyracc.def](http://www.tug.org/texlive//devsrc/Master/texmf-dist/tex/plain/amsfonts/cyracc.def) which is used in much production content.

**Comment by dpvc** [comment]
@pkra, when you added this to v2.x.x, were you thinking about the example extension that I went you back in February?  Would we need to add a Cyrillic web font, or rely on system fonts?  Your 1120 links to some potential font sources.

**Comment by dpvc** [comment]
@pkra ping

**Comment by pkra** [comment]
I think I added this before this milestone moved from "all the things 2.x" to "2.7" (but yes, it must have been inspired from your example).

I don't mind kicking it out or doing whatever you want to do.

**Comment by dpvc** [comment]
I'd prefer not to do it without proper font support.  We could do it with the STI fonts now, but not the MathJax TeX fonts.  If you want me to build a Cyrillic font to include in the MathJax fonts, I can do that.  Probably would not be too hard.

**Comment by dpvc** [comment]
The package you link to seems to have a different transliteration scheme than the one we did from the AMS style.  do we have anyone at AMS who knows about the different packages and could advise us on how to proceed?

**Comment by pkra** [comment]
Hm. Getting complicated. Do you want to discuss this at the next F2F?

**Comment by dpvc** [comment]
> Do you want to discuss this at the next F2F?

Sure.

**Comment by dpvc** [comment]
Maybe this should be a third-party extension in `[Contrib]`?

**Comment by pkra** [comment]
> Maybe this should be a third-party extension in [Contrib]?

Oh yes, that sounds like a good compromise for now.
