### ISSUE TITLE
[HTML-CSS] square root top line is too close to the number below

### ISSUE THREAD

**Issue by karoltarasiuk** [mathjax/MathJax#1370]
### Issue Summary

Square root top line is too close to the number below. I have also replicated the bug on latest develop branch using `unpacked/MathJax.js`.

### Steps to Reproduce

Simple go here: https://docs.staging.learnosity.com/demos/isolation/mathjax/260rendering.php

Or check this sample page:
```
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<!-- Copyright (c) 2010-2015 The MathJax Consortium -->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {inlineMath: [["$","$"],["\\(","\\)"]]}
});
</script>
<script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>

</head>
<body>

<p>
When $a \ne 0$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
$$x = {-b \pm \sqrt{b^2-4ac} \over 2a}.$$
</p>
<p>
text around \(\frac{\sqrt{123}}{123}\) text around
</p>
<p>
$\frac{\sqrt{123}}{123}$
</p>

</body>
</html>
```

### Technical details

* MathJax Version: develop - latest commit: 0740dd4735cee63809c1228ae69bb2531e03c3fe
* Client OS: MaxOS
* Browser: Chrome 48

**Comment by pkra** [comment]
Thanks for the detailed report. A few follow up questions.

* Since this is about a layout detail, could you add a screenshot to show what you see? 
* Which renderers (HTML-CSS, SVG, CommonHTML) are you seeing a problem with? I do see a minor issue with HTML-CSS.
* Your report points to the develop branch but your demo is using master. I'm guessing you see it on both?

**Comment by karoltarasiuk** [comment]
1. A screenshot with the issue:
![screen shot 2016-02-04 at 9 12 03 am](https://cloud.githubusercontent.com/assets/1845230/12798792/8a02b708-cb1f-11e5-9e55-d2ccdab051bf.png)


The top line of a square root is too close to the number.

2. The issue is observed in HTML-CSS.
3. Yes - I observed it first in the latest official release (which would be master), and then checked the develop branch as well just in case it could've been fixed there already.

**Comment by dpvc** [comment]
The `issue1370` branch of my fork of MathJax includes a fix for this.

**Comment by karoltarasiuk** [comment]
Confirming that it's working:
![screen shot 2016-05-09 at 3 04 49 pm](https://cloud.githubusercontent.com/assets/1845230/15104150/74980ef4-15f7-11e6-8c40-48fa02868e08.png)

**Comment by dpvc** [comment]
Thanks for the confirmation!

**Comment by dpvc** [comment]
==> Merged

**Comment by samfromlv** [comment]
It's still an issue with CommonHTML output.

Test page: https://yklstaticcontent.blob.core.windows.net/libs/mathjax/mathjax1370/test.html

Screenshot:
![image](https://user-images.githubusercontent.com/1714331/76234746-cc147100-6232-11ea-94d8-646ca864e3d9.png)

Chrome Version 80.0.3987.132 (Official Build) (64-bit) on Windows 10
