### ISSUE TITLE
[sample-dynamic-2] Uncaught RangeError when offline

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1374]
[Reported on the User Group](https://groups.google.com/d/msg/mathjax-users/CJcShRZxTpU/AgEWkI1gCAAJ).

* visit http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html
* go offline
* enter content that will require additional resources (e.g., $¾$)
* Get an error `Uncaught RangeError: Maximum call stack size exceeded`

**Comment by dpvc** [comment]
This is basically the same issue as #1401 (not gracefully handling inability to load a file).

**Comment by pkra** [comment]
This issue claims seniority -- not :wink:
