### ISSUE TITLE
Loading extension by full path only?

### ISSUE THREAD

**Issue by ickc** [mathjax/MathJax#1383]
According to [Third-party Extensions — MathJax 2.6 documentation](http://docs.mathjax.org/en/latest/options/ThirdParty.html?highlight=multiple%20location), it is said that

> Usually, third-party extensions have to be specified with their full paths (and matching loadComplete calls); this limits portability. To simplify this process, the MathJax configuration can include (possibly multiple) third-party locations for easier reference.

So, 3rd party extension can be loaded from full paths only?

And what does it mean by "possibly multiple"? Does it only mean different extensions can have different locations only? Or does it mean I can specify multiple locations for the same third-party extensions as a fallback option?

# Fallback for 3rd party extensions

In my site I have fallback options (by fallback.js) to load CSSs and JSs. But in MathJax, to load a third party extension, one need to write (using the example from the quoted link above):

```javascript
<script type="text/x-mathjax-config">
  MathJax.Ajax.config.path["Contrib"] = "//cdn.mathjax.org/mathjax/contrib";
</script>
```

And I'm unsure how one can load this with a fallback option.

# Can we load 3rd party extensions with Relative Path?

If MathJax allow a relative path for the extensions, then a fallback can be done easily. e.g. if MathJax is loaded from `https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full`, then loading the extension from `mathjax/contrib/` means `cdn.mathjax.org/mathjax/contrib`.

In this way, if the Fallback loads a fallback path, say, locally, then `mathjax/contrib` can follow the domain to the local 3rd party extension.

There are other advantages to allow relative path too. e.g. when building a site locally in development, it can load the local copy instead of the uploaded copy.

Sorry it was quite messy up there, I will try to summaries it here:

1. question:
    1. Are there any way to load the 3rd party extension with a fallback in the current version of MathJax?
    2. Is there a way to load the 3rd party extension with relative path but not full path?
2. feature request:
    1. Allow 3rd party extension to load with relative path.

Please let me know if I misunderstand anything and if there's already ways to handle what I'm asking. Thanks.

**Comment by ickc** [comment]
I found out that is a stupid question. Although the documentation mentioned that it has to be a full path, but I just tried and a relative path is ok for specifying the `MathJax.Ajax.config.path["Contrib"] = ` path. I should have tested before I ask.

Anything, may be this can be considered to a suggestion to a change in the documentation.

**Comment by pkra** [comment]
Sorry for the silence. Glad to see you worked it out yourself!
