### ISSUE TITLE
Math jax does not render on mac el capitan

### ISSUE THREAD

**Issue by sivi29y** [mathjax/MathJax#1386]
The titles say it.

**Comment by fkammer** [comment]
@sivi29y I think some more information would be very useful: wich version of MathJax are you using, which browsers are effected (versions!), which behavior are you expecting and what is happing instead. Maybe you can link a plunkr as well.

**Comment by pkra** [comment]
Please checkout https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md for some guidance on writing a bug report.
