### ISSUE TITLE
Math processing errors with MathJax 2.6.1 and CHTML

### ISSUE THREAD

**Issue by samfromlv** [mathjax/MathJax#1387]
We use MathJax for educational website www.yaklass.ru. Due rendering issues with MathJax 2.5 and new version of Chrome (line on the right of all formulas) we were forced to upgrade to 2.6. We decided to test CHTML output and started to get complaints from users about math display errors. For small fraction of users all math on the page were displayed as errors.

Screenshot of the problem from one of our users (we use [-!-] as message in errorSettings)
[user-screenshot](https://cloud.githubusercontent.com/assets/1714331/13036432/d4b487c4-d36f-11e5-9f79-a27983e0d1a0.jpg)

We were not able to reproduce this issue and deployed Google Analytics error tracking to collect some data before switching back to HTML-CSS output. 

Our code to track errors:

` MathJax.Hub.Register.MessageHook("Math Processing Error", function (message) {
            try {
                Yk.utils.trackEvent("MathJax/Error", "MathJax/Error/Processing", message[2] + '', null, true);
            }
            catch (e) { }
        });`

We collected errors for MathJax version 2.6.1 with CHTML.

Here are errors by browser:
[Analytics yaklassru Top Events 20160214-20160214.pdf](https://github.com/mathjax/MathJax/files/129892/Analytics.yaklassru.Top.Events.20160214-20160214.pdf)

with versions:
[Analytics yaklassru browsers with versions MathJax Errors 20160214-20160214 (1).pdf](https://github.com/mathjax/MathJax/files/129919/Analytics.yaklassru.browsers.with.versions.MathJax.Errors.20160214-20160214.1.pdf)

Here are page URLs (currently CHTML is disabled there, however formulas are the same that caused errors):
[Google Doc](https://docs.google.com/spreadsheets/d/16bigG9RC4ipxz6Ahu1PGiHZ0e_2ERoy8pyFE0q85mWg/edit?usp=sharing)

After switching back to HTML-CSS output we no longer see these errors.
Please let me know if any additional data from Google Analytics is required.

**Comment by pkra** [comment]
> We were not able to reproduce this issue

Same here.

While it's great that you have collected a long list of links where your users had trouble, I'm afraid we don't have the resources to debug your content or site setup, especially since we can't reproduce the problem. The best guess would be that those users with problems had a corrupted copy in their browser cache.

If you are able to create a reproducible sample, we'd be very happy to take a closer look.

**Comment by samfromlv** [comment]
We will work with users to reproduce the problem. I hope we can isolate this thing. CHTML works faster and we would like to use in production.

**Comment by pkra** [comment]
> We will work with users to reproduce the problem. I hope we can isolate this thing. 

Thanks, that would be great!
