### ISSUE TITLE
[Math Processing Error] on iOS / Safari

### ISSUE THREAD

**Issue by chrisbainbridge** [mathjax/MathJax#1388]
http://colah.github.io/posts/2015-08-Understanding-LSTMs/

iOS 9.2.1 / iPad Mini 2

Safari shows [Math Processing Error] where equations should be (e.g. 7 errors in first paragraph of "Step-by-Step LSTM Walk Through")

**Comment by pkra** [comment]
I cannot reproduce this, cf. https://saucelabs.com/beta/tests/e89f32e91de249d894238c3e5c9a0a34. 

Most likely this is due to corrupted files or mixed versions in the cache; try cleaning MathJax and its components from the browser cache.

**Comment by chrisbainbridge** [comment]
I cleared the cache and the issue was gone, only to reappear on another site and then disappear when I clicked refresh.  Odd. Perhaps a caching bug in Safari or some issue with using "mathjax/latest/MathJax.js" instead of a specific version. Closing since I can't reproduce the problem any more.

**Comment by pkra** [comment]
> Perhaps a caching bug in Safari

Some browsers need a restart to reliably clear the cache. Chrome is one (and nowadays even reports that in the developer console if you make a hard refresh for a particular page); I don't recall if Safari suffers the same. Let us know if it recurs.
