### ISSUE TITLE
Make the MathJax root configurable

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1403]
Currently, using 

    MathJax.Hub.Config({root: '...'});

doesn't cause the root to be copied to `Ajax.root`.  There should be a point at the end of the configuration process, but before files are loaded, where the `root` is copied to `Ajax.root`.  This may be complicated, because the combined configuration file is loaded before user configuration is processed, so that may need to be taken into account.

**Comment by dpvc** [comment]
The `issue1403` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

Configuration/Hub/root.html

**Comment by alexweissman** [comment]
This really needs to be added to the documentation.

**Comment by pkra** [comment]
Good point => https://github.com/mathjax/MathJax-docs/issues/182
