### ISSUE TITLE
Too much space around minus sign in some cases should be configurable.

### ISSUE THREAD

**Issue by garagebrewer** [mathjax/MathJax#1404]
When using AsciiMath and I use something like `A-B=C` the spacing around the minus seems reasonable.  When it's not 2 operands though, it seems like too much space.

Examples: `=-1+2` or `(-5+1)/6`

Either the minus has too much space or the parenthesis / equals sign do.

Whatever the case, the spacing is being set on the style of the element, so it can't be overwritten with CSS selectors.  I wish it were just controlled by classes so we could override cases that we don't like.

**Comment by pkra** [comment]
> Too much space around minus sign in some cases should be configurable.

If you [read the docs](http://docs.mathjax.org/en/latest/options/AsciiMath.html) you'll find the `useMathMLspacing` option. If you search around a bit you'll find many discussion on math spacing rules and traditions.

>  I wish it were just controlled by classes so we could override cases that we don't like.

We strongly advise against hacking the output. You will almost inevitably screw things up.

**Comment by garagebrewer** [comment]
Thank you.  That resolves the issue.  I had read the docs but that option seems a little non-intuitive.  Works great though!

**Comment by pkra** [comment]
Glad it works for you.
