### ISSUE TITLE
Incorrect parsing of ASCIIMath

### ISSUE THREAD

**Issue by bhelzer** [mathjax/MathJax#1405]
The following equation works on the ASCIIMath website, but not in MathJax without inserting extra spaces. It seems to be correct according to the ASCIIMath syntax.

`<<a-j,b-k,c-l>>` - does not render
`<< a-j,b-k,c-l >>` - renders correctly

**Comment by pkra** [comment]
It's hard to say without a live minimal sample, but  I'm guessing you're not escaping the `<` and `>` which you need to do in HTML documents otherwise they turn into tags.

**Comment by bhelzer** [comment]
To recreate:

1. Goto https://www.mathjax.org/
2. Click on Try a live demo
3. Type `<<a-j,b-k,c-l>>`

I contrast:
1. Goto http://asciimath.org/
2. Type <<a-j,b-k,c-l>>

**Comment by pkra** [comment]
Sorry, wrong tag. This is expected behavior. The browser parser generates the DOM tree long before MathJax gets a chance to process it. You must escape `<` and `>`. The asciimath demo works around that.

**Comment by bhelzer** [comment]
OK. Looks like this is just a problem in the Live Demo then, which does not encode.

**Comment by dpvc** [comment]
It is not really a problem with the demo (since you are allowed to enter tags, specifically MathML tags), so it can't escape `<` and `>`.  This is exactly the same results you would have if you entered 

    `<<a-j,b-k,c-l>>`

in a web page using MathJax with AsciiMath input.  You would need to use either

    `<< a-j, b-k,c-l >>`

or

    `&lt;&lt;a-j,b-k,c-l&gt;&gt;`

**Comment by bhelzer** [comment]
Closed, as this is an encoding issue.
