### ISSUE TITLE
Math Processing Error

### ISSUE THREAD

**Issue by meir0001** [mathjax/MathJax#1407]
All the current Papers in the Bulletin of the Australian Mathematical Society (AMS) Online Journalling System (OJS) using MathJax suddenly seem to have a "Math Processing Error" for each MathJax item.
This started occurring ~ 3/3/2016.
Very importantly, this problem only occurs with my PC, (under Windows 7 & Firefox).
I do not see the problem on my laptop, using Windows 8 & Firefox.
Two other users in my community are having no such problem!

**Comment by zorkow** [comment]
Have you tried to clear Firefox's cache? 
If that does not help, what do you see in different browsers: IE, Chrome, Opera...?

**Comment by meir0001** [comment]
Clearing Firefox's cache worked!
Thanks very much.
