### ISSUE TITLE
Zoom area gets printed!?

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1409]
When printing a page including MathJax I was surprised to find a Zoom area in the printed page. I don't recall to see a mention of this in the documentation. Is there a class that one might assign display:none or visibility:hidden with media="print"?

**Comment by pkra** [comment]
It's not clear what you are describing. You might want to add a link to a live example that exhibits the problem.

See also https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports

**Comment by cebola2** [comment]
A live example is a bit hard. I can mail (the old fashioned kind of mail) you the hard copy or show you a photo: https://plus.google.com/+JoãoPalhotoMatos/posts/Q3VSBLHmmGw
I also find it hard to reproduce.

**Comment by pkra** [comment]
Thanks for the image (btw you can attach images in the comments here).

I can see a zoom popup is visible in the printed page. Are you saying that this popup was not intentionally left open before printing?

It would be good to see a live page (eg on jsbin, codepen etc) .that, when printed, exhibits the problem (even if it only sometimes occurs).

**Comment by cebola2** [comment]
The page where it occurred is
https://cdi2tp.math.tecnico.ulisboa.pt/praticas/3
The browser was FF 44.0.2 on Linux.
![img_20160307_102240](https://cloud.githubusercontent.com/assets/1136663/13574730/5186d57c-e47d-11e5-91b8-faf9e6a71466.jpg)

**Comment by pkra** [comment]
Thanks. I still cannot reproduce this, I'm afraid.

Since zoom is set to hover on the page, are you sure it's not caused by accidentally hovering over the expression before staring to print?

**Comment by cebola2** [comment]
You are probably right and I am not saying otherwise. What I am saying is: considering it can happen, can one just set visibility:hidden for some class for media="print"?

**Comment by pkra** [comment]
> can one just set visibility:hidden for some class for media="print"?

Sure. Just add some custom CSS for `#MathJax_ZoomFrame`, cf. https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/MathZoom.js#L36
