### ISSUE TITLE
[CommonHTML] Passing ARIA roles through

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1410]
The CommonHTML does not pass roles "perfectly". For example, a `role=presentation` on an `mi` will not make it to the actual content node but a wrapping element (thus not having the desired effect of hiding the node with the `mi`'s content from AT). 

[This is probably just extremely minor. I'm not sure if there are any serious repercussions of this (any roles that are really problematic). Just wanted to make a note.]

**Comment by dpvc** [comment]
The attributes from the MathML nodes are attached to the span that represents the element (in this case, the one with class `mjx-mi`).  Note that an `<mi>` element may have multiple children (depending on the fonts needed for the characters in it content) so in general, you would not want to move properties to the content elements.  Also, more complicated elements (`<mfrac>`, `<mtable>`, etc.) can have lots of children (with nested children).  Perhaps `role` is an exception that would have to be handled specially, though it's not clear to me at the moment what the correct behavior should be.

**Comment by pkra** [comment]
Right. `role=presentation` on a token seems special as it affects just that element and not its children; not sure how many roles would have that problem; probably not many.
