### ISSUE TITLE
triple renders from mathjax

### ISSUE THREAD

**Issue by snihalani** [mathjax/MathJax#1411]
gif of the issue:
![](http://g.recordit.co/npAlT9hNyr.gif)

to reproduce, you can visit: https://www.quora.com/What-is-the-solution-graph-of-9x-2+9y-2+6x-18y-18-0

After tracing DOM modifications and looking at the css classes, it seems like intermediate representations are previews. I looked around in the configs for extensions and no particular option stood out to disable this and only have the user see one render. Is there an existing option to do this/is this behavior intentional?

**Comment by pkra** [comment]
As far as I can tell:

1) the TeX source from the raw page
2) MathJax's FastPreview
3) I don't know (something changing the font of the PreviewHTML output)
4) the final (HTML-CSS) rendering

I don't know what's triggering 3). If I switch to PreviewHTML as an output I don't see this but it may be some kind of FOUT. 

It also doesn't seem related to the AssitiveMML extension. Disabling the FastPreview helps as well.

**Comment by pkra** [comment]
I can't reproduce this outside of the particular page; re-labeling as `question`.

**Comment by snihalani** [comment]
Are you looking for another instance? 

https://www.quora.com/What-is-the-solution-to-this-equation

**Comment by dpvc** [comment]
> I don't know what's triggering 3)

Actually 3) is the correct output, it is 2) that is incorrect.  The fast preview output sets up the styles before it displays the math, but it looks like Chrome is not getting around to applying that for a while.  Not sure what would cause that.  It might be that other CSS on the page is interfering, but I don't see anything obvious (but your page is very complex, so it is hard to tell for sure).

>  I looked around in the configs for extensions and no particular option stood out to disable this and only have the user see one render.

Sorry you had trouble finding that.  If I google "MathJax fast preview" the first hit for me is the page that documents the `disable` option.  If you do disable it, you will still get a preview (which is the original math in grey, but without the delimiters).  You can change that via the `tex2jax` configuration's `preview` option.  Setting it so `none` will prevent any preview (so the math will go blank, then be displayed as typeset).

**Comment by pkra** [comment]
> Are you looking for another instance?

No. We'd be looking for a minimal sample that exhibits the problem.

**Comment by matijs** [comment]
@snihalani what happens if you turn off fast-preview in your config?

```javascript
'fast-preview': {
    disabled: true
}
