### ISSUE TITLE
[SVG output] check for `base` element

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1413]
[This is more a note in case people run into this.]

After Firefox and Edge, [Chrome now also has trouble](https://github.com/readium/readium-js/issues/138#issuecomment-196384536) resolving the links in the SVG output's use elements if a `base` element is around. 

Perhaps, v2.x (at least) should check for a base element and switch off the use of `use` elements.

(This would also fix #831.)

**Comment by dpvc** [comment]
There is already a proposed solution to 831 in my [issue831](https://github.com/dpvc/MathJax/commit/3473ccb61369606ca01312f90569805c451dbd35) branch that resolved the issue.  It doesn't turn of the use of `<use>` but it does cause the links to be full URLs to avoid the base URL.

**Comment by pkra** [comment]
Oh, sorry, I missed that. Should I close this one?

**Comment by dpvc** [comment]
I probably would.  I don't think we need a duplicate for this one.
