### ISSUE TITLE
mml2jax preprocessor ignores preview: 'none' setting

### ISSUE THREAD

**Issue by matijs** [mathjax/MathJax#1416]
Using:
```javascript
MathJax.Hub.Config({
  mml2jax: {
    preview: 'none'
  }
});
```
to disable the preview still results in a `<span class="MathJax_Preview"/>` ending up in the DOM. This in combination with the (new?) fast-preview extension (that seems to be enabled by default) resulted in two (or in the case of Firefox, OS X and iOS three) displays/renders of formulas with accompanying jumps of the page. First the MathML, followed by a flash of fast-preview followed by the final rendering of the formula.

See https://jsfiddle.net/j63fogqo/1/ for an example. Uncomment the disabling of 'fast-preview' to see one render less.

**Comment by pkra** [comment]
I'm seeing the expected behavior, I'm afraid. MathJax can't hide the MathML that's originally in the DOM until it is loaded and pre-processes the DOM.

If you want to hide things completely, you need to hide the math via CSS (visibility hidden with 0 dimensions is best) and queue something with MathJax to change it back after rendering is complete. Quick demo https://jsfiddle.net/j63fogqo/2/.

**Comment by matijs** [comment]
@pkra thanks for getting back so fast. The initial MathML that's showing is not actually the problem. Sorry if that wasn't clear. In the actual code, I'm hiding that using CSS.

However, your quick demo does not generate the `<span class="MathJax_Preview"/>` which is what I would expect. My example though, _does_ generate the `<span class="MathJax_Preview"/>`  despite the:

```javascript
MathJax.Hub.Config({
  mml2jax: {
    preview: 'none'
  }
});
```

I did notice you also disabled the fast-preview. Is this what one should do to not end up with  `<span class="MathJax_Preview"/>` in the DOM at all?

**Comment by dpvc** [comment]
Setting `mml2jax: {preview: 'none'}` tells the `mml2jax` preprocessor not to create the preview that it normally would, but the preprocessor is not the only way that previews can be created.  The `fast-preview` extension also creates previews (as its name indicates).  So the preview span you are seeing is not coming from `mml2jax` (which correctly processes your `preview: "none"` option, despite the title of your post), but rather from the `fast-preview`.

> Is this what one should do to not end up with `<span class="MathJax_Preview"/>` in the DOM at all?

Yes, as you original fiddle points out.  When you disable fast-preview (and the mml2jax preview), you don't get the preview span.  Leaving either preview enabled gives you a preview.  I indicated this in [my response](https://github.com/mathjax/MathJax/issues/1411#issuecomment-195768964) to a previous question (to which you also replied).  Peter's jsfiddle also indicates this.

**Comment by matijs** [comment]
@dpvc that explains everything then. Would adding this to the documentation be worth a PR to https://github.com/mathjax/mathjax-docs?

**Comment by pkra** [comment]
Thanks for sorting things out.

> Would adding an explicit mention of this behaviour to the documentation be worth a PR to https://github.com/mathjax/mathjax-docs?

That would always be appreciated.
