### ISSUE TITLE
SVG font data for `&#x2206;`

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1418]
From https://github.com/mathjax/MathJax-node/issues/196

> It looks like the SVG font data for `&#x2206;` is incorrect.

**Comment by dpvc** [comment]
The `font-fixes` branch of my fork of MathJax includes the fix for this.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/letters/issue1418.html
