### ISSUE TITLE
Reset browser cache on new versions

### ISSUE THREAD

**Issue by drlippman** [mathjax/MathJax#1420]
I just ran into same problem as in issue #1032 where an update of MathJax caused [Math Processing Error] to show all over the page due to the browser mixing old cached scripts with new ones.

I know that MathJax internally puts ?rev=2.6.1 on all resource loads, presumably to trigger reload on new editions.  Should I be putting rev=2.6.1 in the query string for my script call to MathJax.js itself to prevent the mixed cache issue?

**Comment by dpvc** [comment]
You are right that the `?rev=x.y.z` is an attempt to break browser caching on new versions.  During major version updates (from x.y.z to x.(y+1).0), MathJax forces a directory change in the URL as well, which guarantees the correct version is used (the one that matches the MathJax.js file that was obtained).  But for minor releases, the same URL is used as for the previous minor version, and it is possible that, during the update to the CDN, not all the files have arrived at the CDN node that you use when you first get the new copy of MathJax.js.  So even though it adds the correct `?rev=x.y.z` to the URLs for the other files, if they haven't reached the CDN edge node yet, the file that is servers is still the old version, and the browser cached that under the new `rev` value.  I suspect that is what has happened for you.

Short of maintaining every subversion in a separate directory as well, I don't see a way to guarantee that this doesn't occur.

To answer your question, no I don't recommend adding `rev=2.6.1` MathJax.js itself.  It shouldn't hurt, but it probably won't help, either, and it is just something more you have to maintain on your site.
