### ISSUE TITLE
SVG data in fontdata-extra.js is incorrect

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1421]
The widths of the single-character versions should be times 1000, but are given as decimals instead.  This is easily fixed, but needs to be done.

See mathjax/MathJax-node#202 for the original report.

**Comment by pkra** [comment]
I had already filed https://github.com/mathjax/MathJax/issues/1418

**Comment by pkra** [comment]
Oh nevermind. This is a new bug. Sorry!

**Comment by dpvc** [comment]
The `font-fixes` branch of my fork of MathJax fixes this problem.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/letters/issue1421.html
