### ISSUE TITLE
virustotal.com reports false positive for TeX-AMS-MML_HTMLorMML-full.js

### ISSUE THREAD

**Issue by gnosygnu** [mathjax/MathJax#1426]
Hi all. This is probably a low priority issue. However, it was reported to me by another party, so I just wanted to do the due diligence and investigate. I'm reporting it here just in case it might be of interest to anyone.

As per the subject, virustotal.com will report a false positive for TeX-AMS-MML_HTMLorMML-full.js. Here are my reproduction steps:

* Download https://raw.githubusercontent.com/mathjax/MathJax/master/config/TeX-AMS-MML_HTMLorMML-full.js
* Go to https://virustotal.com/ and upload it.
* virustotal.com will report cached results. Click Reanalyze.
* Wait about a minute. Of the 57 virus checkers, the Rising antivirus software will report a trojan called JS:Trojan.Nemucod!1.A420 [F] . 

I suspect the problem is with the Rising antivirus software:

* I was able to reduce the file to about 3200 lines, and got it to fail / pass just by removing any innocent javascript variable assignment. See below
* Rising antivirus software seems to be a small shop in china and the website is no longer being maintained. See: http://www.rising-global.com/. For whatever it's worth, I submitted a report for the false positive. My inquiry number is RS20160329100018234396.
* Only TeX-AMS-MML_HTMLorMML-full.js and TeX-AMS-MML_HTMLorMML.js are the problem files. Rising passes the entire Mathjax repo if those two files are excluded.

At any rate, I hope this may be useful to someone. For anyone curious, I've also attached my working file: [TeX-MML-AM_HTMLorMML-full.txt](https://github.com/mathjax/MathJax/files/192802/TeX-MML-AM_HTMLorMML-full.txt)

Note the following:
* this was based on an old version of TeX-AMS-MML_HTMLorMML-full.js (circa 2013-05-03)
* the current file fails the antivirus check
* I can get it to pass by removing any of these lines:
```
            gimel: "2137",
            daleth: "2138",
            leadsto: "21DD",
            dashrightarrow: "21E2",
            dashleftarrow: "21E0",
```

**Comment by pkra** [comment]
Thanks for letting us know. I doubt we can do anything about false positives but if anyone has a suggestion, we're happy to hear about it.
