### ISSUE TITLE
Progress bar keeps growing with dynamically created math

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1428]
I have a case where math is dynamically created based on user input. Over time, the MathJax progress bar ("Typesetting ...") grows beyond all limits. I wish there was an (official) way of resetting it. I can reset `MathJax.Message.typesetting` etc. by hand, but it feels like MathJax should do this automatically after finishing its job.

**Comment by dpvc** [comment]
Good point.  This is with `messageStyle` set to `simple`, I assume.  I agree that it should be reset for the next typeset operation.

**Comment by dpvc** [comment]
The `issue1428` branch of my fork of MathJax fixes the issue.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

UI/issue1428.html
