### ISSUE TITLE
Typo in Portuguese language selection in drop-down menu

### ISSUE THREAD

**Issue by HelioGuilherme66** [mathjax/MathJax#1429]
### Issue Summary
The selection name of the Portuguese (pt) language is wrong.
It shows "portugusê (pt)" when it should be "português (pt)".

### Steps to Reproduce

1. Navigate to [a Stackexchange math page](http://stats.stackexchange.com/questions/203462/in-clt-why-sqrtn-frac-barx-n-mu-sigma-rightarrow-n0-1-implies)
2. Right click over a formula select Language> português (pt)

This is a bug because someone typed it wrong ;)
Compare with the correct "português do Brasil (pt-br)"

### Technical details

* MathJax Version: MathJax v2.6.1
* Client OS:  Linux
* Browser: Firefox 38.6.1 ESR, Chrome 49.0.2623.110 (64-bit)

### Screenshot
![mathjax_pt_error](https://cloud.githubusercontent.com/assets/2866630/14300843/22637b68-fb8b-11e5-9c34-a78f20d93af5.png)

**Comment by pkra** [comment]
I've opened an upstream issue at https://github.com/mathjax/MathJax-i18n/issues/15.
