### ISSUE TITLE
Bug: Page not found in CONTRIBUTING.md for https://github.com/MathJax/MathJax-testing

### ISSUE THREAD

**Issue by HelioGuilherme66** [mathjax/MathJax#1430]
### Issue Summary
There is no page for the testing framework at https://github.com/MathJax/MathJax-testing
### Steps to Reproduce

1. Open CONTRIBUTING.md from "Please review the [guidelines for contributing](https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md) to this repository."
2. Jump to "[testing and quality assurance](https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#testing-and-quality-assurance)"
3. When you click the following link you get 404 (Jedi Octocat):
    "If you want to get involved with testing MathJax, there is a set of QA Documentation [in our testing framework.](https://github.com/MathJax/MathJax-testing)."

This is a bug because we should not see the missing page error.
(and then I can not get involved in testing MathJax ;) )

### Technical details

* MathJax Version: GitHub page CONTRIBUTING.md
* Client OS: Linux
* Browser: Firefox 38.6.1 ESR

**Comment by pkra** [comment]
Thanks for catching that. It's https://github.com/mathjax/MathJax-test by the way.

**Comment by pkra** [comment]
Fixed in `develop`.
