### ISSUE TITLE
Vertical Bar not used as "infix" operator

### ISSUE THREAD

**Issue by tlhamrick** [mathjax/MathJax#1432]
To see an example: https://jsfiddle.net/pwosgdma/

I would expect that since in this case, the vertical bar is not the first or last character in its respective `mrow`, that it would be interpreted to be in "infix" form.

I don't know if it is the expected behavior to be done this way, but it should be possible to consider this operator in the infix form, as well as the prefix and postfix form, and I think by default I would expect this operator to be interpreted as being in the infix form as a normal operator would.

**Comment by dpvc** [comment]
By default, MathJax's renderers implement the spacing rules for TeX rather than the MathML rules.  If you want to use MathML spacing rules, you need to configure the MathML input jax to enforce that.  If you add

```
MathML: {useMathMLspacing: true},
```

to your configuration, then I think you should get the result that you expect.

**Comment by dpvc** [comment]
See the [MathML input jax documentation](http://docs.mathjax.org/en/latest/options/MathML.html) for more details.
