### ISSUE TITLE
[CommonHTML] [Safari 5.1] \TeX and \LaTeX commands break after initial rendering

### ISSUE THREAD

**Issue by TreeOfMath** [mathjax/MathJax#1433]
I just changed
http://www.onemathematicalcat.org/MathJaxDocumentation/TeXSyntax.htm
to load the newest version from the CDN.

Notice that, when viewed in Safari (I'm using Mac OS X version 10.6.8) both  the \TeX and \LaTeX commands *initially* render correctly, then break and look very ugly (the "X" gets separated by a relatively large distance from the rest of the logo).
This behavior doesn't occur in Chrome and Firefox.

**Comment by dpvc** [comment]
What version of Safari are you using?  I see you have the CHTML output selected.  It was hard to get some of this output to work with Safari at all, and it may be that elder versions (I can only test back to version 6.1) don't work entirely properly.  It may also be that there is other CS on the page that is affecting the output, but I didn't see anything that looked troubling.  I suspect it may just be that the old version of Safari isn't up to the newer output format.  (10.6 is nearly 7 years old, now.)

**Comment by TreeOfMath** [comment]
Hi Davide,
First --- that gigantic page loads BLAZING FAST with the new version of MathJax.  I was floored.  Makes me want to upgrade my entire site yesterday --- but then the first page I tried the CDN on, something rendered differently (sigh).  So, I'll stick with my ancient version of MathJax a bit longer.  (I really want to finish Precalculus.)
I'm using Safari 5.1.10.  Yes, it's ancient too.  Every major site is screaming at me that I need to upgrade my browser. But, to upgrade my browser I need to upgrade my operating system.  And my husband is wanting me to go back to PCS.  I hate change.
I've attached a couple snapshots of what I'm seeing, but probably it isn't worth fixing if no one else is having this problem.
Please let me know if there are changes/additions you want made in that "TeX Commands available in MathJax" document, to keep it current.  It gets a lot of hits. It seems to be useful to the MathJax community. In particular, if there's a configuration that you want to encourage people to use, I can use it --- I imagine lots of people may just cut-and-paste what I've used in that document.  
I'm sure you're aware of the Chrome bug that puts a vertical bar at the right of the math.  I notice that it isn't an issue in the newest version, but it sure makes my other pages look crappy in Chrome.  (And---go figure---Chrome is the most popular browser among my visitors.)  Is there any quick-and-easy way you know of that I could fix this behavior, other than (sigh) upgrading and going thru (sigh) every one of my now-almost-400 lessons to check that they still look the way they should?
Hope you're well.  Hope MathJax is finding lots of success.  What you've done with MathJax will be recognized in the future as world-changing.  Math is tough on the web, it seems.  People are so used to seeing ugly math that they don't appreciate the beauty that MathJax provides.  Someone posts a picture of their kid in a funny hat on Facebook and gets 150 likes within minutes...  (So sorry --- can you tell that I'm totally discouraged these days that my site isn't going anywhere?)
-- Carol

Date: Sat, 9 Apr 2016 17:01:04 -0700

**Comment by TreeOfMath** [comment]
![tex1](https://cloud.githubusercontent.com/assets/18368490/14410532/27d3bd06-ff00-11e5-8dfe-4e830dbb3092.png)
![tex2](https://cloud.githubusercontent.com/assets/18368490/14410534/2c788724-ff00-11e5-8336-ffc614c7591f.png)

The images didn't seem to come across on the previous message, so I attached them here.

**Comment by pkra** [comment]
Marked `expected behavior` (unless @dpvc corrects me).

@TreeOfMath you could configure MathJax to switch output processors to HTML-CSS on older Safari versions, see http://docs.mathjax.org/en/latest/output.html#automatic-selection-of-the-output-processor

**Comment by dpvc** [comment]
Well, it really is a bug, not expected behavior, but because Safari 5.1 is so old, and we don't want to make CommonHTML have nay browser dependencies, I don't think it is something we will be able to fix.  So I guess that does mean expected behavior in that sense.  The output is correct is Safari 6 and above, and in other browsers, so I agree with Peter that configuring MathJax for HTML-CSS for older versions of Safari would be reasonable.
