### ISSUE TITLE
MathJax Rendering SVG Format not proper in IE browser

### ISSUE THREAD

**Issue by Prasanna9000** [mathjax/MathJax#1435]
I am trying to Render SVG for the mathml. It looks fine on chrome , but in IE svg has additonal attributes to its tag. How can we avoid these additional attributes being added. Please try to render below mathml as SVG in chrome and IE. You can see the difference in SVG tag which got generated (Attached scrrenshots in both browsers) MathML used to render is also attached.

**Issue**: Allignment is not proper in IE  browser because of those additiona attributes added to svg.

**MATH ML used** : 
[MathMl.txt](https://github.com/mathjax/MathJax/files/212257/MathMl.txt)

![svgrendering_in_chrome](https://cloud.githubusercontent.com/assets/18389315/14416673/81f05f7c-ffca-11e5-9991-4bad520f34ce.png)
![svgrendering_in_ie](https://cloud.githubusercontent.com/assets/18389315/14416674/8333d3fa-ffca-11e5-80cc-15d0a1057edd.png)

**Comment by pkra** [comment]
Thanks for the report. Please add a live sample (e.g., using jsbin, codepen, jsfiddle) as well as information on which version of IE (and Windows) you're seeing this on. See also https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#reporting-an-issue

**Comment by dpvc** [comment]
As I mentioned in [my response](http://stackoverflow.com/a/36463358/502334) to your post on StackExchange, the IE output does **not** have additional attributes.  The ones you have highlighted in yellow are simply in a different order in the first image (they are at the end of the line, following the `viewBox` attribute).  The code used to produce the SVG output has no browser-specific code, and produces the same thing in all browsers.

Again, as I said before, these styles are important for getting the placement correct. If the placement isn't correct for you, there may be other CSS on the page that is interfering.  If you are seeing different placements in the two brasiers, you need to describe that (not point to attributes that are actually the same in both instances).
