### ISSUE TITLE
HTML-CSS renderer produces invalid markup

### ISSUE THREAD

**Issue by anssiko** [mathjax/MathJax#1440]
The HTML-CSS output processor produces invalid markup. [Validation][1] of the generated HTML yields:
`Element nobr not allowed as child of element span in this context.`

Here's a suggestion how the markup could be made valid. In [maction.js#L177][2] replace:

`<span class="MathJax"><nobr></nobr></span>`

... with:

`<span class="MathJax"><span class="nobr"></span></span>`

And adjust the CSS accordingly [here][3] and [here][4], replace:

`.MathJax nobr`

... with:

`.MathJax .nobr`

Not sure if that'd break some legacy browsers that do not support `white-space: nowrap`. There may be other caveats with this change as well that I'm not aware of as I'm new to this project. Anyway, that worked for me.

[1]: https://validator.w3.org/nu/
[2]: https://github.com/mathjax/MathJax/blob/d4ab1b35c96dd964eaa9e1ed2c86e39fffbdacf6/unpacked/jax/output/HTML-CSS/autoload/maction.js#L177
[3]: https://github.com/mathjax/MathJax/blob/d4ab1b35c96dd964eaa9e1ed2c86e39fffbdacf6/unpacked/jax/output/HTML-CSS/jax.js#L282
[4]: https://github.com/mathjax/MathJax/blob/d4ab1b35c96dd964eaa9e1ed2c86e39fffbdacf6/unpacked/jax/output/HTML-CSS/jax.js#L301

**Comment by anssiko** [comment]
Here's the script I use to make the markup valid in a post-processing step after grabbing the generated output (i.e. a monkeypatch that applies the above changes):
https://github.com/w3c/mediacapture-depth/blob/gh-pages/releases/make-valid.sh

Would like to see these fixes integrated into MathJax proper.

**Comment by pkra** [comment]
@dpvc will correct me but I think this is the expected behavior. 

Note that the HTML-CSS is **not** portable across browsers (and OSs), so the validity of its output is not very important.

If you want to generate HTML server-side, the CommonHTML output is the only choice you have. You might want to use mathjax-node for that.

**Comment by anssiko** [comment]
@dpvc Thanks a bunch! The use of CommonHTML output fixed my issue, making the generated output valid HTML.

Feel free to close this issue.

**Comment by pkra** [comment]
> Thanks a bunch! The use of CommonHTML output fixed my issue, making the generated output valid HTML.

Glad to hear that solved the problem. Note that the CommonHTML output only supports IE8+ (and Safari <6 can have problems) but it should degrade reasonably well. You might also want to check out github.com/mathjax/mathjax-node or github.com/zorkow/speech-rule-engine if you want to make the output accessible.
