### ISSUE TITLE
[CommonHTML] problem with labeled equations

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1441]
Due to [this SO question](http://stackoverflow.com/questions/36628111/mathml-left-adjust-equation-numbers-in-table-of-equations), I noticed a problem with labels in the CommonHTML output.

The following example does have the labels float to the right/left (but does in HTML-CSS and SVG) -- but each table individually renders correctly.

```
<math display="block">
    <mtable side='left'>
        <mlabeledtr>
            <mtd>
                <mtext>(1)</mtext>
            </mtd>
            <mtd>
                <mi>X</mi>
            </mtd>
        </mlabeledtr>
    </mtable>
    <mspace linebreak="newline" />
    <mtable>
        <mlabeledtr>
            <mtd>
                <mtext>(2)</mtext>
            </mtd>
            <mtd>
                <mi>Y</mi>
            </mtd>
        </mlabeledtr>
    </mtable>
</math>
```

**Comment by pkra** [comment]
For completeness, two labeled rows in one table are fine.

**Comment by dpvc** [comment]
It has to do with some elements not getting `width:100%` when they should.  I'll see about a fix.

**Comment by dpvc** [comment]
The `issue1441` branch of my fork of MathJax fixes the problem.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1441.html
