### ISSUE TITLE
[package.json] make unpacked/MathJax.js the main script

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1442]
Rationale: when used in a nodejs setting (i.e., in mathjax-node), the unpacked version is usually the better entry point (e.g., for debugging). 

I'm not sure if somebody might consider this a breaking change; does anyone rely on the `main` entry to generate script tags for the front end?

**Comment by dpvc** [comment]
I'm OK with the change.

**Comment by dpvc** [comment]
fixed by PR #1446
