### ISSUE TITLE
echidna CSS validation issues

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1443]
Reported at https://github.com/w3c/echidna/issues/271

Bug: CHTML has a typo `".mjx-span":   {display:"span"}`  https://github.com/mathjax/MathJax/blob/d4ab1b35c96dd964eaa9e1ed2c86e39fffbdacf6/unpacked/jax/output/CommonHTML/jax.js#L126.

Not strictly a bug: but the menu still uses `DXImageTransform` etc (which are strictly speaking invalid). Not sure if we want to drop them but I feel like we could.

**Comment by dpvc** [comment]
> Not sure if we want to drop them but I feel like we could.

They are for IE8 and below.  I suppose they could be added only in that case.  I would leave them in 2.x but certainly remove them in 3.0.

**Comment by pkra** [comment]
> I would leave them in 2.x but certainly remove them in 3.0.

Copy that. So #1448 will fix this bug.

**Comment by dpvc** [comment]
==> Merged.
