### ISSUE TITLE
Text with hashtag "#" assumed as MathJax script

### ISSUE THREAD

**Issue by Bahir** [mathjax/MathJax#1486]
A text that starts with # symbol, for instance #(5,4) assumed as script and processed with processor.
Even if i put in the config

tex2jax : {
inlineMath: [ ['\\[', '\\]'] ],
}

**Comment by dpvc** [comment]
I cannot reproduce your result.  You should provide a link to a page showing the issue, if you can.  Use codebin or jsfiddle if necessary.  You should also give the browser and OS you are using, and their versions.

If you are using a content-management system, you should indicate that as well.  I suspect that there is something else going on, as MathJax will not process `#` unless you have misconfigured it, so it may be that some other script your are using, or your content-management system, is really the one that is causing the problem.
