### ISSUE TITLE
[Menu] behavior on mobile (with keyboard)

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1489]
This is more a question/note than an issue. I just want to make sure this was the expected behavior we decided on.

I was exploring the menu with a keyboard on (emulated) mobile. I noticed the following

* navigating a level of the menu by keyboard won't automatically pop-up the submenus (as it does on the desktop).
* opening the submenu with <kbd>enter</kbd> works but requires another <kbd>left</kbd>, i.e.,  up/down will continue in the top level menu.

I'm wondering if the submenu can't automatically open on mobile. If not, perhaps opening via <kbd>enter</kbd>  should move the active position to the first item of the submenu (though I'd prefer identical behavior on all platforms).

**Comment by dpvc** [comment]
I don't know how to get a keyboard to be active while the menu is open on an actual mobile device, so I'm not sure how to test this in a non-emulator.  The reason for this difference is that the mobile menus are laid out more compactly, and if the submenu opened, it would block the title of the menu for which it is a submenu, and you couldn't see that title.

How likely is keyboard activation of menus on a mobile device?  I can't figure out how to do it on an iPad or an Android phone.

**Comment by pkra** [comment]
> The reason for this difference is that the mobile menus are laid out more compactly, and if the submenu opened, it would block the title of the menu for which it is a submenu, and you couldn't see that title.

Thanks for the background.

> How likely is keyboard activation of menus on a mobile device?

Well, I use a keyboard on a tablet all the time. I don't know how much AT users rely on external keyboards (didn't some ChromeVox team members have braille outputs with keyboard for mobile devices?)

Anyway. Not critical.

**Comment by dpvc** [comment]
> Well, I use a keyboard on a tablet all the time.

Ah, hadn't thought of that.

We could drop the compressed version of the menu and always lay it out like the desktop version.  Or we could use the window size to decide whether to do that or not (tablets are probably big enough to do the desktop menu layout).
