### ISSUE TITLE
[HTML-CSS] [Chrome mobile] inline-math overlap with following text

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1490]
From a user.

example: http://leancrew.com/all-this/2016/05/lebron-james-and-conditional-probability/

On mobile Chrome (50 in my case), the last pieces of inline math (near the bottom of the article) will have some overlap with the surrounding page; this can also be simulated using the Chrome dev tools.

I don't see any issues with the surrounding CSS.

CommonHTML and SVG are not affected.

**Comment by dpvc** [comment]
Mobile devices sometimes change the font size after the page is processed, and that may mean that MathJax has let the wrong amount of space for the HTML-CSS expressions.  (The measurements are taken before the font-size change.)  I haven't checked this site on a mobile, but I know that has been a problem in the past.

Alternatively, if the post is loaded in a `display:none` format, processed, then revealed, that could also be it.  It doesn't look like it to me, but it is hard to tell for sure on that page.

**Comment by pkra** [comment]
> Mobile devices sometimes change the font size after the page is processed

Right. This also happens on the desktop when simulating a mobile device via the developer tools. 

More importantly, re-rendering via the console won't fix it, so I think the problem lies elsewhere.

> Alternatively, if the post is loaded in a display:none format, processed, then revealed, that could also be it. 

From what I can tell, that's not the case.

**Comment by westurner** [comment]
I am seeing the same issue. (And also a different font size). Looks fine with Firefox Mobile latest.

> When I view [1] on my 5" Android 8.1 phone with Chrome latest, the MathJax text font size is smaller than the rest of the summary text and overlaps with subsequent non-MathJax text.

> The text looks fine with Firefox.

> Screenshot attached.

> Is this a MathJax bug?

> [1] http://export.arxiv.org/abs/1808.07593
![screenshot_20190125-041117_firefox](https://user-images.githubusercontent.com/50891/51736232-8a892c80-2057-11e9-8de0-59a0c6f74e3f.png)
![screenshot_20190125-041136_chrome](https://user-images.githubusercontent.com/50891/51736234-8a892c80-2057-11e9-98a7-005042be78e9.png)

**Comment by pkra** [comment]
This is an old yet persisting Webkit/Blink bug that probably won't be fixed because it doesn't happen if `<meta name="viewport" content="width=device-width">` was in the head (which should really be a default for developers by now).

**Comment by ValZapod** [comment]
@pkra So this is a bug in Chromium! Can you please give me a link about that meta name thing? I opened a bug some time ago, https://bugs.chromium.org/p/chromium/issues/detail?id=979121#c_ts1565801815
but alas.

**Comment by ValZapod** [comment]
Archive.org added `<meta name="viewport" content="width=device-width, initial-scale=1">`, so it is good now, but this is not a normal fix!
