### ISSUE TITLE
Pass in a string and get the rendered math back

### ISSUE THREAD

**Issue by felipellrocha** [mathjax/MathJax#1493]
Is there anyway I could do something like:

```
MathJax.renderToString('a^2 + b^2 = c^2')
```

and have that function return a bunch of divs I could just attach to my dom?
I think all the other functions within MathJax are nice for a day to day case (the hub, the queue, automatically downloading things for the user, reading the entire doc looking for equations to parse), but they can sometimes get in the way of development whenever the user needs something more specific, or wants to take a bit more control of how the rendering is accomplished.

**Comment by pkra** [comment]
There is no such method at this time. MathJax needs to work in the DOM to be able to get contextual information (matching font-size, CSS, handling arbitrary Unicode characters, HTML fragments etc). 

You could write a hacky wrapper around MathJax (cf. [this idea for images](http://stackoverflow.com/a/35430069) for images)), e.g. create detached nodes, process them and serialize them. I wouldn't try that that with HTML-CSS though; SVG and CommonHTML output are more robust and thus the rendering will more likely be ok.

In the long run with v3.0 will very likely have such a method but we're in the design phase right now. The notes on the [dev mailing list](https://groups.google.com/forum/#!forum/mathjax-dev) to our TC meetings for v3.0 provide more information on the various related issues.
