### ISSUE TITLE
PlainSource output vs AssistiveMML

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1497]
A user pointed out to me that it would be good for the PlainSource output to disable the AssitiveMML extension. 

I think that would be preferable behavior as it avoids both accessibility issues as well as copy&paste problems on some browsers when PlainSource is used.

**Comment by dpvc** [comment]
The `issue1497` branch of my fork of MathJax will prevent assistive MathML output when PlainSource is the selected output.

**Comment by pkra** [comment]
I guess that's a yes to my question :wink: . Sorry for not proposing a fix alongside it.

**Comment by dpvc** [comment]
For copy&paste, it might be good for PlainSource to insert the math delimiters for TeX code.  Right now, it is just the TeX code directly, which may be good for reading, but not so good for copy and paste.  Should there be a menu option to control that?

**Comment by pkra** [comment]
Yes, I thought about that as well. But then I coudn't decide if "standard" delims are better than page-configured ones so I left it.

**Comment by dpvc** [comment]
Well, the tex2jax could store the actual delimiters used for each expression, so they would be available for PlainSource to use.

**Comment by camlorn** [comment]
As someone who will use this feature, `$` isn't bad and `\(\)` is horrible.  You don't see the latter often, but it does come up every once in a while.

No delimiters is ideal for use with a screen reader, however.  I think this is probably the primary use case of this feature by far, and is certainly the reason it was originally suggested.  I can see the potential use to sighted people though.

**Comment by dpvc** [comment]
@camlorn, thanks for your comment.

I agree that the screen-reader use case is best with no delimiters.  The other use case, however, is to be able to copy-and-paste paragraphs of math into an actual TeX document.  For that use case, having delimiters would be useful.  Because there are two distinct use cases with different needs (in terms of delimiters), it might be useful to allow the user to select whether he or she wants them or not.

**Comment by pkra** [comment]
> The other use case, however, is to be able to copy-and-paste paragraphs of math into an actual TeX document.

Right. Then again, we also don't use delims in the show-math popups.

**Comment by dpvc** [comment]
> Then again, we also don't use delims in the show-math popups.

Of course, there is nothing else to delimit it from on the pop up.  Here, the idea is to be able to copy and paste entire paragraphs or longer, with multiple equations and intervening text.  There, delimiters are critical.

**Comment by pkra** [comment]
Maybe I misunderstood. I thought your earlier comment suggested delimiters to be useful for the "paste" part of copy&paste (so that it stays inline/display). Your last comment makes it more about the "delimiting" part. For that, we could simply use styling (assuming delimiters are only good for delimiting).

Anyway, I'm fine either way -- 1/10 I'd say.

**Comment by dpvc** [comment]
> I thought your earlier comment suggested delimiters to be useful for the "paste" part of copy&paste (so that it stays inline/display). Your last comment makes it more about the "delimiting" part.

I don't understand that distinction you are trying to make.  Delimiters certainly are for delimiting, yes, and if you are planning to past an entire *paragraph* into a TeX document, say, then you do need to delimit the text from the math.  That involves both delimiting and pasting.  I'm really not sure what is causing the miscommunication that we are having.

**Comment by dpvc** [comment]
We don't do testing on PlainSource output, so I'm marking this "No Test Needed."

**Comment by pkra** [comment]
@dpvc Sorry for not having responded to your earlier comment. I can't reconstruct my thoughts from back then at this point; apologies for the miscommunication in any case.

**Comment by dpvc** [comment]
No problem.

I still think it might be useful to retain the delimiters and have an option to include them (i.e., make the page look more like a TeX source document), but that can wait for now.

**Comment by pkra** [comment]
> I still think it might be useful to retain the delimiters and have an option to include them (i.e., make the page look more like a TeX source document), but that can wait for now.

Whatever you prefer. (At least that part I can reconstruct :wink: )

**Comment by dpvc** [comment]
I'm closing this, but marking it "address later" so I can find it in the future, if needed.
