### ISSUE TITLE
[Safari 9.1.1 / OSX] [MathJax Menu] can't enter submenu via keyboard

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1520]
I ran into this while testing with VoiceOver. Not sure what the problem is.

**Comment by dpvc** [comment]
I think this is because VoiceOver uses the arrow keys for its own purposes, so they aren't passed to the web page, and hence MathJax doesn't seem them and can't respond to them. Not sure there is anything we can do about that, other than provide alternative keys.

**Comment by dpvc** [comment]
If you use <kbd>CTRL-SHIFT-CMD-arrow</kbd>, you can access the menu via arrow keys.

**Comment by pkra** [comment]
D'oh. Excellent point :wink:
