### ISSUE TITLE
AssistiveMML not writing MathML for dynamic math

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#1528]
Using the attached sample page, the static math at the top creates the appropriate `<span class="MJX_Assivstive_MathML" ...>` tag. However, the dynamically created MathML which uses
`    MathJax.Hub.Queue(["Typeset",MathJax.Hub,"mathElement"]);`
after inserting the math in the page only creates the HTML/CSS math, not the `class="MJX_Assivstive_MathML"` part.

Note: to see the dynamic math easily, fill in the first and second arguments and click on the "Divide" button. Then click on "Calculate" and use the browser's DOM inspector to see that the assistive part is missing.

Sample page: [pesrson-sample.zip](https://github.com/mathjax/MathJax/files/317239/pesrson-sample.zip)

**Comment by dpvc** [comment]
I'm not able to reproduce the problem.  Your document includes the span with `class="MJX_Assistive_MathML"` on both the original and the computed equation for me.  I tried in Firefox, Chrome, and Safari on Mac OS X.  What browser/OS are you using?

Here is a snapshot of Chrome with the assistive MathML selected.  Note from the `data-mathml` attribute of the containing span that this is the computed math.

![assistivemml](https://cloud.githubusercontent.com/assets/432782/16098361/8bf559c6-3320-11e6-99bf-496c92a566de.png)

**Comment by NSoiffer** [comment]
My bad -- I could have sworn I had clicked and opened up the MJ node
(several times) to look inside, but looking at again, I see the
class="MJX_Assistive_MathML" node. (FYI: This was with Firefox).

Sorry about the bad bug report.

   Neil


On Wed, Jun 15, 2016 at 2:42 PM, Davide P. Cervone <notifications@github.com

**Comment by dpvc** [comment]
No problem.  Glad it is working.
