### ISSUE TITLE
Question: Display MathJax on canvas

### ISSUE THREAD

**Issue by cfloody** [mathjax/MathJax#1531]
Hello,

I'm very new to MathJax, but really like how well it displays LaTeX expressions. I'd really like to incorporate it into my project, except that all my math content is displayed on a canvas. Right now I'm just displaying the LaTeX syntax directly on the canvas:

I.e. `ctx.fillText("\(x^2 + y^2 = z^2\)", 100, 100);`

...but is there anyway that I can use MathJax to properly format the LaTeX into proper math notation, and add it to the canvas?

Many thanks,
Connor

**Comment by pkra** [comment]
There is no built-in way for accomplishing this. The easiest approach is probably to use MathJax's SVG output on a detached DOM node and injecting the result with `drawImage`, see [this pen](http://codepen.io/pkra/pen/XKjvqE) for very simple example and [the MathJax User Group](https://groups.google.com/forum/#!searchin/mathjax-users/canvas) for several discussions and examples.

**Comment by cfloody** [comment]
Thanks for your help. The pen doesn't seem to be quite working. I've tried editing it, but can't get it running. However, I'm getting some ideas from the discussions.

With the solution you suggested, do you think there would a significant delay in rendering the image compared to when MathJax is displayed directly in HTML? I'm not sure if this example: http://jsfiddle.net/RG7yG/4/
..is similar to that you're discussing, but I noticed it takes around 7 seconds to display the output.

**Comment by cfloody** [comment]
I found the error in the pen, was just an extra bracket.

**Comment by pkra** [comment]
Glad it helped. I'm not sure what happened in the pen, probably an accidental edit; sorry about that.
