### ISSUE TITLE
Alignment problem in CHTML tables with labels

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1532]
The alignment of labels with their table rows continues to be problematic in CommonHTML output.  See mathjax/MathJax-node#244 and mathjax/MathJax-node#245.

**Comment by dpvc** [comment]
The `issue1532` branch of my fork of MathJax uses a different approach to aligning the labels with the rows, and it seems to do a better job of dealing with the round-off issues.  @pkra, Give that a try and see if it works better for you.

**Comment by pkra** [comment]
Will test it in the morning.

**Comment by pkra** [comment]
Ok, I've updated http://s.codepen.io/pkra/debug/YWqRLB with a second result using your new branch.

My impression is that the layout is much more stable under zoom now (yay!) but the cells are not yet aligning correctly. Does that seem likely?

**Comment by dpvc** [comment]
The output does not appear to be from the new branch.  Also, the CSS is not up to date.  So I'm not sure what to tell you.  Try using `tex2htmlcss` to get a complete page with the current CSS and see if that works better.

**Comment by dpvc** [comment]
[Here](http://www.math.union.edu/~dpvc/transfer/mathjax/tag-align.html) is what I get.

**Comment by pkra** [comment]
Ah, that's great. I'll double check later.

**Comment by pkra** [comment]
I found the issue on my end (mathjax-node was pulling mathjax from a different location which I hadn't udpated). I updated the codepen -- it looks great!!

**Comment by dpvc** [comment]
Glad you got it worked out.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1532.html
