### ISSUE TITLE
MathJax not loading in Chromium for Android

### ISSUE THREAD

**Issue by dgroh** [mathjax/MathJax#1536]
We have an HTML page with the following script in header:

```
    <script type="text/javascript" async
            src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_CHTML/">
    </script>
```

When we deploy it to windows phone, it works fine, when we deploy it to android we get the following error:

> "Uncaught ReferenceError: MathJax is not defined"

**Comment by dpvc** [comment]
You do not give enough of the details of your page to diagnose the issue for you.  The error message is likely coming from javascript running elsewhere on the page, not the script tag that you include.

Note that you have used the `async` parameter on the script tag, which means that the page will continue being processed (and other javascript will run) while MathJax.js is loading, so if your code elsewhere on the page tries to use the `MathJax` variable before this script has loaded, you will get the type of error that you are seeing.

Also, `...config=AM_CHTML/"` should be `...config=AM_CHTML"` (without the final slash, though I doubt that is the source of the problem).

**Comment by dgroh** [comment]
@dpvc  my apologies. I was able to fix the issue and it has nothing todo with matjjax, although I would recoomend mathjax to update its documentation for `android`.

this was the fix for my issue:

http://stackoverflow.com/questions/14065279/include-mathjax-in-android-app
