### ISSUE TITLE
Styling of exponents

### ISSUE THREAD

**Issue by infusion** [mathjax/MathJax#1560]
Hi,

I was wondering if `\vec{A}_r^2` could be formatted a bit better by setting the exponent not so high. As an alternative `\vec{A^2}_r` sets the arrow on A too high. I think the first form is the convenient way to express this.

Thanks

**Comment by dpvc** [comment]
This is a duplicate of #712 (modulo that one talking about `\hat` and this one `\vec`).  Please see that issue for an extended discussion of the situation and why it is not likely to be changed.
