### ISSUE TITLE
Font size, once more

### ISSUE THREAD

**Issue by mhchem** [mathjax/MathJax#1562]
I wonder why https://mhchem.github.io/MathJax-mhchem/ renders so differently in different browsers. I checked the x height calculation, but that is almost identical. Also, the bounding box of the text is pretty much the same. (The parent's height is 31px or a little more.) However, the letters inside differ quite a lot. In particular the last example appears much larger.

Windows Chrome 51.0
![win 10 chrome 51_0](https://cloud.githubusercontent.com/assets/16336692/16968211/a93e40d0-4e0d-11e6-8ab7-934b54471d61.png)

Ubuntu Chromium 51.0
![ubuntu chromium 51_0](https://cloud.githubusercontent.com/assets/16336692/16968178/77e0de62-4e0d-11e6-914a-9d9364cbb020.png)

Windows Firefox 47.0
![win 10 firefox 47_0](https://cloud.githubusercontent.com/assets/16336692/16968212/ab34599c-4e0d-11e6-9fa3-9d639928ab51.png)

Ubuntu Firefox 47.0
![ubuntu firefox 47_0](https://cloud.githubusercontent.com/assets/16336692/16968184/83f47d94-4e0d-11e6-9213-949a5e9e6d6e.png)

**Comment by dpvc** [comment]
Well, different browsers and OSes do handle fonts differently; in particular, the font height can vary from browser to browser.  Also, MathJax tries to match the math font's ex-height to that of the surrounding font, so depending on what the surrounding font is, the math font height may vary.  So in your Ubuntu Firefox, the default font might be different from the one used in the other browsers, which could account for it being larger.

Unlike in TeX, you are not going to get identical output across browsers and OSes.
