### ISSUE TITLE
Name of cache busting parameter

### ISSUE THREAD

**Issue by millette** [mathjax/MathJax#1570]
Hello, I'm new to MathJax, but checked older (and closed issues) and I don't think this was brought up yet.

Long story short, I'm using CouchDB to serve the MathJax files for a CouchApp (instead of nginx or another http server). The ```rev``` parameter that's added to the automatically loaded JS files is interfering with CouchDB's semantics.

Searching this source code, I see ```rev``` is only used in a couple of places, and only for cache busting. Correct me if I'm wrong.

May I suggest changing ```rev``` to ```ver```? From what I understand, if shouldn't change anything in MathJax, but it would stop interfering with CouchDB. If you feel using another hardcoded parameter name could lead the further problems down the line, we could make it an option.

For now, I'm using this workaround:
```js
window.MathJax = {
  AuthorInit: function () {
    // couchdb really doesn't like the ?rev argument
    // appended by the MathJax loader;
    // taking care of that here (side effects, perhaps?)
    window.MathJax.cdnVersion = ''
  }
}
```

I'm ready to write a quick patch for the 1st option if this solution is accepted (s/rev/ver/). I can also try to make it an option if that's preferable.

Thoughts?

**Comment by pkra** [comment]
Could you provide some background on why this is causing problems with CouchDB?

**Comment by millette** [comment]
According to the [Officlal CouchDB Docs](http://docs.couchdb.org/en/1.6.1/api/document/attachments.html):
<dl>
<dt>Query Parameters:</dt>
 <dd>rev (string)</dd>
 <dd>Document’s revision. Optional</dd>
</dl>

```rev``` is used to fetch CouchDB internal revisions for an attachment, and the name of this query parameter can't be changed (without recompiling erlang, I guess). I also inquired on #couchdb (Freenode) and got the same reply.

**Comment by millette** [comment]
In effect, the JavaScript files autoloaded by MathJax aren't found (404) when attached to a CouchDB document since the specified ```rev``` doesn't exist according to it. Using ```ver``` or any other parameter name would probably work, only ```rev``` conflicts.

**Comment by dpvc** [comment]
I don't have any problem with changing `rev` to `ver`; it is only used to break caches, as you point out.  @pkra, what do you think?

I was going to suggest essentially the patch that you are already using (I didn't see it in the email version sent to me when you initially posted, so I assume you edited it afterward).

Alternatively, you could use

```
var MathJax = {
  AuthorInit: function () {
    MathJax.Ajax.fileRev = function (file) {
      var rev = MathJax.cdnFileVersions[file] || MathJax.cdnVersion;
      if (rev) {rev = "?ver="+rev}
      return rev;
    }
  }
}
```

which does the change you are asking for.

**Comment by millette** [comment]
Ah, replacing the fileRev(), less magic than my workaround, thanks.

CouchDB might not be the most popular web server, it's probably less work to change the parameter name than to add a description of the workaround to a FAQ on in the README.

The patch would be trivial but let me know if you want me to provide it.

With the possibility of changing fileRev(), I hereby retract my suggestion to make the "rev" parameter changeable thru an option :-) A new hardcoded value will do just fine.

**Comment by dpvc** [comment]
It is probably easier for us to do it, as contributed changes require an SLA, which is too much of a hassle for this one-word change.

**Comment by millette** [comment]
I wouldn't want copyright to swap 2 letters :-)

**Comment by dpvc** [comment]
Right.  But administrators like to have all the forms.  Thanks for your contribution!

**Comment by pkra** [comment]
> @pkra, what do you think?

I don't mind either way. @zorkow?

**Comment by dpvc** [comment]
The `issue1570` branch of my fork of MathJax includes the change.

**Comment by dpvc** [comment]
==> Merged

**Comment by millette** [comment]
Thanks!

**Comment by zorkow** [comment]
I'm fine with that.

**Comment by smonsarr** [comment]
We just got bitten by this.
In our content provider ?V=xxx means select a specific "view", all resources loaded with ?V=2.7.9 are met with 404.

Have changed this to :
if (V) {V = "?mjv!"+V}

This has the benefit of not being a standard query parameter, and therefore a lot less likely to interfere with other systems while fulfilling the required effect of making the URL to MathJax resources reflect the current version.
