### ISSUE TITLE
Mathjax duplicates content in the print view

### ISSUE THREAD

**Issue by andela-engmkwalusimbi** [mathjax/MathJax#1572]
Print View
<img width="271" alt="screen shot 2016-08-03 at 1 06 49 pm" src="https://cloud.githubusercontent.com/assets/11237598/17361851/301ef162-597b-11e6-8cca-970532855223.png">

I'm having problems with rendering content in a print view. The image above is the print view and below is how it should look like.

I'm loading the latest version of MathJax from a CDN.
Normal View
<img width="246" alt="screen shot 2016-08-03 at 12 51 37 pm" src="https://cloud.githubusercontent.com/assets/11237598/17361492/73e1df88-5979-11e6-863a-565d329ee385.png">

**Comment by pkra** [comment]
Please provide more information, in particular a live sample and browser/OS versions -- see https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports for advice.

A random guess would be that the print stylesheet of the page makes invisible content from the AssistiveMML extension visible. E.g., http://cdn.mathjax.org/mathjax/latest/test/sample-tex.html prints just fine.

**Comment by andela-engmkwalusimbi** [comment]
Here's a [fiddle](https://jsfiddle.net/mahadJr/ug0m2zb4/), you can refer to. When you click the print button, content renders poorly. I'm using a simpler fiddle to express what I'm trying to achieve. there are a number of hidden divs that get displayed in the print view when the button is clicked. Tried to add Mathjax in the print view too, but I get more problems.


All browsers have this problem. It's not a browser problem.

**Comment by pkra** [comment]
Thanks. 

You are cloning only the HTML element and not the CSS that MathJax adds to the head. Hence, the visually hidden MathML generated by the AssistiveMML extension (with class `MJX_Assistive_MathML`) is visible.

This kind of cloning will also usually break MathJax's layout (e.g., this example fails if you switch to CommonHTML or SVG output).

The easiest solution would be to copy the styles.
