### ISSUE TITLE
[SVG, HTML-CSS output] menclose does not inherit color

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1573]
Via the user group. 

For SVG, it looks like we forget `menclose` in https://github.com/mathjax/MathJax/issues/1002. This seems to be it: https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/SVG/autoload/menclose.js#L116.

For HTML-CSS it seems to be https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/HTML-CSS/autoload/menclose.js#L58

**Comment by pkra** [comment]
Edited my OP with information for HTML-CSS.

**Comment by dpvc** [comment]
The `issue1573` branch of my fork of MathJax includes the fix.  Thanks for finding the lines that caused the problem.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/GeneralLayout/menclose/issue1573.html
