### ISSUE TITLE
Mathjax configuration menu does not work for Responsive Web Design(RWD) sites 

### ISSUE THREAD

**Issue by amughrabi** [mathjax/MathJax#1576]
For Desktop view, we can right click on any formula to show the settings popup:
![mathjax](https://cloud.githubusercontent.com/assets/8401456/17461299/2d0e4118-5c90-11e6-99e5-c5557a998e9e.png)

For Tablet and Mobile views, this option is no longer available. Is there any configuration needed to be added?

Thanks.

**Comment by pkra** [comment]
On touchscreens, the MathJax menu can be triggered using double-tap+hold. 

Unfortunately, due to inconsistent OS and browser behavior this can sometimes be hard to trigger and we haven't found a completely reliable mode for triggering the menu across touch-based platforms.
