### ISSUE TITLE
Mathjax does not render exponents in parentheses correctly

### ISSUE THREAD

**Issue by Blendify** [mathjax/MathJax#1581]
I am using mathjax as a sphinx extension and I am having issues with math like:

:math:`e^(-8x^2/ radius^2)`
:math:`2^(steps -1)`
:math:`5^(x-1)`

If I should write the expressiondifferently let me know other wise I will wait for a fix.

Page with this problem:

https://www.blender.org/manual/render/cycles/settings/motion_blur.html#object-properties

**Comment by pkra** [comment]
You need to use `{...}` instead of `(...)` for grouping in TeX.

**Comment by pkra** [comment]
See also http://docs.mathjax.org/en/latest/tex.html (in particular the first note pointing to wikibooks).
