### ISSUE TITLE
Add extension (similar to) mathtools [was: Support for \xrightleftharpoons]

### ISSUE THREAD

**Issue by sassanh** [mathjax/MathJax#1582]
While I can draw arrows with `\rightarrow` for example, I can't use `\xrightleftharpoons{\hspace{8cm}}` which is supported in LaTeX. Am I missing something or is it not supported? If it's not supported is there any document I can read about which parts of LaTeX are supported in MathJax?

**Comment by pkra** [comment]
I'm not sure which TeX package you have in mind, but you can define custom arrows using the extpfeil extension, http://docs.mathjax.org/en/latest/tex.html#extpfeil, e.g., `\require{extpfeil} Newextarrow{\xrightharpoonup}{5,10}{0x21C0}`

**Comment by sassanh** [comment]
I guess it's `mathtools`, please take a look at this: http://tex.stackexchange.com/questions/324906/having-a-leftrightharpoons-with-custom-length

**Comment by sassanh** [comment]
> \require{extpfeil} Newextarrow{\xrightharpoonup}{5,10}{0x21C0}

It didn't work in the demo dialog provided in https://www.mathjax.org/, I wrapped it with $$.

**Comment by pkra** [comment]
>I guess it's mathtools, 

Mathtools is not directly supported (and probably not a good name for an extension since it does a lot of text mode). But large parts of it are easy to implement (e.g., harpoons), see also #1059.

If someone wants to contribute, the best place to start would be https://github.com/mathjax/MathJax-third-party-extensions/.

> I guess it's mathtools, 

It works for me; you need to use the newly defined arrow, e.g., `$$\require{extpfeil} \Newextarrow{\xrightharpoonup}{5,10}{0x21C0} \xrightharpoonup{x}$$`..

**Comment by dpvc** [comment]
@pkra, your original code was missing a backslash before `Newextarrow`.  Might be worth editing that in in case anyone else gets to this issue looking for the answer.

**Comment by pkra** [comment]
@dpvc ah, sorry. Thanks for catching that!

**Comment by sassanh** [comment]
Thanks for info, so I close this.

**Comment by pkra** [comment]
Re-opening this as a feature request for mathtools.

**Comment by sassanh** [comment]
Oh, I thought you're not interested to add this to core. Thanks for reopening then.

**Comment by pkra** [comment]
> Oh, I thought you're not interested to add this to core. Thanks for reopening then.

No problem. Let me try to clarify. 

We (the MathJax team) do not have plans to work on this, thus it's only in the long-term backlog milestone (like most feature requests). 

If somebody wants to contribute, they should start in the third party repo. Nevertheless, those extensions can move up into core. 

Also, the third party repo's tracker isn't used much so it's better to track features here.

**Comment by dpvc** [comment]
MathJax v3.2 includes a `mathtools` extension that implements most of the macros from the mathtools package.
