### ISSUE TITLE
x^x^2 is not rendered

### ISSUE THREAD

**Issue by proy87** [mathjax/MathJax#1583]
Simple power is not rendered: `x^x^2`

**Comment by pkra** [comment]
This is invalid TeX. You need to group the exponents, e.g., `x^{2^2}` or `{x^2}^2}`.

**Comment by pkra** [comment]
Correction: the latter example should be `{x^2}^2`.

**Comment by proy87** [comment]
OK. But http://quicklatex.com/ shows the formula, at least it doesn't show error as MathJax.

**Comment by dpvc** [comment]
The are suppressing all LaTeX errors (try something like `x_{` for example).  So the fact that you get output for that doesn't make it valid LaTeX.  If you run a real LaTeX installation (not in batch or quiet mode) you will get an error message for `x^x^2` just as you do in MathJax.

**Comment by proy87** [comment]
Oh. OK. Is there something like quiet mode in MathJax?

**Comment by dpvc** [comment]
Only for undefined macro names, not generic errors.

**Comment by proy87** [comment]
OK. Thank you for your explanation.
