### ISSUE TITLE
[TeX input] \operatorname {Res\ } throws error

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1586]
From https://phabricator.wikimedia.org/T136812. 

In a quick test, this didn't cause an error in real LaTeX (but I couldn't check warnings). 

Is this expected behavior?

**Comment by dpvc** [comment]
It's a bug (related to #1563).  Arguments to some macros have leading and trailing spaces removed, and the trimming meant that the space from `\ ` was removed, leaving it essentially `{Res\}`, and so the closing brace was escaped, and that messed up the brace balancing.

The `issue1586` branch of my fork of MathJax includes a fix.

**Comment by dpvc** [comment]
==> In testsuite

LaTeXToMathML/issue1586.html

**Comment by physikerwelt** [comment]
@dpvc Thank you. We cherry picked your change and it now works for wmf cf.
https://en.wikipedia.org/api/rest_v1/media/math/render/mml/a2c9f30d6ff4230bf5406de1fc4ccdb6ba2712b0

**Comment by dpvc** [comment]
@physikerwelt, glad you were able to get it working for you.

**Comment by dpvc** [comment]
==> Merged
