### ISSUE TITLE
mathjax.org not working with IE11/

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#1598]
On windows 7 with IE11, mathjax.org doesn't seem to want to render the math when you click on "view samples". See attached images for example and IE 11 version info. I also tried the other rendering options (SVG, etc) and they failed also.

The "live demo" buttons do display appropriately.

![ie-version](https://cloud.githubusercontent.com/assets/1545836/17881268/eb63bd58-68b8-11e6-9101-9e5db29036cf.png)
![ie11-bug](https://cloud.githubusercontent.com/assets/1545836/17881269/eb7b162e-68b8-11e6-8e85-083f72dc0bed.png)

**Comment by pkra** [comment]
Is this specific to mathjax.org?

**Comment by NSoiffer** [comment]
So far, that's the only site/example on which I have seen that happen.

**Comment by pkra** [comment]
Closed in favor of downstream issue https://github.com/mathjax/MathJax-website/issues/63
