### ISSUE TITLE
Interesting colon rendering

### ISSUE THREAD

**Issue by karoltarasiuk** [mathjax/MathJax#1601]
Here's the screenshot of the issue I found:
<img width="33" alt="screen shot 2016-08-24 at 10 00 15" src="https://cloud.githubusercontent.com/assets/1845230/17913998/cce1785a-69e1-11e6-9fb1-b556d7fff425.png">

I see the same results when trying your live demo on official website. HTML I'm using is as follows:
```
<p>\(V\):</p>
<p>\(V:\)</p>
<p>\(V\);</p>
<p>\(V;\)</p>
<p>\(V\).</p>
<p>\(V.\)</p>
<p>\(1\):</p>
<p>\(1:\)</p>
<p>\(1\);</p>
<p>\(1;\)</p>
<p>\(1\).</p>
<p>\(1.\)</p>
```

Colon is the only character rendered with an extra space. So my question is - is it intentional? And then could you give me some explanation for it? Or maybe it is a bug? Thanks!

**Comment by pkra** [comment]
In TeX, the colon is considered a relation symbol and gets additional spacing, e.g., see http://tex.stackexchange.com/questions/37789/using-colon-or-in-formulas#37791
