### ISSUE TITLE
update asciimath input for v2.7

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1605]
I think there were some relevant changes we should pull in.

**Comment by dpvc** [comment]
The `issue1605` branch of my fork of MathJax includes the changes.  There seems to have been only [one commit](https://github.com/asciimath/asciimathml/commits/master/mathjax/jax.js) since 2.6.

**Comment by pkra** [comment]
> There seems to have been only one commit since 2.6.

Yep, I noticed that as well.

@drlippman anything you want to fix before MathJax v2.7?

**Comment by dpvc** [comment]
==> Merged.

**Comment by drlippman** [comment]
There's been a few improvement requests I haven't gotten to yet. What's the timeline? None are a big deal, but might be nice to get them done if I can find the time.

**Comment by pkra** [comment]
> What's the timeline?

Beta is starting pretty soon (this week or next) but I think we might be able to squeeze this in during the beta run.

**Comment by drlippman** [comment]
OK, I'll see if there's anything I can get done in the next day or two.  Thanks.

**Comment by drlippman** [comment]
I just made three to the asciimath repo with possible changes addressing lingering issues.  I'm not sure exactly what the process should be for vetting those changes.

The [bracket one](https://github.com/asciimath/asciimathml/pull/61) is really straightforward and can be merged without concern.  The other two have potential side effects, but I worry that no one else is going to look at them and give feedback.  It obviously would make things a lot easier if we had unit tests, but we don't :/

**Comment by pkra** [comment]
Closing this as we finalizing the release.
