### ISSUE TITLE
[locale] update MathJax.js

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1607]
Cf. https://github.com/mathjax/MathJax/pull/1604#issuecomment-242829835

**Comment by pkra** [comment]
I noticed that `lki` had not been added last time around. 

There are two more locales (Chechen, Welsh) that are present in the core repo but far from the 40% completion threshold we use today (4% and 7% respectively); I would not add them to MathJax.js at this time.

**Comment by dpvc** [comment]
==> Merged
