### ISSUE TITLE
How to break client caching, by using the version information in Mathjax code?

### ISSUE THREAD

**Issue by TonyChanNJU** [mathjax/MathJax#1609]
Hi

I read the code of MathJax.js, and see

> 

MathJax.version = "2.6.1";
MathJax.fileversion = "2.6.1";
MathJax.cdnVersion = "2.6.1";  // specifies a revision to break caching
MathJax.cdnFileVersions = {};  // can be used to specify revisions for individual files

> 

I installed the latest version of Mathjax on my server, the same directory as 2.6.0
But I don't know how to use this version info to break caching.

**Comment by pkra** [comment]
The `MathJax.cdnVersion` value is used for this by modifying the query string that loads MathJax's components (e.g., `MathJax/jax/output/HTML-CSS/fonts/TeX/fontdata.js?rev=2.6.1` -- note `rev` has changed in v2.7.0-beta.0 to `V` )

But you'd have to break loading of `MathJax.js` manually (by adding something to the query url you load it with).
