### ISSUE TITLE
How to detect that the rendering process of Mathjax has completed?

### ISSUE THREAD

**Issue by TonyChanNJU** [mathjax/MathJax#1611]
The rendering process need almost 1 sec on mobile device.

I want to hide the process, using a div.

So, is there any api, event or config to tell user the process has completed ?

Thanks!

**Comment by dpvc** [comment]
You can push a function onto the MathJax queue, and it will not be run until the previous actions in the queue (and in particular, the typesetting) is complete.  E.g., 

```
<script type="text/x-mathjax-config">
MathJax.Hub.Queue(function () {
   ... this won't run until the initial typesetting is done ...
});
</script>
```

Put this *before* the script that loads `MathJax.js` itself.

See [this page](https://cdn.mathjax.org/mathjax/latest/test/sample-all-at-once.html) for an example of how you might use this to make the page visible only after the math has been typeset.
