### ISSUE TITLE
How to disable the render tip? 

### ISSUE THREAD

**Issue by TonyChanNJU** [mathjax/MathJax#1614]
During the mathjax render process, tool tips about renderring will show.

Although, we can show all the formula at one, by setting MathJax.Hub.Queue, some tips will still appear.
So, is there any settings to disable mathjax's render tips?

Besides this, when click on the formula, some blue or yellow border will show. How to disable it? 

Thanks！

**Comment by pkra** [comment]
I'm not 100% sure what you're after, but I'm guessing you mean the processing messages. You can configure and disable them via `showProcessingMessages` and `messageStyle`, see http://docs.mathjax.org/en/latest/options/hub.html.

The "border" is likely the outline when an element is in focus. See my http://stackoverflow.com/questions/38986545/override-mathjax-accessibility-blue-box-feature/38990229#38990229 for some comment.

**Comment by TonyChanNJU** [comment]
Thanks for the answer:-)
