### ISSUE TITLE
\mathbf and \imath, \jmath

### ISSUE THREAD

**Issue by bartsnapp** [mathjax/MathJax#1620]
MathJax does not math-bold \imath or \jmath.

![imath](https://cloud.githubusercontent.com/assets/1376703/18519928/b1f5934e-7a73-11e6-8326-d3caade8e804.png)

**Comment by dpvc** [comment]
That is correct, because that is also what LaTeX does.  You need to use `\boldsymbol{\imath}` for a bold version of `\imath`.  If you want a roman (rather than italic) dotless i, even in LaTeX that takes some work.  In MathJax, you could use `\mmlToken{mi}[mathvariant="bold"]{ı}`, but only if you are using the STIX fonts (as the required character isn't in the MathJax TeX fonts).

**Comment by bartsnapp** [comment]
Wow! It seems that if you use STIX fonts, it is automatically roman
(even with $\mathbf{imath}$)

I never guessed that STIX fonts would render that differently.

**Comment by dpvc** [comment]
> It seems that if you use STIX fonts, it is automatically roman (even with `\mathbf{math}`)

That should not be the case, and I can't reproduce it.  Here is what I get for

```
\imath\mathbf{\imath}\boldsymbol{\imath}\\
\mmlToken{mi}[mathvariant="normal"]{ı}\mmlToken{mi}[mathvariant="bold"]{ı}
```

using the STIX fonts: 

<img width="51" alt="dotless-i" src="https://cloud.githubusercontent.com/assets/432782/18523682/3f86c94e-7a83-11e6-80b1-9bf76d330292.png">

**Comment by bartsnapp** [comment]
Ok. This somewhat weird: With the attached files, I seem to be getting different behavior.
If you can confirm your behavior with my file, then I must simply have out-of-date software.
[imath.pdf](https://github.com/mathjax/MathJax/files/473255/imath.pdf)

**Comment by dpvc** [comment]
Sorry, it's miscommunication.  When I said use the STIX fonts, I was talking about in MathJax, not LaTeX, and my example above with the image is for MathJax as well.  It looks like the `stix` package in LaTeX alters things so that `\mathbf` does affect `\imath`.  That isn't the case in MathJax.
