### ISSUE TITLE
About ttf font of mathjax

### ISSUE THREAD

**Issue by TonyChanNJU** [mathjax/MathJax#1624]
Hi
I saw my friend's font code about mathjax  as below

`url('http://{cdn_url}/Mathjax-master/fonts/HTML-CSS/TeX/ttf/MathJax_Math-Italic.ttf')  format('truetype'), `

But, I can't find the font file in this directory. And my friend may forget it........

So, I wonder is there any ttf font files in MathJax? 

Thanks a lot!

**Comment by pkra** [comment]
> So, I wonder is there any ttf font files in MathJax?

No, there are not. 

See, e.g., https://github.com/mathjax/MathJax/tree/master/fonts/HTML-CSS/TeX for the font formats we provide.
