### ISSUE TITLE
MathJax doesn't always load in the Tor Browser even with low Privacy and Security Settings and even using Firefox or Chrome routed through Tor

### ISSUE THREAD

**Issue by kitroti** [mathjax/MathJax#1625]
MathJax sometimes loads (rarely), sometimes doesn't at all, and sometimes it loads but some packages don't work (such as \require{cancel} ...) even do the Tor Browser is with low Privacy and Security Settings

I suspect that this has to do with the fact that cdn.mathjax.org is using CloudFlare which blocks by default all Tor exit nodes by showing them a captcha.

This issue is not limited to the Tor Browser only, if I load tor.exe and configure Firefox and Chrome to route through Tor, the same issue reappears again, with MathJax not loading.

It would be greatly appreciated if there was some way to fix this, as I'm -- along with many others -- a 100% full time Tor user.

**Comment by pkra** [comment]
Thanks for raising this. I don't know if we will be able to do much about this, but we are open to suggestions. Please note that we don't have the resources to use a different CDN provider. 

I'm wondering if one of the access rules mentioned [here](https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-) might help. I'm guessing the only way to do this is to visit one of our pages, e.g., http://cdn.mathjax.org/mathjax/latest/test/examples.html and then hope the confirmation works long enough to be useful (i.e., for a session). Then again, if somebody else uses the same TOR node for something that gets it blocked again, this might not be practical.

I suppose an alternative would be to block our CDN while using a greasemonkey script to inject a local copy of MathJax whenever MathJax is loaded from cdn.mathjax.org. Or maybe redirect cdn.mathjax.org to a local server hosting your own copy of MathJax.

**Comment by pkra** [comment]
Marked as abandoned.

**Comment by cledecitif** [comment]
@pkra There's a proposed solution, if implemented it may resolve this issue https://github.com/cloudflare/challenge-bypass-specification

**Comment by pkra** [comment]
@cledecitif thanks for pointing that out. That would be a nice upstream solution should it be successful. 

In the mean time, it seems the most pragmatic solution would be to build a plugin or greasemonkey script that replaces calls to the CDN with calls to a local MathJax copy. We're happy to help answer questions but we don't have the resources to maintain such plugins. There's an example of a Chrome extension https://github.com/emichael/texthings (which calls the CDN but that wouldn't be hard to change) for  those interested.

**Comment by domapine** [comment]
@pkra You don't even need to change your CDN provider, you can just turn off CloudFlare's captchas: https://support.cloudflare.com/hc/en-us/articles/200170096-How-do-I-turn-the-CloudFlare-captcha-challenge-page-off-

**Comment by pkra** [comment]
@domapine disabling captcha's is only available at the [Enterprise-plan level](https://www.cloudflare.com/plans/) (which does not even have a price point but is definitely beyond our means).

**Comment by domapine** [comment]
@pkra What about the "Essentially Off" option?

**Comment by pkra** [comment]
> @pkra What about the "Essentially Off" option?

That's our current setting.

**Comment by domapine** [comment]
@pkra Sorry, I gave you the wrong link, have a look at this one: https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

**Comment by pkra** [comment]
@domapine thanks for that link! That looks like it could be a solution. 

We'll have to discuss it internally.

**Comment by kitroti** [comment]
@pkra So where's the progress :) ?

**Comment by pkra** [comment]
No decision yet, I'm afraid.

**Comment by pkra** [comment]
Closing this as `cdn.mathjax.org` is being retired. See https://www.mathjax.org/cdn-shutting-down/ and #1725 for details.
