### ISSUE TITLE
support webpack

### ISSUE THREAD

**Issue by trebor** [mathjax/MathJax#1629]
please consider supporting webpack.

**Comment by pkra** [comment]
Compatibility with build tools like webpack is planned for v3.0.

**Comment by ssougnez** [comment]
Hi,

do you have an idea of the release date of the v3.0. Mathjax is really an awesome library but nowadays, it becomes really critical for this kind of library to be compatible with tools such as WebPack. 

Thanks and keep up the good work ;-)

**Comment by jpatel3** [comment]
+1

**Comment by pkra** [comment]
We don't plan for a release date that's comparable to v2 releases because v3 will be much more modular. You can follow discussions at https://groups.google.com/forum/#!forum/mathjax-dev. 

The first "set" (MathML input, HTML output) should be ready by the end of summer.

**Comment by pkra** [comment]
As mentioned in this thread, https://github.com/mathjax/mathjax-v3/ (in beta) supports all modern module systems. See the demos for some examples.

**Comment by daveisfera** [comment]
Now that v3 is available, is there an example of how to do this?

**Comment by trebor** [comment]
i'm a huge fan of working forkable examples.  here is a [working example](https://observablehq.com/@andy0130tw/mathjax) of mathjax 2.7.5 in observable.  so simple, so easy to understand.  i've tried to get mathjax 3.0.0 working in observable with no luck.  any hope of some help with that?

**Comment by pkra** [comment]
Here's an example using webpack https://github.com/mathjax/MathJax-demos-web/tree/master/custom-build

**Comment by dpvc** [comment]
MathJax v3 can be used with webpack.
