### ISSUE TITLE
Fast-preview extension doesn't work

### ISSUE THREAD

**Issue by arun1595** [mathjax/MathJax#1630]
I was trying to make use of the [fast-preview extension](http://docs.mathjax.org/en/latest/options/fast-preview.html) and I modified my MathJax configuration to

```javascript
MathJax.Hub.Config({
    extensions: ['fast-preview.js'],
    "fast-preview": {
    Chunks: {EqnChunk: 10000, EqnChunkFactor: 1, EqnChunkDelay: 0},
    color: "inherit!important",
    updateTime: 30, updateDelay: 6,
    messageStyle: "none",
    disabled: false
  },
    skipStartupTypeset: true,
    messageStyle: 'none',
    'HTML-CSS': {
      showMathMenu: false
    }
  });
  MathJax.Hub.Configured();
```

But it doesn't seem to work. When I tried to modify the `color` property to something else, I didn't notice the color change. 

And then I removed the top-level `messageStyle` property to see if the `messageStyle` property on the `fast-preview` has any effects on it. To my surprise, I was still able to see the status message on the lower left hand corner of the page.

This confirmed that `fast-preview` is not working as I expected and that I was missing something.

What part of configuration am I missing? 

If you need any other information, I am happy to provide that.

Thanks!

**Comment by pkra** [comment]
Thanks for the report. It's difficult to say if what you're seeing is expected behavior or not. Can you provide a self-contained example (either your own page or using jsbin, codepen etc)?
