### ISSUE TITLE
Calling "MathJax.Hub.Queue(["Typeset",MathJax.Hub]);" is generating the markup again.

### ISSUE THREAD

**Issue by abhikhatri** [mathjax/MathJax#1634]
Hey guys, I recently started using Mathjax and I having an issue with "MathJax.Hub.Queue(["Typeset",MathJax.Hub])" command and I have a simple editor that adds latex commands to my html document and whenever I add something and click ok it runs that command and generate output like this. It works fine for the first time. 
![screen shot 2016-10-08 at 6 53 32 pm](https://cloud.githubusercontent.com/assets/6468965/19213369/a993dfe4-8d88-11e6-83bb-1500eec0eb2c.png)

But whenever I add another item and it runs typeset command and it generate the output again from `<script type="math/tex" ></script>` on existing elements like so.

![screen shot 2016-10-08 at 6 53 44 pm](https://cloud.githubusercontent.com/assets/6468965/19213402/75f90c26-8d89-11e6-97fe-bd3346e6380d.png)

How can I avoid either generating that script tag or avoid parsing it when the typeset runs. Adding `tex2jax_ignore` class on it doesn't work as well. 

Thanks in advance 😊

**Comment by pkra** [comment]
There's not much to say without a live sample page, I'm afraid. 

Most likely, you are modifying the DOM in a way that makes MathJax think the equation has not yet been typeset.

You might want to check out http://docs.mathjax.org/en/latest/advanced/typeset.html and the example at http://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html.

**Comment by abhikhatri** [comment]
@pkra Oh yeah I figured it out, I was copying the whole html content instead of just copying the latex that why it was recompiling everything that was in that `<script>`.

**Comment by pkra** [comment]
Thanks for the follow-up, @abhikhatri. Glad to hear you could resolve the issue.

**Comment by abhikhatri** [comment]
Yeah finally resolved it 😁
