### ISSUE TITLE
Big brackets not scaling consistently around dfracs

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1642]
Compare `\left[ \dfrac{x}{2} \right]` to `\left[ \dfrac{1}{2} \right]`:

![image](https://cloud.githubusercontent.com/assets/295205/19409139/4c9e26dc-92ce-11e6-84f9-91b3c634c723.png)

In the first case, the 2 in the denominator reaches outside the bracket. In the second case, it doesn't. This happens with HTML-CSS and CommonHTML with at least MathJax 2.7.0 and 2.6.1 (I didn't test previous versions).

Compare to the SVG rendering, which is a bit better:

![image](https://cloud.githubusercontent.com/assets/295205/19409164/b859681e-92ce-11e6-8737-85a9bc4d6079.png)

Is this expected behavior?

(both images rendered with Chrome 53.0.2785.143 m under Windows 10)

**Comment by dpvc** [comment]
This is correct behavior, and is consistent with LaTeX output.  MathJax uses the TeX algorithm for determining the size of stretchy delimiters, and it provides for a small leeway for the delimiters to be undersized, as in this case.  Here is actual LaTeX output:

<img width="264" alt="brackets" src="https://cloud.githubusercontent.com/assets/432782/19422683/50f93e24-93e6-11e6-8bbd-01a56e2836fe.png">

If you want the brakes to be the same size in the first expression, try

    \left[ \dfrac{x\vphantom{1}}{2} \right]

which should produce the same size as the second one

**Comment by pkra** [comment]
> Is this expected behavior?

@dpvc will correct me but I think so; in particular, this matches TeX behavior.

**Comment by pkra** [comment]
Oops. Didn't @dpvc's response for some reason.
