### ISSUE TITLE
SVG tag not converting to png

### ISSUE THREAD

**Issue by dinkarthakur** [mathjax/MathJax#1643]
I got svg tag when converted from mathml , when i try to convert it into png i only got grey line

`<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="23.426ex" height="6.274ex" viewBox="0 -1558.2 10086.3 2701.4" role="img" focusable="false" aria-hidden="true" style="vertical-align: -2.655ex;"><g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-66" x="0" y="0"></use><g transform="translate(717,0)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-28" x="0" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-61" x="389" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-29" x="919" y="0"></use></g><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-3D" x="2303" y="0"></use><g transform="translate(3081,0)"><g transform="translate(397,0)"><rect stroke="none" width="1539" height="60" x="0" y="220"></rect><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-31" x="519" y="676"></use><g transform="translate(60,-686)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-32" x="0" y="0"></use><g transform="translate(500,0)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-3C0"></use></g><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-69" x="1074" y="0"></use></g></g></g><g transform="translate(5305,0)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJSZ2-222E" x="0" y="1"></use><use transform="scale(0.707)" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-3B3" x="787" y="-1270"></use></g><g transform="translate(6346,0)"><g transform="translate(286,0)"><rect stroke="none" width="2340" height="60" x="0" y="220"></rect><g transform="translate(271,720)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-66" x="0" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-28" x="550" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-7A" x="940" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-29" x="1408" y="0"></use></g><g transform="translate(60,-686)"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-7A" x="0" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMAIN-2212" x="690" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-61" x="1691" y="0"></use></g></g></g><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-64" x="9094" y="0"></use><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#MJMATHI-7A" x="9617" y="0"></use></g></svg>`

you can use https://petercollingridge.appspot.com/svg-editor to check 

I'm not sure whether mathjax creating right svg or not

also i got two svg tags !!

**Comment by pkra** [comment]
> also i got two svg tags !!

If you look carefully, you'll notice that the above SVG code includes `use` elements pointing to paths in the other SVG. You'll need to either copy the relevant paths yourself or to disable `useGlobalCache` in the SVG output configuration, cf. http://docs.mathjax.org/en/latest/options/SVG.html.

**Comment by dinkarthakur** [comment]
Thanks now I'm able to convert the svg to png. Its working fine
