### ISSUE TITLE
Should linebreak/wrap text when it exceeds

### ISSUE THREAD

**Issue by Ahmed310** [mathjax/MathJax#1650]
Text should wrap when it exceeds depending on the space between words like normal text area block.

<img width="1218" alt="screen shot 2016-10-26 at 6 22 25 pm" src="https://cloud.githubusercontent.com/assets/8081578/19727710/fcab6402-9ba9-11e6-8acc-4ec634ed25c7.png">

**Comment by pkra** [comment]
Please read the documentation at http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking.
