### ISSUE TITLE
MathJax change the standard backflash on another character

### ISSUE THREAD

**Issue by darkthefirst** [mathjax/MathJax#1651]
**MathJax**. Can I somehow change the standard backslash on another character. Having problems with escapes in jquery post.

**Comment by pkra** [comment]
Do you mean "backslash" (not "backflash") by any chance? 

You might want to add a sample that exhibits whatever problem you're facing. Changing the backslash seems like a terrible idea; if your only problem is escaping backslashes in JavaScript, then there are probably easier ways to do it.

**Comment by dpvc** [comment]
There is no mechanism for doing that in MathJax's TeX input processing.
