### ISSUE TITLE
Bug: Mjx-over pushes down stacks out of line with surrounding text at certain sizes

### ISSUE THREAD

**Issue by barillax** [mathjax/MathJax#1653]
### Issue Summary

There are some vertical alignment problems with mjx-stack elements at different sizes. I've reproduced this in a CodePen, linked below.

### Steps to Reproduce

View this CodePen: http://codepen.io/barillax/pen/mrNxPR

Notice that at various sizes, the hat, bar, acute, and dot'ed elements may align or not align with the surrounding text. I suspect this inconsistency extends to more mjx-underover pairs, but I haven't tested further.

In the word depósito, there also appears to be too much space to the right of the ó, but that might be better classified as a separate bug.

### Technical details

* MathJax Version: 2.7.0
* Client OS: macOS Sierra 10.12.1
* Browser: Chrome54.0.2840

**Comment by dpvc** [comment]
I believe this is the same issue as #1498.  This is a WebKit bug in rounding up the size of the stack without adjusting the top position to accommodate it.  I do not know of a work-around.

**Comment by pkra** [comment]
Closed as duplicate.
