### ISSUE TITLE
[CommonHTML] [mhchem] spacing between hooked arrows

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1657]
Reported on the User group.  E.g. `\ce{Ni <=> H}` looks significantly different on CommonHTML (vs HTML-CSS and SVG).

**Comment by dpvc** [comment]
Yes, seems to be a bug in CommonHTML's `<mpadded>` implementation.

**Comment by dpvc** [comment]
The `issue1657` branch of my fork of MathJax includes a work-around for this.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/mover/issue1657.html
