### ISSUE TITLE
Rendering MathJax on canvas

### ISSUE THREAD

**Issue by cfloody** [mathjax/MathJax#1658]
Hi all,

I'm attempting to display some LaTeX expressions using MathJax on a canvas. I have found the following workarounds to be fairly helpful:

http://jsfiddle.net/7mdMz/29/
http://jsfiddle.net/RG7yG/4/

My question is that since I'm building this for a web application, the content I display using MathJax is not static, i.e. the LaTeX expressions will change depending on the user input. Is there any way that I can force MathJax to "refresh" its rendering, so that it updates what's being displayed according to the updated LaTeX expression?

I've tried doing this by accessing the DOM directly, as shown below:
`document.getElementById("latexContent").innerHTML = "\(\frac{3}{7}\)";`

But this will just simply display the string itself, and does not get rendered by MathJax.

Any help on this would be greatly appreciated!

Thanks,
Connor

**Comment by pkra** [comment]
You might want to start with the documentation at http://docs.mathjax.org/en/latest/advanced/typeset.html.

**Comment by cfloody** [comment]
Thank you pkra. Really appreciate the quick responses on this repo. Got everything working the way I had hoped :)

**Comment by pkra** [comment]
Thanks for the update. Good to hear that you got everything to work.
