### ISSUE TITLE
Why the chemistry latex can't be rendered with svg setting?

### ISSUE THREAD

**Issue by TonyChanNJU** [mathjax/MathJax#1662]
Hi

I'm using mathjax to render latex equation with svg setting, like
<script async src="{{cdn_url}}/static/js/MathJax-master/MathJax.js?config=TeX-AMS_SVG"></script>

But chemistry latex equation can't be rendered, such as
$(ⅰ)CO(g)+2{H}_{2}(g)$═$C{H}_{3}OH(g)$△${H}_{1}=-90.1kJ$•$mo{l}^{-1}$

I also tried html setting, it worked. 

So, is there any external settings should be added?

**Comment by pkra** [comment]
MathJax renders this string just like LaTeX does so I'm not sure what you are expecting here.

You might want to [read the documentation for the mhchem extension](http://docs.mathjax.org/en/latest/tex.html#mhchem).

**Comment by TonyChanNJU** [comment]
The expected result should be the one in red box.
![image](https://cloud.githubusercontent.com/assets/20067396/20345807/c80f4c5a-ac33-11e6-9456-24248817583c.png)

When I use config=TeX-AMS_HTML-full, the rendered result is as expected.
But, when using config= TeX-AMS_SVG, the chemistry latex expression won't be rendered.

**Comment by dpvc** [comment]
It looks like you may be using a Markdown-based content management system that uses the underscore (_) to indicate italics.  Note that your "{2}(g)$═$C{H}" are in italics, and the underscores that you show in your later message are missing.  That is because they have been turned into <em> or <i> tags in the HTML page.  MathJax runs after Markdown is processed, so it sees the <em> tag rather than the underscores, and since it doesn't process math containing HTML tags, the math isn't typeset.

You may be able to use \_ rather than _ to get around that problem.

You might also consider the mhchem extension, since that is set up specifically to handle Chemistry notation.

Davide

**Comment by pkra** [comment]
> But, when using config= TeX-AMS_SVG, the chemistry latex expression won't be rendered.

Sounds like a problem with your setup. You might want to post a live sample.

**Comment by TonyChanNJU** [comment]
@dpvc 
I tried the workaround, but failed. It may not be a Markdown issue.

@pkra 
I also think there maybe something wrong with my setup. The live page is in a LAN.

I can provide my setup here.

`<script async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
        "jax": ["input/TeX","output/SVG", "output/PreviewHTML"],
        "extensions": ["tex2jax.js","MathMenu.js","MathZoom.js", "fast-preview.js", "AssistiveMML.js"],
        "TeX": {
            extensions: ["AMSmath.js","AMSsymbols.js","noErrors.js","noUndefined.js"]
        },
        "SVG": {
            scale: 80,
            linebreaks: { automatic: true, width: "110%" }
        },
        "messageStyle": "none",
        "showMathMenu": false,
        "menuSettings": {
            inTabOrder: false
        }
      });
</script> `

**Comment by pkra** [comment]
You forgot to enable `$` as inline delimiters. It works fine for me once I enable them, cf. https://codepen.io/pkra/pen/WoGmoz.

**Comment by TonyChanNJU** [comment]
@pkra 
Thanks, Peter! 
It also works for me.

**Comment by pkra** [comment]
OK. Please post general questions to the [MathJax User Groups](https://groups.google.com/forum/#!forum/mathjax-users) where more people weigh in; this helps reduce noise on the issue tracker.
