### ISSUE TITLE
[Menu] "Copy Math As"

### ISSUE THREAD

**Issue by episanty** [mathjax/MathJax#1663]
This should be easy to do and it would aid certain workflows immensely. Currently, if I want to get the LaTeX code for some given MathJax expression, I need to right click > Show Math As > TeX Commands, then go to the new window, select all, copy paste, and close the window.

![workspace 1_144](https://cloud.githubusercontent.com/assets/6827034/20396141/7b20ca10-ace5-11e6-8d98-c4a7eb9e2e7d.png)

As an enormous shortcut to that, there could be a Copy Math As entry below Show Math As in the context menu. This entry would have the same sub-entries as Show Math As, except that instead of opening a new window to display, it would simply output directly into the clipboard.

**Comment by pkra** [comment]
Thanks for the feature request.

It's already mentioned in #1117, actually, assuming you're thinking of the Clipboard API or clipboard.js which seems ready for production since Safari 10 was released.

**Comment by pkra** [comment]
If someone wants to contribute, this shouldn't be hard to implement as a third party extension and then turned into a PR down the road.

**Comment by dpvc** [comment]
This functionality is available in v3.
