### ISSUE TITLE
How to make formula in the center of HTML page , but keep left align in its body.

### ISSUE THREAD

**Issue by yu961549745** [mathjax/MathJax#1669]
just like this
```
                              x+y+z
                              +w
```

**Comment by pkra** [comment]
General purpose questions fit better on our mailing list at https://groups.google.com/forum/#!forum/mathjax-users

You will want to provide a minimal example of what you've tried. In particular, you should say what input method you're using.

**Comment by yu961549745** [comment]
Thanks. 
Although, I haven't found a perfect answer yet. But I found a quit weird solution by myself.

first set the equation left align and set output format is HTML-CSS
```
 MathJax.Hub.Config({]
        jax: ["input/TeX", "output/HTML-CSS"],
        displayAlign:"left"
    });
```
then set the width of span.math to 0, so it's real width would be it's min-width
```
MathJax.Hub.Queue(function() {
    $("div.MathJax_Display span.math").css("width","0");
});
```
and add \\ for every equation, whether you wan't it has a line break or not.
```
\[
x+y+z\\
+w\\
\]
```
for equations you have add the line-breaks by yourself.
```
\[
x+y+z+w\\
\]
```
for equations you in a single line, to make MathJax generate a span with class of MathJax_FullWidth instead of MathJax.

**Comment by dpvc** [comment]
Try this:

```
\[{
x+y+z\\
+w
}\]
```

This forces the expression to be in a box that will cause line breaks to be treated as internal breaks (not centered or indented) rather than normal line breaks (affected by centering and indenting).

See if the does what you need.

**Comment by yu961549745** [comment]
Perfect! dpvc, thank you very much!
