### ISSUE TITLE
Speeding up MathJax by configuring? 

### ISSUE THREAD

**Issue by arogozhnikov** [mathjax/MathJax#1676]
Hi, 
I'm using MathJax for a while and it is an amazing project.

Recently I've tried also KaTeX, which provides limited TeX functionality, but works significantly faster in my experience (Chrome-related mostly, I've read about MathML support). 

I'd like to understand this difference in speed (and how I can reduce it by configuring MathJax):
- is it due to the simpler parsing in KaTeX?  (I seriously doubt, but...)
- is it because MathJax tries to encounter the whole page layout and KaTeX doesn't?
- fonts?
- some other factors I don't know?

Thanks in advance.

**Comment by pkra** [comment]
Please post general questions to our mailing list, https://groups.google.com/forum/#!searchin/mathjax-users/ and https://groups.google.com/forum/#!forum/mathjax-dev.

[This old comment](https://groups.google.com/d/msg/mathjax-users/vStfa_uxbCk/OH19FYTWnG4J) is still largely accurate. Nowadays, mathjax-node allows you to avoid client-side rendering altogether.
