### ISSUE TITLE
[SVG output] add unicode values as <title>

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1677]
Just something I wanted to jot down after doing some accessibility related 

It would be useful to have Unicode in the SVG content.

**Comment by dpvc** [comment]
I'm not sure I understand what you are requesting.  Can you give an example of what you have in mind?

**Comment by pkra** [comment]
Renamed a little. 

Example:

```svg
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="1.678ex" height="2.176ex" style="vertical-align: -0.338ex;" viewBox="0 -791.3 722.5 936.9" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg">
  <defs aria-hidden="true">
  <path stroke-width="1" id="E1-MJAMS-4E" d="M20 664Q20 666 31 683H142Q256 683 258 681Q259 680 279 653T342 572T422 468L582 259V425Q582 451 582 490T583 541Q583 611 573 628T522 648Q500 648 493 654Q484 665 493 679L500 683H691Q702 676 702 666Q702 657 698 652Q688 648 680 648Q633 648 627 612Q624 601 624 294V-8Q616 -20 607 -20Q601 -20 596 -15Q593 -13 371 270L156 548L153 319Q153 284 153 234T152 167Q152 103 156 78T172 44T213 34Q236 34 242 28Q253 17 242 3L236 -1H36Q24 6 24 16Q24 34 56 34Q58 35 69 36T86 40T100 50T109 72Q111 83 111 345V603L96 619Q72 643 44 648Q20 648 20 664ZM413 419L240 648H120L136 628Q137 626 361 341T587 54L589 68Q589 78 589 121V192L413 419Z">
</path>
</defs>
  <g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true">
  <title>ℕ</title>
  <use xlink:href="#E1-MJAMS-4E" x="0" y="0">
</use>
</g>
</svg>
```

This will put `ℕ` in the accessibility tree at the position of the group.

But perhaps this is not the right places for doing so. The idea came up while exploring "deep" aria-labels on MathML children. The result works reasonably well with an HTML output since the characters are in the output; in the SVG output the lack of text breaks this approach. 

This was one idea for overcoming the problem but it should probably be moved to whatever enriches the MathML.

I'm ok with rejecting this.

**Comment by dpvc** [comment]
Thanks for the clarification.  Now I understand.  It probably could be done.

It sounds like something that would be good to discuss during the AT conference at AIM, but perhaps we can't wait that long?
