### ISSUE TITLE
\xlongequal subscript drops too far.

### ISSUE THREAD

**Issue by hesitateh** [mathjax/MathJax#1678]
Using the extfeil extension, if one uses, say, "\xlongequal[du=dx]{u=x+1}" one can see that the expression "du=dx" drifts too far below the long equal sign. On some tablets, the horizontal alignments of the letters inside the expression below the long equal sign are also not consistent.

**Comment by dpvc** [comment]
This is the output of your expression from LaTeX itself:

<img width="137" alt="latex" src="https://cloud.githubusercontent.com/assets/432782/21329322/204af086-c606-11e6-904b-671ebe76cefb.png">

And this is from MathJax:

<img width="108" alt="mathjax" src="https://cloud.githubusercontent.com/assets/432782/21329327/28421ddc-c606-11e6-9a0a-6fde88a782f9.png">

Although the MathJax over and under items are slightly farther from the equal signs than the LaTeX versions, the asymmetry of the distances (i.e., the fact that the lower one is farther away than the upper one) is present in LaTeX, and that is why it is that way in MathJax.

If you would like them to be closer to the same, try

    \xlongequal[\smash{du=dx}]{u=x+1}

or

    \xlongequal[du=dx]{\raise.1em{u=x+1}}

or a combination of the two.

As for the alignment issue, you would need to indicate which renderer you are using (HTML-CSS, SVG, or CommonHTML), the browser in use, and the type of tablet in order for us to help.

**Comment by hesitateh** [comment]
Thank you very much for looking into this!  Sorry that my first post was not very informative. 

From the picture you attached, the position of the under item is somewhat acceptable. But I found out that the problem occurs when I am using the "Common HTML" renderer, the command "\smash" inside the bracket doesn't appear to be effective. 

![2016-12-20-133606_445x211_scrot](https://cloud.githubusercontent.com/assets/21970497/21339335/66dbc472-c6b9-11e6-935e-96fe84782b13.png)


The configuration of MathJax that I am using is as follows: 

- MathJax.js:   v2.7.0

- Common HTML Output Jax: v2.7.0

- TeX/extpfeil Extension v2.7.0

- Browser: Firefox v43.0

- The relevant source header for the webpage is : 

- The script-header of the html source code of the webpage: the same as the one given below. 

==========================================================

For the alignment problem, you can see how it looks in the following picture:
![rect4138r](https://cloud.githubusercontent.com/assets/21970497/21340676/070d0592-c6c3-11e6-8859-b0e654b02d2e.png)

My configuration is as follows:

- MathJax.js v2.7.0

- TeX/extpfeil Extension v2.7.0

- Renderer: HTML-CSS  (This is only my guess, it could also be Common HTML, because I couldn't figure out exactly which renderer the iPad was using; you can't really right-click on the formula and find out....although in the html header I tried to enforced the HTML-CSS renderer, I found that it is not honored by my desktop browser).

- Webpage's html source code header 
`<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
});
</script>`
`<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {extensions: ["AMSmath.js","AMSsymbols.js"]}
});
</script>`
`<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "HTML-CSS": {
    preferredfont: "STIX"
  }
});
</script>`
`<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {extensions: ["extpfeil.js"]}
});
</script>`
`<script type="text/javascript" async
  src="/MathJax/MathJax.js?config=TeX-MML-AM_CHTML">
</script>`

Many thanks!

**Comment by dpvc** [comment]
It does look like there is an issue with CommonHTML that needs to be looked into.

Safari (and WebKit in general) does have some bugs that can cause alignment issues like the ones you are seeing.  These are often affected by the font size, so you might try changing that slightly to see if that helps at all.

> in the html header I tried to enforce the use of the HTML-CSS renderer, I found that it is not honored by my desktop browser

If you change the renderer using the MathJax contextual menu, that setting will override the renderer set by the page, so that is why your changes to the page didn't affect the renderer used.  You would need to clear the MathJax cookie in order to go back to the page defaults.

Note that you can (and probably should) combine your configuration blocks into one:

```
<script type="text/x-mathjax-config"> MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
  TeX: {extensions: ["AMSmath.js","AMSsymbols.js","extpfeil.js"]},
  "HTML-CSS": {preferredFont: "STIX"}
 });
</script>
```

Note the capitalization in `preferredFont` (your setting won't have any effect).  You may also want to change `webFont` to `"STIX-Web"` if you really want to use the STIX fonts for HTML-CSS output.  Also, note that you need to put all the TeX extensions into one array, otherwise you second `extensions` array will override the first one.

**Comment by hesitateh** [comment]
Thank you very much for your very useful suggestions! I did also find that Safari on iOS is not very pleasant to work with.

**Comment by dpvc** [comment]
The spacing has been corrected in MathJax v3.
