### ISSUE TITLE
arrow on tooltip not aligned properly.

### ISSUE THREAD

**Issue by Rahul1992** [mathjax/MathJax#1682]
The :after element of the tooltip on the documentation part is not aligned properly.
<img width="184" alt="screen shot 2017-01-02 at 12 05 12" src="https://cloud.githubusercontent.com/assets/7263138/21588109/c0e260aa-d0e3-11e6-9c32-aa50d76f039a.png">

**Comment by pkra** [comment]
Thanks! Filed in the website repo at https://github.com/mathjax/MathJax-website/issues/66; closing this here.
