### ISSUE TITLE
MathJax in contenteditable div bad behavior

### ISSUE THREAD

**Issue by uperetz** [mathjax/MathJax#1685]
I posted this on [SO](http://stackoverflow.com/questions/41520685/good-browsers-mathjax-and-contenteditable-div) first but no answer can be found there. On most modern browsers when MathJax elements are inserted to a `contenteditable`  div dynamically the caret ends up before the inserted symbol. Moreover, moving it too much right makes it and any typed text disappear. This does not happen on IE 11, amusingly, but does on chrome, edge, and firefox.

A full example and fiddle can be found in the link above.
Many thanks,
kabanus

**Comment by pkra** [comment]
`conteneditable` is a mess (cf. [medium folks](https://medium.engineering/why-contenteditable-is-terrible-122d8a40e480), [ckeditor folks](https://medium.com/content-uneditable/fixing-contenteditable-1a9a5073c35d). It seems anything slightly complex does not work and MathJax definitely falls in that category. 

Either way, StackOverflow is definitely the better place to ask about it.

**Comment by kabanus** [comment]
Seems as though this is a hard problem. I got an achievement in SO for a question no one would touch :). I actually am familiar with your references, but I was looking for the quickest way to implement an inline editor with math. I haven't seen any MathJax example that does this, only two (html) elements based typesetting, one for writing one for viewing.

If the great team here won't touch this (with good reason I guess), do you have suggestions for a quick solution for an inline MathJax element? Even a suggestion on how you would start to tackle this would be appreciated. May turn out I can contribute to the project if no one did this before.
