### ISSUE TITLE
Doesn't work < (great then).

### ISSUE THREAD

**Issue by lk-geimfari** [mathjax/MathJax#1689]
I use `matjax` with TinyMCE and when i try add `<`, it's does not work. Look at screenshots, please:

![](http://i.imgur.com/QLNxyTK.png)

And when i click `submit` i see following:
![](http://i.imgur.com/IZNJUQ4.png)

In the same time `>` work perfectly.

**Comment by dpvc** [comment]
See the [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents) for why this occurs, and how to work around it.  See also #457.

**Comment by lk-geimfari** [comment]
@dpvc I'm sorry. i didn't knew that issue already exist. Thank you.
