### ISSUE TITLE
[CommonHTML] alignment issue along multiple mfracs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1692]
[Reported on PhysicsForums](https://www.physicsforums.com/threads/getting-vphantom-to-work.900606/)

The alignment across numerators (and denominators) is not as good as it is in HTML-CSS and SVG.

**Comment by dpvc** [comment]
I'm not able to reproduce.  The PhysicsFormums page renders properly for me on Chrome on Mac OS.  Haven't tried Windows yet.

**Comment by pkra** [comment]
I could see it on Chrome on Linux. It was a very small effect either way.
