### ISSUE TITLE
mhchem 3 - wrong sub/sup alignment sans-serif

### ISSUE THREAD

**Issue by d3im** [mathjax/MathJax#1693]
With new mhchem (3.0.2) implementation there is a wrong alignment issue, see:
https://jsfiddle.net/8ww1cf90/7/

**Comment by dpvc** [comment]
This is, in fact, the correct placement.  The LaTeX version of your expression produces the same result:

<img width="401" alt="mhchem" src="https://cloud.githubusercontent.com/assets/432782/22146943/7f18e3d4-ded4-11e6-87da-14fe2bc4864c.png">

The new version of the mhchem extension is more faithful to the original LaTeX version (in fact, it was rewritten by the author of the LaTeX package).

I believe that the expression you want is

    \ce{H^{I}Cl, H2^{I}O, H2^{I}SO4, NaOH^{I}}
