### ISSUE TITLE
Array of stacked arrays does not render correctly

### ISSUE THREAD

**Issue by cbcoutinho** [mathjax/MathJax#1696]
I am trying to produce an array (1 column) of 3 arrays on top of one another, but they are being incorrectly placed next to one another. I've created two examples conveying the same data information - the first is what I would prefer and is being produced correctly, the second is my hackish workaround.

This is my goal - although the smaller brackets are optional:

![example](https://cloud.githubusercontent.com/assets/12901868/22605086/ab8b8748-ea4e-11e6-8e2b-ba903a39188f.png)

Both examples produce expected results when put in a tex document, at least on my machine running texlive 2015:

```
\documentclass{article}
\usepackage{amsmath}

\begin{document}

% This is my hack
\[ X = \left[ \begin{array}{rcl}
      x_1 & & y_1 \\
      x_2 & & y_2 \\
      & \vdots & \\
      x_{N-1} & & y_{N-1} \\
      x_N & & y_N \\
  \end{array} \right]\]

% This one is being incorrectly rendered
\[ X = \left[ \begin{array}{c}
     \begin{array}{cc}
       x_1 & y_1 \\
       x_2 & y_2
     \end{array} \\
     \vdots \\
     \begin{array}{cc}
       x_{N-1} & y_{N-1} \\
       x_N & y_N
     \end{array} \\
   \end{array} \right]\]

\end{document}
```

To see an example of what I'm talking about, check out my project's documentation [specifically here](https://cbcoutinho.github.io/learn_dg/proc/getjacobian.html), currently showing both versions of the arrays I reposted above

Currently I'm using the documentation engine ([FORD](https://github.com/cmacmackin/ford)), which uses MathJax as its LaTeX engine through python-markdown, of which I'm using v2.6.8. I'm not sure if the issue is with FORD, python-markdown, or totally upstream with you guys - I'm totally assuming it's a MathJax issue, so correct me if I'm wrong.

If this issue is not related to MathJax itself, feel free to let me know and I'll bring it up with the python-markdown maintainers.

**Comment by dpvc** [comment]
Your initial page is not coming through quite as you listed it above.  When I view the page source, I see

``` html
<p>\[ X = \left[ \begin{array}{c}
      \begin{array}{cc}
        x_1 &amp; y_1 \\
        x_2 &amp; y_2
      \end{array} \
      \vdots \
      \begin{array}{cc}
        x_{N-1} &amp; y_{N-1} \\
        x_N &amp; y_N
      \end{array} \\
    \end{array} \right]\]</p>
```

Note that two of the the `\\` have become `\` and so no longer act as line breaks in the array.  That is the source of your issue.  You may have to do something special to quote those backslashes (depending on the content-management system you are using), but I'm not sure whey those two would be treated differently than the others.

In any case, the page is coming through with single slashes initially, so MathJax will not treat those as line breaks.

**Comment by cbcoutinho** [comment]
That's strange - for some reason the tool I'm using is allowing some backslashes while not others. I guess I'll just have to use `\\\\` in places where it's needed. Silly workaround, but it works nonetheless.

Thanks for giving me the tip of looking at the output html - I'll check there in the future if I have a similar rendering issue.

Feel free to close if you are satisfied

Cheers!
