### ISSUE TITLE
Test in Hub.Browser.Select argument causes error on non-WebKit platforms / browsers

### ISSUE THREAD

**Issue by jdthorpe** [mathjax/MathJax#1697]
The `[1]` in [this line](https://github.com/mathjax/MathJax/blob/6273842a9746731b9ecca0de18ec9fd50a36df99/unpacked/MathJax.js#L3208) causes this error to be thrown: 

> Cannot read property '1' of null

on non WebKit browsers.  Could easily be re-written to not assume that the the RegEx matched.

**Comment by pkra** [comment]
I cannot reproduce the issue on neither Firefox, IE11, Edge (nor Chrome).

>  non WebKit browsers.

Can you be more specific regarding your browser and OS version? And a live sample that exhibits the problem might be needed.
