### ISSUE TITLE
A problem for subscript

### ISSUE THREAD

**Issue by xiaoyao2102** [mathjax/MathJax#1702]
The code was :
 
$$\alpha_i$$
$$\alpha_i \alpha_i$$

But the render result was : 
![qq20170218164429](https://cloud.githubusercontent.com/assets/12893323/23093216/d88525a4-f617-11e6-9016-51b34197b048.png)

Anyone got an idea？MathJax version is 2.7.0

Thanks a lot

**Comment by pkra** [comment]
This works fine in https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html. 

Without a live sample, there's not much to say. Possibly a CMS editor or something like a markdown processor is interfering.
