### ISSUE TITLE
Use MathMl in HTML

### ISSUE THREAD

**Issue by fatma55** [mathjax/MathJax#1703]
when I write the MathMl code in html page like
`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"> <mo>&#x2211;<!-- ∑ --></mo> <mn>1</mn> <mrow class="MJX-TeXAtom-ORD"> <mo>/</mo> </mrow> <mi>n</mi> <mo>!</mo> </math>`
but it always comes in the middle and I want to adjust it next to the words. Any idea??

**Comment by pkra** [comment]
Remove the `display=block` attribute, see the MathML specification at https://www.w3.org/Math/draft-spec/mathml.html#chapter2_interf.toplevel.atts.
