### ISSUE TITLE
HTML-CSS and SVG output: minimal height for mover base [was [TeX input] \quad has no height]

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1706]
It seems real (La)TeX considers `\quad` to have a height but the TeX input jax only produces an mspace with width.

An example (distilled from a journal article):

```TeX
\widehat{\quad}: O \to Y
```

produces 

```html
<math display="block">
  <mrow class="MJX-TeXAtom-ORD">
    <mover>
      <mspace width="1em" />
      <mo>&#x005E;<!-- ^ --></mo>
    </mover>
  </mrow>
  <mo>:</mo>
  <mi>O</mi>
  <mo stretchy="false">&#x2192;<!-- → --></mo>
  <mi>Y</mi>
</math>
```

but the following is closer to rendering in real LaTeX:

```html
<math display="block">
  <mrow class="MJX-TeXAtom-ORD">
    <mover>
      <mspace width="1em" height="0.5em" />
      <mo>&#x005E;<!-- ^ --></mo>
    </mover>
  </mrow>
  <mo>:</mo>
  <mi>O</mi>
  <mo stretchy="false">&#x2192;<!-- → --></mo>
  <mi>Y</mi>
</math>
```

**Comment by dpvc** [comment]
No, `\quad` has no height in TeX; it is just horizontal space, like in MathJax.  I suspect that the accent code has a minimum height for the base that isn't in MathJax.  If you look at `\widehat{}` in both LaTeX and MathJax, you'll see the difference.

**Comment by dpvc** [comment]
PS, CommonHTML does have the minimum height, but HTML-CSS and SVG don't.

**Comment by pkra** [comment]
Thanks. I renamed the issue.

**Comment by pkra** [comment]
@dpvc do you have any suggestion for a workaround? (This issue came up in production.)

**Comment by dpvc** [comment]
@pkra, you could use

```
\widehat{\vphantom{x}\quad}
```

if you want a source-level solution.  It would also be possible to use a pre-filter to modify the input to replace `\widehat{\quad}` with `\widehat{\vphantom{x}}`.  Or you could use an input post-filter to scan the produced MathML for an `<mover>` with an `<mspace>` as a base, and add the hight to it.  Finally, it would be possible to override the TeX input jax's Accent method so that it checks if the base is an mspace and adds the height attribute.  Something like

```
MathJax.Hub.Config({
  TeX: {Parse: {prototype: {
    Accent: function (name,accent,stretchy) {
      var c = this.ParseArg(name);
      if (c.isa(MML.mspace) && c.height == null) c.height = "1ex";
      var def = {accent: true}; if (this.stack.env.font) {def.mathvariant = this.stack.env.font}
      var mml = this.mmlToken(MML.mo(MML.entity("#x"+accent)).With(def));
      mml.stretchy = (stretchy ? true : false);
      var mo = (c.isEmbellished() ? c.CoreMO() : c);
      if (mo.isa(MML.mo)) mo.movablelimits = false;
      this.Push(MML.TeXAtom(MML.munderover(c,null,mml).With({accent: true})));
    }
  }}}
});
```
should do it (but I haven't tested it).

**Comment by pkra** [comment]
Thanks!

**Comment by dpvc** [comment]
The `issue1706` branch of my fork of MathJax includes a fix.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/issue1706.html
