### ISSUE TITLE
[CommonHTML] on Safari, baseline issue in superscripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1710]
[Reported on SO](https://stackoverflow.com/questions/42509821/mathjax-not-rendering-properly-on-wordpress).

In the CommonHTML output on Safari 10, the baseline for a single character  `mi` seems lower than for a multi-character  `mi`.

Simple example 
```
<math display="block">
  <msup>
    <mi>k</mi>
    <mrow>
      <mi>sec</mi>
      <mi>x</mi>
    </mrow>
  </msup>
</math>`
```

**Comment by dpvc** [comment]
Looks like rounding problems again.  Zooming in causes it to move around (sometimes too high, sometimes OK, sometimes too low).  I haven't looked into it more closely.

**Comment by pkra** [comment]
labeling this as browser bug. We should file an issue with WebKit.

**Comment by pkra** [comment]
Note: this may be due to the font data.
