### ISSUE TITLE
[CommonHTML] rowlines can be too short

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1711]
In the CommonHTML output, a row line can end up too short when the row above is shorter than the maximal row in the table (or perhaps the next row, I'm not sure what the spec says).

This seems due to `rowline`s being drawn via `border-bottom` on the elements from the row above the `rowline`; that row would need additional empty elements at its end (to match the rowline length) to ensure a correct line.

For example,
```html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mtable data-mml-elementary="mstack" columnspacing="0" rowlines="none solid none">
    <mtr>
      <mtd />
      <mtd>
        <mn>4</mn>
      </mtd>
      <mtd>
        <mn>2</mn>
      </mtd>
      <mtd>
        <mn>4</mn>
      </mtd>
      <mtd data-mml-elementary-decimalpos="true">
        <mn>.</mn>
      </mtd>
      <mtd>
        <mn>2</mn>
      </mtd>
    </mtr>
    <mtr data-mml-elementary-msrow-op-front="true">
      <mtd>
        <mo>+</mo>
      </mtd>
      <mtd>
        <none />
      </mtd>
      <mtd>
        <mn>3</mn>
      </mtd>
      <mtd>
        <mn>3</mn>
      </mtd>
    </mtr>
    <mtr>
      <mtd />
      <mtd>
        <mn>4</mn>
      </mtd>
      <mtd>
        <mn>5</mn>
      </mtd>
      <mtd>
        <mn>7</mn>
      </mtd>
      <mtd data-mml-elementary-decimalpos="true">
        <mn>.</mn>
      </mtd>
      <mtd>
        <mn>2</mn>
      </mtd>
    </mtr>
  </mtable>
</math>
```

**Comment by pkra** [comment]
For the record, HTML-CSS and SVG work as expected.

**Comment by dpvc** [comment]
OK, thanks for the report.  It looks like if you add two empty `<mtd></mtd>` elements to the end of the line with the 3's, that does resolve the problem, so you might eb able to use that for now until it is fixed.

I guess the solution is to pad all lines using blank entries so that they all have the same number of columns.

**Comment by pkra** [comment]
Sounds good to me.

**Comment by dpvc** [comment]
The `issue1711` branch of my fork of MathJax includes a fix for this.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue1711.html
