### ISSUE TITLE
Fast preview does not left align if displayAlign is configured to left

### ISSUE THREAD

**Issue by WebStew** [mathjax/MathJax#1713]
**Issue Summary**

Fast preview does not left align if displayAlign configuration setting is set to left. This allows a flash of the fast preview with center alignment and when the typesetting process finishes the equation becomes left aligned.

**Steps to Reproduce**

Visit [CodePen](http://codepen.io/Terminalpunk/pen/peNgqm) for an code setup example.

**Technical Details**

- MathJax Version: v2.7
- Output : CommonHTML
- Client : Chrome 56 but more than likely reproducible on any client.

![fast-preview-alignment-error](https://cloud.githubusercontent.com/assets/1636565/23658502/c287010c-033a-11e7-8713-a15960f385e9.png)

**Comment by pkra** [comment]
Thanks for the report. That's not yet implemented in the FastPreview, I suppose.

Via CSS you could add

```css
.MJXp-display {
  text-align: left!important;
}
``` 
to workaround it on the fly (or set this in the configuration, see http://docs.mathjax.org/en/latest/reference/CSS-styles.html).

I would probably add this for `MathJax_Preview` and `math[display="block"]` as well to avoid other jitter (especially for `math` since it's outside of MathJax's control).  Live example at https://codepen.io/pkra/pen/QpGNaw.

**Comment by WebStew** [comment]
Thanks very much for the advice @pkra. I was going to override it with CSS but wasn't sure if it would have a knock on effect so disabled it for the time being instead.

**Comment by pkra** [comment]
> I was going to override it with CSS but wasn't sure if it would have a knock on effect so disabled it for the time being instead.

You're right to be cautious, I'm afraid. But in this case, it's the top-level class and it's in the ([relatively simple](https://github.com/mathjax/MathJax/blob/master/unpacked/jax/output/PreviewHTML/jax.js)) Fast Preview output, so this should be fine. 

(@dpvc please correct me if I missed something subtle.)

**Comment by pkra** [comment]
For the record, this would be a great https://github.com/yourfirstpr kind of thing.

**Comment by WebStew** [comment]
>  it's in the (relatively simple) Fast Preview output,

You convinced me - I'll take a look!

**Comment by pkra** [comment]
Don't worry about it. Most things will be changing for v3 so it might not be the best time after all.

**Comment by dpvc** [comment]
MathJax v3 no longer has fast-preview.
