### ISSUE TITLE
MathJax don't support more than once "_"

### ISSUE THREAD

**Issue by funqc** [mathjax/MathJax#1715]
e.g. $$p(w_{t+j}|w_t)$$
It can not display.

**Comment by pkra** [comment]
You are likely using MathJax within a markdown document and the markdown processor converts this content into italics long before MathJax gets to it. See http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents for more information on this and similar issues.

Check with your markdown converter whether it's able to handle TeX-like markup; if not, you'll need to work around it some other way (e.g., insert spaces, use backslashes to escape).

**Comment by funqc** [comment]
@pkra using backslashes before '_' to escape can solve the problem.
Thanks
