### ISSUE TITLE
MathJax couldn't get the correct root path when it's loaded via jQuery $.getScript() method

### ISSUE THREAD

**Issue by Raolibec** [mathjax/MathJax#1717]
So is there anyway to slove this problem?
mathjax could be loaded but the other js files which from mathjax could't get the correct file path.
my code like this:
`var a= '/js/mathjax.js';`
`$.getScript(a,function(){console.log('123')})`

**Comment by pkra** [comment]
There is. When loading MathJax this way, you'll need to configure its root folder, e.g.,  `window.MathJax = {root:"http://myhost.net/mathjax"};`. 

Unfortunately, this is not mentioned in the docs ( [yet](https://github.com/mathjax/MathJax-docs/issues/182)).
