### ISSUE TITLE
Math Processing Error on slow network 

### ISSUE THREAD

**Issue by ryuutatsuo88** [mathjax/MathJax#1721]
We are getting issues from users on slow networks reporting Math Processing Errors. we are on version 2.6

After investigating I was able to reproduce the issue when throttling chrome down to (GPRS 500ms, 50kb/s, 20kb/s)

Seems to fail in the jax.js file inside the jax/input usually throws error of Cannot read property 'mspace' of undefined

**Comment by pkra** [comment]
It's hard to say without a live sample but this usually indicates that some components took longer than 15s to load which is the default value for MathJax. You either need to optimize your configuration (depending on the situation either load larger or smaller combined-configuration files). You can of course change the timeout itself in the configuration, e.g., `MathJax.Ajax.timeout = 20 * 1000;`, see also https://groups.google.com/d/msg/mathjax-users/i5OHKI9NYCQ/zH86TTAkYo0J.
