### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by Sigillatus** [mathjax/MathJax#1724]
I'm constantly running into this scripting error.

![script error](https://cloud.githubusercontent.com/assets/14228355/24436431/e56e8168-1497-11e7-8016-5720858517e8.png)

If I leave the browser alone it will eventually render the desired equation, but only after the browser abandons the attempt to load the file accessibility-menu.js

![](https://forums.getpaint.net/uploads/monthly_2017_03/MrkupScriptError.png.dd999c2d3664ee2303722c905e75a06a.png)

**Comment by pkra** [comment]
It's hard to say much from screenshot. A live sample and detailed information on browser and OS version would be necessary to say more.

**Comment by Sigillatus** [comment]
Its a standard webBrowser control from Visual Studio 2015. I've rolled it into a paint.net plugin (available here: https://forums.getpaint.net/index.php?/topic/31446-dr-scotts-markup-renderer/). 

I'm accessing the CDN as per the instructions on the website (or so I believe).

I've got around the script error temporarily by suppressing the error message, however it still takes an age to load looking for the problem file.

I've not touched the code in over a year. It *used* to work without showing this error.

**Comment by pkra** [comment]
> Its a standard webBrowser control from Visual Studio 2015. I've rolled it into a paint.net plugin (available here: https://forums.getpaint.net/index.php?/topic/31446-dr-scotts-markup-renderer/).

Can you share some HTML source that approximates what is opened in the webBrowser control?


> I've not touched the code in over a year. It used to work without showing this error.

The error indicates a problem loading the accessibility menu, a component that was added in the v2.7.0 release. So you are likely using the `latest` copy from the CDN which gets updated with each release and you're probably using a combined configuration file. 

You could downgrade to `2.6-latest` temporarily or replace the combined configuration with a manual configuration block (and exclude the accessibility menu extension).

Debugging embedded browsers is difficult, especially if you're not the developer. If you can create an example that fails in a normal browser that would allow us to debug this. 

If that fails then it's likely specific to .NET, so you might want to post to a more general forum like stackoverflow about such problems with webBrowser controls. I could imagine that additional security features get in the way.

**Comment by Sigillatus** [comment]
> Can you share some HTML source that approximates what is opened in the webBrowser control?

Sure.
`<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8'>
<title>Title</title>
<script type='text/javascript' src='http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script>
</head>
<body>
<math display='block'><mrow mathcolor='#8914FF'><mi>x</mi><mo>=</mo><mfrac><mrow><mo>−</mo><mi>b</mi><mo>±</mo><msqrt><mrow><msup><mi>b</mi><mn>2</mn></msup><mo>−</mo><mn>4</mn><mi>a</mi><mi>c</mi></mrow></msqrt></mrow><mrow><mn>2</mn><mi>a</mi></mrow></mfrac></mrow></math>
</body>
</html>`

I'll downgrade to 2.6 as you suggest.....O.K. that works as expected  - without the script error. Rendering speed is significantly improved too.

I'll investigate a manual configuration block. Thank you for your help.

**Comment by pkra** [comment]
Thanks for posting the snippet. It looks fine in general (I'm guessing https isn't required or else nothing would render). I'd suggest to ask on a more general forum like stackoverflow. Maybe something akin to clearing the browser cache is all it takes (if there are corrupted components in the cache), but it's always hard to tell with embedded browsers. Sorry for not having a better suggestion.

**Comment by Sigillatus** [comment]
Http vs. Https doesn't seem to make a difference to the rendering here. 

Your suggestion to use 2.6 in place of 'latest' has worked very well. 

Thanks again Peter.
