### ISSUE TITLE
[IMPORTANT] cdn.mathjax.org end-of-life April 30, 2017 | Basic redirect in place | Alternatives available

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1725]
We would like to alert you to the fact that the MathJax CDN hosted at cdn.mathjax.org will be shutting down on April 30, 2017.

Please check the full announcement on our website at https://www.mathjax.org/cdn-shutting-down/ for alternatives, including other free CDN services.

**Comment by pkra** [comment]
Quick guide from our announcement:

> The easiest way for most site owners will be to simply switch to another CDN provider. We recommend [cdnjs](https://cdnjs.com) which uses CloudFlare for delivery and thus provides the same level of quality as our own CDN.

> [Our documentation page on installing MathJax](http://docs.mathjax.org/en/latest/installation.html) explains how to install MathJax locally.

**Comment by yihui** [comment]
That is really sad news. What will happen after the CDN is shut down? 404?

I imagine there must be millions of web pages using the original CDN, and we are only given one month to fix them. That seems to be fairly short notice... Is it possible to do a 301 or 302 redirect before you completely shut it down? For example, from `https://cdn.mathjax.org/mathjax/*` to `https://cdnjs.cloudflare.com/ajax/libs/mathjax/*`? Thanks!

**Comment by pkra** [comment]
Thanks for the comment. We are looking into stopgap measures.

**Comment by pkra** [comment]
REMINDER&UPDATE: cdn.mathjax.org is closing down April 30, 2017. 

News: we'll add a stopgap on May 1! 

Check https://www.mathjax.org/cdn-shutting-down/ for other minor updates and clarifications.

**Comment by brendanrmurphy** [comment]
We noticed you have a few hardcoded references to cdn.mathjax.org in the v2.7.0 script. Can you confirm how these are used and if they'll be an issue after 4/30/17?

**Comment by pkra** [comment]
> We noticed you have a few hardcoded references to cdn.mathjax.org in the v2.7.0 script. Can you confirm how these are used and if they'll be an issue after 4/30/17?

There are basically two references right now. 

* in a redirect from `cdn.mathjax.org/mathjax/latest` to `cdn.mathjax.org/mathjax/n.M-latest`
  * this does not have an effect except when MathJax is loaded from `cdn.mathjax.org`.
* The definition of the `[Contrib]` path to `cdn.mathjax.org/mathjax/contrib`
  * this is used in the `mhchem` extension (to load mhchem v3) as well as the combined configuration files to load the `accessibility-menu` extension.

The `contrib` path can be overwritten in the configuration to point to another location so you can host any third party extension you use yourself and change contrib, cf. http://docs.mathjax.org/en/latest/options/ThirdParty.html#custom-extension-path-configuration

However, we will make a **2.7.1 bug fix release before April 30** to remove those references and provide a self-sufficient copy (which will include mhchem v3 and the accessibility extensions). 

We also plan to keep `cdn.mathjax.org/mathjax/contrib` alive for a while longer (alongside the redirect).

**Comment by pkra** [comment]
Note that 2.7.1 is out https://github.com/mathjax/MathJax/releases/tag/2.7.1

**Comment by pkra** [comment]
I think we can close this now.
