### ISSUE TITLE
MathJax.Ajax.config.path.Contrib refers to cdn.mathjax.org

### ISSUE THREAD

**Issue by christianp** [mathjax/MathJax#1727]
[`MathJax.Ajax.config.path.Contrib`](https://github.com/mathjax/MathJax/blob/master/unpacked/MathJax.js#L669) refers to cdn.mathjax.org. What's the plan for this? Should it point to cdnjs?

**Comment by pkra** [comment]
As mentioned in the announcement, we are still working on a solution for the third party extensions repository.

**Comment by WebStew** [comment]
Hi @pkra.

We're in the process of moving to the new CDN but have noticed that accessibility-menu.js is resolving from cdn.mathjax.org. Presume this is related to this issue?

**Comment by pkra** [comment]
> Presume this is related to this issue?

Yes, that's the main problem. 

We haven't decided yet how third party extensions will be hosted on cdnjs (the whole repo or individual extensions), so we don't have any final recommendations yet. 

One way would be to host a [copy of the a11y extensions](https://github.com/mathjax/MathJax-a11y/releases/download/v1.1.0/mathjax-a11y-v1.1.0.zip) yourself and redefine `[Contrib]` in your configuration to point to that location, cf. http://docs.mathjax.org/en/latest/options/ThirdParty.html#custom-extension-path-configuration.

But we should have something smoother than that in the end.

**Comment by dsjen** [comment]
Is there any update on this?  We've noticed that `accessibility-menu.js` is being loaded from `cdn.mathjax.org` too after moving to `cdnjs.cloudflare.com`.

Hosting a copy of the a11y extension seems like a reasonable solution.  However, it would preferable to install it via a package manager, e.g. npm, rather than downloading a copy.  However, because the [files field](https://github.com/mathjax/MathJax-a11y/blob/master/package.json#L35) in the package.json file is set to just "LICENSE" and "README.md" none of the source is downloaded.

**Comment by pkra** [comment]
> Is there any update on this? We've noticed that accessibility-menu.js is being loaded from cdn.mathjax.org too after moving to cdnjs.cloudflare.com.

See my comment on https://github.com/mathjax/MathJax/issues/1725#issuecomment-294001245.

> . However, it would preferable to install it via a package manager,

Thanks for pointing that out. I've filed https://github.com/mathjax/MathJax-a11y/issues/186.

**Comment by dsjen** [comment]
Great, thank you!

**Comment by pkra** [comment]
As per F2F, we will leave this default value for `[Contrib]` in place in the upcoming v2.7.1.

However, both mhchem v3 and the accessibility extensions will be pulled into the core. The `cdn.mathjax.org/mathjax/contrib` folder will stay online alongside the redirect mentioned in https://www.mathjax.org/cdn-shutting-down/.
