### ISSUE TITLE
Adding many elements dynamically before the first jax is displayed fails

### ISSUE THREAD

**Issue by ippeiukai** [mathjax/MathJax#1729]
### Issue Summary

I'm trying to add multiple elements programmatically and cannot MathJax to display them properly.
My page do not have any elements initially, and the log suggests adding many 'Typeset' in the queue fails while the first element triggers some additional startup process.

### Technical details:

* MathJax Version: 2.7.0

### Steps to Reproduce

Following is a simplified version of my app that reproduces the problem:

```HTML
<html>
<head>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/x-mathjax-config">
    (function() {
      "use strict";

      var debugMessage = function (type) {
        return function (message) {
          var args = [];
          if (Array.isArray(message)) {
            args = message.slice(1);
            message = message[0];
          }
          var logMsg = "MathJax " + type + ": ";
          logMsg += message;
          for(var arg of args) {
            logMsg += ', %o';
          }
          args.unshift(logMsg);
          console.debug.apply(console, args);
        };
      };
      MathJax.Hub.Startup.signal.Interest(debugMessage('Startup'));
      MathJax.Hub.signal.Interest(debugMessage('Hub'));

      MathJax.Hub.Config({
        
        elements: [],
        showProcessingMessages: false,
        messageStyle: 'none',
        jax: [
          "input/TeX",
          "output/CommonHTML"
        ],
        extensions: [
          "tex2jax.js",
          "Safe.js"
        ],
        TeX: {
          extensions: ["AMSmath.js", "AMSsymbols.js", "noErrors.js", "noUndefined.js"]
        },
        CommonHTML: {
          linebreaks: {
            automatic: true,
            width: "container",
          }
        },
        tex2jax: {
          inlineMath: [ ['$','$'] ],
          displayMath: [ ['$$','$$'] ],
          preview: 'none',
        },
      });
      MathJax.Hub.processSectionDelay = 0;
      MathJax.Hub.processUpdateTime = 0;
      MathJax.Hub.processUpdateDelay = 0;
    })();
  </script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"></script>
  <script>
    <!--
      (function(global) {
        'use strict';
        global.addMathEq10 = function()  {
          for (var i = 0; i < 10; i ++)  {
            global.addMathEq();
          }
        }
        global.addMathEq = function() {
          var element = global.document.createElement('div');
          element.innerHTML = '$y=x^2$';
          global.document.body.appendChild(element);
          MathJax.Hub.Queue(function () {
            MathJax.Hub.Typeset(element);
          });
        };
      })(window);
    //-->  
  </script>  
</head>
<body>
  <button onclick="addMathEq10()">try me</button>
</body>
</html>
```
(https://codepen.io/ippeiukai/pen/GWVwJE)

**Comment by pkra** [comment]
It would help if you described in more detail how to reproduce the problem.

I suspect all that is necessary is to queue the typesetting commands properly, i.e., use `MathJax.Hub.Queue(["Typeset",MathJax.Hub,element]);` in `addMathEq`.

**Comment by ippeiukai** [comment]
> I suspect all that is necessary is to queue the typesetting commands properly, i.e., use MathJax.Hub.Queue(["Typeset",MathJax.Hub,element]); in addMathEq.

@pkra 
`MathJax.Hub.Queue(["Typeset",MathJax.Hub,element]);` seems to work indeed. Thanks for the tip.

What is the correct usage of `MathJax.Hub.Queue()`? According to http://docs.mathjax.org/en/latest/api/hub.html, `MathJax.Hub.Queue()` takes a callback specification as argument. According to http://docs.mathjax.org/en/latest/api/callback.html, `fn` is as much a callback specification as `["method", object, data...]`.

**Comment by ippeiukai** [comment]
I think I have figured it out. `MathJax.Hub.Typeset()` is an async method that returns something akin to a Promise. So we need to return what it returns in the function in order for the Queue to synchronise. I suspect the Queue does more than waiting for an async process to finish, but it can have it wait for other processes somehow.

Anyways, here is the end result, just in case anyone is wondering:

```JS
        global.addMathEq = function() {
          var element = global.document.createElement('div');
          element.innerHTML = 'Loading...';
          global.document.body.appendChild(element);
          MathJax.Hub.Queue(() => {
            element.innerHTML = '$y=x^2$';
            return MathJax.Hub.Typeset(element);
          });
        };
```
