### ISSUE TITLE
Disable Fast-Preview

### ISSUE THREAD

**Issue by MFJones21** [mathjax/MathJax#1730]
I am using MathJax for displaying rapidly changing Input. From another Forum I got the hint that the described "twitching" is due to the Fast-Preview feature. I am new to MathJax and a bit confused by all   the configuration options. Below you see the script I use : 

<html><header><script type="text/x-mathjax-config">MathJax.Hub.Config({extensions: ['fast-preview.js'],"fast-preview": {Chunks: {EqnChunk: 10000, EqnChunkFactor: 1, EqnChunkDelay: 0},color: "inherit!important",updateTime: 0, updateDelay: 0,messageStyle: "none",disabled: true},jax: ["input/TeX","output/HTML-CSS"],messageStyle: 'none',tex2jax: {inlineMath: [['$','$'], ['\(','\)']]},"HTML-CSS": {linebreaks: {automatic: true}}});</script><script src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'></script></header><body>$x^3+2x$</body></html>

Thanks a lot for your help in advance =)

**Comment by pkra** [comment]
Please check out [the documentation](http://docs.mathjax.org/en/latest/options/fast-preview.html) I pointed out on StackOverflow.

**Comment by MFJones21** [comment]
Thanks a lot for your answer! But I looked at that before and as I understood it putting "disabled: true" should put everything out. I am talking about this light gray plain text that is displayed before the rendering.

**Comment by pkra** [comment]
>  But I looked at that before and as I understood it putting "disabled: true" should put everything out

Ah, sorry. Your OP only talks about the fast-preview.

> I am talking about this light gray plain text that is displayed before the rendering.

Hard to say but I'm guessing you are referring to the original input in the page.

Again, please read the documentation, e.g., http://docs.mathjax.org/en/latest/options/tex2jax.html (the `preview` option) and http://docs.mathjax.org/en/latest/advanced/typeset.html.

General questions are better asked on the User Group, https://groups.google.com/forum/#!forum/mathjax-users, not on this issue tracker.

**Comment by MFJones21** [comment]
No Problem at all mate ! Thanks a lot for your help ! The links solved it :1st_place_medal:
