### ISSUE TITLE
uneven rendering of mathematical expression 

### ISSUE THREAD

**Issue by Yuteen** [mathjax/MathJax#1731]
My application runs on Backbone JS and CakePHP framework. On certain pages mathematical expressions do not get rendered properly whereas on others rendering is proper.
![screenshot1](https://cloud.githubusercontent.com/assets/22909265/24952909/f9859d44-1f96-11e7-9163-01ccb82172b4.png)
![screenshot2](https://cloud.githubusercontent.com/assets/22909265/24952915/fdd844e6-1f96-11e7-925b-e00f8ae54711.png)

**Comment by pkra** [comment]
I'm afraid there's not much one can tell from a screenshot. 

The problem does not seem related to MathJax but the overall application since the markup that is displayed as text content has nothing to do with MathJax.
