### ISSUE TITLE
MathJax fails silently when run locally with RequireJS

### ISSUE THREAD

**Issue by MareoRaft** [mathjax/MathJax#1732]
I am using requireJS.  Mathjax works via a CDN when I configure 

    require.config({
    	mathjax: [
    		"https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML&amp;delayStartupUntil=configured"
    	],
    })

.  However, I would like to run MathJax locally, since this allows me to develop even when I'm not connected to the internet.  Mysteriously, MathJax fails in this case, but gives no error messages:

    require.config({
    	mathjax: [
    		"mylib/MathJax.js?config=TeX-AMS_HTML&amp;delayStartupUntil=configured"
    	],
    })

where I have placed `MathJax.js` in `mylib` folder, and I have also created the paths/files `extensions/MathMenu.js` and `extensions/MathZoom.js` since MathJax seems to want those.

I'm guessing that the issue has to do with MathJax not playing nice with RequireJS.  Also, it's weird that I create manual paths for MathMenu and MathZoom instead of going through the Require system.

**Comment by MareoRaft** [comment]
I am serving all files with the Tornado web server (in Python) on a Darwin or FreeBSD operating system, to give a little background.

**Comment by dpvc** [comment]
MathJax calls on many more files than just `MathJax.js`, `extensions/MathMenu.js`, and `extensions/MathZoom.js`, so you would need to install those as well.  For example, you have called on the `config/TeX-AMS_HTML` file for one thing.  But you will also need a number of file in the `jax/output/HTML-CSS` directory as well as ones from the `fonts` and may well need others as well.

> it's weird that I create manual paths for MathMenu and MathZoom instead of going through the Require system.

MathJax has its own resource-loading system (it was written before RequireJS existed), and it doesn't interact with RequireJS's system.

**Comment by MareoRaft** [comment]
So would it be much trouble to run this locally?  Also, it does not seem like expected behavior that MathJax should fail silently.  Typically when something fails, there should be an error message describing the issue.

**Comment by MareoRaft** [comment]
As a note, this issue is NOT specific to Safari.

**Comment by pkra** [comment]
> So would it be much trouble to run this locally? 

No, read the documentation at http://docs.mathjax.org/en/latest/installation.html.

> Also, it does not seem like expected behavior that MathJax should fail silently. 
> Typically when something fails, there should be an error message describing the issue.

This is expected since you specifically asked it to wait via `delayStartupUntil=configured`; read the docs at http://docs.mathjax.org/en/latest/options/hub.htm
