### ISSUE TITLE
New CDN not working with Angular2

### ISSUE THREAD

**Issue by family-guy** [mathjax/MathJax#1733]
Not sure if I'm doing something wrong / the only one with this issue. I am using Angular2 and everything works fine with the soon to be retired CDN https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_HTMLorMML. But when I try changing to https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_HTMLorMML I get the error below:

Uncaught SyntaxError: Unexpected token ;
    at eval (<anonymous>)
    at EVAL (MathJax.js:19)
    at Function.execute (MathJax.js:19)
    at cb (MathJax.js:19)
    at Object.Process (MathJax.js:19)
    at Object.call (MathJax.js:19)
    at Function.WAITEXECUTE (MathJax.js:19)
    at cb (MathJax.js:19)
    at Object.Execute (MathJax.js:19)
    at Object.loadComplete (MathJax.js:19)
vendor.bundle.js:54525 

The new CDN does work though when developing locally using 'ng serve'.

**Comment by dpvc** [comment]
It looks like there might be an error in your configuration.  Are you using a script with `type=text/x-mathjax-config`?  If so, check there to make sure there are no syntax errors (like a `;` when you mean a `,`).

Otherwise, there is not enough information here to give you any real help.  A live page that we could look at would be a big help.

**Comment by family-guy** [comment]
Ok many thanks. I will take a look at my configuration (pasted below)

  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      showProcessingMessages: false,
      tex2jax: { inlineMath: [['$','$'],['\\(','\\)']] }
    });
  </script>

**Comment by dpvc** [comment]
That looks OK, so not sure what the issue is.  I don't know how MathJax is integrated into Angular2.  Is there a plugin of any sort?  If so, you might need to check if that needs adjusting to work with cdnjs (e.g., perhaps it references can.mathjax.org in some way).

**Comment by family-guy** [comment]
Everything seems ok now. Not sure what I am doing different TBH. In any case, this is the page I was testing on http://www.staging.babilib.co.uk/spa/mathdruck/. Many thanks for your help

**Comment by vanabel** [comment]
maybe you have the wrong order of loading mathjax: first load the configuation and then the mathjax script.
