### ISSUE TITLE
Glyphs for ⋒ and ⋓ are swapped in math font

### ISSUE THREAD

**Issue by gareth-rees** [mathjax/MathJax#1734]
These characters are:

* ⋒ U+22D2 DOUBLE INTERSECTION
* ⋓ U+22D3 DOUBLE UNION

But enter them in math mode (`$⋒$` and `$⋓$`) and the glyphs are swapped.

Confirmed via [the dynamic preview](https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html):

<img width="470" alt="double-union" src="https://cloud.githubusercontent.com/assets/922721/25027866/b9d30f58-20a7-11e7-9319-5e84cded5616.png">

**Comment by pkra** [comment]
I cannot replicate this with any font or output we support. Can you tell us from the dev tools which fonts are actually used for the character? Browser and OS versions might help as well.

**Comment by gareth-rees** [comment]
Operating system: macOS Sierra 10.12.4. Browser: Safari 10.1 (12603.1.30.0.34) — but I can reproduce the problem in Firefox 50.0.2 and Chrome 58.0.3029.68

Web Inspector shows the following HTML for the bad glyphs:
```
<span class="mo" id="MathJax-Span-3" style="font-family: STIXGeneral-Regular;">⋒</span>
```

**Comment by pkra** [comment]
> Web Inspector shows the following HTML for the bad glyphs:

Can you check what the actual font being used is (under computed styles)? From a quick check STIXGeneral-Regular 1.1 has the correct glyphs.

**Comment by gareth-rees** [comment]
I have STIXGeneral-Regular 1.0. Let me see if updating to 1.1 fixes it.

**Comment by gareth-rees** [comment]
Ok, updating to 1.1 fixes the glyphs. So there is nothing for you to do and I'll close the issue.

**Comment by pkra** [comment]
Thanks for following up on this. Glad you could fix it.
