### ISSUE TITLE
one-character macros inside \text{}

### ISSUE THREAD

**Issue by Alex-Jordan** [mathjax/MathJax#1736]
I discovered the following with the percent sign in an MBX project. I investigated a little and the issue extends to other characters.

With:
```
$\text{\&}$
$\text{\%}$
$\text{\#}$
$\text{\_}$
$\text{\{}$
$\text{\}}$
$\text{\$}$
```

the first four render with the backslash present (as in they appear like `\%` instead of just `%`). The last three do not, which is the right behavior. I checked that a LaTeX document will render all of these without the backslash. I did my MathJax testing at math.se.

**Comment by pkra** [comment]
This is expected behavior as MathJax does not support text mode macros (except $ to switch back to math mode). See http://docs.mathjax.org/en/latest/tex.html?highlight=text-mode

**Comment by Alex-Jordan** [comment]
Ah, thanks.
