### ISSUE TITLE
\tilde has moved

### ISSUE THREAD

**Issue by bradleyashton** [mathjax/MathJax#1739]
A recent change - `\tilde{x}` doesn't format correctly in e.g. jupyter, the tilde sits above and to the right of the character in question. This seems to be affecting other packages too, e.g documents rendered by "read the docs". 

Oh, I see this could be a duplicate of #1737 (it is a Safari issue for me also)

**Comment by pkra** [comment]
> Oh, I see this could be a duplicate of #1737 (it is a Safari issue for me also)

Correct.
