### ISSUE TITLE
CDN page loading Error in IE

### ISSUE THREAD

**Issue by MchlFil** [mathjax/MathJax#1741]
### Issue summary
MathJax CDN is shutting down. The old `cdn.mathjax.org/mathjax/latest/MathJax.js` file contains now a script that is replacing the script tag to load files from cloudflare. In Internet Explorer (or in browsers that do not support `document.currentScript`) the script that is looking for the current script tag is not supporting src attributes with relative URLs in them.

### Steps to Reproduce
1. Just add a script tag in the header with relative URL. `<script type="text/javascript" src="lib/require.js"></script>`
2. Then load MathJax from the MathJax CDN. `<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js"></script>`
3. In the console: `Unable to get property 'substr' of undefined or null reference` MathJax.js (21,7)

### Technical details:
* Internet Explorer 11

### Note
I know the new CDN URL should be used, however some of the deployed (legacy and hard to update) scripts are currently breaking on page load.

**Comment by pkra** [comment]
Filed at  https://github.com/mathjax/cdn-redirect/issues/3

**Comment by pkra** [comment]
A fix is going out to the CDN now.

**Comment by pkra** [comment]
Closing this here as it has been fixed downstream.

Thanks for filing the bug report!

Let us know if you see any other issues.

**Comment by MchlFil** [comment]
This was fast! :)

I'll reroute those scripts to another CDN now... Everything is fine otherwise.

Thanks!
