### ISSUE TITLE
converting a latex code to svg code in javascript

### ISSUE THREAD

**Issue by karthibose** [mathjax/MathJax#1742]
Pass the latex string to java script function, java script link to mathJax, compile them, return back to svg image. Please any one know this, please help me.

**Comment by pkra** [comment]
It's not clear what you are asking. You should post to a discussion forum such as stackoverflow for general web development question and the MathJax User Group for mathjax-specific questions -- make sure to thoroughly read the user guidelines https://groups.google.com/d/msg/mathjax-users/Dhk3bQgThaM/NPtq7VLv-5EJ.
