### ISSUE TITLE
dynamic viewer webpages broken

### ISSUE THREAD

**Issue by jason-s** [mathjax/MathJax#1743]
These don't work on my Chromebook; I get these errors on the console:

    WARNING: cdn.mathjax.org has been retired.
    Uncaught ReferenceError: MathJax is not defined at sample-dynamic-2.html:102

on these pages:

- https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html
- https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html

I know cdn.mathjax.org has been retired... but fix it on your own pages please!

**Comment by pkra** [comment]
That's expected behavior and these files will be removed soon. I'd suggest to use https://cdn.rawgit.com/mathjax/MathJax/2.7.1/test/sample-dynamic-2.html etc.

**Comment by jason-s** [comment]
Ah -- thanks. Yeah, the problem is that when you search for "mathjax online" in Google, the first two results are https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic.html and https://cdn.mathjax.org/mathjax/latest/test/sample-dynamic-2.html, but neither of them work.

Please consider adding a notice to those pages or a 301 Redirect, as it reflects badly on the MathJax project.

**Comment by jason-s** [comment]
...and it may be Expected Behavior to you, but it's not expected to end-users when there's no visible indication of why these two pages don't work.

**Comment by dpvc** [comment]
The pages have been rerouted to a working copy.
