### ISSUE TITLE
Angular2 error

### ISSUE THREAD

**Issue by mist3r3** [mathjax/MathJax#1744]
Hello I've been using Mathjax with angular2 for a few months, but lately I have some errors while trying to run my server (ng serve).
This is the error:
Cannot invoke an expression whose type lacks a call signature. Type '{ Hub: { Queue: (param: Object[]) => void; }; }' has no compatible call signatures.`

And this is my directive:

> import {Directive, ElementRef, OnChanges, Input} from "@angular/core";
> 
> declare var MathJax: {
>   Hub: {
>     Queue: (param: Object[]) => void;
>   }
> }
> 
> 
> @Directive({selector: '[mathJax]'})
> export class MathJaxDirective implements OnChanges {
>   @Input("mathJax") private value: string = "";
> 
>   constructor(private element: ElementRef) {}
>   ngOnChanges() {
> 
>     this.element.nativeElement.innerHTML = this.value;
>     //console.log("MathJax is:");
>     //console.log(MathJax.Hub);
>     MathJax(["Typeset", MathJax.Hub, this.element.nativeElement]);
> 
>   }
> }

If someone knows about how to fix that I'll be glad. Thank you.

**Comment by pkra** [comment]
Please post a link to a minimal, live example (on jsbin, codepen etc).

**Comment by dpvc** [comment]
I think

```
MathJax(["Typeset", MathJax.Hub, this.element.nativeElement]);
```

should be

```
MathJax.Hub.Queue(["Typeset", MathJax.Hub, this.element.nativeElement]);
```

**Comment by mist3r3** [comment]
This is right but when I do what you say I don't have a compilation error but something like this
`ReferenceError: Can't find variable: MathJax
ngOnChanges — mathjax.directive.ts:20
checkAndUpdateDirectiveInline — core.es5.js:10724
checkAndUpdateNodeInline — core.es5.js:12117
debugCheckAndUpdateNode — core.es5.js:12715
debugCheckDirectivesFn — core.es5.js:12656
(anonymous function)
checkAndUpdateView — core.es5.js:12053
callViewAction — core.es5.js:12367
...
`

**Comment by RuVT** [comment]
I think you need to do one of the next two things.
Download the type definitions of mathjax for TypeScript: https://www.npmjs.com/package/@types/mathjax

OR

Create a variable called MathJax so the compiler can continue.

**Comment by pkra** [comment]
Closed as abandoned.
