### ISSUE TITLE
Using < in the limits of a sum leads to rendering issues

### ISSUE THREAD

**Issue by kanedo** [mathjax/MathJax#1745]
I encountered the following bug:
Using `<` in the sum-operator doesn’t work and will not be rendered.
To reproduce:
```
\\[
\sum_{i’<i} \alpha_{i’j}
\\]
```
will not produce a correct formula where as:
```
\\[
\sum_{i’ = 0}^{i-1} \alpha_{i’j}
\\]
```
works.

![screen shot 2017-05-11 at 08 35 07](https://cloud.githubusercontent.com/assets/660158/25935740/c9875692-3624-11e7-8caa-3fcd0602dd54.png)

Tested with Marked 2 (2.5.10) and using the MathJax configuration: `TeX-AMS-MML_HTMLorMML-full`

**Comment by pkra** [comment]
Please read the documentation http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents.
