### ISSUE TITLE
MathJax with ReactJS

### ISSUE THREAD

**Issue by shenkev** [mathjax/MathJax#1747]
I haven't found too much information on Google with regards to MathJax + ReactJS. Is ReactJS not recommended for MathJax? Is there a working example?

Best,
K

**Comment by shenkev** [comment]
My current solution:

class Preview extends React.Component {

```
componentDidMount () {
    MathJax.Hub.Queue(["Typeset",MathJax.Hub, ReactDOM.findDOMNode(this)]);
  }

  componentDidUpdate () {
    MathJax.Hub.Queue(["Typeset",MathJax.Hub, ReactDOM.findDOMNode(this)]);
  }

  render () {
    var tex= this.props.name,

    if(!!tex) {
      texDisplay = "$$" + tex + "$$"
    }
    return (
      <div>The Tex!</div>
      <div>{texDisplay}</div>
    )
  }
}
```

**Comment by NPersonal** [comment]
Is your code work fine? 
I couldn't work in ReactJS, and i don't know why, can you help me see
[my issue](https://github.com/mathjax/MathJax/issues/1934). Or share your code to me, i will thank you very much.
