### ISSUE TITLE
How do I close the progress bar in the lower left corner?

### ISSUE THREAD

**Issue by yangchun9525** [mathjax/MathJax#1748]
How do I close the progress bar in the lower left corner?like progress math:100%

**Comment by pkra** [comment]
I'm not sure what you mean with "close" here. The bar should disappear when all components have loaded; if that's not the case, please share a live sample.

If you want to disable the progress bar, then check the documentation at http://docs.mathjax.org/en/latest/options/hub.html, in particular disable `showProcessingMessages` and `messageStyle` in your configuration.

**Comment by yangchun9525** [comment]
I've found a solution，that is showProcessingMessages: false,
     messageStyle: "none",and thanks your answer

**Comment by pkra** [comment]
Good to hear you could sort it out and thanks for following up.
