### ISSUE TITLE
Mathjax appears to the right

### ISSUE THREAD

**Issue by Mitiko** [mathjax/MathJax#1749]
![2017-05-15](https://cloud.githubusercontent.com/assets/26521741/26056632/d6ef386a-397e-11e7-96ad-3e19d6f42a3b.png)
This is the math, but it appears to be a lot to the right...Like something is pushing it...
I added this: <br />
`MathJax.Hub.Config({
        tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        skipTags: ["script","noscript","style","textarea"]},
        displayAlign: "left"});`, but it didn't work so I added this too:<br />
`.math {
            margin-left: -50px;
        }` but with no success
![2017-05-15 1](https://cloud.githubusercontent.com/assets/26521741/26056631/d6d62762-397e-11e7-9474-843aaf5e095f.png)

**Comment by pkra** [comment]
Please share a link to a live, minimal example that exhibits the problem.

**Comment by pkra** [comment]
Closed as abandoned.
