### ISSUE TITLE
\text{''} renders backwards

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#1751]
Opening quotes render backwards inside a text string.  Closing quotes look okay though.
Example: https://jsfiddle.net/t6r9oht3/

**Comment by pkra** [comment]
MathJax does not provide text-mode features and no macros are handled inside `\text` (with the exception of `$` to enter math mode).  You simply see the Ynicode characters from your input.

**Comment by orangeplanet** [comment]
Ok, thanks, but isn't there some sort of transformation happening here?  I typed two left ticks (for the opening mark) and two straight single quotes (for the closing mark), and in my browser (Firefox 45 ESR, Windows) the output looks like the unicode character U+201D (right double quote) for both. 

Still, there are some ways (which avoid using \text) for a user to get the desired output: use html double quote codes, use the \unicode command and matching code points, or go in and out of math lock and use keyboard quotes.  Examples: https://jsfiddle.net/t6r9oht3/1/

**Comment by pkra** [comment]
>  the output looks like the unicode character U+201D (right double quote) for both.

It's two `U+0027`'s using the `MathJax_Main` font.

> Still, there are some ways (which avoid using \text) for a user to get the desired output

That's correct. I was only commenting on the  rendering of `\text{''}`.

**Comment by orangeplanet** [comment]
Ah, I think I get it now.  It's seeing the input as two apostrophes.  They do look slightly spacier than the double quote.  Thanks for the explanation.
