### ISSUE TITLE
"Understanding Mathax Performance" Outdated?

### ISSUE THREAD

**Issue by autopulated** [mathjax/MathJax#1752]
I have a performance problem with a page with many large MathJax blocks in it (extremely slow initial rendering of the blocks).

Before I start digging into whether anything can be improved, is this wiki page on the performance still an accurate representation of the current issues: https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance (it seems to be quite old)

**Comment by pkra** [comment]
Don't start digging here.

We're currently working on v3 which will be a complete overhaul of MathJax internals. The repository is at https://github.com/mathjax/mathjax-v3

But also have a look at https://github.com/mathjax/MathJax-node for server-side rendering.
