### ISSUE TITLE
When will mml3 be fully supported?

### ISSUE THREAD

**Issue by himajasuman** [mathjax/MathJax#1753]
Documentation(http://docs.mathjax.org/en/latest/options/MML3.html?highlight=mml3) states it is experimental support only. https://github.com/mathjax/MathJax-docs/issues/78

It would be great if some information is provided on this.

**Comment by pkra** [comment]
It is in our backlog but not scheduled to be worked on any time soon.

**Comment by pkra** [comment]
For completeness: the slow progress in elementary math support is primarily an issue of resources  (i.e., developer time).
