### ISSUE TITLE
\textit nested in \texttt (or vice versa) not handled

### ISSUE THREAD

**Issue by Eelis** [mathjax/MathJax#1758]
Consider:

![screenshot](http://eel.is/mathjax-texttt.png)

**Comment by pkra** [comment]
That's expected behavior. Only $ is recognized within `\text{}`, cf. http://docs.mathjax.org/en/latest/tex.html?highlight=exception

**Comment by Eelis** [comment]
Hm, does that mean it's considered too hard to fix? Or is that oversimplifying the case?

**Comment by Eelis** [comment]
Because I thought a typical use case for MathJax was to take formulas from LaTeX documents and feed them through MathJax to then publish them on the web. That's how I've been using it, and the document I happen to be most interested in (the C++ ISO standard) uses this textit/texttt nesting inside math formulas. :)

**Comment by Eelis** [comment]
So, closed without any explanation of why this functionality is excluded and why it is allowed to undermine typical use cases? Wow, what a toxic project.

**Comment by pkra** [comment]
It would help to follow our suggestions at

https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#reporting-an-issue 

which is linked to from the top of any new issue at submission. In particular, please note https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#conduct.

> So, closed without any explanation of why this functionality is excluded and why it is allowed to undermine typical use cases?

This is not a typical use case for MathJax, I'm afraid. 

There are many discussion here on the tracker as well as [on the user group](https://groups.google.com/forum/#!searchin/mathjax-users/text$20mode$20macro%7Csort:relevance) around text mode macros. 

But for the benefit for future viewers of this issue: There are two main reasons for text-mode macros are not supported. 

a) TeX's text mode is an entirely different beast from math mode and cannot be implemented easily. 

b) MathJax's internal format is (essentially) MathML which is limited when it comes to text mode content. In particular, it cannot adequately model the output one would expect from something as simple as `\texttt{some \textit{important} text }`.
