### ISSUE TITLE
Well... This is interesting. Samantha ChromeVox voice confused over capital and lowercase letters.

### ISSUE THREAD

**Issue by jeankaplansky** [mathjax/MathJax#1759]
Made a small preview video of Chromevox reading MathJax for a colleague. The Google US voice reads the letters correctly. Here's the recording:

[AllLettersAreCapitalChromeVoxMathJax2.7.1.zip](https://github.com/mathjax/MathJax/files/1043050/AllLettersAreCapitalChromeVoxMathJax2.7.1.zip)

The Samantha voice is confused and reads all letters as capital letters. Does a list of specific Chromevox voices to avoid exist for MathJax?

Please advise?

Thanks!
Jean

**Comment by pkra** [comment]
This sounds like a ChromeVox bug?

**Comment by jeankaplansky** [comment]
I don't know anyone on the ChromeVox project to report this to. Please let me know if you know of a specific ChromeVox issues list I should be aware of. 

Thanks!

**Comment by pkra** [comment]
I missed the other question.

> Does a list of specific Chromevox voices to avoid exist for MathJax?

Not that we're aware of. 

>  Please let me know if you know of a specific ChromeVox issues list I should be aware of.

There's a google group and the chromium bug tracker, see http://www.chromevox.com/feedback.html.

**Comment by jeankaplansky** [comment]
Filed with chromium bug tracker per your link: 

https://bugs.chromium.org/p/chromium/issues/detail?id=728721

**Comment by pkra** [comment]
Thanks!
