### ISSUE TITLE
Square root layout mis-match 

### ISSUE THREAD

**Issue by hr1992** [mathjax/MathJax#1760]
### Issue Summary
I create a simple equation on jsfiddle, but Square root layout mis-match.
![image](https://cloud.githubusercontent.com/assets/4222261/26721013/d7333cf8-47bc-11e7-99ea-510543f7e75f.png)

Here is my example: https://jsfiddle.net/p0e9ja5m/

### Steps to Reproduce

1. Include the mathjax file from cdn.(https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML)
2. Add the equation to page.
3. Square root looks strange on this page.

### Technical details

* MathJax Version: 2.7.0 - latest commit:  6273842
* Client OS: Macintosh
* Browser:  chrome 58.0.3029.110 (64-bit)
* 

Please let me know is there any solution for this situation.
Thx.

**Comment by pkra** [comment]
There is not sufficient information to reproduce the issue.

Please follow the instructions in https://github.com/mathjax/MathJax/blob/master/CONTRIBUTING.md#bug-reports.

**Comment by pkra** [comment]
Thanks for the additional information. 

Unfortunately, I still cannot reproduce this; see
 https://saucelabs.com/beta/tests/a49449d757154712813ad6f1e30d869d/metadata for a test run.

**Comment by pkra** [comment]
Closing as abandoned.
