### ISSUE TITLE
multiple inline formulas in a single line doesn't render right

### ISSUE THREAD

**Issue by JerryYangJin** [mathjax/MathJax#1761]
Hello, I found this [tutorial](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference?newreg=a32d782f32444d4f8cd93b3c30c37ba0) and trying to use `mathjax` for my own project.

I found for the latest version `2.7.1', if there're multiple inline formulas in a single line, it doesn't work sometimes.

below is from the [tutorial](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference?newreg=a32d782f32444d4f8cd93b3c30c37ba0), which renders right in `math.meta.stackexchange.com`

```mathjax
4. For superscripts and subscripts, use ^ and _. For example, `x_i^2`: $x_i^2$, `\log_2 x`: $\log_2 x$.
```

But when I tried the same using `2.7.1` on my own project, it doesn't work. And if I only render one of the the 2 formulas,  or split it into 2 separate lines, it works fine.

This looks like a bug

**Comment by pkra** [comment]
There's not much to say without a live example exhibiting the problem.

If you are using Markdown, then you are running into a typical problem with markdown parsers replacing underscores with `<em>` which breaks math content, see http://docs.mathjax.org/en/latest/tex.html?highlight=markdown#tex-and-latex-in-html-documents.

**Comment by JerryYangJin** [comment]
@pkra , thank you for your update, i was using `showdown` with `mathjax`, which requires a custom extension, i guess the issue is with either showdown or the customer extension
