### ISSUE TITLE
Link to Google Summer of Code 2017 wiki page does not work

### ISSUE THREAD

**Issue by prog1dev** [mathjax/MathJax#1765]
On [main MathJax wiki page](https://github.com/mathjax/MathJax/wiki) these is an info:

> Are you a student? We're applying as an organization at [Google Summer of Code 2017](https://github.com/mathjax/MathJax/wiki/GSoC-2017). Stay tuned for more updates!

But link does not work. It redirects to the main wiki page.

**Comment by pkra** [comment]
Thanks for pointing that out. I've removed this outdated section.
