### ISSUE TITLE
Cannot recover from Math Processing Error

### ISSUE THREAD

**Issue by falsandtru** [mathjax/MathJax#1769]
[In this page](https://falsandtru.github.io/securemark/#%24%24%0A%5Cfrac%7B%5Cpi%7D%7B2%7D%20%3D%0A%5Cleft(%20%5Cint_%7B0%7D%5E%7B%5Cinfty%7D%20%5Cfrac%7B%5Csin%20x%7D%7B%5Csqrt%7Bx%7D%7D%20dx%20%5Cright)%5E2%20%3D%0A%5Csum_%7Bk%3D0%7D%5E%7B%5Cinfty%7D%20%5Cfrac%7B(2k)!%7D%7B2%5E%7B2k%7D(k!)%5E2%7D%20%5Cfrac%7B1%7D%7B2k%2B1%7D%20%3D%0A%5Cprod_%7Bk%3D1%7D%5E%7B%5Cinfty%7D%20%5Cfrac%7B4k%5E2%7D%7B4k%5E2%20-%201%7D%0A%24%24) and the code, when I remove a space as the following diff, the rendering for this code crashes and never recover even if I revert the change. Could you take a look?

```diff
  $$
  \frac{\pi}{2} =
- \left( \int_{0}^{\infty} \frac{\sin x}{\sqrt{x}} dx \right)^2 =
+ \left(\int_{0}^{\infty} \frac{\sin x}{\sqrt{x}} dx \right)^2 =
  \sum_{k=0}^{\infty} \frac{(2k)!}{2^{2k}(k!)^2} \frac{1}{2k+1} =
  \prod_{k=1}^{\infty} \frac{4k^2}{4k^2 - 1}
  $$
```

**Comment by falsandtru** [comment]
I have fixed this by https://github.com/falsandtru/securemark/commit/a9b51e6d87d5788cf677c7bf0d24097cbc7d6d56 by chance. Thanks.

**Comment by dpvc** [comment]
Thanks for letting us know.  I was actually looking into it when you made your changes, and things started working for me unexpectedly.  So I was confused there for a while until I realized that the javascript had changed, and assumed you were making updates.

In any case, I'm glad you got it working.

**Comment by falsandtru** [comment]
Thanks for the response! FYI, you should still be able to repro this error using v0.19.0 and `gulp view` command. I felt MathJax has some wrong internal state.
