### ISSUE TITLE
ETA on MathJax v3.0

### ISSUE THREAD

**Issue by timolawl** [mathjax/MathJax#1773]
Hi,

Thanks for answering my other question about the single files. To follow up on it, I tried to find some estimated time of arrival on the release of MathJax v3.0 but the latest update was in a paper back in 2015. For a project I'm working on, we wish to use the single files of MathJax v3 as we intend to have our app work offline.

Is there an ETA on MathJax v3.0? I hope it's not taboo to ask. Thanks

**Comment by pkra** [comment]
General questions should be posted to the mailing lists at https://groups.google.com/forum/#!forum/mathjax-user and https://groups.google.com/forum/#!forum/mathjax-dev 

There is no ETa. For those interested, we'd recommend following the discussions on the dev list or the development in the v3 repository.
