### ISSUE TITLE
Selecting an overline on Windows breaks the overline rendering

### ISSUE THREAD

**Issue by no-chris** [mathjax/MathJax#1777]
### Issue Summary

On Windows, when selecting a Mathjax-rendered Latex expression such as overline `\overline{AB}`, the overline will appear as a dashed line instead of being a continuous line, such as when its unselected.

### Steps to Reproduce

1. On Windows platform
2. Render the following Latex expression:`\overline{AB+CD}`
3. Select the rendered expression with the mouse
4. Observe the result:
<img width="265" alt="screen shot 2017-06-27 at 14 33 20" src="https://user-images.githubusercontent.com/11467480/27587850-4d1f5220-5b46-11e7-9b76-97036ab57230.png">

### Technical details:

* MathJax Version: 2.7.1 (release)
* Client OS: Windows 10
* Browser: Latest Chrome / Firefox / Internet Explorer / Edge

**Comment by pkra** [comment]
That's expected behavior. 

The overline is, in fact, made up of individual dashes (in HTML-CSS and CommonHTML) and highlighting will make this apparent.
