### ISSUE TITLE
Mactions magnify expression for large mathsize

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax#1800]
Expressions are displayed magnified, when collapsible is turned on. Example:

```
<math xmlns="http://www.w3.org/1998/Math/MathML" mathsize="36pt">
  <mi>1</mi><mo>+</mo>
 <mi>2</mi> <mo>+</mo>
  <mi>3</mi> <mo>+</mo>
  <mi>4</mi> <mo>+</mo>
  <mi>5</mi>
 </math>
```
Then switch on collapsible ..

See [here](https://codepen.io/zorkow/pen/XgygBP).

**Comment by zorkow** [comment]
Some further investigation: 
mactions alone don't have that effect. It only happens in conjunction with collapsible being switched on. 
Maybe it is more an issue for the a11y repo.

**Comment by dpvc** [comment]
OK, it turns out to be a problem in the a11y `collapsible.js` extension (when the `maction` is created, the parent pointers for the content moved into the `maction` aren't being handled properly).  I'll open an issue there and handle it in the a11y repo.
