### ISSUE TITLE
[HTML-CSS] Width of \overrightarrow{} is incorrect for unicode subscripts

### ISSUE THREAD

**Issue by jsmaniac** [mathjax/MathJax#1801]
The the arrow is too wide in `\overrightarrow{aᵢ = eᵢ}`.

![screenshot of the rendered `\overrightarrow{aᵢ = eᵢ}`](https://user-images.githubusercontent.com/299872/28032038-78af3816-65a9-11e7-84a1-f5b66410e436.png)

The problem seems to come from the unicode subscripts, the more there are, the worse it is. Here is what `\overrightarrow{aᵢᵢᵢᵢᵢᵢᵢᵢᵢᵢ}` looks like:

![a followed by lots of unicode subscript i, the arrow is more than twice as long as it should be](https://user-images.githubusercontent.com/299872/28032298-451cbdb0-65aa-11e7-9425-35e9e9859917.png)

The problem does not occur with LaTeX subscripts (`\overrightarrow{a_{iiiiiiiiii}}`):

![a followed by lots of latex subscript i (noted with an underscore), the arrow is more than twice as long as it should be](https://user-images.githubusercontent.com/299872/28032322-6764f1ee-65aa-11e7-901b-c5fd53559323.png)

Online fiddle: https://jsfiddle.net/ec4or3no/2/

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Thesis</title>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        extensions: ["jsMath2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js"],
      });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=default"></script>
  </head>
  <body>
    <span class="math">\overrightarrow{a&#7522; = e&#7522;}</span>
  </body>
</html>
```

**Comment by dpvc** [comment]
For characters that MathJax doesn't have in its fonts, like the ones you are using, the HTML-CSS has to guess about the size of the characters, and which an unusually think character like the subscripted "i", it gets it wrong.  One solution would be to switch to the CommonHTML output jax instead, which handles this better.  Another would be to tell HTML-CSS to measure the unknown characters.  This slows things down, but will improve the results.

Try adding

```
  "HTML-CSS": {
    noReflows: false
  }
```

to your configuration.  That should take care of it.

**Comment by dpvc** [comment]
I'm marking this "expected behavior" because that is how the HTML-CSS output is designed.

**Comment by jsmaniac** [comment]
Since the width is correctly calculated for the rest of the layout (the `ᵢ` do not have extra space between each other), I thought MathJax had already computed the size (I guess this means it relies on the browser's layout in these cases).

I'll try to see if I can switch to CommonHTML (or pre-process the input to turn the `ᵢ` into `_i`, which will give better results anyway).

From what I read in the docs, CommonHTML has poorer browser support and supports less font characters than HTML-CSS, or did I misunderstand the docs?

Thanks!

**Comment by dpvc** [comment]
> CommonHTML has poorer browser support

In the sense that it doesn't support old versions of IE (no support for IE7 and below, and marginal support for IE8), and some *VERY* old versions of other browsers, yes, but I don't think you will find it a problem unless you need very old IE.

> supports less font characters than HTML-CSS

It uses the MathJax TeX fonts, which is the same as you are using with HTML-CSS (though you could choose to use STIX with HTML-CSS, a much larger set of characters, but can't with CommonHTML).

So again, I think you will be reasonably happy with CommonHTML if you are happy with the MathJax fonts for HTML-CSS.
