### ISSUE TITLE
Any plans to support STIX-web with CommonHTML?

### ISSUE THREAD

**Issue by chris-malloy-mri** [mathjax/MathJax#1808]
It seems currently we only have the option of using the Tex font.

**Comment by pkra** [comment]
Duplicate of https://github.com/mathjax/MathJax/issues/1351.

This will be in the v3 release.

**Comment by chris-malloy-mri** [comment]
Thank you. I assume v3 has no scheduled release date yet?

**Comment by pkra** [comment]
There isn't.

You can follow the discussions of the TC at https://groups.google.com/forum/#!forum/mathjax-dev and the development at https://github.com/mathjax/mathjax-v3. We aim for a first set of components by the end of the summer.
