### ISSUE TITLE
[CommonHTML] menclose with diagonal strikethrough not scaling in zoom popup

### ISSUE THREAD

**Issue by danschmiedeler** [mathjax/MathJax#1815]
Howdy -

I noticed that when an element is &lt;menclosed&gt; with either an "updiagonalstrike" or a "downdiagonalstrike" notation, the strikethrough does not scale properly when the element is enlarged via the zoom trigger (it doesn't scale at all, in fact.)  All other notations (box, circle, verticalstrikethrough, etc.) scale just fine.  For example, if I were to zoom the following to 400% (using whatever zoom trigger I have set,) the "2" zooms, but the strikethrough remains at 100%, no longer even touching the 2.
            
&lt;menclose notation="updiagonalstrike"&gt;
&nbsp;&nbsp;&nbsp;&lt;mn&gt;2&lt;/mn&gt;
&lt;/menclose&gt;

**Comment by pkra** [comment]
Thanks for the report. Confirmed but limited to the CommonHTML output.

@dpvc do you want to add this to 2.7.2?

**Comment by dpvc** [comment]
> Do you want to add this to 2.7.2?

No, I think we should go with what we have in the beta, since it is packaged, tested, and being tested on SE.

**Comment by dpvc** [comment]
In testsuite:

UI/zoom/issue1815.html
