### ISSUE TITLE
/over in mathJax not displayed

### ISSUE THREAD

**Issue by A-Allam** [mathjax/MathJax#1816]

**Comment by pkra** [comment]
Please provide a minimal example that exhibits the problem. 

But perhaps check that you're using a backslash not a forward slash (as in the title of this issue), e.g., `$\over{X}$`.

**Comment by dpvc** [comment]
Also note that `\over` appears *between* two things, as in `\(x \over y\)`.

**Comment by A-Allam** [comment]
I solved it, the issue has occurred because the user has a default font for all the system
thanks all.
