### ISSUE TITLE
MathJax rendering on Raphale JS generated SVG

### ISSUE THREAD

**Issue by jpatel3** [mathjax/MathJax#1817]
I am trying to render MathJax formatted equation in the programmatically generated text in Raphael JS svg. 

Here is the sample code - https://jsfiddle.net/jpatel/bdef7kg2/

```
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_SVG"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.js"></script>
        <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            showProcessingMessages: false,
            tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] }
        });
        </script>
    </head>
    <body>
        <div id="container" style="border: 2px solid #999;"></div>
        <script type="text/javascript">
            window.onload = function() {
              var paper = new Raphael(document.getElementById('container'), 100, 100);
                var text = paper.text( 20, 20, "Hello $a^2 + b^2 = c^2$" );
                MathJax.Hub.Queue(['Typeset', MathJax.Hub, text[0]])
            };
        </script>
    </body>
</html>
```

Though it ignores the equation pattern and only renders the plain text. I can see in the console, that it has identified the equation pattern and replaced with script and span tags though it doesn't render in SVG. How can I resolve it?

**Comment by pkra** [comment]
The SVG `text` element does not allow HTML markup; you have to use `foreignObject` instead, cf. https://stackoverflow.com/questions/9946604/insert-html-code-inside-svg-text-element

Also, please make an note when [double posting](https://stackoverflow.com/questions/45556689/raphael-js-svg-text-element-and-mathjax-rendering).

**Comment by pkra** [comment]
Cf. https://stackoverflow.com/questions/15962325/mathjax-inside-svg

**Comment by jpatel3** [comment]
@pkra thanks for confirming. I did read the second link which you sent, though was not sure that its the only way that's why I posted here. Also, those questions were for SVG, I wanted to confirm for Raphael, as while using Raphael adding text element adds tspan inside text node, which is different than that proposed solution in the StackOverflow links.

**Comment by pkra** [comment]
No worries. I'm afraid I don't know why the `tspan` appears but they don't change the main problem - the limitations of `text` nodes, https://www.w3.org/TR/SVG11/text.html#TextElement.
