### ISSUE TITLE
Spacing between cases environments

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1833]
This
\\[ \begin{cases} u_1 =a, \\\\ u_{n+1} =r + u_{n}, \end{cases} \qquad\qquad\qquad \begin{cases} v_1 =a, \\\\ v_{n+1} =rv_{n}. \end{cases} \\]
should produce two cases constructions with some horizontal spacing between them as in
![captura de ecra no 2017-09-12 13-55-03](https://user-images.githubusercontent.com/1136663/30326989-5e4a7562-97c2-11e7-9001-95fde5a4487b.png)
In MathJax the horizontal spacing produced by the \qquad 's is ignored. Example (look for item number 9.) in https://cdi1tp.math.tecnico.ulisboa.pt/praticas/2

**Comment by pkra** [comment]
Thanks for the report. This seems to be a problem with the semantic enrichment (that's active on your site for collapsible rendering).

cc @zorkow

**Comment by zorkow** [comment]
Spacing is not really lost but for some reason it is moved to the front during the enrichment. I'll make it an SRE issue.

**Comment by zorkow** [comment]
Resolved in SRE patch version 2.0.1
