### ISSUE TITLE
Consider using localStorage instead of cookies for storing user's settings

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#1834]
MathJax currently uses cookies to persistently store the settings that the user can change via the menu. Cookies are not the best solution here because they are needlessly transmitted to the server with each and every request (the server doesn't care about MathJax settings). A much better way of storing these settings would be the `localStorage` object. Nowadays, it is widely supported by all major browsers and should be preferred over cookies in such cases where the information is only needed locally and doesn't need to be sent to the server.

**Comment by GalvinGao** [comment]
It's 2019 now, and using `localStorage` is generally a standard way to store user settings. As @TomasRiker mentions, storing information in Cookie causes privacy concerns as well as extra bandwidth consumption.

**Comment by dpvc** [comment]
The version 3 rewrite of MathJax (currently in beta) uses `localStorage` rather than cookies.  After that is released, we can look into back porting that to version 2.

**Comment by dpvc** [comment]
This is fixed in v3.
