### ISSUE TITLE
How can I keep the raw string on my form text input?

### ISSUE THREAD

**Issue by mvww11** [mathjax/MathJax#1835]
Hello.

On the edit page of my text, I don't want MathJax to process the string that appears on the input text field of the edit form. I want it raw. In other words, I want to keep the $$...$$ notation.

How could I do that?

Thanks!

**Comment by mvww11** [comment]
Just use Class: "tex2jax_ignore"

http://docs.mathjax.org/en/latest/options/preprocessors/tex2jax.html

**Comment by pkra** [comment]
Glad to see you could work it out.
