### ISSUE TITLE
Clarification: Is slashed available within MathJax?

### ISSUE THREAD

**Issue by q2apro** [mathjax/MathJax#1841]
You can read at http://arxitics.com/help/mathjax the following: 

> You can use `\slashed` to produce the Feynman slashed-character notation.

However, using the \slashed{x} command does not work. Is that above a false information?

**Comment by q2apro** [comment]
I found it with the cancel package, now the strikeout is working: 

	<script type="text/x-mathjax-config">
		MathJax.Ajax.config.path["Extra"] = "https://my.extra.com/mathjax/extra";
		MathJax.Hub.Config({
			extensions: ["cancel.js"]
		});
	</script>

However, still, the above quote from the other site is confusing.

**Comment by pkra** [comment]
`\slashed` is not part of MathJax's core macros. The site in question has specified a custom macro `\slashed` in their configuration, cf. the source of (e.g.) view-source:http://arxitics.com/articles/1709.06979.
