### ISSUE TITLE
Can the .htaccess file in a11y be removed?

### ISSUE THREAD

**Issue by bert-github** [mathjax/MathJax#1845]
There is an .htaccess file in the a11y extension (unpacked/extensions/a11y/mathmaps/.htaccess) but I wonder why it is there. Shouldn't it be up to each installation to determine if CORS headers are needed? And if they are, wouldn't they rather be at the top level?

**Comment by pkra** [comment]
That sounds like an accidental addition.

@dpvc ?

**Comment by dpvc** [comment]
That's Volker's directory, originally.  I'm wondering if was part of an attempt on his part to get the `.json` to load on cdnjs.

**Comment by pkra** [comment]
cc @zorkow

**Comment by zorkow** [comment]
Yes, we needed that to avoid CORS problems when pulling symbol mappings into SRE.
But we should really only need that on the actual distribution directory.

**Comment by pkra** [comment]
> Yes, we needed that to avoid CORS problems when pulling symbol mappings into SRE.
> But we should really only need that on the actual distribution directory.

So it can be removed here?

**Comment by pkra** [comment]
Fixed upstream.

**Comment by dpvc** [comment]
==> Merged.
