### ISSUE TITLE
Getting transpose symbols to be along the same line

### ISSUE THREAD

**Issue by karnikram** [mathjax/MathJax#1846]
For my expression,

    \dot{R}(t)R^{\top}(t) + R(t){\dot{R}}^{\top}(t) = 0  

The transpose symbols are not along the same line and this is bugging me. It seems to work on share latex though. How do I correct this?

[output](https://drive.google.com/open?id=0B_2Iwz6JbA4pYmhfVEp0MGVJcUE)

**Comment by pkra** [comment]
Thanks for the report. It definitely looks like we do not match TeX's layout here.

@dpvc is this expected behavior?

**Comment by dpvc** [comment]
@pkra, yes, this is the expected result for MathJax.  See issue #712 which discusses the same problem (with `\hat` in that case, but it is the same reason).

As for working around it, the following does get the alignment to be consistent:

    \dot{R}(t)R^{\top}(t) + R(t){\smash{\dot{R}}}^{\top}(t) = 0

Note that for your second example in the image, the output is consistent with TeX (if your input is the following:

    \dot{R}(t)R^{\top}(t) = - {(R(t){\smash{\dot{R}}}^{\top}(t))}^{\top}

If you remove the outermost braces on the right

    \dot{R}(t)R^{\top}(t) = - (R(t){\smash{\dot{R}}}^{\top}(t))^{\top}

you will get the alignment that you desire in both MathJax and TeX.  See the discussion in the issue linked above for details of why these differ.

**Comment by karnikram** [comment]
Thank you for the quick response! I've fixed them now. The problem for me was only the first equation though.
