### ISSUE TITLE
Stars issue in with mathjax \\[ block, with jekyll and markdown

### ISSUE THREAD

**Issue by pltrdy** [mathjax/MathJax#1852]
Hi,

With the following code:
```
\\[ p_{gen} = \sigma(w_{h^{*}}^T h_t^{*}+ w_s^T s_t+w_x^T x_t + b_{ptr}) \\] 
```
It seems that, when using with jekyll (thus, markdown) it interpret the stars like italic operators. Thus, stars aren't displayed. I can escape it with \ but it makes my code non LaTeX compatible which isn't a good thing.

Any idea?

**Comment by pltrdy** [comment]
The best thing I can do so far is to use \ast instead of the character *. It may be the best option, let me know

**Comment by pkra** [comment]
This is a common problem with markdown environments, cf. http://docs.mathjax.org/en/latest/tex.html?highlight=markdown#tex-and-latex-in-html-documents.

If a markdown processor runs before MathJax, there's nothing MathJax can do -- the HTML will be broken. Some markdown processors have special syntax to work around this, e.g. Jekyll's default kramdown uses $$ for both inline and display.
