### ISSUE TITLE
mathjax-sre.js bug causing JS error (fixed upstream)

### ISSUE THREAD

**Issue by mudrd8mz** [mathjax/MathJax#1854]
The bug https://github.com/zorkow/speech-rule-engine/issues/182 affects web applications that integrate MathJax and use RequireJS. The version currently used in MathJax (as per https://github.com/mathjax/MathJax-a11y/blob/master/docs/README.md#mathjax-srejs-and-its-components) leads to a collision and error in JS: mathjax-sre assumes that it can use "require" in CommonJS way (as if it was executed in Node.js).

We have hit this in Moodle - https://tracker.moodle.org/browse/MDL-60209 - but this is likely to affect any product that uses RequireJS. See the discussion there for the analysis and debug of the issue.

To reproduce this in Moodle: Enable any Accessibility option in the popup menu

Result:
![image](https://user-images.githubusercontent.com/85831/31493913-7f51f860-af51-11e7-9294-9d0f5e00b249.png)

The bug seems to be addressed upstream and it now should not attempt to `require('process')` if it is not available.

**Comment by pkra** [comment]
Thanks. It's generally not necessary to file upstream bugs downstream if they are already reported upstream. We will push out a bug fix release once the accessibility extensions are updated (IIRC there's a fix in their repo already).

**Comment by mudrd8mz** [comment]
Yes this has been fixed in their recent version.
