### ISSUE TITLE
Use different kernel browser mathjax font size is not the same

### ISSUE THREAD

**Issue by ljjrhm** [mathjax/MathJax#1857]
Use different kernel browser mathjax font size is not the same,
See example：    
Different browsers show a formula with different results
This is my formula：
![image](https://user-images.githubusercontent.com/29592579/31698409-0bedd7b0-b3f0-11e7-9db9-efbdb220388e.png)
This is my mathml <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>f</mi><mo stretchy="false">(</mo><mi>x</mi><mo stretchy="false">)</mo><mo>=</mo><mstyle displaystyle="true" scriptlevel="0"><mfrac><mn>1</mn><mn>2</mn></mfrac></mstyle><mi>cos</mi><mo>&#x2061;</mo><mn>2</mn><mi>x</mi><mo>+</mo><mn>3</mn><mi>a</mi><mo stretchy="false">(</mo><mi>sin</mi><mo>&#x2061;</mo><mi>x</mi><mo>&#x2212;</mo><mi>cos</mi><mo>&#x2061;</mo><mi>x</mi><mo stretchy="false">)</mo><mo>+</mo><mo stretchy="false">(</mo><mn>4</mn><mi>a</mi><mo>&#x2212;</mo><mn>1</mn><mo stretchy="false">)</mo><mi>x</mi></math>
Different results：
1.
![image](https://user-images.githubusercontent.com/29592579/31698380-e2204364-b3ef-11e7-836c-d2fc0921ff9b.png)
2.
![image](https://user-images.githubusercontent.com/29592579/31698738-934a886a-b3f1-11e7-8e4c-dcf3806c0b1e.png)

**Comment by pkra** [comment]
> Different browsers show a formula with different results

The screenshots indicate that you are using the HTML-CSS output. That particular output is highly client-dependent (all the way to browser and OS versions), so such differences are generally the expected behavior.
