### ISSUE TITLE
Upright lower case Greek letters not supported by all fonts used by MathJax

### ISSUE THREAD

**Issue by AlanFez** [mathjax/MathJax#1859]
I know that this has been raised before see https://github.com/mathjax/MathJax/issues/1076 

Are there any plans to support upright lower case Greek letters across all fonts used by MathJax?

**Comment by pkra** [comment]
> Are there any plans to support upright lower case Greek letters across all fonts used by MathJax?

That depends on what you mean. 

We don't plan to design additional fonts to match existing ones. 

We plan on improving the font fallback chain to allow developers to specify additional font fallbacks, e.g., fallback to glyphs in other supported fonts. We also plan on improving the font tools so that developers can add support for custom fonts somewhat more easily.

**Comment by AlanFez** [comment]
Across fonts supported by MathJax. At the moment has I understand it and see it there is a fallback position http://docs.mathjax.org/en/latest/font-support.html  e.g., upright Greek will be substituted with italic Greek, and it's this substitution in the fallback chain rather than providing the correct glyphs for upright Greek letters across all supported fonts that's giving us problems. 

I suppose the question is are there plans to stop that fallback from occurring, or will it become possible for developers to override that particular fallback making use of their own glyphs if they have them?  I take it from what you are saying that they might be possible in future versions of MathJax.

**Comment by pkra** [comment]
> I take it from what you are saying that they might be possible in future versions of MathJax.

Correct.  Part of this is already being worked on indirectly as part of v3.

**Comment by AlanFez** [comment]
Thanks  :-)

**Comment by dpvc** [comment]
The upgreek package now allows access to upright Greek letters. It is new in v3.2.
