### ISSUE TITLE
MathJax miscalculates width of the container in linebreaks configuration?

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#1861]
I seem to have found a situation where MathJax miscalculates width of the container

![imagem](https://user-images.githubusercontent.com/1136663/31994169-ac545a30-b977-11e7-9458-c6e153126230.png)

Live example at https://math.tecnico.ulisboa.pt/seminars/ , currently near the bottom of the page

Removing

linebreaks: { automatic: true , width:"90% container"},

from the configuration restores the formula.

**Comment by pkra** [comment]
This expected behavior. The content is in a details/summary element which means it effectively has `display:none` when being typeset. See [this blog post](https://www.peterkrautzberger.org/0165/) for some background on the problem.

**Comment by cebola2** [comment]
But going from linebreaks: { automatic: true , width:"90% container"}, to linebreaks: { automatic: true , width:"95% container"} changes linebreaks...

**Comment by pkra** [comment]
> But going from linebreaks: { automatic: true , width:"90% container"}, to linebreaks: { automatic: true , width:"95% container"} changes linebreaks...

Yes, this can happen because MathJax injects the `display:none`ed content somewhere else in the DOM to render it (and then moves the result back to the original position) --  the CSS of that location will determine the rendering, in particular the container width (and thus it can change this way).
