### ISSUE TITLE
Mathjax with phantomJs giving different Margin and height values.

### ISSUE THREAD

**Issue by pawan52tiwari** [mathjax/MathJax#1865]
Hi,
I am using mathjax to convert mathml in svg.
I use phantomjs to process the html,xhtml etc.
I inject Mathjax.js into phantomjs before start the processing. If input has mathml then i am calling my processing function by using mathjax queue.

` MathJax.Hub.queue.Push(function() {window.callPhantom();
                            });`

otherwise i am simply call my function.

My input file doesn't have any mathml content, so it won't got through mathjax queue for processing. 
But i am getting different height of my document and paragraphs.
Document height is 2107 but it should be 2120 and paragraph height is 16px but it should be 21px.
If i am not injecting mathjax in phantomjs then values are coming as per expectation.

Is Mathjax causes to my document run in quirks mode.
My document mode is CSS1Compat
or Mathjax is causing this height issue.

Thanks

**Comment by pawan52tiwari** [comment]
Please let me know if you need input file

**Comment by pkra** [comment]
A minimal example exhibiting the problem would be necessary to help you.

In general, you might want to consider https://github.com/mathjax/MathJax-node. Also, phantomJS uses an old and buggy webkit version and is no longer maintained.

**Comment by GerHobbelt** [comment]
> Also, phantomJS uses an old and buggy webkit version and is no longer maintained.

References about that:
- https://github.com/ariya/phantomjs/issues/15105
- https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE

> In general, you might want to consider https://github.com/mathjax/MathJax-node. 

I am currently looking into that package (and others): isn't https://github.com/mathjax/MathJax-node-page more fitting for this purpose as that one takes a chunk of HTML with one or more TeX formulas and pulls the entire thing through https://github.com/mathjax/MathJax-node, which itself only accepts a *single TeX formula* per call, so with https://github.com/mathjax/MathJax-node alone you would need to provide your own logic to extract the TeX formulas one-by-one from the (HTML) page containing them?

**Comment by pkra** [comment]
Yes, mathjax-node-page would be one way of handling this but if there's a more complex HTML workflow it's usually simpler to built an optimized too on mathjax-node.
