### ISSUE TITLE
While rendering in SVG, mathml input box leaves space to the right

### ISSUE THREAD

**Issue by khalidkadiri** [mathjax/MathJax#1870]
mathjax script tag,
`script("https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_SVG")`

mathml code,
```
<script type="math/mml">	
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle displaystyle="true" mathsize="19px">
    <mrow>
      <mfrac>
        <mrow>
          <msup>
            <mi>&#x3C0;</mi>
            <mn>2</mn>
          </msup>
        </mrow>
        <mrow>
          <mrow>
            <mo></mo>
            <mrow>
              <semantics>
                <annotation-xml encoding="application/xhtml+xml">
                  <input xmlns="http://www.w3.org/1999/xhtml" type="text" maxlength="7" style="width:105px" />
                </annotation-xml>
              </semantics>
            </mrow>
            <mo></mo>
          </mrow>
        </mrow>
      </mfrac>
      <mo>=</mo>
      <mrow>
        <mo></mo>
        <mrow>
          <semantics>
            <annotation-xml encoding="application/xhtml+xml">
              <input xmlns="http://www.w3.org/1999/xhtml" type="text" maxlength="7" style="width:105px" />
            </annotation-xml>
          </semantics>
        </mrow>
        <mo></mo>
      </mrow>
      <mi>w</mi>
    </mrow>
  </mstyle>
</math>
</script>
```

**Comment by dpvc** [comment]
It turns out that the mechanism SVG uses to measure the size of the annotation has a bug that causes the width to be misreported.  

For now, you can add

```
.MathJax_SVG > div {
  display: inline-block;
}
```

to your page CSS in order to work around the problem.

**Comment by khalidkadiri** [comment]
Thanks. It is now working, but for some of the input box, left side is getting cutoff.
Below is the example,
`<script type="math/mml">
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle displaystyle="true" mathsize="19px">
    <mrow>
      <msqrt>
        <mrow>
          <mi>x</mi>
          <mo>+</mo>
          <mn>4</mn>
        </mrow>
      </msqrt>
      <mo>=</mo>
      <msqrt>
        <mrow>
          <mrow>
            <mo></mo>
            <mrow>
              <semantics>
                <annotation-xml encoding="application/xhtml+xml">
                  <input xmlns="http://www.w3.org/1999/xhtml" type="text" maxlength="6" style="width:90px" />
                </annotation-xml>
              </semantics>
            </mrow>
            <mo></mo>
          </mrow>
          <mi>x</mi>
          <mo>&#x2212;</mo>
          <mrow>
            <mo></mo>
            <mrow>
              <semantics>
                <annotation-xml encoding="application/xhtml+xml">
                  <input xmlns="http://www.w3.org/1999/xhtml" type="text" maxlength="6" style="width:90px" />
                </annotation-xml>
              </semantics>
            </mrow>
            <mo></mo>
          </mrow>
        </mrow>
      </msqrt>
    </mrow>
  </mstyle>
</math>
</script>`

![image](https://user-images.githubusercontent.com/15946897/33322889-c445421c-d470-11e7-9a31-82c072d29965.png)

**Comment by pkra** [comment]
> for some of the input box, left side is getting cutoff.

That looks like a browser issue. E.g., Chrome suffers from this but Firefox does not. You could manually add a border to the input via CSS.

**Comment by khalidkadiri** [comment]
Thank you for the help

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite
MathMLToDisplay/issue1870.html
