### ISSUE TITLE
[TeX]  \tag can generate invalid IDs

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1899]
E.g., 

```TeX
\begin{equation}
x \tag{Y $x$}
\end{equation}
```

creates (on any output) an element with `id="mjx-eqn-Y $x$_1"` which is not a valid ID due to the space.

Since IDs can end up in SVG elements, they should ideally be a valid XML IDs to pass validation but stripping spaces probably covers most use cases.

**Comment by pkra** [comment]
This seems to be due to https://github.com/mathjax/MathJax/blob/82590066f9cc3561d4a6b6355ce82af324cb161d/unpacked/jax/input/TeX/config.js#L44 not including whitespace

**Comment by dpvc** [comment]
Perhaps using `encodeURLComponent()` around the string rather than replacing the characters would be a better solution.  Luckily, this is a configuration option, so you can change it yourself in the TeX configuration block until it is fixed.

**Comment by dpvc** [comment]
OOPS! Was thinking of the wrong config parameter, here.  The URL component is already escaped (but should use `escapeURLComponent()` not `escape()`.  You are right that this should not include spaces.  The other characters actually are valid, so perhaps should be left as is?

**Comment by pkra** [comment]
>  The other characters actually are valid, so perhaps should be left as is?

It would be enough for my content but SVG validators will throw an error if the ID is not XML compliant, e.g., if non-BMP unicode is in the tag name. Since SVG is ideal for ebook production, that will probably be a problem for some as most distributors reject files that do not validate.

**Comment by pkra** [comment]
> Since SVG is ideal for ebook production, that will probably be a problem for some as most distributors reject files that do not validate.

But this is hypothetical so the proposed solution seems the right direction especially since it has to be done anyway.

**Comment by dpvc** [comment]
OK, I've made a PR to update the string replacement (now only replaces space characters, and replaces them with underscores instead of just removing them).  If someone needs to filter additional characters, they can override the `formatID` property in the `equationNumbers` block of there TeX configuration.

Also, I switched `encode()` to `encodeURIComponent()`.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite.
LaTeXToMathML/references/issue1899.html

**Comment by pkra** [comment]
> But this is hypothetical [...]

Fun fact: this just became real for me. E.g., `\tag{4 $x^2$}` creates `mjx-eqn-4_$x^2$` which is invalid in XML / SVG; it's even flagged in an HTML context by the nu validator. Time to add a custom function to my configuration.
