### ISSUE TITLE
Misaligned equations

### ISSUE THREAD

**Issue by waynemystir** [mathjax/MathJax#1900]
In MathJax, equations that are tagged do not line up with untagged equations.

[Off-centered Equation][1]

  [1]: https://i.stack.imgur.com/i0ZEI.png

You can see that the tagged equation is not lined up with the untagged equation. This was the code I used to produce this:

    $$
    \begin{equation}
    \Delta f\approx\nabla f\cdot\Delta\mathbf{v}
    \tag{4}\end{equation}
    $$

    $$
    \begin{equation}
    \Delta f\approx\nabla f\cdot\Delta\mathbf{v}
    \notag\end{equation}
    $$

How can I align these equations? Both should be centered the same.

**Comment by dpvc** [comment]
You didn't say which renderer you are using, but I am not able to reproduce your results; the equations along properly for me in HTML-CSS, CommonHTML, and SVG output format.  Can you provide a live example illustrating the problem?

It may be that there is CSS on your page that is bleeding through to the equations and affecting the results.  Try removing CSS files and see if you continue to get the same problem.
