### ISSUE TITLE
Does it support offline functionality？

### ISSUE THREAD

**Issue by jingle0927** [mathjax/MathJax#1922]

**Comment by dpvc** [comment]
See this [MathJax user's forum post](https://groups.google.com/d/msg/mathjax-users/A33PABNJX1w/mg3pgmqlBAAJ) for the answer.  That is a better location for asking questions than this issue tracker, which is designed for reporting bugs and making feature requests, not asking usage questions.

**Comment by jingle0927** [comment]
ok  Thanks
