### ISSUE TITLE
powers to Arabic

### ISSUE THREAD

**Issue by Mohamedaliby** [mathjax/MathJax#1927]
I would like to change the power to be on the left instead of the rightbut I couldn't find that part in the source code.
Can you point it out please. thanks

**Comment by dpvc** [comment]
It's not quite clear what you are asking.  Are you using the [Arabic third-party extension](https://github.com/Edraak/arabic-mathjax)?  If not, perhaps this already does what you need?

**Comment by Mohamedaliby** [comment]
thank you, that's what I needed
