### ISSUE TITLE
MathJax in Blogger

### ISSUE THREAD

**Issue by Telefierito** [mathjax/MathJax#1928]
Dear all,

I wrote some equations in a post of blogger previously I put code to use MathJax, math sentences are showen successful however in android in the cellphone just I see the LaTeX code I mean math sentences dont rendered.
Coud you tell me why this is happening?

Regards,

**Comment by dpvc** [comment]
I suspect that there is a separate theme file for mobile devices like the android, and that you have to modify that one as well.  You may have to ask the blogger community about that.  Google "blogger mobile theme" may get you some help for how to modify the mobile theme.  It looks like setting the mobile theme to "custom" is an important step, but it also seems that you have to make the same edits to the mobile theme that you did to the desktop theme.
