### ISSUE TITLE
[HTML-CSS] box-sizing css can cause table frames to misalign

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#1942]
Originally from [StackExchange](https://math.meta.stackexchange.com/questions/27991/how-to-fix-the-protruding-lines-in-a-mathjax-table).

If the CSS sets `box-sizing: border-box`, then HTML-CSS table frames will be too small.  Using

```
.MathJax span {
  box-sizing: content-box;
}
```

should resolve the issue.

**Comment by pkra** [comment]
The second `box-sizing` should read `content-box`.

**Comment by dpvc** [comment]
Sorry, fixed it.

**Comment by dpvc** [comment]
==> Merged.
