### ISSUE TITLE
[TeX] accents and superscript alignment, comparing with real TeX

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1944]
This is a question, mostly out of curiosity (though it came up in production) and just in case the team considers it a bug.

Comparing MathJax with real TeX, the following renders differently

```
$$\hat{G}^J\widehat{G}^J\widehat{GG}^J\overline{GG}^J\overline{G}^J\bar{G}^J G^J$$
```

MathJax consistently (i.e. in all outputs) has the superscript at (I think) 4 different heights whereas TeX has them at 3 different heights; and they disagree on which one gets which.

MathJax screenshot:

![image](https://user-images.githubusercontent.com/426686/36984967-599fd5f4-2096-11e8-8291-02becbc2fc5d.png)

TeX  screenshot:

![image](https://user-images.githubusercontent.com/426686/36984985-60b10c96-2096-11e8-8e41-a4597a437b37.png)

**Comment by dpvc** [comment]
This has come up before (see #712); TeX handles accents generated by the `\accent` macro via special rules, but MathJax doesn't have `\accent` and the underlying MathML would make it difficult to handle as TeX does.  In particular TeX ignores the accent in the first two and second-from-last cases, while MathJax doesn't.

**Comment by pkra** [comment]
Ah, I didn't find that issue -- thanks for pointing me to it! I figured it was a bit of TeX special sauce.
