### ISSUE TITLE
mathjax printing equation twice

### ISSUE THREAD

**Issue by NikhlPatil** [mathjax/MathJax#1946]
Hello
I am using mathjax to generate equations from latex in our web application. but we are facing some issues like in mathjax printing every equation twice.but after refresh problems gets resolved as well as this issue we face only sometime form same application as page.
if there is any solution for this issue kindly regards

**Comment by dpvc** [comment]
You do not give enough information to analyze your problem.  Can you provide a live example that we can look at?

**Comment by NikhlPatil** [comment]
![mathjax problem](https://user-images.githubusercontent.com/32305306/37326032-40c4a156-26b6-11e8-8730-f18fd7e95e49.png)
as shown in above image mathjax printing every equation twice for generation equation i am using backbone js and cakephp 
 for in js ama using 
`render: function()
{
var self = this;
mStitute.tmplCacheMgr('question', function(tpl)
{
self.model.fetch().complete(function(){
self.$el.html(tpl(self.model.toJSON()));
module.Views.Board.render();
setTimeout(function(){
}, 100);
MathJax.Hub.Queue(function () {
var els_id = $(".question-wrapper[data-question-index='1']").attr('id');
MathJax.Extension.tex2jax.PreProcess(els_id);
MathJax.Hub.Process(els_id, function(){
module.Views.Header.setMainTimerClock();
});
});
});
});
return self;
}
`

and in TeX-AMS_HTML-full.js i am using 

`
MathJax.Hub.Config({
extensions:["tex2jax.js","MathEvents.js","MathZoom.js","MathMenu.js","toMathML.js","TeX/noErrors.js","TeX/noUndefined.js","TeX/AMSmath.js","TeX/AMSsymbols.js","fast-preview.js","AssistiveMML.js","[a11y]/accessibility-menu.js"],
jax: ["input/TeX","output/HTML-CSS","output/PreviewHTML"]
});
MathJax.Ajax.loadComplete("[MathJax]/config/TeX-AMS_HTML-full.js");`
