### ISSUE TITLE
Equations with unwanted symbols - issue on newly updated chrome browser 

### ISSUE THREAD

**Issue by varunkn07** [mathjax/MathJax#1947]
If we create a new equation on newly updated chrome browser some unwanted symbols or Chinese like languages are shown with the equations. 

issue on chrome browser - Version 65.0.3325.146 (Official Build) (64-bit) 

issue:
![issoe on mathjax](https://user-images.githubusercontent.com/20451860/37324491-aa0612a0-26af-11e8-893f-d08df57aed7b.png)

working fine on other browsers and older versions of chrome: 

![original](https://user-images.githubusercontent.com/20451860/37324504-c65512ee-26af-11e8-86ec-127a5c816ba3.JPG)

**Comment by dpvc** [comment]
This suggests that there is a problem with the page encoding, but I can't tell from the given information.  Is it possible to link to a live page where the problem is occurring?

**Comment by varunkn07** [comment]
i will explain the steps:
First i generated an equation using MS Word 2016. And i copied the equation into our contents which was opened in newly updated chrome. when we try to preview the equation the issue occurs. As i mentioned before it was working fine on firefox and older versions of chrome. 

screenshot 1 : 
![mathjax4](https://user-images.githubusercontent.com/20451860/37587890-975614a8-2b86-11e8-8137-61e8be49d6c2.png)

screenshot 2:
![save eqn](https://user-images.githubusercontent.com/20451860/37586248-cb9faaa8-2b81-11e8-99d3-880a27d03a0d.JPG)

screenshot 3:
![math eqn issue](https://user-images.githubusercontent.com/20451860/37586105-52ebdc08-2b81-11e8-8b1c-ce1aa506a996.JPG)

these contents are managed by our admins. So i can't give the link.

**Comment by dpvc** [comment]
From your screen shots, the extra characters are part of the original file (you might look at the "View Page Source" contextual menu item to view the page as it was before MathJax runs and see that the extra characters are already there).  If that is the case, then it is not a MathJax issue, but something to do with the copy and paste operation in newer versions of Chrome.  I suspect that the clipboard data includes additional information (e.g., the equation in several formats), and Chrome is not selecting the right one properly.  The URL's listed among the asian characters suggest that they are coming from a Microsoft product, so they look like additional data that is being copied and pasted into the page.

In any case, it doesn't seem to be a MathJax issue, but rather either a Microsoft one, or a Chrome one. I'm sorry, but I don't think we will be able to help you, here.

**Comment by varunkn07** [comment]
Ok. we will check it.

**Comment by varunkn07** [comment]
i think that was browser issue. We repeated the same steps as mentioned above. Now we can't find the issue. it doesn't exist. So i checked chrome's version and it is updated to **Version 65.0.3325.181 (Official Build) (64-bit)** 

Thanks for your support.

**Comment by dpvc** [comment]
OK, thanks for letting us know.
