### ISSUE TITLE
Webfonts and local MathJax paths in Firefox

### ISSUE THREAD

**Issue by felix11h** [mathjax/MathJax#1949]
I'm using MathJax 2.7.3 with Firefox 59.0 on Ubuntu 16.04. Please consider the following minimal example.

Folder structure:
```
.
├── content
│   ├── index.html
│   └── MathJax-2.7.3/
└── MathJax-2.7.3/  
```

where both MathJax-2.7.3 directories are fully downloaded and unzipped MathJax installations without any modification.

Then 

``` html
<!doctype html>

<html lang="en">
  <head>
    <meta charset="utf-8">

    <!-- path outside of current directory fails to load webfonts -->
    <script type="text/javascript" src="../MathJax-2.7.3/MathJax.js"></script>

    <!-- successfully loads webfonts -->
    <!-- <script type="text/javascript" src="MathJax-2.7.3/MathJax.js"></script> -->

    <script type="text/javascript">
     
     MathJax.Hub.Config({
         jax: ["input/TeX", "output/HTML-CSS"],
         extensions: ["tex2jax.js","TeX/AMSmath.js","TeX/AMSsymbols.js",
                      "TeX/noUndefined.js", "[Contrib]/siunitx/siunitx.js", "[Contrib]/mhchem/mhchem.js"],
         tex2jax: {
             inlineMath: [ ["\\(","\\)"] ],
             displayMath: [ ['$$','$$'], ["\\[","\\]"], ["\\begin{displaymath}","\\end{displaymath}"] ],
             skipTags: ["script","noscript","style","textarea","pre","code"],
             ignoreClass: "tex2jax_ignore",
             processEscapes: false,
             processEnvironments: true,
             preview: "TeX"
         },
         TeX: {extensions: ["AMSmath.js","AMSsymbols.js",  "siunitx.js", "mhchem.js"]},
         showProcessingMessages: true,
         displayAlign: "center",
         displayIndent: "2em",

         "HTML-CSS": {
             scale: 100,
             availableFonts: [],
             preferredFont: "null",
             webFont: "Latin-Modern",
             imageFont: "TeX",
             showMathMenu: true,
         },
         MMLorHTML: {
             prefer: {
                 MSIE:    "MML",
                 Firefox: "MML",
                 Opera:   "HTML",
                 other:   "HTML"
             }
         }
     });

    </script>    

    <title>MathJax in Firefox</title>
    

  </head>

  <body>

    Let \(X: (\Omega_1, \mathcal{A}_1, P_1) \to (E, \mathcal{F})\) and
    \(Y: (\Omega_2, \mathcal{A}_2, P_2) \to (E, \mathcal{F})\) be
    random variables. 

  </body>
</html>
```

does not produce the Latin-Modern webfont and seems to fall back to the image font.

However, if the MathJax installation is used that is in the same directory as `index.html` (commenting and uncommenting the two lines at the top), the Latin-Modern webfont is loaded and displayed correctly. 

Is this intended behaviour? How can I set up MathJax or Firefox so that MathJax paths outside the current directory will still display webfonts? Maybe this is more of a problem of Firefox, but I have already set `security.fileuri.strict_origin_policy ` to `False` as explained [here](https://stackoverflow.com/questions/2856502/css-font-face-not-working-with-firefox-but-working-with-chrome-and-ie).

Thank you!

**Comment by pkra** [comment]
Please read the documentation at https://docs.mathjax.org/en/latest/installation.html#firefox-and-local-fonts.

**Comment by Felix11H** [comment]
@pkra Thank you for the fast reply and for pointing me to this relevant section.

> One solution to this problem is to install the MathJax fonts locally, so that Firefox will not have to use web-based fonts in the first place. To do that, either install the STIX fonts, or copy the fonts from MathJax/fonts/HTML-CSS/TeX/otf into your systems fonts directory and restart your browser. 

The text doesn't mention Latin-Modern fonts and they are also not given as an option for `availableFonts`. As the fonts are installed on my system already, is it correct that there is currently no way to have Latin-Modern displayed in Firefox when using MathJax locally in a different directory from the HTML document? 

Thanks again.

**Comment by dpvc** [comment]
Note that you would need to install the MathJax Latin Modern web fonts, which are not the same as the ones used in TeX itself.  They are at the location linked in the section Peter referred to above.  You can add "Latin-Modern" to the `availableFonts` list, if you wish.  The alternative web fonts like Latin Modern are not included in the `availableFonts` by default because most of them are not complete enough to use by default.

**Comment by dpvc** [comment]
PS, you could also just use

    fonts: ["Latin-Modern", "TeX", "STIX"]

or whatever list you want in order to set `availableFonts` to the list given, and `preferredFont` and `webFont` to the first one in the list.  That makes configuring the fonts a little easier.  This goes in the HTML-CSS block of your MathJax configuration.
