### ISSUE TITLE
Linebreak is not working in chrome as it works in firefox.

### ISSUE THREAD

**Issue by Pratiksha15** [mathjax/MathJax#1959]
I am using Chrome version 65.0.3325.181, Linebreaks{} is not working in chrome but it works in Firefox and safari as well. If this cannot be fixed is there any workaround?

I am using TEX format for equation string = **"$$ \mathrm{R}\hbox{--} C HO+ N{H}_2\hbox{--} NH\hbox{--} C O\hbox{--} C{H}_2\hbox{--} \mathrm{N}{\left( C{H}_3\right)}_3\to \mathrm{R}\hbox{--} \mathrm{C}=\mathrm{N}\hbox{--} NH\hbox{--} C O\hbox{--} C{H}_2\hbox{--} \mathrm{N}{\left( C{H}_3\right)}_3 $$"**

`<script type="text/x-mathjax-config">`
`MathJax.Hub.Config({`
        ` CommonHTML: { linebreaks: { automatic: true }, width: "10% container" },`
           ` "HTML-CSS": { linebreaks: { automatic: true }, width: "10% container" },`
                 `SVG: { linebreaks: { automatic: true }, width: "10% container" }`
       ` });`
`</script>`
`<script type="text/javascript" async`
`        src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML">`
`MathJax.Hub.Config({`
`            tex2jax:{ inlineMath: [['$','$'], ['\\(','\\)']], processEscapes: true }`
`        });`
`</script>`

**This is how it looks in Chrome**
<img width="650" alt="screen shot 2018-03-29 at 5 11 01 pm" src="https://user-images.githubusercontent.com/22068069/38087086-7bf43dc0-3374-11e8-8701-c3d34c3ec17f.png">

**This is how it looks in Firefox**
<img width="605" alt="screen shot 2018-03-29 at 5 30 51 pm" src="https://user-images.githubusercontent.com/22068069/38087769-fc679478-3376-11e8-9392-37bf134e4656.png">

**Comment by dpvc** [comment]
I am not able to reproduce the problem you are seeing in my own test files.  Can you provide a link to the actual page you are looking at?  I suspect there may be some funny interaction of the CSS on the page with MathJax.

PS, do you know about the [mhchem extension](https://mhchem.github.io/MathJax-mhchem/)?
