### ISSUE TITLE
tex2jax, $ delimiters might ignore escaped \$

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1960]
Via the AMS. With `processEscapes:true`, e.g., this

`<p> \$1 -- \$2 -- \$3 -- $4 -- \$5 -- \$6</p>`

is turned into

`<p> $1 -- $2 -- $3 -- $4 -- \$5 -- \$6</p>`

I'm guessing tex2jax starts lookin for another `$` to match `$4`, reaches the end of the text node, realizes it can stop and never goes back to convert the escaped `\$`.

Would you consider this a bug?

**Comment by pkra** [comment]
Thanks, Davide.

**Comment by dpvc** [comment]
No problem.  It looks like I will be putting together a 2.7.4 release (for within the next two weeks).  If you have anything else in the hopper that you haven't reported, let me know.

**Comment by dpvc** [comment]
==> In testsuite
Parsing/issue1960.html
