### ISSUE TITLE
2.7.4 not published on npm

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1972]
I'm guessing it's the same key change issue as with other repos.

@dpvc could you manually push it out?

**Comment by dpvc** [comment]
Done.

I had failed to update the version in the `package.json` file, and had to fix that first.  It was supposed to have been edited automatically along with the other files when I update versions, but there was a bug in the code for that.  I think I have fixed it.

There may still be a problem with the token.  I had updated it, but it still seems not to be working.  I'm pretty sure the last mathjax-node went through, so I will see if I can tell what the difference is.  I got an email that indicated 2.7.4 was released that I thought was from npmjs, but I guess it was only from github, and that didn't mean the travis task completed properly.

**Comment by pkra** [comment]
Thanks, Davide.
