### ISSUE TITLE
Unable to display latex equation on a webpage read from database  

### ISSUE THREAD

**Issue by shivaprashanthg** [mathjax/MathJax#1973]
1.I am trying to use a Mathjax library in emberjs/Angular application, and am able to convert tex code to math equation( from my templates and also from my model from javascript).
2. When tried to get tex equation from mysql database to the emberjs templates through model, i can see only the tex code but not actual equation?
3. In the 1st step i am hardcoding my array of objects and able to render through model and convert to equations as desired.
4. In the 2nd step i am fetching the array of objects from mysql database to the emberjs templates through model, in both the cases tex code in the objects are same as i can view it in console.
What might be the reason for this?

**Comment by dpvc** [comment]
It sounds like you need to include a call to `MathJax.Hub.Queue(["Typeset", MathJax.Hub])` after you load the math into the page from the database.  See [the documentation](http://docs.mathjax.org/en/latest/advanced/typeset.html) for more details.

**Comment by dpvc** [comment]
PS, this forum is intended for reporting errors in MathJax, not for asking general questions about how to use MathJax.  Such questions are better suited to the [MathJax User Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users).
