### ISSUE TITLE
can't render ^ in inline equation

### ISSUE THREAD

**Issue by RanMaosong** [mathjax/MathJax#1978]
I write a inline equation with superscript， it can't be rendered,but it's ok in block equation.For example:
`$c^{T}x^{*}=y^{T}Ax^{*}=y^{*T}b$` , the result is also "`$c^{T}x^{*}=y^{T}Ax^{*}=y^{*T}b$`" instead of a math equation.The other inline equation can work, only when inline equation contains '^' don't.

**Comment by dpvc** [comment]
Have you enabled the dollar signs as in-line math delimiters?  The dollar sign is not enabled by default.  See the [documentation](http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters) for more details.

If that isn't it, you will have to be more clear about how you have included MathJax in your pages (e.g., your configuration, and whether you are using a content-management system of any kind).  A link to a page exhibiting the problem would be best.
