### ISSUE TITLE
Can't render \begin{cases}...\end{cases} using Jekyll on Github pages

### ISSUE THREAD

**Issue by fedemengo** [mathjax/MathJax#1980]
I tried to write a system of equations using "cases" but it doesn't show up on the webpage. I have no idea why but on my machine works just fine. When I push the changes on GitHub and the page is rendered that specific part is gone. 

I manage to find a workaround to display it by putting the "cases" inside a <div></div>. However is not really nice since it broke the whole text.

Here is my configuration

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    TeX: {
      equationNumbers: {
        autoNumber: "AMS"
      }
    },
    tex2jax: {
      inlineMath: [ ['$','$'] ],
      displayMath: [ ['$$','$$'] ],
      processEscapes: true,
    }
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
```

Here is the code I'm trying to display: 

```
$$\widetilde{d_t} = \begin{cases} d_t & if d_{t+1} \leq \dfrac{B}{2}\\ d_t+1 & if d_{t+1} > \dfrac{B}{2} \end{cases}$$
```

I tried to use single `$` but they don't work either. Is there a way to correctly use this kind of command that I'm not aware of?

**Comment by cebola2** [comment]
Replace > with \gt
That is a MathJax limitation due to the nature of the usage of < and > in
HTML code.

A Qua, 18 de abr de 2018, 20:10, Federico Mengozzi <notifications@github.com>
escreveu:

**Comment by pkra** [comment]
> When I push the changes on GitHub and the page is rendered that specific part is gone.

Do you have a link to the repo and/or a live page that exhibits the problem?

**Comment by pkra** [comment]
The HTML source of the last link has 

` <script type="math/tex">% <![CDATA[ p \not\in [L, U] \implies \begin{cases} p \gt U & \textbf{overflow}\\ p \le L & \textbf{underflow} \end{cases} %]]></script>`

The `% ` demarks comments in TeX, thus MathJax's TeX processor will ignore the string.

Then there's the CDATA which should not be there (i.e., if you remove the %, you'll get `[CDATA ... ]` in your output).

So something is screwing up your content between the source and the HTML. Without the Jekyll setup, it's hard to tell which part is at fault.

In any case, MathJax can only render what's provided in the HTML so this is not an issue with MathJax.

**Comment by fedemengo** [comment]
Thank you for the insight, I wasn't able to find the problem. Anyway, if I use '$' instead of '$$' and I escape the new line using '\\\\' it seems to be ok.
