### ISSUE TITLE
[PreviewHTML] support for munder

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#1981]
I just noticed this the other day. Looks like the styles for `MJXp-munderover` would be enough to make it work.

**Comment by dpvc** [comment]
Not sure why that wasn't there to begin with.  I think it was probable;y because `munder` is implemented via `munderover`, and I didn't take the fact that it would be producing containers with different names.

**Comment by dpvc** [comment]
We don't have test runs for PreviewHTML, so I'm not making a test for this.
