### ISSUE TITLE
Common HTML scriptlevel width problem

### ISSUE THREAD

**Issue by thewilkybarkid** [mathjax/MathJax#1985]
Having a `<mstyle scriptlevel="+1">` and using Common HTML seems to cause a width to be miscalculated in  

<img width="345" alt="screen shot 2018-04-24 at 10 15 58" src="https://user-images.githubusercontent.com/1784740/39177999-95622b8a-47a8-11e8-9c37-37e572868972.png">

(http://jsbin.com/piciyufabo/1/edit?html,output)

Remove the `scriptlevel` sees it work:

<img width="377" alt="screen shot 2018-04-24 at 10 16 13" src="https://user-images.githubusercontent.com/1784740/39178003-99b6351e-47a8-11e8-8a98-c33bf946e075.png">

(http://jsbin.com/wupalifula/1/edit?html,output)

HTML-CSS and SVG render correctly.

**Comment by dpvc** [comment]
Thanks for the report, I'll look into it.

**Comment by dpvc** [comment]
Here is a more minimal test case:

```
<math><mfrac><mi>x</mi><mrow><mstyle scriptlevel="+1"><mi mathvariant="italic">xxxxxxxxxxxxxx</mi></mstyle></mrow></mfrac></math>
```

**Comment by dpvc** [comment]
OK, it turns out that the CommonHTML implementation of `mstyle` gets its bounding box wrong when `scriptstyle` is present on that element (it improperly applied the scaling twice).

A temporary fix for now would be to add

```
MathJax.Hub.Register.StartupHook("CommonHTML Jax Ready", function () {
  delete MathJax.ElementJax.mml.mstyle.prototype.toCommonHTML;
});
</script>
```

just before the script that loads `MathJax.js` itself.  That will remove the offending code.

**Comment by dpvc** [comment]
==> In testsuite
MathMLToDisplay/issue1985.html
