### ISSUE TITLE
Only properly loading after refresh

### ISSUE THREAD

**Issue by joolsmtw** [mathjax/MathJax#1989]
I've seen two similar issues with MathJax, although the solutions presented there did not work for me.
Example page: #### (Scroll down for the Tex)

I use a Ghost blog with the following code injected into the `<head>`

```
<script type="text/javascript" async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML">
if (window.MathJax) {
        MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [["$", "$"], ["\\(", "\\)"]],
            processEscapes: true
        }
    });
}
</script>
```

Two similar issues were https://github.com/mathjax/MathJax/issues/507 and https://stackoverflow.com/questions/32928303/mathjax-not-rendering-equation-unless-page-reloaded, although the solutions proposed there didn't work for me (at least I didn't get them to work).

Any ideas on what could cause this?

Sorry, if I haven't provided enough information.

**Comment by joolsmtw** [comment]
Thank you, I'll investigate a bit further and ask around in the Ghost community!
Also, I just afterwards realized that this is the Dev issue page (rather new with using Github), so feel free to delete my issue, if that's possible. 

Thank you agai nfor your help, though.

**Comment by BilalReffas** [comment]
I could observe the same behaviour on Safari (Ghost) it works fine on Firefox and Chrome though.
