### ISSUE TITLE
Same text, different display.

### ISSUE THREAD

**Issue by JAtank** [mathjax/MathJax#1993]
The text is the same, but different in SVG and HTML.
text:"$\\underline{\\underline{\\begin{array}11111111\\end{array}}}$"
SVG:
![svg](https://user-images.githubusercontent.com/20762912/40032957-dd9f39f2-5828-11e8-8ec0-7d60bbc8d22e.png)
HTML:
![html](https://user-images.githubusercontent.com/20762912/40032961-e4d902de-5828-11e8-9bc5-9501169cd745.png)

**Comment by JAtank** [comment]
Why didn't anyone solve it? @dpvc

**Comment by dpvc** [comment]
It is a bug and I haven't yet tracked down its cause.  Neither output is entirely correct.  I do not know when a fix will be ready.  Patience is a virtue.

**Comment by JAtank** [comment]
Thank you very much. I hope you can inform me in time after the change.In fact, we have encountered some other mistakes in the process of use, but this problem is very special, and it is difficult for us to have a good way to display our resources.

**Comment by dpvc** [comment]
==> In testsuite
MathMLToDisplay/Presentation/ScriptsAndLimits/issue1993.html
