### ISSUE TITLE
Execution of unrelated Object.prototype methods by TeX parser

### ISSUE THREAD

**Issue by sergey-o** [mathjax/MathJax#1996]
When given the TeX input `\toString`, MathJax internally calls `Object.prototype.toString` as a control sequence "handler" instead of reporting an error. This happens for any property name defined in `Object.prototype` and is caused by missing `hasOwnProperty` checks in lookups ([here](https://github.com/mathjax/MathJax/blob/2.7.4/unpacked/jax/input/TeX/jax.js#L1112-L1122), for instance).

Examples of other problematic constructs: `\begin{toString}\end{toString}`, `\cfrac[toString]ab`.

**Comment by dpvc** [comment]
==> In testsuite
LaTeXToMathML/issue1996.html
