### ISSUE TITLE
Colorbox does not render on my machine

### ISSUE THREAD

**Issue by tonyriverms** [mathjax/MathJax#1999]
I follow the test example in your repo https://github.com/mathjax/MathJax-test/blob/master/testsuite/LaTeXToMathML/colors/colorbox-1.html, and the instruction here http://docs.mathjax.org/en/latest/tex.html

It dose not work on my machine.

<img width="112" alt="capture" src="https://user-images.githubusercontent.com/9701455/40617712-2d8501b6-625d-11e8-86a7-f90ae935263e.PNG">

```
<!DOCTYPE html>
<html class="reftest-wait">
  <head>
    <title>colorbox</title>
    <!-- Copyright (c) 2011-2015 MathJax Consortium
         License: Apache License 2.0 -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript">
		MathJax.Hub.Config({
			TeX: { extensions: ["color.js","autoload-all.js"] }
		});
    </script>
  </head>

  <body>
    <div id="reftest-element">\( \colorbox {red} x y z \)</div>
  </body>
</html>
```

**Comment by dpvc** [comment]
Your configuration is not being done properly.  Because MathJax starts loading its resources during the script that loads MathJax.js itself, you need to configure MathJax *before* loading the MathJax.js file.  That is done using a script with `type="text/x-mathjax-config"`.  If you change your code to

```
<!DOCTYPE html>
<html class="reftest-wait">
  <head>
    <title>colorbox</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        TeX: { extensions: ["color.js","autoload-all.js"] }
      });
    </script>
    <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
  </head>

  <body>
    \( \colorbox {red} x y z \)
  </body>
</html>
```

that should resolve the issue.

**Comment by tonyriverms** [comment]
Great! This works, thank you!

**Comment by dpvc** [comment]
Glad it worked!
