### ISSUE TITLE
mathjax支持reactjs吗

### ISSUE THREAD

**Issue by zuwensong** [mathjax/MathJax#2000]
请问mathjax如何在reactJS的环境中正常使用，我在react项目的启动页面引入脚本文件后，在组件第一次渲染的时候能看出效果，但是当页面中的组件被更新时，mathjax无法生效。
![image](https://user-images.githubusercontent.com/18671875/40621845-481e74a2-62d1-11e8-9d21-3ab9157ebffc.png)
请问有谁在react中用过mathjax吗？

**Comment by dpvc** [comment]
Perhaps [react-mathjax](https://www.npmjs.com/package/react-mathjax) is what you are looking for?

Otherwise, you will have to look at the MathJax documentation for [modifying math on the page](http://docs.mathjax.org/en/latest/advanced/typeset.html) for some ideas.
