### ISSUE TITLE
Please add upright greeks

### ISSUE THREAD

**Issue by tonyriverms** [mathjax/MathJax#2004]
The upright greeks like ``$\rm{\alpha}$`` does not work, and ``$\bf{\rm\{\alpha}}$`` does not work either. I searched online and it looks mathjax current does not support that. I believe these notations are not uncommonly used. Adding support for them could be very helpful for those in the field of numerical computation who frequently use these upright greeks to represent coefficient vectors.

**Comment by dpvc** [comment]
This is a duplicate of #1076.  See also #1859.

**Comment by dpvc** [comment]
The `upgreek` package now allows access to upright Greek letters.  It is new in v3.2.
