### ISSUE TITLE
LaTex cannot be modified correctly

### ISSUE THREAD

**Issue by totoroyyb** [mathjax/MathJax#2007]
I've been trying to modify the equation dynamically.

So, I tried `MathJax.Hub.Queue()`

The code is here:
``` 
function ChangeEquation() {
    var math = MathJax.Hub.getAllJax("equation")[0];
    MathJax.Hub.Queue(["Text", math, "\frac{\partial\psi}{\partial t}=\kappa\mathrm{\nabla}^2\psi"]);
}
```

However, MathJax seems cannot re-render LaTex correctly since I got this:
![image](https://user-images.githubusercontent.com/30278896/41227023-006400f2-6da6-11e8-82da-4348d3e25f8c.png)

It should looks like this:
![image](https://user-images.githubusercontent.com/30278896/41227173-8815210c-6da6-11e8-8c0c-be474687e30e.png)

MathJax can correctly render LaTex at first time, but when I try to modify it, something goes wrong.

I'm not sure is that a bug of MathJax or I haven't use it in a right way.

Any help are appreciated!! Thanks!!

**Comment by dpvc** [comment]
Within a javascript string, `\` has a special meaning, so if you want to include a literal `\` you must double it.  So you should use

    MathJax.Hub.Queue(["Text", math, "\\frac{\\partial\\psi}{\\partial t}=\\kappa\\mathrm{\\nabla}^2\\psi"]);

That should produce the result you are looking for.

**Comment by totoroyyb** [comment]
Thanks for your help!
