### ISSUE TITLE
wideparen feature requests

### ISSUE THREAD

**Issue by doraven** [mathjax/MathJax#2008]
I know `wideparen` is not supported in amsmath. It comes from package [`yhmath`](http://mirrors.ibiblio.org/CTAN/fonts/yhmath/yhmath.pdf).

And mathjax has `overparen` which is not in amsmath either. But it's not what I imaged.

Here is `overparen` by `mathjax`
![default](https://user-images.githubusercontent.com/15844287/41449829-fd610a24-7095-11e8-8552-776327dfb617.png)

And it's `wideparen` by `yhmath`
![default](https://user-images.githubusercontent.com/15844287/41449866-3d64e79e-7096-11e8-9245-f3a85747fdb7.png)

The latter is what we use in handwrite.

So could it be possible to add `wideparen` in mathjax?That would be great help!

PS: I tried with adding `wideparen: ['UnderOver','2322'],`,  in maros config and the source js file. Both failed. '2322' is `frown` (oh god, I found this) which looks like `wideparen' . 

Thanks for reading this.

**Comment by dpvc** [comment]
The MathJax TeX fonts don't include the needed characters for the over parenthesis like in your screenshot.  But the STIX fonts do, so if you configure MathJax to use STIX instead of the default MathJax fonts, you will get something more like what you want.

**Comment by doraven** [comment]
add `fonts: [["STIX",]`](https://docs.mathjax.org/en/latest/options/output-processors/HTML-CSS.html#configure-html-css) , `overparen` is working well.

thank u
