### ISSUE TITLE
Characters incorrectly displayed as subscripted

### ISSUE THREAD

**Issue by fonnesbeck** [mathjax/MathJax#2010]
There is a rendering issue with some LaTeX equation characters on a Chromebook. Notably, characters like summation and integration appear as if they are subscripted. For example, the following:

    $$E[h(\theta)|y] = \int h(\theta) p(\theta|y) d\theta \approx \frac{1}{n}\sum_{i=1}^n h(\theta)$$

results in this equation:

![image](https://user-images.githubusercontent.com/81476/41566404-ff26974c-7320-11e8-9733-700413247bc2.png)

Note the bug in vertical alignment for the summation and integration symbols. I am running this on a Pixelbook (ChromeOS 67).

**Comment by dpvc** [comment]
It looks like you are not getting the MathJax fonts, which have variants at larger sizes that are used for the large integral and summation signs.  Have you disabled page-specified off fonts in your browser (some browsers allow that)?  Are you using your own installation of MathJax, or does the page use MathJax from a CDN?

**Comment by fonnesbeck** [comment]
This is using ChromeOS (PixelBook), so its just Chrome. The page uses MathJax from a CDN. I expect you may be right regarding fonts being locked down, but I haven't been able to find a setting to change for that.

**Comment by dpvc** [comment]
I don't see a setting for this anymore myself.  If you open the developer console, do you see any errors about the fonts?

**Comment by fonnesbeck** [comment]
I ended up addressing the issue by installing the [katex extension](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/katex-extension) for Jupyter (though it does not fix the original problem, of course). I did notice there was a failure installing the STIX fonts the last time I attempted rendering a page without the extension, however.

**Comment by dpvc** [comment]
OK.  I'm sorry you were not able to get MathJax to work for you.  I'm sure it is a font issue.  It may be that the configuration is set up to expect local STIX fonts, for example, but you don't have them.  It might be worth checking what the MathJax configuration is (you might have to inspect the DOM for the page (I don't know how much Jupyter lets you control that).
