### ISSUE TITLE
Math rendered inside of MathJax status bar (div#MathJax_Message) instead of where it should be [jsfiddle example]

### ISSUE THREAD

**Issue by vmarquet** [mathjax/MathJax#2012]
When math stuff is rendered with MathJax, the math elements are rendered INSIDE the status bar: `div id="MathJax_Message" style="display: none">[HERE]</div>`, instead of in a sibling element. Therefore, the math content is invisible since `display: none` is used.

[jsfiddle example of bug](http://fiddle.tinymce.com/yugaab/1). To reproduce, just wait for everything to load and click the 'latex' button. The math will be rendered inside the grey status bar and then disappear with it. Note that when the button is clicked a second time without moving the cursor to an other line, it works. But this is not acceptable for the user experience to have something that does not work the first time.

So there is an error when managing the creation of the div#MathJax_Message, MathJax should make sure that some other content do not get included as children of the div. I've taken a quick look around, maybe the error is near https://github.com/mathjax/MathJax/blob/50c333cc695066b9d27f713035b44c9ef78ab658/unpacked/MathJax.js#L1680.

Note that I would be happy if there was an option to disable completely the status bar, since I don't want it. This bug would not be there in the first place if it was possible. I've tried the options [here](https://github.com/mathjax/MathJax-docs/wiki/Hide-render-statusbar) but they only hide the status bar with css, they don't disable entirely the associated logic as I would have liked.

Copy of the code, in case the fiddle goes down:

```
<script type="text/javascript">
const plugin = (editor) => {
  editor.addButton('latex', {
	text: 'latex',
	onclick: () => {
	  createEquation()
	}
  })

  editor.on('init', function (event) {
	const body = editor.dom.getRoot() 
	addMathJaxScript(editor.getDoc())
  })

  const addMathJaxScript = (document) => {
	var script = document.createElement('script')
	script.type = 'text/x-mathjax-config'
	script.text = `
	  MathJax.Hub.Config({
		showMathMenu: false,
		tex2jax: {
		  inlineMath: [['$-','-$']],
		  displayMath:[['$$','$$']],
		}

	  })

	  rerenderMathJax = function() {
		MathJax.Hub.Queue(["Typeset", MathJax.Hub])
	  }
	`
	document.head.appendChild(script)

	script = document.createElement('script')
	script.type = 'text/javascript'
	script.src = 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
	document.head.appendChild(script)
  }

  const createEquation = () => {
	editor.insertContent(`
	  <span>
		$$ x=2 $$
	  </span>
	`.trim())

	try {
	  editor.getWin().rerenderMathJax()
	} catch(e) {  // TypeError if MathJax not completely loaded yet.
	  if (!(e instanceof TypeError)) { throw e }
	}
  }
}


(function () {
var code = (function () {
  'use strict'

  const PluginManager = tinymce.util.Tools.resolve('tinymce.PluginManager')
  PluginManager.add('latex', function (editor) {
    plugin(editor)
    return {}
  })

  function Plugin () {}
  return Plugin
}())
})()

</script>

<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor latex",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | latex",
	forced_root_block: false,
});
</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```

**Comment by dpvc** [comment]
This is not actually a MathJax bug.  It is due to the fact that 

	editor.insertContent(`
	  <span>
		$$ x=2 $$
	  </span>
	`.trim())

inserts the span inside the `MathJax_Message` div rather than after it.  So MathJax typesets it; perhaps that is a MathJax error, but the fact that the math is in the message div is not.  That come from TinyMCE.

One work-around would be to remove the message div so MCE won't put the math into it.  If you add

	  MathJax.Hub.Register.StartupHook('Begin Jax', function () {
		var div = MathJax.Message.div;
		div.parentNode.removeChild(div);
	  });

to the MathJax configuration script (say after line 27 in your jsFiddle), that should take care of that for you.

**Comment by vmarquet** [comment]
Thank you very much @dpvc for looking into this and your quick answer. This is indeed my mistake with the wrong `insertContent` so I'm closing this.

I'd like still to point out that all of this wouldn't have happened is there was a simple option to just disable completely the creation of `div#MathJax_Message`, this would be really helpful.

Anyway, thank you again for your work on this issue and for this

**Comment by pkra** [comment]
> [if]  there was a simple option to just disable completely the creation of div#MathJax_Message, this would be really helpful.

There is. Just google "mathajx hide message" or read the documentation, e.g., https://docs.mathjax.org/en/latest/options/hub.htm

```
showProcessingMessages: true

    This value controls whether the Processing Math: nn% messages are displayed in the lower left-hand corner. Set to false to prevent those messages (though file loading and other messages will still be shown).

messageStyle: "normal"

    This value controls the verbosity of the messages in the lower left-hand corner. Set it to "none" to eliminate all messages, or set it to "simple" to show “Loading…” and “Processing…” rather than showing the full file name or the percentage of the mathematics processed.
```

**Comment by vmarquet** [comment]
@pkra Either I was unclear or you are mistaken about those options, because what I meant by 'disable completely' is 'do **not create** the div#MathJax_Message in the DOM'.

The `messageStyle: "none"` option merely sets `display: none` on the div, which still creates a dirty element that is still causing the bug above, see [this fiddle](http://fiddle.tinymce.com/5ugaab/1).

**Comment by pkra** [comment]
> Either I was unclear or you are mistaken about those options, because what I meant by 'disable completely' is 'do not create the div#MathJax_Message in the DOM'.

No, it was my fault. I had not read your comment carefully enough. Sorry.
