### ISSUE TITLE
Colored text possible?

### ISSUE THREAD

**Issue by gandalfsaxe** [mathjax/MathJax#2013]
Looking at #218, I can't quite figure out what the point of `\textcolor` is. If I do:
```latex
\textcolor{red}{hi}\textcolor{blue}{ there}
```
<img width="58" alt="image" src="https://user-images.githubusercontent.com/12127864/42050970-d368d948-7b0a-11e8-9a24-aaa2f6ffe731.png">

all letters are italic as if it was math, and there is no space between the words. Is there away to achieve colors in a string of text that is upright, not italic?

**Comment by dpvc** [comment]
This is the correct behavior, and is consistent with how LaTeX processes the commands you listed.

If you want to color non-mathematical text, you can use

    {\color{red}{\text{hi}}\color{blue}{\text{ there}}}

You can , of course, define your own macro to make it easier, e.g.,

    \def\textcolor#1#2{{\color{#1}{\text{#2}}}

which should make your expression produce the result you are looking for (both with MathJax's initial `\color` command, and the one from the `color` extension; that's the purpose of the extra braces).

**Comment by gandalfsaxe** [comment]
Ah perfect then. What are the supported colors?

**Comment by dpvc** [comment]
If you use the original `\color` macro (i.e., don't load the color extension), then any HTML color name (e.g., red) or color value (e.g., #F00 or #00FF80) is allowed.  If you use the color extension, then it depends on which color model you use (and you are allowed to define your own colors).

**Comment by gandalfsaxe** [comment]
1. Just to be clear, it's HTML and hex that works, not the [default from LaTeX or dvipsnames option](https://www.sharelatex.com/learn/Using_colours_in_LaTeX#Reference_guide)?

2. Can more colors be loaded by loading in e.g. `\usepackage{xcolor}` or is this package unsupported?

Not because I desperately need them, I just want to be clear on what's available :-)

**Comment by dpvc** [comment]
> Just to be clear, it's HTML and hex that works, not the default from LaTeX or dvipsnames option?

If you don't load the `color` extension, then yes, HTML and hex RGB values.  If you load the `color` extension, either in your MathJax configuration, or through `\require{color}` within a math expression, then you can use the divps names.  You can also use several of the other color models (`rgb`, `RGB`, `grey`).

> Can more colors be loaded by loading in e.g. \usepackage{xcolor} or is this package unsupported?

No, but you can use `\definecolor` to specify your own named colors.

**Comment by gandalfsaxe** [comment]
Thanks.

**Comment by RoyiAvital** [comment]
I have an issue which is related.
I use `color{Cyan} some text` and the result from MathJaX doesn't match the Cyan of HTML.

Where are the colors defined?

**Comment by dpvc** [comment]
> Where are the colors defined?

The ones for the v3 color extension are in [ts/input/tex/color/ColorConstants.ts](https://github.com/mathjax/MathJax-src/blob/master/ts/input/tex/color/ColorConstants.ts).  They are the [dvips color names](https://www.overleaf.com/learn/latex/Using_colours_in_LaTeX#Accessing_additional_named_colours) from the xcolor LaTeX package, and they use the color values from that package, not the HTML colors of the same names.

Note, however, that the color names are case sensitive, and that if you use a name that is not in the list, it will be passed along as an HTML color name, so you can use

``` latex
\color{cyan} some text
```

or

``` latex
\color{#0FF} some text
```

to get the HTML cyan colors.
