### ISSUE TITLE
Subscript could not be rendered using MathJax 2.7.4

### ISSUE THREAD

**Issue by kwailamchan** [mathjax/MathJax#2016]
Using MathJax 2.7.4 as below:

```
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
```

Superscript ``$$x^{a+1}$$`` worked well, $$x_t$$ worked well, whereas ``$$x_t = F_t * x_{t-1}$$`` could not be rendered. 

```
$$x^{a+1}$$  --> worked
$$x_t$$  --> worked
$$x_{t-1}$$  --> worked
$$x_{t-1} F_t$$  --> worked
$$F_t x_{t-1}$$  --> not rendered
$$x_t = F_t * x_{t-1}$$ --> not rendered
```

**Comment by pkra** [comment]
You are probably using a Markdown processor that does not isolate TeX syntax and thus converts pairs of underscores inside TeX to `<em>`s. Please search the tracker https://github.com/mathjax/MathJax/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+subscript+markdown

**Comment by kwailamchan** [comment]
@pkra Thanks for your reply, #573 provided the solution:

``x_\{t-1}`` made the problem solved.

```
$$ x_t = F_t x\_{t-1} $$
```
