### ISSUE TITLE
Adjust the space above and below a displayed formula

### ISSUE THREAD

**Issue by ShaohongShi** [mathjax/MathJax#2018]
How to adjust the space above and below the formula under Principle of Archimedes.
I need to put all codes in one html file, and it has to be a static html file.
Moveover,I would like to make the code in the head of the file.
![6c13f65b-11f3-4ccd-bd1e-8aec9216b083](https://user-images.githubusercontent.com/39336808/42251686-5a133a4c-7f6b-11e8-9b21-24ed1fab2c7f.jpeg)

**Comment by dpvc** [comment]
PS, this issue tracker is really for reporting bugs in MathJax.  It is better to use the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) to post general questions about MathJax.

**Comment by ShaohongShi** [comment]
Oh, really appreciate you. I do not know much about mathjax and I did not find that forum before. I will close this issue and turn to the forum you suggested next time.
