### ISSUE TITLE
请问，如何将转换完的公式DOM，重新转换回LaTeX字符串？

### ISSUE THREAD

**Issue by wcdxhl0117** [mathjax/MathJax#2040]
请问，如何将转换完的公式DOM，重新转换回LaTeX字符串？

**Comment by dpvc** [comment]
> How can I convert the converted formula DOM back to LaTeX strings?

See [this MathJax forum post](https://groups.google.com/d/msg/mathjax-users/x6XVkwp8i0o/nyP7uvFuCgAJ)
