### ISSUE TITLE
Support TeX-in-<math>-tags, a la Wikipedia's math markdown

### ISSUE THREAD

**Issue by Quuxplusone** [mathjax/MathJax#2043]
I don't trust myself never to write `$$` or `\[` by accident (in a non-math context) on my blog, so I'd like to see MathJax support Wikipedia-style markdown for math:

    Inline as <math>1+2=3</math> or out-of-line as
    <math mode=display>
        1+2 = 3
    </math>

The docs for `tex2jax` indicate that `tex2jax` cannot handle delimiters with angle brackets in them, and I've verified that that's the case. However, `mml2jax` can handle `<math>` tags just fine, and I have managed to make a patch that implements the above-requested behavior.

**Comment by dpvc** [comment]
See #2042 for a discussion of this issue.
