### ISSUE TITLE
hybrid app device back button can't work on android

### ISSUE THREAD

**Issue by Rick-Lewis** [mathjax/MathJax#2047]
angularjs + onsenui + mathjax + cordova, device back button can't work when using mathjax,  need help, thanks

**Comment by dpvc** [comment]
You really haven't given us enough information to give you much advice.  You haven't said anything about your configuration, nor about why you think MathJax is the source of the problem.  MathJax shouldn't have anything to do with the navigation buttons, so I don't see how it could be a MathJax issue.  Without more information (e.g., access to a page that exhibits the problem), I don't see how we can help.
