### ISSUE TITLE
\color and \text together, will not render.

### ISSUE THREAD

**Issue by w32zhong** [mathjax/MathJax#2048]
I have this formula that will not render, but if you remove the color command, it will render.
$\tau_{\color{Green}\text{rms}}$

KaTeX will render it correctly.

Environment:
```
MathJax.js v2.7.5
AsciiMath Input Jax v2.7.5
MathML Input Jax v2.7.5
TeX Input Jax v2.7.5
CommonHTML Output Jax v2.7.5
PreviewHTML Output Jax v2.7.5
mml Element Jax v2.7.5
AssistiveMML Extension v2.7.5
MathEvents Extension v2.7.5
MathMenu Extension v2.7.5
MathZoom Extension v2.7.5
TeX/AMSmath Extension v2.7.5
TeX/AMSsymbols Extension v2.7.5
TeX/noErrors Extension v2.7.5
TeX/noUndefined Extension v2.7.5
accessibility-menu Extension v1.5.0
asciimath2jax Extension v2.7.5
fast-preview Extension v2.7.5
mml2jax Extension v2.7.5
tex2jax Extension v2.7.5
Chrome v67.0.3396.99
```

**Comment by dpvc** [comment]
The default `\color` comment in MathJax does not work quite the same as in LaTeX.  It takes two arguments, the first being the color and the second being the thing to be colored, whereas the LaTeX `\color` macro takes one argument (the color), and makes everything that follows it be in that color.   Therefore, in MathJax, your expression acts essentially like

    \tau_{\color{Green}{\text}{rms}}

where only `\text` is the second argument, and when that `\text` is processed, it has been separated from its argument, causing the "missing argument" error that you are getting.  So one solution would be to brace the second argument to `\color`, as in

    \tau_{\color{Green}{\text{rms}}}

Alternatively, you can load the color extension to get a LaTeX-compatible version of `\color`.  Either add it to your configurations TeX extensions list, or use `\require{color}` within the first math expression that needs color:

    \require{color}
    \tau_{\color{Green}\text{rms}}

Either one will work.
