### ISSUE TITLE
Linebreaks are not rendered at first

### ISSUE THREAD

**Issue by louisabraham** [mathjax/MathJax#2049]
This code

``` html
<script type="math/tex">\textrm{solution((}\\
~~~~(\textrm{5, ((1, 3), (2, 3), (3, 4), (2, 5), (5, 4)), (1, 5)),}\\
~~~~(\textrm{5, ((1, 3), (2, 3), (3, 4), (2, 5), (5, 4)), (1, 2, 5))}\\
)\textrm{)}</script>
```

renders as expected, but only after a delay. During this delay, the output does not include the newlines 
and it messes with the width of the page on mobile devices.

**Comment by louisabraham** [comment]
My immediate fix:

``` html
<script type="math/tex; mode=display">% <![CDATA[
\begin{align}&\textrm{solution((} \\
&~~~~\textrm{(5, ((1, 3), (2, 3), (3, 4), (2, 5), (5, 4)), (1, 5)),} \\
&~~~~\textrm{(5, ((1, 3), (2, 3), (3, 4), (2, 5), (5, 4)), (1, 2, 5))} \\
&\textrm{))}\end{align} %]]></script>
```

**Comment by dpvc** [comment]
If the delay is 10 to 15 seconds, then it may be that one of MathJax's components isn't loading properly (or isn't signaling the it is loaded), and MathJax is waiting for it to do so and eventually timing out.

It may also be that you are seeing the "fast preview" temporarily as the full typesetting is being performed, in which case that is normal.  The fast preview is only a "rough and ready" version of the math, and it doesn't support all features (in particular, line breaking).  You can disable the fast preview using 

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  "fast-preview": {disabled: true}
});
</script>
```
just *before* the script that loads MathJax.js itself.

On the other hand, it just may be the normal delay in loading the components and MathJax doing its processing.  Without seeing the actual page, it is not easy to tell.

**Comment by dpvc** [comment]
PS, it is not clear to me why you are using MathJax for this layout in any case.  Since everything is enclosed in `\textrm{}`, why not just format this using HTML instead?
