### ISSUE TITLE
Mathjax on Mkdocs: Tried to write more data than Content-Length

### ISSUE THREAD

**Issue by vict0rsch** [mathjax/MathJax#2066]
I unpacked the 2.7.4 release archive and load `MathJax.js` in Mkdocs. 

The server returns this error: 

```
Uncaught exception GET /js/unpacked/extensions/MathMenu.js?V=2.7.5 (127.0.0.1)
...
HTTPOutputError: Tried to write more data than Content-Length
```

[I asked the question on SO](https://stackoverflow.com/questions/52624102/local-mathjax-with-mkdocs) but got no answer.

Cheers

**Comment by pkra** [comment]
This sounds like an issue with mkdocs or a webserver, not MathJax.

**Comment by Vict0rSch** [comment]
Ok, question then, what part of the archive are actually needed for the package to run locally?

At least `MathJax.js` but also `MathMenu.js`? others?

Thanks

**Comment by pkra** [comment]
> Ok, question then, what part of the archive are actually needed for the package to run locally?

For full features and compatibility, all of it. But if you restrict that you can remove much of it, cf. https://github.com/mathjax/MathJax-grunt-cleaner
