### ISSUE TITLE
formulas and matrices are shown in one long line in chrome - backslash problem

### ISSUE THREAD

**Issue by phymalidoust** [mathjax/MathJax#2070]
I have written some formulas and matrices in an .md file. They work OK on my desktop Editor. Look like this:

<img width="822" alt="screen shot 2018-10-18 at 18 05 18" src="https://user-images.githubusercontent.com/41995552/47168154-73bc9680-d300-11e8-92ca-48f5a8b1b124.png">

When I upload to the github, and open using chrome with MathJax extension, it shows all the formulas and matrices in a single line. Like this:

<img width="891" alt="screen shot 2018-10-18 at 18 08 24" src="https://user-images.githubusercontent.com/41995552/47168360-f9d8dd00-d300-11e8-8e2b-28e91f60fd54.png">

It looks like Backslashes are not properly interpreted. When I right-click on the formula on github page and click "Show Math as Tex Commands" I see that most of the Backslashes are lost. Like this:

<img width="758" alt="screen shot 2018-10-19 at 09 54 53" src="https://user-images.githubusercontent.com/41995552/47205025-20d8f280-d385-11e8-9481-4432e7fc8b2b.png">

How should I resolve the issue? I restarted the chrome and things but it didn't help. Also, I use Mac OSX.

**Comment by mark-wiemer** [comment]
I believe you have to double the backslashes to escape them: For each line break, instead of writing "\\", write "\\\\" (four backslashes). See https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents for more info
