### ISSUE TITLE
Speech Rule Engine and Commas

### ISSUE THREAD

**Issue by garagebrewer** [mathjax/MathJax#2076]
I'm using the AM_SVG configuration with math that is normal numbers with commas as the "thousands" separator.  `1,234,567` is read as "one comma two hundred thirty four comma five hundred sixty seven".  I'm surprised that it's not ready "one million two hundred thirty four thousand five hundred sixty seven".  I'm not sure if I should report this here or over at the SRE project (or if I should do this a different way or if it's configurable).

**Comment by dpvc** [comment]
This is the correct rendering for `1,234,567`, which MathJax (and TeX) treats as a list of three numbers, `1`, `234`, and `567`.  To get what you are looking for, you must use `1{,}234{,}567` as you would in TeX to get a single number rather than a list.  How that number with commas is actually spoken may depend on the screen reader you are using.  @zorkow, is there anything more to be said, here?

**Comment by garagebrewer** [comment]
I am locked into AsciiMath.  Is there an AM equivalent to your TeX solution?

**Comment by dpvc** [comment]
Unfortunately, I don't know a good solution in that case.  I gave a partial answer at

	https://stackoverflow.com/a/46383402/502334 <https://stackoverflow.com/a/46383402/502334>

that might be sufficient for your purposes.  To do better would require leaving some sort of marker in the math at the place where the number that has had commas removed is, and looking for that to put the comma back in (and remove the marker).  It could be done, but is clunky.

Davide

**Comment by dpvc** [comment]
Unfortunately, I don't know a good solution in that case.  I gave a [partial answer]((https://stackoverflow.com/a/46383402/502334) on StackOverflow that might be sufficient for your purposes.  To do better would require leaving some sort of marker in the math at the place where the number that has had commas removed is, and looking for that to put the comma back in (and remove the marker).  It could be done, but is clunky.

Davide
