### ISSUE TITLE
when the equation is too long, mathjax can't render the equation

### ISSUE THREAD

**Issue by cw1997** [mathjax/MathJax#2085]
when the equation is too long, mathjax can't render the equation.
for example:
	
```
$$ 
\lim\limits_{x \to \infty }{ \frac{ a_0x^m + a_1x^{m-1} + ... + a_m }{ b_0x^n + b_1x^{n-1} + ... + b_n } } =$\left\{\begin{array}{rcl}\frac{a_0}{b_0} & & {n=m}\\0 & & {n>m}\\\infty & & {n<m}\end{array} \right.
$$
```
mathjax can't render the equation in this page
https://blog.changwei.me/2018/11/27/%E6%9E%81%E9%99%90%E7%9A%84%E8%BF%90%E7%AE%97%E6%B3%95%E5%88%99/

**Comment by pkra** [comment]
See https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents

**Comment by dpvc** [comment]
In particular, your content management system seems to be using backslashes as escape characters for the special characters it uses.  In particular, `\{` is being converted to `{` while `\\` is being converted to `\`.  You probably should double all backslashes in your mathematics.  So use

```
$$ 
\\lim\\limits_{x\\to\\infty }{\\frac{a_0x^m + a_1x^{m-1} + ... + a_m}{b_0x^n + b_1x^{n-1} + ... + b_n}} =$\\left\\{\\begin{array}{rcl}\\frac{a_0}{b_0} & & {n=m}\\\\0 & & {n>m}\\\\\\infty & & {n < m}\\end{array} \\right.
$$
```

instead.

**Comment by cw1997** [comment]
wow, thanks very much!!!
