### ISSUE TITLE
Updiagonalstrike rendering issue in CommonHTML

### ISSUE THREAD

**Issue by drlippman** [mathjax/MathJax#2088]
There seems to be a minor issue with the placement of the `updiagonalstrike` in some complex fractions using CommonHTML (the display is accurate using the HTML+CSS renderer).  See this rendered equation for an example:

![image](https://user-images.githubusercontent.com/190505/49172773-c83b3480-f2f6-11e8-8f50-9c345758a541.png)

The AsciiMath generating this is 
`(1*(x+2)+1/cancel((x+2))*cancel((x+2)))/(x/cancel((x+2))*cancel((x+2))-3*(x+2))`

If it would be helpful to paste in the generated MathML as well, let me know.  

This was generated by MathJax 2.7.5 loaded via CDN.

**Comment by drlippman** [comment]
Thanks!

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/Presentation/GeneralLayout/menclose/issue2088.html
