### ISSUE TITLE
Switch Renderer on iOS

### ISSUE THREAD

**Issue by goerz** [mathjax/MathJax#2092]
As a workaround to #2091, presumably one should switch to the SVG render (which in any case always looks much better than the default HTML-CSS; I don't really understand why SVG is not the default). However, since I cannot do a right-click on an equation (and tap-and-hold doesn't do anything), I haven't figured out any way to switch the renderer. Is there any possibility to do this? Maybe something like a bookmarklet?

**Comment by goerz** [comment]
Alternatively, is there anything I can do server-side to force SVG output? I thought that maybe `"jax": ["input/TeX", "output/SVG"]` in `MathJax.Hub.Config` would do this, but it doesn't seem so. What does that option do, actually?

**Comment by goerz** [comment]
Just found out about the double tap and hold gesture.

**Comment by dpvc** [comment]
Glad you found the correct gesture.  To answer your question about forcing SVG output, that is usually determined by the configuration file you load.  Your page (used to) use `config=TeX-AMS-MML_HTMLorMML` (it has been changed recently, so I might not be correct about which one it used to use).  The `HTMLorMML` is the part that determines the output format (in this case, it will be HTML-CSS`.  If you used `config=TeX-AMS_SVG`, that would use TeX input and SVG output.  

Your current page no longer loads a combined configuration file, and so the `jax` array that you have in your configuration will control that.  The setup you have now is correct (except that you should put the configuration script *before* the script that loads `MathJax.js`, as some older browsers will not see the configuration until it is too late if it comes afterward), but there is a drawback to this approach, which is that MathJax will have to load each component separately, so there are multiple network requests.  With the combined configuration file, most of the needed components will be loaded in one network request, which is more efficient, in general.
