### ISSUE TITLE
how to enable mathjax error messages

### ISSUE THREAD

**Issue by fardina** [mathjax/MathJax#2097]
I would like to enable error messages in my configuration for mathjax so that when write `$x^$ ` then this message appear: `missing superscript or subscript arguments`. At the moment it doesn't work for me. I tried looking for that in http://docs.mathjax.org but unfortunately I didn't find it. Any help about will be appreciated.

**Comment by dpvc** [comment]
Add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: {noErrors: {disabled: true}}
});
</script>
```

to your page just *before* the script that loads `MathJax.js` itself.  That will disable the `noErrors` extensions, which is what prevents the messages from being displayed.

**Comment by fardina** [comment]
@dpvc Thank you very much. That's exactly what I was looking for.
