### ISSUE TITLE
xrightarrow in array broke going from 2.6 to 2.7

### ISSUE THREAD

**Issue by keithharbaugh** [mathjax/MathJax#2104]
\xrightarrow, and other extensible arrows, when elements of an array, worked okay in 2.6 but gives Math Processing Error in 2.7. 
An example using 2.6 is: http://kwhmath.blogspot.com/2013/03/2-as-boolean-subobject-classifier.html
The same, using 2.7 is: http://kwhfoobartemp.blogspot.com/2018/12/mathjax-27-2-as-boolean-subobject.html 
For a file which demonstrates the problem is specific to xrightarrow in an array, see the top item in the table in: http://kwhfoobartemp.blogspot.com/2018/12/mathjax-test-2-as-boolean-subobject.html 
The same behavior is found using browsers Chrome Version 71.0.3578.98 (Official Build) (64-bit)
and Firefox 53.0 (32-bit), 
running Microsoft Windows Version 6.1 (Build 7601: Service Pack 1)

**Comment by dpvc** [comment]
Thanks for the report.  I will look into the problem and see what I can find.

**Comment by dpvc** [comment]
OK, I see that your blog is using version 2.7.1, but this error seems to have been fixed in 2.7.2.  The current version is 2.7.5.  Can you update to a more current version?

**Comment by keithharbaugh** [comment]
Surprised to see reference to 2.7.1.
The mathjax info is set in the blog's "Theme", which for kwhfoobartemp.blogspot.com contains
<script async='async' src='https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML-full' type='text/javascript'>
</script>
Looking at the page source for 
http://kwhfoobartemp.blogspot.com/2018/12/mathjax-27-2-as-boolean-subobject.html 
shows the same script.
By the way, in my production blog kwhmath.blogspot.com, 
the theme, in order to circumvent the problem, contains 
<script async='async' src='https://cdn.mathjax.org/mathjax/2.6-latest/MathJax.js?config=TeX-AMS_CHTML-full' type='text/javascript'>
</script>
which also shows in the page source for that blog's web pages.

**Comment by dpvc** [comment]
The MathJax CDN was decommissions almost two years ago (see the [announcement](https://www.mathjax.org/cdn-shutting-down/)), and we encouraged users to move to one of several other CDNs that deliver MathJax.  The `cdn.mathjax.org` site still forwards to one of those at the then-current version of 2.7.1.  That is why you are getting that version.

You should move to `cdnjs` or one of the other servers (other than `rawgit.com`, which is going off line later this year) in order to get more current versions of MathJax.  Load `latest.js` rather than `MathJax.js` to get the most current version (see the [documentation](http://docs.mathjax.org/en/latest/start.html#using-a-content-delivery-network-cdn) for more details).

**Comment by GerHobbelt** [comment]
When I test a copy (grab) your TeX content from the example pages you referenced with a local MJ setup, I notice the MathJax config section from your example pages loads the `AMScd` extension, but not the `AMSsymbols` extension.

When that extension is not mentioned my (modified!) MathJax 2.7.5 produces this error for each of the TeX formulas that error in your example pages:  

```
Undefined control sequence \lrcorner
```

or

```
Undefined control sequence \rightarrowtail
```

I'm not sure the error path is the same as yours as your example pages, but that's easily checked by adding the `AMSsymbols` extension to your MathJax config setup code like this:

``` 
  MathJax.Hub.Config({
    extensions: [
      "tex2jax.js",
      "FontWarnings.js",
    ],
    jax: ["input/TeX", "output/CommonHTML"],
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
      displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
      processEscapes: true
    },
    TeX: {
      extensions: [
        //"AMScd.js",     //  <-- isn't needed; does not impact output here either way
        "AMSsymbols.js",    // <-- with this added, the errors go away in my (edited) copy.
      ],
      ...
```

HTH

**Comment by keithharbaugh** [comment]
Thanks very much for your past insights on what caused the problem. 
Updating to 2.7.5, at cloudflare, solved those problems. 
But now, reviewing some of my older files, a further, probably related, problem has been noticed. 
See the file:
http://kwhmath.blogspot.com/2014/01/test2.html
When viewed using 2.6.1, everything displays fine, in particular the simplified mathjax code:
\\[
\begin{array}{}
\xrightarrow{\textstyle f K Q K} \atop \xrightarrow{\textstyle f K Q K} 
\end{array} 
\\]
When viewed using 2.7.5, this last gives a [Math Processing Error].
Another example shows that \atop as an array element works fine;
the problem arises when using \xrightarrow inside \atop inside an array,
but in 2.7.5, not in 2.6.1.

**Comment by dpvc** [comment]
OK, I can confirm the problem in CommonHTML output (but not the other formats).  You could change to SVG output as a workaround for now until it is fixed.

**Comment by keithharbaugh** [comment]
Fascinating. I never did that before, always sticking to CHTML -- and checking how things looked there (generally quite satisfactory). I'll take a look at SVG.

**Comment by dpvc** [comment]
The CommonHTML output has a rather fragile means of locating the elements that contain stretchable characters once the size need for the character is known (and replacing the original version of the character by the correctly sized one).  This code has caused problems in the past, and is probably the source of the problem, here, as well (though I haven't looked yet to make sure).

Needless to say, that code is completely replaced in the version 3 rewrite that is nearing completion.

**Comment by keithharbaugh** [comment]
I can easily work around this problem; if it is not fixed until 3.0 that is fine with me. 
BTW, is there a tutorial somewhere on how to get more specific information on what went wrong than just "[Math Processing Error]"? I'm using Chrome. A control panel? Console? It's not worth you all writing such a thing, but if such already exists it would be nice to know about.

**Comment by dpvc** [comment]
> is there a tutorial somewhere on how to get more specific information on what went wrong than just "[Math Processing Error]"?

If you right-click (or CTRL-click on a Mac) on the `[Math Processing Error]`, you should get the MathJax contextual menu; the "Show Math As" submenu should include "Error Message" as an option, and if you select that, you should get the main error message.  There will also be a message that says you can look at `MathJax.Hub.lastError` in the browser console for the Error object associated with the last expression that produced a math processing error.  So `MathJax.Hub.lastError.stack` should get you the stack trace, for example.  This would be more meaningful if you are using the `unpacked` version of MathJax, rather than the minified one.

**Comment by dpvc** [comment]
This is fixed in v3.
