### ISSUE TITLE
Character Replacement Macro

### ISSUE THREAD

**Issue by GalAster** [mathjax/MathJax#2106]
Is there a simple pre-process for string replacement?

For example, I want to replace `<=` with `\leq`

I've tried setting Macros or using `\def` but still can't recognize `<=` or `\<=`.

**Comment by dpvc** [comment]
You can use a TeX Input Jax pre-filter to do this.  For example, you can add

```
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("TeX Jax Ready", function () {
  MathJax.InputJax.TeX.prefilterHooks.Add(function (data) {
    data.math = data.math.replace(/<=/g, '\\leq')
                         .replace(/>=/g, '\\geq');
  });
});
</script>
```

to your page just **before** the script that loads MathJax.js to add a filter that replaces `<=` with `\leq` and `>=` with `\geq`.  You can add other replacements as needed.

Note that this issue tracker is really for reporting *bugs* in MathJax, not for asking general questions.  That is better handled in the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see your question.
