### ISSUE TITLE
mhchem 3.3.0 won't work in some legacy browsers

### ISSUE THREAD

**Issue by drify** [mathjax/MathJax#2110]
https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/mhchem3/mhchem.js#L200
```
if (Array.isArray(b)) ...
```
`Array.isArray` was added in ES5 and some of the oldest browsers won't support it ([See the compatibility table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Browser_compatibility)). [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#Polyfill) it and all goes well. (Tested on IE8)

**Comment by pkra** [comment]
Please file this issue upstream at https://github.com/mhchem/MathJax-mhchem (though be prepared  that people might no longer care to support IE8 given its security vulnerabilities).

**Comment by drify** [comment]
@pkra Thank you very much for your reply! 
I had found another problem that MathJax 2.7.5 doesn't contain the minified version of mhchem 3.3.0 and made a pull request https://github.com/mathjax/MathJax/pull/2109 for it. Would you mind checking it as well?

**Comment by pkra** [comment]
@drify I'm just a community member. But minification happens at releases time so the problem probably lies in mathjax-dev. As a workaround, I would pull in mhchem from elsewhere (e.g., from cdnjs).

**Comment by drify** [comment]
See https://github.com/mhchem/MathJax-mhchem/commit/ec725a7183203d8021496c74ec078b78f79cc649. The problem was fixed.
