### ISSUE TITLE
"Zoom Factor" is ignored on Firefox 64

### ISSUE THREAD

**Issue by Kodiologist** [mathjax/MathJax#2113]
Since upgrading to Firefox 64 (on Linux), I've noticed that MathJax objects seem to stay the same size regardless of the "Zoom Factor" setting, even if I switch renderers. This makes me sad, since I have low vision and Stack Exchange's default size for its MathJax objects is too small for me to see easily.

**Comment by dpvc** [comment]
I think you may be setting the wrong value.  The Zoom Factor is for the pop-up zooming (you have to use the Zoom Trigger on the expression to activate it).  If you want to enlarge all the math on the page (in place), then you need to use the "Scale all Math" item two items below that.

See if that does what you are looking for.

**Comment by Kodiologist** [comment]
Oh, that works. I was used to "Zoom Factor" having that effect, perhaps because that's how it worked in previous versions. Thanks!
