### ISSUE TITLE
Failed to render minus after power

### ISSUE THREAD

**Issue by willy1920** [mathjax/MathJax#2117]
this is one of the demo \(ax^2 + bx + c = 0\) it will render correctly but after I add minus next after power \(ax^-2 + bx + c = 0\) two in not at superscript but only minus at superscript

**Comment by zorkow** [comment]
This is expected LaTeX behaviour as you need to write 
```TeX
x^{-2}
```
for a multi-character superscript to disambiguate the notation. For more details also see here:
https://en.wikibooks.org/wiki/LaTeX/Mathematics#Powers_and_indices
