### ISSUE TITLE
Tell MathJax to only process specific nodes

### ISSUE THREAD

**Issue by geajack** [mathjax/MathJax#2118]
Only certain HTML nodes in my site actually contain LaTeX, so I'd like to be able to tell MathJax to only process those. What I'd like to be able to do is something like this:

```
<script>
    MathJax.Hub.Config({
        tex2jax: {
            restrict: document.getElementsByTagName("article")
        }
    });
</script>
```

But instead, the only way I could get the result I want is

1. Add a class to the `<body>` - "nomathjax" or something.
2. Use the `ignoreClass` property to exclude the whole page.
3. Add a class to the `<article>` tags like "yesmathjax".
4. Use the `processClass` property to include those tags back in.

It's steps (2) and (4) that bother me. My HTML is mine. I'm finicky about it. I've got it nice and clean and minimal, just the way I like it. I don't want to have to add meaningless CSS classes to it just because a library I'm using needs me to. Actually, in my particular use case, it's impossible for me to do that - I can't modify the page body, all I can do is insert <script> tags into the head. 

I don't want to modify my markup, but what I do know - what absolutely anybody who ever wants to restrict MathJax to certain parts of their site knows - is which tags I want to apply MathJax to, and how to get a list of them with Javascript. That should be enough.

Perhaps there's a way of doing this that I'm missing?

**Comment by dpvc** [comment]
You can use
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        elements: document.getElementsByTagName("article")
    });
</script>
(and it must be placed BEFORE the script that loads MathJax.js itself).  This will restrict MathJax typesetting operations to the contents of the specified elements.  It is a global property because it applied to ALL preprocessors.

Davide

**Comment by geajack** [comment]
Awesome! I've been waist-deep in docs about Queues and pre processors for the past hour. The Google results on this topic really seemed to suggest there was no way of doing it other than `processClass`. Time to update some StackOverflow threads, I guess.

**Comment by nitely** [comment]
The problem with @dpvc solution is that it if no elements are found, then mathjax will fallback to the default behaviour of trying to process the entire DOM.

**Comment by geajack** [comment]
> The problem with @dpvc solution is that if no elements are found, then mathjax will fallback to the default behaviour of trying to process the entire DOM.

Is there a way around that?

**Comment by nitely** [comment]
Sure, a hack like passing an array of a single dummy node (i.e
[document.createElement('div')) if there are no matches (i.e nodes.length
=== 0). But mathjax could make passing null mean don't process anything to
make this less hackish, without a breaking change (altough a better api
would do the opposite, null process all and empty array process nothing).
My 2c

**Comment by dpvc** [comment]
One possible way to handle the case where there might be no elements of the given type is the following:

```
<script type="text/x-mathjax-config">
(function () {
  var articles = document.getElementsByTagName("article");
  MathJax.Hub.Config({
    elements: articles,
    skipStartupTypeset: (articles.length === 0)
  });
})();
</script>
```

**Comment by JamesTheAwesomeDude** [comment]
How is this to be done with the v3 config?

**Comment by dpvc** [comment]
@JamesTheAwesomeDude:

> How is this to be done with the v3 config?

``` javascript
MathJax = {
  startup: {
    elements: ['article']
  }
};
```

See the [Startup Options](https://docs.mathjax.org/en/latest/options/startup/startup.html?highlight=elements) documentation for details.
