### ISSUE TITLE
Autonumbering failed for align* math block

### ISSUE THREAD

**Issue by abnerlee** [mathjax/MathJax#2120]
demo: https://codepen.io/anon/pen/VgVRbZ

autoNumber fails for 
```
\begin{align*}
y(x) &= x^2\\
&= 5\\
& = z
\end{align*}
```

using

```
\begin{align}
y(x) &= x^2\\
&= 5\\
& = z
\end{align}
```

won't have the issue.

**Comment by dpvc** [comment]
This is the correct behavior.  The star at the end of the environment name indicates that the equation numbers should be suppressed.  See [this post](https://tex.stackexchange.com/questions/9514/whats-the-difference-between-align-and-align) for details.  The upshot is that `align` includes numbers, but `align*` does.  MathJax properly implements this.
