### ISSUE TITLE
MathML from Wiries not displayed in the right way

### ISSUE THREAD

**Issue by enkelmedia** [mathjax/MathJax#2121]
Hi!

I'm having an issue after upgrading to the latest version of Wiris/MathType, after the upgrade they no longer add a `<mrow>` to the expression. And with this the rendering with MathJax does not work.

I've validated the generated MathML and it looks valid, but it does not render correct, see this:
https://jsbin.com/nucupom/edit?html,output

I'm not sure where to start, is this an issue with Wiris or should MathJax be able to render this?

**Comment by pkra** [comment]
As usual, that's unfortunately the correct rendering.

From the spec https://www.w3.org/Math/draft-spec/mathml.html#chapter5_mixing.elements.semantics

> The default rendering of a semantics element is the default rendering of its first child. 

You might want to file a bug with WIRIS to fix their MathML output.

**Comment by enkelmedia** [comment]
Thanks for letting me know!
