### ISSUE TITLE
Question: How to find out whether ``MathJax.Hub.Queue(["Typeset", MathJax.Hub]);`` rendered anything?

### ISSUE THREAD

**Issue by klieret** [mathjax/MathJax#2122]
Hi,

I am using ``MathJax`` on a page that dynamically loads content, so I am issuing  ``MathJax.Hub.Queue(["Typeset", MathJax.Hub]);`` several times with a certain delay until I am convinced that no new elements appear on the page.

To optimize that, I would like to find out whether the last call  ``MathJax.Hub.Queue(["Typeset", MathJax.Hub]);`` rendered any new element.

Is there any possibility to do this?

Cheers,
Kilian

**Comment by dpvc** [comment]
Do you control the process that is loading the pages?  It would be better to link into that process to determine when the page is completely loaded and then run MathJax.

If not, then one possible approach would be to count the number of equations before typesetting, and then check the number afterward and see if they are different.  E.g.,

```
function () {
  var eqnCount;
  MathJax.Hub.Queue(
    function () {
      eqnCount = MathJax.Hub.getAllJax().length;
    },
    ["Typeset", MathJax.Hub],
    function () {
      if (eqnCount === MathJax.Hub.getAllJax().length) {
        // no new math was processed; do whatever you need here.
      }
    }
  );
})();
```

**Comment by klieret** [comment]
Thanks a lot for helping me out on this one!

Yes, for the most part I have hooks that trigger a MathJax-rerendering, however so far there were still cases where some unrendered formulas were left over, so I want to implement a workaround for this (until a proper solution is found). But I totally agree that this is only a workaround.

Thanks a lot for your solution! This is just what I was looking for!
