### ISSUE TITLE
mglyph in scripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2124]
If an mglyph's dimensions are given in relative units (e.g., em), the mglyph's dimensions are not affected by scriptlevels, e.g.,

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">  <mi>x</mi>     <mglyph src="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMTAwIDEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIvPgo8L3N2Zz4=" width="1em" height="1em" valign="-0.33em"></mglyph></math>
```

and 

```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">   <msub>     <mi>x</mi>     <mglyph src="data:image/svg+xml;base64,PHN2ZyB2aWV3Qm94PSIwIDAgMTAwIDEwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8Y2lyY2xlIGN4PSI1MCIgY3k9IjUwIiByPSI1MCIvPgo8L3N2Zz4=" width="1em" height="1em" valign="-0.33em"></mglyph>   </msub> </math>
```

both give identically sized circles.

This seems counterintuitive if mglyph's are thought of as non-Unicode glyphs (which is where we ran into this).

**Comment by dpvc** [comment]
OK, this was properly handled in CHTML, but not HTML-CSS or SVG.  I've made a PR (#2125) to resolve the issue.

**Comment by pkra** [comment]
Thanks for looking into it.

**Comment by dpvc** [comment]
In testsuite:

MathMLToDisplay/Presentation/TokenElements/mglyph/issue2124.html
