### ISSUE TITLE
Bug: wrong display of sans serif bold italic characters

### ISSUE THREAD

**Issue by balagge** [mathjax/MathJax#2126]
### Issue Summary

MathML rendering: characters in the range A .. Z, a ... z, Α (alpha) .. Ω, α, ..., ω are rendered incorrectly if **sans-serif, bold and italic** requested. There are 2 different scenarios, both of which produce incorrect results:

(1) setting the `mathvariant` attribute (and using Unicode BMP characters), examples:

```
<mi mathvariant = "sans-serif-bold-italic">x</mi>
<mi mathvariant = "sans-serif-bold-italic">S</mi>
<mi mathvariant = "sans-serif-bold-italic">&#x03C8;<!--GREEK SMALL LETTER PSI--></mi>
<mi mathvariant = "sans-serif-bold-italic">&#x03A9;<!--GREEK CAPITAL LETTER OMEGA--></mi>
```

- error for latin letters:  the bold attribute is not rendered. (sans-serif and italic OK)
- error for greek letters: the bold & sans-serif attribute is not rendered (italic is OK)

(2) using a Mathematical Alphanumeric Symbol (Unicode SMP character), example:
```
<mi>&#x1D66D;<!--MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X--></mi>
<mi>&#x1D64E;<!--MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S--></mi>
<mi>&#x1D7C1;<!--MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PSI--></mi>
<mi>&#x1D7A8;<!--MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMEGA--></mi>
```
- error (both for latins and greeks) the italic attribute is applied twice (character slants abnormally)

### Expected behavior

whether specifying by the `mathvariant` attribute, or using an actual Mathematical Alphanumeric Symbol, sans-serif + bold + italic characters should be rendered as such. Check Firefox built-in mathml renderer, which renders these characters correctly.

Note: the scenario (2) above is probably due to the "single character is italic by default" rule. This can be checked by comparing single-letter identifiers with multi-letter identifiers. compare:

```
<mi>&#x1D66D;<!--xMATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X--></mi>
```
, which renders incorrectly (italicized twice), vs.

```
<mi>
  &#x1D66D;<!--xMATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X--></mi>
  &#x1D66D;<!--xMATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X--></mi>
<\mi>
```
, which renders normally.

### Notes

All renderers (CSS, HTML, HTML preview, SVG) behave the same way.

**Comment by pkra** [comment]
This depends on which font you are using. Read the docs at https://docs.mathjax.org/en/latest/font-support.html#character-fallbacks for what the fallback chain looks like (or read the many questions on the user group about it).

**Comment by dpvc** [comment]
These issues have been resolved.  MathJax now maps Greek letters to their Math Alphanumeric positions (when there is one for the given mathvariant), and calls on system fonts if the needed character is not in the MathJax fonts.
