### ISSUE TITLE
Implement display mathematics for AsciiMath

### ISSUE THREAD

**Issue by iovuio** [mathjax/MathJax#2128]
There are two display options for TeX content:

* in-line mathematics - delimiters $...$, \\(...\\)
* display mathematics (centered, clear both) - delimiters $$...$$, \\[...\\]

However for AsciiMath only the inline version is available - delimiters \`...\`

It would be nice to have  display mathematics version for AsciiMath also - \`\`...\`\` delimiters maybe.

Currently, in order to achieve the _display mathematics_ effects for AsciiMath content requires one to intervene at markup level
```
<p style="text-align:center">
  `x = (-b +- sqrt(b^2-4ac))/(2a) .`
</p>
```

When it comes to tools that use MathJax (e.g. Asciidoctor) the user has no access to the markup and the desired effect cannot be achieved.

AsciiMath is arguably more beginner friendly, learning TeX for this reason alone goes hard on the user.

**Comment by dpvc** [comment]
The AsciiMath notation does not have a mechanism for distinguishing in-line from displayed math, like TeX does.  Indeed, its output is a hybrid of the two, as it uses the equivalent of `\displaystyle` for the math it lays out (at least by default), but as an in-line expression.  The intention (I assume) was that the rest of the page layout would be used to handle things like centering, as you have done in your example above.

There is a [discussion](https://groups.google.com/d/msg/mathjax-users/CvM6tE0m3Rg/Mt1x3I3YQf8J) in the MathJax user's forum about one possible way to extend AsciiMath to include notation for both in-line and display math formats.

**Comment by iovuio** [comment]
Thank you @dpvc,
You provided all the  information needed to fix the issue downstream. 
Closing issue.
