### ISSUE TITLE
$<a$ render failure

### ISSUE THREAD

**Issue by WenHuayu** [mathjax/MathJax#2130]
a can be any letter.

**Comment by pkra** [comment]
See https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents

**Comment by WenHuayu** [comment]
> See https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-in-html-documents

thanks

**Comment by dpvc** [comment]
Duplicate of #2116 and #2044, among others.
