### ISSUE TITLE
Support \textup

### ISSUE THREAD

**Issue by varkor** [mathjax/MathJax#2133]
`\textup{text}` renders text that is always upright (i.e. not italicised), regardless of its content.

**Comment by dpvc** [comment]
In MathJax, `\textrm{}` will do that, and you can define `\textup` to be equivalent to `\textrm` if you need it.  MathJax is mostly about typesetting mathematics, and has limited support for text-mode commands like this.

**Comment by dpvc** [comment]
This was added in v3.2.
