### ISSUE TITLE
Matrices show as  'Unknown node type: matrix'

### ISSUE THREAD

**Issue by ogregames** [mathjax/MathJax#2136]
**### Issue Summary**
For testing of using mathjax 2.6.1 in project we used MathML test expessions from https://www.drillster.com/info/mathml
All of them rendered correctly exept one:
```
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <matrix>
    <matrixrow>
      <cn> 0 </cn> <cn> 1 </cn> <cn> 0 </cn>
    </matrixrow>
    <matrixrow>
      <cn> 0 </cn> <cn> 0 </cn> <cn> 2 </cn>
    </matrixrow>
    <matrixrow>
      <cn> 3 </cn> <cn> 0 </cn> <cn> 0 </cn>
    </matrixrow>
  </matrix>
</math>
```

That must rendered as 
![mathml-matrix](https://user-images.githubusercontent.com/32984302/55547332-c258c400-56d9-11e9-8ea3-0a4f08636442.png)

But it is displayed as 'Unknown node type: matrix':
<img width="212" alt="Screen Shot 2019-04-04 at 1 04 28 PM" src="https://user-images.githubusercontent.com/32984302/55547600-4ca12800-56da-11e9-903b-4fcc1a205915.png">

I had read documentation https://docs.mathjax.org/en/latest/mathjax.html
but didn't find answer.

**### Technical details:**
MathJax Version: 2.6.1 
Client OS: Mac OS X 10.14.3
Browser: not depend on browser

### **Expected result**
Can you confirm that `<matrix>` must render properly by mathjax?
Or maybe I have to add some config props for correct work?

**Comment by pkra** [comment]
See https://docs.mathjax.org/en/latest/mathml.html#content-mathml

**Comment by ogregames** [comment]
Thank you!! It was really fast answer!
