### ISSUE TITLE
Duplicated content when using toggle macro

### ISSUE THREAD

**Issue by EmanuelPrima** [mathjax/MathJax#2137]
Sorry if this is a duplicate, this is my first post and the best I could do was to meet the following questions:

- [Mathjax duplicates content in the print view](https://github.com/mathjax/MathJax/issues/1572).
- [mathjax duplicates and resizes when iframe dynamically changes content](https://github.com/mathjax/MathJax/issues/1619).

---

I am using the source code of this answer:

[Formatting Sandbox (math.meta.stackexchange)](https://math.meta.stackexchange.com/a/13259/525384)

```
$$
\require{action}
\require{enclose}
\toggle{ 
x\cdot 0 = 0\quad\enclose{roundedbox}{\text{ Click this for derivation }}
}{
\begin{array}{rll}
x\cdot 0 
&= \mathtip{x\cdot 0 + 0}{0 \text{ is additive identity}} \\
&= \mathtip{x\cdot 0 + (x\cdot 0 + -(x\cdot 0))}{ -(x\cdot 0) \text{ is additive inverse of } x\cdot 0}\\
&= \mathtip{(x\cdot 0 + x\cdot 0) + -(x\cdot 0)}{ \text{ addition is associative }\;}\\
&= \mathtip{x\cdot(0 + 0) + -(x\cdot 0) }{ \text{ mulitplication is distributive }\;}\\
&= \mathtip{x\cdot 0 + -(x\cdot 0) }{ 0 \text{ is additive identity}} \\
&= \mathtip{0}{ -(x\cdot 0) \text{ is additive inverse of } x\cdot 0}
\end{array}
\quad\quad
\bbox[4pt,border: 1px solid red]{
\begin{array}{l}
\text{If you cannot figure out why a line}\\
\text{is true, move your mouse over}\\
\text{RHS of that line for hint.}
\end{array}}
}\endtoggle
$$
```

and pasting it on this site:

http://rinconmatematico.com/foros/index.php?topic=108597.msg429066#msg429066

The output is fine in math.meta, but in the last site me and other users are getting a **duplicated content** when clicking several times on "Click this for derivation":

![Example 1](https://user-images.githubusercontent.com/40039900/55921592-ca31d000-5bd3-11e9-9983-489d6297245b.png)

![Example 2](https://user-images.githubusercontent.com/40039900/55921598-d453ce80-5bd3-11e9-9555-aa1b0f26ac68.png)

![Example 3](https://user-images.githubusercontent.com/40039900/55921602-d9b11900-5bd3-11e9-8d66-a67706bb2a83.png)

Check the following GIF:

![GIF that represents the problem](https://user-images.githubusercontent.com/40039900/55922123-2b5aa300-5bd6-11e9-9f82-18ad2144780b.gif)

**How can we solve this issue for that page?**

I think it is due to the MathJax version of the site, but I am not sure. Check its MathJax configuration:

![Config of MathJax](https://user-images.githubusercontent.com/40039900/55922339-24806000-5bd7-11e9-9076-828d27f7c751.png)

P.S. The images and the GIF have been taken with Google Chrome (same version for both reference pages), but the problem persists in other browsers (Firefox, Edge, even in the mobile versions).

P.S.2. I am not an admin/mod of the site so I cannot make changes on the site config nor can I provide more information than you have access to, but I can inform them that I have opened an issue and so they read the solution/request that you propose.

**Comment by EmanuelPrima** [comment]
P.S.2. The images and the GIF have been taken with Google Chrome (same version for both reference pages), but the problem persists in other browsers (Firefox, Edge, even in the mobile versions).

**Comment by dpvc** [comment]
The page you linked to includes a function that runs every 100 milliseconds that calls MathJax to typeset the page.  I'm not sure why it is doing that, but I suspect that that loop is interfering with the operation of the toggle that you use to show the complete proof.  I believe that both the toggle and the loop are trying to typeset the expression at the same time, and you get duplicate output.

I do not get duplicate output when I test the expression in other pages, so it does seem to be specific to this site, and I'm afraid that fixing it would require the page author to modify the page not to have that loop.

**Comment by EmanuelPrima** [comment]
> ery 100 milliseco

Thanks for the review, it is very helpful.

OK, so the next step is to find the loop that causes the duplication of the expression. What are the steps to find that loop?

**Comment by dpvc** [comment]
> so the next step is to find the loop that causes the duplication of the expression. What are the steps to find that loop?

The loop is at lines 870 and 871 of the `index.php` page that you linked to above, and consists of

```
window.setInterval(loadPreview, 100);
function loadPreview(){MathJax.Hub.Queue(["Typeset",MathJax.Hub]);}
```

which sets up a repeated call to `loadPreview()` every 100 milliseconds, and the function asks MathJax to typeset the page.

I'm not sure whey this loop is being used.  Perhaps the page author doesn't know how to link into the updating of the page.  The better approach would be to tie into the content-management system's page-maintenance functions so that you only run MathJax when the page is updated.  Running MathJax every 100 milliseconds is very inefficient.

**Comment by EmanuelPrima** [comment]
> > so the next step is to find the loop that causes the duplication of the expression. What are the steps to find that loop?
> 
> The loop is at lines 870 and 871 of the `index.php` page that you linked to above, and consists of
> 
> ```
> window.setInterval(loadPreview, 100);
> function loadPreview(){MathJax.Hub.Queue(["Typeset",MathJax.Hub]);}
> ```
> which sets up a repeated call to `loadPreview()` every 100 milliseconds, and the function asks MathJax to typeset the page.
> 
> I'm not sure whey this loop is being used. Perhaps the page author doesn't know how to link into the updating of the page. The better approach would be to tie into the content-management system's page-maintenance functions so that you only run MathJax when the page is updated. Running MathJax every 100 milliseconds is very inefficient.

When the administration deletes that loop, `toggle` works correctly.

Now, because of the way that page is designed, LaTeX is not compiled in the preview of the messages. You can see the origin of those lines of code by visiting https://www.simplemachines.org/community/index.php?topic=543948.0

If you manage to keep everything as it is until now and correct the `toggle` problem that the page has, it would be great!

P.S. A side comment. Because of the way the page is designed, the math expressions must be enclosed with `[tex][/tex]` tags (which are used for online mathematics or display), and the original LaTeX delimiters also work: `\(\)` for inline and `\[\]` for display.

**Comment by dpvc** [comment]
> When the administration deletes that loop, `toggle` works fine!

Great, glad to hear that that was indeed the issue.

> You can see the origin of those lines of code by visiting ...

I don't see the `setInterval()` anywhere in the mod linked from that page.

> Any requirement please let me know.

The best way to handle the updates would be to have MathJax typeset only when the preview is updated, not every 100 milliseconds all the time.  I don't know the software you are using, and it is not a service that I offer to modify your content-management system to incorporate MathJax.  That is smooth the site administrators will have to handle themselves.

One possible starting point is the [mathjax editor code](https://gist.github.com/gdalgas/a652bce3a173ddc59f66) used by StackExchange.  This might give you some ideas of how to proceed.

**Comment by EmanuelPrima** [comment]
Thanks for worrying, you have already solved the issue.

The `setInterval` part can be found in the reply #10 of the linked question or here: https://www.simplemachines.org/community/index.php?topic=543948.msg3944031#msg3944031

Yeah, I agree with you that it is useless to reload each formula every 0.1 seconds. However, since I am not an admin there I cannot take descisio
