### ISSUE TITLE
TeX Commands opens in a small window

### ISSUE THREAD

**Issue by EmanuelPrima** [mathjax/MathJax#2146]
Lately I have been experiencing a change in the way window "TeX Commands" opens after following steps "Right click on a formula -> Show Math As -> TeX Commands".

Before:

![Before](https://user-images.githubusercontent.com/40039900/57664186-8e709880-75cd-11e9-855e-3feb3d14c867.png)

Now:

![Now](https://user-images.githubusercontent.com/40039900/57664220-a9430d00-75cd-11e9-9a09-d9ff3f35a64b.png)

It is annoying having to be enlarging the window every time I want to see the source code, is there any way to enlarge it by default?

**Comment by dpvc** [comment]
MathJax opens a small window, measures the size of the content, and then resizes the window to accommodate the size.  The code for that is pretty old, and browsers may have changed how they respond to those actions.  In particular, they may no longer allow window resizing under program control, and that may be the reason the window isn't getting larger.

That section of the code should be reviewed and updated to accommodate the current browser behavior.

**Comment by EmanuelPrima** [comment]
> MathJax opens a small window, measures the size of the content, and then resizes the window to accommodate the size. The code for that is pretty old, and browsers may have changed how they respond to those actions. In particular, they may no longer allow window resizing under program control, and that may be the reason the window isn't getting larger.
> 
> That section of the code should be reviewed and updated to accommodate the current browser behavior.

Thanks, as always!

Meanhwile could you propose a solution, please? Because this happens in any web page that I tested.

**Comment by dpvc** [comment]
Sorry for the delay in getting back to you on this.  Here is something to try:

```
<script type="text/x-mathjax-config">
 MathJax.Hub.Config({
     MathMenu: {
         windowSettings: {
             width: 800,
             height: 400,
             left: Math.round((screen.width - 800)/2),
             top:  Math.round((screen.height - 400)/3)
         }
     }
 });
</script>
```

Adjust the 800 and 400 to your preferences.  This is the initial size of the window, so if the code that is trying to adjust the size and placement doesn't work, the window should be this size.

If the size of the window is changed after that, and the size is incorrect, then you have to work a little harder.  use

```
<script type="text/x-mathjax-config">
 MathJax.Hub.Config({
     MathMenu: {
         windowSettings: {
             width: 800,
             height: 400,
             left: Math.round((screen.width - 800)/2),
             top:  Math.round((screen.height - 400)/3)
         }
     }
 });
 MathJax.Hub.Register.StartupHook("MathMenu Ready", function () {
     MENU = MathJax.Menu;
     var _ = function (id) {
         return MathJax.Localization._.apply(
         MathJax.Localization,
         [["MathMenu",id]].concat([].slice.call(arguments,1))
         );
     };
     MENU.ShowSource.Text = function (text,event) {
         var w = MENU.ShowSource.Window(event); delete MENU.ShowSource.w;
         text = text.replace(/^\s*/,"").replace(/\s*$/,"");
         text = text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
         var title = _("EqSource","MathJax Equation Source");
         if (MENU.isMobile) {
             w.document.open();
             w.document.write("<html><head><meta name='viewport' content='width=device-width, initial-scale=1.0' /><title>"+title+"</title></head><body style='font-size:85%'>");
             w.document.write("<pre>"+text+"</pre>");
             w.document.write("<hr><input type='button' value='"+_("Close","Close")+"' onclick='window.close()' />");
             w.document.write("</body></html>");
             w.document.close();
         } else {
             w.document.open();
             w.document.write("<html><head><title>"+title+"</title></head><body style='font-size:85%'>");
             w.document.write("<table><tr><td><pre>"+text+"</pre></td></tr></table>");
             w.document.write("</body></html>");
             w.document.close();
         }
     };
 });
</script>
```
instead.

See if one of those works for you.

**Comment by EmanuelPrima** [comment]
> Sorry for the delay in getting back to you on this. Here is something to try:
> 
> ```
> <script type="text/x-mathjax-config">
>  MathJax.Hub.Config({
>      MathMenu: {
>          windowSettings: {
>              width: 800,
>              height: 400,
>              left: Math.round((screen.width - 800)/2),
>              top:  Math.round((screen.height - 400)/3)
>          }
>      }
>  });
> </script>
> ```
> 
> Adjust the 800 and 400 to your preferences. This is the initial size of the window, so if the code that is trying to adjust the size and placement doesn't work, the window should be this size.
> 
> If the size of the window is changed after that, and the size is incorrect, then you have to work a little harder. use
> 
> ```
> <script type="text/x-mathjax-config">
>  MathJax.Hub.Config({
>      MathMenu: {
>          windowSettings: {
>              width: 800,
>              height: 400,
>              left: Math.round((screen.width - 800)/2),
>              top:  Math.round((screen.height - 400)/3)
>          }
>      }
>  });
>  MathJax.Hub.Register.StartupHook("MathMenu Ready", function () {
>      MENU = MathJax.Menu;
>      var _ = function (id) {
>          return MathJax.Localization._.apply(
>          MathJax.Localization,
>          [["MathMenu",id]].concat([].slice.call(arguments,1))
>          );
>      };
>      MENU.ShowSource.Text = function (text,event) {
>          var w = MENU.ShowSource.Window(event); delete MENU.ShowSource.w;
>          text = text.replace(/^\s*/,"").replace(/\s*$/,"");
>          text = text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
>          var title = _("EqSource","MathJax Equation Source");
>          if (MENU.isMobile) {
>              w.document.open();
>              w.document.write("<html><head><meta name='viewport' content='width=device-width, initial-scale=1.0' /><title>"+title+"</title></head><body style='font-size:85%'>");
>              w.document.write("<pre>"+text+"</pre>");
>              w.document.write("<hr><input type='button' value='"+_("Close","Close")+"' onclick='window.close()' />");
>              w.document.write("</body></html>");
>              w.document.close();
>          } else {
>              w.document.open();
>              w.document.write("<html><head><title>"+title+"</title></head><body style='font-size:85%'>");
>              w.document.write("<table><tr><td><pre>"+text+"</pre></td></tr></table>");
>              w.document.write("</body></html>");
>              w.document.close();
>          }
>      };
>  });
> </script>
> ```
> 
> instead.
> 
> See if one of those works for you.

Sorry for the silly question, but where do I have to paste that code? I am not an admin nor creator of any website.

**Comment by dpvc** [comment]
Sorry, didn't understand your situation.  In that case, you would want to use an extension like [Tampermonkey](https://www.tampermonkey.net) and make a script for it that runs the code above during the page load event.  Something like the following:

```
// ==UserScript==
// @name         Better MathJax Source Windows
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Improve size of MathJax source windows
// @author       Davide P. Cervone
// @match        *
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    function initMathJax () {
        var MathJax = window.MathJax;
        MathJax.Hub.Config({
            MathMenu: {
                windowSettings: {
                    width: 800,
                    height: 400,
                    left: Math.round((screen.width - 800)/2),
                    top:  Math.round((screen.height - 400)/3)
                }
            }
        });
        MathJax.Hub.Register.StartupHook("MathMenu Ready", function () {
            var MENU = MathJax.Menu;
            var _ = function (id) {
                return MathJax.Localization._.apply(
                    MathJax.Localization,
                    [["MathMenu",id]].concat([].slice.call(arguments,1))
                );
            };
            MENU.ShowSource.Text = function (text,event) {
                var w = MENU.ShowSource.Window(event); delete MENU.ShowSource.w;
                text = text.replace(/^\s*/,"").replace(/\s*$/,"");
                text = text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
                var title = _("EqSource","MathJax Equation Source");
                w.document.open();
                if (MENU.isMobile) {
                    w.document.write("<html><head><meta name='viewport' content='width=device-width, initial-scale=1.0' /><title>"+title+"</title></head><body style='font-size:85%'>");
                    w.document.write("<pre>"+text+"</pre>");
                    w.document.write("<hr><input type='button' value='"+_("Close","Close")+"' onclick='window.close()' />");
                    w.document.write("</body></html>");
                } else {
                    w.document.write("<html><head><title>"+title+"</title></head><body style='font-size:85%'>");
                    w.document.write("<table><tr><td><pre>"+text+"</pre></td></tr></table>");
                    w.document.write("</body></html>");
                }
                w.document.close();
            };
        });
    }

    window.addEventListener('load', function () {if (window.MathJax) initMathJax()});
})();
```

I haven't testing this very heavily, so it may need to adjusting if there are timing issues with some sites.  It might be that the test for wither MathJax is present would have t one delayed in some cases, for example if the page loads MathJax dynamically after the page onLoad even has fired.  It may also miss MathJax if it is loaded in an iframe.  So this may not cover all the cases, and you may have to play around with it to get better coverage.

**Comment by EmanuelPrima** [comment]
Thanks for the code. I downloaded Tampermonkey and pasted your code on a script.

The code runs OK when (I think) we are only in `https` domains. But it does not work in `http` domains, like these link: http://rinconmatematico.com/foros/index.php?topic=107665.0

I tried [this link](https://stackoverflow.com/questions/15475404/include-all-pages-in-tampermonkeyuserscript) and [this](https://www.tampermonkey.net/documentation.php#_include) and [this](https://developer.chrome.com/extensions/match_patterns), so I ended up with different "solutions":

`// @match <all_urls>`
`// @match      *://*/*`
`// @include *`

(copied just after your `// ==/UserScript==`), and it does not work.

Any idea? Sorry if this is off-topic, but I can achieve your solution in e.g. [math.SE](https://math.stackexchange.com/) (it uses `https` domain).

**Comment by dpvc** [comment]
The `@match` line must come *before* the `// ==/UserScript==` comment.  I've edited my script above to include the correct `@match` statement.  Give that a try.  It works for me on both your links.
