### ISSUE TITLE
Sponsors link in header on mathjax website doesn't work

### ISSUE THREAD

**Issue by montanaflynn** [mathjax/MathJax#2147]
There's a link in the header on mathjax.org that is broken:

https://www.mathjax.org/#sponsors

I couldn't find that section on the page either.

**Comment by dpvc** [comment]
It seems to work fine for me.  The `<section>` element at line 336 has `id="sponsors"`.

**Comment by montanaflynn** [comment]
@dpvc after inspecting the source I found my ad blocker was blocking any div with that id, thanks!

**Comment by dpvc** [comment]
OK, good to know the source of the issue.  Glad you got it resolved.
