### ISSUE TITLE
Math Processing Error - Uncaught TypeError: n.replace is not a function

### ISSUE THREAD

**Issue by Timothy-Pulliam** [mathjax/MathJax#2148]
I am using Python [Pelican](https://github.com/getpelican/pelican) static site generator's [render_math](https://github.com/getpelican/pelican-plugins/tree/master/render_math) plugin, which uses MathJax to insert math equations into my website. render_math uses MathJax via CDN in the following line

`mathjax_settings['source'] = "'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/latest.js?config=TeX-AMS-MML_HTMLorMML'"`

Whenever I render my site, the equations show for 10 seconds and then all appear as such

![mathjax_error](https://user-images.githubusercontent.com/12704531/57896202-81e27f00-781d-11e9-83c9-0d8d77d29d7b.png)

I have tested this in both Chrome incognito mode, and Firefox with the same results. In Chrome developer tools, I see the following.

```
Uncaught TypeError: n.replace is not a function  jax.js?V=2.7.5:formatted:102 
    at Object.testCollection (jax.js?V=2.7.5:formatted:102)
    at Object.findFont (jax.js?V=2.7.5:formatted:77)
    at Object.Config (jax.js?V=2.7.5:formatted:583)
    at Function.execute (MathJax.js:19)
    at cb (MathJax.js:19)
    at Object.Process (MathJax.js:19)
    at Object.Push (MathJax.js:19)
    at Object.loadComplete (MathJax.js:19)
    at Function.execute (MathJax.js:19)
    at cb (MathJax.js:19)
```
Tracing back to the file It appears the error appears in the following function

```
testCollection: function(n) {
            var m = {
                testString: "() {} []"
            };
            m.family = {
                TeX: "MathJax_Size1",
                STIX: "STIXSizeOneSym"
            }[n] || n.replace(/-(Math)?/, "") + "MathJax_Size1";
            if (n === "STIX") {
                m.noStyleChar = true
            }
            return this.testFont(m)
```

I am not sure if this is a MathJax issue, or if this is a Pelican plugin issue. I have tried replacing render_math CDN link to the latest MathJax version like so, with no effect.

`mathjax_settings['source'] = "'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js'"`

I am thinking (based on a quick google search) `n.replace ` could be replaced with `n.toString().replace`, however I am not a Javascript programmer.

**Comment by dpvc** [comment]
The error message suggests that the value passed to `n` is not a string (as your solution suggests you know).  But that value is being taken from the MathJax preferences, so the error is probably in the preferences.  This value will be the value of `preferredFont` or one of the names in the `availableFonts` array in the `HTML-CSS` block of your configuration, so I would look there to see if the value of `preferredFont` is not a string (or `null`), and if the `availableFonts` is an array of strings.

**Comment by Timothy-Pulliam** [comment]
That was the issue. I will submit a pull request to the render_math maintainers. Thank you so much for your help.

**Comment by Timothy-Pulliam** [comment]
Actually, it appears the issue still persists even though I have hard coded the available and preferred fonts. I am not sure if you will be able to help me, but I can provide more information if necessary.

"    'HTML-CSS': {{ " +
"        availableFonts: ['STIX', 'TeX']," +
"        preferredFont: 'STIX'," +
"        styles: {{ '.MathJax_Display, .MathJax .mo, .MathJax .mi, .MathJax .mn': {{color: '{    color} ! important'}} }}," +
"        linebreaks: {{ automatic: "+ linebreak +", width: '90% container' }}," +
"    }}, " +
"}}); " +

**Comment by dpvc** [comment]
Is it possible for me to access the website where this is happening?  If not, can you view the page source from the browser to make sure that the values are getting through as you expect them too?

If you could enter

```
MathJax.Hub.config["HTML-CSS"]
```

into the browser console and open the object to list its properties, and copy and past that here, that might help.

**Comment by Timothy-Pulliam** [comment]
I should probably note,  I am using the a pelican/python local HTTP server. I will check to see if that may be the issue

```
MathJax.Hub.config["HTML-CSS"]

{noReflows: true, matchFontHeight: true, scale: 100, minScaleAdjust: 50, availableFonts: Array(1), …}
EqnChunk: 10000
EqnChunkDelay: 0
EqnChunkFactor: 1
availableFonts: Array(1)
0: Array(2)
0: "STIX"
1: "TeX"
length: 2
__proto__: Array(0)
length: 1
__proto__: Array(0)
imageFont: "TeX"
linebreaks: {automatic: false, width: "90% container"}
matchFontHeight: true
minScaleAdjust: 50
mtextFontInherit: false
noReflows: true
preferredFont: "STIX"
scale: 100
styles: {.MathJax_Display: {…}, .MathJax .merror: {…}, .MathJax .MJX-monospace: {…}, .MathJax .MJX-sans-serif: {…}, #MathJax_Tooltip: {…}, …}
undefinedFamily: "STIXGeneral,'Arial Unicode MS',serif"
webFont: "TeX"
```

**Comment by dpvc** [comment]
OK, the `availableFonts` doesn't look right.  It seems to be an array consisting of one entry that is an array of two strings.  It should just be an array of strings.  The outer array is what is causing the problems.  Can you check the page source (view source in browser) to see if the configuration that is coming through looks like 

```
availableFonts: [['STIX', 'TeX']]
```

which is incorrect, rather than the correct

```
availableFonts: ['STIX', 'TeX']
```

That would account for the extra array nesting.  Could Pelican be doing that?  I see that you have had to double the braces to get actual braces in the output (rather than variable substitution); is there something similar needed for brackets?

**Comment by Timothy-Pulliam** [comment]
You were correct. The page source does show a nested array. I simply had to remove the outer square brackets (I am not sure why they were there) to the following

`availableFonts: {font_list}," 
`
The page source now displays it correctly

`availableFonts: ['STIX', 'TeX']`

It is working now. Thank you so much for your help.

**Comment by dpvc** [comment]
Great! Glad we able to get the problem resolved.
