### ISSUE TITLE
Donation code for website 

### ISSUE THREAD

**Issue by lisamartin72** [mathjax/MathJax#2149]
@dpvc Attached is the donation button for your website we discussed on the call this morning. Welcome to NumFOCUS!

Best, 
Lisa

```html
<a href="https://numfocus.salsalabs.org/donate-to-mathjax" target="_blank" style="background:#FFA500;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#222222;font-family:Arial, Helvetica, sans-serif;display:inline-block;">Donate Now!</a>
```

**Comment by dpvc** [comment]
Thanks for the code.  Much appreciated.

It was very nice getting to meet you today.  The team is very helpful, and I look forward to working with you all.

Davide
