### ISSUE TITLE
"HTML-CSS" in config fails to render the equation

### ISSUE THREAD

**Issue by Harrypotterrrr** [mathjax/MathJax#2150]
The font of my blog using the following config code to support latex:
``` html
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    TeX: { 
        equationNumbers: { 
          autoNumber: "all" 
        } 
    },
    tex2jax: {
      inlineMath:  [ ["$", "$"] ],
      displayMath: [ ["$$","$$"] ],
      processEscapes: true,
    },
    "HTML-CSS": {
        availableFonts: ["TeX", "STIX-Web", "Asana-Math", "Neo-Euler", "Gyre-Pagella", "Gyre-Termes", "Latin-Modern"],
        preferredFont: "Asana-Math",
        showMathMenu: false,
    }
  });
</script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>
```
However I have tried to change `preferredFont` for several times, but "HTML-CSS" block always fails to render in right way whether for `showMathMenu` or `preferredFont`.
I hope to change my latex font from this
![image](https://user-images.githubusercontent.com/28552583/58366187-39078600-7f01-11e9-80e3-8cdde481a2c5.png)
to this one as in many papers:
![image](https://user-images.githubusercontent.com/28552583/58366160-d57d5880-7f00-11e9-8b5c-9d502fde3258.png)
It seems that there is a little difference but it indeed makes a big influence..

I have checked the Chrome in inspect mode that the font-family is as follows:
![image](https://user-images.githubusercontent.com/28552583/58366177-0bbad800-7f01-11e9-9415-9e002b154a57.png)

Could you help me? Appreciate in advance!

**Comment by dpvc** [comment]
Note that by requesting `TeX-MML-AM_CHTML` as your config file, you are requesting the CommonHTML output renderer, not the older HTML-CSS output renderer.  So you are configuring the wrong renderer.  You will not be able to change the font for the CommonHTML because it only has data for the MathJax TeX font (based on the Computer Modern fonts), not the other web fonts available in SVG and HTML-CSS output.

Also, the two images you provide both appear to use Computer Modern (or perhaps Latin Modern) fonts.  The second one certainly is *not* the Asana font that you seem to be trying to use.

**Comment by Harrypotterrrr** [comment]
Thanks for your reply.
The second screenshot is taken from the paper, while the first one is taken from my jekyll-based blog.
I indeed hope to change the font to the second, so is there any way that I can configure the correct renderer to solve this problem, like reading source code of my jekyll theme?

**Comment by dpvc** [comment]
> I indeed hope to change the font to the second,

You have not said what the font actually is.  The math characters appear to the Computer Modern or Latin Modern fonts, and the output from MathJax is already using the MathJax TeX fonts, which are derived from the Computer Modern fonts, so the math characters themselves are already in the font you are requesting (or as close to it as MathJax can provide).

The text font appears to be something based on the Times font.  MathJax can be configured to use the surrounding text font for the contents of `\text{}` commands, and if your surrounding font is Times, then you should get that for the `\text{}` in your expressions.  Use `mtextFontInherit: true` in your configuration as

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    TeX: { 
        equationNumbers: { 
          autoNumber: "all" 
        } 
    },
    tex2jax: {
      inlineMath:  [ ["$", "$"] ],
      displayMath: [ ["$$","$$"] ],
      processEscapes: true,
    },
    CommonHTML: {
      mtextFontInherit: true
    }
  });
</script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML' async></script>
```

MathJax only has a fixed number of fonts that it can be configured to work with, so it does not handle arbitrary fonts, in general.  But the MathJax TeX fonts, together with inheriting the font from the surrounding text (provided it is Times or a derivative), is as close to your second image as MathJax will produce.

I do see that there are some spacing differences between the two images, and the spacing in your first image is not what MathJax would normally produce.  I wonder if there is CSS on your page that is interfering with MathJax's layout (e.g., CSS that adds padding to all `<span>` elements, for example)?

**Comment by Harrypotterrrr** [comment]
Appreciate your patience and help, I am a newbie of front-end techniques.
I am using `Mathjax` to render my homepage, and as you say, I guess there might be other CSS rendering my page, fork from [here](https://github.com/academicpages/academicpages.github.io).
But now I don't care the font of the formula anymore, I think the above one is fine! I will study your reply carefully. Btw `$\Phi` is much different between two pictures.
Thanks again for your help!
