### ISSUE TITLE
invalid asciimath output leading to errors

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2153]
Cf. https://github.com/mathjax/MathJax-node/issues/441 and https://github.com/asciimath/asciimathml/issues/106.

Asciimath has a bug creating invalid mathml `{cc}` leads to invalid MathML (with stray text nodes). This input leads to processing errors; MathJax handles the invalid MathML itself sensibly.

**Comment by dpvc** [comment]
Thanks for working out the details.  I had see that the `{cccc}` was probably the issue, but hadn't taken time to verify it.
