### ISSUE TITLE
Re-implement commands in mediawiki-texvc.js like \oiint as big operators

### ISSUE THREAD

**Issue by muzimuzhi** [mathjax/MathJax#2154]
In #1810 , several commands, including `\oiint` are added to TeX extension `mediawiki-texvc.js`. But, `\oiint` was implemented as a macro, 
https://github.com/mathjax/MathJax/blob/39c61f62a9a8196e6caa189ff5771ea31b7f7379/unpacked/extensions/TeX/mediawiki-texvc.js#L88-L90
not a big operator.
https://github.com/mathjax/MathJax/blob/39c61f62a9a8196e6caa189ff5771ea31b7f7379/unpacked/jax/input/TeX/jax.js#L537-L540

Therefore, when `\oiint` is used in display style, it is just in a larger font size (using `\huge`) and hence ugly, not with the corresponding "bigger" glyph defined in math font.

![image](https://user-images.githubusercontent.com/6376638/59425915-7462e980-8e09-11e9-948f-58b9a70f14a0.png)

**Comment by dpvc** [comment]
One reason for the definition is that the MathJax TeX fonts don't include the needed characters; the STIX fonts do, but the MathJax TeX fonts are the default, and defining it in the way that you indicate would mean the symbol would not show up at all for some people.  The authors of the extension probably felt that this was the best compromise between functionality and quality.

**Comment by muzimuzhi** [comment]
Are the MathJax TeX fonts you just mentioned derived from any otf Math fonts, like Latin Modern Math font?

**Comment by dpvc** [comment]
No, they were built using `mftrace` from the Computer Modern TeX fonts ages ago.

**Comment by muzimuzhi** [comment]
Ok, I see. 

Maybe it's time to build the MathJax TeX fonts from Latin Modern Math, for a more complete list of math symbols.

**Comment by dpvc** [comment]
The Latin Modern fonts are supported in the HTML-CSS and SVG output (but not currently the CommonHTML output), but they are not the defaults.  We are in the final stages of a complete rewrite for version 3.0, which has a revised font handling framework.  Currently v3 only supports the current MathJax TeX fonts, but we plan a revamping of the fonts for 3.1, and that will include updating the MathJax TeX fonts.

**Comment by muzimuzhi** [comment]
To record the progress after one year: 
 - The latest release of MathJax is [3.0.5](https://github.com/mathjax/MathJax/releases/tag/3.0.5).
 - `\oint` is supported as math operator (`texClass: TEXCLASS.OP`). See [related source line](https://github.com/mathjax/MathJax-src/blob/b526361f6d036772491f4b521361664df44b2768/ts/input/tex/base/BaseMappings.ts#L182).
 - Extension `mediawiki-texvc` is not supported, hence `\oiint` and `\oiiint` (and some other commands) are not supported in 3.0+.
