### ISSUE TITLE
Problems with rendering cfrac 

### ISSUE THREAD

**Issue by apio1** [mathjax/MathJax#2159]
I know that `\cfrac` can be used for continued fractions. However, it does not work in my case. I'm using Mathjax 2.7.1. 

When trying `$$\frac{a}b=q_0+\cfrac{1}{q_1+\cfrac{1}{q_2+\cfrac{1}{\ddots+\cfrac{1}{q_{n-2}+\cfrac{1}{q_{n-1}+\cfrac{1}{q_n}}}}}}$$`, the following result will be displayed in my environment (Chrome 75.0.3770.100).

![example 1](https://www.bookofproofs.org/graphics/examples/cfugly1.png)

As a second choice, I use `\frac` instead, knowing that it produces not so pretty results:

![example 1](https://www.bookofproofs.org/graphics/examples/cfugly.png)

I know that it should work like it is demonstrated in [this tutorial](https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference/5058#5058). But the example from the tutorial does not work in my environment either.

Is this a configuration issue on my side? 

By the way, the `\cfrac` example works with Firefox 67.0.4 correctly!

**Comment by dpvc** [comment]
Your `\cfrac` example works fine for me, so it may be that there is something in the CSS for your page that is interfering with the layout.  Can you link to a page that shows the problem?  A screen shot is not sufficient for us to investigate the problem.  Also, it would be useful to know your MathJax configuration and the config file that you are using.

**Comment by apio1** [comment]
Sorry, a reproducible example can be found [here](https://www.bookofproofs.org/branches/rational-numbers-and-the-greatest-common-divisor/). Unfortunately, this seems to work fine with Firefox and also with Chrome from another workstation (unfortunately, I do not have the version). So it seems to be not a CSS issue on the server side but has something to do with my local installation of Chrome (version 75.0.3770.100)

**Comment by dpvc** [comment]
The page you link to works for me in Chrome 75.0.3770.100 on Mac OS X Mojave.  So it does seem to be something with your browser.  Can you clear your cache and restart Chrome to see if that helps?  (Restarting is important, as clearing the cache doesn't seem to be enough in Chrome.)

**Comment by apio1** [comment]
Thank you for your help. It seems to be a local problem. I have no clue what is going on, it did not work, even after clearing the cache.

**Comment by popv** [comment]
@apio1 For what it's worth, I've seen that behavior with the Accessibility, Collapsible Math option enabled. Seems to be resolved in 2.7.2+.
