### ISSUE TITLE
Important: CDN files have link to cdn.mathjax.org which break the rendering on ALL websites

### ISSUE THREAD

**Issue by q2apro** [mathjax/MathJax#2160]
I just realized today that the CDN versions of Mathjax, even the latest https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML&locale=de have a link to the obsolete mathjax.org site:

`b.Contrib="https://cdn.mathjax.org/mathjax/contrib";`

which leads to:

> GET https://cdn.mathjax.org/mathjax/contrib/a11y/accessibility-menu.js?V=2.7.0 net::ERR_CONNECTION_TIMED_OUT

And breaks all Mathjax renderings.

I *strongly* advise to fix this as soon as possible. And push the new files to the CDNs (with a relative path?).

**Comment by dpvc** [comment]
While you are correct that `Contrib` points to a dead link, MathJax itself doesn't load anything from that location.  So the reference to this must be in your configuration.  It looks like you may be loading the accessibility menu from there, but there is no need to do that, as it is already included in the `TeX-AMS_HTML` configuration file.  The easiest solution for you would be to simply remove the reference to the `Contrib` directory in your configuration.

When `cdn.mathjax.org` was retired, the control directory was retired as well, as described in [this announcement](https://github.com/mathjax/MathJax-third-party-extensions/issues/39).  Some of the extensions are being maintained by others (e.g., mhchem), and have their own addresses now.

The `Contrib` path will be removed in the next release.  Thanks for reporting the problem.
