### ISSUE TITLE
Whether React Native is supported or not

### ISSUE THREAD

**Issue by Buliceli** [mathjax/MathJax#2169]
Whether React Native is supported or not

**Comment by dpvc** [comment]
There is apparently a React Native tool for MathJax [here](https://www.npmjs.com/package/react-native-mathjax).  There is also [this discussion](https://stackoverflow.com/questions/53837090/how-to-display-mathml-equation-in-react-native-app-using-mathjax) on StackOverflow that might be helpful.

**Comment by pkra** [comment]
v3 will even work without a webview, see the discussion at https://github.com/mathjax/mathjax-v3/issues/190

**Comment by dpvc** [comment]
In light of Peter's comment, you may also want to look at some of the [demos](https://github.com/mathjax/mj3-demos#processing-user-input).  The user-input demos show how to do conversion from a TeX or MathML string to HTML, SVG, or MathML without using the browser DOM.  These end up putting them into the DOM in the end, but the conversion doesn't require it.
