### ISSUE TITLE
Crossing out rows and columns of an array

### ISSUE THREAD

**Issue by MarcoEpsilon** [mathjax/MathJax#2170]
How can I typeset a determinant with a row or column crossed out?

**Comment by dpvc** [comment]
There is no easy way to do it.  Here is an example of one way it can be done, but you need to determine the sizes of the strike-throughs by hand.

```
\def\rowrule#1#2{\rlap{\kern#1\Rule{#2}{.325em}{-.175em}}}
\def\colrule#1#2#3{\rlap{\kern#1\smash{\Rule{.15em}{#2}{#3}}}}

\left|\begin{array}{ccc}
aaa & \colrule{.15em}{1em}{3.2em} b & cc \\
\rowrule{-.5em}{7em} cc & aaa & b \\
b & cc & aaa
\end{array}\right|
```

The first argument to `\rowrule` is a horizontal shift of the rule, and the second argument is the width of the rule.

The first argument to `\colrule` is a horizontal shift of the rule, the second is the height of the rule above the baseline and the third is the depth of the rule below the baseline.

**Comment by dpvc** [comment]
Note:  this issue tracker is really for reporting bugs, not for general questions about MathJax.  For questions, you should probably ask them in the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it and possibly provide an answer.

**Comment by MarcoEpsilon** [comment]
> Note: this issue tracker is really for reporting bugs, not for general questions about MathJax. For questions, you should probably ask them in the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it and possibly provide an answer.

thanks,i will notice
