### ISSUE TITLE
Want to integrate mathjax and mhchem with mathmap but i am not able to do that 

### ISSUE THREAD

**Issue by ngcgolf11** [mathjax/MathJax#2172]
i have read the whole documentation for integrate mathjax with mhchem and mathmap please help me integrate this with mathjax.

**Comment by dpvc** [comment]
It is not clear what you are trying to do.  Mathmap seems to be an image processing program, so do you want to overlay mathematics on your images?  If so, you could potentially use mathjax-node to generate SVG images, and then import those into Mathmap.

Also, this issue tracker is really for reporting bugs in MathJax, not asking general questions.  You would be better served to ask such questions on the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see them and may be able to help.
