### ISSUE TITLE
Macro \class fails to assign compound class to an element

### ISSUE THREAD

**Issue by dainiak** [mathjax/MathJax#2185]
Using `tex-svg.js`, I’m trying to do this type of command: `\class{reddish boldish}{e=mc^2}` where say `reddish` and `boldish` are two CSS classes. That works fine in MathJax v2, but results in *Math output error* in MathJax v3. Trying `\class{reddish}{\class{boldish}{e=mc^2}}` results in an error as well. Trying `\class{reddish}{{\class{boldish}{e=mc^2}}}` produces an output, though it does not achieve what I want as it does not create a single element with two CSS classes simultaneously applied to it. Great overall work on v3 though, keep going!

**Comment by zorkow** [comment]
Thank you!
And thanks for reporting this. I can confirm this. I get a `Missing close brace` error during TeX parsing.

In addition when switching on the a11y extension both expressions during semantic enrichment.

**Comment by zorkow** [comment]
There's a couple of issues:

* [ ] Parse error for ```\class{reddish}{\class{boldish}{e}}```
* [ ] Enrichment error for ```\class{reddish}{{e}}``` (but not for ```\class{reddish}{e}```). SREs output is fine so it has to be in `semantic-enrich.ts`.
* [ ] ```\class{reddish}{{e}}``` produces multiple class entries.

**Comment by dpvc** [comment]
I added a pull request that addresses the original issue with multiple classes in the `\class{}` and nested `\class{}` calls, as well as the three issues Volker reported.
