### ISSUE TITLE
Version 3 anomaly in \begin{cases}...\end{cases}

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2186]
A cases structure like
\[ g(x,y)=\begin{cases}1,& \text{ se } x\in\mathbb{Q} \text{ ou } y\in\mathbb{Q}, \\ 0, & \text{ caso contrário.}\end{cases}\]
is typeset anomalously in MathJax v. 3.0.0.

I have adapted https://cdi2tp.math.tecnico.ulisboa.pt/ (version 2.7) to MathJax version 3.0.0 at https:logrus.math.tecnico.ulisboa.pt/ The example comes from

https://cdi2tp.math.tecnico.ulisboa.pt/texto/3
https://logrus.math.tecnico.ulisboa.pt/texto/3

Screenshots:
Version 2.7 under Firefox 69 Linux
![Screenshot_2019-09-05 CDI II — TP — Página 3](https://user-images.githubusercontent.com/1136663/64374804-73161700-d01c-11e9-9467-9708db555dc4.png)

Version 3.0.0 under Firefox 69 Linux
![Screenshot_2019-09-05 CDI II — TP — Página 3(1)](https://user-images.githubusercontent.com/1136663/64374843-8cb75e80-d01c-11e9-9a53-7eac22b44eb4.png)

Version 3.0.0 under Firefox 68.1 Android
![Screenshot_20190905-201620](https://user-images.githubusercontent.com/1136663/64375622-17e52400-d01e-11e9-9988-3288dcb4b03d.jpg)

**Comment by zorkow** [comment]
I can verify the problem. But only for Firefox/CHTML on Linux. Looks fine in Chrome as well as with SVG renderer on Firefox.
Same for Android: Looks good for Chrome/Kiwi/DuckDuckGo with either renderer, Firefox with SVG but not for Firefox with CHTML.

**Comment by cebola2** [comment]
I have also noticed in the same example (Firefox or Chrome on Linux) that mtextInheritFont: true seems to be ignored.

**Comment by cebola2** [comment]
On MS Edge on Windows (but not on Android) you get something alike what you get on Firefox (Linux or Windows).

**Comment by dpvc** [comment]
OK, this turns out to have been due to an extra .5ex offset that is part of CSS `vertical-align: middle` that I didn't take into account.  I've made a PR to compensate for it.
