### ISSUE TITLE
skipHtmlTags results in an error in v3

### ISSUE THREAD

**Issue by dainiak** [mathjax/MathJax#2188]
While working with MJv3 (tex-svg.js), putting 
```
MathJax = {
  tex: {skipHtmlTags: ['svg','script','noscript','style','textarea','pre','code']}
}
```
results in `Mathlax(?): Invalid option "skipHTMLTags" (no default value).` and looks like MathJax halts processing altogether after this message, no formulas are converted.

As I got it, MathJax by default does process math inside inline SVGs, but these formulas don’t show up [in Chrome 76 at least], as they become wrapped in mjx-container and their own svg container. Any workaround for this one other than v2 style (processing formula separately and inserting manually as SVG `<g>`)?

**Comment by dpvc** [comment]
OOPS, I've listed the option in the wrong place.  It should be `options` not `tex`.  I.e., 

```
MathJax = {
  options: {skipHtmlTags: ['svg','script','noscript','style','textarea','pre','code']}
}
```

**Comment by dainiak** [comment]
Thanks!

**Comment by dpvc** [comment]
I'm reopening this so that I will have it to remind me to change the documentation (and potentially the configuration converter).

**Comment by dpvc** [comment]
I've fixed the documentation and the converter, so closing again.

**Comment by JamesTheAwesomeDude** [comment]
Speaking of the documentation, [it says that](https://docs.mathjax.org/en/latest/options/document.html#processHtmlClass)

>  `processHtmlClass` …is used to…  cause a tag that appears in the skipHtmlTags list to be processed rather than skipped.

This sounded perfect for my blog: I only want MathJax to mess with elements designated via `class="mathjax"`, so I set it up:

```js
MathJax = {
  tex: {
    inlineMath: [
      ['$', '$']
    ],
  },
  options: {
    skipHtmlTags: [
      'body'
    ],
    processHtmlClass: 'mathjax',
  }
};
```

…but that `'body'` entry seems to disable it *entirely*.

Is the documentation mistaken and this issue should be re-opened, the code bugged and I should open a new issue, or is something else likely wrong?

**Comment by dpvc** [comment]
@JamesTheAwesomeDude:

> Is the documentation mistaken and this issue should be re-opened, the code bugged and I should open a new issue, or is something else likely wrong?

I think you have misunderstood the documentation.  The contents of a tag in the `skipTags` list is skipped entirely (MathJax doesn't look into its contents at all) unless its class has the `processClass`, in which case its contents are processed.
So unless your `body` tag has `class="mathjax"`, adding `body` to `skipTags` will mean MathJax does not process anything.

I think what you may want is 

``` javascript
MathJax = {
  tex: {
    inlineMath: [
      ['$', '$']
    ],
  },
  options: {
    processHtmlClass: 'mathjax',
    ignoreHtmlClass: 'no-mathjax',
  }
};
```

and then use `<body class="no-mathjax">`, or `<body><div class="no-mathjax">...</div></body>`.

**Comment by dpvc** [comment]
Also setting `sklipTags` to `['body']` would mean that is the **only** tag that is skipped, so you would be losing all the other tags in the list.  You may have wanted to do

``` javascript
skipTags: {'[+]': ['body']}
```

instead to *add* `body` to the list.
