### ISSUE TITLE
Problem with MathJax 2.7.5 and Chrome >= 76.0.3809.132 for MathJaX inside an RTL DIV

### ISSUE THREAD

**Issue by taniwallach** [mathjax/MathJax#2190]
### Issue Summary

When Chrome 76.0.3809.132 is used to render MathJaX content inside an right-to-left (RTL) DIV element using MathJax 2.7.5 problems occur with the placement of the mathematics. The mathematics is often displayed on the incorrect side of the Hebrew (RTL direction) text.

These problems were originally found in WeBWorK problems rendered using MathJax 2.7.5 (not from the CDN) late last week.

The earlier report of trouble dates to Sept 4 from a Windows user.

MathJax 2.7.5 behaves properly when the prior version of Chrome (76.0.3809.100 on Windows) is used, and the problems was seen to immediately begin as soon as Chrome was updated on a machine which had an running copy of Chrome 76.0.3809.100 on Windows. (Since Chrome auto-updates, but does not restart the updated version, it requires some luck to see this.)

These problems do not occur when MathJax 2.7.4 is used even with Chrome 76.0.3809.132.

On my main (Debian 10) machine - I originally did not have these problems immediately after the update to Google Chrome 76.0.3809.132, and they began to occur only on about Sept 7. It may be possible that a cached version of MathJax.js was responsible for the delayed appearance of the issue. 

The Chrome update includes changes to the Blink rendering engine, and something in these 2 updates (Chrome 76.0.3809.100 to 76.0.3809.132 and MJ 2.7.4 to 2.7.5) triggers the problems. 

The issues has been seen on Windows 10, Windows 8, Debian 10, Android 6.0.1 - all when running Chrome 76.0.3809.132.

### Steps to Reproduce

Test pages:
  - https://codepen.io/taniwallach/pen/zYORoQa (used MJ 2.7.5 from CDN, set in the `head` settings)
  - https://codepen.io/taniwallach/pen/jONZyOw (used MJ 2.7.4 from CDN, set in the `head` settings)

Symptoms:
  - Initial page load (uses the default `HTML-CSS` math renderer: the math is **incorrectly** displayed at the far right, while it is logically located at the end of a right-to-left line so should be on the left side of the Hebrew text.
  - Changing the Math Renderer (Context menu -> Math Settings -> Math Renderer) to `Common HTML` and the math moves to the left (where it should be)
  - but then after a page refresh it moved back to the right side (**incorrect** location)
  - Changing the Math Renderer back to `HTML-CSS` and the math moves to the left (where it should be)
  - but then after a page refresh it moved back to the right side (**incorrect** location)
  - Changing the Math Renderer to `SVG` and the math moves to the left (where it should be)
  - but then after a page refresh it moved back to the right side (**incorrect** location)
  - Changing the Math Renderer back to `HTML-CSS` and the math moves to the left (where it should be)
  - but then after a page refresh it moved back to the right side (**incorrect** location)
  - Sometimes the math is seen to appear briefly in the correct location (left side) before disappearing and reappearing on the right side  (**incorrect** location)
  - In some cases, fiddling with these settings and refreshing lead to multiple math displays or the math disappearing from the page.

No such trouble was detected using FireFox or Edge.

Several screen shots will follow.

### Technical details:

* MathJax Version: 2.7.5 (from the CDN)
* Client OS: Debian 10, Windows 10, Windows 8, Android 6.0.1
* Browser: Chrome 76.0.3809.132

**Comment by taniwallach** [comment]
Screen-shots from Windows 8:

OS version:

![PC-info-Windows8](https://user-images.githubusercontent.com/39089094/64489972-3a1ab400-d261-11e9-94f8-8f8a47fe169b.jpg)

Initial Chrome version:

![chrome-76 0 3809 100-version-info](https://user-images.githubusercontent.com/39089094/64489970-3a1ab400-d261-11e9-992f-0c4783cd50d9.jpg)

No problems on Chrome 76.0.3809.100:

![chrome-76 0 3809 100-mj-2 7 5-ok](https://user-images.githubusercontent.com/39089094/64489971-3a1ab400-d261-11e9-99ad-b346d690dfef.jpg)

Issue on initial page load on Chrome 76.0.3809.132:

![chrome-76 0 3809 132-version-info](https://user-images.githubusercontent.com/39089094/64489969-39821d80-d261-11e9-8857-6c5fe1f07974.jpg)

![chrome-76 0 3809 132-mj-2 7 5-BAD](https://user-images.githubusercontent.com/39089094/64489967-39821d80-d261-11e9-9cb3-e5515b2b778e.jpg)

Change to Common-HTML no issue on initial display after change on Chrome 76.0.3809.132:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-common-HTML-ok](https://user-images.githubusercontent.com/39089094/64489966-39821d80-d261-11e9-92d4-7069ac2f191c.jpg)

but then issue occurs after page refresh:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-common-HTML-then-refreshed-BAD](https://user-images.githubusercontent.com/39089094/64489964-38e98700-d261-11e9-9c4c-b0d7593a4968.jpg)

Change back to HTML-CSS and no issue on initial display after change on Chrome 76.0.3809.132:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-common-HTML-then-refreshed-then-back-to-HTML-CSS-ok](https://user-images.githubusercontent.com/39089094/64489961-37b85a00-d261-11e9-936c-afbfedfca2cf.jpg)

but then issue occurs after page refresh:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-common-HTML-then-refreshed-then-back-to-HTML-CSS-then-refresh-BAD](https://user-images.githubusercontent.com/39089094/64489960-37b85a00-d261-11e9-9bd3-cf546df472dd.jpg)

Change to SVG no issue on initial display after change:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-SVG-ok](https://user-images.githubusercontent.com/39089094/64489963-38e98700-d261-11e9-8ae8-a2bce81c2d97.jpg)

but then issue occurs after page refresh:

![chrome-76 0 3809 132-mj-2 7 5-changed-to-SVG-then-refreshed-BAD](https://user-images.githubusercontent.com/39089094/64489962-3850f080-d261-11e9-8bc7-c435101fc62a.jpg)

No issues on FireFox:

![ff-68 0 2-version-info](https://user-images.githubusercontent.com/39089094/64489973-3a1ab400-d261-11e9-820d-7a8620bada00.jpg)

![ff-68 0 2-mj-2 7 5-ok](https://user-images.githubusercontent.com/39089094/64489974-3ab34a80-d261-11e9-92a1-1e6ebfb9d54e.jpg)

**Comment by taniwallach** [comment]
Screen-shots from Windows 10:

OS version:

![Windows10-version-info](https://user-images.githubusercontent.com/39089094/64490107-81ee0b00-d262-11e9-84a7-22be22b6f2c5.png)



Issue on initial page load on Chrome 76.0.3809.132:

![mj-2 7 5-Chrome-76 0 3809-BAD](https://user-images.githubusercontent.com/39089094/64490117-83b7ce80-d262-11e9-8257-a512ba672d62.png)

Change to Common-HTML no issue on initial display after change on Chrome 76.0.3809.132:

![mj-2 7 5-Chrome-76 0 3809-change-to-CommonHTML-ok](https://user-images.githubusercontent.com/39089094/64490116-83b7ce80-d262-11e9-96bc-5ce16e070ff9.png)

but then issue occurs after page refresh:

![mj-2 7 5-Chrome-76 0 3809-change-to-CommonHTML-then-reload-BAD](https://user-images.githubusercontent.com/39089094/64490115-83b7ce80-d262-11e9-8b73-4ef373b98ce6.png)

Change back to HTML-CSS and no issue on initial display after change:

![mj-2 7 5-Chrome-76 0 3809-change-to-CommonHTML-then-reload-then-change-back-to-HTML-CSS-ok](https://user-images.githubusercontent.com/39089094/64490113-831f3800-d262-11e9-83f6-bcb4f6abe12f.png)

but then issue occurs after page refresh:

![mj-2 7 5-Chrome-76 0 3809-change-to-CommonHTML-then-reload-then-change-back-to-HTML-CSS-the -reload-BAD](https://user-images.githubusercontent.com/39089094/64490112-831f3800-d262-11e9-95de-fa5c19379b34.png)

Change to SVG no issue on initial display after change:

![mj-2 7 5-Chrome-76 0 3809-change-to-SVG-ok](https://user-images.githubusercontent.com/39089094/64490111-831f3800-d262-11e9-80a2-cbf4ef059e8e.png)

but then issue occurs after page refresh:

![mj-2 7 5-Chrome-76 0 3809-change-to-SVG-then-reload-BAD](https://user-images.githubusercontent.com/39089094/64490110-8286a180-d262-11e9-95a2-c227343d9126.png)

Change back to HTML-CSS and no issue on initial display after change:

![mj-2 7 5-Chrome-76 0 3809-change-to-SVG-then-reload-then-change-back-to-HTML-CSS-ok](https://user-images.githubusercontent.com/39089094/64490109-8286a180-d262-11e9-9b3b-c458e222ced4.png)

but then issue occurs after page refresh:

![mj-2 7 5-Chrome-76 0 3809-change-to-SVG-then-reload-then-change-back-to-HTML-CSS-the -reload-BAD](https://user-images.githubusercontent.com/39089094/64490108-81ee0b00-d262-11e9-98d6-a2305c720edb.png)

**Comment by taniwallach** [comment]
Several other screenshots - some with multiple displayed copies of the single math "object":

![Android-starnge-partial-clear](https://user-images.githubusercontent.com/39089094/64490257-cb8b2580-d263-11e9-8da8-bb26a045da49.png)

![MathJax2 7 5-after-fiddling-with-context-menu-and-reload](https://user-images.githubusercontent.com/39089094/64490260-de9df580-d263-11e9-9e56-6bf7a7566b44.png)

![MJ-2 7 5-svg-then-refresh](https://user-images.githubusercontent.com/39089094/64490263-e78ec700-d263-11e9-8955-fc65723b242f.png)

![svg-after-refresh](https://user-images.githubusercontent.com/39089094/64490268-f8d7d380-d263-11e9-90b8-4cb81cf96749.png)

![SVG-after-refresh](https://user-images.githubusercontent.com/39089094/64490273-0a20e000-d264-11e9-8574-a5f22cfbe65b.png)

![MJ-2 7 4-tab-after-other-tab-set-to-SG-and-refreshed](https://user-images.githubusercontent.com/39089094/64490277-15740b80-d264-11e9-855c-741b4c158c70.png)

![MJ-2 7 4-after-mod-to-SVG](https://user-images.githubusercontent.com/39089094/64490278-15740b80-d264-11e9-9e02-158253e8fc26.png)

![MJ-2 7 5-smaller-pen](https://user-images.githubusercontent.com/39089094/64490284-1ad15600-d264-11e9-815d-b8fdd383c7d4.png)


---

No problems are typically seen on 2.7.4:

![MJ-2 7 4-smaller-pen](https://user-images.githubusercontent.com/39089094/64490283-1a38bf80-d264-11e9-968e-546c79aab150.png)

**Comment by dpvc** [comment]
OK, I've been able to reproduce the issue in Chrome on Mac OSX using your latest codepen.  It appears that it is due to the handling of the MathJax preview element that is inserted in the document (ether by MathJax automatically, or in your case any you explicitly).  This seems to disrupt the language direction when they are empty.

One solution would be to disable the previews via:

```
<style>
  .MathJax_Preview {
    display: none;
  }
</style>
```

It is also possible to use

```
<style>
  .MathJax_Preview {
    display: contents;
  }
</style>
```

which will allow the preview to be shown (if that's what you want).

Alternatively,

```
<style>
  .MathJax_Preview:before {
    content: '\200B'
  }
</style>
```

adds some content so that the element is non-empty, but doesn't display anything.

Any of these seem to resolve the issue.

**Comment by taniwallach** [comment]
I reported the issue also to the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1004071
as it seems that the real bug is in Chromium and not MathJax.

I tried (quickly) to see if I could determine what changes between 2.7.4 and 2.7.5 might be related to the fact that the problem occurs in 2.7.5 and not 2.7.4. The commits which I believe may be related are:
  - https://github.com/mathjax/MathJax/commit/204ffbb5e791f909d2bb2d7d71b9de87add8c567
    - seems related as setting `display: none` or `display: contents` on `MathJax_Preview` avoids the issue.
  - Less likely:   https://github.com/mathjax/MathJax/commit/2fe8c702c76b3b43fc2b6a2c9dde5a4371d8684d
However, since I don't really know much about MathJax's internals, I may have ignored commits which could be related, or just missed something in the larger commits.

**Comment by dpvc** [comment]
I suspect you are right about the first commit being the one that is the difference between 2.7.4 and 2.7.5.  This change was made to prevent crashes in Safari, so it's kind of important.  I would think that setting `display: contents` initially on the elements would be OK, however.

> But I could not hack `MathJax.js` to get it to work inside WeBWorK.

One should not hack `MathJax.js` at all.  Changes should be made using the MathJax configuration; there should almost never be a need to alter MathJax itself.  You can specify the styles using the configuration object directly.  For example:

```
MathJax.Hub.Config({
  styles: {
    '.MathJax_Preview:before': {
      contents: "'\200B'"
    }
  }
});
```

would be the equivalent of

```
<style>
  .MathJax_Preview:before {
    content: '\200B'
  }
</style>
```

Similarly,

```
MathJax.Hub.Config({
  styles: {
    '.MathJax_Preview': {
      display: 'contents'
    }
  }
});
```

would be equivalent to

```
<style>
  .MathJax_Preview {
    display: contents;
  }
</style>
```

You can do this in WeBWorK, which already includes a `MathJax.Hub.Config()` call, by adding additional configuration to the call in [PG.pl](https://github.com/openwebwork/pg/blob/dfef4c682ccc93305545671fde7bd9edfb83ed37/macros/PG.pl#L90-L92).  Making this be

```
                  MathJax.Hub.Config({
                     styles: {
                       '.MathJax_Preview:before': {contents: "'\200B'"}
                     },
                     MathMenu: {showContext: true}
                  });
```

should do it.

**Comment by taniwallach** [comment]
The Chromium acknowledges the issue, and it is apparently due to the transition to a new layout engine. Thus, there is hopefully no reason to rush to adding a long-term fix/workaround to the main MathJax code. For now, the recommended workarounds should suffice, until we see if the Chromium team will be able to fix the issue on their side in a timely manner.

BYW I had tried to use WW's `htdocs/themes/math4/math4-overrides.css` to make the CSS override, but could not get that to work. Since I did not know of a better approach, a temporary hack to the locally installed `MathJax.js` seemed a reasonable short-term solution. I'll replace it with a local modification to `pg/macros/PG.pl` instead soon.

**Comment by dpvc** [comment]
The `math4-ocerrides.css` will be processed before the styles added by MathJax, so you might need to include `!important` to the CSS in order to override MathJax's settings.

**Comment by dpvc** [comment]
I can't make a test for this, as it no longer seems to be an issue in Chrome 79, so I can't reproduce the problem in order to test the detection of the issue.

**Comment by taniwallach** [comment]
> I can't make a test for this, as it no longer seems to be an issue in Chrome 79, so I can't reproduce the problem in order to test the detection of the issue.

Chrome 80 is not effected, and when I drop the workaround code from my WeBWorK server, the MathJax equations display properly. Sorry that I did not check to see if the workaround was still needed before you added it to MathJax v2 as a long term fix.
