### ISSUE TITLE
Loading exstension is really slow

### ISSUE THREAD

**Issue by arn4** [mathjax/MathJax#2192]
I'm using MathJax with an [extension that allows to render SI units](https://github.com/burnpanck/MathJax-siunitx). The extension file is hosted on my server, as suggested in the extension page. When I load a page with MathJax it takes around 10 seconds to load the extension file and at bottom-left of the page appers a box with 
> Loading _url of the file_...

After these 10 seconds it appears another box saying that the loading has failed, but the extensions works anyway.

I'm sure that is not a server problem since that if I try to get the extension file from another browser tab it loads istantly. Any idea how to fix this annoying delay time? (MathJax does not work at all untill the extension file is loaded, despite it says that the loading has failed)

**Comment by pkra** [comment]
See https://github.com/burnpanck/MathJax-siunitx/issues/6
