### ISSUE TITLE
rendering TeX input with custom elements

### ISSUE THREAD

**Issue by jxxcarlson** [mathjax/MathJax#2195]
I've modified the example https://github.com/mathjax/MathJax/issues/2162#issuecomment-506962519 so that it processes the text between the opening and closing tags rather than processing hardwired MML text. Thus one can say things like

```
<p>
      Custom element test:
      <custom-element>
          <math><mrow><mfrac><mn>17</mn><mrow><mn>616</mn></mrow></mfrac></mrow></math>
      </custom-element>
</p>
```

(I will attach code below).  However, I'd now like to modify the code so that this is processed properly:

```
<p>
      Custom element test:
      <custom-element>
          $a^2 + b^2 = c^2$
      </custom-element>
</p>
```

The only place that I can see where MML is referred to  in the original code is the line 

```
<script src="https://rawcdn.githack.com/mathjax/mj3-demos/3.0.0-beta.4/mathjax3/mml-chtml.js"></script>
```

I replaced it by

```
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

Alas, this did not work: the original TeX source is displayed.

**NOTE.**  In all versions of the code below, including your original, I get the error `TypeError: t.getAttribute is not a function`

**THE CODE:**

**(1) index.html**

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">

    <script src="custom-element-config.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="custom-element.js"></script>

    <style>
      body {
        font-family: sans-serif;
        width: 400px;
        margin: 40px;
      }
    </style>

  </head>

  <body>
    <h1>Custom Element TeX test</h1>

    <p>
      Custom element test:
      <custom-element>
          \(a^2 + b^2 = c^2\)
      </custom-element>
    </p>

    <p>
      Another test:
      <custom-element>
\[
\int_{-\infty}^\infty e^{-x^2} dx = \pi
\]
      </custom-element>
    </p>

  </body>
</html>
```

**(2)custom-element.js**  (modified so as to grab the text between the opening and closing tags). It was necessary to move some code from the `constructor` function to the `connectedCallback` function for this to work properly and reliably. 

```
class CustomElement extends HTMLElement {
  constructor() {
    super();
   }

  connectedCallback() {
    this.template = document.createElement('template');
    this.template.innerHTML = this.innerHTML;
    this.attachShadow({mode: "open"}).appendChild(this.template.content.cloneNode(true));
    MathJax.typesetShadow(this.shadowRoot);
  }
}

customElements.define('custom-element', CustomElement);
```

***(3) custom-element-config.js** (identical to your code)

```
MathJax = {
  startup: {
    ready: () => {
      //
      //  Get some MathJax objects from the MathJax global
      //
      //  (Ideally, you would turn this into a custom component, and
      //  then these could be handled by normal imports, but this is
      //  just an example and so we use an expedient method of
      //  accessing these for now.)
      //
      const mathjax = MathJax._.mathjax.MathJax;
      const HTMLAdaptor = MathJax._.adaptors.HTMLAdaptor.HTMLAdaptor;
      const HTMLHandler = MathJax._.handlers.html.HTMLHandler.HTMLHandler;
      const AbstractHandler = MathJax._.core.Handler.AbstractHandler.prototype;
      const startup = MathJax.startup;

      //
      //  Extend HTMLAdaptor to handle shadowDOM as the document
      //
      class ShadowAdaptor extends HTMLAdaptor {
        create(kind, ns) {
          const document = (this.document.createElement ? this.document : this.window.document);
          return (ns ?
                  document.createElementNS(ns, kind) :
                  document.createElement(kind));
        }
        text(text) {
          const document = (this.document.createTextNode ? this.document : this.window.document);
          return document.createTextNode(text);
        }
        head(doc) {
          return doc.head || doc;
        }
        body(doc) {
          return doc.body || doc;
        }
        root(doc) {
          return doc.documentElement || doc;
        }
        allAttributes(node) {
          return (node.attributes ? super.allAttributes(node) : []);
        }
      }

      //
      //  Extend HTMLHandler to handle shadowDOM as document
      //
      class ShadowHandler extends HTMLHandler {
        create(document, options) {
          const adaptor = this.adaptor;
          if (typeof(document) === 'string') {
            document = adaptor.parse(document, 'text/html');
          } else if ((document instanceof adaptor.window.HTMLElement ||
                      document instanceof adaptor.window.DocumentFragment) &&
                     !(document instanceof window.ShadowRoot)) {
            let child = document;
            document = adaptor.parse('', 'text/html');
            adaptor.append(adaptor.body(document), child);
          }
          //
          //  We can't use super.create() here, since that doesn't
          //    handle shadowDOM correctly, so call HTMLHandler's parent class
          //    directly instead.
          //
          return AbstractHandler.create.call(this, document, options);
        }
      }

      //
      //  Register the new handler and adaptor
      //
      startup.registerConstructor('HTMLHandler', ShadowHandler);
      startup.registerConstructor('browserAdaptor', () => new ShadowAdaptor(window));

      //
      //  A service function that creates a new MathDocument from the
      //  shadow root with the configured input and output jax, and then
      //  renders the document.  The MathDocument is returned in case
      //  you need to rerender the shadowRoot later.
      //
      MathJax.typesetShadow = function (root) {
        const InputJax = startup.getInputJax();
        const OutputJax = startup.getOutputJax();
        const html = mathjax.document(root, {InputJax, OutputJax});
        html.render();
        return html;
      }

      //
      //  Now do the usual startup now that the extensions are in place
      //
      MathJax.startup.defaultReady();
    }
  }
};
```

**Comment by jxxcarlson** [comment]
**A couple of comments.**

I tried replacing the import by `<script src="https://rawcdn.githack.com/mathjax/mj3-demos/3.0.0-beta.4/mathjax3/tex-mml-chtml.js"></script>`.

1.  For the displayed math code (`$$...$$`), inspection of the output was interesting:  `#shadow-root (open) ...` with a sibling on the next line that begins `<mjx-container ... `.  It looks to me like the sibling was the MathJax-processed input that should be displayed (and maybe the first element should be *closed*???

2. For the inline math code (`$ ... $`), there was the `#shadow-root (open)` line followed by the verbatim text of the input (`$ ... $`). When I changed the input to `\( ... \)` the results were similar to (1); a sibling that looks like MathJax had processed the input. Hmmm ...

**Comment by jxxcarlson** [comment]
Below is screen shot of one test.  You see two sibling elements, one displaying the source (which is visible in the browser), the other which looks to me like rendered TeX, but which is not visible in the browser.  Thus it looks like TeX rendering is happening (???) but the result is not visible (???).

<img width="613" alt="image" src="https://user-images.githubusercontent.com/679991/64915059-f7a31c80-d723-11e9-8bcd-c57f871ced29.png">

**Comment by dpvc** [comment]
I've had a chance to look into this, and before I present any code, I do want to ask one question, which is what is the purpose for the custom elements, and in particular, is there a particular reason for using the ShadowDOM?  I ask because MathJax will render the content of the `<custom-element>` tags just fine when they are in the main document, so there is no need to do anything special to make that happen.

The only reason I can see for using the ShadowDOM would be if you are planning to change the contents of the main window frequently, in which case you need to tell MathJax to drop the math items that it has saved for the mathematics that you have removed from the page (it is easiest to clear the math list entirely), otherwise you will build up math items for expressions that are not longer in the page, wasting memory.  If you use the ShadowDOM, it would have its own math list, and if the custom element is removed, that should allow that list to be freed and the memory reclaimed.  But I'm not sure the overhead of the ShadowDOM is worth it.

If you could say what your purpose is in using a custom element with a ShadowDOM is, then I might be able to give better advice.

-----

If you really want to use ShadowDOM, then here is code that does it:

**custom-element.js:**
```
class CustomElement extends HTMLElement {
  connectedCallback() {
    this.attachShadow({mode: "open"});
    this.shadowRoot.innerHTML =
      '<mjx-doc><mjx-head></mjx-head><mjx-body>' + this.innerHTML + '</mjx-body></mjx-doc>';
    MathJax.typesetShadow(this.shadowRoot);
  }
}

window.addEventListener('DOMContentLoaded', () => customElements.define('custom-element', CustomElement), true);
```
 
Here, we use only the `connectedCallback()`, since we are using the original content, not creating new content.  The custom element isn't registered until the `DOMContentLoaded` event so that the contents of the custom elements will have been parsed and is available for use in the callback.  The callback attaches the ShadowDOM, and sets the contents from the contents of the original DOM, wrapped in some extra elements to mimic the `html`, `head`, and `body` elements of a standard document, since these are not present in the ShadowDOM, and MathJax expects these (it would be possible to do without these, if necessary).

**custom-element-config.js**

```
MathJax = {
  tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]},
  options: {
    skipHtmlTags: {'[+]': ['custom-element']}
  },
  startup: {
    ready: () => {
      //
      //  Get some MathJax objects from the MathJax global
      //
      //  (Ideally, you would turn this into a custom component, and
      //  then these could be handled by normal imports, but this is
      //  just an example and so we use an expedient method of
      //  accessing these for now.)
      //
      const mathjax = MathJax._.mathjax.mathjax;
      const HTMLAdaptor = MathJax._.adaptors.HTMLAdaptor.HTMLAdaptor;
      const HTMLHandler = MathJax._.handlers.html.HTMLHandler.HTMLHandler;
      const AbstractHandler = MathJax._.core.Handler.AbstractHandler.prototype;
      const startup = MathJax.startup;

      //
      //  Extend HTMLAdaptor to handle shadowDOM as the document
      //
      class ShadowAdaptor extends HTMLAdaptor {
        create(kind, ns) {
          const document = (this.document.createElement ? this.document : this.window.document);
          return (ns ?
                  document.createElementNS(ns, kind) :
                  document.createElement(kind));
        }
        text(text) {
          const document = (this.document.createTextNode ? this.document : this.window.document);
          return document.createTextNode(text);
        }
        head(doc) {
          return doc.head || (doc.firstChild || {}).firstChild || doc;
        }
        body(doc) {
          return doc.body || (doc.firstChild || {}).lastChild || doc;
        }
        root(doc) {
          return doc.documentElement || doc.firstChild || doc;
        }
      }

      //
      //  Extend HTMLHandler to handle shadowDOM as document
      //
      class ShadowHandler extends HTMLHandler {
        create(document, options) {
          const adaptor = this.adaptor;
          if (typeof(document) === 'string') {
            document = adaptor.parse(document, 'text/html');
          } else if ((document instanceof adaptor.window.HTMLElement ||
                      document instanceof adaptor.window.DocumentFragment) &&
                     !(document instanceof window.ShadowRoot)) {
            let child = document;
            document = adaptor.parse('', 'text/html');
            adaptor.append(adaptor.body(document), child);
          }
          //
          //  We can't use super.create() here, since that doesn't
          //    handle shadowDOM correctly, so call HTMLHandler's parent class
          //    directly instead.
          //
          return AbstractHandler.create.call(this, document, options);
        }
      }

      //
      //  Register the new handler and adaptor
      //
      startup.registerConstructor('HTMLHandler', ShadowHandler);
      startup.registerConstructor('browserAdaptor', () => new ShadowAdaptor(window));

      //
      //  A service function that creates a new MathDocument from the
      //  shadow root with the configured input and output jax, and then
      //  renders the document.  The MathDocument is returned in case
      //  you need to rerender the shadowRoot later.
      //
      MathJax.typesetShadow = function (root) {
        const InputJax = startup.getInputJax();
        const OutputJax = startup.getOutputJax();
        const html = mathjax.document(root, {InputJax, OutputJax});
        html.render();
        return html;
      }

      //
      //  Now do the usual startup now that the extensions are in place
      //
      MathJax.startup.defaultReady();
    }
  }
};
```

This sets up the DOM adaptor to handle the ShadowDOM.  The `custom-element` tag is added to the `skipHtmlTags` array so that their contents will not be typeset on the initial MathJax typeset pass.  The adaptor is slightly different from the original one in order to locate the proper elements for the head, body, and document root elements that are inserted when the ShadowDOM is created.

**index.html**

```
<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8">
    <script src="custom-element-config.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
    <script src="custom-element.js"></script>

    <style>
      body {
        font-family: sans-serif;
        width: 400px;
        margin: 40px;
      }
    </style>
  </head>

  <body>
    <h1>Custom Element TeX test</h1>

    <p>
      Custom element test:
      <custom-element>
          $a^2 + b^2 = c^2$
      </custom-element>
    </p>

    <p>
      Another test:
      <custom-element>
      \[
        \int_{-\infty}^\infty e^{-x^2} dx = \pi
      \]
      </custom-element>
    </p>

  </body>
</html>
```

Note that the `custom-element.js` file can be loaded in the document `head` because of the use of the event handler to declare the custom element.

**Comment by jxxcarlson** [comment]
Hi Davide, 

Thanks so much for taking a look at this.  First, the big news — after a bit of experimentation and a few code changes — it works!  This is a very big deal for my little project. Thanks again!!

You can see the results here:

	https://markdown.minilatex.app/

I will be integrating this into my other projects soon.  One very good side effect is that there
is no jumping or jittering of the rendered text while the user is eding a formula.

About custom elements.  My understanding of custom elements is not sufficient to answer your question except to say that indeed the contents of the window are changed frequently during live editing.  That said, the extent of the document where those changes occur is generally limited, since we humans operate on a few fragments of text that are close to each other.  

There are in fact two use cases — an author editing the page and someone else reading it but making no changes to it.  But it would be a pain, unless truly necessary, to treat the two cases differently.

As for the shadow DOM specifically, I am not sure, but I think it is necessary to use it,  Elm runs a VDOM system, and is very persnickety about anyone chaning the DOM on their own.  In any case the original custom element with shadow Dom solution is not min, but Luke Westby, and engineer at a startup that is probably the beggist user of this language — over 300,000 loc.  I had to modify the code somewhat for the present use case. 

I will ask Luke to explain this to me.

Best, 

Jim

**Comment by jxxcarlson** [comment]
I've migrated one other project (knode.io) to MathJax 3 with the custom element setup.  All working beautifully.  In addition to much faster rendering, I notice that while editing math text, even deep in the document, it doesn't jump and jitter as we with MathJax 2.7.*

**Comment by jxxcarlson** [comment]
I found one little glitch, which is that math-mode macros in the body of the document are not propagated to the custom element. Perhaps this is because the text of each custom element lives in its own world, with no communication with others.  Is there a way around this?  Perhaps a way to "feed" the custom element with macro definitions.  I've attached the current custom element definition.

Thanks!

```
class MathText extends HTMLElement {

   // The paragraph below detects the
   // argument to the custom element
   // and is necessary for innerHTML
   // to receive the argument.
   set content(value) {
  		this.innerHTML = value
  	}

  connectedCallback() {
    this.attachShadow({mode: "open"});
    this.shadowRoot.innerHTML =
      '<mjx-doc><mjx-head></mjx-head><mjx-body>' + this.innerHTML + '</mjx-body></mjx-doc>';
    MathJax.typesetShadow(this.shadowRoot);
  }
}

customElements.define('math-text', MathText)
```

**Comment by jxxcarlson** [comment]
Well, it is strange.  In one app, math-mode macros are rendered just fine, in the other not.  Both are using MathJax3.  There are some differences in how the MiniLaTeX library is used, so it must be my code.  I'll reclose this and investigate further

**Comment by dbatiste** [comment]
@dpvc thanks for putting this together.  I am in the process of trying to get this to work, however I am currently running into a couple issues, and I am hoping you may be able to advise.  

First I should mention that we have well defined use cases for using MathJax in shadowDOM - our apps are comprised of many web components, and in many instances they are nested within each other.  Many of these components make API calls and then populate their shadowDOMs with other components.  I can describe more if it is helpful, but it seems like this adapter component would be worthwhile to provide as part of MathJax.

Our tech of choice for building components is LitElement.  LitElement renders empty HTML comments (`<!---->`) within the shadowRoot to demarcate binding locations for properties, and the presence of such a comment as the first child seems to cause a JavaScript error in MathJax, preventing further processing.  While we are using LitElement, it can be reproduced with the vanilla component used in the previous comments on this thread.
``` javascript
this.shadowRoot.innerHTML = '<!----><mjx-doc><mjx-head></mjx-head><mjx-body>' + this.innerHTML + '</mjx-body></mjx-doc><!---->';
```
and the error:
```
Uncaught TypeError: t.getAttribute is not a function
    at ShadowAdaptor.e.getAttribute (tex-mml-chtml.js:1)
    at t.handleContainer (tex-mml-chtml.js:1)
    at t.find (tex-mml-chtml.js:1)
    at e.findMath (tex-mml-chtml.js:1)
    at Object.renderDoc (tex-mml-chtml.js:1)
    at e.renderDoc (tex-mml-chtml.js:1)
    at e.t.render (tex-mml-chtml.js:1)
    at Object.MathJax.typesetShadow (html-block.js:102)
    at HTMLElement.connectedCallback (html-block.js:177)
    at html-block.js:181
```

I have another issue where legacy Edge doesn't appear to be running the `ready` callback for the startup, and the MathJax object doesn't appear to have the `typeset()` method. I am suspicious that for legacy Edge, my configuration is running too late.

Many thanks,
Dave
