### ISSUE TITLE
Upgrading from v2.7 to v3 -- renderActions.find override breaks rendering

### ISSUE THREAD

**Issue by SaswatPadhi** [mathjax/MathJax#2199]
Hello,

I followed the [Upgrading from v2 to v3 guide](https://docs.mathjax.org/en/latest/upgrading/v2.html), and as per the last bullet under the [Changes in the MathJax API](https://docs.mathjax.org/en/latest/upgrading/v2.html#changes-in-the-mathjax-api) section, I modified the `renderActions.find`. My config is as shown below:

```html
      <script>
        MathJax = {
          options: {
            renderActions: {
              find: [10, function (doc) {
                for (const node of document.querySelectorAll('script[type^="text/tex"]')) {
                  const display = !!node.type.match(/; *mode=display/);
                  const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
                  const text = document.createTextNode('');
                  node.parentNode.replaceChild(text, node);
                  math.start = {node: text, delim: '', n: 0};
                  math.end = {node: text, delim: '', n: 0};
                  doc.math.push(math);
                }
              }, '']
            }
          },
          tex : {
            tags: 'ams',
            inlineMath : [ ['$','$'] ],
            processEscapes : false,
            processEnvironments : false,
            processRefs : false,
          }
        };
      </script>
      <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-chtml.js"></script>
```

After this change, the inline math `$ x $` is no longer rendered. The `text/tex` scripts are correctly located and rendered, but the inline math that used to be rendered is no longer rendered. Upon removing this override for `renderActions`, things work as expected.

**Comment by dpvc** [comment]
Your code is replacing the usual `find` action (the one that locates dollar delimiters and such) with a replacement that looks for `<script>` tags instead.  If you want to do both actions, then there are two options.

First, you could change

```
 find: [10, function (doc) {
```

to 

```
 findScripts: [11, function (doc) {
```

so that the original `find` action is not replaced, and your action is added as a new one that occurs just after the original.

Alternatively, you can add

```
doc.findMath();
```

at the beginning or end of your replacement `find` action in order to do the usual find operation in addition to your script finding.

**Comment by SaswatPadhi** [comment]
Perfect! Thank you -- both solutions work for me.

It would be nice if the upgrading guide specified this as well.

**Comment by dpvc** [comment]
I updated the documentation a while back, so am closing this issue.
