### ISSUE TITLE
[SVG][v3] RTL support for v3

### ISSUE THREAD

**Issue by parhizkari** [mathjax/MathJax#2204]
Hi, v.2 of MathJaX was fine to render math in RTL divs, but v.3 seems to have problem doing so. The problem is with accurate placement of non-English characters and digits in math. The following code shows the problem:
```
<!DOCTYPE html>
<html dir="rtl" lang="fa">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script>
window.MathJax = {
    tex: {
    	inlineMath: [ ["$","$"] ],
	displayMath: [ ["$$","$$"] ],
	processEscapes: true,
        tags: "ams"
    },
    svg: {
	mtextInheritFont: true
    }
};
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js">
</script>
</head>
<body>
ابتدا داریم: $۱+\tan(\alpha)^۲=\frac{۱}{\cos(x)^2}$، سپس داریم$$\int_\text{الف}^b f(x,\tau,\epsilon)\,dx\qquad\text{بدون شماره‌گذاری}$$و نهایتاً هم خواهیم داشت:\begin{align}
&۱۳۲۴۵٫۲\times ۱٬۳۴۴.۶۷\times۱۳٬۴۵.۶\sin(x)\,\frac{\alpha_{32}}{\beta}\;\frac{\alpha_{۳۲}}{\beta}\tag{*}\\
&\xrightarrow{x^۵}\sinh(x)\qquad \text{with AMS number}
\end{align}
</body>
</html>
```
I can use an LTR wrapper around the equations and math environments to resolve the problem, so not really a bug, but the code woulf be cleaner if Mathjax dose this by itself, like in v.2.

**Comment by dpvc** [comment]
This seems to be specific to the SVG output.  One option would be to switch to the CommonHTML output for now.

If you add

```
<style>
mjx-container {
    direction: ltr
}
</style>
```

to the page, is the output correct?

**Comment by parhizkari** [comment]
Yes, thank you, it solved the problem for svg output that I use.

**Comment by dpvc** [comment]
Great.  Thanks for the confirmation.
