### ISSUE TITLE
 How to check user entered LaTeX information

### ISSUE THREAD

**Issue by itexsolution** [mathjax/MathJax#2205]
When input in LaTeX, in v2, after rendering, the `<script type = "math/tex">` tag contained LaTeX information entered by the user. 
But in v3 I can't find both chtml and svg. 
TeX information seems to be stored somewhere, as seen from the context menu "Show math As> TeX Command".

How can I check the LaTeX information entered by the user?

Thank you.

**Comment by dpvc** [comment]
MathJax version 3 no longer stores information in the page itself.  Instead, it uses an internal list to store information about the mathematics in the page.  The list is stored at `MathJax.startup.document.math`, and it is iterable, so you can use

```
for (const item of MathJax.startup.document.math) {
   // your code here
}
```

or if you prefer

```
var math = Array.from(MathJax.startup.document.math);
for (var i = 0; i < math.length; i++) {
  var item = math[i];
  // your code here
}
```

Within the loop, `item.math` will hold the original TeX code for the math item, and `item.typesetRoot` will be a pointer to the `mjx-container` element for the typeset math.  you can use that to associate the `item` with its typeset expression in the page.

**Comment by itexsolution** [comment]
It was very helpful.

thank you!!
