### ISSUE TITLE
chrome and opera browsers don't show the formula's in the correct way for RTL languages

### ISSUE THREAD

**Issue by fardina** [mathjax/MathJax#2211]
Hi
Recently in `chrome` and `opera` browsers inline formulas float to the beginning of the line. For example when I want to write
`اتحاد $e^{i\pi}=-1$ اویلر`
 the expected behaviour is:
![right](https://user-images.githubusercontent.com/13521621/66230079-38250300-e6f0-11e9-8c68-4219b959596b.png)

but at the moment it is like:
![wrong](https://user-images.githubusercontent.com/13521621/66230082-3b1ff380-e6f0-11e9-8118-6ea088a1f294.png)

As you can see the formula floats to the beginning of the line.
You can reproduce this issue by creating a `p` element with property `direction:rtl`.
my configuration:
```
<script type="text/x-mathjax-config">
                MathJax.Hub.Config({"HTML-CSS": { preferredFont: "TeX", availableFonts: ["STIX","TeX"], linebreaks: { automatic:true }, EqnChunk: (MathJax.Hub.Browser.isMobile ? 10 : 50) },
                    tex2jax: { inlineMath: [ ["$", "$"], ["\\\\(","\\\\)"] ], displayMath: [ ["$$","$$"], ["\\[", "\\]"] ], processEscapes: true, ignoreClass: "tex2jax_ignore|dno" },
                    TeX: {
                        extensions: ["begingroup.js"],
                        noUndefined: { attributes: { mathcolor: "red", mathbackground: "#FFEEEE", mathsize: "90%" } }, 
                        Macros: { href: "{}" } 
                    },
                    messageStyle: "none",
                    
                    styles: { ".MathJax_Display, .MathJax_Preview, .MathJax_Preview > *": { "background": "inherit" } }
            });
            </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML-full">
 </script>
```

Thanks.

**Comment by dpvc** [comment]
This may be related to #2190.  Try adding

```
    '.MathJax_Preview': {display: 'contents'}
```

to your `styles` configuration block and see if that resolves the issue.

**Comment by fardina** [comment]
@dpvc Thanks, that resolves the issue.
