### ISSUE TITLE
[v3] how can I manual trigger mathjax render

### ISSUE THREAD

**Issue by tangxu2424** [mathjax/MathJax#2212]
I wanna trigger mathjax render when my tui-editor change event is triggered

**Comment by dpvc** [comment]
See the [documentation](http://docs.mathjax.org/en/latest/web/typeset.html), as well as the [interactive examples](https://github.com/mathjax/MathJax-demos-web#processing-user-input), in particular [this one](https://github.com/mathjax/MathJax-demos-web/blob/master/input-tex_mml2chtml.md).
