### ISSUE TITLE
 How can I manual modify mathjax renderActions with SVG Output

### ISSUE THREAD

**Issue by views63** [mathjax/MathJax#2217]
such as http://docs.mathjax.org/en/latest/output/mathml.html, bug not have API MathJax.startup.toSVG

**Comment by dpvc** [comment]
It is not clear what you are asking to do.  Can you be more explicit about what you want your page to accomplish?

Also, this issue tracker is for reporting bugs in MathJax.  It is better to use the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) for asking general questions.  More people will see your question, so you may be more likely to get an answer there.

**Comment by dpvc** [comment]
You can use

```
<script>
function addContainer(math, doc) {
  const tag = math.display ? 'section' : 'span';
  const cls = math.display ? 'block-equation' : 'inline-equation';
  math.typesetRoot = doc.adaptor.node(tag, {class: cls}, [math.typesetRoot]);
}
MathJax = {
  options: {
    renderActions: {
      addContainer: [190, (doc) => {for (const math of doc.math) {addContainer(math, doc)}}, addContainer]
    }
  }
};
</script>
```

just *before* the script that loads MathJax to accomplish this.  

Note, however, that this probably is not an appropriate use for the `section` tag.  See the documentation for [section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element), which says:

> The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element's contents would be listed explicitly in the document's outline.

**Comment by views63** [comment]
> 
> 
> You can use
> 
> ```
> <script>
> function addContainer(math, doc) {
>   const tag = math.display ? 'section' : 'span';
>   const cls = math.display ? 'block-equation' : 'inline-equation';
>   math.typesetRoot = doc.adaptor.node(tag, {class: cls}, [math.typesetRoot]);
> }
> MathJax = {
>   options: {
>     renderActions: {
>       addContainer: [190, (doc) => {for (const math of doc.math) {addContainer(math, doc)}}, addContainer]
>     }
>   }
> };
> </script>
> ```
> 
> just _before_ the script that loads MathJax to accomplish this.
> 
> Note, however, that this probably is not an appropriate use for the `section` tag. See the documentation for [section](https://html.spec.whatwg.org/multipage/sections.html#the-section-element), which says:
> 
> > The section element is not a generic container element. When an element is needed only for styling purposes or as a convenience for scripting, authors are encouraged to use the div element instead. A general rule is that the section element is appropriate only if the element's contents would be listed explicitly in the document's outline.

it's good, thanks you. use the `section`  tag is for the special website ([Tencent WebChat blogs](https://mp.weixin.qq.com/)) Best compatibility tag is ‘section’.
