### ISSUE TITLE
Does version 3 support <script type="math/tex">?

### ISSUE THREAD

**Issue by memakura** [mathjax/MathJax#2220]
It seems Mathjax version 3 does not render <script type="math/tex">, which was supported in version 2. (https://docs.mathjax.org/en/v2.7-latest/advanced/model.html#how-mathematics-is-stored-in-the-page)

I found this when I used Github Pages to convert a markdown file with $$...$$. The markdown file was processed on the Github server, but nothing was rendered with Mathjax v3 (v2 had no problem). I also checked this locally with Jekyll and found that $$...$$ in a markdown file is converted to <script type="math/tex; mode=display">…</script> before processed by Mathjax.

I was wondering whether this is an expected behavior in v3 or not. If so, are there any options to turn on the rendering of <script type="math/tex">?

The following is for a simple test.
```html
<script async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/tex-chtml.js" id="MathJax-script"></script>
<!-- <script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS_CHTML"></script> -->

<p><script type="math/tex">ax+by+c=0</script></p>
<script type="math/tex; mode=display">\sum_{i=1}^n x_i</script>
```

**Comment by dpvc** [comment]
This is the expected behavior in version 3.  See the last bullet point in the [changes to the API](http://docs.mathjax.org/en/latest/upgrading/v2.html#changes-in-the-mathjax-api) section of the upgrading to v3 documentation.  This gives a configuration that will process the scripts that you are using.

**Comment by memakura** [comment]
Thank you so much for the information. This is exactly what I was looking for. Adding the following script successfully processed html files generated by Jekyll (from both html and markdown files).
```javascript
MathJax = {
  options: {
    renderActions: {
      /* add a new named action not to override the original 'find' action */
      find_script_mathtex: [10, function (doc) {
        for (const node of document.querySelectorAll('script[type^="math/tex"]')) {
          const display = !!node.type.match(/; *mode=display/);
          const math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
          const text = document.createTextNode('');
          node.parentNode.replaceChild(text, node);
          math.start = {node: text, delim: '', n: 0};
          math.end = {node: text, delim: '', n: 0};
          doc.math.push(math);
        }
      }, '']
    }
  }
};
```

**Comment by opeltre** [comment]
Would you consider making this a simple option switch?

**Comment by dpvc** [comment]
@opeltre, No, but it could be made an extension you could load.

**Comment by Domiii** [comment]
For anyone still looking: @memakura's code just kinda works very well and out of the box :)
