### ISSUE TITLE
Superscript of \sum cannot be rendered properly

### ISSUE THREAD

**Issue by memakura** [mathjax/MathJax#2221]
When I use `\sum_{i=1}^{n} x_i` without other equations, it seems the superscript `n` cannot be rendered properly. (`n` becomes a subscript together with `i=1`.)
But when I use the equation with other symbol, such as `\int_a^b`, it works.

```html
<!DOCTYPE html>
<html lang="en-US">
<head>
    <script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script"></script>
    <!-- <script async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS_CHTML"></script> -->
</head>
<body>

<p>When I use only this line, the superscript in \(\sum_{i=1}^{n} x_i\) does not work.</p>
<!-- <p>When I use only this line, the superscript in \(\sum_{i=1}^{n} x_i, \int_a^b\) works.</p> -->

<!-- <p>\(\int_a^b\) has no problem.</p> -->

</body>
</html>
```

**Comment by dpvc** [comment]
I have made a pull request that resolves this problem.

**Comment by YohnWang** [comment]
I have found that `\prob` has the same problem in inline math.
And wherever `\int_a^b`  occur ,this problem will disappear.

**Comment by dpvc** [comment]
@YohnWang, yes, any operator will show the same issue.  It is taken care of in the pull request listed above.

**Comment by owlstead** [comment]
It still seems a problem on GitHub itself, probably due to using an older implementation. However, there seems to be a workaround: use `\sum\limits_{i=0}^n i`: $\sum\limits_{i=0}^n i$.

**Comment by dpvc** [comment]
@owlstead, the GitHub issue is a different cause: GitHub is filtering out attributes from the MathJax output and one of the attributes that it removes is critical to the proper placement of the summation sign, which is out of place when that attribute is removed by GitHub.  They are using version 3.2.0, which is relatively recent, and does not have the bug reported here.  The GitHub problem is a different cause.

**Comment by owlstead** [comment]
@dpvc  Ah, yeah, wrong repo I guess, I found a further discussion [here](https://github.com/community/community/discussions/17051?sort=top). Not sure why that isn't a bug report.
