### ISSUE TITLE
To blank space with mhchem

### ISSUE THREAD

**Issue by views63** [mathjax/MathJax#2223]
Issue Summary

Steps to Reproduce

Go to the MathJax demo site
Paste the following equation in:

$$\ce{2H2 + O2 ->T[燃烧] 2H2O} $$

Click the "Render HTML" button.

![图片](https://user-images.githubusercontent.com/175116/67097990-de433380-f1ed-11e9-8fd0-37ff753a8b22.png)

with mathjax 2：

![图片](https://user-images.githubusercontent.com/175116/67097890-a9cf7780-f1ed-11e9-8507-0e58ae5f89ff.png)

Technical details
Client OS: Windows 10 64 bit
Browsers: Firefox (69.03 (64-bit))

**Comment by dpvc** [comment]
I'm not sure what the issue is you are reporting.  Is it the difference in spacing of the characters over the arrow?  This may be due, in part, to the difference in the font being used in the two cases.  I am not actually able to reproduce your v2 output.  My results all look like the v3 output (more vertical space).

**Comment by views63** [comment]
> 
> 
> I'm not sure what the issue is you are reporting. Is it the difference in spacing of the characters over the arrow? This may be due, in part, to the difference in the font being used in the two cases. I am not actually able to reproduce your v2 output. My results all look like the v3 output (more vertical space).

yes, more vertical space of the characters over the arrow. the other one is latex with mhchem package. compare v3 and v2: $\ce{A ->[H2O] B}$

![图片](https://user-images.githubusercontent.com/175116/67137313-7fb99c00-f265-11e9-8ae7-b09649d1caf4.png)

**Comment by dpvc** [comment]
I am not able to reproduce your result.  This is what I see:

<img width="432" alt="v2-v3" src="https://user-images.githubusercontent.com/432782/67159803-b4862b80-f317-11e9-8cbb-11eb32336094.png">

Here, the black is v2 and the white is v3.  This is on MacOS and Firefox 69.0.1, with CommonHTML output.

What specific version of 2.x.y are you using?  And what version of mhchem?  (Use the About MathJax item in the v2 contextual menu to find out.)  Which output renderer are you using?

**Comment by views63** [comment]
> 
> 
> I am not able to reproduce your result. This is what I see:
> 
> <img alt="v2-v3" width="432" src="https://user-images.githubusercontent.com/432782/67159803-b4862b80-f317-11e9-8cbb-11eb32336094.png">
> 
> Here, the black is v2 and the white is v3. This is on MacOS and Firefox 69.0.1, with CommonHTML output.
> 
> What specific version of 2.x.y are you using? And what version of mhchem? (Use the About MathJax item in the v2 contextual menu to find out.) Which output renderer are you using?
 
the mwe: 

mathjax 2.7.5+mathjax-mhchem 3.3.2

```html

  <script type="text/x-mathjax-config">
    MathJax.Ajax.config.path["mhchem"] = "https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.2";
    MathJax.Hub.Config({
      tex2jax: {
        ignoreClass: "tex2jax_ignore",
        inlineMath: [["$","$"]]
      },
      TeX: {
        extensions: ["[mhchem]/mhchem.js", "color.js"],
        noErrors: { disabled: true }
      },
      SVG: {
          useFontCache: false,
      }
    });
  </script>
  <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script>

  $\ce{A ->[H2O] B}$
```
mathjax 3.0.0:

```html
    <script>
      MathJax = {
        tex: {
          inlineMath: [["$", "$"]],
        },
        svg: {
          fontCache: "none",
        },       
      };
    </script>
    <script
      type="text/javascript"
      id="MathJax-script"
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
    ></script>

  $\ce{A ->[H2O] B}$
```

copy the svg source save to 2.svg and 3.svg. use imagemagick with : `magick convert -density 1000 2.svg 2.png` `magick convert -density 1000 3.svg 3.png` compare  2.png with 3.png.
