### ISSUE TITLE
Add multiple classes when creating nodes (parse.create method)

### ISSUE THREAD

**Issue by gcalmettes** [mathjax/MathJax#2230]
When using the `parser.create` method, how can one assigns multiple classes to a node?

For example, considering the following code:
```
const math = parser.ParseArg(name)
const node = parser.create('node', 'mrow', [math], def)
```

The code will correctly create a node with `class='class1'` when `const def = { class: 'class1' }`.

However, if multiple classes are given (e.g.: `const def = { class: 'class1 class2' }`, the code will fail with error `Failed to execute 'add' on 'DOMTokenList': The token provided ('class1 class2') contains HTML space characters, which are not valid in tokens." `

Using an array of classes in the definition (e.g.: `const def = { class: ['class1', 'class2'] }`) will not fail, but the classes are concatenated into one string `class='class1,class2'`.

Is there any way around this to create a node with `class='class1 class2'`?
Thanks!

**Comment by dpvc** [comment]
This is a duplicate of #2185, for which there is an open PR already (mathjax/MathJax-src#340).  Does that PR meet your needs?

**Comment by gcalmettes** [comment]
@dpvc Yes, [mathjax/MathJax-src#340](https://github.com/mathjax/MathJax-src/pull/340) fixes this behavior. 
Closing this issue (and [(mathjax/MathJax-src#378](https://github.com/mathjax/MathJax-src/pull/378)) since it is a duplicate.
Thanks!
