### ISSUE TITLE
how to without \tag use ref or eqref

### ISSUE THREAD

**Issue by views63** [mathjax/MathJax#2234]
user scenario：page width is 300px and the equation width is 400 in output svg, set the parent node `overflow:auto`. but use `\tag` the equation width is 100%， the number and the equation body overlapping. so, I use `\qquad() ` replace `\tag`, but it can't use 'ref'  reference equation bumber

**Comment by dpvc** [comment]
What version of MathJax are you using?  Equation numbers should not overlap the equations in the latest 2.7 or 3.0 versions (though they could in earlier versions of 2.7).  If you are having this happen in 2.7.6 or 3.0.0, can you provide an example page in jsFiddle or codebin or one of the other page testing services?

**Comment by views63** [comment]
> 
> 
> What version of MathJax are you using? Equation numbers should not overlap the equations in the latest 2.7 or 3.0 versions (though they could in earlier versions of 2.7). If you are having this happen in 2.7.6 or 3.0.0, can you provide an example page in jsFiddle or codebin or one of the other page testing services?

I use Mathjax 3.0. eg:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
    <style>
        body {
            margin: 0 auto;
            width: 300px;
        }

        div {
            width: 100% !important;
            background: gray;
        }
    </style>
</head>
</head>
<body>
    <div>
        $$\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\tag{11}$$
    </div>
</body>
</html>
```

**Comment by dpvc** [comment]
OK, thanks.  This is resolved by PR mathjax/MathJax-src#354, which will be included in the next release.  So I'm marking this as a duplicate.

**Comment by views63** [comment]
> 
> 
> OK, thanks. This is resolved by PR [mathjax/MathJax-src#354](https://github.com/mathjax/MathJax-src/pull/354), which will be included in the next release. So I'm marking this as a duplicate.

the  mathjax/MathJax-src#354 is different target with me. My targe is keep the nomal size(no zoom out) with the too long equation (has tag number) and I can  reference  them.

**Comment by dpvc** [comment]
I understand, but the solution is the same.  I have tested with that branch, and it resolves the problem.

**Comment by views63** [comment]
I don't know the effect you made, I want it like this: (used mathjax 2.7.6)
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
            }
        });
    </script>
    <script src="https://cdn.bootcss.com/mathjax/2.7.6/latest.js?config=TeX-AMS-MML_SVG"></script>
    <style>
        body {
            margin: 0 auto;
            width: 300px;
        }

        div {
            width: 100% !important;
            background: gray;
        }
    </style>
</head>
</head>
<body>
    <div>
        $$\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b
        f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\int_a^b f(x)\tag{eq1}\label{q}$$

        $\eqref{q}$
    </div>
</body>
</html>
```
![图片](https://user-images.githubusercontent.com/175116/68522056-1ec03980-02e2-11ea-937f-19e15ac6f6a7.png)

**Comment by dpvc** [comment]
> I don't know the effect you made, I want it like this

That is the result when mathjax/MathJax-src#354 is used.  As I said, the PR applies to both the current text in the document, as well as the zoomed content.
