### ISSUE TITLE
spacing in scripts seems too large

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2241]
The following is an attempt to simulate the MathML spacing rules in scripts:
```
\[\displaystyle x^{(n\>+\>1)(n\>-\>1)}=x^{n^2\>-\>1} \neq x^{n^2}-1
\]\[
\displaystyle\sum_{i\;=\;0}^{\infty} e^{i\>+\>1} \hskip 1em
\displaystyle\int _0^{2\pi}e^{e^{it}\> - \>it}dt \hskip 1em
\displaystyle\int _0^{2\pi}e^{ - it\>+\>e^{it}}dt \hskip 1em
\]\[
\displaystyle \left( \frac{-1}{p} \right) = (-1)^{\frac{p\>-\>1}2}=\ldots 
\]
```

In v2.7, it looks like the spacing amounts are interpreted correctly, but in v3.0, they are too big, perhaps been taken from the displaystyle font, not the scriptstyle font.

2.7 (as rendered in Firefox):
![image](https://user-images.githubusercontent.com/1545836/68627855-b618be80-0493-11ea-856e-cf71fe794585.png)

3.0 (as rendered in Firefox):
![image](https://user-images.githubusercontent.com/1545836/68627824-9f726780-0493-11ea-96e9-5deaa1186274.png)

In the first line, the difference seems particularly obvious around the n+1 and n-1.

For reference, the script tags are:
```
  <script type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML">			 
  </script>
```

and 

```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
It does look like there is a bug there.  I will check into it.

In the meantime, perhaps you can just set the `mathmlSpacing` option of the CHTML output jax:

```
<script>
MathJax = {
  chtml: {mathmlSpacing: true}
};
</script>
```

in order to have MathJax use MathML spacing rules rather than TeX spacing rules.

**Comment by dpvc** [comment]
OK, it turns out that this is due to a bug in the handling of tex classes of the elements, which is being handled by another PR (not yet in place).  So it will be fixed in the next release.

Thanks for the report.

**Comment by NSoiffer** [comment]
Thanks for checking on this.

FYI: The MathML refresh group is formalizing all the layout rules, and one of the ones currently being decided upon is spacing in scripts. I encourage you and anyone else who sees this to take a look at the [issue/samples on github](https://github.com/mathml-refresh/mathml/issues/38#issuecomment-552664086), and add a comment to the issue with your preference.

**Comment by dpvc** [comment]
I was wrong, there was another issue at play, so I've made a new pull request for the fix.
