### ISSUE TITLE
Use a strict version on the mathjax-full dependency

### ISSUE THREAD

**Issue by Mogztter** [mathjax/MathJax#2242]
Currently the `package.json` file is using a git URL:

https://github.com/mathjax/MathJax/blob/fb0d28b5fa6fe6112c25d11ba8b5f6964e700559/package.json#L53-L55

Using git protocol can be an issue for people behind a corporate proxy and I think it's better to use a fixed version rather than using the master branch.
Also do we really need the sources as a dependency? What is the reasoning behind it? Maybe as `devDependencies` but if I just want to use MathJax, this module should be enough right?

**Comment by dpvc** [comment]
You are right, this should just be a dev dependency.  It is only needed for building the distribution files that are part of the final mathjax npm package.  I'll update the `package.json` file.  Thanks for the catch!  There is certainly no need for `mathjax-full` to be installed for people using the `mathjax`.

**Comment by dpvc** [comment]
I've made a pull request for this, and it will be included in the next release.

**Comment by Mogztter** [comment]
Excellent news, thanks @dpvc 👍
