### ISSUE TITLE
Broken NPM package for 2.7.6 release

### ISSUE THREAD

**Issue by idzikovsky** [mathjax/MathJax#2243]
As we discussed in user groups [thread](https://groups.google.com/forum/#!topic/mathjax-users/Hp4UB6pVqDw), NPM package for MathJax 2.7.6 does not includes MathJax.js script in it's content.

So here is a ticket to track this problem.

**Comment by dpvc** [comment]
I've put out v2.7.7 that fixes this problem, so you should be able to update to that.

**Comment by idzikovsky** [comment]
It seems like the problem has been resolved. Thank you!
