### ISSUE TITLE
equation render issue

### ISSUE THREAD

**Issue by varunkn07** [mathjax/MathJax#2245]
There is an issue with some equations shown below. 
![image](https://user-images.githubusercontent.com/20451860/69240140-d77b5800-0bc1-11ea-9a36-280e16079427.png)

It repeats the same variables again without the symbols.

**Comment by dpvc** [comment]
There is not enough information here to diagnose your issue.  Can you provide a link to a live page that contains the issue?  Perhaps a minimal example using jsFiddle or codebin?

From the looks of it, MathJax may have stopped in the middle of its processing.  Are there any error messages in the browser console?

This kind of thing can also happen if you modify the page while MathJax is processing it, or if you call MathJax a second time while the first time is still running (e.g., you aren't using `MathJax.Hub.Queue()` to synchronize your calls to MathJax). 

 Without seeing what you are actually doing in your code, it is difficult to help.

**Comment by varunkn07** [comment]
Issue resolved. That was a mistakes from our side. Now it is working fine. Thanks for your replay.
