### ISSUE TITLE
'\bf{\left\{ \begin{array}{l} {a}\\{a} \end{array}\right.}'Cannot render completely

### ISSUE THREAD

**Issue by lhy666** [mathjax/MathJax#2247]
![image](https://user-images.githubusercontent.com/30484206/69402088-c7828600-0d31-11ea-9f5d-a1bf8f402c97.png)
I hope it's all bold

**Comment by lhy666** [comment]
I find that if there is a "\ \", there will be problems.

**Comment by dpvc** [comment]
Actually, none of it should be bold (it true LaTeX, the `\bf` has no effect on the array), so the first entry should be an italic, non-bold "a" as well.

> I find that if there is a "\ ", there will be problems.

Can you be more specific about what problem you are seeing?

**Comment by lhy666** [comment]
Thank you for your answer. usually,I am used to use '\bf' when i need bolding something. 
like '\bf a' and '\bf \sqrt{a^2+b^2}'. now I just want to know how to bold '\begin{array}{l} {a}\\{a} \end{array}\right.
like:
![image](https://user-images.githubusercontent.com/30484206/69474605-4ba23f80-0dfe-11ea-9760-cbf4b9ff79e5.png)
not:
![image](https://user-images.githubusercontent.com/30484206/69474626-5bba1f00-0dfe-11ea-9ede-4aa624336fff.png)

**Comment by lhy666** [comment]
Oh, I see. the ' \bf' has no effect on the array, if i want this:
![image](https://user-images.githubusercontent.com/30484206/69475084-d9345e00-0e03-11ea-97e4-763f9b166ebb.png)
I should write like this ‘\left\{ \begin{array}{l}  \bf{a}\\ \bf{a} \end{array}\right.’
thank you very much.
