### ISSUE TITLE
[v3] Arrays inside left and right brackets render misaligned

### ISSUE THREAD

**Issue by drgrice1** [mathjax/MathJax#2249]
A minimal example is:

```
<script>id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"</script>
<span>\(\left[\begin{array}{cc} -8 &amp; 4\cr 0 &amp; 7 \end{array}\right]\)</span>
```

This yields:

![matrix](https://user-images.githubusercontent.com/47527406/69678591-a1c7ea80-106b-11ea-9be6-f658ae5db14a.png)

The numbers in the array are not correctly aligned with the brackets.

**Comment by dpvc** [comment]
I am not able to reproduce the result.  Can you give the browser and OS (and versions) that you are using?  Also, does this happen for you also in this [interactive example](https://mathjax.github.io/MathJax-demos-web/input-tex2chtml.html)?

**Comment by drgrice1** [comment]
It seems to work in Google chrome. The browser that I generated the above image in was the current version of Firefox in the Ubuntu 18.04 repositories. It also occurs in the Firefox browser on Android.

**Comment by drgrice1** [comment]
I have done a little more testing on this, and I have found that the misalignment occurs more frequently than not.  I used the interactive example you linked.  I tested this on Microsoft Windows 10 with several browsers and on all of them the misalignment occurred.  The browsers were version 78.0.3904.108 of Google Chrome, version 68.0esr of Firefox, version 11.239.18362.0 of Miicrostoft Internet Explorer, and version 44.18362.1.0 of Microsoft Edge.

**Comment by dpvc** [comment]
Thanks for the additional information.  I think this is probably the same issue as #2186 and #2203, which is resolved in mathjax/MathJax-src#352 (that's probably why I couldn't reproduce, since I was probably using the branch with that fix already merged).  If you check with a single-line array like $A=\left[\begin{array}{C}A\end{array}\right]$ is it the array or the brackets that are misaligned?  If it is the array, then it is the fix that is already in the PR linked above.

**Comment by drgrice1** [comment]
I think you are probably correct.  Those issues look like they are the same.

So I take it that although this has been merged into https://github.com/mathjax/MathJax-src, it has not been added to https://github.com/mathjax/MathJax yet.  I will build from MathJax-src, just to ensure that it is fixed there.

**Comment by dpvc** [comment]
Yes, you are correct.  It is merged into the MathJax-src `develop` branch, which will become the `master` branch when we do a new release.  We are preparing for 3.0.1 with a number of fixes, but have not made the release yet.

**Comment by drgrice1** [comment]
I tested this using a build of MathJax from the develop branch.  It is fixed there, so I am marking this as closed.
