### ISSUE TITLE
regarding font change.

### ISSUE THREAD

**Issue by rajatssml2** [mathjax/MathJax#2250]
Hi,
I am facing some issues in mathJx. When I have not selected any font from wiris editor and it's rendering through mathJx it's not showing the proper font that I have selected from wiris editor. 
For example:
**From wiris editor:**
![wiris](https://user-images.githubusercontent.com/46716864/69697744-5f54eb00-1109-11ea-8193-a9d72a56e89f.png)
**passing the math HTML:**
`<p><math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mi>a</mi><mi>w</mi><mi>s</mi><msqrt><mn>23</mn><mi>a</mi><mi>w</mi><mi>s</mi></msqrt></math></p> `
**Rendering from mathJx:**
![mathjx](https://user-images.githubusercontent.com/46716864/69697798-97f4c480-1109-11ea-8c98-157edb7284ca.png)
If you see the font is different.
I have used CDN: 
[https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML](url)

Please help me to get the same font.

Thank you.

**Comment by rajatssml2** [comment]
I am waiting for your update.

**Comment by dpvc** [comment]
MathJax only supports a limited number of fonts (MathJax needs to know a lot of information about the font, and that has to be build into MathJax; data is available only for a handful of fonts).

Note that the MathML that you are passing to MathJax contains no font information at all, so MathJax will use its default font (or the one that you include in your MathJax configuration, which you have not provided).  It is possible to add `fontfamily="sans-serif"` to the `<math>` element, but this will likely lead to poor layout (MathJax doesn't have the bounding box information about the font) and slow rendering (MathJax will have to try to measure the widths of all the characters, which causes page reflows).  So this is not a great approach.

There is a description of how to [configure MathJax to use sans-serif fonts for text](https://github.com/mathjax/mathjax-docs/wiki/Can-MathJax-use-font-xxxx%3F) that you might be able to use if you are only concerned with using sans-serif for letters and numbers, but don't care too much about which sans-serif font it it.
