### ISSUE TITLE
mathjax can not render "\parallelogram"

### ISSUE THREAD

**Issue by lhy666** [mathjax/MathJax#2254]
Please give me some support...i want to render "\parallelogram". like: 
[image](https://user-images.githubusercontent.com/30484206/70135943-f865a200-16c5-11ea-92bc-cf55c9ac3445.png)

mathquill is supported

**Comment by dpvc** [comment]
The MathJax fonts don't include this symbol, but you can use

    \unicode{x25B1}

to request the parallelogram unicode character.  The results will vary depending on the fonts available on your reader's computer, both in terms of its size, and its positioning.

You can do something like

    \lower.2em{\Large\unicode{x25B1}}

to change the location and size of the character, but again, the results will vary from user to user.

It is possible to do some CSS tricks to make a parallelogram from the `\square` glyph, such as

    \mathord{\style{transform:translate(.2em, .1em) scale(1.5, .7) skewX(-20deg}{\square}}

This will likely produce more consistent output, though it is not as semantically meaningful, and will produce wrong spoken output for those using screen readers, for example.

For any of these, you can define `\parallelogram` to be the desired definition, e.g.,

    \def\parallelogram{\unicode{x25B1}}

If you control the MathJax configuration on the site you are using, you can add

    tex: {
      macros: {
        parallelogram: '\\unicode{x25B1}'
      }
    }

to your configuration (in v3) or

    TeX: {
      Macros: {
        parallelogram: '\\unicode{x25B1}'
      }
    }

(in v2) to predefine the macro.

**Comment by dpvc** [comment]
Note:  this issue tracker is for reporting bugs in MathJax.  General questions should be address to the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see it and may be able to help you.
