### ISSUE TITLE
V3: activating accessibility results in "Math input error"

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2255]
Visit the page `https://mathjax.github.io/MathJax-demos-web/mml-chtml.html`. It renders well. Right click on some math, choose Accessibility:Activate. The math is now replaced by "Math input error". Here's a small snippit:
![image](https://user-images.githubusercontent.com/1545836/70194704-2c39cb00-16b8-11ea-86c7-aba1f54a8196.png)

The page's heading says "...v3 beta...", but it appears to link to the V3 release. Here's the script tags from the page:
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
--
  | <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
Thanks, I can confirm the behavior.  I'll check into it.

**Comment by dpvc** [comment]
I'll also update the page titles.  Thanks!

**Comment by dpvc** [comment]
Note that reloading the page displays properly and has the accessibility features activated.  So the problem is somewhere in the updating of the page to add/remove accessibility.

**Comment by zorkow** [comment]
This only happens for MathML input, i.e., `mml-svg.html` and `mml-chtml.html` pages. TeX works fine.

Just FYI: The issue is filed in the wrong repo.

**Comment by dpvc** [comment]
> Just FYI: The issue is filed in the wrong repo.

@zorkow, I don't agree.  What repository did you have in mind?

**Comment by zorkow** [comment]
`mathjax-src`

**Comment by dpvc** [comment]
No, we agreed that all issues for MathJax would be tracker here, so that they were easier to search and would all be in one location.  This is what is listed in the [documentation](http://docs.mathjax.org/en/latest/basic/bugs.html), and I've certainly been pointing people here.

**Comment by zorkow** [comment]
Ah, I had recalled it exactly the other way around (i.e,. that we wanted to forward with this to the `-src` repo, automatically if possible). But looking at the doc, you're right, of course.

Well done @NSoiffer ! You've found the right place.

**Comment by dpvc** [comment]
The decision of which to use came down to the fact that all the old v2 issues were here, so to keep everything in one place, this was the natural place to do it.
