### ISSUE TITLE
Mathjax doesn't render in-text equation like $a+b=c$

### ISSUE THREAD

**Issue by lanfeiying** [mathjax/MathJax#2256]
Hi, 
I use MathJax in my HTML file, and I found it doesn't work for in-text equation, such as $a+b=c$. 
For independent equation, it works well, such as $$x+y=z$$.
My web browser is the newest google chrome.

A minimal work example:
```
<!doctype html>
<html lang="en-us">
<head>
    <script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML-full"></script>
    <style type="text/css">
	.main
    {
    	text-align: center; 
    	width: 30%;
    }
    </style>
</head>
<body>
    <div class="main">
        <p>
	    this is a text $a+b=c$. <!-- mathjax doesn't render this in-text equation -->
	    $$x+y=z$$ <!-- this equation works well -->
	</p>
    </div>
</body>
</html>
```

![Screenshot from 2019-12-05 22-13-32](https://user-images.githubusercontent.com/22729258/70278620-887e1700-17ac-11ea-9884-c6e9839dcd34.png)

**Comment by zorkow** [comment]
Three points:
1. The cdn is not longer active, so you are working with a pretty old version for MathJax. See here:
https://www.mathjax.org/cdn-shutting-down/
2. You might want to change from MathJax v2.7.x to the new v3.0.
3. And you need to tell MathJax explicitly what the inline math delimiters are, to prevent confusion when `$` signs are used for other purposes. The following should work:

```html
<!doctype html>
<html lang="en-us">
  <head>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <script>
      MathJax = {
        tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]}
      };
    </script>
    <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script" async></script>
    <style type="text/css">
      .main
      {
      text-align: center; 
      width: 30%;
      }
    </style>
  </head>
  <body>
    <div class="main">
      <p>
	this is a text $a+b=c$. 
	$$x+y=z$$ 
      </p>
    </div>
  </body>
</html>
```

**Comment by lanfeiying** [comment]
> Three points:
> 
> 1. The cdn is not longer active, so you are working with a pretty old version for MathJax. See here:
>    https://www.mathjax.org/cdn-shutting-down/
> 2. You might want to change from MathJax v2.7.x to the new v3.0.
> 3. And you need to tell MathJax explicitly what the inline math delimiters are, to prevent confusion when `$` signs are used for other purposes. The following should work:
> 
> ```
> <!doctype html>
> <html lang="en-us">
>   <head>
>     <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
>     <script>
>       MathJax = {
>         tex: {inlineMath: [['$', '$'], ['\\(', '\\)']]}
>       };
>     </script>
>     <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script" async></script>
>     <style type="text/css">
>       .main
>       {
>       text-align: center; 
>       width: 30%;
>       }
>     </style>
>   </head>
>   <body>
>     <div class="main">
>       <p>
> 	this is a text $a+b=c$. 
> 	$$x+y=z$$ 
>       </p>
>     </div>
>   </body>
> </html>
> ```

Thanks very much for your answer, it works.
