### ISSUE TITLE
The mathjax CDN files too old?!

### ISSUE THREAD

**Issue by DevelopDaily** [mathjax/MathJax#2258]
The mathjax CDN files at the hosting site [https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/](https://cdn.jsdelivr.net/npm/mathjax@3.0.0/es5/) have the same old timestamp "Sat, 26 Oct 1985 08:15:00 GMT", which is obviously too old.

The timestamp doesn't bother me per se, but is the content trustworthy on that site?

**Comment by dpvc** [comment]
Yes, these are the current files.  I don't know what the issue is with the timestamp.  MathJax didn't exist in 1985, so I'm sure what's up with that.

**Comment by DevelopDaily** [comment]
Thanks.
