### ISSUE TITLE
How to set the top and bottom margins globally in mathjax3

### ISSUE THREAD

**Issue by kz16** [mathjax/MathJax#2259]
The following is the HTML codes
```
<!DOCTYPE html>
<head>
   <script>
    MathJax = {
        tex: {
            tags: 'ams', // should be 'ams', 'none', or 'all'
            inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        chtml: {
            scale: 1.,
            displayAlign: 'left', 
        },
    };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>
How to set the top and bottom margins globally in mathjax3? <br>
$(1) a+b=c $<br>
The eq.(1) is too crowded
$$
(2) a+b=c
$$
And eq.(2) is too wide apart.
</body>
</html>
```

The output results

![2](https://user-images.githubusercontent.com/47207168/70390179-a5f8ee00-1a03-11ea-8d03-1b06f469f592.png)

I need the help, thanks a lot

**Comment by dpvc** [comment]
You can add something like:

```
   <style>
   mjx-container[display="true"] {
       margin: .5em 0 ! important
   }
   </style>
```

to your page (or in you CSS file) to override the margin setting for displayed equations.

Note that you can create numbered equations using the `\tag{}` macro, and if you want the tags on the left, use `tagSide: 'left'` in your `text` configuration:

```
   <script>
    MathJax = {
        tex: {
            tags: 'ams', // should be 'ams', 'none', or 'all'
            tagSide: 'left',
            inlineMath: [['$', '$'], ['\\(', '\\)']]
        },
        chtml: {
            displayAlign: 'left'
        },
    };
  </script>
```

Then you can use

```
$$a+b=c \tag{1}$$
```

to get the equations tagged, and with tag on the left-hand side.  Of course, with `ams` tagging, as you have set up, you could also do

```
\begin{equation}
a+b=c
\end{equation}
```

to get the equation to be numbered automatically.

Also, you don't need the `scale: 1.` configuration as that is the default (I have left it out above).

**Comment by dpvc** [comment]
PS, note that the issue tracker is for reporting bugs in MathJax, not for asking general questions about using MathJax.  That is better handled in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people are likely to see your question and answer it.

**Comment by kz16** [comment]
Thanks very much for your help！
