### ISSUE TITLE
[v3][svg][TeX] The spacing of the characters gets messed up for \boldsymbol

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/MathJax#2261]
When I write `\langle \boldsymbol { U I } \rangle ` the spacing of the characters gets messed up: 
![image](https://user-images.githubusercontent.com/31571062/60302957-0bd83a00-98ea-11e9-853d-0bd5f43883a9.png)

` + \boldsymbol{AI}` 

![screenshot-mathjax github io-2019 12 12-10_08_51](https://user-images.githubusercontent.com/32493105/70694081-72e68100-1cc7-11ea-9a1d-3936abb59ee4.png)

**Comment by dpvc** [comment]
Thanks, I can confirm the behavior, and will check into it.

**Comment by dpvc** [comment]
The issue appears to be only if the math is entered in TeX form.  The corresponding MathML renders properly.

**Comment by dpvc** [comment]
This turns out to be an issue with the internal MathML generated by the `\boldsymbol` macro.  I have created a pull request that resolves the problem.
