### ISSUE TITLE
[v3] xmlns missing on Show Math as > MathML code

### ISSUE THREAD

**Issue by philippetrov** [mathjax/MathJax#2264]
With MathJax 2 it was very convenient that you can right-click the formula, select "Show math as... > MathML code", copy and directly paste the code in Microsoft Word - it will immediately render as a Word equation formula.

With MathJax 3 it is no longer the case - it will paste as a regular text.

The issue is coming from the first line. In MathJax 2 it was:

`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">`

while in MathJax 3 it is just:

`<math display="block">`

It looks like Word will not parse the code without xmlns defined.

Can it be included again?

**Comment by dpvc** [comment]
> Can it be included again?

Yes, it was an error that it was missing.  I have added a fix to the pull request that is listed above.  Thanks for reporting the problem.
