### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by ad1tyawagh** [mathjax/MathJax#2265]
[This package](https://www.jsdelivr.com/package/npm/mathjax) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by dpvc** [comment]
The `main` field *is* set in `package.json`.

https://github.com/mathjax/MathJax/blob/91fbc1666f3364e378458341faba607cc5b305e2/package.json#L26

**Comment by dpvc** [comment]
Sorry, you were pointing at the 2.7 version.  The 2.x versions are not true node packages, and don't work in node (they were just for setting up a web site).  Version 3.0 is the current version, and is node compatible, and does have a main entry point, as indicated above.
