### ISSUE TITLE
Incorrect placement of sub/superscripts on delimiters with Windows+Chrome

### ISSUE THREAD

**Issue by sean-fitzpatrick** [mathjax/MathJax#2273]
I'm experiencing a rendering issue with sub and superscripts on non-pairing delimiters, but only when running Chrome on Windows.
This is in a book built using PreTeXt, with MathJax 2.7.5; the book is [available here](http://www.cs.uleth.ca/~fitzpat/apex-calculus/sec_FTC.html) and the problem is visible in Example 5.4.16.
In an example with Fundamental Theorem of Calculus, we have the LaTeX markup `cos(x)\Big|_0^\pi`.
This renders properly on all Linux browsers I've tried, as well as both Firefox and Edge on Windows, and I have reports from colleagues that it's fine on Safari as well.
The problem shows up running Google Chrome version 79 on Windows 10.
Instead of the lower limit (0) appearing as a subscript, and the upper limit (pi) as a superscript, the lower limit appears inline, and the upper limit as a subscript of the lower, as one would get using
`cos(x)\Big|0_\pi`.
You can see the issue [here](http://www.cs.uleth.ca/~fitzpat/wonkylimits.png) for a different problem with similar markup.
I'd ignore it since it's such an isolated case, but Chrome on Windows is a pretty big chunk of the market.

**Comment by dpvc** [comment]
I believe that this is not actually a browser-dependent issue, but is actually issue #2182, which is a problem with the semantic enrichment that is done for assistive technology (the expression explorer).  This is something that you need to turn on via the MathJax contextual menu, and I suspect you have done that in your Chrome browser on Window, but not on the other browsers that you tested.

One work-around for now is to use braces around the vertical bar, as in `\cos(x){\Big|}_0^\pi`.

**Comment by sean-fitzpatrick** [comment]
You're right -- I had turned on accessibility some time ago to show someone that this was possible.
Turning off accessibility fixes the problem. But we should still apply the workaround, since we want things to work for those who need these features.
