### ISSUE TITLE
How can i convert the trignometic functional angles from radian to degree

### ISSUE THREAD

**Issue by vishnusbabu** [mathjax/MathJax#2275]
Hi team, How can i convert the default set _**radian**_ in a trignometric function  to **_degree_**. With a wide search i haven't got any perfect solution.

**Comment by dpvc** [comment]
MathJax doesn't do any computation; it is only about *display* of mathematics.  But if you have computational system where `sin(x)` produces the sine of `x` radians, then `sin((d/180)pi)` will be the sine of `d` degrees.
