### ISSUE TITLE
Bracket and Modulo size varying based on alphabets inside 

### ISSUE THREAD

**Issue by mohanen** [mathjax/MathJax#2276]
## In the below images, while all the brackets and modulo are same yet their size vary in the rendered output

![image](https://user-images.githubusercontent.com/20907037/71553308-874eab80-2a33-11ea-84c8-a01ae98ae650.png)

![image](https://user-images.githubusercontent.com/20907037/71553355-7a7e8780-2a34-11ea-9196-cc0250f5d608.png)

### Input in aciimath
`|vec a * vec b| <= ||vec a|| * ||vec b||`
### Ouput 
![image](https://user-images.githubusercontent.com/20907037/71553402-f8db2980-2a34-11ea-9573-ec0907c45e1d.png)

1. Is this expected behaviour ?
2. Is there any work arounds like using a monospace font ?

**Comment by dpvc** [comment]
> Is this expected behaviour ?

Yes.  AsciiMath converts `|a|` to MathML as

```
<mrow>
  <mo>|</mo>
  <mi>a</mi>
  <mo>|</mo>
</mrow>
```

and in MathML, `<mo>` elements inside an `<mrow>` stretch to the height of the tulles thing in the row.  In the case of something like `vec a`, the normal sized vertical line is tall enough to cover it, but `vec b` is taller than that, so the next size up must be used.

> Is there any work arounds like using a monospace font ?

It doesn't have to do with the font, it has to do with how MathML handles delimiters.

AsciiMath doesn't have a way to control the size of delimiter that is uses (that I know of).  The only thing I can suggest is to use something like `{:||:}vec b{:||:}`, which will prevent the double bars from growing, but doesn't work for single bars.
