### ISSUE TITLE
The symbol तऀ is decomposed into two: त ऀ

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/MathJax#2281]
Is there a way to display the तऀ symbol in a formula?
![screenshot-mathjax github io-2020 01 04-12_38_11](https://user-images.githubusercontent.com/32493105/71764418-59b0a900-2ef0-11ea-8e28-2330125fb002.png)

Please tell me if it is possible to do this.

**Comment by dpvc** [comment]
In order to get combining characters to work, you must set the `mtextInheritFont` property to `true` on the output jax.  So use

```
MathJax = {
  svg: {
    mtextInheritFont: true
  }
};
```

and then use `\text{तऀ}` to get this combined character.

**Comment by OlgaRedozubova** [comment]
Thanks a lot, this works for me.
