### ISSUE TITLE
Crashing rendering for `\text{constructor}`

### ISSUE THREAD

**Issue by OlgaRedozubova** [mathjax/MathJax#2283]
![screenshot-mathjax github io-2020 01 04-13_05_02](https://user-images.githubusercontent.com/32493105/71764653-2885a800-2ef3-11ea-9838-8c084d23ecba.png)

**Comment by OlgaRedozubova** [comment]
Also, this error will happen with:
`constructor, hasOwnProperty, isPrototypeOf, propertyIsEnumerable, toLocaleString, toString, valueOf, __proto__, ...`

**Comment by OlgaRedozubova** [comment]
Possible solution to this problem change:

```
let list = this.nodeLists[property];
```
on
```
    let list;
    for(const key of Object.keys(this.nodeLists)){
      if(key === property){
        list = this.nodeLists[property];
        break;
      }
    }
```

In this function https://github.com/mathjax/MathJax-src/blob/master/ts/input/tex/ParseOptions.ts#L164-L170

**Comment by dpvc** [comment]
Thanks for the suggested fix.  It is actually the fact that `addNode()` is being called when it shouldn't be, so the solution actually lies in `NodeFactory.ts`.  I will make a pull request with a fix.

**Comment by OlgaRedozubova** [comment]
Thanks for your answer, looking forward to your update.
