### ISSUE TITLE
[v3] Some characters don't have italic correction values

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#2286]
Some characters, like `\partial` don't have their italic correction values, which leads to errors in placement, e.g., in `\partial^2` the 2 is too close to the delta.

This is probably due to an error in the code that converted from the v2 data to the v3 data format.  It is not clear how many characters are affected.

**Comment by zorkow** [comment]
I can't see a difference, neither in CHTML nor SVG. I still looks too close for me, at least for the `\partial^2` example.
