### ISSUE TITLE
npm install mathjax : pending!

### ISSUE THREAD

**Issue by ewasos** [mathjax/MathJax#2287]
Hi,

I'm installing mathjax with `npm install mathjax`

And it starting, runnig and pending... on 
`extract:mathjax: sill extract mathjax@latest extracted to folder/node_modules/.staging/mathjax-78bc5b61 `

the installation would never finished..!
Any idea why ??

**Comment by dpvc** [comment]
It works for me, so I'm not sure what to tell you.  If you want version 3, try

    npm install mathjax@3

It looks like when I published an update to 2.7.7, that became the "latest" version, even though 3.0.0 has a higher version.

**Comment by ewasos** [comment]
I solved it.
It was the problem with the acces to the git repository with git@.. link,
I passed this command on my server, and it works now

` git config --global url."https://".insteadOf git:// `
