### ISSUE TITLE
\lim_{\to} not properly typeset in MathJax 3.0

### ISSUE THREAD

**Issue by jano-m** [mathjax/MathJax#2293]
![image](https://user-images.githubusercontent.com/266826/72476819-f998ed00-37a2-11ea-85e8-d4fde7ef40ae.png)
should be
![image](https://user-images.githubusercontent.com/266826/72476869-1f25f680-37a3-11ea-8200-90fabfae9b31.png)
(note incorrect position of the arrow)

**Comment by dpvc** [comment]
Thanks for the report.  I've pushed a pull request to fix the issue.
