### ISSUE TITLE
[v3][svg] \overleftrightarrow{abc} in Mathjax 3

### ISSUE THREAD

**Issue by jano-m** [mathjax/MathJax#2300]
It produces extra horizontal bar between <-> and abc, and prints two errors to console:
```
tex-svg.js:formatted:14429 Error: <svg> attribute width: A negative value is not valid. ("-409")
tex-svg.js:formatted:14429 Error: <svg> attribute viewBox: A negative value is not valid. ("-102.3 -182 -409 865")
```
Remarks: it works fine if the number of chars is less or more than 3 (or perhaps it depends on the total width of those chars)

**Comment by dpvc** [comment]
I am not able to reproduce the error (I do not get negative `width` or negative values in the `viewBox`).  Can you provide a minimal (non-)working example code for this?

**Comment by jano-m** [comment]
Here is a small example that exhibits this issue:
[https://hypatiasys.com/test/mj.html](url)
Note: the problem occurs in Chrome browser, but it works fine in Firefox and Edge, I haven't tested other browsers

**Comment by dpvc** [comment]
OK, got it, thanks.  I'll look into it.

**Comment by dpvc** [comment]
OK, I found the issue and have made a pull request to resolve it.  Thanks for reporting the problem.
