### ISSUE TITLE
Equations render at different sizes at different times.

### ISSUE THREAD

**Issue by csbrown** [mathjax/MathJax#2303]
I am unable to get my equations to render at a consistent size.  Sometimes they are big, sometimes they are small.  Which one seems strangely arbitrary.  Possibly it has to do with my `div`s starting out in a hidden state.  Any advice on workarounds would be helpful.

To recreate, go to my presentation [here](http://schoolofcomputing.southalabama.edu/~cbrown/local_svm_prez/#/30)  Hit the left arrow key about a dozen times.  Notice that the equation at the top changes size.  I guess that MathJax is having a hard time determining what size the surrounding text is (there seems to be some auto-magical logic on that).  Is there a way to disable the auto-scaling logic?  I don't mind telling an individual equation how big to be, but I'm not sure how to do that thing.

MathJax 2.7 (cloudflare CDN)
Firefox 72

**Comment by dpvc** [comment]
I'm not able to reproduce your results, but yes, you are right that MathJax can't determine the font size when the math is inside a container with `display: none`.  See this [discussion](https://github.com/mathjax/mathjax-docs/wiki/Dealing-with-display:none) for more details and some suggestions.

> Is there a way to disable the auto-scaling logic?

Yes, you can set `matchFontHeight: false` in the HTML-CSS and CommonHTML configuration blocks of you MathJax configuration, or switch to the SVG output renderer.
