### ISSUE TITLE
[help] Two problems I encountered when migrating to v3

### ISSUE THREAD

**Issue by reuixiy** [mathjax/MathJax#2319]
Hello,

MathJax v3 is just awesome! :smiley_cat:

However, I encountered the following two problems when I was preparing to migrate to v3:

1. How to add a class to mathjax inline element's parentNode

    - [Reason](https://github.com/theme-next/hexo-theme-next/pull/1314#issuecomment-583705324)
    - [Code in v2](https://github.com/theme-next/hexo-theme-next/blob/68ccfa5f89dda1b2456533eafe6930f91d6f9488/layout/_third-party/math/mathjax.swig#L37-L46)

2. ~~How to remove `<br>` after a mathjax element~~

    - ~~[Reason](https://github.com/theme-next/hexo-theme-next/pull/1314#issuecomment-583705324)~~
    - ~~[Code in v2](https://github.com/theme-next/hexo-theme-next/blob/68ccfa5f89dda1b2456533eafe6930f91d6f9488/layout/_third-party/math/mathjax.swig#L23-L35)~~

    [Solved by CSS](https://github.com/theme-next/hexo-theme-next/pull/1314#discussion_r376763718).

And my current code of v3 is [here](https://github.com/reuixiy/hexo-theme-next/blob/master/layout/_third-party/math/mathjax.swig). Apologies for asking this kind of questions... It's just too difficult for me to implement it...

Looking forward to your reply. Thanks!

**Comment by reuixiy** [comment]
Looks like we solved it by ourselves! Sorry for the bothering tho.

**Comment by dpvc** [comment]
Glad you got it worked out.  I was going to suggest similar CSS for handling the over in your issue 1, but your CSS solution to 2 is better than what I was going to suggest for that.  Thanks for sharing.
