### ISSUE TITLE
Is there a way to output an unwrapped svg?

### ISSUE THREAD

**Issue by t-k-** [mathjax/MathJax#2320]
I am using the following way to generate svg string.
```js
const svg = await jax.tex2svgPromise('\\frac{1}{x^2-1}', {display: true});
svg_str = jax.startup.adaptor.outerHTML(svg)
```
it outputs a svg wrapped with `<mjx-container>` tag, I am thinking that is there any way to get rid of it? I am working on a platform without DOMParser built-in, it would be nice if I can output a svg string directly. Any idea?

**Comment by t-k-** [comment]
I think `jax.startup.adaptor.innerHTML(svg)` will do the job. Problem solved.

**Comment by dpvc** [comment]
This may produce more than just the `svg` element.  In particular, in v3.0.1 (just released), you can also get the hidden MathML that is meant for assistive technology like screen readers.

A more reliable way would be to use

``` javascript
const html = await jax.tex2svgPromise('\\frac{1}{x^2-1}', {display: true});
const adaptor = jax.startup.adaptor;
const svg_str = adaptor.outerHTML(adaptor.tags(html, 'svg')[0]);
```

as this will always get the (first) `svg` element from the container.
