### ISSUE TITLE
Learndash Quiz Import Plugin conflict

### ISSUE THREAD

**Issue by SamDP02** [mathjax/MathJax#2338]
I am uploading a Maths course using the Learndash Quiz Import Plugin from Wooninjas. However, it won't let me import quizzes anymore. I've deactivated the plugin to see if there's a difference, there isn't but I haven't installed any other plugins. It was working fine prior to this. I want to delete it but it doesn't give me an option to delete the plugin without deleting the data too and I've got 50 quizzes that I've uploaded and been working on using this plugin. 

Is there any way to fix this?

**Comment by dpvc** [comment]
I do not see the connection of this to MathJax (whose issue tracker you are using here).  It seems that this is a problem withe Learndash or the plugin that you are using.  You would probably be better served to report the issue to them.  Perhaps the [wooninjas forum](https://wooninjas.com/forums/forum/learndash-quiz-import-export/) would be a good place to start?

**Comment by SamDP02** [comment]
Hi 
I have checked all my plugin and was just about to let you know that plugin is not the issue. Thank you for your quick response. Wooninjas customer support is terrible and I couldn't get through to them so I panicked a little. 
It turns out that their plugin with conflicting with another plugin that I've had installed for a while. 
Get Outlook for Android



On Tue, Feb 18, 2020 at 4:13 PM +0200, "Davide P. Cervone" <notifications@github.com> wrote:












I do not see the connection of this to MathJax (whose issue tracker you are using here).  It seems that this is a problem withe Learndash or the plugin that you are using.  You would probably be better served to report the issue to them.  Perhaps the wooninjas forum would be a good place to start?

**Comment by dpvc** [comment]
OK, glad you were able to work it out.

**Comment by SamDP02** [comment]
Great plugin by the way!

**Comment by SamDP02** [comment]
Hi Davide 

I am wondering if you can help me. Yesterday I used the troubleshooting mode on Wordpress to find out which plugin wasn’t working (It automatically switched off all plugins). Today, I figured out that non of the html for the fractions are rendering. 

Have you come across this issue with the plugin before? Do you have any solutions. I’m hoping that I have just switched something off. 

Kind regards,

Sam

**Comment by SamDP02** [comment]
Hi Davide

 

It seems like it’s just Chrome that’s not showing the fractions. It looks fine on Safari

 

From: Sam du Plessis <sam@xgroup.co.za>
Date: Thursday, 20 February 2020 at 12:36
To: mathjax/MathJax <reply@reply.github.com>, mathjax/MathJax <MathJax@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: [mathjax/MathJax] Issue

 

Hi Davide 

I am wondering if you can help me. Yesterday I used the troubleshooting mode on Wordpress to find out which plugin wasn’t working (It automatically switched off all plugins). Today, I figured out that non of the html for the fractions are rendering. 

Have you come across this issue with the plugin before? Do you have any solutions. I’m hoping that I have just switched something off. 

Kind regards,

Sam

**Comment by dpvc** [comment]
I have not heard of this before, and don't know what could be causing the problem for you.  It may be that there is CSS from some other part of the page that is interfering with MathJax's output.  You might try changing the renderer using the MathJax contextual menu to see if one of the other renderers displays properly.

Alternatively, you could use your browser developer tools (the DOM inspector and browser console) to disable the various (non-MathJax) stylesheets that are in the page and see if the math formats properly when one of them is disabled.  That could tell you where to look for the problem.

Without access to the page, it is not really possible for me to tell you want the issue is.  Sorry!

**Comment by dpvc** [comment]
Also, if it is just Chrome that is acting up, you might check if you have any Chrome extensions that might be causing the problem.

**Comment by SamDP02** [comment]
Thank you so much for the quick response 




Get Outlook for Android







On Thu, Feb 20, 2020 at 6:25 PM +0200, "Davide P. Cervone" <notifications@github.com> wrote:












Also, if it is just Chrome that is acting up, you might check if you have any Chrome extensions that might be causing the problem.
