### ISSUE TITLE
Access tex from the mathjax, after typsetting

### ISSUE THREAD

**Issue by HariDongli** [mathjax/MathJax#2354]
Hi
I'm trying to  access the original tex  through code from the mathjax node after typesetting.
which we can do it from the browser as shown in 
![Screen Shot 2020-02-21 at 11 24 11 PM](https://user-images.githubusercontent.com/13314512/75061324-80f62080-5506-11ea-81f4-717ca3886101.png)

In the browser, i'm able to see & copy the tex by following menu popup,
https://github.com/mathjax/MathJax-src/blob/1d5ce9837c82f1d12efec8da829c2138bd640c08/ts/ui/menu/Menu.ts#L303

the above function returns the original tex, when clicked on show as tex commands

MathJax version: 3

Looking for the help to resolve my issue

Thanks

**Comment by dpvc** [comment]
See [my answer](https://groups.google.com/d/msg/mathjax-users/x5Z7JBElOas/Z4DYXY_nEQAJ) in the MathJax Users Forum for some suggestions on how to accomplish your goal.

Note that this tracker is for MathJax bugs, not general questions about MathJax, which are better asked in that forum.

**Comment by HariDongli** [comment]
Thanks @dpvc, your link helped me and yes noted thank you for the forum link!
