### ISSUE TITLE
tex2chtml not working properly?

### ISSUE THREAD

**Issue by leontepe** [mathjax/MathJax#2365]
I have tried using the `tex2chtml` method to directly render just a single expression and insert it into the DOM by hand, but it doesn't seem to work. Normal typesetting via standard startup typesetting or `MathJax.typeset()` typesetting works.

It seems like some things are not loaded properly for me, when using `tex2chtml`. When I let the startup typesetting render an equation and let `tex2chtml` render the exact same one, it works. But when I change it a little bit, the parts of the equation that are new/changed go missing and only the parts that were already rendered once by the startup typesetting before are showing. When I don't let the startup typesetting render anything, `tex2chtml` just produces nothing or at times also the "fallback string" (`\sqrt{x^2+1}` just becomes `x2+1`).

This is my code:
```
<!DOCTYPE html>
<html>
    <head>
        <script id="MathJax-script" async src="node_modules/mathjax-full/es5/tex-chtml.js"></script>

        <script>

            MathJax = {
                chtml: {
                    scale: 2
                },
                // startup: {
                //     pageReady: () => {}
                // },
                options: {
                    // Disable context-menu
                    renderActions: {
                        addMenu: [0, '', ''],
                    }
                },
            }

            function render() {

                var div = document.querySelector('#mainDiv');
                var html = MathJax.tex2chtml('\\sqrt{x^2+5n}');
                div.appendChild(html);
                
            }

        </script>
    </head>
    <body>
        <button type="button" onclick="render()">Render</button>
        <p>$$\sqrt{x^2+1}$$</p>
        <div id='mainDiv'/>
    </body>
</html>
```

It is an electron app, which is why I am loading `tex-chtml.js` via the node_modules directory, although I think this shouldn't matter, since normal startup rendering works perfectly fine. I've also tried providing the `options` for `tex2chtml` myself, but that didn't seem to change anything either.

**Comment by dpvc** [comment]
The CHTML output uses CSS to render its results, and that CSS is dependent on the expressions being typeset.  So when you typeset something new, you need to update the CSS to include what is needed for the new content.  See the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web#mathjax-demos-web), and the [user input demos](https://github.com/mathjax/MathJax-demos-web#processing-user-input) in particular.

In your case, if you add

``` javascript
                MathJax.startup.document.clear();
                MathJax.startup.document.updateDocument();
```

right after appending the typeset math, that should do the trick for you.
