### ISSUE TITLE
Hash symbol

### ISSUE THREAD

**Issue by mgttlinger** [mathjax/MathJax#2367]
LaTeX disallows `'#'` to occur normally as it is used for macro parameter references. Hence LaTeX code needs to escape `'#'` as `'\#'`. Sadly MathJax does not "unescape" this character requiring production of different math expressions for use with MathJax and LaTeX.

**Comment by dpvc** [comment]
MathJax *does* process `\#` to produce a literal `#` in the output, as you can see in this screen shot

<img width="865" alt="hash" src="https://user-images.githubusercontent.com/432782/76229564-ce59d980-61f8-11ea-9cb6-bcaf0243f9db.png">

obtained from the [on-line demo](https://mathjax.github.io/MathJax-demos-web/input-tex_mml2chtml.html) where you can try it out for yourself.  This is version 3 of MathJax, but the same holds for version 2.

It may be that your content-management system is altering the TeX that you are entering.  You might use MathJax's `Show Math As...` contextual menu item to see what the TeX code that it is processing really is.

**Comment by mgttlinger** [comment]
Oh, it does not process it inside a `\text` expression inside a math expression (verified in the live demo). Sorry for not checking if the error does occur in normal math expressions as well.

**Comment by dpvc** [comment]
MathJax only implements math-mode macros, not text-mode macros, so the contents of `\text{}` and other text-mode contexts are not processed (except for internal math and a very few escapes related to that).  This is [documented](http://docs.mathjax.org/en/latest/input/tex/differences.html) but perhaps not as clearly as it should be.

There is an [extension](https://github.com/mathjax/MathJax/pull/2051) (to be included in the upcoming v2.7.8 release) that implements some tex-mode macros in `\text{}` and the other similar macros.  You could download that extension and use it now if you are using version 2.  It hasn't been ported to version 3 yet.

**Comment by mgttlinger** [comment]
I see but isn't the `\#` macro the same inside and out of math expressions and therefore already kinda implemented?

**Comment by mgttlinger** [comment]
If this is indeed the case and you can give me a pointer as to where this needs adaptation in the code, I can see if I can hack up a PR.

Anyway as this is expected behaviour I'm closing the issue.

**Comment by dpvc** [comment]
Yes, it is not the macro itself that is the problem, it is the difference between text-mode and math-mode that is the problem.  MathJax doesn't implement text-mode rules, which are different from math-mode rules, and so doesn't process text-mode material, except to look for math within it.

The extension I cited above implements a limited text-mode processing model, which allows some text mode processing.

**Comment by dpvc** [comment]
> If this is indeed the case and you can give me a pointer as to where this needs adaptation in the code, I can see if I can hack up a PR.

The extension I cited above already does that, but you can look there to see if there is anything more you want to work on.
