### ISSUE TITLE
SVG output ignores the scale configuration option

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#2376]
The SVG output is not taking the scale configuration option into account.  This should be done in the SVG output jax `setScale()` method, but that was override because the default includes the MathItem's metric scaling as well, which isn't needed for SVG output.

**Comment by working-name** [comment]
How can I help with testing? I'm seeing this on Safari (iOS 13, macOS 10.15) - chose _SVG to get away from _CHTML which doesn't render all MML items.

**Comment by dpvc** [comment]
> How can I help with testing?

You could try out the `issue2376` branch of the [MathJax-src](https://github.com/mathjax/MathJax-src) repository, but you would have to clone the repository locally, checkout the branch, and then run the compile and make-components npm scripts in order to create the `es5/tex-svg.js` file that needs to be tested.  If that doesn't make sense to you, I can spell it out in more detail.

Alternatively, this is a sample file that patches the CDN copy of MathJax, and you can check that this does scale properly when you set the scaling factor.

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta charset="utf-8"/>
    <title>SVG scale option</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script>
    MathJax = {
      svg: {
        scale: 2
      },
      startup: {
        ready() {
          const SVG = MathJax._.output.svg_ts.SVG;
          const percent = MathJax._.util.lengths.percent;
          SVG.prototype.setScale = function (node) {
            if (this.options.scale !== 1) {
              this.adaptor.setStyle(node, 'fontSize', percent(this.options.scale));
            }
          }
          MathJax.startup.defaultReady();
        }
      }
    };
    </script>
    <script id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
  </head>
  <body>
  
  Scaled math: \(x+1\).

  </body>
</html>
```

If it works for you, you could indicate that in the [pull request](https://github.com/mathjax/MathJax-src/pull/460) for this issue.

**Comment by working-name** [comment]
Sorry that comment was probably out of line/scope. I am experiencing rendering issues with 2.7.x not 3.0 but that's on a site which is subscription only with tests, not entirely easy to provide examples. I'll open a specific issue if I can recreate it in a vanilla HTML.

Will report back about the scaling.

**Comment by dpvc** [comment]
No problem.  Thanks for being willing to help check.
