### ISSUE TITLE
bbox of arrow is not displayed at expected position. 

### ISSUE THREAD

**Issue by t-k-** [mathjax/MathJax#2380]
### Issue Summary

When using bbox around `rightarrow` under a limit, it has unexpected vertical alignment.

### Steps to Reproduce:

1. Paste and render TeX
```
\lim _ {x \bbox[red]{\rightarrow} 0}
```
at demo page: https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html

You will see a bad alignment like this:
![](https://i.imgur.com/DC7peCK.png)

Notice, changing `\rightarrow` to `\to` would not have this issue.

**Comment by dpvc** [comment]
This is an issue with how certain characters are remapped to accents when they appear in limits or superscripts.  I have made a pull request (mathjax/MathJax-src#468) that fixes the problem.

Thanks for reporting the problem.
