### ISSUE TITLE
inline latex ($...$) isn't working for me, yet non-inline is ($$...$$)

### ISSUE THREAD

**Issue by mathacka** [mathjax/MathJax#2384]
Hi

I'm using inline latex, the single dollar sign, and mathjax isn't reading it. The paragraph latex, however, is working, I've double and tripple checked everything, here's my simple hml:

```
  <html>
  <head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title></title>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
  </script>
  <link rel="stylesheet" href="stylesheet.css" type="text/css">
  </head>
  <body>
    $r^2 = a^2 + b^2$
    $$r^2 = a^2 + b^2$$
  </body>
</html>
```

Here's a picture:
![snippet](https://user-images.githubusercontent.com/1857352/77602243-4efc2380-6ee3-11ea-874f-56cb44422a5b.png)

I'm using http-server to serve it up, one shows $r^2 = a^2 + b^2$, the other shows the formatted latex code in paragraph form. I tried it both in Microsoft Edge and Google Chrome with the same results.

Please submit MathJax bug reports to

https://github.com/mathjax/MathJax/issues

unless they are about structural issues in this repository (e.g., the package.json file, the compilation process, the repository layout, etc).  Bugs with how MathJax works should be reported at the link above.

If you are not part of the MathJax team, it is unlikely that you should be posting an issue here.  Use the tracker linked above instead.

**Comment by dpvc** [comment]
This is correct behavior.  Single-dollar delimiters are not enabled by default, since single dollar signs are used too frequently for other things.  You need to enable them explicitly if you want to use them.  See [the documentation](http://docs.mathjax.org/en/latest/input/tex/delimiters.html#tex-and-latex-math-delimiters) for details.

**Comment by mathacka** [comment]
Thanks for the reply!
