### ISSUE TITLE
How should I load MathJax?

### ISSUE THREAD

**Issue by MartinThoma** [mathjax/MathJax#2386]
I've created a website for my bachelors thesis which I checked now, 3 years later. I saw that the CDN is retired, so I thought I should update it ([website](http://write-math.com/) - just draw a circle and you will see it)

I had the following in the `<head>`:

```
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
```

I tried to simply replace the URL with https://cdn.jsdelivr.net/npm/mathjax@2.7.6/unpacked/MathJax.min.js, but this made me run into issue #1934 .

I tried to replace the URL with https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.1/es5/startup.js but then I get:

    MathJax(?): Cannot read property 'MmlTree' of undefined

**Comment by dpvc** [comment]
The new address that corresponds to your original one is

    https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

though unless you are using both TeX *and*  MathML formats in your document, you might want to select a smaller configuration.  TeX-AMS_CHTML is probably sufficient.

If you want to try version 3, then use

    https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

If you have a version 2 configuration block, you should use the [conversion tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) to convert it from v2 to v3 format.

**Comment by dpvc** [comment]
PS, this issue tracker is for reporting bugs in MathJax.  General questions are better asked in the [MathJax User's Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see them and can respond.

**Comment by MartinThoma** [comment]
Nice, this works:

    https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

Thank you, @dpvc !
