### ISSUE TITLE
Issues with \enclose{}{}

### ISSUE THREAD

**Issue by jnnkB** [mathjax/MathJax#2387]
### Issue Summary

Result of `\enclose{circle}{X}` command is misaligned.

### Steps to Reproduce:

Minimal working example:

```latex
\enclose{circle}{X}
```
To test you can simply copy the following in the textarea on mathjax.org
```latex
$$\enclose{circle}{X}$$
```
I would expect, that the X is placed in the middle of an circle not an oval.

<img width="79" alt="image" src="https://user-images.githubusercontent.com/29376715/77757657-e7a0b980-7031-11ea-80af-03cc1508555d.png">

Client OS: Mac OS X 10.15.3
Browser: Firefox 74.0

---

In Chrome this example works:
<img width="61" alt="image" src="https://user-images.githubusercontent.com/29376715/77773299-b16f3400-7049-11ea-9b29-c23f4af1de41.png">
But it needs a more recent version as in 2.7.5 it doesn't work:
<img width="46" alt="image" src="https://user-images.githubusercontent.com/29376715/77773606-1fb3f680-704a-11ea-956d-c91112896f57.png">

**Comment by dpvc** [comment]
I suspect that you have unchecked "Allow pages to choose their own fonts" in the Advanced font settings in the Firefox preferences.  Note that the "X" is not in the correct font (It should be an italic "X" like the on in your Chrome picture).  I have tested turning off this setting and get the same as in your Firefox image, so I'm pretty sure that is the issue for you.

I am not able to reproduce the output you have to 2.7.5, as the output I get in both Firefox and Chrome is correct in v2.7.5 (and earlier) versions.  Which output format are you using, and are you at 100% zoom, or some other zoom value?

**Comment by jnnkB** [comment]
Thanks alot.
