### ISSUE TITLE
How can you extend the CHTML output jax?

### ISSUE THREAD

**Issue by leontepe** [mathjax/MathJax#2388]
So I wrote my custom component file for MathJax and included a custom version of the CHTML output jax, which I just named `CustomHTML`. Everything worked kind of fine at first, but then I realized one weird behaviour: certain parts of the math don't render correctly. I noticed this with the following LaTeX input: `\sqrt{\frac{123}{abc}}`, the root symbol doesn't scale. It does work with the custom components in the MathJax-demos-web repo though.

**My version**
![image](https://user-images.githubusercontent.com/27787342/77788916-60b80500-7062-11ea-99c6-450bc5edf571.png)

**MathJax-demos-web custom component version**
![image](https://user-images.githubusercontent.com/27787342/77788931-67df1300-7062-11ea-94ec-8cae1be77070.png)

My `custom-component.js` file looks like the one in the repo, the only major difference is that instead of importing `components/src/output/chtml/chtml.js`, I include the code myself to change
```
if (MathJax.startup) {
    MathJax.startup.registerConstructor('chtml', CHTML);
    MathJax.startup.useOutput('chtml');
}
```
for
```
if (MathJax.startup) {
    MathJax.startup.registerConstructor('chtml', CustomCHTML); // substitution here
    MathJax.startup.useOutput('chtml');
}
```
plugging in my own `CustomCHTML` chtml output jax. This, however, makes these rendering issues come up.
I've tried so many things so far and even deleted all the code and just extended the `CHTML` class without adding anything to it (`export class CustomCHTML<N,T,D> extends CHTML<N,T,D> {}`) and even copied the whole source of `CHTML` into my file, but I didn't work.
I suppose that something goes wrong with the directories or something, but I can't figure out what it is.

You said in an earlier answer:

> But again, I don't recommend changing the base MathJax code unless you are planning to make pull requests back to the MathJax source repository. Instead, you should subclass the objects you plan to change, make the changes in your subclass, and use the subclasses instead of the base MathJax classes. It is possible to substitute your own classes for most of the originals (though there are some places where that is more difficult to do).

Is it harder to do here? What do I have to change to get it working?

**Comment by dpvc** [comment]
It is hard to tell without the actual code that you are using.  If I replace the `custom-component.js` with

``` javascript
//
//  Initialize the MathJax startup code
//
require('mathjax-full/components/src/startup/lib/startup.js');

//
//  Get the loader module and indicate the modules that
//  will be loaded by hand below
//
const {Loader} = require('mathjax-full/js/components/loader.js');
Loader.preLoad(
    'loader', 'startup',
    'core',
    'input/tex-base',
    '[tex]/newcommand',
    '[tex]/action',
    'output/chtml', 'output/chtml/fonts/tex.js'
);

//
// Because the root URL will be determined from the URL of the
// combined file we load into the web pasge (this file), we
// adjust the mathjax path to be the CDN instead of this directory.
//
const paths = MathJax.config.loader.paths;
paths.mathjax = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5';

//
// Load the components that we want to combine into one component
//   (the ones listed in the preLoad() call above)
//
require('mathjax-full/components/src/core/core.js');

require('mathjax-full/components/src/input/tex-base/tex-base.js');
require('mathjax-full/components/src/input/tex/extensions/newcommand/newcommand.js');
require('mathjax-full/components/src/input/tex/extensions/action/action.js');
MathJax.config.tex.packages.push('newcommand', 'action'); // add these to the tex packages to register

//========== changes ==============//

//require('mathjax-full/components/src/output/chtml/chtml.js');

const {combineDefaults} = require('mathjax-full/js/components/global.js');
const {CHTML} = require('mathjax-full/js/output/chtml.js');

class MyCHTML extends CHTML {
  
  constructor(...args) {
    super(...args);
    console.log('Creating MyCHTML');
  }
  
}

if (MathJax.startup) {
    MathJax.startup.registerConstructor('chtml', MyCHTML);
    MathJax.startup.useOutput('chtml');
}

//========== end changes ==============//

require('mathjax-full/components/src/output/chtml/fonts/tex/tex.js');

//
// Loading this component will cause all the normal startup operations to be
//   performed when this component is loaded.
//
require('mathjax-full/components/src/startup/startup.js');
```

and build the component, it displays properly for me.

Can you check in the browser to see if the fonts have loaded?  You certainly are getting the main fonts, but if MathJax_Size3-Regular isn't loading for some reason, that could be why.  

Can you give the DOM tree for the output that you are seeing?  For me, I get

``` html
<mjx-math display="true" class="MJX-TEX">
  <mjx-msqrt>
    <mjx-sqrt>
      <mjx-surd>
        <mjx-mo class="mjx-s3">
          <mjx-c class="mjx-c221A"></mjx-c>
        </mjx-mo>
      </mjx-surd>
      <mjx-box style="padding-top: 0.236em;">
        <mjx-mfrac>
          <mjx-frac type="d">
            <mjx-num>
              <mjx-nstrut type="d"></mjx-nstrut>
              <mjx-mn class="mjx-n">
                <mjx-c class="mjx-c31"></mjx-c>
                <mjx-c class="mjx-c32"></mjx-c>
                <mjx-c class="mjx-c33"></mjx-c>
              </mjx-mn>
            </mjx-num>
            <mjx-dbox>
              <mjx-dtable>
                <mjx-line type="d"></mjx-line>
                <mjx-row>
                  <mjx-den>
                    <mjx-dstrut type="d"></mjx-dstrut>
                    <mjx-mrow>
                      <mjx-mi class="mjx-i">
                        <mjx-c class="mjx-c61"></mjx-c>
                      </mjx-mi>
                      <mjx-mi class="mjx-i">
                        <mjx-c class="mjx-c62"></mjx-c>
                      </mjx-mi>
                      <mjx-mi class="mjx-i">
                        <mjx-c class="mjx-c63"></mjx-c>
                      </mjx-mi>
                    </mjx-mrow>
                  </mjx-den>
                </mjx-row>
              </mjx-dtable>
            </mjx-dbox>
          </mjx-frac>
        </mjx-mfrac>
      </mjx-box>
    </mjx-sqrt>
  </mjx-msqrt>
</mjx-math>
```

Note in particular the `<mjx-mo class="mjx-s3">`; make sure that has `mjx-s3` as the class.

**Comment by leontepe** [comment]
My DOM tree looks like this:

```
<mjx-container class="MathJax" jax="CHTML" display="true" style="font-size: 101.6%;">
  <mjx-math display="true" class="MJX-TEX">
    <mjx-msqrt>
      <mjx-sqrt>
        <mjx-surd>
          <mjx-mo class="mjx-n">
            <mjx-c class="mjx-c221A"></mjx-c>
          </mjx-mo>
        </mjx-surd>
        <mjx-box style="padding-top: 0.17em;">
          <mjx-mfrac>
            <mjx-frac type="d">
              <mjx-num>
                <mjx-nstrut type="d"></mjx-nstrut>
                <mjx-mn class="mjx-n">
                  <mjx-c class="mjx-c31"></mjx-c>
                  <mjx-c class="mjx-c32"></mjx-c>
                  <mjx-c class="mjx-c33"></mjx-c>
                </mjx-mn>
              </mjx-num>
              <mjx-dbox>
                <mjx-dtable>
                  <mjx-line type="d"></mjx-line>
                  <mjx-row>
                    <mjx-den>
                      <mjx-dstrut type="d"></mjx-dstrut>
                      <mjx-mrow>
                        <mjx-mi class="mjx-i">
                          <mjx-c class="mjx-c61"></mjx-c>
                        </mjx-mi>
                        <mjx-mi class="mjx-i">
                          <mjx-c class="mjx-c62"></mjx-c>
                        </mjx-mi>
                        <mjx-mi class="mjx-i">
                          <mjx-c class="mjx-c63"></mjx-c>
                        </mjx-mi>
                      </mjx-mrow>
                    </mjx-den>
                  </mjx-row>
                </mjx-dtable>
              </mjx-dbox>
            </mjx-frac>
          </mjx-mfrac>
        </mjx-box>
      </mjx-sqrt>
    </mjx-msqrt>
  </mjx-math>
</mjx-container>
```
So no, I don't have the `mjx-s3` as a class for the `<mo>`, although I don't know why.

Also, is there a reason why you left out the
```
if (MathJax.loader) {
    // ...
}
```
and the `components/src/output/chtml/lib/chtml.js` import part? I don't know if that was unclear from my question, but I included that part from `components/src/output/chtml/chtml.js` as well, I basically copied the file contents into my `custom-component.js` and changed the output jax part.

And also one thing that might be the cause, is that I am using an external TypeScript file to define my CustomCHTML output jax.
My code in `custom-component.js` roughly looks like this:
```
require('mathjax-full/components/src/startup/lib/startup.js');

const {Loader} = require('mathjax-full/js/components/loader.js');
Loader.preLoad(
    'loader', 'startup',
    'core',
    'input/tex-base',
    'output/chtml', 'output/chtml/fonts/tex.js',
);

const paths = MathJax.config.loader.paths;
paths.mathjax = "./node_modules/mathjax-full/es5";

require('mathjax-full/components/src/core/core.js');
require('mathjax-full/components/src/input/tex-base/tex-base.js');

require('mathjax-full/components/src/output/chtml/lib/chtml.js');
const {combineDefaults} = require('mathjax-full/js/components/global.js');

const {CustomCHTML} = require('../js/chtml-custom.js');

if (MathJax.loader) {
    combineDefaults(MathJax.config.loader, 'output/chtml', {
        checkReady() {
            return MathJax.loader.load("output/chtml/fonts/tex");
        }
    });
}

if (MathJax.startup) {
    MathJax.startup.registerConstructor('chtml', CustomCHTML);
    MathJax.startup.useOutput('chtml');
}

require('mathjax-full/components/src/output/chtml/fonts/tex/tex.js');
require('mathjax-full/components/src/startup/startup.js');
```

So I included the transpiled JS version of my TS source file for the custom output jax. I have the exact same `tsconfig.json` as in the original `mathjax-full` package and also the same version as indicated in its `package.json`.

**Comment by leontepe** [comment]
Actually, it works for me now too. I reproduced it even with a TS file in a clone of the MathJax-demos-web repo and now it's rendering properly.
I don't know what's wrong in my other project as of now though, lol.
Thanks a lot for the help anyway! I really appreciate your quick and thorough answers!!!

**Comment by leontepe** [comment]
I think my problem was the following: in my main project with its own `package.json` and its own version of MathJax I had my TypeScript source files and they referenced the MathJax version of my main project. I had a nested folder `custom-component` inside of it, with its own package.json as well and its own MathJax installation. I referenced the nested `mathjax-full` in my `custom-component` folder and the outer `mathjax-full` in my TypeScript source files...
I don't even know what exactly produced the error here in the end but that's just so sad... I've literally wasted a whole day because I nested my folders wrong... at least I've got it down now. Sorry for wasting your time with my dumb mistake, lol. Thanks a lot anyway!

**Comment by dpvc** [comment]
Glad you got it to work.  Thanks for letting us know.

> is there a reason why you left out the  `if (MathJax.loader) { ... }` and the `components/src/output/chtml/lib/chtml.js` import part?

The `components/src/output/chtml/lib/chtml.js` should be included.  I think I just missed it in my copy and paste.  The `MathJax.loader` part is the original file for when CHTML is loaded as a separate component, but in the combined component, it will never be used because CHTML is preloaded (and so is the font that this block of code references).  Sit doesn't hurt, but it is never used, so I didn't include it.

Good luck with the rest of your project.
