### ISSUE TITLE
Spacing issue involving single '=' in fractions in mrow

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2391]
### Issue Summary

The spacing is different between these fractions is not symmetric (extra space before last fraction):
![image](https://user-images.githubusercontent.com/1545836/78075289-1cc24a00-7359-11ea-976f-cde5ab5965cd.png)

Note: this weird example came from looking at how some MathML spacing rules are being interpreted by different renderers. Since MathJax uses TeX rendering, I was quite surprised to see it doesn't seem to render this properly. Next I'll try turning on MathML spacing rules, where right and wrong are much more subjective ;-)

### Steps to Reproduce:
With this header:
```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js">
```
this MathML produced the above input
```
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mn>1</mn>
  <mfrac>
	<mo lspace="0" rspace="0">=</mo>
	<mn>2</mn>
  </mfrac>
  <mn>1</mn>
  <mfrac>
	<mo>=</mo>
	<mn>2</mn>
  </mfrac>
  <mn>1</mn>
  <mfrac>
	<mn>2</mn>
	<mo>=</mo>
  </mfrac>
  <mn>1</mn>
</math>
```

The problem occurs in both Chrome and Firefox.

You can view this at https://codepen.io/nms/pen/MWwxEKj.

**Comment by dpvc** [comment]
Thanks for catching this.  It turns out that the right-hand space was using MathML rules even when `mathmlSpacing` is false.  I will make a pull request to fix it.  Note that the problem applies in both v2 and v3.
