### ISSUE TITLE
"t.setAttribute is not a function" when "\$" is present

### ISSUE THREAD

**Issue by KyrietS** [mathjax/MathJax#2396]
### Issue Summary

When I use **\\$** anywhere in my HTML document I get an error: (Chrome)
```
tex-mml-chtml.js:1 Uncaught (in promise) TypeError: t.setAttribute is not a function
    at l.setAttribute (tex-mml-chtml.js:1)
    at e.assistiveMml (tex-mml-chtml.js:1)
    at e.assistiveMml (tex-mml-chtml.js:1)
    at r.assistiveMml (tex-mml-chtml.js:1)
    at Object.renderDoc (tex-mml-chtml.js:1)
    at v.renderDoc (tex-mml-chtml.js:1)
    at r.I.render (tex-mml-chtml.js:1)
    at tex-mml-chtml.js:1
    at e (tex-mml-chtml.js:1)
    at new Promise (<anonymous>)
```
But **\\$** is not set as delimiter! What's interesting when I set **\\$** as tex delimiter then it's recoginsed correctly. The bigger problem is that **I cannot set '\\\\$' as delimiter for asciimath** beacause of this error. Is it possible to do?

### Steps to Reproduce:

1. Include MathJax (latest)
```
<script id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
```
2. Use \\$ anywhere in HTML document

MathJax reference says that `$$`, `\(`, `\[` are used for delimiters so I don't udnerstand what's wrong with \\$.

### Technical details:

* MathJax Version: 3.x.x
* Client OS: Windows 10
* Browser: Chrome 80.0.3987.163

### Supporting information:

jsbin: https://jsbin.com/zafijuzuqa/edit?html,output

**Comment by dpvc** [comment]
This is a duplicate of #2327.  See that issue for details, and a workaround.

**Comment by KyrietS** [comment]
Thank you for quick response! When I was looking for similar issues I didn't think it's the same problem as mine (I mean source of that problem).

**Your fix for now works.** I'm looking forward to the next release then. Cheers!
