### ISSUE TITLE
mathjax-node-page for MathJax 3

### ISSUE THREAD

**Issue by formiel** [mathjax/MathJax#2398]
For my static blog, I used to create server-side math formulas using `mathjax-node-page`, by running the `npx mjpage` command on all `*.html` pages.

I would like to know if such a tool exists for MathJax 3 (to convert math formulas to CHTML).

Thank you in advance for your help.

**Comment by dpvc** [comment]
See the [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node) repository, which has a number of usable examples including ones like `tex2chtml-page` and `mml2chtml-page`, which would do what you want if your mathematics is in TeX or MathML format.

There are three different ways to call MathJax, so there are examples in all three forms: components, preloaded, and direct calls to MathJax.  They are all functionally equivalent, so any one of them would do.

Note for the future, this issue tracker is for reporting bugs in MathJax; general questions are better asked in the [MathJax Users Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will see them and can respond.

**Comment by formiel** [comment]
@dpvc Sorry, somehow I missed that repo. Thank you very much!
