### ISSUE TITLE
MathJax(?): window.MathJax is undefined

### ISSUE THREAD

**Issue by nschloe** [mathjax/MathJax#2399]
This is a continuation of https://github.com/mathjax/MathJax/issues/2393. I'm trying to write a browser extension that adds MathJax 3.0.1 to arbitrary sites, https://github.com/nschloe/green-pi. It already works on Chrome, but doesn't yet on Firefox.

It basically inserts this
```js
MathJax = {
  chtml: {
    fontURL: chrome.runtime.getURL("fonts")
  },
};
// plus the populated code of mathjax-full/components/src/tex-chtml/tex-chtml.js via
require("mathjax-full/components/src/tex-chtml/tex-chtml.js");
```
into every page. On Firefox, this gives the error
```
MathJax(?): window.MathJax is undefined loader.js:141:34
```
Perhaps I'm including the wrong file here? All hints appreciated.

**Comment by dpvc** [comment]
I think you probably want to use

```
window.MathJax = {
  chtml: {
    fontURL: chrome.runtime.getURL("fonts")
  },
};
```

or perhaps `global.MathJax`, since I think webpack will make this `MathJax` be local to the `mathjax.js` file rather than the global value that it needs to be.  Give that a try and see if that works.

**Comment by nschloe** [comment]
* `window.MathJax` still works on Chrome, doesn't on Firefox with the error message
   ```
   MathJax(?): window.MathJax._ is undefined
   ```
* `global.MathJax` still works on Chrome, doesn't on Firefox with error message
   ```
   MathJax(?): window.MathJax is undefined
   ```

The config isn't really important here either, I could just go with the default
```js
// No config
// MathJax = {
//  chtml: {
//    fontURL: chrome.runtime.getURL("fonts")
//  },
// };
// plus the populated code of mathjax-full/components/src/tex-chtml/tex-chtml.js via
require("mathjax-full/components/src/tex-chtml/tex-chtml.js");
```
and it should still work. It does on Chrome (without the proper fonts, expected), but doesn't on Firefox with
```
MathJax(?): window.MathJax is undefined
```

**Comment by nschloe** [comment]
The same applied if I require 
 * `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js` from the CDN
 * `mathjax-full/components/src/tex-svg/tex-svg.js`

**Comment by dpvc** [comment]
Can you try `mathjax-full/es5/tex-chtml.js`? The `components/src` files are intended to be used with the `webpack.config.js` files that are in their directories, and it may be that something there is the source of the problem.  But this should be equivalent to calling the version from the CDN, so I suspect this won't work, either.

**Comment by dpvc** [comment]
The only references to `window.MathJax` are in the `ts/ui/menu/Menu.ts` file, which is being modified to remove those references.  The `develop` branch of `mathjax/MathJax-src` has the new code merged in, so you could try getting that (you will need to compile MathJax and build the components) and see if that helps.

**Comment by dpvc** [comment]
Alternatively, you could remove the line

    import '../ui/menu/menu.js';

from `components/src/tex-chtml/tex-chtml.js` and see if that prevents the message.

**Comment by nschloe** [comment]
> Alternatively, you could remove the line
> ```js
> import '../ui/menu/menu.js';
> ```
> from components/src/tex-chtml/tex-chtml.js and see if that prevents the message.

This works.

**Comment by nschloe** [comment]
It appears this is fixed in 3.0.4?

**Comment by dpvc** [comment]
> It appears this is fixed in 3.0.4?

It is supposed to be.  If you put back the menu import, does it work now?

**Comment by nschloe** [comment]
It does indeed. Thanks!

**Comment by dpvc** [comment]
Great!  Thanks for the confirmation.
