### ISSUE TITLE
Two identical uses of \tag will cause identical element id's

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#240]
Since the `\tag{xyz}` macro produces a DOM element with `id="mjx-eqn-xyz"`, two identical uses of `\tag{}` will cause two DOM elements to have identical id's, which is technically an error, since element id's are supposed to be unique.

Since MathJax uses the element id's to locate the elements associated with its internal MathML structure, that can cause confusion if the id's are not unique.  See [this post](http://meta.math.stackexchange.com/questions/4118/mathjax-bug-upon-page-refresh) on meta.math.stackexchange.com for an instance where this occurred in the wild.

**Comment by basvandertol** [comment]
There is a bug in the fix.
The initialization of AMS.IDs and AMS.eqIDs is wrong.
The lines
`AMS.eqlabels = AMS.eqIDs = {};` in TEX.prefilterHooks.Add
`AMS.labels = AMS.IDs = {}` in TEX.resetEquationNumbers
make the labels and IDs point to the same empty object.
This shared object then gets filled with both labels and IDs

**Comment by dpvc** [comment]
Argh!  Quite right.
