### ISSUE TITLE
\overline fails

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2400]
### Issue Summary

\overline does not produce a line as it should. It is not caused by screen resolution.

### Steps to Reproduce:

Try typesetting \overline{B}

### Technical details:

* MathJax Version: 3.0.4
* Client OS: Linux Mint 19.3 64 bits
* Browser: Firefox 75.0 (64 bits), Chromium 80.0.3987.163

### Supporting information:

 * https://cdi2tp.math.tecnico.ulisboa.pt/test It's the first example.
![Captura de ecrã de 2020-04-09 18-49-38](https://user-images.githubusercontent.com/1136663/78925348-32d7b500-7a93-11ea-9702-88517c34d308.png)
 * MathJax configuration: https://cdi2tp.math.tecnico.ulisboa.pt/scripts/mathjax-config.js
 * Loading MathJax with https://cdi2tp.math.tecnico.ulisboa.pt/mathjax3/es5/tex-mml-chtml.js

**Comment by dpvc** [comment]
Thanks, I can confirm the problem.  The extenders aren't be placed properly (and so they fall outside the clipping region).  I'll look into it further.

The issue is CHTML-specific, so switching to SVG output would work around the problem for now.

**Comment by dpvc** [comment]
OK, I found it.  A change in 3.0.4 caused an element to be `display: block` that used to be `display: inline-block`, and that caused horizontal extenders to be misplaced.  

You can work around it for now by adding

      mjx-stretchy-h > * > mjx-c::before {display: inline-block}

to your CSS.

**Comment by cebola2** [comment]
Thanks! Your support is amazing.

**Comment by dpvc** [comment]
I put out a hit-fix release (3.0.5) that fixes this issue.
