### ISSUE TITLE
\overbrace broken in SVG output

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#2402]
Use of `\overbrace` causes an error (`getVariant` not defined).  This is due to not passing the variant name to `unicodeChars()` in the [`placeChar()` method](https://github.com/mathjax/MathJax-src/blob/5e9a5c66de610dd754a0377b278892ae4f007058/ts/output/svg/Wrapper.ts#L281).

See the [MathJax User's Forum post](https://groups.google.com/d/msg/mathjax-users/95BnUPx2qLE/lNCy6F5RBwAJ).

**Comment by dainiak** [comment]
"\not\equiv" failed in SVG output in MJ 3.0.5
Is that the same issue there?

**Comment by dpvc** [comment]
@dainiak, yes, it is the same issue.  You can use

``` html
<script>
    MathJax = {
      startup: {
        ready() {
          if (MathJax.version === '3.0.5') {
            const SVGWrapper = MathJax._.output.svg.Wrapper.SVGWrapper;
            const CommonWrapper = SVGWrapper.prototype.__proto__;
            SVGWrapper.prototype.unicodeChars = function (text, variant) {
              if (!variant) variant = this.variant;
              return CommonWrapper.unicodeChars.call(this, text, variant);
            }
          }
          MathJax.startup.defaultReady();
        }
      }
    };
</script>
```

as a work-around until the next release.

**Comment by dpvc** [comment]
Fixed in v3.1 released today.

**Comment by FDK7** [comment]
Still Problems with svg-Output: Try it on https://mathjax.github.io/MathJax-demos-web/input-tex2svg.html ser on renderer: svg with \overbrace{\underbrace{x}\text{real} +\underbrace{iy}\text{imaginary}}^\text{complex number}.

**Comment by dpvc** [comment]
@FDK7, it works for me:

<img width="692" alt="issue2402" src="https://github.com/mathjax/MathJax/assets/432782/82900672-74b1-4e8d-ba8a-25c38ea470d4">

Are you still getting an error message?

**Comment by FDK7** [comment]
![grafik](https://github.com/mathjax/MathJax/assets/111186287/178008e4-0364-45b7-add4-3572fa725199) 
You have to switch to SVG and click display on and off.

**Comment by dpvc** [comment]
@FDK7, OK, here is a configuration that should resolve the problem in v3:

``` js
MathJax = {
  startup: {
    ready() {
      if (MathJax._.output.svg) {
        const {SVGWrapper} = MathJax._.output.svg.Wrapper;
        Object.assign(SVGWrapper.prototype, {
          _unicodeChars: SVGWrapper.prototype.unicodeChars,
          unicodeChars(text, variant = this.variant) {
            text = text.replace(/\\([0-9A-F]{1,4})/g, (match, n) => String.fromCodePoint(parseInt(n, 16)));
            return this._unicodeChars(text, variant);
          }
        });
      }
      MathJax.startup.defaultReady();
    }
  }
};
```

If you incorporate that into your configuration, that should take care of it.

**Comment by FDK7** [comment]
Great! Included in my electron-app and it is working. Thanks so much!
