### ISSUE TITLE
mathjax 3@/es5/tex-svg.js fails to load with exception "t.charAt is not a function"

### ISSUE THREAD

**Issue by kkm000** [mathjax/MathJax#2405]
### Issue Summary

Script https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js throws an uncaught exception  "t.charAt is not a function" on load; no TeX rendering at all.

I'm trying to upgrade to v3 from v2.7.7 (https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_SVG,Safe)

### Steps to Reproduce:

1. Add the following to the `<head>` element:
```html
<script>
window.MathJax = {
  tex: {
    inlineMath: [ ['$ ','$'], ['\\(','\\)'] ],
    displayMath: [ ['$$ ', '$$'], ['\\[', '\\]'] ],
    processEnvironments: false,
    autoload: {
      color: [],
      colorV2: ['color']
    },
    packages: {'[+]': ['noerrors']}
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process'
  },
  loader: {
    load: ['[tex]/noerrors']
  }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js" id="MathJax-script"></script>
```
Actually, I used the Web tool mention in the v3 documentation to auto-convert config from a working v2.7.7 site. I have only the first 2 settings in the v2 config, `inlineMath` and `displayMath`; also, for v3, I added `processEnvironments: false` after conversion. There was a warning about module "Safe" being unsupported during conversion.

2. Load the page.

Inline TeX does not render at all (`$ x$` displayed unchanged), and the browser console logs an uncaught exception: “TypeError: t.charAt is not a function.”

I stopped at the exception in the Firefox debugger, but cannot make much sense of the minified JS. The `t` really has no `charAt()` method, and, naively, its type name does not look like it shoud:
```
>> t.__proto__
{…}
​next: function next()
​Symbol(Symbol.toStringTag): "Map Iterator"
>>
```
I do not know how helpful is the stack trace:
```
methodName (tex-svg.js#1)
o (tex-svg.js#1)
s (tex-svg.js#1)
u (tex-svg.js#1)
c (tex-svg.js#1)
defaultReady (tex-svg.js#1)
defaultReady (tex-svg.js#1)
<anonymous> (tex-svg.js#1)
```
and a bit of minified code where the exception occurs from the previous `;` (slightly reformatted to make at least some sense of it)
```js
var l=e(47),
    r=(o.methodName=function(t){
          return"visit"+(t.charAt(0).toUpperCase()+t.substr(1)).replace(/[^a-z0-9_]/gi,"_")+"Node"},
       o.prototype.visitTree= ....
```
Unfortunately, I'm more of a C++ programmer, and cannot be of much help understanding the issue (I do not even know if the `;`, which I looked for to the left of the exception point separates statements, really). I can send code snippets around the calling code down the stack, if needed, so maybe you can understand the whole stack trace leading to the error. I did not do it right away because it takes time, and I'm not even sure if this would be of help. But I'll gladly do more diagnostics if you direct me. Maybe there is a way to load non-minified code from the CDN, but I could not find it.

I tried explicit versions 3.0.4 and 3.0.1, same exception.

### Technical details:

* MathJax Version: 3.0.5 (https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js)
* Client OS: Windows 10 Pro x64, Version 10.0.18362
* Browser: Firefox 75.0 (64-bit), beta channel, build ID 20200403064226.

**Comment by dpvc** [comment]
Your configuration works fine for me.  The problem is probably triggered by something special in your page content.  Can you provide the content of the page, or perhaps narrows down the content to determine which expression is causing the problem?  It is not the configuration itself that is at issue, but the processing of some particular expression in your page, so I can't tell what is wrong from the information given.

**Comment by kkm000** [comment]
I'll try to narrow it down, thanks for verifying so quickly! The problem is the host is WordPress, so it's going to be tricky. WP itself, the theme and plugins load insane amount of JS. Probably I should just save the whole kaboodle as local files and HTML and try to pare it down. Give me a few days.

I'd create a page so that you could look at it, if I knew how. _Of course_ there is a way to do that in WP. I jumped into this blogging thing headlong. I just needed a blog/documetation site for a project, and a couple of Web designers I asked said WP is the best choice, no-brainer, easy-peasy. 

The header is generated by a PHP file common to all pages. I learned much more PHP than I ever wanted to know, and then twice as more. If the same guys ever ask me what computer language is the easiest to learn as their first, I'll recommend Haskell or Eiffel in revenge... :)
