### ISSUE TITLE
Loading elements in MathMl dynamically

### ISSUE THREAD

**Issue by CamilaSiqueira** [mathjax/MathJax#2407]
I'm using offline version and it's was going well until I had to put math elements dynamically.

I've already researched a solution and I found MathJax.Hub.Queue(["Typeset",MathJax.Hub,desiredElement]);
But when I try to use MathJax.Hub the console shows me 'undefined'.

So, I decided to use MathJax.typeset() and worked, but this method reprocess all document and for me this is a problem.

I really don't know what I should do now. What I need is a method capable of process just one dom element.

Someone could help me?

**Comment by dpvc** [comment]
I suspect that you are using MathJax version 3, but the API has changed considerably from version 2.  The `MathJax.Hub` is part of version 2, and is no longer available, so you are looking at old documentation.  You are correct to use `MathJax.typeset()` or `MathJax.typesetPromise()`.

> his method reprocess all document

You can pass it an array of container elements to process, as in 

``` javascript
MathJax.typeset(["#myContainer"]);
```

which would process the element with `id = "myContainer"`.  You can use a CSS selector to specify the element, or a direct reference to a DOM node, as in

``` javascript
MathJax.typeset([document.getElementById('myContainer')]);
```

Even if you don't specify an array of containers, MathJax will only look through the document for unprocessed math, and will not reprocess any math that was already typeset.  So it should only render *new* math.  So unless the document is very large, that should not be too expensive.

**Comment by dpvc** [comment]
Note that this tracker is for reporting bugs in MathJax.  General questions are better asked at the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will be able to see and respond to your question.

**Comment by CamilaSiqueira** [comment]
> Note that this tracker is for reporting bugs in MathJax. General questions are better asked at the [MathJax Users' Forum](https://groups.google.com/forum/?fromgroups#!forum/mathjax-users) where more people will be able to see and respond to your question.

Sorry about that, I was desperate.

**Comment by CamilaSiqueira** [comment]
> I suspect that you are using MathJax version 3, but the API has changed considerably from version 2. The `MathJax.Hub` is part of version 2, and is no longer available, so you are looking at old documentation. You are correct to use `MathJax.typeset()` or `MathJax.typesetPromise()`.
> 
> > his method reprocess all document
> 
> You can pass it an array of container elements to process, as in
> 
> ```js
> MathJax.typeset(["#myContainer"]);
> ```
> 
> which would process the element with `id = "myContainer"`. You can use a CSS selector to specify the element, or a direct reference to a DOM node, as in
> 
> ```js
> MathJax.typeset([document.getElementById('myContainer')]);
> ```
> 
> Even if you don't specify an array of containers, MathJax will only look through the document for unprocessed math, and will not reprocess any math that was already typeset. So it should only render _new_ math. So unless the document is very large, that should not be too expensive.

Yes, I'm using version 3 and my document is stupidly large. So when I call MathJax.typeset() without the math container it takes a long time to process.

I was calling like this:
MathJax.typeset('#mathContainer') 
I just had to add '[]' 

Thank you very much!!!!!!!
