### ISSUE TITLE
double prime fails in svg mode

### ISSUE THREAD

**Issue by 70ray** [mathjax/MathJax#2409]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.

### Steps to Reproduce:

1. This is the first step
include in html header
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>

2. This is the second step
in body `\[''\]`
3. Further steps, etc.
No conversion takes place. The following message appears in console:
TypeError: t.setAttribute is not a function tex-svg.js:1:276942

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

Works correctly with versions other than svg

### Technical details:

* MathJax Version: 3
* Client OS: Linux KDE Neon
* Browser: Firefox 75.0

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and in crude them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by dpvc** [comment]
Thanks for your report.  This turns out to be the same issue as #2402, and the work-around listed [here](https://groups.google.com/d/msg/mathjax-users/95BnUPx2qLE/QHueiiWkAgAJ) should resolve the issue for you until the next release, when it will be fixed.

**Comment by 70ray** [comment]
Thanks for the quick response.

**Comment by dpvc** [comment]
Fixed in v3.1 released today.
