### ISSUE TITLE
MathJax v3 incompatibilities with WebKit of MacOS 10.9.5

### ISSUE THREAD

**Issue by chacha21** [mathjax/MathJax#2416]
[edit]The issue is finally not limited to Cocoa integration, but Mathjax v3 compatibility with WebKit of MacOS 10.9.5 which does not support all modern Javascript[/edit]

This issue is very special.
I use MathJax as a rendering engine in a Cocoa WebView of a MacOS application. The WebView is provided by the Webkit.framework.
Under MacOS 10.15, it works well with both MathJax v2 and MathJax v3, with both a (deprecated) WebView or a (recommended) WkWebView.

However, I have been told (and observed myself) that under MacOS 10.9.5 (which use legacy WebView, WkWebView is unavailable), the MathJax v3 version does not work as expected in this application-embedded context.

To be more precise, the Cocoa application establish a bridge between the WebView and the Objective-C code, and can call javascript methods or receive javascript callbacks.

With MacOS 10.9.5 and MathJax v3, a callback that should be called to mark the "ready" status of MathJax is never intercepted, as if it was not emitted at all.

Of course, I have built a minimal sample code to exhibit that.
[http://chachatelier.fr/temp/TestMathJax-src.zip](http://chachatelier.fr/temp/TestMathJax-src.zip)

And a few screenshots :
[http://chachatelier.fr/temp/mathjax-v2-macos-10_15.png](http://chachatelier.fr/temp/mathjax-v2-macos-10_15.png)
[http://chachatelier.fr/temp/mathjax-v3-macos-10_15.png](http://chachatelier.fr/temp/mathjax-v3-macos-10_15.png)
[http://chachatelier.fr/temp/mathjax-v2-macos-10_9_5.png](http://chachatelier.fr/temp/mathjax-v2-macos-10_9_5.png)
[http://chachatelier.fr/temp/mathjax-v2-macos-10_9_5.png](http://chachatelier.fr/temp/mathjax-v3-macos-10_9_5.png)

**Comment by dpvc** [comment]
I don't have access to a iOS 10.9 system to check this out, so I can only give some general advice.

I notice that the finished-loading messages are wrapped inside a test for `window.myDocument` being defined.  I'm wondering if the `window.myDocument.mathjaxDidFinishLoading_` is being skipped because `window.myDocument` is not there.  Could it be that MathJax is running before `window.myDocument` has been set up by the WebView?  

Alternatively, could the line

```
self->webView.mainFrameURL = url.absoluteString
```

that loads a new document cause `myDocument` to become undefined?  It might be that the older version of WebKit acted differently when a new document is loaded.

I don't know much about WebKit, but would it be possible for your `startup.ready()` function to cause a change in the displayed DOM to verify that `ready()` is running (even if `myDocument` isn't defined)?  I.e., set some text in the window, or set the color of some text.  Then you could tell if MathJax is running its `ready()` function or not.

That's the best I can offer.  Hope that moves you forward with the process.

**Comment by dpvc** [comment]
PS, your `compileError` and `typesetError` are in the wrong place in your configuration, and so are not being used. They need to be in the `options` section.

**Comment by chacha21** [comment]
Thanks for the info.
I have fixed the misplaced compileError and typesetError
I have added a <p id="logger"> element to see the DOM being modified
I have changed the way Mathjax is loaded to defer it to a explicit call to preload()
The behaviour is still the same :
under MacOS 10.15, no problem
under MacOS 10.9.5, the MathJax startup is not called (the "logger" does show the "configure" logs, but does not show the "startup callbacks" logs)
But the problem is not visible in Safari when hitting the "preload()" button, it is only exhibited by the Cocoa application when calling algorithmically the preload() method.
It also means that the problem is not the "myDocument" bridging variable since it is not involved in the preload() call.

New src and screenshots:

[http://chachatelier.fr/temp/mathjax-v3-macos-10_15-deferred.png](http://chachatelier.fr/temp/mathjax-v3-macos-10_15-deferred.png)
[http://chachatelier.fr/temp/mathjax-v3-macos-10_9_5-deferred.png](http://chachatelier.fr/temp/mathjax-v3-macos-10_9_5-deferred.png)
[http://chachatelier.fr/temp/TestMathJax-src.zip](http://chachatelier.fr/temp/TestMathJax-src.zip)

**Comment by dpvc** [comment]
OK, thanks, that does suggest that MathJax is not running.  I wonder if you could add an `onerror` handler for the script that loads MathJax and see if that fires (and you might add an `unload` handler as well, so that one or the other should fire; old version of WebKit didn't run those handlers, but that was long ago).  Something like

```
script.onload = function () {
  document.getElementById('logger').innerHTML += 'MathJax loaded<br/>';
}
script.onerror = function (err) {
  document.getElementById('logger').innerHTML += 'MathJax failed to load: ' + err.message + '<br/>';
}
```

Perhaps that will tell you something.

**Comment by chacha21** [comment]
'MathJax loaded' is displayed, 'MathJax failed to load: ' is not (even on 10.9.5). So the script loads, but the ready() callbacks are not called.
Is there another place I can add a useful log ?

**Comment by dpvc** [comment]
> Is there another place I can add a useful log ?

Well, one possibility would be to add `try {` at the beginning of the `tex-svg.js` file, and

```
} catch(err) {
  document.getElementById('logger').appendChild(
    document.createText((err.message + '\n' + err.stack)
  );
}
```

at the end of that file, and turn the logger element into a `<pre>` so the newlines will be honored, that might tell us something.

If you are willing to install the developer tools for mathjax-full and recompile and rebuild the components, we could do more granular testing, but the above might give a sufficient clue to what is happening that that might not be necessary.

**Comment by chacha21** [comment]
I haved switched the <p> by a <pre> (and it still works with \n rather than <br/>, as expected)
I have added that try/catch to tex-svg and tex-svg-full
But no more log is visible after loading, so no exception is raised, and the problem remains out of scope for now.
I can spend time with MathJax-src if necessary.

**Comment by dpvc** [comment]
OK, thanks for trying that.  Here's something else to try before editing the code itself:

Use the configuration

``` html
<script>
function Log(message) {
  document.getElementById('logger').appendChild(document.createText(message+'\n'));
}
MathJax = {
  loader: {
    ready: function () {
      Log('> loader ready');
      MathJax.loader.defaultReady();
      Log('< loader ready');
    },
    failed: function (err) {
      Log('# Loader failed: ' + err.message);
    }
  }
}
<script>
```

and then include the script that loads `tex-svg.js`.  You should get one or the other of these messages.   I expect something is failing and since the default for that is to print to the console, we aren't seeing the message.  This should get the message where we can see it.

**Comment by chacha21** [comment]
Got it ! The try/catch should haven worked, but there was an error : "createText()" was not found and has to be replaced by "createTextNode()"
Here is the log  :
` preload_v3
&gt;configureMathJax

&lt;configureMathJax

Can't find variable: Map
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:89698
r@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:114
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:28580
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:30515
r@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:114
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:1660881
r@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:114
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:903
global code@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:913exiting big try/catch
MathJax loaded<br/>`

**Comment by dpvc** [comment]
Sorry about `createTextNode()`, I was going by memory (never a good thing).

OK, that does indicate the problem, then.  The Map object is new in ES6, so apparently the version of WebKit used in 10.9 is too cold for that.  You may want to include a polyfill for that.  We recommend using

    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>

Can you add that to your HTML file and see if that does the trick?  See the polyfill.io site for details, in case you need to have a local copy.

**Comment by chacha21** [comment]
I have added polyfill-3.52.1.min.js, and the Map error is gone, but there is still a loading failure :

`preload_v3
&gt;configureMathJax

&lt;configureMathJax

exiting big try/catch
MathJax loaded<br/>
> loader ready
&gt;defaultReady

# Loader failed: 'undefined' is not a function (evaluating 'this._configuration.find(function(t){return t.name===Q})')`

**Comment by dpvc** [comment]
OK, `_configuration` is an array, and so this is using `Array.prototype.find()`.  Apparently that version of WebKit is missing the `find()` method, and the polyfill hasn't added it.  The `es6` polyfill is supposed to do that, but perhaps you need to specify it explicitly in your case. Try

    https://polyfill.io/v3/polyfill.min.js?features=es6%2CArray.prototype.find

and see if that fixes it.  Otherwise, you may want to  add

    Log(Array.prototype.find.toString());

to your startup logging and see if you get undefined or the definition of a function.

**Comment by chacha21** [comment]
even after adding ?features=es6%2CArray.prototype.find, logging `Array.prototype.find.toString()` will just raise `exception : TypeError: 'undefined' is not an object (evaluating 'Array.prototype.find.toString')`

**Comment by chacha21** [comment]
My mistake, it works with https://polyfill.io/v3/polyfill.min.js?features=es6%2CArray.prototype.find, while it fails when using a local polyfill.min.js.
What the hell did I download from polyfill.io ?! I have to investigate

**Comment by dpvc** [comment]
I'm glad that adding the `Array.prototype.find` allows it to work.  I'm not sure how to capture the result into a local file.  I wonder if you could use `XMLHttpRequest` inside the WebView to get the file, and print it to the screen where you could copy and past it into a file.

There does seem to be an npm library (polyfill-library) so it may be possible to use that to get the file you need.

If you figure it out, please let us know!

**Comment by chacha21** [comment]
I used curl, it is now OK with the local file. I did not understand at first sight how polyfill was distributed. This is a very dynamic build !

**Comment by chacha21** [comment]
Thanks for all the answers, I would have never figured that out myself.

**Comment by dpvc** [comment]
Thanks for being able to work through the debugging process.  That saved me trying to get a MacOS 10.9 virtual machine running!

Good luck with the project.  Glad you were able to work out a solution.

**Comment by chacha21** [comment]
For information, my project is here : [](https://chachatelier.fr/chalk/index.php), and MathJax was really the only solution I found to render maths properly in such a context

**Comment by chacha21** [comment]
I reopen the issue and change its title for the next step, new problem : MathJax.typeset() does not work with 10.9.5

`error'null' is not an object (evaluating 't.body')body@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:549062
assistiveMml@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:541714
assistiveMml@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:531874
assistiveMml@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:542391
file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:352724
renderDoc@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:352956
render@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:355058
typeset@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/mathjax/v3.0.5/tex-svg.js:2:3164585
typeset@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/calculator-v3.js:21:27
onclick@file:///Users/chacha/Desktop/TestMathJax.app/Contents/Resources/Web/calculator-v3.html:18:51`

**Comment by dpvc** [comment]
The error is occurring in the assistive-mml extension that inserts hidden MathML that can be read by screen readers that handle MathML.  I'm not sure if that applies to your WebView or not.  Does VoiceOver work with your application?

One solution for now would be to disable the assistive-mml extension using

```
MathJax = {
  options: {
    renderActions: {
      assistiveMml: []
    }
  }
}
```

in your configuration.  Looking at the code, the `adaptor.body()` call is being made on the results of an `adaptor.parse()` call that is supposed to be parsing a serialized MathML string into the MathML DOM nodes.  That uses a `DOMParser` object, which might not be implemented in that version of WebKit, or might not be operating as expected.

If you want to enable the assistive MathML extension, we could do some experimenting to see if we could identify the issue.

[BTW, your calculator looks pretty cool.  I will definitely play around with it when I get some spare moments.]

**Comment by chacha21** [comment]
Setting "assistiveMml: []" works ! Thanks.

**Comment by chacha21** [comment]
Hi,
I have reports of my application not rendering anymore under MacOS 10.9.5 after I upgraded it to MathJax 3.1.4.
I have no logs yet, but do you already have hints of breaking changes in 3.1.3 or 3.1.4 that could have triggered new problems with the poor javascript support of MacOS 10.9.5 ?

**Comment by chacha21** [comment]
I am re-closing the bug.
I can't reproduce it with 3.1.4

**Comment by dpvc** [comment]
OK, thanks.  I'm glad 3.1.4 works for you.
