### ISSUE TITLE
tex-mml-svg throw TypeError:Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2420]
When I use nested html tags to typesetPromise tex , it'll throw error. I can't find why, because **tex-mml-svg.js** has been confused. How can I know what's happen, and can u give me some situations?

### Steps to Reproduce:

```js
export class A{
    render(){
        Mathjax.typesetPromise('<tex>some tex</tex>')
    }
}

// in jsx
// it'll throw TypeError:Cannot read property 'replaceChild' of null
<A>
  <A>
    <tex>some tex</tex>
  </A>
</A>

//it works good
<>
  <A>
    <tex>some tex</tex>
  </A>
</>
```

### Technical details:

* MathJax Version: 3.0
* Client OS: Mac OS X 10.15.4
* Browser: Chrome 81

**Comment by dpvc** [comment]
You don't seem to be using `MathJax.typesetPromise()` correctly.  You do not pass it a strong containing serialized HTML.  You pass it an array of DOM elements to search for math to be processed (those can be either the DOM elements themselves, or strings that act as CSS selectors for the elements).  See the last paragraph of the [documentation](http://docs.mathjax.org/en/latest/web/typeset.html#typesetting-math-in-a-web-page) for this function.

**Comment by qq240814476** [comment]
thanks, I'll change my code and retry it
