### ISSUE TITLE
Prime symbols using apostrophes break SVG output

### ISSUE THREAD

**Issue by nicknytko** [mathjax/MathJax#2425]
### Issue Summary

Representing double/triple/quadruple prime with `'` gives the following error when using the SVG output on a web page:
```
TypeError: can't access property "chars", this.font.getVariant(...) is undefined
```

### Steps to Reproduce:

1. Load MathJax with tex input and svg output, here is the config I am using:
```html
<script>
 var MathJax = {
     tex: {
         inlineMath: [['$', '$'], ['\\(', '\\)']]
     },
     svg: {
         mtextInheritFont: true,
         fontCache: 'global'
     },
     loader: {
         load: ['input/tex', 'output/svg']
     },
     /* Register a callback to be run when MathJax is loaded, use MathJax.config.onReady() */
     readyQueue: [],
     onReady: (cb) => { MathJax.config.readyQueue.push(cb); },
     startup: {
         ready: () => {
             MathJax.startup.defaultReady();
             MathJax.Hub = {
                 Queue: function(){
                     MathJax.typeset();
                     console.warn("MathJax.Hub.Queue() has been deprecated in 3.0, please use MathJax.typeset() or MathJax.typesetPromise()");
                 }
             };
         },
         pageReady: () => {
             MathJax.startup.defaultPageReady();
             MathJax.config.onReady = cb => cb();
             MathJax.config.readyQueue.forEach(cb => cb());
         }
     }
 };
</script>
<script type="text/javascript" id="MathJax-script" src="/MathJax/startup.js" async></script>
```

2.  Include the following on the page: `$$f''(0) = 0$$"` OR in the JS console run `MathJax.tex2svg("$$f''(0) = 0$$")`

### Technical details:

* MathJax Version: 3.0.5
* Client OS: Arch Linux
* Browser: Firefox 76.0a1

### Supporting information:

I've done some digging and this looks to be related to the `unicodeChars()` function: https://github.com/mathjax/MathJax-src/blob/77bb06d267b2fe5949bf11c3b87f2a10251fc469/ts/output/common/Wrapper.ts#L706.

**Comment by dpvc** [comment]
Thanks for the report.  This turns out to be the same issue as #2402.  The work-around given there should resolve the problem for you until the next release, where it will be fixed.

**Comment by nicknytko** [comment]
Oh! Thanks, I'll close this issue out since it's a duplicate.
