### ISSUE TITLE
Issue with primes in tex-svg

### ISSUE THREAD

**Issue by ulthiel** [mathjax/MathJax#2432]
Typesetting $$y''$$ with tex-mml-chtml.js works fine but doesn't work with tex-svg.js.

Minimal example:
```
<html>
<head>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
</head>

<body>
$$y''$$
</body>

</html>
```

**Comment by ulthiel** [comment]
Sorry, duplicate of #2409.

**Comment by ulthiel** [comment]
Sorry, duplicate of #2409.

**Comment by dpvc** [comment]
Thanks for spotting it yourself.  It will be fixed in the next release.
