### ISSUE TITLE
Multi-lined environments with \\*

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2433]
### Issue Summary

MathJax v3.

With multline and similar, `\\` and `\\[2ex]` work as expected, but `\\*` and `\\*[2ex]` fail.  The star and trailing optional argument are not absorbed.

### Steps to Reproduce:
```
<!DOCTYPE html>
<html lang="en-US">
<head>
<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>
</head>
<body>

<p>

\begin{multline}
\tan a+b &lt; c \\
\cos (d)+sin(e) \\*
\cos (f)+sin(g) \\*[2ex]
h+i=j
\end{multline}

</p>

</body>
</html>
```

**Comment by dpvc** [comment]
You are correct, MathJax doesn't process `\\*`.  This is because the star is about controlling page breaks, which are outside the scope of MathJax output.  But I do suppose it should process and ignore the star.  I've marked it as a "feature request" for that.
