### ISSUE TITLE
Horizontal arrows in AMScd too short in MML-CHTML, fine in SVG

### ISSUE THREAD

**Issue by ulthiel** [mathjax/MathJax#2434]
The MathJax 3.0.5 output of the following AMScd diagram looks fine in SVG mode but not in MML-CHTML mode (the horizontal arrows are too short). 

\begin{equation}
\begin{CD}
A     @>a>>  B\\
@VVbV        @VVcV\\
C     @>d>>  D
\end{CD}
\end{equation}

<img width="114" alt="svg" src="https://user-images.githubusercontent.com/6717247/81782253-d7696e80-94f9-11ea-848e-ad7ac03f560e.png">
<img width="126" alt="html" src="https://user-images.githubusercontent.com/6717247/81782274-de907c80-94f9-11ea-8f16-0c0a17ec956e.png">

In MathJax 2 this looked fine in HTML mode.

**Comment by dpvc** [comment]
Can you say what browser and OS you are using?

I can see a problem in Safari, but it is not exactly the same as your output.  Recent versions of Chrome and Firefox work for me.

**Comment by ulthiel** [comment]
Sorry, I should have said that: Safari 13.1, macOS 10.15.4. 
I checked with Firefox, there it looks fine (the vertical arrows are always bit too short IMO).

**Comment by dpvc** [comment]
I believe that version 3.2 has resolved this issue.  Can you check to see if that is the case?
