### ISSUE TITLE
Characters partially disappear when zooming on iOS devices

### ISSUE THREAD

**Issue by loopspace** [mathjax/MathJax#2435]
### Issue Summary

When using "pinch to zoom" on an iOS device (iPad/iPhone) on a page with MathJaX rendered as "CommonHTML" (such as the MathJaX test page) then characters flicker and if the zoom is stopped in the right place then they can (partially) disappear.

This does not happen with the SVG renderer.

### Steps to Reproduce:

1. Open up the samples page https://www.mathjax.org/#samples on an iOS device - I tested with safari and chrome.  Make sure it is set to render as "CommonHTML"
2. Use the "pinch to zoom" facility to zoom in on a piece of Mathematics.  You should see a noticeable flicker.
3. You can "catch" the flicker in the act if you stop the zoom carefully.

Although most of the time it's really obvious that something weird is happening, if the zoom is _just right_ then it can turn a plus into a minus.

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: iPadOS 13.4.1, also confirmed on an iPhone (iOS version unknown)
* Browser: Chrome 81.0.4044.124, Safari (latest version - can't find version number)

### Supporting information:

Screenshots from the MathJaX samples page.

![image](https://user-images.githubusercontent.com/4444762/81805400-b103fd00-9512-11ea-8bce-34a09da24280.png)
![image](https://user-images.githubusercontent.com/4444762/81805426-bf521900-9512-11ea-98e5-7ca5a83c562d.png)
![image](https://user-images.githubusercontent.com/4444762/81805450-c6792700-9512-11ea-9dac-f57f6a6a56ba.png)

**Comment by dpvc** [comment]
We have seen this with Safari, and other WebKit based browsers.  See for example [this post](https://groups.google.com/d/msg/mathjax-users/crqVVSNyTpQ/NLjNgI38AwAJ).  We do not currently know of a work-around.  This summer we are working on the font support for v3, and will be looking into this issue at that time.

**Comment by llui85** [comment]
This appears to be something weird going on with the fonts. [See this codepen](https://codepen.io/llui85/full/YzWNMzJ), in which I have copied the font declarations from MathJax and just displayed some text. I can still reproduce this issue on iOS with just the fonts.

**Comment by llui85** [comment]
I converted one of the fonts to TTF and then back to WOFF2, and this [seems to have fixed the issue](https://codepen.io/llui85/full/wvWgbXp). Could something we wrong in the font generation process?

**Comment by llui85** [comment]
@dpvc 
How are the TEX fonts generated?

**Comment by dpvc** [comment]
> I converted one of the fonts to TTF and then back to WOFF2, and this seems to have fixed the issue. Could something be wrong in the font generation process?

The MathJax fonts have some font metrics set in an unusual way in order to be able to position them more easily in math formulas.  Your conversion process probably reset those parameters, so they worked better as text fonts.  

We are in the middle of doing a font overhaul and will be replacing the MathJax fonts with newer versions.  We hope to address this problem at that time.  Doing so may require changes to MathJax internals, however.

**Comment by LLWest1** [comment]
Is this font overhaul project still being planned?  Will this include support for more fonts, similar to MathJax 2.0.
"We are in the middle of doing a font overhaul and will be replacing the MathJax fonts with newer versions. We hope to address this problem at that time. Doing so may require changes to MathJax internals, however."

Is there a planned fix for the iPad rendering issue? (I can provided examples if needed). With 3.1 we are seeing issues with MathJax cutting of the screen on IPad iOS.  We also have a preference for sticking with our existing 2.0 font choice.

Will this include support for more fonts, similar to MathJax 2.0.

**Comment by mt4c** [comment]
Setting the css will-change property to "will-change: unset;" seems to solve the issue.
from https://stackoverflow.com/questions/52655475/why-is-safari-cutting-off-the-top-of-this-text

**Comment by dpvc** [comment]
@mt4c, thanks for the tip.  It seems that setting one of these two starts a new "stacking context" (see the Mozilla documentation [here](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change), in particular the description of the <custom-ident> half way down the page), and that seems to be what does the trick.  I tried other techniques that start a stacking context, but by themselves, they don't do it.

That page suggests that this is not recommended for leaving on in a stylesheet, which is what is necessary for Safari, so I'd recommend using a "WebKit-only" CSS wrapper.  For example,

``` css
  @supports (-webkit-marquee-repetition:infinite) and (object-fit:fill) {
    mjx-container mjx-c::before {
      will-change: opacity;
    }
  }
```

works to select only Safari (and not Chrome) for this change, and to apply it only on the characters themselves.

Again, thanks for the solution, here.  I would not have found this myself (and didn't).

**Comment by dpvc** [comment]
I've made a PR with this solution.

**Comment by mt4c** [comment]
@dpvc I read the MDN document and follow the link https://dev.opera.com/articles/css-will-change-property/ in stacking context page (following the will-change description).
Found out that "transform: translzteZ(0);" also does the trick.

**Comment by dpvc** [comment]
@mt4c, thanks for the follow up, and the pointer to the interesting article.  I had tried some `transform` values, but didn't think to try that one.  Thanks.  There are also new developments in the PR comment list.  I will revise the PR based on that.  I'm not sure whether to use your `transform` property or the original `will-change: opacity`, as I'm not sure which one uses more resources.  My gut feeling is that `will-change: opacity` may be less intensive.  With this new information about what is actually happening under the hood, I will see if I can make a better PR.

**Comment by physics-archive** [comment]
I have tried these solutions but am still experiencing the same type of cutoff. Maybe these solutions were broken by future updates?
