### ISSUE TITLE
copy and paste not working

### ISSUE THREAD

**Issue by nschloe** [mathjax/MathJax#2439]
When using MathJax through [Green Pi](https://github.com/nschloe/green-pi), copy-and-pasting doesn't work: The math text is not selected. Is there an option I forgot to turn on?

**Comment by dpvc** [comment]
This is a duplicate of #2240.  See my [answer}(https://groups.google.com/d/msg/mathjax-users/1BzTQFINbqY/xGYAlhDNAwAJ) to a similar post (now deleted) in the MathJax user's forum.  It includes code that may provide support for what you want.

**Comment by nschloe** [comment]
Closing as dup, thanks for the explanation!
