### ISSUE TITLE
Deterministic ctxmenu_counter (or rather _id)

### ISSUE THREAD

**Issue by hsk81** [mathjax/MathJax#2442]
### Issue Summary

If a MathJax formula get's rendered, then a `ctxtmenu_counter` is produced, like below:

```html
<mjx-container ... ctxtmenu_counter="1">...</mjx-container>
```
It seems that with each re-render this counter changes, although the content itself did not change at all. In my www.notex.ch project, where I'm using a diff-patch approach, this causes a rerender of all the formulae. Further, when I take a document hash then with each re-render the hash changes also -- although technically it's the same content.

### Steps to Reproduce:

1. Provide any formula
2. Have it rendered with MathJax
3. Check HTML output w.r.t. the `ctxtmenu_counter`

### Expectation

Each time when the same formula gets rendered, then each time *exactly* the HTML should be produced.

### Observation

Due to the `ctxtmenu_counter` changing on each re-render determinism is lost.

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Mac OS X 10.8.4
* Browser: Chrome 29.0.1547.57

### Supporting information:

 * Go to https://www.notex.ch, where I'm using MathJax ;
 * enter a formula on the left-hand side, between dollar signs, e.g. $$e^{i\pi}-1=0$$ ;
 * Check with the browser's inspector the produced HTML (on the right-hand side) ;
 * press the *refresh* button on the right-hand side toolbar (the two circling arrows) ;
 * re-check with the browser's inspector the produced HTML (on the right-hand side) ;
 * observe that `ctxmenu_counter` is different on each refresh.

I'm actually not interested in the context menu at all: I tried to disable it, in the hope that the `ctxmenu_counter` attributes would vanish, but they still get rendered in the HTML.

**Comment by dpvc** [comment]
Your `addMenu` option is in the wrong place.  It should be in `MathJax.options.renderActions`, as in 

``` javascript
MathJax = {
  options: {
    renderActions: {
      addMenu: [],
      checkLoading: []
    }
  }
};
```

in order to disable the menus.  That will prevent the menu classes and attributes from being added to the output.

**Comment by hsk81** [comment]
@dpvc Cool, thank you that did the trick! ;D However, since my diff-patch approach with `tex-mml-svg.js` was still causing flickering of all formulae, I had to switch over to `tex-mml-chtml.js`: I guess however, that this is more a problem my diff-patch algo that seems to re-patching the SVGs.
