### ISSUE TITLE
physics extension missing macros

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2449]
v3 physics extension:

Missing the macros: `\Bqty`, `\Residue`, `\ip`.

(`\Residue` is in the style file, but not mentioned in the physics package documentation.)

It would be nice to have a way to request the equivalent to the options `italicdiff` and `arrowdel`.

```
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />
<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>
</head>

<body>


<div class="hidden" >
\(\require {physics}\)
</div>


<p>
<kbd>\pqty</kbd>: \(\pqty {a}\) <kbd>\vqty</kbd>: \(\vqty {a}\) <kbd>\bqty</kbd>: \(\bqty {a}\) <kbd>\Bqty</kbd>: \(\Bqty {a}\)
</p>


<p>
<kbd>\Residue</kbd>: \(\Residue [f(z)]\)
</p>


<p>
<kbd>\innerproduct</kbd>: \(\ip {\frac {A}{B}} \quad \ip {\frac {A}{B}}{b}\)
</p>

<p>
<kbd>\innerproduct*</kbd>: \(\ip *{\frac {A}{B}} \quad \ip *{\frac {A}{B}}{b}\)
</p>

</body>
</html>
```

**Comment by zorkow** [comment]
* `\Bqty` is actually implemented but produces an error.
* `\Residue` is not in the [manual]( http://mirrors.ibiblio.org/CTAN/macros/latex/contrib/physics/physics.pdf). But it should be added as the base operator for '\Res'
* `\ip` must have been an oversight and should be added.

**Comment by ickc** [comment]
copy from #694 to deduplicate:

The following commands are not working:

    \Bqty{ \frac{1}{1+\frac{1}{2}} }
    \qsince

**Comment by zorkow** [comment]
[PR 704](https://github.com/mathjax/MathJax-src/pull/704) implements the missing/incorrect macros and the two options.

Options can be set in the global configuration object:
```javascript
    <script>
      MathJax = {
      tex: {
          packages: ['base', 'physics'],
          inlineMath: [['$', '$'], ['\\(', '\\)']],
          physics: {
             italicdiff: true,
             arrowdel: true
           }
         }}
    </script>
```
That does not yet work with `\require`.
