### ISSUE TITLE
Don't replace the stylesheet when option adaptiveCSS is false

### ISSUE THREAD

**Issue by mt4c** [mathjax/MathJax#2454]
### Issue Summary

When the adaptiveCSS is false, there is no need to replace the stylesheet ( the "MJX-CHTML-styles" element ) on typesetting. It cause flicker on old version browsers and slow devices.

### Steps to Reproduce:

1. Typeset some math on the page.
2. Typeset some other math on the page. The old maths flicker.

### Technical details:

* MathJax Version: 3
* Client OS: Android
* Browser: Chrome 52

### Supporting information:

I copy the stylesheet and modify the font-family name. Make the font family styles "!important". Insert it in the page. Then the flickers disappear.

**Comment by dpvc** [comment]
Thanks for the report.  I've made a pull request to resolve the issue.

**Comment by dpvc** [comment]
Fixed in v3.1 released today.
