### ISSUE TITLE
Expose latex to mathjax internal representation translation API

### ISSUE THREAD

**Issue by cl4yton** [mathjax/MathJax#2457]
The MathJax Web Demo tex-chtml.html (https://mathjax.github.io/MathJax-demos-web/tex-chtml.html) shows a configuration of MathJax that will process an entire webpage, find existing LaTeX source, extract and translate to MathJax's internal representation, and then render the equation in place. 

I would like to be able to just call the portion of MathJax such that I could pass a single string (or other object) containing the LaTeX source (for a single equation) and have MathJax return and instance of its internal representation.

Is this functionality already available? 
If not, could it be exposed?

**Comment by dpvc** [comment]
The first four examples in the [Processing User Input](https://mathjax.github.io/MathJax-demos-web/#processing-user-input) section of the demos repository show how to do what you ask.  See also the documentation on [converting a math string to other formats](http://docs.mathjax.org/en/latest/web/typeset.html#converting-a-math-string-to-other-formats).
