### ISSUE TITLE
No API to map font URLs 

### ISSUE THREAD

**Issue by kovidgoyal** [mathjax/MathJax#2458]
### Issue Summary

I am trying to port a MathJax v2 to v3 use case for calibre. This involves loading MathJax inside a sandboxed iframe. In v2 I could monkeypatch fileURL to map font urls to blob urls inside the iframe. In v3, as far as I can tell, the equivalent function to patch is addFontURLs() however, I dont know where it lives. It would be very helpful if someone could give me a pointer on how to monkeypatch this function.

It would be even nicer if you would be willing to allow the fontURL option to be a function or a string, instead of just a string. The function would take the URL and return the mapped URL.

**Comment by kovidgoyal** [comment]
Ah, it appears to MathJax.startup.output.font now to figure out the best point in the life cycle to monkeypatch it

**Comment by kovidgoyal** [comment]
And monkeypatching it after a call to defaultReady does the trick

**Comment by sanmai-NL** [comment]
@kovidgoyal Is this issue closeable?
