### ISSUE TITLE
underset in inline equation

### ISSUE THREAD

**Issue by MacroUniverse** [mathjax/MathJax#2460]
the inline equation $\underset{i\ge k}{\bigcup}$ produce "i \ge k" under \bigcup in texlive, but using mathjax, it's on the lower right, unless \displaystyle is added.

however, $\underset{i\to \infty}{\lim}$ will work as expected.

I'm using mathjax 3.0.0.

**Comment by dpvc** [comment]
Thanks for the report.  I can confirm the error.

**Comment by dpvc** [comment]
Fixed in v3.1 released today.
