### ISSUE TITLE
mathjax 3 latex command underbrace gives js error (svg) or faulty output (chtml)

### ISSUE THREAD

**Issue by ronligt** [mathjax/MathJax#2466]
### Issue Summary

When using **tex->svg** in Mathjax 3 the use of the latex command `\underbrace` results in a javascript error:

```
Unhandled Promise Rejection: TypeError: t.setAttribute is not a function.
   (In 't.setAttribute(Q,e)', 't.setAttribute' is undefined)
```
When using **tex->chtml** the equation is rendered but gives an ugly result:
<img width="616" alt="tex_chtml_underbrace" src="https://user-images.githubusercontent.com/6848987/86785561-1da6fe00-c063-11ea-976f-fdc9a0465030.png">

This happens in Firefox 78.0.1, Safari 13.1.1 and Chrome 83.0.4103.116 tested on macOS 10.15.5

### Steps to Reproduce:

1. write `HTML` as follows:

```html
<!DOCtype html>
<html>
    <head>
        <title>Test underbrace</title>
    </head>
    <body>
        $$\underbrace{blablabla}_{bloe}$$
        <script type="text/javascript" id="MathJax-script" async
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js">
        </script>
    </body>
</html>
```

2. Open `HTML`-file in browser
3. Observe error in javascript-console
4. replace in `HTML`-file `tex-mml-svg.js` with `tex-mml-chtml.js`
5. Re-open `HTML`-file in browser
6. Observe output as included above

### Technical details:

* MathJax Version: 3
* Client OS: Mac OS X 10.15.5
* Browser: Firefox 78.0.1, Safari 13.1.1 and Chrome 83.0.4103.116

### Supporting information:

 * no mathjax-configuration is used

**Comment by dpvc** [comment]
The svg issue is a duplicate of #2408, which is in turn a duplicate of #2402.  There is a work-around in the latter that you may be able to use.

The CommonHTML issue is a known issue (though I don't think there is an issue tracker for it).  I hope to have a fix for it this summer, as we work on font issues.

**Comment by ronligt** [comment]
Thank you very much for the speedy reply and fix!

**Comment by eric-wieser** [comment]
> The CommonHTML issue is a known issue (though I don't think there is an issue tracker for it). I hope to have a fix for it this summer, as we work on font issues.

Is it related to #661?

**Comment by dpvc** [comment]
@eric-wieser, no, #661 is for v2, and the mechanism used for stretchy characters v3 is substantially different.  Also, #661 only affected the Asana-Math font, which is not yet available in v3.

**Comment by eric-wieser** [comment]
Ah, ok. I'm still seeing the same problem, so I guess this hasn't been fixed yet:

![image](https://user-images.githubusercontent.com/425260/186475425-be4c1c0e-ecf7-4009-982b-55cdb501bead.png)

Do you know of any other discussions about this elsewhere?

**Comment by eric-wieser** [comment]
The cause seems to be the
```
mjx-stretchy-h > mjx-ext > mjx-c::before {
    transform: scalex(500);
}
```
If I change this to 200 the problem goes away.

**Comment by dpvc** [comment]
We are preparing an alpha release that includes support for alternative fonts, and that includes a new font set for the default font.  Your example works for me with the current v3 in Safari 15.5 on Mac OS 12.4, as well as Firefox 104.0 and Chrome 104.0.5112.101.

<img width="475" alt="braces" src="https://user-images.githubusercontent.com/432782/186482205-3a13e8f0-bfea-4891-80a6-0907013ac027.png">

and also with the new fonts.  

Can you tell me the OS and browser versions that you are using?

**Comment by eric-wieser** [comment]
I will try to update with exact versions tomorrow, but this was with Chrome on Windows 10.

**Comment by eric-wieser** [comment]
Chrome is at `Version 104.0.5112.102 (Official Build) (64-bit)`, and Windows 10 Pro is at version 1909.
