### ISSUE TITLE
Cases rendering locally, but not on Github Pages

### ISSUE THREAD

**Issue by lukzmu** [mathjax/MathJax#2470]
### Issue Summary

I have a problem where MathJax renders `cases` correctly locally on my computer, but fails to do so on GithubPages.

### Steps to Reproduce:

1. Add the following code in my blog post:
```
$$
U_{att}(q) = \begin{cases}
        \frac{1}{2} \zeta d^2(q, q_{goal}), & d(q, q_{goal}) \leq d_{goal}^*,\\
        d_{goal}^* \zeta d(q, q_{goal}) - \frac{1}{2} \zeta (d_{goal}^*)^2, & d(q, q_{goal}) \gt d_{goal}^*.\\
    \end{cases}
$$
```
2. Works perfectly well when on my local machine.
3. Publish blog post to Github
4. There is no math code present.

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Mac OS X 10.8.4
* Browser: Chrome 29.0.1547.57

### Supporting information:

Link to post:
https://zmudzinski.me/posts/2020/07/potential-fields

MathJax is loaded because you can see it displays other equations.
You can see missing `cases` in the blank lines in the later part of the post.

**Comment by dpvc** [comment]
This is a duplicate of #2377.  There is a work-around listed in my answer to that issue.

**Comment by lukzmu** [comment]
> This is a duplicate of #2377. There is a work-around listed in my answer to that issue.

Will check this out in a while and will come back to you, if it works. Thanks!

**Comment by lukzmu** [comment]
Thanks @dpvc. It worked!
