### ISSUE TITLE
The linebreaks are not being rendered as expected

### ISSUE THREAD

**Issue by Joyeeta** [mathjax/MathJax#2471]
I have created a mathML which looks like `<math xmlns="http://www.w3.org/1998/Math/MathML"><mn>200</mn><mspace linebreak="newline"/><mo>+</mo><mn>3</mn></math>`. I was expecting a line break to be introduced after `<mn>200</mn>` when I render this MathML thorough mathJax.  But unfortunately, I am not seeing the line break.

This is react codebase where I am basically rendering the MathMLs in web browsers using MathJax 2.7 . I am using a mml3.js extension and my entire config looks like -

```
{
  AsciiMath: {
    useMathMLspacing: true,
  },
  CommonHTML: {
    fonts: [
      'STIX',
      'TeX',
    ],
    linebreaks: {
      automatic: true,
    },
  },
  'HTML-CSS': {
    fonts: [
      'STIX',
      'TeX',
    ],
    linebreaks: {
      automatic: true,
    },
  },
  MathML: {
    extensions: ['mml3.js'],
    linebreaks: {
      automatic: true,
    },
  },
  asciimath2jax: {
    delimiters: ['`'],
  },
  extensions: [
    'asciimath2jax.js',
    'tex2jax.js',
    'mml2jax.js',
  ],
  jax: [
    'input/TeX',
    'input/MathML',
    'input/AsciiMath',
    'output/HTML-CSS',
  ],
  messageStyle: 'none',
  tex2jax: {
    `inlineMath: [[ ['$','$'], ["\\(","\\)"] ],],`
    preview: 'none',
  },
}
```

Could you point me where I am going wrong?

Note: I have tried with both linebreaks automatic set as true or false as found in https://docs.mathjax.org/en/v2.7-latest/options/output-processors/HTML-CSS.html

**Comment by dpvc** [comment]
I am not able to reproduce your issue.  The expression breaks properly for me.  Here is an example file that works for me.

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>MathJax MathML Linebreaks</title>
<script>
MathJax = {
  AsciiMath: {
    useMathMLspacing: true,
  },
  CommonHTML: {
    fonts: [
      'STIX',
      'TeX',
    ],
    linebreaks: {
      automatic: true,
    },
  },
  'HTML-CSS': {
    fonts: [
      'STIX',
      'TeX',
    ],
    linebreaks: {
      automatic: true,
    },
  },
  MathML: {
    extensions: ['mml3.js']
  },
  asciimath2jax: {
    delimiters: [['`', '`']],
  },
  extensions: [
    'asciimath2jax.js',
    'tex2jax.js',
    'mml2jax.js',
  ],
  jax: [
    'input/TeX',
    'input/MathML',
    'input/AsciiMath',
    'output/HTML-CSS',
  ],
  messageStyle: 'none',
  tex2jax: {
    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
    preview: 'none',
  },
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js"></script>
</head>
<body>

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mn>200</mn>
  <mspace linebreak="newline"/>
  <mo>+</mo>
  <mn>3</mn>
</math>

</body>
</html>
```

Note that there were several issues with your configuration that I corrected in the code.  In particular, the `ascimath2jax` delimiters need to be an array of arrays, with both an opening and closing delimiter, the use of backticks around the `inlineMath` property is incorrect and there are too many array brackets, and the `MathML` block does not have a `linebreaks` option (so it is just ignored).  

Perhaps one of these is causing your problem?  If not, you will need to provide a minimal (non-)working example, not just a configuration snippet.
