### ISSUE TITLE
Analog of katex htmlData command for enriching math with dom dataset values

### ISSUE THREAD

**Issue by dainiak** [mathjax/MathJax#2472]
Currently MathJax supports enrichment of formulas with html id and css class attributes. Sometimes it is convenient do add some extra data to an element which does not naturally converts into e.g. css class assignment (e.g. attaching [data-fragment-index](https://revealjs.com/fragments/#fragment-order) to parts of math formula when making a [reveal.js](https://github.com/hakimel/reveal.js/) presentation).

Recently [KaTeX added an HTML extension](https://katex.org/docs/supported.html#html) which supports \htmlData macro to add “data-xxx” attributes to the created math elements as well. It would be great so see this feature in MathJax as well.

**Comment by dpvc** [comment]
This is implemented via mathjax/MathJax-src#802 and will be in the next release.
