### ISSUE TITLE
Stoichiometric numbers have extra space

### ISSUE THREAD

**Issue by bszabo44** [mathjax/MathJax#2478]
### Issue Summary

Windows 10,  latest FF and Chrome, Mac chrome. Happens with both svg and chtml

### Steps to Reproduce:

1. $\ce{ 2H2O }  - as all documentation sources state.
2. ![Capture](https://user-images.githubusercontent.com/1420054/88202899-8374b780-cc17-11ea-9a99-60f982ef4168.PNG)
3. Here is the offending section of resulting svg, this element should not be present between the 2 and H

**`<g data-mml-node="mstyle" transform="translate(500, 0)"><g data-mml-node="mspace"></g></g>`**

### Technical details:

* MathJax Version: 3.x (latest ) via https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
* Client OS: All
* Browser: All tested

**Comment by dpvc** [comment]
The `mhchem` extension is a thrid-party extension that is maintained by its author, Martin Hensel.  Martin is the author of the original LaTeX package as well, and he has made the MathJax and LaTeX packages work via the same algorithms.  The space is being inserted explicitly by that package, and it is as documented in the [package documentation](http://ftp.math.purdue.edu/mirrors/ctan.org/macros/latex/contrib/mhchem/mhchem.pdf) on CTAN.  Here is an image from there, which shows the spacing as it appears in MathJax:

<img width="499" alt="mhchem" src="https://user-images.githubusercontent.com/432782/88221209-20444e80-cc32-11ea-82e2-9c3758abcf0a.png">

If you wish to object to that layout, you should report the issue at the [mhchem GitHub site](https://github.com/mhchem/MathJax-mhchem).  Should Martin change the output, it will be incorporated into MathJax at that time.

**Comment by bszabo44** [comment]
Thank you for the prompt and detailed response.  I will let my SME know!
