### ISSUE TITLE
Web Worker problem

### ISSUE THREAD

**Issue by edemaine** [mathjax/MathJax#2489]
### Issue Summary

I'm trying to build a Web Worker that will take LaTeX math inputs and convert them into SVG source (via `postMessage`) for background rendering of LaTeX expressions.  I feel like this should be very close to the [existing Node demos](https://github.com/mathjax/MathJax-demos-node). But I'm getting the following error message when calling `MathJax.tex2svg`:

```
Uncaught TypeError: Cannot read property 'apply' of undefined
    at StackItemFactory.AbstractFactory.create (Factory.js:63)
    at new Stack (Stack.js:42)
    at new TexParser (TexParser.js:67)
    at TeX.compile (tex.js:134)
    at HTMLMathItem.AbstractMathItem.compile (MathItem.js:57)
    at Object.eval [as renderMath] (MathDocument.js:107)
    at RenderList.renderConvert (MathDocument.js:159)
    at HTMLMathItem.AbstractMathItem.convert (MathItem.js:53)
    at HTMLDocument.AbstractMathDocument.convert (MathDocument.js:299)
    at Object.exports.MathJax.<computed> (startup.js:180)
```

As far as I understand, `configuration.items` isn't getting set to include any node types, and so `this._factor.create('start')` can't find the node type `'start'` to call. But I'm not very familiar with the MathJax code, so am uncertain of the exact cause here.

### Steps to Reproduce:

1. Clone this demo repo: https://github.com/edemaine/tex2svg-webworker
2. `npm install` (which runs `webpack` via a `prepare` script)
3. Run a local web server, e.g., `python3 -m http.server` or `python2 -m SimpleHTTPServer`
4. Open web browser on `localhost` with appropriate port, e.g. `localhost:8000`. Note that `index.html` just launches a Web Worker that runs the Webpack-bundled `dist/tex2svg.js`.
5. Open JavaScript console to see the error message.

I expected some SVG code to be output to console, but instead MathJax crashes.

Admittedly, `node dist/tex2svg.js` does the same thing, so maybe I'm doing something wrong...

### Technical details:

* MathJax Version: 3.0.5
* Client OS: Windows
* Browser: Chrome 84.0.4147.105

### Supporting information:

https://edemaine.github.io/tex2svg-webworker/ is a live web demo -- going there produces the console error above.

**Comment by dpvc** [comment]
The problem is that the `packages` configuration option should be an array of strings, not a single string.  If I replace

    tex: packages: ['base, autoload, require, ams, newcommand'

by

    tex: packages: ['base', 'autoload', 'require', 'ams', 'newcommand']

then it works for me.

**Comment by edemaine** [comment]
Many thanks for finding this discrepancy!  I just got a chance to check that this indeed fixes the problem.  <3

**Comment by qq240814476** [comment]
> Many thanks for finding this discrepancy! I just got a chance to check that this indeed fixes the problem. <3

Hi, dude, could u shall the web worker version MathJax in github ? It sounds good, because it'll solve the problem that big mirco task for calculating block render. But I stop try it, because I reallized it won't reduce the consume of CPU. So I have a crazy idea, write MathJax in C++ and then complize  .cpp to .wasm by webassembly.

**Comment by edemaine** [comment]
@qq240814476 Check out https://github.com/edemaine/tex2svg-webworker which has instructions about how to use a web worker to render LaTeX via MathJax. But it requires JavaScript.
