### ISSUE TITLE
return to line not working !

### ISSUE THREAD

**Issue by Lagrida** [mathjax/MathJax#2491]
### Issue Summary

I try to return to line with `\\` but didn't work!

### Steps to Reproduce:
Example:
```
a \\ b
```
Then, the page display `ab`

### Technical details:

* MathJax Version: 3.0.5
* Client OS: all
* Browser: all

**Comment by dpvc** [comment]
This is a duplicate of #2312 (and #2382 and #2418).  Line-break support is not yet implemented in v3.
