### ISSUE TITLE
Space between \begin or \end and the following brace

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2494]
### Issue Summary

If a space is included after \begin or \end and the following brace, the environment is not rendered.

Ex. `\begin{equation}` works, but `\begin {equation}` does not.

(I didn't see this addressed in the docs or in previous Github issues.)

### Supporting information:

```
<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />

<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>

</head>
<body>

<p>
No spaces:
</p>

\begin{equation}
y=mx+b
\end{equation}

<p>
Space after begin:
</p>

\begin {equation}
y=mx+b
\end{equation}

<p>
Space after end:
</p>

\begin{equation}
y=mx+b
\end {equation}
</body>
</html>
```

**Comment by dpvc** [comment]
You are correct, the search pattern for the `\begin` command doesn't include spaces.  I will look into fixing that.

**Comment by dpvc** [comment]
I have made a PR to resolve the issue.  Thanks for the report!
