### ISSUE TITLE
the bold + italic font makes the web page uglier

### ISSUE THREAD

**Issue by DibasDauliya** [mathjax/MathJax#2499]
I have tons of mathjax equation in my web page. Some texts are of html text and some are mathjax equation. 

These fonts are not matching to each other which is making web page mix mix type. 

I searched about it and I got to know mathjax only offers few fonts in its documentation page. If I convert the whole text in mathjax text then it would take more time to load and also I don't like the bold/italics/more size type font that mathjax offers.  

Please forgive me, If I'm asking this question in the wrong platform . But I really want its solution and no one is helping me in this. I want your help.

The below image is when mathjax is being loaded (I want this state).
![image](https://user-images.githubusercontent.com/51583004/90228823-9fdecb00-de36-11ea-91dd-d389bf954d00.png)

And this is when mathjax is completely loaded:
![image](https://user-images.githubusercontent.com/51583004/90228892-bf75f380-de36-11ea-9dac-5a252cd0f8f6.png)

I want the font/font style of the above image(1st image). Is that possible?

This is the code that I'm using:
This is mathjax init code:
```
<script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          tex2jax: {inlineMath: [['$','$']]},
          "HTML-CSS": { linebreaks: { automatic: true } },
          CommonHTML: { linebreaks: { automatic: true } },
          SVG: { linebreaks: { automatic: true } }
        });
        </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML-full"></script>
```

This is code that I showed in above picture:
```
<li class="ans">Solution, <br>
                $\begin{aligned}
                Given, 
                f(x) & = 3x \\
                g(x) & = x + 2 \\
                fog(x) &= 18 \\
                \end{aligned}$ <br>
                To find: x = ?, <br>
                Now, <br>
                $\begin{aligned}
                \text{fog(x)} & = 18 \\
                \text{or, f(x + 2)} & = 18 \\
                \text{or, 3(x + 2)} & = 18 \\
                \text{or, x + 2} & = 6 \\
                \therefore \text{x} & = 4 \\
                \end{aligned}$
                </li>
```

**Comment by dpvc** [comment]
You are not consistent in your use of math and text, and that is part of the issue you are facing. For example, the "Given," should be in `\text{...}` so that it is upright text (math italics is not designed to be used for words, even italicized words).  On the other, hand `f(x+2)` should be in math mode, not `\text{}`.  Straightening out those issues will help a lot.

Then, if you want to use the surrounding text font for the `\text` elements, you can set the `mtextFontInherit` property if the output jax to `true`.  This will use the body text font for any `text{}` content within the math.

Here is the configuration:

``` html
  <script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    tex2jax: {inlineMath: [['$','$']]},
    "HTML-CSS": { linebreaks: { automatic: true }, mtextFontInherit: true },
    CommonHTML: { linebreaks: { automatic: true }, mtextFontInherit: true },
    SVG: { linebreaks: { automatic: true }, mtextFontInherit: true }
  });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-AMS_CHTML-full"></script>
```

(note that I switched to CommonHTML rather than the older and slower HTML-CSS output jax).  Then the text of the page would include

``` html
<ol>
  <li class="ans">
  Solution: <br>
  $\begin{aligned}
  \text{Given }
  f(x) & = 3x, \\
  g(x) & = x + 2, \\
  (f\circ g)(x) &= 18. \\
  \end{aligned}$ <br><br>
  To find: $x = {}$?. <br><br>
  Now <br>
  $\begin{aligned}
  (f\circ g)(x) & = 18 \\
  \text{or, } f(x + 2) & = 18 \\
  \text{or, } 3(x + 2) & = 18 \\
  \text{or, } x + 2 & = 6 \\
  \therefore x & = 4. \\
  \end{aligned}$
  </li>
</ol>
```

**Comment by dpvc** [comment]
Here is the result of the code above:

<img width="206" alt="text" src="https://user-images.githubusercontent.com/432782/90296748-661fbb80-de5a-11ea-926d-1aa81a378b59.png">

**Comment by DibasDauliya** [comment]
@dpvc Thank you so much. :)

**Comment by DibasDauliya** [comment]
@dpvc  And, Isn't there any technique to include html tag inside mathjax? I want to make the text 'A' round inside mathjax as of the figure.

**Comment by DibasDauliya** [comment]
@dpvc ??? :(

**Comment by DibasDauliya** [comment]
@dpvc help me please
