### ISSUE TITLE
Integral sign cropped in Cauchy's formula MathML Chrome 400% zoom

### ISSUE THREAD

**Issue by DominicCronin** [mathjax/MathJax#250]
Google Chrome 19.0.1084.46 m running on Windows 7
http://www.mathjax.org/demos/mathml-samples/
Zoom the browser to 400% and view Cauchy's integral formula (note: slightly larger or smaller zooms look OK)
The Integral sign is clipped off on the right, and the f is also missing a bit on the right

**Comment by pkra** [comment]
Seems to have been fixed in WebKit as well.
