### ISSUE TITLE
SVG \not\subset or \not\supset error!

### ISSUE THREAD

**Issue by itexsolution** [mathjax/MathJax#2504]
When outputting SVG in v3, `\not\subset` or `\not\supset` is not displayed.
please check.

Thank you.

**Comment by dpvc** [comment]
This turns out to be the same issue as #2402, and the work-around listed there should resolve the problem.  It will be fixed in the next release.

**Comment by itexsolution** [comment]
Thank you for answer

**Comment by dpvc** [comment]
Fixed in v3.1 released today.
