### ISSUE TITLE
\boldsymbol in macro fails to render correctly on first appearance

### ISSUE THREAD

**Issue by MichaelAllenWarner** [mathjax/MathJax#2511]
### Issue Summary

After the most recent MathJax update, it seems that a macro that has `\boldsymbol` followed by a symbol (like `\boldsymbol \nabla`) renders fine _except_ on its first appearance in the page, which instead gets rendered as the literal letters "boldsymbol" followed by the symbol. I'm using the tex-chtml component (https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js), and it happens in every browser I try after yesterday's update.

### Steps to Reproduce:

1. Have the config like this:
```javascript
window.MathJax = {
  tex: {
    macros: {
      del: '\\boldsymbol \\nabla'
    }
  }
};
```
2. Use the tex-chtml component like this:
```javascript
<script type="text/javascript" id="MathJax-script" defer
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
</script>
```
3. Include the `del` macro in equations on the page.
4. On its first appearance in the page (can be either inline-math or display-math), the macro gets rendered like this:

![Screen Shot 2020-08-26 at 9 53 56 AM](https://user-images.githubusercontent.com/44578578/91312357-245c1280-e782-11ea-8f58-a0c2387d0111.png)

(and you can see it's rendered fine on the right side of the equation).

I can avoid the problem on my end by using `'\\boldsymbol{\\nabla}'` instead of `'\\boldsymbol \\nabla'` in the macro, but this does look like a new bug.

### Technical details:

* MathJax Version: 3.1.0
* Client OS: Mac OS X 10.15.5
* Browser: (all browsers)

**Comment by dpvc** [comment]
OK, I'm able to reproduce the issue, and will look into it.  I noticed that if you remove the space, it also works, so it looks like something funny about the handling of the space.  You can also work around it by loading the bold symbol extension explicitly, or using the `tex-chtml-full.js` component.

**Comment by DibasDauliya** [comment]
@dpvc sir?? reply to my issue please? https://github.com/mathjax/MathJax/issues/2510
😢

**Comment by dpvc** [comment]
I've made a pull request that fixes the issue.  It is the space that follows the `\boldymbol` that was causing the problem.  That's why `\boldymbol{\nabla}` worked.  For a temporary work-around, can you remove the space?

**Comment by MichaelAllenWarner** [comment]
Any reason why I shouldn't just keep using `\boldsymbol{\nabla}`?

**Comment by dpvc** [comment]
No, that's fine, too.
