### ISSUE TITLE
AsciiMath doesn't use the correct display style

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#2520]
AsciiMath in v3 doesn't seem to set the inherited properties correctly, as the output is in inline-mode rather than the displaystyle that is the default, despite the fact that there is an `mstyle` that sets the `displaystyle` attribute properly.  Something in the translation from the old internal MathML to the new is going wrong.

**Comment by DanielJGeiger** [comment]
In some sense this bug remains.  I am using MathJax 3.2.0 in Excalidraw PR [#2993](https://github.com/excalidraw/excalidraw/pull/2993).  AsciiMath always renders in display mode, disregarding the `display` option.

I tried changing `displaystyle: true` to `displaystyle: false` in `js/input/asciimath/mathjax2/legacy/jax/input/AsciiMath/config.js`.  Then some scripts in [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node) would respect the `display` option.  But some would not.

@dpvc Any suggestions where to check for the real culprit?  I would gladly submit a bugfix PR once a proper solution is found.

**Comment by dpvc** [comment]
@DanielJGeiger, the following file:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<title>AsciiMath configuration</title>
<script>
MathJax = {
  loader: {load: ['input/asciimath', 'output/chtml']},
  asciimath: {displaystyle: false}
}
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
</head>
<body>

`sum_{n=0}^infty xn`

</body>
</html>
```

produces

<img width="108" alt="asciimath-non-display" src="https://user-images.githubusercontent.com/432782/168649308-0b62078d-c637-407f-b265-4c9cac7c7b7a.png">

for me, while switching `display` to `true` produces

<img width="82" alt="asciimath-display" src="https://user-images.githubusercontent.com/432782/168649464-c94dcb7b-a0ae-4f6c-ba37-0bd19d07ac24.png">

so the `display` option does seem to work for me.

My only suggestion is that the configuration is not being read, which means either it is not being inserted into the page, or it is added after MathJax already starts up, in which case it won't have any effect.  I looked at the PR you linked to, but could not find the configuration at all, nor any calls to MathJax, so I wasn't able to figure out what was wrong.

**Comment by DanielJGeiger** [comment]
> @DanielJGeiger, the following file:

@dpvc Thanks.  That example falls into one of the cases where I have seen the `display` option work.  The script `direct/am2chtml` is an example from [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node) where it does not work, unless I make the change mentioned [earlier](https://github.com/mathjax/MathJax/issues/2520#issuecomment-1126473686).

> My only suggestion is that the configuration is not being read, which means either it is not being inserted into the page, or it is added after MathJax already starts up, in which case it won't have any effect. I looked at the PR you linked to, but could not find the configuration at all, nor any calls to MathJax, so I wasn't able to figure out what was wrong.

My apologies. The relevant file in the linked PR is [src/textlike/math/index.tsx](https://github.com/excalidraw/excalidraw/blob/72295849985d389e0e6c1a6ff65e89209651141c/src/textlike/math/index.tsx), and the relevant method is `loadMathJax`.

**Comment by dpvc** [comment]
OK, I think I was not understanding the issue properly.  It isn't the AsciiMath `displaystyle` configuration option that isn't working, it is the `display` option of the MathDocument's `convert()` method that you are complaining about.

Because AsciiMath doesn't actually have both display and non-display modes (it always uses wither one or the other based on the `displaystyle` document configuration option), the `display` option to `convert()` has no effect for AsciiMath.  You are correct in pointing that out.

It is possible, however, to switch the global mode in the AsciiMath input jax using

``` javascript
MathJax.InputJax.AsciiMath.AM.Augment({displaystyle: false});
```

(or `true`).  so you could modify [this line](https://github.com/excalidraw/excalidraw/blob/72295849985d389e0e6c1a6ff65e89209651141c/src/textlike/math/index.tsx#L364) to include that.  Or perhaps better would be to subclass AsciiMath and insert it there.  Something like

``` javascript
class MyAsciiMath<N, T, D> extends AsciiMath<N, T, D> {
  public compile(math: MathItem<N, T, D>, document: MathDocument<N, T, D>) {
    MathJax.InputJax.AsciiMath.AM.Augment({displaystyle: math.display});
    return super.Compile(math, document);
  }
}
```

so that `convert()` will do this automatically based on the `display` option.
