### ISSUE TITLE
Assistive mml requires a large amount of additional space beyond equation in Chrome

### ISSUE THREAD

**Issue by matthuszagh** [mathjax/MathJax#2521]
The following html file demonstrates the issue:
```html
<script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/mathjax@3.1/es5/tex-mml-chtml.js?config=MML_HTMLorMML">
</script>
<mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" role="presentation" tabindex="0" ctxtmenu_counter="5" style="font-size: 103.7%; position: relative;"><mjx-math id="S0.Ex1.m2.1" class="ltx_Math MJX-TEX" aria-hidden="true"><mjx-semantics id="S0.Ex1.m2.1a"><mjx-mrow id="S0.Ex1.m2.1.4" xref="S0.Ex1.m2.1.4.2.cmml"><mjx-mrow id="S0.Ex1.m2.1.4.2" xref="S0.Ex1.m2.1.4.2.cmml"><mjx-mi class="mjx-n" id="S0.Ex1.m2.1.4.2.1" xref="S0.Ex1.m2.1.4.2.1.cmml"></mjx-mi><mjx-mo class="mjx-n" space="4" id="S0.Ex1.m2.1.1" xref="S0.Ex1.m2.1.1.cmml"><mjx-c class="mjx-c3D"></mjx-c></mjx-mo><mjx-mstyle space="4" id="S0.Ex1.m2.1.2" xref="S0.Ex1.m2.1.2.cmml"><mjx-mfrac id="S0.Ex1.m2.1.2a" xref="S0.Ex1.m2.1.2.cmml"><mjx-frac type="d"><mjx-num><mjx-nstrut type="d"></mjx-nstrut><mjx-mrow id="S0.Ex1.m2.1.2.2" xref="S0.Ex1.m2.1.2.2.cmml"><mjx-mi class="mjx-n" id="S0.Ex1.m2.1.2.2.1" xref="S0.Ex1.m2.1.2.2.1.cmml"><mjx-c class="mjx-c394"></mjx-c></mjx-mi><mjx-mo class="mjx-n" id="S0.Ex1.m2.1.2.2.5" xref="S0.Ex1.m2.1.2.2.5.cmml"><mjx-c class="mjx-c2062"></mjx-c></mjx-mo><mjx-mi class="mjx-i" id="S0.Ex1.m2.1.2.2.2" xref="S0.Ex1.m2.1.2.2.2.cmml"><mjx-c class="mjx-c1D453 TEX-I"></mjx-c></mjx-mi><mjx-mo class="mjx-n" id="S0.Ex1.m2.1.2.2.5a" xref="S0.Ex1.m2.1.2.2.5.cmml"><mjx-c class="mjx-c2062"></mjx-c></mjx-mo><mjx-msub id="S0.Ex1.m2.1.2.2.6" xref="S0.Ex1.m2.1.2.2.6.cmml"><mjx-mi class="mjx-i" id="S0.Ex1.m2.1.2.2.3" xref="S0.Ex1.m2.1.2.2.3.cmml" noic="true"><mjx-c class="mjx-c1D461 TEX-I"></mjx-c></mjx-mi><mjx-script style="vertical-align: -0.15em;"><mjx-mi class="mjx-n" size="s" id="S0.Ex1.m2.1.2.2.4.1" xref="S0.Ex1.m2.1.2.2.4.1.cmml"><mjx-c class="mjx-c1D45F TEX-I"></mjx-c><mjx-c class="mjx-c1D44E TEX-I"></mjx-c><mjx-c class="mjx-c1D45A TEX-I"></mjx-c><mjx-c class="mjx-c1D45D TEX-I"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow></mjx-num><mjx-dbox><mjx-dtable><mjx-line type="d"></mjx-line><mjx-row><mjx-den><mjx-dstrut type="d"></mjx-dstrut><mjx-msub id="S0.Ex1.m2.1.2.3" xref="S0.Ex1.m2.1.2.3.cmml"><mjx-mi class="mjx-i" id="S0.Ex1.m2.1.2.3.1" xref="S0.Ex1.m2.1.2.3.1.cmml" noic="true"><mjx-c class="mjx-c1D453 TEX-I"></mjx-c></mjx-mi><mjx-script style="vertical-align: -0.15em;"><mjx-mi class="mjx-n" size="s" id="S0.Ex1.m2.1.2.3.2.1" xref="S0.Ex1.m2.1.2.3.2.1.cmml"><mjx-c class="mjx-c1D45F TEX-I"></mjx-c><mjx-c class="mjx-c1D44E TEX-I"></mjx-c><mjx-c class="mjx-c1D45A TEX-I"></mjx-c><mjx-c class="mjx-c1D45D TEX-I"></mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-den></mjx-row></mjx-dtable></mjx-dbox></mjx-frac></mjx-mfrac></mjx-mstyle></mjx-mrow><mjx-mo class="mjx-n" id="S0.Ex1.m2.1.3" xref="S0.Ex1.m2.1.4.2.cmml"><mjx-c class="mjx-c2C"></mjx-c></mjx-mo></mjx-mrow></mjx-semantics></mjx-math><mjx-assistive-mml role="presentation" unselectable="on" display="inline"><math xmlns="http://www.w3.org/1998/Math/MathML" alttext="\displaystyle=\frac{\Delta ft_{\mathit{ramp}}}{f_{\mathit{ramp}}}," display="inline" class="ltx_Math"><semantics><mrow xref="S0.Ex1.m2.1.4.2.cmml"><mrow xref="S0.Ex1.m2.1.4.2.cmml"><mi xref="S0.Ex1.m2.1.4.2.1.cmml"></mi><mo xref="S0.Ex1.m2.1.1.cmml">=</mo><mstyle displaystyle="true" xref="S0.Ex1.m2.1.2.cmml"><mfrac xref="S0.Ex1.m2.1.2.cmml"><mrow xref="S0.Ex1.m2.1.2.2.cmml"><mi mathvariant="normal" xref="S0.Ex1.m2.1.2.2.1.cmml">Δ</mi><mo xref="S0.Ex1.m2.1.2.2.5.cmml">⁢</mo><mi xref="S0.Ex1.m2.1.2.2.2.cmml">f</mi><mo xref="S0.Ex1.m2.1.2.2.5.cmml">⁢</mo><msub xref="S0.Ex1.m2.1.2.2.6.cmml"><mi xref="S0.Ex1.m2.1.2.2.3.cmml">t</mi><mi xref="S0.Ex1.m2.1.2.2.4.1.cmml">𝑟𝑎𝑚𝑝</mi></msub></mrow><msub xref="S0.Ex1.m2.1.2.3.cmml"><mi xref="S0.Ex1.m2.1.2.3.1.cmml">f</mi><mi xref="S0.Ex1.m2.1.2.3.2.1.cmml">𝑟𝑎𝑚𝑝</mi></msub></mfrac></mstyle></mrow><mo xref="S0.Ex1.m2.1.4.2.cmml">,</mo></mrow><annotation-xml encoding="MathML-Content"><apply id="S0.Ex1.m2.1.4.2.cmml" xref="S0.Ex1.m2.1.4"><eq id="S0.Ex1.m2.1.1.cmml" xref="S0.Ex1.m2.1.1"></eq><csymbol cd="latexml" id="S0.Ex1.m2.1.4.2.1.cmml" xref="S0.Ex1.m2.1.4.2.1">absent</csymbol><apply id="S0.Ex1.m2.1.2.cmml" xref="S0.Ex1.m2.1.2"><divide id="S0.Ex1.m2.1.2.1.cmml" xref="S0.Ex1.m2.1.2"></divide><apply id="S0.Ex1.m2.1.2.2.cmml" xref="S0.Ex1.m2.1.2.2"><times id="S0.Ex1.m2.1.2.2.5.cmml" xref="S0.Ex1.m2.1.2.2.5"></times><ci id="S0.Ex1.m2.1.2.2.1.cmml" xref="S0.Ex1.m2.1.2.2.1">Δ</ci><ci id="S0.Ex1.m2.1.2.2.2.cmml" xref="S0.Ex1.m2.1.2.2.2">𝑓</ci><apply id="S0.Ex1.m2.1.2.2.6.cmml" xref="S0.Ex1.m2.1.2.2.6"><csymbol cd="ambiguous" id="S0.Ex1.m2.1.2.2.6.1.cmml" xref="S0.Ex1.m2.1.2.2.6">subscript</csymbol><ci id="S0.Ex1.m2.1.2.2.3.cmml" xref="S0.Ex1.m2.1.2.2.3">𝑡</ci><ci id="S0.Ex1.m2.1.2.2.4.1.cmml" xref="S0.Ex1.m2.1.2.2.4.1">𝑟𝑎𝑚𝑝</ci></apply></apply><apply id="S0.Ex1.m2.1.2.3.cmml" xref="S0.Ex1.m2.1.2.3"><csymbol cd="ambiguous" id="S0.Ex1.m2.1.2.3.3.cmml" xref="S0.Ex1.m2.1.2.3">subscript</csymbol><ci id="S0.Ex1.m2.1.2.3.1.cmml" xref="S0.Ex1.m2.1.2.3.1">𝑓</ci><ci id="S0.Ex1.m2.1.2.3.2.1.cmml" xref="S0.Ex1.m2.1.2.3.2.1">𝑟𝑎𝑚𝑝</ci></apply></apply></apply></annotation-xml><annotation encoding="application/x-tex">\displaystyle=\frac{\Delta ft_{\mathit{ramp}}}{f_{\mathit{ramp}}},</annotation></semantics></math></mjx-assistive-mml></mjx-container>
```

When I open this in Chrome and inspect the html, I see an element a lot of additional space to the space required by the actual equation. I've captured this in the following screenshot, where the green line shows the issue:

![issue](https://user-images.githubusercontent.com/7377393/92218848-93a2c800-ee4e-11ea-974c-3625d8eaa3d7.png)

When I encountered this on my webpage, it caused large, unnecessary horizontal scroll bars to appear on the page and in containers. If I disable assistive mml with:
```html
<script>
  MathJax = {
      options: {
          renderActions: {
              assistiveMml: []
          }
      }
  };
</script>
```
the issue disappears.

I also tested this with Firefox and did not encounter an issue, regardless of whether assistive mml was enabled or not.

I've tried to provide a sufficient example for debugging, but please let me know if you're missing information and I'll do my best to include it. Thanks!

**Comment by dpvc** [comment]
The `mjx-assistive-mml` node has CSS that sets its clip region to a 1px square, so it should not affect the layout, but perhaps you have other CSS that is interfering with it.

In any case, if you use

``` html
<style>
mjx-container {
  display: inline-block;
}
mjx-assistive-mml {
  right: 0px;
  bottom: 0px;
}
</style>
```

that should take care of it (without having to disable the assistive MathML entirely).

Also, FYI, you don't need `?config=MML_HTMLorMML` on your script that loads MathJax.  That is a version 2 technique, and it does nothing in version 3 of MathJax.

**Comment by matthuszagh** [comment]
Thanks for the prompt response @dpvc! That css did the trick (and thanks for mentioning the unnecessary v2 part). I imagine you're right and I'm unintentionally injecting some css that's causing issues. I'm closing this for now. If I find an issue related to mathjax I'll reopen.

**Comment by tannerdolby** [comment]
@dpvc The `mjx-assistive-mml` element still occupies more height than its content on Chrome (Version 125.0.6422.142 )

<img width="1275" alt="Screen Shot 2024-06-30 at 10 29 06 PM" src="https://github.com/mathjax/MathJax/assets/48612525/4ccf09d1-6207-4a24-a424-27b25c327c87">

-----

I don't have any conflicting or additional styles outside of things coming from MathJax like `mjx-assistive-mml` etc. I saw your suggestion above to update its absolute positioning to `bottom: 0, right: 0` which does the trick but I'm curious what your thoughts are on updating the elements styling here in MathJax and defining a `height: 100%` for mjx-assistive-mml elements to resolve this issue? I understand mjx-assistive-mml is absolutely positioned relative to the `mjx-container` so setting `bottom: 0` will do the trick but it seems like setting a `height` for that element makes sense to ensure it only occupies the height of its content.

**Comment by dpvc** [comment]
@tannerdolby, you don't need `height: 100%` if you have `bottom: 0`, as they both do the same thing.  Note that `height: 100%` doesn't ensure it occupies the height of its *content*, but the height of its *container*, just as `top: 0; bottom: 0` does.

**Comment by tannerdolby** [comment]
@dpvc thanks for the clarification around occupying the height of the container vs its content. In this case, the height of the container seems to equal the height of its content. Would you be open to adding `bottom: 0` to the elements styling here in MathJax so folks don't have to continue adding extra styles?

**Comment by dpvc** [comment]
> Would you be open to adding `bottom: 0` to the elements styling here in MathJax so folks don't have to continue adding extra styles to account for this?

It is already in the v4.0 codebase (currently in beta release), so will be in v4.0 when the official release is made.
