### ISSUE TITLE
Is there a non minified version of mathJax ?

### ISSUE THREAD

**Issue by Esporia** [mathjax/MathJax#2522]
I ask that, because I want to see if it's possible to create a public latex to svg convertor package over this one without webworker, or webviewer for react ...

**Comment by dpvc** [comment]
The source code for MathJax is available in the [MathJax-src](https://github.com/mathjax/MathJax-src) repository, and via the `mathjax-full` package in npm.  The MathJax components are all minified, but you could use the [direct](https://github.com/mathjax/MathJax-demos-node/tree/master/direct) method of accessing the MathJax modules to make a custom build of MathJax from the source modules.  See, for instance [this example](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-build/custom-mathjax.js) from the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web/) repository for an example of a web-based custom build of MathJax that doesn't use Mathjax components but calls MathJax directly.  It generates speech output, but you could similarly generate sag output (you would need to include the SVG output jax to do it).  See the [tex2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg) node example for another tarting point.  You would remove all the `yargs` stuff (for command-line parsing), but the rest is pretty close to what you need.

**Comment by pkra** [comment]
> I ask that, because I want to see if it's possible to create a public latex to svg convertor package over this one without webworker, or webviewer for react ...

https://github.com/railsjack/react-native-mathjax-svg might be of interest.

**Comment by Esporia** [comment]
@pkra Yeah, I made one that is similar to your suggested package (``react-native-mathjax-svg``).

I made a local npm module (just for me) called ``tex to svg without webworker`` with my stuff. 

I have one question : if I publish my personal local package through NPM, can I cover my wrapper with a MIT licence or It must be covered with a Apache license ?

**Comment by dpvc** [comment]
> if I publish my personal local package through NPM, can I cover my wrapper with a MIT licence or It must be covered with a Apache license ?

Both the MIT and Apache2 licenses are pretty open, and are not viral.  My understanding is that they are "compatible" in the sense that you can use one in a product licensed under the other.  If you are distributing only your wrapper and not modified MathJax code, there should be no problem, especially if you are just including MathJax via a dependency in the `package.json` file, that is allowed by Apache2.
