### ISSUE TITLE
Wrapping with `\text{}` creates strange overlapped output with `tex-svg-full`

### ISSUE THREAD

**Issue by zmoon** [mathjax/MathJax#2524]
### Issue Summary

Wrapping with `\text{}` creates strange overlapped output with `tex-svg-full` but not `tex-svg`.

Example:
```
\text{
This is an equation: $y = m\,x + b$; another: $e^{i \pi} = -1$. These are literal dollar signs: \$\$
}
```

With `tex-svg-full` (see full code below):
![mathjax3_test_bad](https://user-images.githubusercontent.com/15079414/92316761-72fd7e00-efc6-11ea-9acb-5966ca12b4e1.png)

With `tex-svg`:
![mathjax3_test_good](https://user-images.githubusercontent.com/15079414/92316763-798bf580-efc6-11ea-823a-eca379acd912.png)

### Technical details:

* MathJax Version: 3.0.5 (`MathJax.version` in console) but 3.1.0 in the "About MathJax" right-click menu
* Client OS: Windows 10
* Browser: Firefox 80.0

### Supporting information:

<details>
<summary>code</summary>

```html
<!DOCTYPE html>
<html>
<head>
<title>MathJax TeX Test Page</title>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js">
</script>
</head>
<body>

$$
\text{
This is an equation: $y = m\,x + b$; another: $e^{i \pi} = -1$. These are literal dollar signs: \$\$
}
$$

</body>
</html>
```

</details>

**Comment by dpvc** [comment]
This is an error with the `textmacros` extension, which is included in the `tex-svg-full` component, but not `tex-svg` the component.  Apparently there is a bug with it in the SVG output that I'm looking into.  For now, you should be able to disable it using

``` html
<script>
MathJax = {
  tex: {
    packages: {'[-]': ['textmacros']}
  }
}
```

**Comment by edemaine** [comment]
In case you need some more breaking tests for `textmacros`, I found the following, testing [on the demo site](https://www.mathjax.org/#demo):

```latex
$$\require{textmacros}hello + \text{\textbf{hello}}$$
```
renders correctly as:
![image](https://user-images.githubusercontent.com/2218736/93023894-4d710580-f5c0-11ea-9476-d19a9fe938da.png)

```latex
$$\require{textmacros}hello + \text{hello}$$
```
renders correctly as:
![image](https://user-images.githubusercontent.com/2218736/93023903-611c6c00-f5c0-11ea-9181-2f5fdf944f10.png)

```latex
$$\require{textmacros}hello + \text{hello \textbf{hello}}$$
```
renders **incorrectly** as:

![image](https://user-images.githubusercontent.com/2218736/93023884-287c9280-f5c0-11ea-8587-5e3c78b53c79.png)

**Comment by dpvc** [comment]
Thanks.  I suspect it is related to the same issue, which must not be completely resolved.  Sigh.
