### ISSUE TITLE
\text fails with grave, acute accents

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2526]
### Issue Summary

`\text` fails with grave and acute accents.

The other accents work fine.

### Technical details:

Current MathJax 3, Firefox

### Supporting information:

```
<!DOCTYPE html>
<html lang="en-US">

<head>

<meta charset="UTF-8" />

<script>
MathJax = {
    loader: {
         load: ['[tex]/textmacros'],
    },
    tex: {
         packages: {'[+]': ['textmacros']},
    }
}
</script>

<script
         id="MathJax-script"
         src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
></script>

</head>


<body>



<p>
acute accent \(abc + \text {t\’{e}xt}\)
</p>

<p>
grave accent \(abc + \text {t\‘{e}xt}\)
</p>

</body>
</html>
```

**Comment by dpvc** [comment]
The problem, here, is that you aren't actually using the correct macros.  The macros are `\'` and `` \` ``, using the ASCII characters U+0027 and U+0060, whereas your examples have substituted "smart quotes", as `\’` and `\‘`, using U+2019 and U+2018.  MathJax is correctly reporting that these are undefined.  It may be that your content-management system is substituting the smart quotes automatically.

It would make sense to define these as equivalent to the correct macros, for situations where that is the case.

**Comment by bdtc** [comment]
In the meantime, I've now made the LaTeX Lwarp package to use HTML entities, avoiding the font/pdftotext issue with quotes.  Thanks.
