### ISSUE TITLE
a11y extension, SVG output: flame effect is on by default and gets darker after hitting leaf/root

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2529]
When navigation an expression with the accessibility explorer, the background color (flaming effect) is active (despite settings ben off) and gets darker when hitting the down arrow key on a leaf node or the up arrow key on the root (of the semantic tree). 

This only seems to affect the SVG output.

**Comment by pkra** [comment]
I accidentally hit "post" -- I've edited the title and OP content.

**Comment by pkra** [comment]
I guess another part is that the flame effect is active even though its disabld in the context menu.

**Comment by pkra** [comment]
Yet another edit -- going "up" on the root also darkens the flame effect.

**Comment by dpvc** [comment]
It looks like the rectangles used to form the transparent background images are not being removed when you move to the next location, so they "pile up" causing them to get darker, and giving something similar to the flame effect.

**Comment by pkra** [comment]
> It looks like the rectangles used to form the transparent background images are not being removed when you move to the next location, so they "pile up" causing them to get darker, and giving something similar to the flame effect.

Ah, much more subtle!

**Comment by dpvc** [comment]
OK, I tracked this down.  It is in SRE's highlighter SVG for v3, which is a subclass of the SVG highlighter.  The latter overrides the `ssetHighlighted()` method, and that method doesn't mark the node as highlighted properly.  I'll file an upstream issue, but for now, you can use

<script>
MathJax = {
  loader: {
    'a11y/explorer': {
      ready() {
        sre.SvgV3Highlighter.prototype.setHighlighted = sre.AbstractHighlighter.prototype.setHighlighted;
      }
    }
  }
}
</script>

to work around the issue.

**Comment by zorkow** [comment]
This is a regression from May when I made SRE 3.x backwards compatible with v2.7.y 
See the corresponding SRE issue.

**Comment by dpvc** [comment]
I believe this has been fixed upstream.
