### ISSUE TITLE
trigonometric functions asciimath to mathml incorrect

### ISSUE THREAD

**Issue by mt4c** [mathjax/MathJax#2534]
### Issue Summary

asciimath `cos 2A` render as
```
<mrow>
  <mi>cos</mi>
  <mn>2</mn>
</mrow>
<mi>A</mi>
```
the "cos2" is wrapped and the A is outside.

### Steps to Reproduce:

render `cos 2A` or `sin 2pi`

### Technical details:

* MathJax Version: latest
* Client OS: win10
* Browser: latest chrome

**Comment by dpvc** [comment]
This is how AsciiMath works, yes.  If you want to have the cosine of 2A you need to use parentheses:  `cos(2A)`.  AsciiMath is not an algebra system, and doesn't really do precedence-based expression parsing, so when a trig function is used without parentheses, the argument is taken to be just the first symbol that follows it.  This can lead to poor results  (consider what happens for `sin -x`, for example).

MathJax incorporates the AsciiMath parser pretty much verbatim, so we don't control the syntax that it defines.  If you want to suggest a change in how AsciiMath parses an expression, you will need to do so using the [AsciiMath issue tracker](https://github.com/asciimath/asciimathml/issues).

**Comment by mt4c** [comment]
Thanks for the reply. I found a function to auto add the parentheses and it works.
