### ISSUE TITLE
Additional \left, \ right delimiters from unicode-math

### ISSUE THREAD

**Issue by bdtc** [mathjax/MathJax#2535]
The LaTeX `unicode-math` package has more than 2000 macros, most of which can be defined as needed using `\unicode`.  (`texdoc unimath-symbols` for the big list.)

The list includes additiional opening and closing delimiters, such as `\lBrack`.  These can be defined with `\newcommand`, but they are not recognized by `\left` and `\right`.

It would be nice if the additional delimiters from `unimath-symbols` could be added to the list of delimiters in the MathJax source.  It looks like it may be as simple as just adding them to the list.  There are a bit fewer than 60 such macros, each of which has its own Unicode entry.

As an alternative, is there a way to easily add them from a custom script?

**Comment by dpvc** [comment]
You can add a delimiter using the following configuration:

``` javascript
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      const {DelimiterMap} = MathJax._.input.tex.SymbolMap;
      const {Symbol} = MathJax._.input.tex.Symbol;
      const {MapHandler} = MathJax._.input.tex.MapHandler;
      const delimiter = MapHandler.getMap('delimiter');
      delimiter.add('\\lBrack', new Symbol('\\lBrack', '\u27E6'));
    }
  }
}
```

but the MathJax TeX fonts don't include this character, or the glyphs needed to make a multi-character assembly for stretchy version of this character.  So it will allow MathJax to parse the LaTeX that includes these, but won't produce stretched versions of the delimiters.

Once the STIX2 support is ready, you would be able to get stretchy versions of these character using that font.

**Comment by bdtc** [comment]
Works great.  I've used this to add \left and \right support to a number of delimiters for unicode-math, newpxmath, etc. for the lwarp package.

**Comment by bluelightning32** [comment]
I ran into the same problem. Thanks for the example script to add new delimiters!

I agree that the new double bracket delimiters do not stretch in v3.2.2. However, they work great in v4.0.0-alpha. It looks like that stretchy font support was added.

I'm using MathJax through Sphinx. It's a little tricky to set a MathJax startup function in Sphinx. In case anyone else needs it, this is what I put in `conf.py`.
```
macros = { }
pairedDelimiters = { }

# A MathJax start up function is necessary to register more delimiters (from
# https://github.com/mathjax/MathJax/issues/2535). However, Sphinx doesn't
# support including functions in mathjax3_config. So instead, encode the
# MathJax options in a small Javascript script, and inline that script on every
# page. This is based on
# https://github.com/cpitclaudel/alectryon/blob/master/recipes/sphinx/conf.py.

mathjax_config_script = r'''
window.MathJax = {
    startup: {
        ready() {
            MathJax.startup.defaultReady();
            const {DelimiterMap} = MathJax._.input.tex.SymbolMap;
            const {Symbol} = MathJax._.input.tex.Symbol;
            const {MapHandler} = MathJax._.input.tex.MapHandler;
            const delimiter = MapHandler.getMap('delimiter');
            delimiter.add('\\lBrack', new Symbol('\\lBrack', '\u27E6'));
            delimiter.add('\\rBrack', new Symbol('\\rBrack', '\u27E7'));
        },
    },
    loader: {load: ['[tex]/mathtools']},
    tex: {
        packages: {'[+]': ['mathtools'] },
        macros: %s,
        mathtools: {
            pairedDelimiters: %s,
        },
    },
}
''' % (json.dumps(macros), json.dumps(pairedDelimiters))

mathjax_options = { 'priority': 1000 }

html_js_files = [
    (
        None, {
            'body': mathjax_config_script,
            'priority': 1000
        }
    )
]
```
