### ISSUE TITLE
Some anomaly in 3.1.1

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2538]
### Issue Summary

Some macros fail in MathJax 3.1.1. Please compare

[https://math.tecnico.ulisboa.pt/test.php](https://math.tecnico.ulisboa.pt/test.php) (MathJax 3.1.0)

[https://math.tecnico.ulisboa.pt/test2.php](https://math.tecnico.ulisboa.pt/test2.php) (MathJax 3.1.1)

**Comment by dpvc** [comment]
Oh dear!  This is a serious regression.  I'm pushing v3.1.2 as we speak to fix it.  Thank you for reporting the problem so quickly.

**Comment by dpvc** [comment]
Version 3.1.2 has been published to npm, so should be hitting the CDNs soon.
