### ISSUE TITLE
Add an option to disable @font-face generation to allow custom font loading strategies when using chtml output

### ISSUE THREAD

**Issue by Mogztter** [mathjax/MathJax#2539]
**Is your feature request related to a problem? Please describe.**

MathJax automatically generates `@font-face` CSS rules to load fonts from a URL. Please note that this URL can be configured using:

```js
MathJax = {
  chtml: {
    fontURL: 'path/to/fonts'
  }
}
```

However, it's not possible to disable the `@font-face` generation, meaning that MathJax will always try to load the fonts from a URL.

This can be problematic when the fonts cannot be loaded from a URL, for instance, in a restricted/sandboxed environment.

**Describe the solution you'd like**

I think we should provide an option to disable the `@font-face` generation and let the user decide how the fonts should be loaded.

To avoid adding an additional option, we could use the value `false` to indicate that we don't want to load the font from an URL:

```js
MathJax = {
  chtml: {
    fontURL: false // disable fonts loading from an URL
  }
}
```

**Describe alternatives you've considered**

Another possible solution would be to inline the fonts using base64 in the CSS (since we are using Webpack) but some users might prefer to load the fonts from an URL... so it's probably better to add an option.

**Additional context**

![404fonts](https://user-images.githubusercontent.com/333276/93100884-f182ab80-f6a9-11ea-8e9e-d4dd31bc0be7.png)

**Comment by Mogztter** [comment]
@dpvc any opinion on this proposal?

**Comment by dpvc** [comment]
For others, see the discussion at mathjax/MathJax-src#554 for the resolution.
