### ISSUE TITLE
Render wrong When my tex is full of space(\; \: \,  etc.)

### ISSUE THREAD

**Issue by qq240814476** [mathjax/MathJax#2545]
code: 
```
Mathjax.tex2svg('\\;\\;\\;');
```
then I got three <g data-mml-node="mstyle"><g data-mml-node="mspace"></g></g>
I call them a,b,c
a.getBoundingClientRect().x = 0px; // this right
b.getBoundingClientRect().x = 277px; // ??? space has 277px ?

But when I change my tex
```
Mathjax.tex2svg('\\;\\;1') // add 1
```
a.getBoundingClientRect().x = 0px; // this right
b.getBoundingClientRect().x = 7px; // good job, that's right

Then I test all space tex have this problem:
```
\,
\:
\;
\quad
\qquad
\!
```

I find <g> node has translate(x, y) attribute. How I add a special hack to handle this problem?

**Comment by dpvc** [comment]
> then I got three 
I call them a,b,c

I don't know what this means.  Three what?  `MathJax.tex2svg()` will return a single DOM node, not three nodes, and it will be a `mix-container` node.  That node will contain two children (the SVG element, and a MathML element that is visually hidden but available for users of assistive technology), so I'm not sure what your `a`, `b`, and `c` are.

In MathJax's SVG output spacing is handled through translations, not via an explicit node.  If you can explain what your `a`, `b` and `c` are, perhaps I can help.  If you could provide a minimal page that illustrates what you are doing, that would be even better.

**Comment by qq240814476** [comment]
> > then I got three
> > I call them a,b,c
> 
> I don't know what this means. Three what? `MathJax.tex2svg()` will return a single DOM node, not three nodes, and it will be a `mix-container` node. That node will contain two children (the SVG element, and a MathML element that is visually hidden but available for users of assistive technology), so I'm not sure what your `a`, `b`, and `c` are.
> 
> In MathJax's SVG output spacing is handled through translations, not via an explicit node. If you can explain what your `a`, `b` and `c` are, perhaps I can help. If you could provide a minimal page that illustrates what you are doing, that would be even better.

Oh, I mean  I got three  space
