### ISSUE TITLE
 Different rendering with renewcommand in config file than directly used

### ISSUE THREAD

**Issue by Joalland** [mathjax/MathJax#2546]
I like my vector to be in bold. I ussualy redefine the latex \vec{} command :

If i put 
```
$\renewcommand\vec[1]{\mathbf{#1}}\vec{AA'}$
```
inside a dokuwiki page i get :
![image](https://user-images.githubusercontent.com/47032753/94418235-66adb080-0181-11eb-99b8-2bf96f603920.png)

If I put in on the mathax config file above : 
```
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\(","\\)"] ],
        displayMath: [ ["$$","$$"], ["\\[","\\]"] ],
        processEscapes: true
    },
    TeX: {
        Macros: {
          RR: '{\\bf R}',
          bold: ['{\\bf #1}',1],
          vec: ['{\\mathbf #1}',1]
        }
    }
});
```
I get : 
![image](https://user-images.githubusercontent.com/47032753/94418487-c310d000-0181-11eb-828a-14d9b53b1ed5.png)

Is this a bug or I'm missing something in the matjax configuration file ?

Thanks

**Comment by pkra** [comment]
The two definitions do not match - the config is missing the braces around the argument. Try

```
...
 vec: ['\\mathbf {#1}',1]
...
```

**Comment by Joalland** [comment]
Thanks for your answer. It works as expected. Sorry for this false issue.
