### ISSUE TITLE
Problems drawing left/right arrow in mover

### ISSUE THREAD

**Issue by NSoiffer** [mathjax/MathJax#2547]
### Issue Summary

MathJax has some problems with drawing a stretchy arrow as detailed below. The results differ between Chrome and Firefox, but in all cases, the arrow display in an `mover` has problems.

### Steps to Reproduce:

1. View the [codepen I created](https://codepen.io/nms/pen/jOqoVQr)
2. In Firefox, the right arrow is not stretched in normal display -- it is right aligned; the left arrow is left aligned (maybe the horizontal line part isn't visible?). When zoomed, the pieces don't align. The alignment problem might be the same issue reported in #2226. Here is a screen shot:
![image](https://user-images.githubusercontent.com/1545836/94603614-55c97180-024b-11eb-88ac-64e970c5d556.png)
I tried different zoom factors. The alignment problems shows up at 150%, 200%, 300%, but not at 400%.

3. In Chrome, do the same thing. The display is better, but the unzoomed right arrow has different widths for the pieces. In the zoomed case, it is just barely wrong -- an extra pixel is highlighted where the pieces are joined.
![image](https://user-images.githubusercontent.com/1545836/94603676-6d085f00-024b-11eb-8956-d3b71ecae5ff.png)

### Version:
![image](https://user-images.githubusercontent.com/1545836/94603725-814c5c00-024b-11eb-8e64-a67545c018ef.png)

**Comment by dpvc** [comment]
I'm going through back issues, and just saw that I never responded to this.  (I was just starting remote classes, and was swamped at the time.)  I will look into it further.
