### ISSUE TITLE
MathJax.tex2svgPromise cannot be called repeatedly

### ISSUE THREAD

**Issue by Vanessa219** [mathjax/MathJax#2548]
### Steps to Reproduce:

1. run this html and click Render TeX

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width">
  <title>MathJax v3 with interactive TeX input and SVG output</title>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
  <script>
    function convert() {
      //
      //  Get the TeX input
      //
      var input = document.getElementById("input").value.trim();
      //
      //  Disable the display and render buttons until MathJax is done
      //
      var display = document.getElementById("display");
      var button = document.getElementById("render");
      button.disabled = display.disabled = true;
      //
      //  Clear the old output
      //
      output = document.getElementById('output');
      output.innerHTML = '';
      output1 = document.getElementById('output1');
      output1.innerHTML = '';
      //
      //  Reset the tex labels (and automatic equation numbers, though there aren't any here).
      //  Get the conversion options (metrics and display settings)
      //  Convert the input to SVG output and use a promise to wait for it to be ready
      //    (in case an extension needs to be loaded dynamically).
      //
      MathJax.texReset();
      var options = MathJax.getMetricsFor(output);
      options.display = display.checked;
      MathJax.tex2svgPromise(input, options).then(function (node) {
        //
        //  The promise returns the typeset node, which we add to the output
        //  Then update the document to include the adjusted CSS for the
        //    content of the new equation.
        //
        output.appendChild(node);
        MathJax.startup.document.clear();
        MathJax.startup.document.updateDocument();
      }).catch(function (err) {
        //
        //  If there was an error, put the message into the output instead
        //
        output.appendChild(document.createElement('pre')).appendChild(document.createTextNode(err.message));
      }).then(function () {
        //
        //  Error or not, re-enable the display and render buttons
        //
        button.disabled = display.disabled = false;
      });



      MathJax.texReset();
      var options = MathJax.getMetricsFor(output1);
      options.display = display.checked;
      MathJax.tex2svgPromise(document.getElementById("input2").value.trim(), options).then(function (node) {
        //
        //  The promise returns the typeset node, which we add to the output
        //  Then update the document to include the adjusted CSS for the
        //    content of the new equation.
        //
        output1.appendChild(node);
        MathJax.startup.document.clear();
        MathJax.startup.document.updateDocument();
      }).catch(function (err) {
        //
        //  If there was an error, put the message into the output instead
        //
        output.appendChild(document.createElement('pre')).appendChild(document.createTextNode(err.message));
      }).then(function () {
        //
        //  Error or not, re-enable the display and render buttons
        //
        button.disabled = display.disabled = false;
      });
    }
  </script>
  <style>
  #frame {
    max-width: 40em;
    margin: auto;
  }
  #input {
    border: 1px solid grey;
    margin: 0 0 .25em;
    width: 100%;
    font-size: 120%;
    box-sizing: border-box;
  }
  #output {
    font-size: 120%;
    margin-top: .75em;
    border: 1px solid grey;
    padding: .25em;
    min-height: 2em;
  }
  #output > pre {
    margin-left: 5px;
  }
  .left {
    float: left;
  }
  .right {
    float: right;
  }
  </style>
</head>

<body>
<div id="frame">

<h1>MathJax v3: TeX to SVG</h1>

<textarea id="input" rows="15" cols="10">
\left(\boldsymbol{r}^{\prime}\right)^{\mathrm{T}} \cdot \boldsymbol{r}^{\prime}=(\boldsymbol{A} \boldsymbol{r})^{\top}(\boldsymbol{A} \boldsymbol{r})=(\boldsymbol{r})^{\mathrm{T}} \boldsymbol{A}^{\mathrm{T}} \boldsymbol{A} \boldsymbol{r}
</textarea>
<textarea id="input2" rows="15" cols="10">
\boldsymbol{r}\left(x_{1}, x_{2}, x_{3}\right) \rightarrow \boldsymbol{r}^{\prime}\left(x_{1}^{\prime}, x_{2}^{\prime}, x_{3}^{\prime}\right)=\operatorname{Ar}\left(x_{1}, x_{2}, x_{3}\right)
</textarea>
<br />
<div class="left">
<input type="checkbox" id="display" checked onchange="convert()"> <label for="display">Display style</label>
</div>
<div class="right">
<input type="button" value="Render TeX" id="render" onclick="convert()" />
</div>
<br clear="all" />
<div id="output"></div>
<div id="output1"></div>
</div>

</body>

</html>
```

**Comment by josephjohnston** [comment]
I can't solve the problem, but I can reduce it to a problem with autoloading for others to solve.
When using string conversion functions (like `tex2svgPromise`) concurrently on commands from a tex extension not yet loaded, the extension is not properly autoloaded.
Rather than the `boldsymbol` extension, the example below uses the `braket` extension.
As is, it will render (with no errors generated in the process) the text `\ket s` then `\bra r` with the two commands highlighted in red.
Upon uncommenting the explicit loading of the braket extension, it will render the correct form of `\bra{r}` then `\ket{s}`.
```html
<html>
<head>
    <script>
        MathJax = {
            loader: {
                // load: ["[tex]/braket"],
            },
        };
        function convert() {
            MathJax.tex2svgPromise("\\bra{r}").then(function (node) {
                document.body.appendChild(node);
            });
            MathJax.tex2svgPromise("\\ket{s}").then(function (node) {
                document.body.appendChild(node);
            });
        }
    </script>
    <script
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"
        async
    ></script>
</head>
<body>
    <input type="button" value="Render TeX" onclick="convert()" />
</body>
</html>
```
Worth noting:
- In general for two or more concurrent calls, in the erroneous scenario the first input called for rending gets rendered last, the rest preserving the order of the calling. In the case of two inputs as above, this just means they get rendered in the opposite order of calling. Not sure how this relates to the queueing system.
- It's not a problem particular to svg. I see the same with chtml.
- If the two calls cause different extensions to be autoloaded, there is no problem. The problem occurs when both calls cause the same extension to be autoloaded.
- Setting autoload parameters, such as those to autoload the braket extension on the `\bra` and `\ket` commands, doesn't seem to help.
- Chaining the promises, such that the second call in only made once the first is resolved, causes no problems but doesn't allow for concurrency.

It would be a pity if the only way around this is either explicitly loading all extensions that might possibly be needed, or chaining all calls.

**Comment by Vanessa219** [comment]
Thx, I use `window.MathJax.startup.promise` to resole this problem.

**Comment by dpvc** [comment]
@josephjohnston,

Multiple simultaneous calls to `MathJax.typesetPromise()` is not supported, as there are a number of situations where that can go wrong.  You have identified one of the, which is the loading of external components, but there are others as well (e.g., there is global data that can get disrupted if you do this).  

One solution would be to use the `-full` version of the component file that you are loading, so that all the external components are available.  The down side is that that requires a larger download for your readers.

The recommended solution is the one @Vanessa219 has suggested, which is outlined in the [documentation](https://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting) so that your calls to `MathJax.typesetPromise()` are handled sequentially, a required.

**Comment by josephjohnston** [comment]
@dpvc I see. Yes I saw that in the documentation and thought it was particular to `MathJax.typesetPromise()`, but should have guessed it also applies to the string conversion functions (which I used in the example).

**Comment by dpvc** [comment]
Right, sorry, I wrote too quickly and used `typesetPromise()` rather than the calls you were actually making.  You are correct, it applies to all the promise-based calls.

**Comment by qq240814476** [comment]
> @josephjohnston,
> 
> Multiple simultaneous calls to `MathJax.typesetPromise()` is not supported, as there are a number of situations where that can go wrong. You have identified one of the, which is the loading of external components, but there are others as well (e.g., there is global data that can get disrupted if you do this).
> 
> One solution would be to use the `-full` version of the component file that you are loading, so that all the external components are available. The down side is that that requires a larger download for your readers.
> 
> The recommended solution is the one @Vanessa219 has suggested, which is outlined in the [documentation](https://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting) so that your calls to `MathJax.typesetPromise()` are handled sequentially, as required.

Could u provide some example of disrupted global data ? I really use lots of times by this wrong case! so sad~😫

**Comment by dpvc** [comment]
@qq240814476

> Could [yo]u provide some example of disrupted global data ?

Sure.  One issue is if two concurrent `typesetPromise()` calls cause the same extension to be loaded.  In that case, both witll fail to process the autoloader macro properly.  For example

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Promise conflicts</title>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script>
MathJax = {
  startup: {
    pageReady() {
      MathJax.typesetPromise(["#math1"]);
      MathJax.typesetPromise(["#math2"]);
      return MathJax.startup.defaultPageReady();
    }
  }
}
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>

<div id="math1">
\[\bbox[red]{A}\]
</div>
<div id="math2">
\[\bbox[red]{B}\]
</div>

</body>
</html>
```

produces:

<img width="244" alt="promise-bad" src="https://user-images.githubusercontent.com/432782/104929921-89531780-5972-11eb-8e31-1ca87741f757.png">

while the following

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<title>Promise conflicts</title>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script>
MathJax = {
  startup: {
    async pageReady() {
      await MathJax.typesetPromise(["#math1"])
      await MathJax.typesetPromise(["#math2"]);
      return MathJax.startup.defaultPageReady();
    }
  }
}
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>

<div id="math1">
\[\bbox[red]{A}\]
</div>
<div id="math2">
\[\bbox[red]{B}\]
</div>

</body>
</html>
```

produces the expected:

<img width="150" alt="promise-good" src="https://user-images.githubusercontent.com/432782/104930066-a8ea4000-5972-11eb-8ba5-843f0830d4fc.png">

Other issues are also possible.  For example, with automatic equation numbering, if one expression autoload an extension, it could be processed out of order and get the wrong number.

**Comment by qq240814476** [comment]
> @qq240814476
> 
> > Could [yo]u provide some example of disrupted global data ?
> 
> Sure. One issue is if two concurrent `typesetPromise()` calls cause the same extension to be loaded. In that case, both witll fail to process the autoloader macro properly. For example
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <meta charset="UTF-8" />
> <meta http-equiv="X-UA-Compatible" content="IE=edge" />
> <title>Promise conflicts</title>
> <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
> <script>
> MathJax = {
>   startup: {
>     pageReady() {
>       MathJax.typesetPromise(["#math1"]);
>       MathJax.typesetPromise(["#math2"]);
>       return MathJax.startup.defaultPageReady();
>     }
>   }
> }
> </script>
> <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
> </head>
> <body>
> 
> <div id="math1">
> \[\bbox[red]{A}\]
> </div>
> <div id="math2">
> \[\bbox[red]{B}\]
> </div>
> 
> </body>
> </html>
> ```
> 
> produces:
> 
> <img alt="promise-bad" width="244" src="https://user-images.githubusercontent.com/432782/104929921-89531780-5972-11eb-8e31-1ca87741f757.png">
> 
> while the following
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <meta charset="UTF-8" />
> <meta http-equiv="X-UA-Compatible" content="IE=edge" />
> <title>Promise conflicts</title>
> <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
> <script>
> MathJax = {
>   startup: {
>     async pageReady() {
>       await MathJax.typesetPromise(["#math1"])
>       await MathJax.typesetPromise(["#math2"]);
>       return MathJax.startup.defaultPageReady();
>     }
>   }
> }
> </script>
> <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
> </head>
> <body>
> 
> <div id="math1">
> \[\bbox[red]{A}\]
> </div>
> <div id="math2">
> \[\bbox[red]{B}\]
> </div>
> 
> </body>
> </html>
> ```
> 
> produces the expected:
> 
> <img alt="promise-good" width="150" src="https://user-images.githubusercontent.com/432782/104930066-a8ea4000-5972-11eb-8ba5-843f0830d4fc.png">
> 
> Other issues are also possible. For example, with automatic equation numbering, if one expression autoload an extension, it could be processed out of order and get the wrong number.

Very very very thanks for your detailed example, thx again 🤣
