### ISSUE TITLE
\overline in \scriptstyle is not visible when body font is set to Times New Roman

### ISSUE THREAD

**Issue by unageek** [mathjax/MathJax#2549]
### Issue Summary

The overlines of `\scriptstyle \overline{X}` and `\scriptscriptstyle \overline{X}` are not rendered with the following CSS used:

```css
body {
  font-family: 'Times New Roman';
}
```

### Steps to Reproduce:

Please take a look at the JS Bin example:

https://jsbin.com/susazuyaka/edit?html,css,output

Here is a rendering on Edge:

![image](https://user-images.githubusercontent.com/29035331/95100805-6eb2b500-076c-11eb-8a2a-d587bfbf3bb0.png)

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Windows 10 2004
* Browser: Microsoft Edge 85.0.564.68 / Google Chrome 85.0.4183.121

**Comment by dpvc** [comment]
Version 3.2 changes how this is handled, so it should improve the situation for you.  Give it a try and see id the new version helps.

**Comment by unageek** [comment]
I confirmed the issue fixed with MathJax 3.2.0, on Microsoft Edge 91.0.864.64. Thank you!

![image](https://user-images.githubusercontent.com/29035331/124939796-6281be00-e044-11eb-88a6-4ef844be852a.png)

**Comment by dpvc** [comment]
Thanks for the confirmation!
