### ISSUE TITLE
Mangled \divergence and \curl output

### ISSUE THREAD

**Issue by stillyslalom** [mathjax/MathJax#2554]
### Issue Summary

`\divergence` and `\curl` macros from the `physics` package produce mangled output if they're not the first items in a TeX field

### Steps to Reproduce:

1. In a Pluto.jl Markdown environment, enter
```
md"""
``
\curl{u} = 0
``

``
0 = \curl{u}
``

``
\divergence{u} = 0
``

``
0 = \divergence{u}
``

"""
```
2. The following output is produced: 
![image](https://user-images.githubusercontent.com/4324760/95690165-4a772e00-0bdb-11eb-8b60-12cf79dd451f.png)

### Technical details:
* MathJax Version: 3.1.2,  tex-svg-full
* Client OS: Windows 10 insider build 20206.1000
* Browser: Chrome 85.0.4183.121

### Supporting information:

https://gist.github.com/stillyslalom/6968cda032d8ffc25586bc1c008bcdfa

**Comment by zorkow** [comment]
Thanks for reporting this. 
This seems to be a problem with the SVG output jax. The expressions render correctly with CHTML. 
Likewise replacing `\curl` or `\divergence` with their underlying implementation (`\gradientnabla\crossproduct` and `\gradientnabla\vdot`, respectively) works fine. This will of course not give you automatic brackets or parentheses.

**Comment by dpvc** [comment]
I have made a pull request that resolves the issue.
