### ISSUE TITLE
\mathscr{I} renders incorrectly 

### ISSUE THREAD

**Issue by amalikmichael** [mathjax/MathJax#2555]
### Issue Summary

\mathscr{I} renders incorrectly. In fact, \mathscr{I} renders the exact same symbol as \mathscr{J}

### Steps to Reproduce:

1. Reproducible on official live demo: https://www.mathjax.org/#demo
2. Typing \\(\mathscr{IJ}\\) renders the same symbol twice

Same issue with \scr{I}. Same bug occurs on my machine.

### Technical details:

* MathJax Version: 3
* Client OS: Mac OS X 10.15.7
* Browser: Safari 14.0 as well as Chrome 86.0.4240.75

**Comment by zorkow** [comment]
Thanks for finding that.
Script I (unicode 2110) seems to be mapped to script J (unicode 1D4A5).
Branch [issue2555](https://github.com/mathjax/MathJax-src/tree/issue2555) contains a fix for the CHTML renderer.
The SVG renderer contains the wrong [path](https://github.com/mathjax/MathJax-src/blob/fbd71f3f7ca06dc71304e8a2c03f13be233ccac5/ts/output/svg/fonts/tex/normal.ts#L218). @dpvc  can you have a look at that, please?

**Comment by dpvc** [comment]
I've finally had the chance to update the data files for this, and have made a PR for it.
