### ISSUE TITLE
Spaces in subscripts and superscript do not show or are smaller than in Latex

### ISSUE THREAD

**Issue by jano-m** [mathjax/MathJax#2561]
### Issue Summary

Example of Latex code:

```
$a_{a\,b}^{c\,d}a_{a\;b}^{c\;d}$
```

Output in Latex:
![image](https://user-images.githubusercontent.com/266826/97069103-8f5b7700-1582-11eb-9def-060e33ec4660.png)

Output in Mathjax (using tex2svg):
![image](https://user-images.githubusercontent.com/266826/97069117-b0bc6300-1582-11eb-9e55-c1a904abe52f.png)

(Note: also vertical spacing is slightly off when thick space is present in scripts)

* MathJax Version: 3.1.2

**Comment by dpvc** [comment]
I am not able to reproduce your result.  This is what I get:

<img width="86" alt="image" src="https://user-images.githubusercontent.com/432782/97094646-a0f55b00-1624-11eb-91ed-e5e04c25e4ac.png">

What are you using to view the resulting SVG?  Which version of tex2svg are you using (there are several in the [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node) repository).

**Comment by jano-m** [comment]
Apologies. The problem is not related to Mathjax typesetting but to our internal processing before it's sent to Mathjax. I can confirm Mathjax typesets it correctly.

**Comment by dpvc** [comment]
Thanks for the update, and glad you figured out what the issue was.
