### ISSUE TITLE
Equations with Scrollbars and Equation Numbering get out of margin in Mathjax 3

### ISSUE THREAD

**Issue by rafael-fuente** [mathjax/MathJax#2562]
I'm updating a page from Mathjax 2 to Mathjax 3. I found this problem when using the following MathJax 3 settings:

```
<style>
.MathJax {
    padding:0.25em;
    overflow-x:auto;
    overflow-y: hidden;
}
</style>

<script>
MathJax = {
  tex :{
    inlineMath: [ ["$","$"], ["\\(","\\)"] ],
    displayMath: [ ["$$","$$"], ["\\[","\\]"] ],
    tags: 'ams',
  }
};
</script>
<script id="MathJax-script" async
 src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```
![incorrect](https://user-images.githubusercontent.com/37953893/97095518-ac667780-1660-11eb-8c8d-9ef7d98a3929.png)

As you can see the equation (6) doesn't fit correctly in the right margin, while using Mathjax 2 I haven't got this problem with these settings:

```
<style>
.MathJax_Display {
    padding:0.25em;
    overflow-x:auto;
    overflow-y: hidden;
</style>


<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ["$","$"], ["\\(","\\)"] ],
            displayMath: [ ["$$","$$"], ["\\[","\\]"] ],
        },
        TeX: {
            equationNumbers: { autoNumber: "AMS" },
            ]
        }
    });
</script>
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML" type="text/javascript"></script>
```
![correct](https://user-images.githubusercontent.com/37953893/97095684-e173c980-1662-11eb-8cfc-98a662b49d21.png)
As you can see with Mathjax 2 there isn't a problem with the margin of (6)

I also discover that when in Mathjax 3 settings the Equation Numbering is removed by  removing  `tags: 'ams',` the right margin works correctly again, so the problem is about using Scrollbars and Equation Numbering at the same time.

This bug is especially important in the mobile version of the pages with long equations because they go out.

**Comment by dpvc** [comment]
Sorry for the long delay in getting back to you.

You might try adding

```
  max-width: 100%;
```

to the CSS for `.MathJax` and see if that resolves the issue.

**Comment by dpvc** [comment]
Sorry, it turns out that what you need is

``` css
.MathJax {
  min-width: 0 ! important
}
```

**Comment by rafael-fuente** [comment]
> Sorry, it turns out that what you need is
> 
> ```css
> .MathJax {
>   min-width: 0 ! important
> }
> ```

This solution works. Thank you! I had already fixed containing the equations in a header with scrollbars, but of course, your solution is much more simple.

**Comment by dpvc** [comment]
Glad it works for you.  Sorry you had to come up with your own.  Your original message came while I was teaching remotely for the first time, and and zero free minutes until the end of the term.   I have gotten rather behind in responding to issues, and am trying to get caught up.
