### ISSUE TITLE
\underline not work in array environment

### ISSUE THREAD

**Issue by wlianghe00** [mathjax/MathJax#2564]
![image](https://user-images.githubusercontent.com/3353880/97382329-15224e00-1906-11eb-81b9-18a64f9a2aca.png)
~~~tex
$
\text{鄙}\underline{鄙}
 \left\{\begin{array}{l}\text { 越国以 \underline{鄙}远 } \ldots \ldots \ldots \ldots \ldots \\ 
\text { 肉食者\underline{鄙},未能远谋 } \ldots \ldots \ldots \ldots \ldots \ldots \\ 
\text { 蜀之\underline{鄙}有二僧 } \ldots \ldots \ldots \ldots \ldots \\ 
\text { 人贱物亦\underline{鄙},不足迎后人 } \ldots \ldots \ldots \ldots \ldots \end{array}\right. 
$
~~~

https://www.mathjax.org/#demo

**Comment by zorkow** [comment]
The problem is not the array environment, but that you are using `\underline` inside the `\text` macro. 
MathJax currently only supports `\underline` in math mode.

The following would give you what you want:
```LaTeX
$
\text{鄙}\underline{鄙}
 \left\{\begin{array}{l}\text { 越国以 $\underline{鄙}$远 } \ldots \ldots \ldots \ldots \ldots \\ 
\text { 肉食者$\underline{鄙}$,未能远谋 } \ldots \ldots \ldots \ldots \ldots \ldots \\ 
\text { 蜀之$\underline{鄙}$有二僧 } \ldots \ldots \ldots \ldots \ldots \\ 
\text { 人贱物亦$\underline{鄙}$,不足迎后人 } \ldots \ldots \ldots \ldots \ldots \end{array}\right. 
$
```

**Comment by wlianghe00** [comment]
> The problem is not the array environment, but that you are using `\underline` inside the `\text` macro.
> MathJax currently only supports `\underline` in math mode.
> 
> The following would give you what you want:
> 
> ```
> $
> \text{鄙}\underline{鄙}
>  \left\{\begin{array}{l}\text { 越国以 $\underline{鄙}$远 } \ldots \ldots \ldots \ldots \ldots \\ 
> \text { 肉食者$\underline{鄙}$,未能远谋 } \ldots \ldots \ldots \ldots \ldots \ldots \\ 
> \text { 蜀之$\underline{鄙}$有二僧 } \ldots \ldots \ldots \ldots \ldots \\ 
> \text { 人贱物亦$\underline{鄙}$,不足迎后人 } \ldots \ldots \ldots \ldots \ldots \end{array}\right. 
> $
> ```

but it already in math mode at the first?

**Comment by zorkow** [comment]
No, the `\text` macro switches back to text mode. So when using a math macro inside `\text` you need to open another math environment by using math delimiters.
