### ISSUE TITLE
tex-chtml vs tex-chtml-full different math mode behaviour

### ISSUE THREAD

**Issue by jfstephe** [mathjax/MathJax#2566]
### Issue Summary

Excuse my naivety but I'm seeing very different behaviour when using the [demo page](https://mathjax.github.io/MathJax-demos-web/input-tex2chtml.html) when I (slightly) alter it to render the TeX below with either the tex-chtml or the tex-chtml-full versions of MathJax.

```
\begin{cases} { {\textsf{Complicated thing with spaces}}}, &\quad{\text{if }\; {\textsf{No. of catastrophes}}=null}\\{ {\textsf{Underscore_test}}\times{\left(1+ {\textsf{Annual growth (%\$)}}\right)}^{\mathrm{{\textsf{year}}}}\times{\left(1+ {\textsf{Other growth factor}}\right)}^{\mathrm{{\textsf{year}}}}}, &\quad{\text{otherwise}}\end{cases}
```

### Steps to Reproduce:

1. Go to https://jsfiddle.net/j81w3qt9/ (which has the TeX set already)
2. Click 'Render TeX' in the bottom right panel
3. You see an error because there's an '_' in a textsf clause ('Underscore_test')
3. Editing the html in jsfiddle to use tex-chtml instead of tex-chtml-full, running the fiddle and repeating #2 and the error goes away!??

I'm sure there's a good reason for it, but I don't have enough information to know exactly what functionality I'd be losing if I don't use the 'full' version. The documentation suggests that it will load extensions dynamically so perhaps I'm only delaying hitting this error in the future?

It seems that there's different sets of special characters that need to be escaped when using 'textsf' with the different versions.

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Win10
* Browser: Chrome Version 86.0.4240.183 (Official Build) (64-bit)

**Comment by dpvc** [comment]
The reason for this is that the `-full` version includes all the extensions, including the `textmacros` extension.  Normally, the contents of `\text{}` and other text-mode material is not processed further by MathJax (other than any math-mode material that it contains), but the `textmacros` extension enables processing of (some) macros within the text-mode material.  That also enables processing of special characters, like the underscore (which is only allowed in math mode).

You can either use `\_` in place of the underscore, or remove the `textmacros` extension from the TeX packages to use.  To do the latter, use

``` html
<script>
MathJax = {
  tex: {
    packages: {'[-]': ['textmacros']}
  }
}
</script>
```

**Comment by jfstephe** [comment]
Thanks for the reply. It'd be great if the errors had context. How could someone (me next time! ;-)) know that the error was in the textmacros extension?

Is there some way of getting that information easily when debugging?

**Comment by dpvc** [comment]
> It'd be great if the errors had context.

I'm not sure there is a reasonable way to determine that.  The routine that is generating the error message is not part of the `textmacros` extension directly, so one would have to look into the call stack, and I don't see a way to decide which function to claim is the "real" culprit to report.

I have not looked into whether the transpiler `.map` files could be used to make the call stack more meaningful, but you aren't getting the call stack in this case.

On the other hand, if your TeX produces an error that is trapped by the `noerrors`extension, you could either disable that extension to get the actual message, or view the MathML source which includes the error message as an attribute on the `merror` element.  In your case, you would see `'_' allowed only in math mode`, which might be enough to indicate that the error had to do with the text-mode processing, suggesting that `textmacros` could be at fault.
