### ISSUE TITLE
`Copy to Clipboard > Tex commands` doesn't trim newlines

### ISSUE THREAD

**Issue by falsandtru** [mathjax/MathJax#2574]
### Issue Summary

`Show Math As > Tex commands > Copy to Clipboard` trims `\n` but `Copy to Clipboard > Tex commands` doesn't. Both commands should trim `\n`.

### Steps to Reproduce:

```js
      displayMath: [['$$', '$$']],
```

```
$$
E = mc^2
$$
```

1. Right click.
2. Click `Copy to Clipboard > Tex commands`.
3. The copied text has `\n` at the first and the last.

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Win10
* Browser: Chrome 85.0.4183.121

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and in crude them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

`<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.1.2/es5/tex-chtml.min.js" integrity="sha512-OEN4O//oR+jeez1OLySjg7HPftdoSaKHiWukJdbFJOfi2b7W0r0ppziSgVRVNaG37qS1f9SmttcutYgoJ6rwNQ==" crossorigin="anonymous"></script>`

**Comment by dpvc** [comment]
Thanks for the suggestion.  it makes sense to do the trimming for the clipboard.
