### ISSUE TITLE
Disabling initial typesetting

### ISSUE THREAD

**Issue by josephjohnston** [mathjax/MathJax#2575]
I apologize if I missed info on this basic question.
I'm using the combined component file `tex-chtml` and I'd like to avoid an initial typesetting when the page first loads and instead do all typesetting by calling the `tex2chtmlPromise` function.
Simply setting parameters in `MathJax.startup`, such as `typeset=false` or `elements=null` or `document=null`, doesn't help but I'm not sure why.
Setting `typeset=false` worked when I loaded each component separately but I'd like to take your efficiency suggestion in using a combined component file.
Overriding `ready` and not calling `defaultReady` (which queues the initial typesetting) also works but doesn't seem a good idea because it's responsible for initialization.
What are my options?

**Comment by dpvc** [comment]
Setting the `startup.typeset` to `false` works for me.  For example:

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>Skip initial typeset</title>
<script>
MathJax = {
  startup: {
    typeset: false
  }
};
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>

$$ x = y + z $$

</body>
</html>
```

skips the initial typesetting pass.

Without a complete (non)working example, it is hard to tell you what might be wrong.

**Comment by josephjohnston** [comment]
Thank you, now I'm also not sure what was wrong.
