### ISSUE TITLE
use arccot give error tip

### ISSUE THREAD

**Issue by mqingqing123** [mathjax/MathJax#2593]
here is code snip

```
    <p>
   \(  \arccot \alpha \)
  </p>
  
  <p>
   \(  \arcsin \alpha \)
   </p>
```

`\arcsin` is OK, but  `\arccot` give error tip

see here  [https://ibb.co/YcFB5CK](https://ibb.co/YcFB5CK)

**Comment by dpvc** [comment]
MathJax only defines the functions from Plain TeX listed on page 162 of the TeXBook.  

```
            \arccos  \cos   \csc   \exp   \ker     \limsup  \min  \sinh
            \arcsin  \cosh  \deg   \gcd   \lg      \ln      \Pr   \sup
            \arctan  \cot   \det   \hom   \lim     \log     \sec  \tan
            \arg     \coth  \dim   \inf   \liminf  \max     \sin  \tanh
```

and this only includes `\arcsin`, `\arccos`, and `\arctan`.  You can define the others yourself using

``` latex
\DeclareMathOperator{\arcsec}{arcsec}
\DeclareMathOperator{\arccsc}{arccsc}
\DeclareMathOperator{\arccot}{arccot}
```

and similarly for the other ones.  You could predefine this in your Mathjax configuration using

``` html
<script>
MathJax = {
  tex: {
    macros: {
      arcsec: '\\DeclareMathOperator{\\arcsec}{arcsec}\\arcsec',
      arccsc: '\\DeclareMathOperator{\\arccsc}{arccsc}\\arccsc',
      arccot: '\\DeclareMathOperator{\\arccot}{arccot}\\arccot'
    }
  }
}
</script>
```

and placing this **before** the script that loads MathJax itself.  (Incorporate it with your existing configuration, if any.)

Finally, you can always check the list of [macros available in MathJax](https://docs.mathjax.org/en/latest/input/tex/macros/index.html) to see if the macros you want are available in MathJax.
