### ISSUE TITLE
Mathjax does not render correct the second command

### ISSUE THREAD

**Issue by Paolo1991** [mathjax/MathJax#2599]
Hello everyone,
 On Chrome/Firefox and MathJax 2.7.7 when trying to duplicate the command like:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>MathJax example</title>
  <script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
</head>
<body>
<p>
\begin{align}
    \omega_1 & =
    \frac{\partial w}{\partial y}-\frac{\partial v}{\partial z}\,,
    \nonumber  \\
    \omega_2 & =
    \frac{\partial u}{\partial z}-\frac{\partial w}{\partial x}\,,
    \label{eqcurl}  \\
    \omega_3 & =
    \frac{\partial v}{\partial x}-\frac{\partial u}{\partial y}\,.
    \nonumber
\end{align}
</p>

<p>
\begin{align}
    \omega_1 & =
    \frac{\partial w}{\partial y}-\frac{\partial v}{\partial z}\,,
    \nonumber  \\
    \omega_2 & =
    \frac{\partial u}{\partial z}-\frac{\partial w}{\partial x}\,,
    \label{eqcurl}  \\
    \omega_3 & =
    \frac{\partial v}{\partial x}-\frac{\partial u}{\partial y}\,.
    \nonumber
\end{align}
</p>
</body>
</html>
```

The first command is work, but the second doesn't:
![image](https://user-images.githubusercontent.com/12263410/103448170-2d2c9a00-4cc8-11eb-88ce-c4f880aeb844.png)

Could anyone help me with this?
Thanks!

**Comment by dpvc** [comment]
You can not have two equations with the same label.  You are used `\label{eqcurl}` twice, and that is an error, which MathJax correctly reported.  So you need to either remove the second label, or change it to a different table name.  E.g., you could use `\label{eqcurl1}` for the first, and `\label{eqcurl2}` for the second.  

This is correct behavior.
