### ISSUE TITLE
On Selection of mathjax formula additional area gets selected in ios

### ISSUE THREAD

**Issue by mittalaayush** [mathjax/MathJax#2600]
### Issue Summary

When we select some text which contains a mathjax formula it also selects some additional area with it. This does not allow us the click on the tooltip which is created just above the text. The amount of space also varies for different formulas. The issue comes in ios mobile devices only in app under web view.

### Steps to Reproduce:

1. Open a html document in an app in ios which contains a mathjax formula
2. Select some text which contains a formula
3. Additional blank space with the text also gets selected

### Supporting information:

 * MathJax configuration : 2.7.5, 
 * Screenshot below
![Mathjax error 2](https://user-images.githubusercontent.com/31405725/103478086-60674a00-4dea-11eb-96be-6fa2ca3a8d88.jpeg)
![Mathjax error 1](https://user-images.githubusercontent.com/31405725/103478089-63fad100-4dea-11eb-9622-00cc191619e0.jpeg)
<img width="1440" alt="Mathjax element view" src="https://user-images.githubusercontent.com/31405725/103478093-707f2980-4dea-11eb-8b08-faff6199c301.png">

**Comment by dpvc** [comment]
It appears that you are using the HTML-CSS output processor, which is the oldest one, and somewhat buggy.  You would do better to use either the CommonHTML or SVG output.  These should not have the issue that you are seeing here.  For some reason, the selection does not respect the clipping region that you have highlighted here.  The region is correct, but the selection extends outside of it.
