### ISSUE TITLE
Multiline labels on the `{align}` environment are rendered with offset

### ISSUE THREAD

**Issue by agronskiy** [mathjax/MathJax#2601]
### Issue Summary

When creating a multiline tagged `{align}` environment, the labels' heights are computed wrongly for `chtml` output (ok for `svg`). See screenshots below.

No special changes to fonts or scaling were made (see GitHub repo below).

### Steps to Reproduce:

Minimum example is in https://github.com/agronskiy/mathjax-label-issue 

1. Clone it
2. Compare `chtml.html` and `svg.html` rendering:

<img width="519" alt="chtml" src="https://user-images.githubusercontent.com/9802715/103488444-d8df0280-4e0c-11eb-996d-d03b3e210f6a.png">

vs 

<img width="517" alt="svg" src="https://user-images.githubusercontent.com/9802715/103488454-e09ea700-4e0c-11eb-898a-393eaeb4b0e6.png">

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Mac OS X 10.15.7
* Browser: Chrome 87.0.4280.88 (Official Build) (x86_64)

### Supporting information:

* Minimal example: https://github.com/agronskiy/mathjax-label-issue 
* No messages in Chrome's dev console
* In Safari, it is similar:
<img width="647" alt="chtml-safari" src="https://user-images.githubusercontent.com/9802715/103488463-ec8a6900-4e0c-11eb-895e-9f45126dfb87.png">

Thanks for any hints and for the awesome product!

**Comment by dpvc** [comment]
It looks like there may be accumulated round-off problems in WebKit for this.  The exact same HTML renders properly in Firefox.  I'll have to look into it and see what I can do.

**Comment by dpvc** [comment]
I have made a PR to resolve the issue (along with a bunch of other table issues).
