### ISSUE TITLE
config mathajax@3.2.1 in vue2

### ISSUE THREAD

**Issue by greatshieh** [mathjax/MathJax#2602]
I am using mathjax@3.1.2 in vue2. I load the mml-svg.js dynamically in a page by function.

```javascript
const script = document.createElement('script')
script.src = CDN_MathJax
script.id = CDN_MathJax
document.body.appendChild(script)
```
and config mathjax
```javascript
window.MathJax = {
        svg: { fontCache: "global", scale: 2 },
      };
```
then I got an error `window.MathJax.mathml2svg() is not a function` when render the page.

The object `window.MathJax` is 
![](https://i.stack.imgur.com/cXw50.png)

But it's Ok without config, and the object `window.MathJax` is default configuration like

![](https://i.stack.imgur.com/Qwf3o.png)

So how to config Mathjax@3.1.2 in vue correctly?

**Comment by dpvc** [comment]
Make sure the MathJax configuration is in place **before** you add the script that loads MathJax. That is, you are probably overwriting the `MathJax` object that `mml-svg.js` sets up. The configuration has to be in place when MathJax is loaded in order for it to find the configuration.
