### ISSUE TITLE
mjx-container is role="presentation" but focusable

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2608]
The combination of role=presentation and tabindex=0 leads to https://w3c.github.io/aria/#conflict_resolution_presentation_none 

> f an element is focusable, or otherwise interactive, user agents MUST ignore the presentation role and expose the element with its implicit role, in order to ensure that the element is operable.

This is usually flagged by automated checkers.

It's not a real issue since custom elements have no implicit role worth disabling but for the same reason I don't see why it's added either.

**Comment by dpvc** [comment]
I think we can probably remove the `role` entirely.  This was probably just copied from v2 output that didn't use the custom elements.
