### ISSUE TITLE
Different font for mathcal in different browsers (and OSes)

### ISSUE THREAD

**Issue by matteoipri** [mathjax/MathJax#2614]
Hi,

Starting from the LaTeX code
```latex
mathcal
\begin{equation}
\mathcal{W}
\end{equation}
```
using tex4ht and some other tools I end up with the following HTML+MathML code
```html
<!DOCTYPE html>
<html lang="en-US" xml:lang="en-US">

<head>
	<title>math fonts</title>
	<meta charset="utf-8" />
	<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
	<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js"></script>
</head>

<body>
	<p>mathcal</p>
	<table class="equation">
		<tr>
			<td>
				<math xmlns="http://www.w3.org/1998/Math/MathML" display="block" class="equation">
					<mi mathvariant="bold-script">W</mi>
				</math>
			</td>
		</tr>
	</table>
</body>

</html>
```

This HTML page is rendered differently on different browsers and operating systems combinations.
In particular I find that the combination of my Arch Linux installation + Chromium (Version 88.0.4324.96 (Official Build) Arch Linux (64-bit)) renders the font as I expect from the PDF, while Firefox (84.0.2 (64-bit)) on the same PC uses the wrong glyph.

Chromium:
![image](https://user-images.githubusercontent.com/695348/105156409-15e50d80-5b0c-11eb-8ec0-0c428622d882.png)
Firefox:
![image](https://user-images.githubusercontent.com/695348/105156437-21d0cf80-5b0c-11eb-9f19-625fc4b6c093.png)
Safari on Mac (from a friend, I do not have the specific versions at hand now):
![image](https://user-images.githubusercontent.com/695348/105156551-4af16000-5b0c-11eb-8a08-09e322e93f67.png)

The result does not change if I switch to SVG output or if I pre-process the HTML file (both CHTML and SVG output) with the tools available at [MathJax-demos-node](https://github.com/mathjax/MathJax-demos-node).

I do not get any error message in the console.

According the [MathML documentation](https://mathml-refresh.github.io/mathml-core/#bold-script-mappings) I found, bold-script is the correct mathvariant, so it seems like Chromium is correct and the other browsers are wrong here.

How can I have all browsers render as Chromium on Arch Linux does in the first screenshot above?

Thank you

**Comment by dpvc** [comment]
> According the [MathML documentation](https://mathml-refresh.github.io/mathml-core/#bold-script-mappings) I found, bold-script is the correct mathvariant.

That is not actually correct.  The page you link to only indicates that `W` with `mathvariant="bold-script"` should map to U+1D4E6 (the bold script W in the Math Alphanumerics Unicode block), but the character shown next to that is just `&#x1D4E6;` in the HTML file, and so its display is dependent on the fonts on your system, and how your browser handles them.  It will be a different character on different computers (in fact, it should show the same differences that you indicate above).

In addition, this is the bold version of the character at U+1D4B2, in the [script](https://mathml-refresh.github.io/mathml-core/#script-mappings) section, which is probably the one you actually are after.  But again, what you see there will depend on your fonts and the browser you are using.

Unfortunately, there are more than one "script" font face in LaTeX, including the calligraphic face (`\mathcal`) and the script face (`\mathscr`), but MathML only has one `mathvariant` for script, and it is not clear whether this should be the face used by `\mathcal` or the one from `\mathscr`.  The Unicode Organization shows `\mathscr` in the [Math Alphanumerics](https://unicode.org/charts/PDF/U1D400.pdf) section for `script` and `bold-script` variants, and so did the STIX1 fonts, but Cambria Math has `\mathcal` at those locations, and STIX2 seems to have `\mathcal` for `script`, but a bold version of `\mathscr` for `bold-script` (which seems pretty weird).  So there is not much consistency among fonts for what these characters should look like.

The MathJax TeX fonts map the `script` variant to `\mathscr` characters, like the Unicode Organization charts indicate, and uses an internal variant for `\mathcal`.  MathJax doesn't have a bold version of `\mathscr`, and so when the MathML calls on `bold-script`, it falls back on the browser's implementation of the characters at that location in the Math Alphanumerics section.  That is why you are seeing a difference from browser to browser, as you would with any character that is not in the MathJax fonts.

I'm not sure `tex4ht` maps `\mathcal` to `bold-script`, but perhaps the figure `\mathscr` is `script` and didn't have anywhere else for `\mathcal`, or perhaps there is a font that misuses `bold-script` as a different face from `script`. 

It is possible to add a post-filter to the MathJax MathML input jax to convert `bold-script` to the internal mathvariant used by MathJax to produce the calligraphic script.  This configuration would do it:

``` html
<script>
MathJax = {
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      MathJax.startup.input[0].postFilters.add(({math, document, data}) => {
        data.walkTree((node) => {
          if (node.attributes.get('mathvariant') === 'bold-script') {
            node.attributes.set('mathvariant', '-tex-calligraphic');
          }
        });
      });
    }
  }
}
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js"></script>
```

**Comment by matteoipri** [comment]
Thank you very much for the detailed explanation and for the proposed solution that fixes the issue for me.

I never use `\mathscr` in my documents and I just discovered that I do not even have that macro available with the set of packages I use.

Looking at the PDF you have linked, I would say that tex4ht maps `\mathcal` to the `mathematical script` characters where available (e.g. `\mathcal{A}` is mapped to [U+1D49C](https://graphemica.com/1D49C)) and to _simple_ `script` characters when the _mathetical_ version is not available (e.g. `\mathcal{B}` is mapped to [U+212C](https://graphemica.com/%E2%84%AC)).
To all of them, it adds the attribute `mathvariant="bold-script"`.
