### ISSUE TITLE
\not{x} vs \not x (single characters)

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2619]
Could "single character \not" get the same [remapping](https://github.com/mathjax/MathJax-src/blob/master/ts/input/tex/base/BaseMappings.ts#L670) when the character is wrapped in braces, e.g., both `\not =` and `\not{=}` map to `\neq`? It seems unfortunate that these get the generalized `\not` treatment.

**Comment by dpvc** [comment]
They could, but that's not how LaTeX operates, so that is not how these are handled.  In LaTeX `\not=` will be different from `\not{=}` in the same way that they are in MathJax.  Here are `\not=` and `\not{=}` in actual LaTeX:

<img width="249" alt="ne" src="https://user-images.githubusercontent.com/432782/106053755-29b6e380-60b9-11eb-8de1-d26d7e31e40c.png">

We have tried to move away from differences in MathJax and LaTeX when we can, so that is why these are as they are in MathJax.

**Comment by pkra** [comment]
Sorry, I thought I had checked that it matches TeX. I don't think we need it in that case.

**Comment by pkra** [comment]
Just a side note: xetex and luatex do treat \not= and \not{=} identically (IIUC via unicode-math). Mimicking this might make more sense in mathjax-unicode-math.

**Comment by dpvc** [comment]
Here is a (typescript) extension that implements that you ask:

``` typescript
import {MmlNode, TextNode, TEXCLASS} from 'mathjax-full/js/core/MmlTree/MmlNode';
import NodeUtil from 'mathjax-full/js/input/tex/NodeUtil';
import {CheckType, BaseItem, StackItem} from 'mathjax-full/js/input/tex/StackItem';
import {Configuration} from 'mathjax-full/js/input/tex/Configuration';

import {NotItem} from 'mathjax-full/js/input/tex/base/BaseItems';
import {CommandMap} from 'mathjax-full/js/input/tex/SymbolMap';
import TexParser from 'mathjax-full/js/input/tex/TexParser';

export class BetterNot extends NotItem {

  /**
   * @override
   */
  public get kind() {
    return 'better-not';
  }

  /**
   * @override
   */
  public checkItem(item: StackItem): CheckType {
    let mml: TextNode | MmlNode;
    let c: string;
    let textNode: TextNode;
    if (item.isKind('open') || item.isKind('left')) {
      // @test Negation Left Paren
      return BaseItem.success;
    }
    if (item.isKind('mml')) {
      mml = item.First;
      if (NodeUtil.isType(mml, 'TeXAtom') && mml.texClass === TEXCLASS.ORD &&
             NodeUtil.getChildren(NodeUtil.getChildren(mml)[0]).length === 1) {
        mml = NodeUtil.getChildren(NodeUtil.getChildren(mml)[0])[0];
      }
      if (NodeUtil.isType(mml, 'mo') || NodeUtil.isType(mml, 'mi') || NodeUtil.isType(mml, 'mtext')) {
        c = NodeUtil.getText(mml as TextNode);
        if (c.length === 1 && !NodeUtil.getProperty(mml, 'movesupsub') &&
            NodeUtil.getChildren(mml).length === 1) {
          if ((this as any).remap.contains(c)) {
            // @test Negation Simple, Negation Complex
            textNode = this.create('text', (this as any).remap.lookup(c).char) as TextNode;
            NodeUtil.setChild(mml, 0, textNode);
          } else {
            // @test Negation Explicit
            textNode = this.create('text', '\u0338') as TextNode;
            NodeUtil.appendChildren(mml, [textNode]);
          }
          return [[item], true];
        }
      }
    }
    // @test Negation Large
    textNode = this.create('text', '\u29F8') as TextNode;
    const mtextNode = this.create('node', 'mtext', [], {}, textNode);
    const paddedNode = this.create('node', 'mpadded', [mtextNode], {width: 0});
    mml = this.create('node', 'TeXAtom', [paddedNode], {texClass: TEXCLASS.REL});
    return [[mml, item], true];
  }

}

new CommandMap('better-not', {
  not: 'Not'
}, {
  Not(parser: TexParser, _name: string) {
    parser.Push(parser.itemFactory.create('better-not'));
  }
});

export const NotConfiguration = Configuration.create('better-not', {
  handler: {macro: ['better-not']},
  items: {[BetterNot.prototype.kind]: BetterNot}
});
```

It subclasses the `NotItem` stack item and replaces the method that handles negating what follows.  The change is to unpack a `TeXAtom` of class `ORD` that contains a single child node (which is what `{=}` will produce), and process that as through the braces weren't there.

This is not perfect in the sense that other things can produce a `TeXAtom` with type `ORD`, for example `\mathord{=}`, so `\not\mathord{=}` would also act like `\not =`, but I suspect that is probably OK (you could always use `\not{\mathord{=}}` to prevent that).
