### ISSUE TITLE
[question] writing dual use macros

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2621]
How do I go about creating a macro (in an extension) that also works in textmode (i.e., using the textmacros extension)?

**Comment by dpvc** [comment]
A substitution macro (like what you get from `\newcommand` or using `['Macro', ...]` in a `CommandMap`) should be available in text mode automatically.  Is that sufficient, or do you need other javascript-based macros?

**Comment by pkra** [comment]
> A substitution macro (like what you get from `\newcommand` or using `['Macro', ...]` in a `CommandMap`) should be available in text mode automatically. 

Good to know.

> do you need other javascript-based macros?

Yes, I have some custom methods in an extension that I'd like to work with the textparser as well.

**Comment by dpvc** [comment]
Here is a configuration that adds an extra CommandMap into the macro handlers for the base configuration for the `textmacros`:

``` javascript
MathJax = {
  tex: {packages: {'[+]': ['textmacros']}},
  loader: {load: ['[tex]/textmacros']},
  startup: {
    ready() {
      //
      //  These would be replaced by import commands if you wanted to make
      //  a proper extension.
      //
      const {CommandMap} = MathJax._.input.tex.SymbolMap;
      const {textBase} = MathJax._.input.tex.textmacros.TextMacrosConfiguration;
      
      //
      //  New command map for your extension
      //
      new CommandMap('textmacros-extension', {
        test: ['TestMacro']
      }, {
        TestMacro(parser, name) {
          parser.Push(parser.create('token', 'ms', {}, 'test'));
        }
      });
      
      //
      //  Include your command map in the macro handler list for the textmacros
      //    base configuration.
      //
      textBase.handler.macro.unshift('textmacros-extension');

      MathJax.startup.defaultReady();
    }
  }
}
```

Will that do what you need?

**Comment by dpvc** [comment]
PS, you should be able to use `textmacros-extension` in a configuration for the main TeX parser as well.  E.g.

``` javascript
MathJax = {
  tex: {packages: {'[+]': ['textmacros', 'my-extension']}},
  loader: {load: ['[tex]/textmacros']},
  startup: {
    ready() {
      //
      //  These would be replaced by import commands if you wanted to make
      //  a proper extension.
      //
      const {Configuration} = MathJax._.input.tex.Configuration;
      const {CommandMap} = MathJax._.input.tex.SymbolMap;
      const {textBase} = MathJax._.input.tex.textmacros.TextMacrosConfiguration;
      
      //
      //  New command map for your extension
      //
      new CommandMap('textmacros-extension', {
        test: ['TestMacro']
      }, {
        TestMacro(parser, name) {
          parser.Push(parser.create('token', 'ms', {}, 'test'));
        }
      });
      
      //
      //  Include your command map in the macro handler list for the textmacros
      //    base configuration.
      //
      textBase.handler.macro.unshift('textmacros-extension');

      Configuration.create('my-extension', {
        handler: {
          macro: ['textmacros-extension']
        }
      });

      MathJax.startup.defaultReady();
    }
  }
}
```

**Comment by pkra** [comment]
Thank you, Davide! The first approach worked for me (the extension is written in typescript by the way).

**Comment by dpvc** [comment]
Glad it worked out.  I only added the second one to show how you could use the macros in both text-mode and math-mode.  If you want text-mode-only macros, the first one is sufficient.

**Comment by pkra** [comment]
> Glad it worked out. I only added the second one to show how you could use the macros in both text-mode and math-mode. If you want text-mode-only macros, the first one is sufficient.

Right, that was a typo on my end. It was already working in math mode so I only needed to add it to the textmacros.
