### ISSUE TITLE
[TeX][SVG] \set overlapping text with brace

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2624]
On mathjax.org#demo (using SVG output), e.g., `$$ \set{n | n \in \mathbb{N}  }$$` renders

![image](https://user-images.githubusercontent.com/426686/106362590-faf07580-6323-11eb-8ed7-150b30745501.png)

More generally, `$\set{ x }$` is ok but `$ \set{xx}$` is not.

**Comment by dpvc** [comment]
This turns out to be due to an inferred mrow being included in the output of `\set` where it shouldn't be.  (This is similar to the issue in #2524, exactly 100 issues/PRs ago.)
