### ISSUE TITLE
avoid nested links

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2628]
MathJax currently takes something like `\href{//example.com}{an \href{//another.com}{example}}` and generates HTML or SVG with nested anchor tags which is invalid and breaks when (re)parsed.

**Comment by dpvc** [comment]
LaTeX doesn't complain about this construction, and I'm not sure it is worth the overhead of checking the hierarchy for every href.  It seems to me that this should be something the user is responsible for doing right.  Is there a use-case where this has been coming up?
