### ISSUE TITLE
Incorrect values of getBoundingClientRect() function

### ISSUE THREAD

**Issue by zezekalo** [mathjax/MathJax#2629]
### Issue Summary

I'm an android developer.
I use WebView to show  Html pages inside Android application (Android 10, OnePlus 7T Pro). I use JavascriptInterface and bridges to interact between  java and javascript, to pass data in both direction.
In one of the js function, I use method getBoundingClientRect() to get relative position of selected text inside viewport. It works perfectly when I download usual html page, position is correct.
But when Html page contains math and I add mathjax to that page then after on getBoundingClientRect() call I  get incorrect value which exceed device height.

How could I get the correct data from getBoundingClientRect() on html page with math?

### Steps to Reproduce:

1. Load page with math and MathJax
2. Scroll a bit down.
3. call getBoundingClientRect()

### Technical details:

* MathJax Version: 2.7
* Client OS: Andrpoid 11
* Browser: WebView

**Comment by dpvc** [comment]
There is insufficient information in your report.  For example, what output renderer are you using (SVG, CommonHTML, HTML-CSS)?  What expression are you rendering that gives the wrong value?  What element are you calling `getBoundingClientRect()` on?

Can you provide a minimal example (a simple app that exhibits the problem)?

**Comment by zezekalo** [comment]
As I could understand the reason of that issue is not MathJax lib, so I'm closing the issue.
