### ISSUE TITLE
Stretchy Parallel after Enrichment

### ISSUE THREAD

**Issue by zorkow** [mathjax/MathJax#2632]
This is the same as [SRE #459](https://github.com/zorkow/speech-rule-engine/issues/459)

```latex
\|\hat{f}\|_{X_j},
```

After enrichment the second parallel is no longer marked as non-stretchy.
The resulting mml structure is similar to what we get from `{{\|\hat{f}}\|_{X_j}},` where the second parallel is marked as non-stretchy.

**Comment by dpvc** [comment]
It looks like the second `\|` is not getting `stretchy="false"` in the original conversion to MathML, so it is not SRE's fault.  I'll look into it further.

**Comment by dpvc** [comment]
OK, I worked out the problem, and have made a PR for it that explains what was going on.
