### ISSUE TITLE
feature, TeX: coloring "full" cells

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2634]
As per discussion elsewhere, v3's outputs allow coloring of "full" table cells, i.e., not just child nodes.

It would be usefult to have access to this in the TeX input. For example, the [xcolor package](https://ctan.org/pkg/xcolor) has table-specific coloring options for (\cellcolor, \rowcolor) which could be a useful set of names.

**Comment by dpvc** [comment]
@coatless, I've moved the issue to the MathJax repository.

**Comment by dpvc** [comment]
This is now in the `colortbl` extension new in v3.2.

**Comment by coatless** [comment]
Thank you so much @dpvc for following up on this and making it a reality!

**Comment by dpvc** [comment]
@coatless, you are welcome.  This was a good addition, and one that I'm sure many people will be able to take advantage of.
