### ISSUE TITLE
SVG image not vertically aligned with the div object

### ISSUE THREAD

**Issue by larzcaetano** [mathjax/MathJax#2636]
I am trying to make an SVG for Green's Theorem and center it on the middle of a div object. It works correctly on the horizontal, however, it looks aligned with the div's top.
This is my code:

`index.html`
```html
<html>
	<head>
		<title>Larz Caetano</title>
		<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
		<script>
			MathJax = {
				loader: {
					load: [
						"[tex]/ams",
						"[tex]/color",
					],
				},
				tex: {
					packages: {
						"[+]": [
							"ams",
							"color",
						],
					},
					inlineMath: [["$", "$"], ["\\(", "\\)"]],
					displayMath: [["$$", "$$"]],
				},
				svg: {
					fontCache: "global",
					displayAlign: "center",
				},
				options: {
					renderActions: {
						addMenu: [],
					},
				},
			};
		</script>
		<script id="Mathjax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.1/es5/tex-svg.js"></script>
	</head>
	<body>
		<script src="main.js"></script>
	</body>
</html>
```

`main.js`
```js
document.body.onload = function() {
	let body = document.body;
	body.width = window.innerWidth;
	body.height = window.innerHeight;
	body.style.margin = "0px";
	body.style.border = "0px";
	body.style.padding = "0px";
	body.style.backgroundColor = "rgb(255, 255, 255)";

	let createTextNode = function(parent, text) {
		let textNode = document.createTextNode(text);
		parent.appendChild(textNode);
		return true;
	}

	let div = document.createElement("div");
	div.style.width = "100%";
	div.style.height = "100%";
	div.style.fontSize = "4em";
	div.style.textAlign = "center";

	let options = MathJax.getMetricsFor(div, true);
	let html = MathJax.tex2svg(`
		\\oint\\limits_{\\partial R} \\vec{F}\\cdot\\mathrm{d}\\vec{s} = 
		\\iint\\limits_{R} \\frac{\\partial Q}{\\partial x} - \\frac{\\partial P}{\\partial y} \\mathrm{d}A
	`, options)
	div.appendChild(html);
	createTextNode(div, "wow nice");
	body.appendChild(div);
}
```

This is what I am getting after running it:
![image](https://user-images.githubusercontent.com/43055816/109369569-915c7c00-787b-11eb-9c94-65f65347f2c1.png)

I thought that it would possibly be an issue or maybe the lack of a feature, or very possibly me being dumb. If you guys can come up with a solution, I would appreciate it.

Thanks,
Larz

**Comment by pkra** [comment]
This might be helpful: https://css-tricks.com/centering-css-complete-guide/

**Comment by dpvc** [comment]
I was going to recommend the same link.  The section on vertical centering using flex-box is particularly effective, here.

Note that this really has nothing to do with MathJax in particular.  The content of a div is always aligned to the top, not matter how tall it is.  Vertical centering is not automatic.  The link above gives several approaches you could use to do what you are after.

**Comment by larzcaetano** [comment]
@pkra and @dpvc, thanks a lot for the immediate response and for suggesting me a way to achieve what I was looking for. Wasn't an issue with MathJax at all.

Best regards,
Larz
