### ISSUE TITLE
I am using Mathjax3 in Production 

### ISSUE THREAD

**Issue by ngcgolf11** [mathjax/MathJax#2638]
Is there any easiest way that we can support more latex script than the current version please suggest how I can extend mathjax support for many other latex commands  which we are not currently supporting

**Comment by dpvc** [comment]
It depends on what the macros you are looking for actually do.  If they are simple replacement macros, you can use `\newcommand` to define them, or use the [configmacros](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html) extension to include them in your configuration.

If they are more complicated than that, then you have to implement them as a MathJax extension using javascript.  There are a number of such extensions in the MathJax core distribution in the various [input/tex](https://github.com/mathjax/MathJax-src/tree/master/ts/input/tex) subdirectories.  The [verb](https://github.com/mathjax/MathJax-src/tree/master/ts/input/tex/verb) and [cance](https://github.com/mathjax/MathJax-src/blob/master/ts/input/tex/cancel/CancelConfiguration.ts) extensions are relatively simple ones.

Finally, there is the [custom-tex-extension](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-tex-extension/mml.html.md) in the [customization](https://github.com/mathjax/MathJax-demos-web#customization) section of the MathJax web demos repository, which is also described in the MathJax [documentation](https://docs.mathjax.org/en/latest/web/webpack.html#a-custom-extension).
