### ISSUE TITLE
rendering ( as \left(

### ISSUE THREAD

**Issue by babarlelephant** [mathjax/MathJax#2644]
Hi, is there a way to render ( as if it was \left(  ?
From [this issue](https://github.com/mathjax/MathJax/issues/2064) I tried

```
MathJax.Hub.Register.StartupHook("mml Jax Ready", function () {
    MathJax.ElementJax.mml.mo.prototype.OPTABLE.postfix[')'][3].stretchy = true;
    MathJax.ElementJax.mml.mo.prototype.OPTABLE.prefix['('][3].stretchy = true;
});
```

but it doesn't work.  Replacing true by false has an impact in the mathML code: the stretchy=false attributes are not there anymore. But \left(  adds the attribute stretchy=true.

**Comment by dpvc** [comment]
The TeX input jax marks `(` and `)` explicitly as `stretchy="false"` so the settings in the operator table will not affect the result, as you have found.  This has to be handled at the TeX input side of things.  Here is one way to do it:

``` javascript
  MathJax.Hub.Config({
    TeX: {Augment: {
      Definitions: {
        special: {
          '(': 'Paren',
          ')': 'Paren'
        }
      },
      Parse: {prototype: {
        Paren: function (c) {
          this.Push(MathJax.InputJax.TeX.Stack.Item[c === '(' ? 'left' : 'right']().With({delim: c}));
        }
      }}
    }}
  });
```

though I'm not sure it's a good idea in general.  But that is up to you.
