### ISSUE TITLE
[context-menu] menu entry for explorer not active when pre-configured to be active

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2646]
When configuring mathjax to enable exploration, e.g.,

```js
  MathJax = {
          loader: {
            load: ['a11y/semantic-enrich', 'a11y/explorer'],
          },
          options: {
            enableExplorer: true,
            a11y: {
              speech: true, // switch on speech output
              braille: true, // switch on Braille output
              subtitles: true, // show speech as a subtitle
            },
          },
        };
``` 

the settings work but the context menu does not reflect this, i.e., under "Accessibility" the first item "Activate" is not checked and the submenus are not available.

Once I check the menu item "Activate", it's ok (and no re-rendering happens).

I suspect it's an issue with zorkow/context-menu but I thought I'd start here.

**Comment by dpvc** [comment]
The item that controls the Activate menu is `explorer`.  That has to be set to true in order to activate the rest of that menu.  The other settings are for subitems in that menu, and your settings are controlling those, as you point out.

**Comment by dpvc** [comment]
I see that the `explorer` item seems to be missing from the documentation.  The `enableExplorer` item also is not as clear as it should be.

**Comment by pkra** [comment]
> The item that controls the Activate menu is `explorer`. That has to be set to true in order to activate the rest of that menu. 

Thanks! If I add explorer: true to the a11y option, I get an error in the console "MathJax(?): Invalid option "explorer" (no default value).". 

Where should I set "exporer: true"?

**Comment by dpvc** [comment]
Use

``` javascript
MathJax = {
  options: {
    menuOptions: {
      settings: {
        explorer: true
      }
    }
  }
};
```

Note that you don't need to load the explorer or semantic-enrich yourself.  The menu will do that for you.

**Comment by pkra** [comment]
Ah! Thanks for clarifying.
