### ISSUE TITLE
[a11y] locale:es not applied to semantic-enrich

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2647]
When configuring mathjax to enable enrichment and exploration in (say) Spanish, e.g.,

```js
MathJax = {
  options: {
    a11y: {
      speech: true, // switch on speech output
      braille: true, // switch on Braille output
      subtitles: true, // show speech as a subtitle
      locale: 'es', // locale
    },
    menuOptions: {
      settings: {
        explorer: true
      }
    }
  }
};
``` 

mjx-container will have an aria-label in English (while the explorer provides Spanish as desired).

Once I activate the explorer (cf #2646), the aria-label disappears; I can't figure out how to bring it back via the menu (in English or otherwise).

**Comment by pkra** [comment]
Thanks, Davide. (For others: the PR is https://github.com/mathjax/MathJax-src/pull/561/)

**Comment by dpvc** [comment]
I also think that if you change the language menu for the explorer, the label will not be updated.  All of the re-rendering on menu changes is pretty complicated, and bears going over again.

**Comment by pkra** [comment]
Thanks, Davide. (For others: the PR is https://github.com/mathjax/MathJax-src/pull/561/)

> I also think that if you change the language menu for the explorer, the label will not be updated. 

Yes, I can confirm that. But at least with the correct configuration, it no longer disappears completely.
