### ISSUE TITLE
Unicode extension: Issues with multi-character subscripts

### ISSUE THREAD

**Issue by ftclausen** [mathjax/MathJax#2648]
### Issue Summary

Browser: Chrome 89.0.4389.82 and Safari 14.0.3
OS: macOS

When a unicode character rendered with the unicode extension, eg. `\unicode{9744}`, is used then MathJax does not render math when used with multi-character subscripts in some circumstances. 

### Steps to Reproduce:

The following MathJax snippet reproduces the problem for me

```
This is a test $\unicode{9744}_n = \unicode{9744}_{n-1} + n^2$ sentence with unicode math
```

Image of the issue as manifested for me:

![](https://ftclausen.s3.amazonaws.com/transfer/mathjax_unicode_render_issue.png)

You can see math is not rendered.

### Technical details:

* MathJax Version: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js
* Client OS: Mac OS X 10.8.4
* Browser: Chrome 29.0.1547.57

### Supporting information:

Minimal example:

http://ftclausen.github.io/testje/

Screenshot:

![](https://ftclausen.s3.amazonaws.com/transfer/mathjax_unicode_render_issue.png)

MathJax config:

```
window.MathJax = {
  chtml: {
    displayAlign: "left",
    displayIndent: "2em",
    scale: 0.95
  },
  tex: {
    inlineMath: [ ['$', '$'], ["\\(", "\\)"] ],
    displayMath: [ ['$$', '$$'], ["\\[", "\\]"] ],
    processEscapes: true
  },
  options: {
    skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process'
  }
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js">
</script>

```

**Comment by pkra** [comment]
This is a typical markdown interference. In the HTML source, you'll see `<p>This is a test $\unicode{9744}<em>n = \unicode{9744}</em>{n-1} + n^2$ sentence with unicode math</p>` which is why things break. See also http://docs.mathjax.org/en/latest/input/tex/html.html#interactions-with-content-management-systems.

**Comment by ftclausen** [comment]
Yes, that was it. I could escape one of the underscores `\_` and that fixes the issue. Thanks for your help!
