### ISSUE TITLE
Wrong input processing option in docs

### ISSUE THREAD

**Issue by fast-reflexes** [mathjax/MathJax#2649]
### Issue Summary

According to the docs (http://docs.mathjax.org/en/latest/options/input/mathml.html) the entry `input/mathml` should be added to the `load` array for MathML support. This is wrong and it should be `input/mml`.

### Steps to Reproduce:

Go to code pen (https://codepen.io/fast-reflexes/pen/yLVQKXe) and check the load array at top with the entry `input/mathml`. This results in a download error in the console. Now, change it to `input/mml` and verify that it works. You may also uncomment the empty `mml` object under to verify that it works this way to (with the upper row commented out).

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.1.2
* Client OS: Mac OS Catalina 10.15.7
* Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

**Comment by dpvc** [comment]
Thanks.  I'll fix it during the next update to the docs.
