### ISSUE TITLE
msub/msup errors when ui/menu is enabled - Chrome only

### ISSUE THREAD

**Issue by sqlpac** [mathjax/MathJax#2666]
Bonjour,

### Issue Summary

On Chrome 89/Windows 10, when `ui/menu` is enabled : msub, msup errors occur. On Firefox and Edge, there is no issue.

### Steps to Reproduce:

1. 

With the following configuration 
```javascript
        window.MathJax = {
          tex: {
            inlineMath: [ ['##','##'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            packages: {'[+]': ['mhchem','physics']}
          },
          chtml: {
            displayAlign: "left"
          },
          options: {
            ignoreHtmlClass: 'tex2jax_ignore',
            processHtmlClass: 'cmath'
          },
          loader: {
            load: ['input/tex-base','output/chtml','[tex]/mhchem','[tex]/physics']
          }
        };
```
```html
<script defer="true" src="[MathJax 3.1.2]/startup.js" id="MathJax-script"></script>
```
On Chrome 89 : the following Tex equation is OK using `ce` macro from `mhchem` package

`\ce{SO4^2- + Ba^2+ -> BaSO4 v} `

2. Add `ui/menu` in the loader

  `load: ['input/tex-base','output/chtml','[tex]/mhchem','[tex]/physics','ui/menu']`

Equation is then KO on Chrome 89 with msub/msup errors. No issues on Firefox and Edge.

![msubmsup](https://user-images.githubusercontent.com/50557334/113413756-aa48d780-93bb-11eb-91a9-0e7d41cc0401.png)

**Comment by sqlpac** [comment]
Seems to be a Chrome issue only on Version 89.0.4389.114 (Build officiel) (64 bits). 

Tests have been conducted on Chrome 91.0.4466.2 (Build officiel) canary (64 bits) : NO issue with msub/msup

**Comment by dpvc** [comment]
It is likely not the menu itself, but more likely the semantic enrichment that is the issue.  You may have that turned on in your menu settings, and that is why adding the menu causes the issue.  Try using the "Reset to defaults" in the "Math Settings" submenu of the Mathjax contextual menu, and then reload the page to see if that helps.  (The reason it seems to be only for one version is that that is the only one where the enrichment has been activated).

**Comment by dpvc** [comment]
I have just verified that enrichment causes the problem for me.

**Comment by sqlpac** [comment]
I do not know Accessibility features at all, this option has been turned on by inadvertance : with Reset Default Settings, everything is OK. Thank you very much and sorry for inconvenience

**Comment by sqlpac** [comment]
Just a note. To be able to deactivate Accessibility, I had to create a new block equation.

When accessibility is enabled, clicking on the equation does not render the contextual menu and in the console the below error is raised

menu.js:1 Uncaught TypeError: Cannot read property 'dataset' of undefined
    at Object.sre.DomUtil.getDataAttribute (sre_browser.js:138)
    at Object.sre.WalkerUtil.getAttribute (sre_browser.js:604)
    at sre.RebuildStree.makeNode (sre_browser.js:609)
    at sre.RebuildStree.assembleTree (sre_browser.js:607)
    at sre.RebuildStree.e (sre_browser.js:608)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (sre_browser.js:608)
    at sre.RebuildStree.e (sre_browser.js:608)
    at Array.map (<anonymous>)
    at sre.RebuildStree.assembleTree (sre_browser.js:608)

**Comment by zorkow** [comment]
I've made an [upstream issue](https://github.com/zorkow/speech-rule-engine/issues/493).

**Comment by zorkow** [comment]
> Just a note. To be able to deactivate Accessibility, I had to create a new block equation.
> 

Another way around this is
```javascript
delete localStorage['MathJax-Menu-Settings']
```
in the developers console.

**Comment by zorkow** [comment]
[SRE PR #493](https://github.com/zorkow/speech-rule-engine/issues/493) contains a fix.
