### ISSUE TITLE
query baseline

### ISSUE THREAD

**Issue by chacha21** [mathjax/MathJax#2667]
After using "window.MathJax.typeset([node])", I can get the SVG result from the $(node).html()
But is it possible to query the baseline of the rendered expression to be used in a different context ?
(of course the baseline would be relative to the current font size or some other dimension)

**Comment by dpvc** [comment]
The `vertical-align` attribute of the SVG element is the depth below the baseline (in ex units), and the `height` is the total height, so the height above the baseline is the height minus the vertical align value.

**Comment by chacha21** [comment]
👍
