### ISSUE TITLE
Nested msubs

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2668]
### Steps to Reproduce

This is a bug because...
[nested msubs.docx](https://github.com/mathjax/MathJax/files/6272787/nested.msubs.docx)

### Technical details

* MathJax Version: master - latest commit:  MathJax.js v2.7.5
* Client OS: Windows
* Browser: Chrome v89.0.4389.114

**Comment by dpvc** [comment]
MathJax uses TeX's layout for superscripts and subscripts, and in TeX, there is very little difference between the heights of the two subscripts.  Here is TeX's output:

<img width="111" alt="TeX" src="https://user-images.githubusercontent.com/432782/113921638-3b50f180-97b4-11eb-94a5-a34abe0bdb4e.png">

and this is MathJax using the MathJax TeX fonts:

<img width="112" alt="MJX" src="https://user-images.githubusercontent.com/432782/113921830-80752380-97b4-11eb-9127-6835663b1806.png">

These are nearly identical.  Using the STIX fonts (as you appear to be), MathJax produces:

<img width="115" alt="STIX" src="https://user-images.githubusercontent.com/432782/113921878-91be3000-97b4-11eb-96ce-1565a77df4b9.png">

This is admittedly fairly close to the same vertical position, but not quite.  In any case, TeX does not produce the large vertical difference that you are requesting, so MathJax doesn't either.

If you want to get more space, you could use something like `{R_{2\mathstrut}}_2`, which could be coded as 

``` xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <msub>
    <msub>
      <mi>R</mi>
      <mrow>
        <mn>2</mn>
        <mphantom>
          <mpadded width="0">
            <mo stretchy="false">(</mo>
          </mpadded>
        </mphantom>
      </mrow>
    </msub>
    <mn>2</mn>
  </msub>
</math>
```

in MathML.  This produces

<img width="116" alt="strut" src="https://user-images.githubusercontent.com/432782/113922750-acdd6f80-97b5-11eb-99fc-d7f62c053673.png">

I would discourage you from using such constructs, however, as these are visually ambiguous:  Does it represent `{R_2}_2` or `R_{2_2}`.  The visual distinctions between these two are very small, and can lead to confusion about what you are presenting.  The usual reading of the last diagram would be as `R_{2_2}`, and one usually includes parentheses for the other one, as in `\left(R_2\right)_2`.  The same goes for `R^{2^2}` versus `\left(R^2\right)^2`.

**Comment by jmitsdarfer** [comment]
Thank you, that was helpful. I appreciate you responding. I think this example was just sort of a silly, non-real-life example that we had in one of our test files. Looking through a few other examples we had, they look totally fine to me in MathJax, e.g.,
***@***.***D72BC8.70F92A30]
<m:msub><m:mrow><m:mo stretchy="false">&#x27e8;</m:mo><m:msub><m:mrow>
<m:mi>R</m:mi></m:mrow><m:mrow><m:msub><m:mrow><m:mn>1</m:mn></m:mrow>
<m:mrow><m:mi>X</m:mi></m:mrow></m:msub></m:mrow></m:msub><m:mo
stretchy="false">&#x27e9;</m:mo></m:mrow><m:mrow><m:mn>1</m:mn><m:mo
>/</m:mo><m:mn>2</m:mn></m:mrow></m:msub>

***@***.***D72BC8.70F92A30]
… <m:msubsup><m:mrow><m:mi>A</m:mi></m:mrow><m:mrow><m:msub><m:mrow><m:mi
>l</m:mi></m:mrow><m:mrow><m:mi>i</m:mi></m:mrow></m:msub><m:mi>m</m:mi>
</m:mrow><m:mrow><m:mo stretchy="false">(</m:mo><m:mi
mathvariant="normal">R</m:mi><m:mo stretchy="false">)</m:mo></m:mrow>
</m:msubsup> …

It must have been something weird with both subs being the same character or something. I think we can just let that go and keep doing what we’re doing with our tagging. It seems to me that it should turn out how we’d expect in nearly all cases.
I still don’t exactly understand why the nested msups turn out differently from the nested msubs ***@***.***D72BC8.70F92A30] and ***@***.***D72BC8.70F92A30] ), but I guess this is just how TeX does it. Is that right?

Thanks again,
Julie Mitsdarfer


From: Davide P. Cervone ***@***.***>
Sent: Wednesday, April 7, 2021 3:33 PM
To: mathjax/MathJax ***@***.***>
Cc: Mitsdarfer, Julie ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [mathjax/MathJax] Bug: Problem with nested msubs (#2668)


[Actual Sender is ***@***.******@***.***>]

MathJax uses TeX's layout for superscripts and subscripts, and in TeX, there is very little difference between the heights of the two subscripts. Here is TeX's output:

[TeX]<https://user-images.githubusercontent.com/432782/113921638-3b50f180-97b4-11eb-94a5-a34abe0bdb4e.png>

and this is MathJax using the MathJax TeX fonts:

[MJX]<https://user-images.githubusercontent.com/432782/113921830-80752380-97b4-11eb-9127-6835663b1806.png>

These are nearly identical. Using the STIX fonts (as you appear to be), MathJax produces:

[STIX]<https://user-images.githubusercontent.com/432782/113921878-91be3000-97b4-11eb-96ce-1565a77df4b9.png>

This is admittedly fairly close to the same vertical position, but not quite. In any case, TeX does not produce the large vertical difference that you are requesting, so MathJax doesn't either.

If you want to get more space, you could use something like {R_{2\mathstrut}}_2, which could be coded as

<math xmlns="http://www.w3.org/1998/Math/MathML">

  <msub>

    <msub>

      <mi>R</mi>

      <mrow>

        <mn>2</mn>

        <mphantom>

          <mpadded width="0">

            <mo stretchy="false">(</mo>

          </mpadded>

        </mphantom>

      </mrow>

    </msub>

    <mn>2</mn>

  </msub>

</math>

in MathML. This produces

[strut]<https://user-images.githubusercontent.com/432782/113922750-acdd6f80-97b5-11eb-99fc-d7f62c053673.png>

I would discourage you from using such constructs, however, as these are visually ambiguous: Does it represent {R_2}_2 or R_{2_2}. The visual distinctions between these two are very small, and can lead to confusion about what you are presenting. The usual reading of the last diagram would be as R_{2_2}, and one usually includes parentheses for the other one, as in \left(R_2\right)_2. The same goes for R^{2^2} versus \left(R^2\right)^2.

**Comment by dpvc** [comment]
In the two examples you give in your last message, the nesting is `R_(1_x)`, while your first message had `(R_2)_2`, so the nesting is very different, and the positioning (and sizing) differs in those to situations.  The `R_(1_x)` nesting produces what you are expecting to see (successively smaller sizes and successively lower positions).  That is why these examples look good when your earlier ones don't.

**Comment by jmitsdarfer** [comment]
OK yes, I understand it better now! I see how this could possibly affect us in more “real-life” examples!

***@***.***D72BCC.7E0E7B40]
<m:msub>
<m:mrow>
<m:mi>R</m:mi>
</m:mrow>
<m:mrow>
<m:msub>
<m:mrow>
<m:mn>1</m:mn>
</m:mrow>
<m:mrow>
<m:mi>X</m:mi>
</m:mrow>
</m:msub>
</m:mrow>
</m:msub>

would be similar to

***@***.***D72BCC.7E0E7B40]
<m:msub>
<m:mi>R</m:mi>
<m:msub>
<m:mn>2</m:mn>
<m:mn>2</m:mn>
</m:msub>
</m:msub>

We may need to do something about fixing our tagging if we think we may see things like the following slip into our XML:

<m:msub>
<m:msub>
<m:mi>R</m:mi>
<m:mn>1</m:mn>
</m:msub>
<m:mi>X</m:mi>
</m:msub>

or

***@***.***D72BCC.7E0E7B40]
<m:msub>
<m:msub>
<m:mi>R</m:mi>
<m:mn>2</m:mn>
</m:msub>
<m:mn>2</m:mn>
</m:msub>

Thank you for explaining this to me (twice). ☺

-Julie
From: Davide P. Cervone ***@***.***>
Sent: Wednesday, April 7, 2021 4:18 PM
To: mathjax/MathJax ***@***.***>
Cc: Mitsdarfer, Julie ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [mathjax/MathJax] Nested msubs (#2668)


[Actual Sender is ***@***.******@***.***>]

In the two examples you give in your last message, the nesting is R_(1_x), while your first message had (R_2)_2, so the nesting is very different, and the positioning (and sizing) differs in those to situations. The R_(1_x) nesting produces what you are expecting to see (successively smaller sizes and successively lower positions). That is why these examples look good when your earlier ones don't.

**Comment by dpvc** [comment]
Yes, it looks like you have it now!

I'm going to close this issue, then.
