### ISSUE TITLE
import 'mathjax' leads to ReferenceError: require is not defined

### ISSUE THREAD

**Issue by miromannino** [mathjax/MathJax#2670]
### Issue Summary

I am trying to use mathjax like any other library in the javascript ecosystem, but sadly ends in a ReferenceError: require is not defined.

### Steps to Reproduce:

1. yarn add mathjax
2. do a require('mathjax') in a react project, or require('mathjax') has the same issue.
3. cry 😢

### Technical details:

* MathJax Version: 3.1.2
* Browser: any

**Comment by pkra** [comment]
Try `yarn add mathjax-full` instead.

**Comment by miromannino** [comment]
With `mathjax`:

![mathjax](https://user-images.githubusercontent.com/160922/114677014-efa1c900-9d1a-11eb-8c24-1593843bfdcc.png)

With `mathjax-full`:

![mathjax-full](https://user-images.githubusercontent.com/160922/114677053-f92b3100-9d1a-11eb-950e-e91c629f671f.png)

**Comment by dpvc** [comment]
If you are using MathJax in a web application, then you should not use `require('mathjax')` or `require('mathjax-full')`.  See the note in the section of the README file for [MathJax in node applications](https://github.com/mathjax/MathJax-src#using-mathjax-components-in-node-applications).  These require statements are only for node-based applications that run on the server, not the browser.

For the browser, you either need to use [MathJax Components](https://docs.mathjax.org/en/latest/web/start.html), or import MathJax's modules directly into an application that you will bundle using webpack or another bundler (see the [documentation](https://docs.mathjax.org/en/latest/web/start.html)).

Also, there are already several MathJax plugs for React.  See the [npm repository](https://www.npmjs.com/search?q=mathjax-react) for a list of them.  Perhaps one of those would suit your needs.

**Comment by dpvc** [comment]
Oh, I meant to say that you should be able to `require('mathjax/es5/tex-chtml-full.js')` or one of the other combined component files, as these are self-contained, and set up for browser use.  They should be able to be webpacked into a larger application. It would use the `MathJax` global variable, just like in a browser.
