### ISSUE TITLE
Support for Upright Small Greek Letters and Bold Italic Letters

### ISSUE THREAD

**Issue by KotobaSuke** [mathjax/MathJax#2671]
Hello.
In some standards, the constant "π", and the prefix "μ" for micro- are used in upright forms instead of italic forms by default. These can be realized by LaTeX package "upgreek". And the command \bm for bold italic letters (like _**A B C**_) does not work.

**Comment by dpvc** [comment]
An upgreek package is scheduled to be included in the v3.2.0 release (hopefully next month), and the v3.1.3 release (today or tomorrow) includes `\mathbfit` that can be used to get bold italic characters.

In the meantime, you could use

``` javascript
MathJax = {
  tex: {
    macros: {
      'bm': ['\\mmlToken{mi}[mathvariant=bold-italic]{#1}', 1],
      'upalpha': ['\\mmlToken{mi}[mathvariant=normal]{\u03B1}'],
      'upbeta': ['\\mmlToken{mi}[mathvariant=normal]{\u03B2}'],
      ...
    }
  }
}
```

as a temporary work-around until those features are available.  You can see the [upgreek PR](https://github.com/mathjax/MathJax-src/pull/663/files#diff-682699710163fbcf3c153d5fb494ccbb1a0260c035b1998bd35f3001e72f9243) for the unicode values to use for the various Greek characters.
