### ISSUE TITLE
mhchemparser causing syntax error in CommonJS environment

### ISSUE THREAD

**Issue by stevenjoezhang** [mathjax/MathJax#2673]
### Issue Summary

The mhchemparser package introduced in [this commit](https://github.com/mathjax/MathJax-src/commit/d9a6a5aedebcdeeb05734bb46bf4863b5eac3be2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) cannot be imported in the CommonJS environment (e.g. Node.js)
See also
https://github.com/mathjax/MathJax-src/blob/29cd0e8569788ec41dd4b2198018983493b83e36/ts/input/tex/mhchem/MhchemConfiguration.ts#L32

### Steps to Reproduce:

The steps required to reproduce the bug:
1. Install `mathjax-full@3.1.3`
2. Create a file named `test.js`:
```js
//
//  Load the packages needed for MathJax
//
const { mathjax } = require('mathjax-full/js/mathjax.js');
const { TeX } = require('mathjax-full/js/input/tex.js');
const { SVG } = require('mathjax-full/js/output/svg.js');
const { LiteAdaptor } = require('mathjax-full/js/adaptors/liteAdaptor.js');
const { RegisterHTMLHandler } = require('mathjax-full/js/handlers/html.js');

const { AllPackages } = require('mathjax-full/js/input/tex/AllPackages.js');

const adaptor = new LiteAdaptor();
RegisterHTMLHandler(adaptor);

function render(content) {

  //
  //  Create input and output jax and a document using them on the content from the HTML file
  //
  const tex = new TeX({
    packages  : AllPackages,
    tags      : 'ams',
    inlineMath: {
      '[+]': [['$', '$']]
    }
  });
  const svg = new SVG({
    fontCache: 'none'
  });
  const html = mathjax.document(content, {
    InputJax : tex,
    OutputJax: svg
  });

  //
  //  Typeset the document
  //
  html.render();

  //
  //  Output the resulting HTML
  //
  return adaptor.innerHTML(adaptor.body(html.document));
};

console.log(render('$E=mc^2$'));
```
3. Run `node test.js`
4. Error message:
```
root@localhost lib % node test.js
~/hexo-filter-mathjax/node_modules/mhchemparser/dist/mhchemParser.js:33
export class mhchemParser {
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (~/hexo-filter-mathjax/node_modules/mathjax-full/js/input/tex/mhchem/MhchemConfiguration.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```

### Technical details:

* MathJax Version: 3.1.3
* Client OS: macOS 11.2.3
* Browser: Node.js 15.14.0

### Supporting information:

N/A

**Comment by PeachScript** [comment]
+1, `mathjax-full@3.1.3` make our project crash, https://github.com/umijs/dumi/issues/657, https://github.com/umijs/dumi/issues/658, and we create a temp npm package `rehype-mathjax-dumi-tmp` with locked `mathjax-full@3.1.2` as the workaround, this is our discussion: https://github.com/umijs/dumi/discussions/659

There has two things that we want to know:

1. Why the [breaking changes](https://github.com/mathjax/MathJax-src/releases/tag/3.1.3) be included in a patch version?
2. What is your plan to fix this problem, and what should the downstream project do?

**Comment by zorkow** [comment]
An initial workaround is to run your files with ES module support, e.g.,
``` bash
node -r esm test.js
```

**Comment by dpvc** [comment]
Another temporary work-around would be to do

``` bash
pushd node_modules/mhchemparser && tsc --target es5 --typeRoots 'src' && pops
```

which will down-compile mhchemparser to ES5 instead of ES6.  That will allow it to be loaded in your current work-flow.

We will be putting out a new version with a fix later today.  I would like to put out a beta version and ask you to try it out first before making an official release.  Would any of you be willing to do that? @PeachScript, @stevenjoezhang, @xrkffgg?

**Comment by dpvc** [comment]
The new release is out.  Can you check and let us know if that works for you now, please @PeachScript, @stevenjoezhang, @xrkffgg?

**Comment by PeachScript** [comment]
@dpvc v3.1.4 works for us, we will remove the version lock workaround in the next version from our project, thanks for your quick response!

**Comment by dpvc** [comment]
@PeachScript, thanks for letting us know, and for your earlier report as well.  Glad it is working for you.

**Comment by dpvc** [comment]
@stevenjoezhang, thanks for the original report, which allowed us to get this fixed quickly.
