### ISSUE TITLE
Formatting in \text

### ISSUE THREAD

**Issue by Artoria2e5** [mathjax/MathJax#2681]
**Is your feature request related to a problem? Please describe.**
LaTeX on Overleaf compiles the following snippet fine, but MathJax (as on the official demo page) does not seem to recognize the format-changing macros.

```tex
$$
\cos(\text{My very \textbf{greatest \textit{headache}}}) = 0
$$
```

Although odd at first glance, formatting in `\text{}` has legit uses such as making phrase-variables look distinct from operator names. Consider:

```tex
$$
\cos(\text{\itshape that one angle}) = \text{\itshape this magical value}
$$
```

Without the `\itshape`, the equation becomes harder to scan through. (Although in this case, I personally find `\sfshape` more visually pleasing.)

**Describe the solution you'd like**
Make `\textit`, `\itshape`, and friends a thing!

**Describe alternatives you've considered**
I can do it manually by a bunch of `\mathit{}` and `\ `. But uhh...

**Additional context**
KaTeX has the `\text*` stuff, but not the `\*shape` stuff. Makes sense, since statefulness is hard, and it's not strictly necessary anyways.

**Comment by dpvc** [comment]
Traditionally, MathJax did not process any macros in text mode.  More recently, MathJax introduced the `textmacros` extension that processes (some) text-mode macros, including the `\textbf{}` and similar ones.  See the [textmacros documentation](https://docs.mathjax.org/en/latest/input/tex/extensions/textmacros.html) for how to configure it.

Note that this does not include `\itshape` and similar macros, either.

**Comment by Artoria2e5** [comment]
Oh, that's good to know. Would it be a good idea to allow enabling extensions in the demo page though?

**Comment by dpvc** [comment]
You can use the `\require{}` macro to load extensions if you want.  So 

```
$$\require{textmaxcros} 
\cos(\text{My very \textbf{greatest \textit{headache}}}) = 0
$$
```

would do the trick.

**Comment by Artoria2e5** [comment]
Thanks!
