### ISSUE TITLE
| and \| fail as vertically extendable delimiters

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2682]
### Issue Summary

| and \\| fail as vertically extendable delimiters. Try

\\\[\\left|\\int\_a^b f\\right|\\\]

### Steps to Reproduce:

1.  Include with MathJax 3.1.4 \\\[\\left|\\int\_a^b f\\right|\\\]
2.  Include with MathJax 3.1.4 \\\[\\left\\|\\int\_a^b f\\right\\|\\\]

Vertically extended absolute value and norm symbols should appear.

### Technical details:

*   MathJax Version: 3.1.4
*   Client OS: Linux Mint 20.1
*   Browser: Firefox 88.0

### Supporting information:

*   [https://cdi2tp.math.tecnico.ulisboa.pt/test](https://cdi2tp.math.tecnico.ulisboa.pt/test) contains live examples, a [link to the actual configuration being used](https://cdi2tp.math.tecnico.ulisboa.pt/scripts/mathjax-config.js), and a sample of LaTeX typeset code for the same code.
*   I have only been able to reproduce this on Firefox 88.0, Linux Mint 20.1 using CHTML.

**Comment by dpvc** [comment]
The test page you cite works for me (Firefox 88.0, Mac OS X):

<img width="165" alt="mj" src="https://user-images.githubusercontent.com/432782/116783244-b4fa9900-aa5b-11eb-9f3c-ad38e932c5bc.png">

Have you tried clearing your browser cache and restarting the browser?  The update to 3.1.4 was fairly recent, and it may be that you have cached versions of some of the older pieces.

**Comment by cebola2** [comment]
Clearing the cache did not help. But I fail to see it on Windows (several browsers), Firefox on Android and changing from CHTML to SVG.

**Comment by dpvc** [comment]
If you switch to 3.1.2 (cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/tex-chmlt.js) does it work for you?

**Comment by cebola2** [comment]
Neither!

**Comment by dpvc** [comment]
OK, do you have any plugins or anything extra in your copy of Firefox?  (And can you try turning off all plugins?)

Does it work for you in Chrome on you Linux Mint?

Does it work for you if you enter those expressions in the demo on the [MathJax website](https://www.mathjax.org/#demo)?

Do other delimiters, like parentheses and braces work for you?

I'm kind of out of ideas.

**Comment by cebola2** [comment]
This turns out to be a very weird anomaly. It was reported by a student and I was immediately able to reproduce it, but that was just a coincidence.  I have not been able to reproduce it unless on my laptop, with Linux Mint 20.1, Firefox 88.0, using CHTML and very specific page Zoom levels (100%, 30%; at the 67% zoom level only one vertical line per symbol is seen). This happens on the same laptop with other accounts, provided the same browser is used, independently of screen resolution, at the same Zoom levels. Going to the official MathJax site test page I am able to reproduce it but at different Zoom levels (not 100%). My temporary conclusion is this has to do on how Firefox draws thin vertical lines on the page but is dependent on may factors.

**Comment by cebola2** [comment]
No problem with MathJax 2.
A test page using MathJax 2 is
https://cdi2tp.math.tecnico.ulisboa.pt/test_1.php

**Comment by physics-HTFI** [comment]
I seem to have the same problem.
When I enter ``` $$\dfrac{1}{\left\| x' \right\|}$$ ``` on [https://www.mathjax.org/#demo](https://www.mathjax.org/#demo),
the text is rendered as:
![image](https://user-images.githubusercontent.com/21361993/116876754-ed66c680-ac57-11eb-93e4-e0e60803ed37.png)
and subsequently after I click "Render HTML" button, it becomes:
![image](https://user-images.githubusercontent.com/21361993/116876961-420a4180-ac58-11eb-86b8-5274e3a08fdb.png)
On the other hand, with LaTeX:
![image](https://user-images.githubusercontent.com/21361993/116877693-3bc89500-ac59-11eb-9fd7-46006cb5029c.png)
Reproducible on Microsoft Edge 90.0 and Firefox 88.0.

**Comment by dpvc** [comment]
@physics-HTFI, this is actually a different problem, introduced by a change in how delimiters are handled.  I will submit a PR to fix it.

**Comment by cebola2** [comment]
Finally got rid of this anomaly with a new Firefox on Linux Mint version (88.0.1) and a new attempt at cache cleaning.
