### ISSUE TITLE
is TeX-MML-AM_CHTML configuration file on latest version 

### ISSUE THREAD

**Issue by yk0817** [mathjax/MathJax#2685]
**Is your feature request related to a problem? Please describe.**
When I write math documentation on markdown, I load TeX-MML-AM_CHTML configuration file.

ex)
```
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

<script type="text/x-mathjax-config">
 MathJax.Hub.Config({
 tex2jax: {
 inlineMath: [['$', '$'] ],
 displayMath: [ ['$$','$$'], ["\\[","\\]"] ]
 }
 });
</script>

# example
$ T_{1}(N) = 1000N $
```

I want to use TeX-MML-AM_CHTML configuration file on latest version, but I can not find latest file.
Is any plan to update TeX-MML-AM_CHTML configuration file?

or could you tell me how to use latest configuration file when I write on markdown.

**Additional context**
[latest cdn version links](https://cdnjs.com/libraries/mathjax/3.1.4)

**Comment by pkra** [comment]
As per http://docs.mathjax.org/en/latest/web/components/index.html, there's no component that bundles the asciimath input. You can use http://docs.mathjax.org/en/latest/web/webpack.html to build your own.

**Comment by yk0817** [comment]
@pkra 
thx!
Is any plan latest version to be released in cdn？

**Comment by dpvc** [comment]
While you can make your own combined configuration file, as @pkra suggests, it is also possible to load the AsciiMath input components in addition to a combined component that has the other two input formats.  For example, if you use the [configuration conversion tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) with your current configuration, it gives you

``` html
<script>
window.MathJax = {
  tex: {
    inlineMath: [['$', '$'] ],
    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    autoload: {
      color: [],
      colorv2: ['color']
    },
    packages: {'[+]': ['noerrors']}
  },
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process'
  },
  loader: {
    load: ['input/asciimath', '[tex]/noerrors']
  }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" id="MathJax-script"></script>
```

as an equivalent one.  This uses the `tex-mml-chtml.js` component, and adds the `input/ascimmath` component as an additional download.  (It also compensates for some other changes between the defaults from v2 to v3.)

So you can build a custom version yourself if you want, but this should also work.

> Is any plan latest version to be released in cdn？

I'm not sure I understand.  The latest version is 3.1.4, and that is being served by CDNs like `cdn.jsdelivr.net`.  If you are asking about having AsciiMath included in a pre-built combined component, that will not occur until the AsciiMath input jax is converted to v3 (currently it is the v2 input jax patched into v3).

**Comment by yk0817** [comment]
@dpvc thx！ I will try it!
