### ISSUE TITLE
How  I can get to load the 'sre' languages files locally and not remotely from jsdelivr

### ISSUE THREAD

**Issue by franclina** [mathjax/MathJax#2686]
Hi everybody!

I'm trying to config Mathjax.option to load the languages 'sre' /mathjax/es5/sre/mathmaps/es.js | en.js locally, because Mathjax always go to recovery this languages to 'https://cdn.jsdelivr.net/npm/speech-rule-engine@3.1.1/lib/mathmaps/en.js'.

Thxs!

**Comment by pkra** [comment]
Duplicate of https://github.com/mathjax/MathJax/issues/2675

**Comment by franclina** [comment]
I've already tried :

window.MathJax = {
      options: {
        sre: {
          json: 'http://localhost/node_modules/sre/speech-rule-engine/lib/mathmaps'
        }
      }
    }

but I get this error from Chrome devTools and not works :

**MathJax(?): Invalid option "sre" (no default value).**

**Comment by dpvc** [comment]
What components are you loading?  Can you give your complete configuration and the script tag that loads the MathJax component that you are using?

**Comment by franclina** [comment]
This is our configuration: 

```
let script = document.createElement('script'),
            scriptes6 = document.createElement('script')//IE11
        ;
        script.src = '/LOCAL_PATH/ext/mathjax/es5/tex-svg.js';
        script.async = true;
        document.head.appendChild(script);
        scriptes6.src = 'https://polyfill.io/v3/polyfill.min.js?features=es6';
        scriptes6.async = true;
        document.head.appendChild(scriptes6);

        window.MathJax = {
            svg: {
                fontCache: 'global',
                displayAlign: 'left',
            },
            options: {
                a11y: {
                    locale: 'es'
                },
                menuOptions: {
                    settings: {
                        renderer: 'SVG'
                    }
                }
            }
        };
```

Thxs!

**Comment by dpvc** [comment]
Your script works for me when I set the json path to be

``` javascript
json: '/LOCAL_PATH/ext/mathjax/es5/sre/mathmaps';
```

using a local web server (`python -m http.server --cgi 8000`).  I can see the localization file being served locally, and there is no error from MathJax about the `sre` setting.

Can you provide a link to a page where this doesn't work?

**Comment by franclina** [comment]
sorry It was my fault, It's working fine! Thank you for your time @pkra and @dpvc
