### ISSUE TITLE
$\varprojlim ^1$ throws error but $$\varprojlim ^1$$ does not

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2691]
Enter the following on mathjax.org#demo

```tex
    $\varprojlim ^1$
    $$\varprojlim ^1$$
```

The inline expression results in a math input error, the display expression renders as expected:

![image](https://user-images.githubusercontent.com/426686/118287125-717c4200-b4d3-11eb-98be-7c1fb0d16164.png)

**Comment by dpvc** [comment]
OK, I can confirm the issue.  It looks like the problem is occurring when trying to an `<munderover>` to an `<msup><munder>` for in-line mode.  I'll have to look into it further.

**Comment by pkra** [comment]
Thanks, Davide.

**Comment by dpvc** [comment]
I've made a PR to resolve the issue.
