### ISSUE TITLE
Disambiguate  subscript and superscript in output.

### ISSUE THREAD

**Issue by ObscureScience** [mathjax/MathJax#2695]
**The problem**
I'm parsing a webpage that is using TeX input, and outputting HTML-CSS. Both subscripted and superscripted expressions are `<span class="msubsup"> `rather than either class="msub" or class="msup". I could have worked around this if the msubsup nodes were generated with all three "arguments", but only two are generated. This makes it impossible to semantically disambiguate weither to interpret the expression as being indexed or raised.

**Describe the solution you'd like**
In the input TeX source, x_i is used for subscript and x^y for superscript. I would prefer to have the option to have these rendered as msub and msup respectively.

**Describe alternatives you've considered**
Alternatively the "msubsup" output element should have all three arguments, whereby looking at which of the second and third argument can deduce weither it is subscripted, superscripted or both, which is the intended purpose of this tag.

**Additional context**
Example of a msubsup element that would allow for disabiguation:

```
<span class="msubsup">
    <span class="mi">c</span>
    <span class="mn"></span> <! -- empty second "argument" means no subscript -->
    <span class="mn">2</span>
</span>
```

and

```
<span class="msubsup">
    <span class="mi">m</span>
    <span class="mn">0</span>
    <span class="mn"></span> <! -- empty third "argument" means no superscript -->
</span>
```

at the moment both look like 
```
<span class="msubsup">
    <span class="mi">m</span>
    <span class="mn">0</span> <! -- is this a raised or indexed expression? -->
</span>
```

**Comment by dpvc** [comment]
You are correct that in v2, the class is listed as `msubsup` in all three cases.  You might consider upgrading to version 3, where the output is marked using separate `msup` and `msub` elements.

But it is not clear what you are trying to do, and there may be a better way.  If you are trying to reconstruct the MathML from the output, that is problematic in more ways than just this.  You would be better off either using the assistive MathML that is inserted for screen readers (unless it has been disabled on your site), or you could ask MathJax in the page to return the ElementJax for the math you are interested in and get the original form (TeX or MathML or AsciiMath) from that, or the internal MathML representation.  So parsing the page may not be needed.

If you must do that kind of parsing, version 3 would make that easier.  If you must stick with v2, you could use the following configuration:

``` html
<script type="text/x-mathjax-config">
MathJax.Hub.Register.StartupHook("HTML-CSS Jax Ready",function () {
  var MML = MathJax.ElementJax.mml;
  MML.msubsup.Augment({
    HTMLcreateSpan: function (span) {
      span = this.SUPER(arguments).HTMLcreateSpan.call(this, span);
      if (this.data[1] === null) {
        span.className = 'msup';
      } else if (this.data[2] === null) {
        span.className = 'msub';
      }
      return span;
    }
  });
});
</script>
```

to cause the class to be listed as `msup` or `msub` for the elements with only one script.

**Comment by ObscureScience** [comment]
Thank you very much. I'm doing this to a third party website, so I can only recommend that they upgrade to v3, but have no control over that.

I'm not converting to MathML per se, but pretty much the semantically equivalent. It's screen reader related. 
Your hook looks very promising and you have certainly given me a few leads to hit up in the documentation. Not least of which are the accessibility and/or assistive-mml extensions.
