### ISSUE TITLE
[SVG Output] Inline CSS

### ISSUE THREAD

**Issue by ShaMan123** [mathjax/MathJax#2696]
**Is your feature request related to a problem? Please describe.**
An option to have `css` inlined for each node with the relevant style would be good for node environments that don't handle `css` and/or don't support `<style>`.
Original issue: https://github.com/ShaMan123/react-native-math-view/issues/45

**Describe the solution you'd like**
An `inlineCSS: boolean` option for the `outputJax`

**Describe alternatives you've considered**
1. Currently I need to traverse the svg tree and apply css rules for edge cases such as described here: https://github.com/ShaMan123/react-native-math-view/issues/45#issuecomment-842883812
2. Add the feature `LiteAdaptor.getComputedStyle(element: LiteElement): Object`

**Additional context**
I use mathjax for my repo [react-native-math-view](https://github.com/ShaMan123/react-native-math-view) so I am facing major constraints due to the environment, mainly the absence of css and the ability to measure nodes.

**Comment by ShaMan123** [comment]
BTW I am willing to PR to add the feature `LiteAdaptor.getComputedStyle(element: LiteElement)` which will resolve this issue entirely.
Are you interested?

**Comment by dpvc** [comment]
Have you tried embedding the `<style>` tag within the SVG as provided by the [SVG specification](https://svgwg.org/svg2-draft/styling.html)?  In SVG2, this is apparently required to be supported by SVG user agents.  The SVG examples in the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository show how to do this.  E.g., [tex2svg](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2svg).  That might be the easiest solution.

I don't think `getComputedStyle()` is the way to go, here.  If you want to convert the CSS to element attributes, I'd say that it might be best to make a custom `renderAction` that takes the CSS stylesheet and applies it to the DOM tree for the MathItem in an efficient way (I haven't really thought out how that would be best handled, but it would need to involve being able to parse fairly complex css selectors).  This could be made into an extension for situations like yours.

**Comment by dpvc** [comment]
Actually, looking at the CSS in the `tex2svg` example, applying that CSS is pretty straight-forward.  So such an extension shouldn't be too hard to create.

**Comment by ShaMan123** [comment]
Thaks for your answer.
I tried embedding a style tag. It works for most environments.
I'll look at render actions.
Thanks

בתאריך יום ד׳, 19 במאי 2021, 17:32, מאת Davide P. Cervone ‏<
***@***.***>:
