### ISSUE TITLE
wrong sizing of \Vert with \left and \right

### ISSUE THREAD

**Issue by mbotsch** [mathjax/MathJax#2697]
### Issue Summary

Sizing `\Vert` with `\left` and `\right` does not work properly after switching to version 3.1.4. 

### Steps to Reproduce:

Try the following, e..g, on the demo page https://www.mathjax.org/#demo
```
$$\left\Vert V \right\Vert$$
```
Left and right Vert should be the same size, but the right one is smaller or (depending where this is in a complex equation) both Verts are too small. This used to work in version 3.1.2. In contrast, using `\vert` instead of `\Vert` works as expected.

### Technical details:

* MathJax Version: 3.1.4, SVG output
* Client OS: Mac OS X 10.15.7.
* Browser: latest Chrome, Firefox, Safari

**Comment by pkra** [comment]
Will be fixed via https://github.com/mathjax/MathJax-src/pull/700
