### ISSUE TITLE
Plain TeX `$$ . . . $$` for displayed equations is discouraged in LaTeX

### ISSUE THREAD

**Issue by heavywatal** [mathjax/MathJax#2698]
**Is your feature request related to a problem? Please describe.**
According to ["Short Math Guide for LaTeX"](https://mirror.ctan.org/info/short-math-guide) published by American Mathematical Society (AMS), using `$$ ... $$` for displayed equations is strongly discouraged. Although MathJax does not has to be consistent with AMS, it won't be very good idea to instruct beginners to get used to `$$ ... $$`.

**Describe the solution you'd like**
I suggest removing it from [the default set of delimiters of TeX input processor](http://docs.mathjax.org/en/latest/options/input/tex.html#tex-options), or at least displaying/documenting some warnings.

**Describe alternatives you've considered**

**Additional context**
> Using the plain TEX notation `$$ ... $$` for displayed equations is strongly discouraged. Although it is not expressly forbidden in LATEX, it is not documented anywhere in the LATEX book as being part of the LATEX command set, and it interferes with the proper operation of various features such as the `fleqn` option.

**Comment by dpvc** [comment]
Thank you for your suggestion.  We appreciate your interest in MathJax and its documentation.

There are several reasons, however, that we will not be making the requested change. 

First, MathJax is not just LaTeX, but includes Plain TeX features as well as LaTeX ones, including features that are deprecated in LaTeX; for example, we support both `\bf` and `\mathbf`, and both `\cases` and the `cases` environment . 

Second, changing this defaults would cause those pages that are currently using `$$...$$` to break, which is not something we want to do.  Even were we to make announcements about such a change, many people would not see them and their sites would stop working; they would be requires to update their configurations, which could involve hundreds of pages, or modifying plugins that they are using (many people use MathJax plugins and may not be able to change the configuration).  

The biggest issue, however, is that MathJax is used in settings where the LaTeX `\(...\)` and `\[...\]` are difficult (or sometime impossible) to use.  Many interactive sites use Markdown to compose their content, for example, and in Markdown the backslash already has a meaning, so one would need to use `\\(` and `\\)`, when that is possible.  Some Markdown MathJax plugins that prevent the mathematics from being modified by Markdown, but they typically use the dollar delimiters.  These settings make using `\(...\)` and `\[...\]` difficult.

For these reasons, we are not planning to change the default delimiter list or issuing warning for using these delimiters.
