### ISSUE TITLE
Characters omitted from chrome 

### ISSUE THREAD

**Issue by dominicwojciechowski86** [mathjax/MathJax#2700]
### Issue Summary

Hello, 

In the last few hours Chrome has stopped rendering some characters  on Chrome (Version 91.0.4472.77 MJ 3.0.1, Windows 10 ). Intriguingly, when I right click on the output to look at Mathml code, it contains the characters that have been omitted from the screen. No error messages display in the console.

It works fine on IE and, up until today, was working fine on Chrome.
![image](https://user-images.githubusercontent.com/27436678/120548811-b1578a80-c3ea-11eb-869f-4804ec142d0f.png)
What it looks like on IE.
![image](https://user-images.githubusercontent.com/27436678/120549009-ecf25480-c3ea-11eb-8118-a0dabbaf07f6.png)
What it looks like on Chrome.
![image](https://user-images.githubusercontent.com/27436678/120550451-c9c8a480-c3ec-11eb-990e-e38e45e6d56c.png)
Showing the correct MathML code for the invisible brackets.
Any help would be much appreciated,

Dom

**Comment by dominicwojciechowski86** [comment]
'''
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <link rel="stylesheet" href="fontsizes.css">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
    <script>
    MathJax = {
    startup: {
    typeset: false
  }
};

</script>

<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>
    <script>

    function makerange(a,b) {
            var integer= Math.floor(Math.random() * a) + b;
            return integer;
    }

    function makeneg(a) {
            if (Math.random()<0.5){
                a=a*-1
            }
        return(a)
    }
function one(a) {
        if (Math.abs(a)==1||a==0){
            return("")
        }
        else{return(Math.abs(a))}
    }

    function chooseop(a){
            if (a<0){
                return("-")
            }
            else if (a==0){
                return("")
            }
            else { return"+"}
    }

       window.onload= function() {


               var a=makerange(5,1)
               var b=makeneg(makerange(5,1))
               var c=makeneg(makerange(5,1))
               var d=1
               var e=makerange(2,2)
               var f=makerange(2,2)
               var g=[d,a]
               var h=[e,b]
               var i=[f,c]
               console.log(g,h,i)
               var j=d*e*f
               var k=d*e*c + f*(d*b+a*e)
               var l=c*(d*b+a*e)+(f*a*b)
               var m=a*b*c
               console.log(j)
               if (g[0]==h[0] && g[1]==h[1] && g[0]==i[0] &&  g[1]==i[1]){
                   var q1='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(d)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(a)+'</mo>\n' +
                       '  <mn>'+Math.abs(a)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mo stretchy="false">)</mo>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>3</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '</math>'
               }
               else if(g[0]==h[0] && g[1]==h[1]){
                   var q1='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(d)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(a)+'</mo>\n' +
                       '  <mn>'+Math.abs(a)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mo stretchy="false">)</mo>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>2</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(f)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(c)+'</mo>\n' +
                       '  <mn>'+Math.abs(c)+'</mn>\n' +
                       '  <mo stretchy="false">)</mo>\n' +
                       '</math>'
               }
               else if(h[0]==i[0]&&h[1]==i[1]){
                   var q1='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(d)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(a)+'</mo>\n' +
                       '  <mn>'+Math.abs(a)+'</mn>\n' +
                       '  <mo stretchy="false">)</mo>\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(e)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(b)+'</mo>\n' +
                       '  <mn>'+Math.abs(b)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mo stretchy="false">)</mo>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>2</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +

                       '</math>'
               }
               else if(g[0]==i[0]&&g[1]==i[1]){
                   var q1='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(d)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(a)+'</mo>\n' +
                       '  <mn>'+Math.abs(a)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mo stretchy="false">)</mo>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>2</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(e)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(b)+'</mo>\n' +
                       '  <mn>'+Math.abs(b)+'</mn>\n' +
                       '  <mo stretchy="false">)</mo>\n' +
                       '</math>'

               }
              else {
                   var q1='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(d)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(a)+'</mo>\n' +
                       '  <mn>'+Math.abs(a)+'</mn>\n' +
                       '    <mo stretchy="false">)</mo>\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(e)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(b)+'</mo>\n' +
                       '  <mn>'+Math.abs(b)+'</mn>\n' +
                       '  <mo stretchy="false">)</mo>\n' +
                       '  <mo stretchy="false">(</mo>\n' +
                       '  <mn>'+one(f)+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(c)+'</mo>\n' +
                       '  <mn>'+Math.abs(c)+'</mn>\n' +
                       '  <mo stretchy="false">)</mo>\n' +
                       '</math>'
               }
              if (k==0&&l==0) {
                   var r='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mn>'+one(j)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>3</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo>'+chooseop(m)+'</mo>\n' +
                       '  <mn>'+Math.abs(m)+'</mn>\n' +
                       '</math>'
              }
              else if (k==0){
                   var r='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mn>'+one(j)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>3</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +

                       '  <mo>'+chooseop(l)+'</mo>\n' +
                       '  <mn>'+one(Math.abs(l))+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(m)+'</mo>\n' +
                       '  <mn>'+Math.abs(m)+'</mn>\n' +
                       '</math>'
              }
              else  if (l==0){
                  var r='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mn>'+one(j)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>3</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo>'+chooseop(k)+'</mo>\n' +
                       '  <mn>'+one(Math.abs(k))+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>2</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo>'+chooseop(m)+'</mo>\n' +
                       '  <mn>'+Math.abs(m)+'</mn>\n' +
                       '</math>'
              }
              else{
                   var r='<math xmlns="http://www.w3.org/1998/Math/MathML">\n' +
                       '  <mn>'+one(j)+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>3</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo>'+chooseop(k)+'</mo>\n' +
                       '  <mn>'+one(Math.abs(k))+'</mn>\n' +
                       '  <msup>\n' +
                       '    <mi>x</mi>\n' +
                       '    <mrow class="MJX-TeXAtom-ORD">\n' +
                       '      <mn>2</mn>\n' +
                       '    </mrow>\n' +
                       '  </msup>\n' +
                       '  <mo>'+chooseop(l)+'</mo>\n' +
                       '  <mn>'+one(Math.abs(l))+'</mn>\n' +
                       '  <mi>x</mi>\n' +
                       '  <mo>'+chooseop(m)+'</mo>\n' +
                       '  <mn>'+Math.abs(m)+'</mn>\n' +
                       '</math>'
              }
           document.getElementById("var1").innerHTML = q1;
           document.getElementById("var2").innerHTML = r;


           MathJax.startup.promise.then(function () {
          MathJax.typesetPromise().catch(function (err) {console.log(err)});

       })}


    </script>

    <meta charset="UTF-8">
    <title>Title</title>


</head>
<body>
<div id="question">
    <p> Expand and simplify:</p> <span id="var1"></span>
</div>

<div id="answer">
<p id="var2"></p>


</div>
'''

**Comment by dominicwojciechowski86** [comment]
'''
    <p> Expand and simplify:</p> <span id="var1"></span>





</div>

<div id="answer">
<p id="var2"></p>

</div>
'''

**Comment by dominicwojciechowski86** [comment]
Every time I try to paste my code, Github leaves some out. Here's a screenshot of the final bit of code:
![image](https://user-images.githubusercontent.com/27436678/120552199-dbab4700-c3ee-11eb-81b7-4ec94e0f2856.png)

**Comment by dpvc** [comment]
It looks like the latest release of Chrome (91.0) has a rendering problem with MathJax's fonts.  I will have to look into it further, but for now, you might want to switch to SVG output rather than CHTML output, as that renders properly.

**Comment by dominicwojciechowski86** [comment]
Thanks for your help and all your work on MJ, much appreciated.

**Comment by dpvc** [comment]
I only just noticed that you are using version 3.0.1 of MathJax.  The current version is 3.1.4, and switching to that version makes your test page work for me (in CHTML).  So perhaps upgrading to the current version is the better solution.

**Comment by acanas** [comment]
I have verified that it also does not work with version 3.1.4 on Chromium 91.0.4472.77 (Official Build) snap (64 bit). With some zoom sizes it works, with others it doesn't.
