### ISSUE TITLE
overline does not show up for chtml output

### ISSUE THREAD

**Issue by jirilebl** [mathjax/MathJax#2701]
### Issue Summary

Using https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js (using chrome 91 on linux), "\overline" will just no show up (there is no line). 

See https://www.jirka.org/badmj.html

However, moving to https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js fixes the problem

### Steps to Reproduce:

1. Use tex-chtml.js
2. Add \(\overline{A}\)
3. See A without an overline.
4. Switch to tex-svg.js
5. See A with an overline.

### Technical details:

* MathJax Version: 3.1.4
* Client OS: Linux PopOS 20.10
* Browser: Chrome 91.0.4472.77

### Supporting information:

 * Example: https://www.jirka.org/badmj.html
 * No errors on the console

**Comment by dpvc** [comment]
I'm not able to reproduce the issue (In MacOS with the same Chrome version).  The line is there, though a bit thin.  Does it change if you zoom the window?

Also, try adding

``` css
mjx-stretchy-h.mjx-c2013 mjx-ext mjx-c::before {
  padding-top: .3em ! important
}
```

to the CSS for the page and see if that helps.

**Comment by jirilebl** [comment]
Interesting, when zooming, the line is there for every zoom > 100%, and for some smaller zooms like 75%, 80%, 90%, though it is very faint in 75% and 90%, while clear at 80%.  Also for large zooms like 250% or 150% the line is thin, but it is thicker in 125% and 175%, etc.  It jumps around.

The extra css does not help for 100% zoom, it still doesn't show up, but it does make the line thicker at some zooms.

I wonder if it is just getting cut off, that is, chrome might be cropping or overwriting with whitespace or something.  I mean how else would it be different widths at different zooms otherwise.  I tried playing around with the css, and while I couldn't really "fix" it, setting line-height on mjx-math to 2px instead of 0, made the overline appear, so that's why I'm thinking it is somehow getting cropped out.

Definitely chrome issue as I've tried firefox and the line is there.

Here are some screenshots.  The first is at 100%, the second at 200% (note that the line at 200% is clearly not the width that it ought to be).

![Screenshot-20210609104512-328x104](https://user-images.githubusercontent.com/3384911/121403751-15f57680-c910-11eb-9c52-84e32c9afb35.png)
![Screenshot-20210609104546-612x157](https://user-images.githubusercontent.com/3384911/121403765-1aba2a80-c910-11eb-91b4-ec753220a048.png)

**Comment by Alex-Jordan** [comment]
For me on MacOS with Chrome 91, the line on jiri's example disappears at zoom levels 75%, 50%, and 25%. However at 100%, it is present.

**Comment by rbeezer** [comment]
Confirming zoom levels from 30% to 300% all show an overline just fine in Firefox 88.0.1 on Ubuntu 20.04, using a test example of my own creation.

**Comment by dpvc** [comment]
@Alex-Jordan, thanks for checking this out.  Were your results with our without the extra CSS that I suggested?

@jirilebl, if you change the CSS to 

``` css
mjx-stretchy-h.mjx-c2013 mjx-ext mjx-c::before {
  padding-top: .5em ! important;
  color: red;
}
```

Does that help?  I've added color so that you can tell if the CSS is actually being applied (when you zoom to where it is visible).

> I wonder if it is just getting cut off, that is, chrome might be cropping

Yes, that is certainly what is happening.  The character is in the DOM, but Chrome is clipping it.

@rbeezer, thanks for checking Firefox.  I'm pretty sure it is a Chrome issue (with round off; historically Chrome has had a lot of these).  With a thin horizontal line, if it is positioned slightly off vertically, it can fall outside the bounding box that MathJax has set up for it.  Although MathJax doesn't request clipping, it seems that that might be happening anyway.

**Comment by Alex-Jordan** [comment]
@dpvc I was just looking at Jiri's example as it was. So I think without the added CSS.

**Comment by jirilebl** [comment]
@dpvc So interestingly, adding the color: red does not seem to have any effect.

@Alex-Jordan By the way, the example has this style there but it's commented out.  I added it and enabled it just to test, then disabled again.

**Comment by dpvc** [comment]
> interestingly, adding the color: red does not seem to have any effect.

You have left out the semicolon after "important", so the two rules run together and neither take effect.  When I save your page locally and add the semicolon, I get the overline in red, and visible at all zoom levels.

**Comment by jirilebl** [comment]
Doh! :)

OK, so the effect is that the bar, when visible, is red, but otherwise still not visible at 100% zoom.

**Comment by dpvc** [comment]
> otherwise still not visible at 100% zoom

Did you try with .5em instead of .3em?  That is large enough that if it is going to show, it should do so.  If that doesn't work try 1em just to be absolutely sure.

**Comment by dpvc** [comment]
Also, can you try turning off hardware acceleration and see if that helps? (Search for "acceleration" in the preferences panel.)

**Comment by jirilebl** [comment]
Making it 0.5em does make it show up even at 100%.  Turning off acceleration doesn't seem to change anything.

**Comment by dpvc** [comment]
Thanks for checking; I appreciate the additional information.  I will consider what the best course is to resolve the problem.

**Comment by dpvc** [comment]
@jirilebl, here's something else to try.  Can you peplace the CSS that I suggested above with

``` css
mjx-stretchy-h > mjx-ext {
  overflow: clip visible ! important;
}
```

and see if that helps?

**Comment by jirilebl** [comment]
Doesn't help.

**Comment by dpvc** [comment]
@jirilebl, note that the selector has changed.  You have left the old selector, which won't help, as you say.  You need to check the whole selector.  Can you give that another try?  (Sorry to keep pestering you about it.)

**Comment by jirilebl** [comment]
Ahhh!  Sorry about that, should have just cut and pasted the whole thing.  I just did it quickly while waiting for my student on a zoom call :)

Anyway.  Yay!  It works.  With that added I see the bar correctly and consistently in all zoom levels.

**Comment by dpvc** [comment]
@jirilebl, thanks for the confirmation.  I think that is the solution I will go with.

**Comment by IMACS-Iain** [comment]
This is still an issue in MathJax 3.2.0:

1) on Firefox in Windows 10 v20H2 and v21H1, underline and overline not visible at 90% or 120%;
2) on Firefox on Ubuntu 21.10, underline and overline not visible at 80%, 100% (but visible at 110+%)

**Comment by felixhekhorn** [comment]
Is there by chance any update on this issue?

I can confirm that for MathJax 3.2.0 and FF98 on debian unstable the overline is *not* visible at 60%, 80%, 100%

**Comment by dpvc** [comment]
@CCXXXI, This will break lots of other stretchy characters, like over- and under-braces, for example.  I would not recommend doing that.

**Comment by CCXXXI** [comment]
@dpvc Is there a CSS selector that selects only `\overline`?

**Comment by dpvc** [comment]
Yes, `mjx-stretchy-h.mjx-c2013` will get you just the various over- and underlines, but note that adding a border will change the height of the result, and so that may throw off MathJax's layout in other ways.  Plus the fact that when the usual overline does show, this will make for an extra thick overline.  I would be cautious about doing this.

**Comment by FeldrinH** [comment]
> We are working on an update that will include major changes to fonts. I'm hoping the new fonts will perform better in Firefox. The current ones were created via mftrace that computes paths by tracing large bitmapped version of the metafont output from TeX twelve years ago, when the available tools were not as good. Those fonts is not ideal, and they have other problems as well. Replacing the old fonts with newer ones that weren't created in that way should (fingers crossed) resolve those issues.

Is there any update on this. The issue with overlines seems to still affect latest version of Firefox with the latest version of MathJax.

**Comment by dpvc** [comment]
> Is there any update on this?

unfortunately, things have taken much longer than expected.  We have been working for the past several months on some significant issues with the assistive technology support that have required some major revisions internally.  We are over the biggest hump with that, thankfully, and are closing in on what I hope will be the final beta release before the official v4 release.  So it is coming "real soon now".  I know it has been frustratingly slow, but this is a major undertaking.
