### ISSUE TITLE
Add suppor for `\textcircled` command

### ISSUE THREAD

**Issue by FuDesign2008** [mathjax/MathJax#2702]
**Is your feature request related to a problem? Please describe.**
MathJax can not render content that contains `\textcircled` command like: 

```html
利用加减消元法解方程组 $$ \begin{cases} 2x + 5y = -10 , \textcircled {  1  } \\ 5x - 3y = 6 , \textcircled {  2  } \end{cases} $$ 下列做法正确的是(	)
<br/>
A.要消去y，可以将  $\textcircled {  1  } \times 5 + \textcircled {  2  } \times 2$ <br/>
B.要消去x，可以将  $\textcircled {  1  } \times 3 + \textcircled {  2 } \times ( - 5 ) $ <br/>
C.要消去y，可以将  $\textcircled {  1  } \times 5 + \textcircled {  2  } \times 3 $ <br/>
D.要消去x，可以将  $\textcircled {  1  } \times ( - 5 ) + \textcircled {  2  } \times 2 $ <br/>


```
Open https://www.mathjax.org/#demo and past the content above into live demo: 
<img width="1148" alt="WX20210610-173331@2x" src="https://user-images.githubusercontent.com/908026/121501656-03636600-ca12-11eb-98b2-dd97ba7795c5.png">

**Describe the solution you'd like**
Add support for `\textcircled` command

**Describe alternatives you've considered**

**Additional context**
KaTex support  `\textcircled` , see https://github.com/KaTeX/KaTeX/pull/1073

Open https://katex.org/ and paste the following content into editor: 

```text
利用加减消元法解方程组  \begin{cases} 2x + 5y = -10 , \textcircled {  1  } \\ 5x - 3y = 6 , \textcircled {  2  } \end{cases}  下列做法正确的是(	)
A.要消去y，可以将  \textcircled {  1  } \times 5 + \textcircled {  2  } \times 2 
B.要消去x，可以将  \textcircled {  1  } \times 3 + \textcircled {  2 } \times ( - 5 )  
C.要消去y，可以将  \textcircled {  1  } \times 5 + \textcircled {  2  } \times 3  
D.要消去x，可以将  \textcircled {  1  } \times ( - 5 ) + \textcircled {  2  } \times 2  
```

The preview will be shown like: 

<img width="800" alt="WX20210610-173755@2x" src="https://user-images.githubusercontent.com/908026/121502332-a61be480-ca12-11eb-8d22-774f68b00abd.png">

**Comment by pkra** [comment]
`\enclose{circle}{#1}` seems a decent approximation.

**Comment by dpvc** [comment]
I was going to suggest something similar to Peter's comment, and will do so below.

I suspect that KaTeX's version is something similar to

``` latex
\newcommand{\textcircled}[1]{\bigcirc\llap{\text{#1}\kern .25em}}
```

but (as in your diagram), the circle is placed too low, so you might prefer

``` latex
\newcommand{\textcircled}[1]{\raise.65em\bigcirc\llap{\text{#1}\kern .25em}}
```

This produces:

<img width="50" alt="bigcirc" src="https://user-images.githubusercontent.com/432782/121515217-f1a2a400-c9ba-11eb-879c-9d251bdd2e9a.png">

You could make the circle larger via something like:

``` latex
\newcommand{\textcircled}[1]{{\large\raise .02em\bigcirc}\llap{\text{#1}\kern .335em}}
```

instead.

Peter's use of `\enclose` may be a better choice, but it may generate an oval rather than a circle.  You could use

``` latex
\newcommand{\textcircled}[1]{\enclose{circle}{\kern.1em\text{#1}\kern.1em}}
```

which would add a little space around the number, making the enclosure more circular.  Since all the numbers have the same width, the amount of extra space should be the same for all of them.  This produces:

<img width="61" alt="enclose" src="https://user-images.githubusercontent.com/432782/121515010-ad170880-c9ba-11eb-84e6-069ba8ccac77.png">

Finally, you can configure MathJax to predefine these using the [configmacros](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html) package.

**Comment by FuDesign2008** [comment]
> I was going to suggest something similar to Peter's comment, and will do so below.
> 
> I suspect that KaTeX's version is something similar to
> 
> ```
> \newcommand{\textcircled}[1]{\bigcirc\llap{\text{#1}\kern .25em}}
> ```
> 
> but (as in your diagram), the circle is placed too low, so you might prefer
> 
> ```
> \newcommand{\textcircled}[1]{\raise.65em\bigcirc\llap{\text{#1}\kern .25em}}
> ```
> 
> This produces:
> 
> <img alt="bigcirc" width="50" src="https://user-images.githubusercontent.com/432782/121515217-f1a2a400-c9ba-11eb-879c-9d251bdd2e9a.png">
> 
> You could make the circle larger via something like:
> 
> ```
> \newcommand{\textcircled}[1]{{\large\raise .02em\bigcirc}\llap{\text{#1}\kern .335em}}
> ```
> 
> instead.
> 
> Peter's use of `\enclose` may be a better choice, but it may generate an oval rather than a circle. You could use
> 
> ```
> \newcommand{\textcircled}[1]{\enclose{circle}{\kern.1em\text{#1}\kern.1em}}
> ```
> 
> which would add a little space around the number, making the enclosure more circular. Since all the numbers have the same width, the amount of extra space should be the same for all of them. This produces:
> 
> <img alt="enclose" width="61" src="https://user-images.githubusercontent.com/432782/121515010-ad170880-c9ba-11eb-84e6-069ba8ccac77.png">
> 
> Finally, you can configure MathJax to predefine these using the [configmacros](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html) package.

Thank you a lot. I will take a try.

**Comment by FuDesign2008** [comment]
In my projects, MathJax 2.7.x is used, and the following code is added  for support `textcircled`: 

``` javascript 
window.MathJax.Hub.Config({
        TeX: {
          // 1. add enclose.js for support `\enclose` command 
          //  @see https://docs.mathjax.org/en/v2.7-latest/tex.html#enclose
          extensions: ['enclose.js'],
          Macros: {
            // 2. define new macro
            // @see https://docs.mathjax.org/en/v2.7-latest/tex.html#defining-tex-macros
            textcircled: ['\\enclose{circle}{#1}', 1],
          },
        },
      })
 window.MathJax.Hub.Configured()

```
