### ISSUE TITLE
Displaying LaTex between [math] [/math]

### ISSUE THREAD

**Issue by Avv22** [mathjax/MathJax#2707]
Hello,

My browser does not render LaTex equations between [math] [/math]. Can you please help me with that? I enabled java script on my browser. 

### Technical details:

* MathJax Version: 2.3 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Windows 10
* Browser: Chrome 29.0.1547.57

**Comment by dpvc** [comment]
The default delimiters for in-line math are `\(...\)` and for display math are `\[...\]` or `$$...$$`.  You do not give any information about your configuration or the environment in which you are using MathJax, so it is not easy to tell you what you need to do to adjust this.  But the basic configuration information is in the [documentation](https://docs.mathjax.org/en/latest/web/configuration.html).  The first code block there gives a configuration that adds inline delimiters, so you could use that idea to add `[math]...[/math]` as delimiters.  That section also tells you how to load MathJax in your page, in case you aren't doing that.  If you are really using version 2.3 (as indicated in your report), then you may want to update to a more current version (at least to the highest v2 version, which is 2.7.9, if you can't move to version 3).

In general, this issue tracker is for reporting bugs in MathJax, not asking questions.  It is better to do that in the [MathJax User's Forum](https://groups.google.com/g/mathjax-users) where more people will see your question and may respond.
