### ISSUE TITLE
Better interpretation of Unicode

### ISSUE THREAD

**Issue by JeppeKlitgaard** [mathjax/MathJax#2708]
I have recently started writing mainly in Unicode using a text expander, which makes reading the source of my math a lot easier and more manageable.

The output almost always looks good in MathJax, though in places the output won't be quite the same.

I don't know how the inner workings of MathJax are set up to deal with this, but perhaps greater support for 'translating' Unicode symbols into the MathJax versions would be a good feature to have.

Example input:
![image](https://user-images.githubusercontent.com/1814611/121925018-c57d7f00-cd3c-11eb-8d5d-1df7c7e62f3d.png)

```latex
% As a code block
$$
\pdv{u}{t} = λ ∇²u
$$

$$
\pdv{u}{t} = \lambda \laplacian u
$$

$$∭_{-∞}^{+∞} α β γ \d V = ∯_{∂V} θωρτ \d S$$

$$\iiint_{-infty}^{+\infty} \alpha \beta \gamma \d V = \oiint_{\partial V} \theta \omega \rho \tau \d S$$
```

Example output:
![image](https://user-images.githubusercontent.com/1814611/121924978-ba2a5380-cd3c-11eb-9300-0aaeb9cd9be4.png)

(The lack of `\oiint` I believe is a separate issue due to be fixed by the 3.2 font support) 

I think the motivation behind this is clear: the Unicode source is far more readable and given the right editor or text expander setup, it could be the preferred (or at least a very viable) option for writing math at some point in the future.

Ideally `α` would be understood by MathJax to be the same as the symbol `\alpha`, etc.

---

I really hope this is something that could be supported by MathJax in the future, though I understand that it might be considered niche use currently.

---

Possibly relevant other issues:
- #920
- #1994 
- #1203 
- #2004

**Comment by dpvc** [comment]
As it happens, the upcoming v3.2.0 will include most of what you are asking for.  The approach to handling non-ASCII unicode characters has been updated to be more granular in how it decides what type of MathML node to use.  In the past, nearly all unicode characters where placed in `<mo>` elements, and that means that they would be displayed in an upright font.  That is the reason your Greek letters are upright.  In v3.2, MathJax will choose an `<mi>` for alphabetic characters (like the Greek letters, accented Latin characters, Cyrillic characters, etc.), and `<mo>` for symbols (and `<mn>` for numbers, and so on).  This should make your input work better.

The superscript 2, however, is what MathML calls a "pseudo-script", which is already raised and in a smaller size.  MathJax will render it as a regular character, but it will not be quite the same position or size as `^2` would produce.  You can use a TeX input jax pre-filter to convert those to actual TeX scripts if you want.  Something like

``` javascript
MathJax = {
  startup: {
    ready() {
      //
      // Do usual setup
      //
      MathJax.startup.defaultReady();
      //
      // The pseudoscript numbers 0 through 9, and a pattern for plus-or-minus a number
      //
      const scripts = '\u2070\u00B9\u00B2\u00B3\u2074\u2075\u2076\u2077\u2078\u2079';
      const scriptRE = /([\u207A\u207B])?([\u2070\u00B9\u00B2\u00B3\u2074-\u2079]+)/g;
      //
      //  Add a TeX prefilter to convert pseudoscript numbers to actual superscripts
      //
      MathJax.startup.document.inputJax[0].preFilters.add((data) => {
        data.math.math = data.math.math.replace(scriptRE, (match, pm, n) => {
          const N = n.split('').map(c => scripts.indexOf(c));  // convert digits
          pm === '\u207A' && N.unshift('+');     // add plus, if given
          pm === '\u207B' && N.unshift('-');     // add minus, if given
          return '^{' + N.join('') + '}';        // make it an actual power
        });
      });
    }
  }
};
```

should handle most cases.  If you are going to do subscripts that way as well, you can do a similar thing for those characters, which are a U+2080 to U+2089 with plus and minus as U+208A and U+208B.  There are a few other script characters (like `=` and parentheses), and you could handle those as well with a little more care.

You are correct about three of the issues you link to being resolved by this as well.  I will need to close those out when v3.2 is released (should be in the next few days).

**Comment by JeppeKlitgaard** [comment]
Thank you so much for the detailed response and immensely helpful response! Truly going above and beyond!

I am super excited to see what 3.2 will look like and all the improvements it will bring!

**Comment by dpvc** [comment]
You're most welcome!
