### ISSUE TITLE
[TeX] \overset not preventing movable limits 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2709]
This is basically https://github.com/mathjax/MathJax/issues/1929, but for v3.

On mathjax.org#demo (and also with the develop branch), `\( \overset{a}{\prod }\)` will render the `a` as a superscript (which it shouldn't).

**Comment by pkra** [comment]
It seems like the moveable limits check in 

https://github.com/mathjax/MathJax-src/blob/5650c74c4d1102e96ae081bd76c90b87c617394f/ts/input/tex/base/BaseMethods.ts#L619-L633

doesn't quite work. Replacing it with the one from underover seems to do the job.

**Comment by dpvc** [comment]
Thanks for the report.  It looks like the condition for `\overset` is not the same as for `\underset` or `\overunderset`, and they differ from the one used in the `ParserUtil.underOver()` method.  unfortunately, your suggested solution isn't quite right, either.  For one thing, you have left off the check for the `movablelimits` property on the node itself (which is important), and the check you are doing assumes the base is an `mo` element, which it may not be here.

I will push a branch that makes a utility function for making the check, and use it in all four places.
