### ISSUE TITLE
consistent style attribute serialization across adaptors

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2726]
This is a bit of a niche question but perhaps you'll consider it.

I'm trying to switch from the jsdomAdaptor to the liteAdaptor and I've noticed a difference in style attribute serialization: the liteAdaptor does not add a closing `;` to the svg element's style attribute. That's obviously not an issue but adds a lot of (commit) noise when switching.

Since it doesn't match the jsdomAdaptor or the output in a browser DOM, I'm wondering if you'd be amenable to changing it.

If you consider it, I have a follow up question. I thought the right place would be

https://github.com/mathjax/MathJax-src/blob/41565a97529c8de57cb170e6a67baf311e61de13/ts/util/Styles.ts#L396-L404

but this introduced `;` in style attributes where I don't see them in either jsdomAdaptor or browser DOM (e.g., on g's for text elements).

An alternative that (from a quick test) seems to match jsdom and browser behavior would be to add `;` to  

https://github.com/mathjax/MathJax-src/blob/41565a97529c8de57cb170e6a67baf311e61de13/ts/adaptors/liteAdaptor.ts#L556-L562

but that seems a bit wrong.

Feel free to just close.

**Comment by dpvc** [comment]
I think you have the right location in the first link.  I would suggest

``` javascript
  public get cssText(): string {
    const styles = [] as string[];
    for (const name of Object.keys(this.styles)) {
      const parent = this.parentName(name);
      if (!this.styles[parent]) {
        styles.push(name + ': ' + this.styles[name] + ';');
      }
    }
    return styles.join(' ');
  }
```

See if that works, and we can include it in the next release.

**Comment by pkra** [comment]
> See if that works, and we can include it in the next release.

Yes, that's what I'd tried. As I wrote, this adds semicolons where neither jsdom nor DOM adaptors seem to add them. After a slightly more thorough check, that only seem to happen with `style="font-family: serif"` in error elements, so that's looks good.
