### ISSUE TITLE
Issues with mathvariant="bold-italic"

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2727]
### Issue Summary

We have noticed issues related to characters set to mathvariant="bold-italic", and we were wondering if there's anything we could do to improve this:

1.  Bold-italic looks odd (not bold enough, too slanted, smaller):

``` xml
<m:mi mathvariant="normal">H</m:mi><m:mi mathvariant="bold">H</m:mi><m:mi mathvariant="bold-italic">H</m:mi><m:mi>H</m:mi>
```

MathJax:
![image](https://user-images.githubusercontent.com/82107944/123998177-3b215600-d99f-11eb-9e45-0cd7ed21af28.png)

PDF for comparison:
![image](https://user-images.githubusercontent.com/82107944/123998244-4a080880-d99f-11eb-94b8-524350eab675.png)

2.  We have seen crashing between bold-italic bases and superscripts:

``` xml
<m:msup><m:mi mathvariant="bold-italic">H</m:mi><m:mo>&#x2032;</m:mo></m:msup>
```

![image](https://user-images.githubusercontent.com/82107944/123998463-83d90f00-d99f-11eb-97fd-17f27ea21aa4.png)

Bold and italic shown for comparison:

``` xml
<m:msup><m:mi mathvariant="bold">H</m:mi><m:mo>&#x2032;</m:mo></m:msup>
```

![image](https://user-images.githubusercontent.com/82107944/123998515-8e93a400-d99f-11eb-8730-f8225b271019.png)

``` xml
<m:msup><m:mi>H</m:mi><m:mo>&#x2032;</m:mo></m:msup>
```

![image](https://user-images.githubusercontent.com/82107944/123998565-981d0c00-d99f-11eb-8a7f-8c339b2de3ae.png)

Another example:

``` xml
<m:msup><m:mi mathvariant="normal">H</m:mi><m:mn>2</m:mn></m:msup><m:msup><m:mi mathvariant="bold">H</m:mi><m:mn>2</m:mn></m:msup><m:msup><m:mi mathvariant="bold-italic">H</m:mi><m:mn>2</m:mn></m:msup><m:msup><m:mi>H</m:mi><m:mn>2</m:mn></m:msup>
```

![image](https://user-images.githubusercontent.com/82107944/123998706-be42ac00-d99f-11eb-9819-b4c62b247f32.png)

3.  Accents are much farther away from a bold-italic base character than normal/italic/bold base characters:

``` xml
       <mover>
          <mi mathvariant="normal">x</mi>
          <mo accent="true" stretchy="false">^</mo>
        </mover>
        <mspace width=".25em" />
        <mover>
          <mi>x</mi>
          <mo accent="true" stretchy="false">^</mo>
        </mover>
        <mspace width=".25em" />
        <mover>
          <mi mathvariant="bold">x</mi>
          <mo accent="true" stretchy="false">^</mo>
        </mover>
        <mspace width=".25em" />
        <mover>
          <mi mathvariant="bold-italic">x</mi>
          <mo accent="true" stretchy="false">^</mo>
        </mover>
```

![image](https://user-images.githubusercontent.com/82107944/123998928-f518c200-d99f-11eb-89c6-172acc054622.png)

### Technical details:

MathJax Version: master - latest commit: MathJax.js v2.7.5
Client OS: Windows
Browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Renderer: HTML-CSS

**Comment by dpvc** [comment]
You should update to the latest version of MathJax (2.7.9).  That should resolve the issue for you.
