### ISSUE TITLE
Common HTML is having stacking problem

### ISSUE THREAD

**Issue by Oymate** [mathjax/MathJax#2734]
### Issue Summary
Using this site: https://www.mathjax.org/#samples
![common](https://user-images.githubusercontent.com/50857856/124382990-00475700-dcec-11eb-83ff-440427f4fe09.png)
![svg](https://user-images.githubusercontent.com/50857856/124382994-03424780-dcec-11eb-8dc1-b262bda42ff6.png)

### Steps to Reproduce:
Just go to the page and render with Firefox(X11)

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?
Wasn't mathML supported? If not maybe keep SVG the default
### Technical details:

* MathJax Version: 3.2.0
* Client OS: Ubuntu 20.10 based
* Browser: Firefox 89.0.2

### Supporting information:

Console:
```Cookie “” has been rejected as third-party. polyfill.min.js
Legacy Google Analytics is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1487072 for details. sandbox eval code:1:9
Cookie “” has been rejected as third-party. tex-mml-chtml.js
Cookie “” has been rejected as third-party. asciimath.js
Cookie “” has been rejected as third-party. svg.js
Cookie “” has been rejected as third-party.```

**Comment by dpvc** [comment]
Your first image indicates that the MathJax fonts are not being used, and that is the reason that the placement is not correct. Do you have page-specifidedfonts disabled?  (There is a preference for that in the advanced font settings.)

**Comment by Oymate** [comment]
Are the fonts 3rd party? Otherwise they should load

**Comment by dpvc** [comment]
The fonts will come from the same server that MathJax does.  Usually that is not the same origin as the page.  In any case, if the browser setting is set to not allow the page to specify its own fonts, then it doesn't matter.  Have you checked that setting in your browser?  Or do you have a plug-in that might be preventing the fonts from being loaded?

The issue is that the fonts are not loading for you; the question is why not?  The browser setting, or a plugin that restricts loading external resources may be at fault.

**Comment by Oymate** [comment]
There might be two reason
1. Firefox(nowadays even chrome) blocks 3rd party cookies
2. Ublock origin blocks them.(more likely) Could you try with ublock installed?

**Comment by dpvc** [comment]
Mathjax v3 does not use cookies (though www.mathjax.org does still have them from GoogleAnalytics).

I trued Ublock Origin, and the site still displayed fine for me in CommonHTML mode.  Even with font blocking turned on.

**Comment by Oymate** [comment]
Ok, so I used a setting in my browser that disabled font from websites and used local fonts instead. Is that considered a bug or not?

**Comment by dpvc** [comment]
> In FF>Settings> Fonts> Advanced>Turn off website fonts

That is the setting I asked you about initially, and was what I suspected was the source of the issue.

> Is that considered a bug or not?

No, if you disable page-specified fonts, MathJax can not set the fonts it needs to display the math.  There is nothing MathJax can do about that if you specifically disallow it.  That is not a bug in MathJax, it is a decision you have made as a reader, and it means CommonHTML mode will not work for you.  You can switch to SVG output, as that doesn't use remote fonts, but that is something you will have to do when you first visit a site that uses MathJax.

**Comment by Oymate** [comment]
@dpvc is it possible to detect if any website font is rejected/unused and switch to svg?

**Comment by dpvc** [comment]
Font detection is possible (v2 HTML-CSS output used it), but it is very fragile.  We dropped it for later output renderers as it just was not as reliable as we needed it to be, and it was a maintenance headache.

There are some proposals for browser support for font APIs, but I don't think any are currently implemented.

**Comment by Oymate** [comment]
Well, thanks for your help. :)
