### ISSUE TITLE
Why MathJax can't reset itself after crash?

### ISSUE THREAD

**Issue by adamma1024** [mathjax/MathJax#2737]
Every time MathJax crashed after accept some strange char , I had to reset it through 

```
MathJax.texReset();
MathJax.typesetClear()
```

But why I must do this, why MathJax don't reset itself ?

**Comment by dpvc** [comment]
There is not enough information here.  For example, can you give the equation that causes you trouble?  Are you running the browser or in a node application?  What typesetting command are you calling?

The issue template indicates a number of things that you should be submitting with your issue report.  Please do try to follow that template.
