### ISSUE TITLE
"Can't find handler for document" despite preLoading adaptors/liteDOM

### ISSUE THREAD

**Issue by edemaine** [mathjax/MathJax#2738]
### Issue Summary

It's me again from Web Worker problem #2489.  I just noticed that the following code:
```js
global.MathJax.loader.preLoad('core', 'adaptors/liteDOM', 'input/tex-base',
  '[tex]/all-packages', '[tex]/textmacros', 'output/svg', 'output/svg/fonts/tex');
global.MathJax.config.startup.ready();
```
is generating the following error message, despite `'adaptors/liteDOM'` being in the preLoad list:
```
HandlerList.js:60 Uncaught Error: Can't find handler for document
    at HandlerList.handlesDocument (HandlerList.js:60)
    at HandlerList.document (HandlerList.js:64)
    at Object.document (mathjax.js:10)
    at getDocument (startup.js:326)
    at getComponents (startup.js:145)
    at Object.defaultReady (startup.js:119)
    at eval (tex2svg.coffee:36)
    at Object../tex2svg.coffee (tex2svg.js:19)
    at __webpack_require__ (tex2svg.js:3183)
    at tex2svg.js:3247
```
However, I can actually render SVG fine with this configuration, so the error doesn't actually seem important.

### Steps to Reproduce:

1. Visit https://edemaine.github.io/tex2svg-webworker/ or the development build https://erikdemaine.org/restricted/tex2svg-webworker/ which has a clearer stack trace.
2. Look at console log and observe error message above.

Tested in Chrome and Firefox on Windows 10.

However, running `node tex2svg.js` produces no errors, so it seems specific to being in a Web Worker.

### Technical details:

* MathJax Version: 3.2.0 (NPM); also tested with 3.1.2
* Client OS: Windows 10
* Browser: Chrome 91 or Firefox 90

### Supporting information:

[Here's the full (CoffeeScript) code](https://github.com/edemaine/tex2svg-webworker/blob/main/tex2svg.coffee) which is based closely on [https://github.com/mathjax/MathJax-demos-node/blob/master/preload/tex2svg](preload/tex2svg).

Any idea what I'm missing? This error isn't critical (it doesn't prevent me from rendering), but it makes me think that something is wrong.  Does MathJax detect that it's in a browser and is unhappy about using liteDOM?

**Comment by dpvc** [comment]
That message usually means that the liteDOM parser wasn't able to properly parse the HTML that it was given in the `mathjax.document()` call.  This call is made using the `startup` component's default `ready()` function, which either passes the browser `document` if there is one, or an empty string other wise (so MathJax will ask its adaptor to set up a separate document).  I don't know if a WebWorker has a defined `document` variable, but if so, that is what is being passed to the `liteDOM` adaptor, and it will definitely not be able to parse that. 

Try adding `document: ''` to the `startup` block of your MathJax configuration to force MathJax to use a blank document.  That might do the trick.

**Comment by edemaine** [comment]
@dpvc That solved my problem &mdash; thanks so much!
