### ISSUE TITLE
Equation editor

### ISSUE THREAD

**Issue by ybh10** [mathjax/MathJax#2743]
**Is your feature request related to a problem? Please describe.**
Can edit mathjax expression.

**Describe the solution you'd like**
Can input math expression for calculation.

**Describe alternatives you've considered**
MathJax Editor: https://ianlucas.github.io/mathjax-editor/
This is a great start for equation editor, but does not seem to be maintained, does not have a release and does not work well with all screen sizes.
Mathquill: http://mathquill.com/
Dependent on Jquery and does not support MathML.

**Additional context**

**Comment by dpvc** [comment]
MathJax does not include an editor of its own, and MathJax does not do calculation, only typesetting of the mathematics.  There are many other on-line math editors that can produce LaTeX or MathML formats that could be typeset by MathJax.  You have named two, but there are others.  See the [list of web-based math editors](https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors) and this [google search](https://www.google.com/search?client=safari&rls=en&q=mathjax+equation+editor+online&ie=UTF-8&oe=UTF-8) for some more.  Perhaps one of those will do what you need.
