### ISSUE TITLE
ui/safe breaks visuals of \longrightleftharpoons

### ISSUE THREAD

**Issue by mhchem** [mathjax/MathJax#2745]
Please have a look at <https://jsbin.com/gapezoravi/1/edit?html,js,console,output>, where the upper arrow is smaller than the lower one. This is a strange side-effect of loading ui-safe.

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>MathJax</title>
  <script>
    window.MathJax = {
      tex: {
        inlineMath: [['$', '$'], ['\\(', '\\)']],
      },
      loader: {load: ['ui/safe']},
    };
  </script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js"></script>
</head>
<body>
    $\longrightleftharpoons$
</body>
</html>
```
This should solve https://github.com/mhchem/MathJax-mhchem/issues/21.

**Comment by dpvc** [comment]
I confirm the result you are getting, but am not sure of there cause and will have to investigate further.  Apparently the `scriptlevel` value that is being set on the upper arrow is being removed.  The `safe` extension does limit the allowed values for `scriptevel`, but it should allow the value 0, which is what it was set to.  I'll have to explore what it happening mere fully.
