### ISSUE TITLE
Does not support "<mstyle></mstyle>"?

### ISSUE THREAD

**Issue by masx200** [mathjax/MathJax#2746]
### Issue Summary
Does not support `"<mstyle></mstyle>"`?
A summary of the issue and the browser/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.

### Steps to Reproduce:

1. This is the first step
https://mathjax.github.io/MathJax-demos-web/input-mml2svg.html
2. This is the second step
input following code
```
<math title="sum_(i=1)^n i^3=((n(n+1))/2)^2"><mstyle fontsize="1em" fontfamily="serif" mathvariant="serif" mathsize="1em" mathcolor="blue" displaystyle="true"><mrow><munderover><mo>∑</mo><mrow><mi>i</mi><mo>=</mo><mn>1</mn></mrow><mi>n</mi></munderover></mrow><msup><mi>i</mi><mn>3</mn></msup><mo>=</mo><msup><mrow><mo>(</mo><mfrac><mrow><mi>n</mi><mrow><mo>(</mo><mi>n</mi><mo>+</mo><mn>1</mn><mo>)</mo></mrow></mrow><mn>2</mn></mfrac><mo>)</mo></mrow><mn>2</mn></msup></mstyle></math>
```
3. Further steps, etc.
click button Render MathML
```
mml-svg.js:1 
Uncaught TypeError: Cannot read property 'chars' of undefined
    at t.Q.getChar (mml-svg.js:1)
    at t.getVariantChar (mml-svg.js:1)
    at t.computeBBox (mml-svg.js:1)
    at t.getBBox (mml-svg.js:1)
    at t.computeBBox (mml-svg.js:1)
    at t.computeBBox (mml-svg.js:1)
    at t.getBBox (mml-svg.js:1)
    at t.getBaseScale (mml-svg.js:1)
    at t [as constructor] (mml-svg.js:1)
    at t [as constructor] (mml-svg.js:1)
```
Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.2.0
* Client OS: `Linux mas-PC 5.10.36-amd64-desktop #2 SMP Mon Apr 26 11:56:35 CST 2021 x86_64 GNU/Linux`
* Browser: Chrome 91.0.4472.106

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and include them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by dpvc** [comment]
Yes, MathJax does support the `mstyle` element, but you have specified `mathvariant="serif"`, which is not a valid variant.  That causes MathJax to fail when it tries to interpret that variant.  The `mathvariant` value is not a font name, but one of a predefined set of variant forms.  The legal values are `normal`, `bold`, `italic`, `bold-italic`, `double-struck`, `fraktur`, `bold-fraktur`, `script`, `bold-script`, `sans-serif`, `bold-sans-serif`, `sans-serif-italic`, `sans-serif-bold-italic`, and `monospace`.  Any other value will cause an error.

**Comment by masx200** [comment]
https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mi
