### ISSUE TITLE
Possible bug: mjx-container font-size set relative to wrong font

### ISSUE THREAD

**Issue by rcragun** [mathjax/MathJax#2747]
### Issue Summary

Giving multiple options for `font-family` of a parent element appears to sometimes lead MathJax to set the font-size of the `mjx-container` relative to a backup font that was never rendered in any of the parent’s content. 

### Minimal complete example
Also at [https://jsfiddle.net/randyc/yfzacqjv/3/](https://jsfiddle.net/randyc/yfzacqjv/3/)
```
<!DOCTYPE html>
<html>
<head>
    <title>MathJax Overflow</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <!-- Load Roboto font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">

    <!-- Use Roboto font -->
    <style type="text/css">
        body{
        /*These produce different results*/
        font-family: Roboto, sans-serif;
        /*font-family: Roboto;*/
        /*font-family: sans-serif;*/
        }
    </style>

    <!-- Load MathJax -->
    <script id="MathJax-script" async 
        src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js">
    </script>
</head>

<body>
    <p>Inline equation: \(Y=2X+3\)</p>
    <p>Same with display: \[Y=2X+3\]</p>
</body>
</html>
```

### Steps to Reproduce
1. Save the code to a file
2. Open the file in a browser
3. Observe rendering and styling:
  a. Note the physical size of the rendered math relative to the rendered regular text
  b. Inspect the `font-size` styling in either `mjx-container`
  c. Inspect the `font-family` inherited by `mjx-container` (Firefox inspector shows the font in use underlined)
4. Edit the `font-family` styling of `body` to include only `Roboto` and do step 3 again
5. Edit the `font-family` styling of `body` to include only `sans-serif` and do step 3 again

#### Expected behavior: 
As long as Roboto has the highest priority in the `font-family` styling of the parent element (and Roboto is available, of course),
* Rendering of math will not depend on what other font options are listed later
* MathJax will set the `font-size` relative to Roboto

#### Observed behavior: 
* When Roboto is the only font option specified, `font-size` of `mjx-container` is `101.1%` (the exact number is not important)
* When sans-serif is the only font option specified, `font-size` of `mjx-container` is `117.4%` (the exact number is not important; the point is that it is different)
* With `font-family: Roboto, sans-serif`, `font-size` of `mjx-container` is `117.4%` even though the text in the parent element is rendered with Roboto
* The behavior is not specific to Roboto. I tried replacing Roboto with Open Sans, and the problem persisted.

### Technical details

* MathJax Version: 3 (no idea how to get more specific because I do not know js)
* Device 1:
  * Client OS: Windows 10 Pro 21H2 build 19044.1149
  * Screen: Dell UltraSharp U3415W 
  * Resolution: 3440×1440 with Windows scaling up to 125%
  * Browsers tested: 
    * Firefox 90.0.2 (64-bit)
    * Chrome 92.0.4515.107 (Official Build) (64-bit)
    * Edge 92.0.902.55 (Official build) (64-bit)
* Device 2:
  * Client OS: Windows 10 Pro 21H1 build 19043.1110
  * Screen: laptop: Dell XPS 13 9370
  * Resolution: 3840×2160 with Windows scaling up to 250%
  * Browser tested: Firefox 90.0.2 (64-bit)

### Supporting information
There were no errors, but here are the console warnings:
```
Unknown property ‘-moz-border-radius’.  Declaration dropped. MathJaxOverflow.html:4:550
Unknown property ‘-moz-box-shadow’.  Declaration dropped. MathJaxOverflow.html:4:798
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped. MathJaxOverflow.html:4:909
Unknown property ‘-moz-border-radius’.  Declaration dropped. MathJaxOverflow.html:1:214
Unknown property ‘-moz-border-radius’.  Declaration dropped. MathJaxOverflow.html:2:194
Unknown property ‘-moz-border-radius’.  Declaration dropped. MathJaxOverflow.html:1:506
Unknown property ‘-moz-box-shadow’.  Declaration dropped. MathJaxOverflow.html:1:750
Unknown pseudo-class or pseudo-element ‘future’.  Ruleset ignored due to bad selector. MathJaxOverflow.html:124:31
```
I am working on a series of screenshots to show the different renderings, but I want to submit this so the page doesn’t time out while I am working on it.

**Comment by dpvc** [comment]
It's not the multiple fonts that are the issue, it is the fact that Roboto is a web font.  That means that it takes time for it to arrive, and the browser may substitute a different font in the meantime.  MathJax tried to measure the ex-height of the surrounding font, and if it does that before Roboto arrives, the value will be determined for the substitute font rather than for Robot itself.  When Roboto is combined with sans-serif, the substitute font appears to be san-serif, so that is why you get the same value for `Roboto, sans-serif` as for `sans-serif`.  When Roboto is used by itself, a different font is used as the temporary font, and that yields a different ex-height, so MathJax uses a different `font-size` value.

Google provides a [web-font loader library](https://github.com/typekit/webfontloader) that lets you determine when the fonts are loaded, so you might try using that to load the fonts and delaying MathJax's typesetting until after the web fonts are available.  That should get the proper sizing.  Something like

``` html
<script>
//
//  A promise that is resolves when the google fonts are loaded
//
const fontPromise = new Promise((resolve, reject) => {
  window.WebFontConfig = {active: resolve};
});
//
//  Configure MathJax to wait for the font promise before typesetting the page
//
MathJax = {
  startup: {
    pageReady() {
      return fontPromise.then(MathJax.startup.defaultPageReady);
    }
  }
};
</script>
<!--
  !  Get the webfont library and use it to load Roboto.
  !-->
<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
<script>WebFont.load({google: {families: ['Roboto']}});</script>
<!--
  !  Load MathJax
  !-->
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
```

might do the trick.  I haven't tested this, so some adjustment might be needed, but that is the general idea.

**Comment by rcragun** [comment]
Excellent clarification, and thanks so much for the advice. I think this should be closed.
