### ISSUE TITLE
WebKit's column-count CSS still causes problems with HTML-CSS output

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#275]
Use of `-webkit-column-count` causes HTML-CSS output to fail in the second and following columns.  This is probably a reappearance of issue #45.  Positioned elements seem to get lost.  See [the user forum post](https://groups.google.com/d/topic/mathjax-users/7mSiGUO4Sjc/discussion) for details and a link to an example.

SVG output is not affected.

**Comment by pkra** [comment]
I can't access the example from the user group to see if this still fails. Closing this until we have a minimal example again.
