### ISSUE TITLE
Email support?

### ISSUE THREAD

**Issue by drdrjacobs** [mathjax/MathJax#2752]
**Is your feature request related to a problem? Please describe.**

Ideally, I would be able to send beautiful math over email (gmail/outlook/etc) using MathJax. However, I know email support for CSS lags massively behind that of browsers. 

Is there any chance that this will eventually work? 

**Describe alternatives you've considered**

Other solutions to this problem are awkward. I could attach a pdf to the email of course, but that's not very streamlined. There are also solutions like [MarkDownHere](https://markdown-here.com/). But these solutions render png images that often have poor resolution and scaling.

**Comment by pkra** [comment]
For CSS, the main challenge would be webfonts but @font-face doesn't work well in email clients (and you'd have to base64 them as external webfonts probably won't ever work), see https://www.caniemail.com/features/css-at-font-face/. For SVG, support is very shoddy for inline svg https://www.caniemail.com/features/html-svg/, in fact even for img tags pointing to svg https://www.caniemail.com/features/image-svg/.

**Comment by drdrjacobs** [comment]
> Addendum: there's really nothing MathJax can do about this.

Understood. It seems like these things move very slowly too. I'll check back in 5-10 years....
