### ISSUE TITLE
Turn off the messages script at the bottom of the page in mobile app

### ISSUE THREAD

**Issue by surya08431** [mathjax/MathJax#2755]
### Issue Summary

How do I remove the “Typesetting math: 100%” display a script message on page bottom in mobile app using flutter.

### Steps to Reproduce:

This is the first step
Add mathjaxview plugin to my flutter app
This is the second step
Integrate mathjax code with my view page
Further steps, etc.
After successful placement during conversion shows script message at bottom of the page.

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:
Flutter:2.12.2
MathJax Version: mathjax_view: ^0.1.2
Client OS: Mac OS X 10.8.4

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

Uploading cct.mp4…
![Screen Shot 2021-07-29 at 10 45 42 AM](https://user-images.githubusercontent.com/33568985/127436726-a6737f0c-18e3-49ce-89bc-200dd9e51064.png)

**Comment by surya08431** [comment]
How can I disable the script message rendering after conversion of given notation in flutter Please give me any solution to this issue. Thank you

**Comment by masx200** [comment]
You can try not to load the ui module, just load the required input and output modules.
```html
<script>
MathJax = {
  loader: {
    load: ['input/tex-full', 'output/svg', ]
  },
  
};
</script>
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@latest/es5/startup.js">
</script>
```

**Comment by surya08431** [comment]
> You can try not to load the ui module, just load the required input and output modules.
> 
> ```
> <script>
> MathJax = {
>   loader: {
>     load: ['input/tex-full', 'output/svg', ]
>   },
>   
> };
> </script>
> <script type="text/javascript" id="MathJax-script" async
>   src="https://cdn.jsdelivr.net/npm/mathjax@latest/es5/startup.js">
> </script>
> ```

Thanks for the reply, my dought is how can I implement this script into my flutter code. I don't no using script file run in flutter
