### ISSUE TITLE
How to display braille codes

### ISSUE THREAD

**Issue by itexsolution** [mathjax/MathJax#2756]
Hello,

Is there any way to make the braille code visible?
I remember it being possible before.
I can't find a way to display it right now.

how to please
thank you.

**Comment by zorkow** [comment]
Braille output/subtitles are no longer automatically switched on as they lead to some bizarre output with certain screen reader when no Braille display is connect. You can activate them using the context menu (right click or press space on a Math expression, `Accessibility > Speech > Braille output|subtitles`).

If you have control over the page you can force them to be switched on by adding the following configuration:

``` javascript
MathJax = {
  options: {
    a11y: {
      braille: true,
      viewBraille: true
    }
  }
};
```

**Comment by itexsolution** [comment]
Thank you for answer.

But I still can't see the braille code in the browser developer tools either.

Attach a snapshot.
<img width="1237" alt="스크린샷 2021-08-08 오후 12 02 51" src="https://user-images.githubusercontent.com/49851589/128619384-7b230052-eace-448d-b747-d13b70323731.png">

**Comment by dpvc** [comment]
The codes are not always show, only when the expression explorer is activated.  Click on an expression and press return to do that.
