### ISSUE TITLE
Equations not properly rendering in website, despite following documentation.

### ISSUE THREAD

**Issue by BuddhiLW** [mathjax/MathJax#2757]
### Issue Summary
I'm using Artix Linux, DWM, with Clojure's Cryogen framework to write a blog.

I tried to put MathJax into the posts <head>s. The website function as a markdown rendered to html (Jekyll, Hugo etc style). So, I use pandoc to convert Org-mode notes to Markdown.

This is the scripts in the head of every post:
```js
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script>
      MathJax = {
	  tex: {
	      // packages: ['base,asm'],        // extensions to use
	      inlineMath: [              // start/end delimiter pairs for in-line math
		  ['\\(', '\\)']
	      ],
	      displayMath: [             // start/end delimiter pairs for display math
		  ['$$', '$$'],
		  ['\\[', '\\]'],
		  ['\begin{equation}', '\end{equation}']
	      ],
	      processEscapes: true,      // use \$ to produce a literal dollar sign
	      processEnvironments: true, // process \begin{xxx}...\end{xxx} outside math mode
	      processRefs: true,         // process \ref{...} outside of math mode
	      digits: /^(?:[0-9]+(?:\{,\}[0-9]{3})*(?:\.[0-9]*)?|\.[0-9]+)/,
              // pattern for recognizing numbers
	  }};
    </script>
```

### Steps to Reproduce:

1. Have leiningen installed in your system.
2. git clone https://github.com/BuddhiLW/Blobing.git
3. cd Blobing
4. lein serve
5. http://localhost:3000/

This is what gets rendered:

![pic-selected-210809-1221-05](https://user-images.githubusercontent.com/59554283/128731161-d347bbf0-0ff1-4e1a-a724-6abfdee9b070.png)

**Comment by pkra** [comment]
The markdown conversion messes up the TeX markup before MathJax gets to it. See http://docs.mathjax.org/en/latest/input/tex/html.html?highlight=markdown#interactions-with-content-management-systems and most of https://github.com/mathjax/MathJax/issues?q=markdown for many (many) discussions.

**Comment by BuddhiLW** [comment]
Ok!

Well, in general I exchanged `$<code>$` for `\( <code> \)`. `\(e^2_M\)` for `\(e\^2\_M\)`, so ^ for \^ and _ for \_.

**Comment by pkra** [comment]
> It worked. Although, it will be very annoying to do that by hand every time. Well... Anyhow, thank you!

Some markdown parsers have support for ignoring TeX fragments built in or via plugins (e.g., kramdown, markdown-it). This usually makes things easier for authors.
