### ISSUE TITLE
Wrong command name in mathtools: DeclarePairedDelimiters should be DeclarePairedDelimiter

### ISSUE THREAD

**Issue by robly18** [mathjax/MathJax#2758]
The mathtools package in LaTeX has a command `\DeclarePairedDelimiter`. Mathjax reproduces it, but the name has an extra "s" at the end: `\DeclarePairedDelimiters`, as do the variations. For example, `\DeclarePairedDelimitersX` should instead be `\DeclarePairedDelimiterX`.

I have found no reason for this change, so as far as I know it is a typo. If it is on purpose, then perhaps a warning should be placed on the [mathtools page](http://docs.mathjax.org/en/latest/input/tex/extensions/mathtools.html).

**Comment by zorkow** [comment]
This is probably a typo. Even if `\DeclarePairedDelimiters` and `\DeclarePairedDelimitersX` were to remain, the singular version should be added.
