### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by donno2048** [mathjax/MathJax#2761]
Is there a place to report Security issues with MathJax? Like HackerOne or something?

**Comment by dpvc** [comment]
No, but if you want us to address the issue without giving it out to the public, you can send a description to "info at mathjax.org"

**Comment by dpvc** [comment]
For others seeing this, the reported vulnerability was fixed three years ago.  See the [announcement](
https://groups.google.com/g/mathjax-dev/c/JCa8uRe3U2o) of the fix from that time.
