### ISSUE TITLE
empheq is missing

### ISSUE THREAD

**Issue by ickc** [mathjax/MathJax#2762]
Under `es5/input/tex/extensions`, `empheq.js` is missing.

c.f. https://github.com/mathjax/MathJax-docs/issues/290

**Comment by dpvc** [comment]
Thanks for your report.  It turns out that the build file for `empheq` and `cases` put the packed file into the wrong location.  I will make a pull request to fix it, but in the meantime, you can use

``` javascript
MathJax = {
  loader: {
    source: {
      '[tex]/empheq': 'https://cdn.jsdelivr.net/npm/mathjax-full@3/components/es5/empheq.js',
      '[tex]/cases': 'https://cdn.jsdelivr.net/npm/mathjax-full@3/components/es5/cases.js',
    }
  },
};
```

to access these components.
