### ISSUE TITLE
empty \dot{} should render higher on the baseline.

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2766]
E.g., `x $\dot{}$ y` renders the dot too low (does not match "real" TeX)

MathJax.org#demo:

![image](https://user-images.githubusercontent.com/426686/132820865-7dc97ca8-252f-4306-b6aa-733791b94683.png)

TeX:

![image](https://user-images.githubusercontent.com/426686/132820929-5dcec4e8-bb74-4015-b0ea-29867529e4a4.png)

**Comment by pkra** [comment]
Similarly for `$\bar{}$` and I'm guessing everything similar.

**Comment by pkra** [comment]
Just to add: this is a regression in v3 - v2 used to do this correctly.

**Comment by pkra** [comment]
Aha -- I had filed this for v2 back in the day https://github.com/mathjax/MathJax/issues/1706

**Comment by dpvc** [comment]
I thought it sounded familiar.  It looks like that was after we had started on v3 already, and so the patch was done to v2 without it making it into v3.  I can see about adding it in.

**Comment by pkra** [comment]
Thanks, Davide.
