### ISSUE TITLE
Bug:Bad rendering in DuckDuckGo browser

### ISSUE THREAD

**Issue by shaughanlavine** [mathjax/MathJax#2769]
Characters overlap in rendering on platform described below, as if all the character widths are too small.

### Steps to Reproduce

Load https://mathjax.github.io/MathJax-demos-web/tex-chtml.html on the platform specified below.

This is a bug because the rendered math is illegible.

### Technical details

* Client OS: Android 11
* Browser: DuckDuckGo 5.94.3 on 
* Galaxy Tab S5e SM-T727A
The same problem occurs within ObsidianApp 1.0.4 on the same tablet.
Everything works fine in Android 9/DuckDuckGo  5.7.2 on my phone.

**Comment by dpvc** [comment]
I'm not able to reproduce the issue in DuckDuckGo 5.95.0 on Android 11 on a Samsung A32 phone.  I don't have access to a Galaxy Tab to try it there.  Can you try updating DuckDuckGo and see if that helps?
