### ISSUE TITLE
Questions about MathJax-src/ts/components/startup.ts

### ISSUE THREAD

**Issue by MarcelBolten** [mathjax/MathJax#2774]
1. I'm not sure if there is a typo on [line 95](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/components/startup.ts#L95):
   ```ts
   useHander(name: string, force?: boolean): void;
   ```
   Shouldn't it be `useHandler()`?

2. I was wondering why `defaultPageReady()` is not listed in the `MathJaxObject.startup` interface on [line 84 ff.](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/components/startup.ts#L84) However, I saw issues ([src #685](https://github.com/mathjax/MathJax-src/issues/685), [#2197](https://github.com/mathjax/MathJax/issues/2197)) about the complexity MathJax has to deal with.

Anyways, Thanks for the great tool. ❤️

**Comment by dpvc** [comment]
Yes, that looks like a typo.  Thanks for reporting it.  You are also correct that `defaultPageReady()` should be in the interface.  It's been a while, but I think that the reason it was left out is that it was added relatively late, and it was just an oversight that it was not included.

I will need to make a PR for it.
