### ISSUE TITLE
Unknown node type "mstack"

### ISSUE THREAD

**Issue by lled0** [mathjax/MathJax#2780]
### Issue Summary

Hi,

I'm trying to parse a mml formula, but show error: Unknown node type "mstack".

I read in [documentation](http://docs.mathjax.org/en/latest/upgrading/whats-new-3.2.html?highlight=mstack#mathml-extensions) that MathML3 is implemented in version 3 and there isn't needed to import the extension.

### Steps to Reproduce:

[Here](https://jsbin.com/ricekuhuce/edit?html,output) is an example.

Must be shown:
<img width="150" alt="Captura de pantalla 2021-10-05 a las 12 55 30" src="https://user-images.githubusercontent.com/9018616/136010190-13723471-ec44-4fba-b6f1-dabbd9ddbb40.png">

### Technical details:

* MathJax Version: 3 

Thank you!

**Comment by dpvc** [comment]
> I read in [documentation](http://docs.mathjax.org/en/latest/upgrading/whats-new-3.2.html?highlight=mstack#mathml-extensions) that MathML3 is implemented in version 3 and there isn't needed to import the extension.

You have misread the documentation.  In the link you provide there is a pointer to configuring the extension, and [that page](http://docs.mathjax.org/en/latest/input/mathml.html#mathml-mml3) indicates that you must use

``` html
<script>
MathJax = {
  loader: {load: ['[mml]/mml3']}
};
</script>
```

to activate the extension.  There are, however, several issues with the mml3 extension (see #2718).  The first, is that you need to also include `forceReparse: true` in the configuration, as in

``` html
<script>
MathJax = {
  loader: {load: ['[mml]/mml3']},
  mml: {forceReparse: true}
};
</script>
```

and [second](https://github.com/mathjax/MathJax/issues/2718#issuecomment-867574013), there is an issue with Chrome and Safari that you need to work around.  This configuration should do it for the MathJax component that you are using:

``` html
  <script>
  MathJax = {
    loader: {load: ['[mml]/mml3']},
    mml: {forceReparse: true},
    startup: {
      ready() {
        MathJax.startup.defaultReady();
        MathJax.startup.document.inputJax[1].preFilters.add(function (data) {
          data.data = data.data.replace(/[\s\n]+<math/, '<math').replace(/math>[\n\s]+/, 'math>');
        }, 10);
      }
    }
  };
  </script>
```

The Chrome/Safari issue should be resolved and the documentation updated in the next release.

**Comment by dpvc** [comment]
@svejdani, it depends on the MathJax file that you are loading.  If you used `tex-mml-chtml.js`, then it would be `inputJax[1]`, but if you used `mml-xhtml.js` then it would be `inputJax[0]`.  Sorry for the confusion!

**Comment by chrisooo3** [comment]
@dpvc after adding configuration, that you have mentioned, I am getting following error:
```
TypeError: Cannot read property 'getElementsByTagName' of null
    at e.tags (mml-svg.js:1)
    at e.transform (mml3.js:1)
    at e.mmlFilter (mml3.js:1)
    at e.execute (mml-svg.js:1)
    at e.t.executeFilters (mml-svg.js:1)
    at e.compile (mml-svg.js:1)
    at e.t.compile (mml-svg.js:1)
    at Object.renderMath (mml-svg.js:1)
    at e.renderConvert (mml-svg.js:1)
    at e.t.convert (mml-svg.js:1)
```

To reproduce, here you have jsbin: https://jsbin.com/kuwujesure/1/edit?html,console,output
