### ISSUE TITLE
SVG - Microsoft Edge - Characters Rotated

### ISSUE THREAD

**Issue by buddyd16** [mathjax/MathJax#2785]
### Issue Summary

On Microsoft Edge using SVG rendering some characters render rotated at 100% view scale, changing the view scale to anything other than 100% renders correctly and printing the page renders correctly in the print preview.

### Steps to Reproduce:

seems to be random 

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: using this CDN -- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
* Client OS: Windows 10
* Browser: Microsoft Edge Version 94.0.992.38 (Official build) (64-bit)

### Supporting information:

```
<!-- Mathjax CDN -->
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async
      src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js">
</script>
```

```
<!-- Formulas --> **jinja templating removed and replaced with 0.000
<div>
  <p> \[R_{n,req} = \sigma_{max} \cdot \Omega = 0.000 \text{ ksi}\]</p>
  <p> \[Req. Throat = \frac{R_{n,req}}{0.6 \cdot F_{exx}} = 0.000 \text{ in} \]</p>
  <p> \[Fillet = \frac{32 \cdot 0.000}{\sqrt{2}} \cdot \frac{1}{16} = 0.000 \]</p>
  <p> \[R_n = 0.000 \cdot \frac{\sqrt{2}}{2} \cdot \frac{1}{16.0} \cdot 0.6 \cdot F_{exx} = 0.000 \text{ ksi} \]</p>
</div>
```

![image](https://user-images.githubusercontent.com/12416202/136829627-f6875f78-a624-40ca-a941-4deb8f9c6e4f.png)

This one the result 2.221 renders with the second 2 rotated but the 2.221 that shows in the following formula renders properly:
![image](https://user-images.githubusercontent.com/12416202/136829872-2361ad47-f97c-4347-b90a-55b345ede2d3.png)

**Comment by pkra** [comment]
Possibly https://bugs.chromium.org/p/chromium/issues/detail?id=1257978 or https://bugs.chromium.org/p/chromium/issues/detail?id=1253952
