### ISSUE TITLE
Numerator/Denominator Incorrectly Left Justified

### ISSUE THREAD

**Issue by jkeneda** [mathjax/MathJax#2787]
### Issue Summary

Teacher here.  I'm not fully sure if this is an issue with MathJax or with Blackboard (or both), but I'm hoping that someone here will know a quick fix for it.

I use MathJax to make quizzes on Blackboard (they host a bunch of class websites), and everything so far has rendered just fine, except for fractions.  The numerator and denominator of a fraction seem to be left-justified by default, and I'd like for them to be centered.  Here's an example:

![Fraction Display](https://user-images.githubusercontent.com/44850411/137512118-04d3e47b-d50f-4998-9de1-14475c3b659c.png)

I tried asking about it on the TeX stackexchange in case it was about configuring TeX or something, but they said it wouldn't be a TeX thing.  Any help would be appreciated!

### Technical details:

* I believe I'm using MathJax Version: 2.7.7, and I've replicated the issue in Firefox/Chrome on Windows and Firefox on iOS.  So I think it must either be a MathJax or Blackboard issue (or something about their interaction).  I can find more specific info if it would be helpful.

Thanks for reading!

**Comment by pkra** [comment]
Without access to a minimal live sample page, there's no way to know for sure but this looks like a blackboard issue.

More specifically, this looks like a typical alignment issue - the list marker and item are aligning at the top, not the baseline. MathJax aligns its output with the baseline of the surrounding context -- but the marker / checkbox is outside that context. Hence, I'd guess it's a blackboard issue.
