### ISSUE TITLE
MathJax 3.2.0 Lazy Loading - mtd error

### ISSUE THREAD

**Issue by bthomale** [mathjax/MathJax#2788]
### Issue Summary

When using `load: ['ui/lazy']` with mathml tables, some mtd elements load as yellow mtd text instead of loading correctly. When you load it without lazy typesetting, it renders just fine. 

This is happening in a variety of browsers. I'm testing on macOS, looking at Safari, MS Edge, and FireFox. 

### Steps to Reproduce:

1. Open the attached zip file. 
2. Open mtd-lazy-error.xhtml in Safari (or, any other browser). 
3. See the yellow mtd text in place of some of the cells. 
4. Open mtd-no-lazy-no-error.xhtml and see that it renders fine. 

### Technical details:

* MathJax Version: 3.2.0
* Client OS: macOS 11.6
* Browser: Safari Version 15.0 (16612.1.29.41.4, 16612)
* Browser: FireFox 93.0 (64-bit)
* Browser: Microsoft Edge Version 94.0.992.50 (Official build) (x86_64)

### Supporting information:

See attached zip archive for screenshots and sample xhtml.

[MathJax-3.2.0-lazy-mtd-bug.zip](https://github.com/mathjax/MathJax/files/7354385/MathJax-3.2.0-lazy-mtd-bug.zip)

**Comment by bthomale** [comment]
Hey guys, I am still able to reproduce this bug in MathJax 3.2.1. Here's an updated "reproducer" that points at the 3.2.1 sources in place of the 3.2.0 sources. 

Can someone take another look? 

The workaround you gave me at the top of this conversation (back in october) still works. I disabled the workaround to test the fix, but I'm afraid I've had to put it back in. 

[MathJax-3.2.1-lazy-mtd-bug.zip](https://github.com/mathjax/MathJax/files/8834690/MathJax-3.2.1-lazy-mtd-bug.zip)

**Comment by dpvc** [comment]
You need to keep the

``` js
    mml: {
      parseAs: 'xml'
    },
```

because of the XHTML document.  The stuff from the `setup` block is what was added in 3.2.1 and is no longer needed.

**Comment by bthomale** [comment]
Oh! That helps. I'll give that a try.

**Comment by bthomale** [comment]
That worked. Thanks! I had other startup logic I needed so it was just a matter of removing these two lines from it, I think:
 
```
        const {HTMLAdaptor} = MathJax._.adaptors.HTMLAdaptor;
        HTMLAdaptor.prototype.body = function(doc) {return doc.body || doc};
```

**Comment by dpvc** [comment]
> it was just a matter of removing these two lines from it, I think

Yes, that's right.

Glad that did it for you.
