### ISSUE TITLE
MathJax Demo subject to XSS vulnerability

### ISSUE THREAD

**Issue by pslootweg** [mathjax/MathJax#2794]
### Issue Summary

MathJax has a demonstrable XSS issue

### Steps to Reproduce:

I will not publish details right now - I have emailed info@mathjax.org but so far no reply.
Can be shown in https://www.mathjax.org/#demo

### Technical details:

* MathJax Version: V2 and V3
* Client OS: Mac OS X 12.0.1
* Browser: Chrome 95.0.4638.54

### Supporting information:

I will update this issue with details in due course.

**Comment by dpvc** [comment]
A couple of point for those concerned about this issue:

1.  The poster's report concerns the code running the demo on the mathjax.org website, not MathJax itself.  Those running MathJax on their own sites are not affected by the issue he has reported.
2.  The code running on mathjax.org does not have an XSS issue, despite the poster's claim, as I will explain to him in response to his email.

**Comment by dpvc** [comment]
I have modified to title to this issue to clarify the nature of the complaint.

**Comment by pslootweg** [comment]
Understand the limitations applying to the demo.

**Comment by H4cK1n6404** [comment]
$\unicode{"<img/src=x onerror="alert(1)">"}$$
