### ISSUE TITLE
MathJax is not rendering on page after rendering from 3 years without any upgrade

### ISSUE THREAD

**Issue by kenluck2001** [mathjax/MathJax#2796]
### Issue Summary

The page was properly rendering latex on the blog for 3 years now. It suddenly started throwing errors this week. There are some 404 error in the cdn version 2.7.1 mathjax, but I can't figure out why it is happening.

### Steps to Reproduce:
Live URL: https://kenluck2001.github.io/blog_post/real-time_anomaly_detection_for_multivariate_data_stream.html
1. Loading the page is malformed
2. Errors on console
Mathjax from cdn

### Technical details:

* MathJax Version: 2.7.1 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Ubuntu 20
* Browser: firefox 88.0 (64-bit)

### Supporting information:
Screenshot of Error log on console

![image](https://user-images.githubusercontent.com/1905599/140461006-a61798ee-f526-4b19-829b-c2ea95655a62.png)

 * Please supply a link to a (live) minimal example page, when possible.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.
 Page source: view-source:https://kenluck2001.github.io/blog_post/real-time_anomaly_detection_for_multivariate_data_stream.html

**Comment by pkra** [comment]
The errors in the console and network tab indicate that cdnjs has some issues loading MathJax v2 components. 
Additionally, the page loads both mathjax v2 and v3 which is bound to cause issues. 
Finally, the MathJax v2 configuration block is incorrectly placed after the script tag for MathJax v2 which can lead to erratic behavior. 

None of these look like issues with MathJax itself. Besides, the page is using MathJax v2.7.1 which was released in April 2017 so a first step should be to update.

(FYI Questions like this are more suitable for http://groups.google.com/group/mathjax-users/ where the community can help each other.)

**Comment by kenluck2001** [comment]
Please help provide code snippet that can help me to resolve the issue.

**Comment by kenluck2001** [comment]
This issue is not mathjax. It is a markdown issue and I have solved it. I will close this ticket. Thanks so much for the help.
