### ISSUE TITLE
I have the same problem with NuxJs:

### ISSUE THREAD

**Issue by doox911** [mathjax/MathJax#2798]
I have the same problem with NuxJs:

Nuxt config:

```
    script: [
      {
        src: 'https://polyfill.io/v3/polyfill.min.js?features=es6',
      },
      {
        id: 'MathJax-script',
        src: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
        body: true,
        async: true,
      },
    ],
```

Error:
> tex-mml-chtml.js:1 Uncaught TypeError: Cannot set property Package of #<Object> which has only a getter
    at i (tex-mml-chtml.js:1)
    at i (tex-mml-chtml.js:1)
    at i (tex-mml-chtml.js:1)
    at i (tex-mml-chtml.js:1)
    at e.combineWithMathJax (tex-mml-chtml.js:1)
    at tex-mml-chtml.js:1
    at tex-mml-chtml.js:1
    at tex-mml-chtml.js:1

In html:

![2021-11-08_14-37](https://user-images.githubusercontent.com/35161922/140735472-0302060b-92ba-49e8-bbd0-7d0bd22fe9a2.png)

_Originally posted by @doox911 in https://github.com/mathjax/MathJax/issues/2370#issuecomment-963050405_

**Comment by Disapear** [comment]
the same problem in NuxJs
