### ISSUE TITLE
"MathJax.Hub is undefined" with MathJax 3 but not 2 when using Vaadin 21 Live Reload

### ISSUE THREAD

**Issue by mtbc** [mathjax/MathJax#2802]
### Issue Summary

Using Firefox and Chrome on Ubuntu 20.04 with a web application that uses Vaadin 21.0's Live Reload feature, when the user hits "reload" in the browser, there is sometimes an error report before things go wrong:
```
TypeError: MathJax.Hub is undefined
```
Further reloads don't help. Restarting the application altogether fixes the issue. We switch from https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js to https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML and from `MathJax.typeset(null);` to `MathJax.Hub.Typeset(null);` then the application works fine on reload: downgrading MathJax from 3 to 2 seems to fix the problem.

### Technical details:

* MathJax Version: Whatever's at the URLs above, at the moment.
* Client OS: Ubuntu 20.04 LTS
* Browser: Firefox 94.0, Chrome 95.0.4638.69

(also other developers' machines which differ somewhat)

### Supporting information:

Unfortunately the offending application is non-trivial and closed-source. I'm opening this issue partly in case there's already enough information for us to try some fix or in case somebody else is seeing a similar issue but also so I can point our internal ticket at it for when we can someday provide a minimal test case or somesuch.

**Comment by dpvc** [comment]
MathJax version 3 has a significantly different interface from that of v2.  In particular, there is no `MathJax.Hub` in version 3 (unless you are using the AsciiMath input jax, which uses the legacy v2 code for that input jax, and so includes much of the v2 infrastructure as a hack to patch it into v3).  So if you are getting messages about `MathJax.Hub` perhaps there are places in your own code where that is being called that you haven't changed over to version 3 calls?

Without seeing the code, it is hard to tell.  Perhaps that traceback information for the error message you are seeing will tell something about where the `MathJax.Hub` call is being made.

**Comment by mtbc** [comment]
Thank you very much @dpvc: your point about `MathJax.Hub` being particular to v2 was a very helpful hint. We dug through the codebase and found some unused legacy typescript code that the build caused to pull in and pack a JavaScript library as a dependency, and that one depended on v2! We've carved out that accumulated cruft and now everything works just as advertised.

**Comment by dpvc** [comment]
Glad you were able to find the problem, and that all works as expected now.
