### ISSUE TITLE
Bug in Chromium >= 95.0.4609.0 (912033) affecting especially MathJax

### ISSUE THREAD

**Issue by TomasRiker** [mathjax/MathJax#2808]
# Disclaimer

This is not a MathJax bug, but a Chromium bug. However, due to the popularity of Chromium-based browsers (Chrome, Edge, ...), it should be considered to do something about it.

# Issue summary

Heavility nested HTML elements with the style `display: inline-block` can make Chromium-based browsers freeze completely. It seems to occur primarily when using a touch screen. Whenever the user touches a non-trivial MathJax formula, for example to scroll the page, there is a good chance that the browser will freeze either for a few seconds or "forever". When that happens, the browser utilizes 100% of CPU time and becomes unresponsive.

Here's my Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1274205

I attached an example HTML document and a video to the Chromium bug report. The example document initially contained formulas rendered by MathJax in the form of highly nested structure of `<span>` elements with the style `display: inline-block`. In an effort to create a minimal working example, I removed everything MathJax-specific and left only the `<span>` structure.

# What to do?

## Help get the bug fixed

I think this is a pretty severe bug in Chromium and it needs to be fixed soon. However I'm afraid that my bug report may go unnoticed due to the high number of reports being filed on a daily basis.

**If you know a Chromium developer or you are one yourself, please help make sure that this bug gets the attention it deserves. It has the potential to destroy the user experience of all websites or WebView apps that make use of MathJax.**

## Workaround

Since this bug heavily affects my current project that uses MathJax and I'm not very confident that it will get fixed soon, I'm trying to find a workaround. My findings so far:

- Values for CSS `display` that trigger the bug: `inline-block`, `inline-table` and possibly `table-row` and `table-cell`
- **No problem** when using `display: block`, `display: flex` or `display: inline-flex`!

I've been trying to use JavaScript to convert the MathJax output to use `inline-flex`. But I haven't been successful so far, due to the `vertical-align` CSS property not being respected on a Flexbox. I've tried to wrap elements in `block`s, but I can't get the vertical alignment right.

My other idea was to remember the position and size of each generated `<span>` inside a MathJax frame relative to the frame, then set all elements to `display: block` and `position: absolute` (circumventing the bug) and set their position and size directly in CSS (`left`, `top`, `width`, `height`).

If anyone has other ideas for a workaround, let's discuss them here.

**Comment by pkra** [comment]
That's a bit of a misleading title. Something like "Incredibly basic Chrome bug affecting MathJax" seems to be more appropriate. 

Like so many recent Chrome regressions, I'd expect it will disappear without being officially addressed.

**Comment by TomasRiker** [comment]
You're right, Peter. I changed the title.
I haven't noticed this bug on any other HTML content except for MathJax (and MathQuill) - probably there aren't that many cases of such heavily nested elements.
I'm working around the issue and I managed to eliminate a huge part of the `inline-block` usages. I will provide my workaround once it's ready.

**Comment by TomasRiker** [comment]
By the way, the SVG renderer doesn't seem to be affected, so switching to SVG is a quick fix.

**Comment by pkra** [comment]
The chrome issue's last comment indicates that this was fixed.

**Comment by dpvc** [comment]
The test file does seem to work now in Chrome 99.
