### ISSUE TITLE
how to cancel the blue border?

### ISSUE THREAD

**Issue by big-zZ** [mathjax/MathJax#2812]
my app is based on WKWebView (iPhone)  to load a html to render latex and math express, i opened the WKWebView's gesture action, after rendered some latex, and i touched one line, then there was a blue border effect around the latex, see the following pictures, i want to cancel the blue border, how to fix it?  thanks a lot
![IMG_7E7977D54D8B-1](https://user-images.githubusercontent.com/75821787/146136908-c54d3cf0-af45-430f-9eb2-64967e5203b9.jpeg)
![IMG_BFAF942AF547-1](https://user-images.githubusercontent.com/75821787/146136949-cf6ef26d-d7af-464e-b00e-d85c13903036.jpeg)

**Comment by dpvc** [comment]
The blue outline is part of the browser's user interface that indicates that a focusable item has been selected.  Because MathJax expressions allow access to the MathJax contextual menu via the space key and to its expression explorer via the return key (when the explorer tool is activated), the MathJax expressions are focusable (they accept key input) and are part of the tab sequence of focusable items.  This is important for people with assistive needs (like those with mobility issues that use keyboard controls rather than mouse clicks).  Removing the blue indicator would negatively impact those users.

If you feel you really **must** turn these off, you could add

``` css
mix-container:focus {
  outline: none;
}
```

to your CSS.

**Comment by big-zZ** [comment]
> The blue outline is part of the browser's user interface that indicates that a focusable item has been selected. Because MathJax expressions allow access to the MathJax contextual menu via the space key and to its expression explorer via the return key (when the explorer tool is activated), the MathJax expressions are focusable (they accept key input) and are part of the tab sequence of focusable items. This is important for people with assistive needs (like those with mobility issues that use keyboard controls rather than mouse clicks). Removing the blue indicator would negatively impact those users.
> 
> If you feel you really **must** turn these off, you could add
> 
> ```css
> mix-container:focus {
>   outline: none;
> }
> ```
> 
> to your CSS.

i have tried， it did not work!  thank u very much, i will try other ways

**Comment by big-zZ** [comment]
> The blue outline is part of the browser's user interface that indicates that a focusable item has been selected. Because MathJax expressions allow access to the MathJax contextual menu via the space key and to its expression explorer via the return key (when the explorer tool is activated), the MathJax expressions are focusable (they accept key input) and are part of the tab sequence of focusable items. This is important for people with assistive needs (like those with mobility issues that use keyboard controls rather than mouse clicks). Removing the blue indicator would negatively impact those users.
> 
> If you feel you really **must** turn these off, you could add
> 
> ```css
> mix-container:focus {
>   outline: none;
> }
> ```
> 
> to your CSS.

can i do some settings in MathJax by force, eg close some switch, set some color to transparent and so on

**Comment by dpvc** [comment]
Sorry, autocorrect changed my "mjx" to "mix" and I didn't catch it.  The CSS should be

``` css
mjx-container:focus {
  outline: none;
}
```

**Comment by big-zZ** [comment]
> Sorry, autocorrect changed my "mjx" to "mix" and I didn't catch it. The CSS should be
> 
> ```css
> mjx-container:focus {
>   outline: none;
> }
> ```

thank you very very very much!!!  it works!~~
