### ISSUE TITLE
Unicode sub- and superscripts

### ISSUE THREAD

**Issue by randolf-scholz** [mathjax/MathJax#2813]
**Is your feature request related to a problem? Please describe.**

Unicode supports a number of [sub- and superscript characters](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts) (unfortunately not the whole Latin alphabet but maybe sometimes in the future.) I find myself using these often when writing comments for scientific computing code, because they are shorter and more easily readable than the expanded form:

`xₜ₊₁ ← xₜ - η∇f(xₜ)` simply reads a lot better than `x_{t+1} \leftarrow x_{t} - \eta \nabla f(x_{t})` in source code.

(If you are wondering how to even type these I use a [custom AutoKey setup](https://github.com/randolf-scholz/autokey_julia_unicode).)

**Describe the solution you'd like**

It would be super cool if MathJax natively supported these characters, i.e. when a regular character is followed by a subscript character interpret it as if it were a real LaTeX subscript.

**Additional context**

I am aware of the WWW-consortium quote on the wiki page, however, I kind of disagree, to me, it seems that the consortium might have overlooked the use case when text is both viewed as source code and as rendered text. In particular, this happens when writing mathematical formulas in docstrings that might be viewed both from console or in an autogenerated documentation.

Secondly one can also consider what would be the disadvantages of supporting this behaviour, and quite frankly there doesn't seem to be too much speaking against it. I doubt anyone will miss a horribly formatted `$a₂$` compared to the beautifully formatted `$a_{2}$`.

**Comment by dpvc** [comment]
I gave an example of how to do this for superscripts via a TeX input pre-filter in [#2708](https://github.com/mathjax/MathJax/issues/2708#issuecomment-861779454).  You could augment that to handle subscripts as well.
