### ISSUE TITLE
\\img not working now. 

### ISSUE THREAD

**Issue by JeongChanYoung** [mathjax/MathJax#2815]
### Issue Summary

\\img TEX code not working suddenly.
I would like to know what is the reason.

### Steps to Reproduce:

```
"\\img["+(-0.6*exam_font_size)+"px]["+(exam_font_size*3)+"px]["+(exam_font_size*2)+"px]{http://www.modoomath.com/img/blank2.png}";
```

This is console massage,
`Failed to load resource: the server responded with a status of 404 (Not Found)       /[img]/img.js?V=2.7.1:1 `

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: v3.x
* Client OS: Window 7
* Browser: Chrome 29.0.1547.57

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and include them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by dpvc** [comment]
The console message you provided suggests that you have not configured the path to the `img.js` file correctly.  You have not provided your configuration, so I can't tell you what to change.  If you can give more details, we can better advise you what to do.

Also, I see that you are using version 2.7.1, which is quite out of date.  You may want to update to the latest version 2 release, which is 2.7.9.  (The current main release is 3.2.0.)
