### ISSUE TITLE
Bits of mfracs are sometimes getting cut off slightly

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2817]
### Issue Summary

I have come across a few cases where tiny bits of mfracs are sometimes getting cut off slightly. Any idea what could be causing this and if there would be a way to fix it?

Here are some examples:

Example 1: The subscript "C" in the mfrac is slightly cut off
In Chrome at 100% zoom:

`<mrow>
    <mrow>
      <mstyle indentshift="3em" indentshiftlast="3em">
        <msub>
          <mrow>
            <mi mathvariant="italic">H</mi>
          </mrow>
          <mrow>
            <mi>Break</mi>
          </mrow>
        </msub>
      </mstyle>
    </mrow>
  </mrow>
  <mrow>
    <mo linebreak="nobreak">=</mo>
    <mstyle indentshift="3em" indentshiftlast="3em">
      <mo>&#x2212;</mo>
      <msub>
        <mrow>
          <mi mathvariant="italic">R</mi>
        </mrow>
        <mrow>
          <mi mathvariant="normal">C</mi>
        </mrow>
      </msub>
      <mo linebreak="nobreak" lspace="0em" rspace=".25em">&#x2061;</mo>
      <mi>cos</mi>
      <mo linebreak="nobreak" lspace="0em" rspace=".25em">&#x2061;</mo>
      <mi>&#x3B8;</mi>
      <mrow>
        <mo stretchy="true">{</mo>
        <mn>1</mn>
        <mo>+</mo>
        <mfrac>
          <mrow>
            <mn>3</mn>
          </mrow>
          <mrow>
            <msup>
              <mrow>
                <mo stretchy="true">(</mo>
                <mstyle displaystyle="true">
                  <mfrac>
                    <mrow>
                      <mn>32</mn>
                      <msub>
                        <mrow>
                          <mi mathvariant="italic">R</mi>
                        </mrow>
                        <mrow>
                          <mi mathvariant="normal">P</mi>
                        </mrow>
                      </msub>
                      <mo linebreak="nobreak" lspace="0em" rspace=".25em">&#x2061;</mo>
                      <mi>cos</mi>
                      <mo linebreak="nobreak" lspace="0em" rspace=".25em">&#x2061;</mo>
                      <mi>&#x3B8;</mi>
                    </mrow>
                    <mrow>
                      <msub>
                        <mrow>
                          <mi mathvariant="italic">R</mi>
                        </mrow>
                        <mrow>
                          <mi mathvariant="normal">C</mi>
                        </mrow>
                      </msub>
                    </mrow>
                  </mfrac>
                </mstyle>
                <mo stretchy="true">)</mo>
              </mrow>
              <mrow>
                <mn>1</mn>
                <mo>/</mo>
                <mn>3</mn>
              </mrow>
            </msup>
          </mrow>
        </mfrac>
        <mo stretchy="true">}</mo>
      </mrow>
    </mstyle>
  </mrow>`

![image](https://user-images.githubusercontent.com/82107944/148844794-e30b2e6a-abf4-4e1e-b6e4-a9d57a38a88b.png)

Note, if I click to open up the zoom pop-up box, it's not cut off in that case:

![image](https://user-images.githubusercontent.com/82107944/148844993-a5c88546-3f32-47fe-ae17-750a1e3eeac2.png)

Example 2: The "E" in the mfrac is slightly cut off
In Chrome at 100% zoom:

`<mrow>
    <mrow>
      <mstyle indentshift="3em" indentshiftlast="3em">
        <mi>&#x3C7;</mi>
      </mstyle>
    </mrow>
  </mrow>
  <mrow>
    <mo linebreak="nobreak">=</mo>
    <mstyle indentshift="3em" indentshiftlast="3em">
      <msub>
        <mrow>
          <mi>&#x3C9;</mi>
        </mrow>
        <mrow>
          <mn>0</mn>
        </mrow>
      </msub>
      <mi>exp</mi>
      <mrow>
        <mo stretchy="true">(</mo>
        <mo>&#x2212;</mo>
        <mfrac>
          <mrow>
            <mi>E</mi>
            <mo>&#x2212;</mo>
            <mi>w</mi>
          </mrow>
          <mrow>
            <msub>
              <mrow>
                <mi>k</mi>
              </mrow>
              <mrow>
                <mi mathvariant="normal">B</mi>
              </mrow>
            </msub>
            <mi>T</mi>
          </mrow>
        </mfrac>
        <mo stretchy="true">)</mo>
      </mrow>
    </mstyle>
  </mrow>`

![image](https://user-images.githubusercontent.com/82107944/148845101-793a8e13-11d2-4c5c-b04a-e2e4d8ee02eb.png)

Again, if I click to open up the zoom pop-up box, it's not cut off in that case:

![image](https://user-images.githubusercontent.com/82107944/148845178-73ef6ee2-0235-4a6c-8de1-e69fe1dc6ef9.png)

Example 3: The subscript "g" in the mfrac within mtable is slightly cut off
In Chrome at 125% zoom (issue not present at 100 or 110%):

`<mrow>
    <mrow>
      <mstyle indentshift="3em" indentshiftlast="3em">
        <mi>S</mi>
      </mstyle>
    </mrow>
  </mrow>
  <mrow>
    <mo linebreak="nobreak">=</mo>
    <mstyle indentshift="3em" indentshiftlast="3em">
      <mo stretchy="true">{</mo>
      <mrow>
        <mstyle indentshiftfirst="0em" indentshift="1em" indentshiftlast="1em">
          <mtable columnalign="left" displaystyle="true">
            <mtr>
              <mtd>
                <mrow>
                  <mn>0.39</mn>
                  <msqrt>
                    <mrow>
                      <mfrac>
                        <mrow>
                          <mn>2</mn>
                          <mi mathvariant="normal">&#x394;</mi>
                          <mi>P</mi>
                        </mrow>
                        <mrow>
                          <msub>
                            <mrow>
                              <mi mathvariant="normal">&#x3C1;</mi>
                            </mrow>
                            <mrow>
                              <mi>l</mi>
                            </mrow>
                          </msub>
                        </mrow>
                      </mfrac>
                    </mrow>
                  </msqrt>
                  <mi>t</mi>
                </mrow>
              </mtd>
              <mtd>
                <mrow>
                  <mi>t</mi>
                  <mrow>
                    <mo>&lt;</mo>
                    <mstyle indentshift="3em" indentshiftlast="3em">
                      <msub>
                        <mrow>
                          <mi>t</mi>
                        </mrow>
                        <mrow>
                          <mi>b</mi>
                        </mrow>
                      </msub>
                    </mstyle>
                  </mrow>
                </mrow>
              </mtd>
            </mtr>
            <mtr>
              <mtd>
                <mrow>
                  <mn>2.95</mn>
                  <msup>
                    <mrow>
                      <mrow>
                        <mo stretchy="true">(</mo>
                        <mrow>
                          <mfrac>
                            <mrow>
                              <mi mathvariant="normal">&#x394;</mi>
                              <mi>P</mi>
                            </mrow>
                            <mrow>
                              <msub>
                                <mrow>
                                  <mi mathvariant="normal">&#x3C1;</mi>
                                </mrow>
                                <mrow>
                                  <mi>g</mi>
                                </mrow>
                              </msub>
                            </mrow>
                          </mfrac>
                        </mrow>
                        <mo stretchy="true">)</mo>
                      </mrow>
                    </mrow>
                    <mrow>
                      <mn>0.25</mn>
                    </mrow>
                  </msup>
                  <msup>
                    <mrow>
                      <mi>d</mi>
                    </mrow>
                    <mrow>
                      <mn>0.5</mn>
                    </mrow>
                  </msup>
                  <msup>
                    <mrow>
                      <mi>t</mi>
                    </mrow>
                    <mrow>
                      <mn>0.5</mn>
                    </mrow>
                  </msup>
                </mrow>
              </mtd>
              <mtd>
                <mrow>
                  <mi>t</mi>
                  <mrow>
                    <mo>&gt;</mo>
                    <mstyle indentshift="3em" indentshiftlast="3em">
                      <msub>
                        <mrow>
                          <mi>t</mi>
                        </mrow>
                        <mrow>
                          <mi>b</mi>
                        </mrow>
                      </msub>
                    </mstyle>
                  </mrow>
                </mrow>
              </mtd>
            </mtr>
          </mtable>
        </mstyle>
      </mrow>
      <mo stretchy="true">}</mo>
    </mstyle>
  </mrow>`

![image](https://user-images.githubusercontent.com/82107944/148845598-9f94368d-f731-4aed-9b28-54de2f0a0827.png)

### Technical details:

MathJax Version: master - latest commit: MathJax.js v2.7.9
Client OS: Windows
Browser: Chrome Version 96.0.4664.110 (Official Build) (64-bit)
Renderer: HTML-CSS

**Comment by dpvc** [comment]
The HTML-CSS output is the oldest and most fragile of the MathJax output formats.  Its layout used large heights (for technical regions) and clip regions to reduce those heights to their proper amounts.  But that makes its output susceptible to rounding-off issues that are browser, OS, font, and size specific, and I suspect that that is what you are seeing here.

You can try adding

``` css
.MathJax * {
  clip: initial ! important
}
```

and see if that helps.  This is just for testing purposes; you probably don't want to do this in production because the tall heights would cause the MathJax equations to overlap (invisibly) items above the expressions, so that links or other clickable things might become inaccessible, as they are "underneath" the math.

If that turns out to be the issue, we may be able to work something out.

**Comment by jlangACS** [comment]
> You can try adding
> 
> ```css
> .MathJax * {
>   clip: initial ! important
> }
> ```
Is this code meant as CSS or part of MathJax config?  I have tried it as CSS, but don't see any change in the text being cropped
![image](https://user-images.githubusercontent.com/97540105/148981243-d9a9aea0-f4a4-4529-b89a-c591f8fb1c5e.png)

**Comment by dpvc** [comment]
Yes, it is CSS.  Can you view the DOM using the browser tools and see if the clip regions are actually being overridden by the CSS?  You should see the original clip specifications, but they should be crossed out except for the new rule that you have given above.

**Comment by jlangACS** [comment]
Yes, I see the override taking effect.
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/97540105/149015112-aa15e34b-b509-4e37-b675-91da04cf6b6f.png">

**Comment by dpvc** [comment]
OK, then it seems that it is not the clipping after all.  

Is it possible to share a document where this is occurring?  You can email directly, rather than post here, if you wish.  

Are you using Windows 11 or Windows 10?

**Comment by dpvc** [comment]
For others seeing this, it turns out the issue was with other CSS on the page that was affecting the MathJax output.
