### ISSUE TITLE
vertical bar height issue

### ISSUE THREAD

**Issue by gbala2412** [mathjax/MathJax#2820]
Vertical bars grow in unwanted places. Check  |z|.

`<math display="block" overflow="scroll">
                  <mrow>
                     <mi>u</mi>
                     <mo stretchy="false">(</mo>
                     <mi>t</mi>
                     <mo stretchy="false">)</mo>
                     <mtext> </mtext>
                     <mtext> </mtext>
                     <mtext> </mtext>
                     <mtext> </mtext>
                     <mo>=</mo>
                     <msubsup>
                        <mrow>
                           <mo stretchy="true">{</mo>
                           <mtext>Kpz</mtext>
                           <mo>+</mo>
                           <mtext>Kddzdt</mtext>
                           <mo>+</mo>
                           <mo stretchy="true">∫</mo>
                           <mtext>Kizdtif</mtext>
                           <mo>|</mo>
                           <mi>z</mi>
                           <mo>|</mo>
                           <mo>≤</mo>
                           <mtext>ZlimV</mtext>
                           <mo stretchy="true">{</mo>
                           <mtable>
                              <mtr>
                                 <mtd>
                                    <mtable>
                                       <mtr>
                                          <mtd>
                                             <mtable>
                                                <mtr>
                                                   <mtd>
                                                      <mtable>
                                                         <mtr>
                                                            <mtd>
                                                               <msub>
                                                                  <mrow>
                                                                     <mi>V</mi>
                                                                  </mrow>
                                                                  <mi mathvariant="normal">max</mi>
                                                               </msub>
                                                               <mtext> </mtext>
                                                               <mtext> </mtext>
                                                               <mtext> </mtext>
                                                               <mi mathvariant="normal">sgn</mi>
                                                               <mo stretchy="false">(</mo>
                                                               <mi mathvariant="normal">z</mi>
                                                               <mo stretchy="false">)</mo>
                                                            </mtd>
                                                         </mtr>
                                                      </mtable>
                                                   </mtd>
                                                </mtr>
                                             </mtable>
                                          </mtd>
                                          <mtd>
                                             <mi mathvariant="normal">if</mi>
                                             <mo>|</mo>
                                             <mi>z</mi>
                                             <mo>|</mo>
                                             <mo>&gt;</mo>
                                             <mi mathvariant="normal">Zlim</mi>
                                             <mi mathvariant="normal">if</mi>
                                          </mtd>
                                       </mtr>
                                    </mtable>
                                    <mrow>
                                       <mo>|</mo>
                                       <mi>z</mi>
                                       <mo>|</mo>
                                    </mrow>
                                    <mo>&gt;</mo>
                                    <msub>
                                       <mi>Z</mi>
                                       <mi mathvariant="normal">lim</mi>
                                    </msub>
                                 </mtd>
                              </mtr>
                              <mtr>
                                 <mtd>
                                    <mtable>
                                       <mtr>
                                          <mtd>
                                             <msub>
                                                <mi>K</mi>
                                                <mi>p</mi>
                                             </msub>
                                             <mi mathvariant="normal">z</mi>
                                             <mtext>&nbsp;</mtext>
                                             <mo>+</mo>
                                             <msub>
                                                <mi>K</mi>
                                                <mi>d</mi>
                                             </msub>
                                             <mfrac>
                                                <mrow>
                                                   <mi>d</mi>
                                                   <mi>z</mi>
                                                </mrow>
                                                <mrow>
                                                   <mi>d</mi>
                                                   <mi>t</mi>
                                                </mrow>
                                             </mfrac>
                                             <mo>+</mo>
                                             <mo>∫</mo>
                                             <mrow>
                                                <msub>
                                                   <mi>K</mi>
                                                   <mi>i</mi>
                                                </msub>
                                                <mi>z</mi>
                                                <mi>d</mi>
                                                <mi>t</mi>
                                             </mrow>
                                          </mtd>
                                          <mtd>
                                             <mi mathvariant="normal">i</mi>
                                             <mi mathvariant="normal">f</mi>
                                          </mtd>
                                       </mtr>
                                    </mtable>
                                    <mrow>
                                       <mo>|</mo>
                                       <mi mathvariant="normal">z</mi>
                                       <mo>|</mo>
                                    </mrow>
                                    <mo>≤</mo>
                                    <msub>
                                       <mi>Z</mi>
                                       <mi mathvariant="normal">lim</mi>
                                    </msub>
                                 </mtd>
                              </mtr>
                           </mtable>
                        </mrow>
                        <mrow></mrow>
                        <mrow></mrow>
                     </msubsup>
                  </mrow>
               </math>`

**Comment by pkra** [comment]
This is the expected behavior as per spec - stretchy is the default. As with parts of your sample, you need to add `stretchy="false"` to the `|` operators if you don't want them to stretch.

**Comment by dpvc** [comment]
The alternative to adding `stretchy="false"` is to put an `mrow` around the absolute values:

``` xml
<mrow>
  <mo>|</mo>
  <mi>z</mi>
  <mo>|</mo>
</mrow>
```

as stretchy delimiters only stretch to match the size of the `mrow` in which they appear.  This is the construction recommend by the specification.
