### ISSUE TITLE
Get unique id attribute for <path> element produced by converting to SVG process

### ISSUE THREAD

**Issue by imaphatduc** [mathjax/MathJax#2821]
### Issue Summary

I am using tex to svg feature of MathJax, specifically through this [repo](https://github.com/CreatifCreateur/TeX-to-SVG). I kind of having a problem like this person has in his/her [issue](https://github.com/mathjax/mathjax-node-cli/issues/10). I've read it and the solution there is not compatible to my issue, as I'm writing in JavaScript rather than the command line. So how can I get the unique ID (ie unique prefix in id attribute) for each of `<path>` element? I tried to set a string to the `localID` field in the `options` object but the result ids has no change.

(I think my issue related to the source code, so I won't include technical details here)

**Comment by dpvc** [comment]
The `localID` property goes in the `svg` block, not the `options` block.  See the [documentation](https://docs.mathjax.org/en/latest/options/output/svg.html?highlight=localID#the-configuration-block) for that.  I suspect that is what you need to use, but there is not enough information about what you actually are trying to do to tell.  If you can give more precise details about what your goal is, and what you have tried, perhaps we can give you some better answers.
