### ISSUE TITLE
Loading common CSS only once

### ISSUE THREAD

**Issue by josephjohnston** [mathjax/MathJax#2826]
I'm server-side rendering math (for an SPA) and would like to load CSS common across renderings only once, and subsequently load CSS on a per-rending basis. How best to do this?
I'm using the ['direct' tex2chtml approach](https://github.com/mathjax/MathJax-demos-node/blob/master/direct/tex2chtml) from the MathJax node demos.
Trying to separate more common styles from more rendering-instance-dependent styles, I look inside [`chtml.styleSheet(html)`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml.ts#L170).
I see styles come from four different groups:
1. [`chtml.commonStyles`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml.ts#L69). These seem clearly instance-independent styles.
2. [`html.getStyles()`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/handlers/html/HTMLDocument.ts#L284). These seem clearly instance-dependent styles.
3. [`chtml.addWrapperStyles(chtml.cssStyles)`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/common/OutputJax.ts#L479). I find these styles hardcoded under [chtml/Wrappers](https://github.com/mathjax/MathJax-src/tree/master/ts/output/chtml/Wrappers). Since they are hardcoded I take them to be instance-independent.
4. [`chtml.font.styles`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/FontData.ts#L175). I see 'defaultStyles' [here](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/FontData.ts#L89) and [here](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/fonts/tex.ts#L167), and 'defaultFonts' [here](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/FontData.ts#L99) and [here](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/fonts/tex.ts#L262), all hardcoded and thus instance-independent. I also see [delimiterStyles](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/FontData.ts#L232) and [charStyles](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/output/chtml/FontData.ts#L350) dynamically computed, so I take them to be instance-dependent. (But why are you styling delimiters? If only relevant to parsing I won't be using them.)

Suppose I extract all hardcoded styles found in groups 1, 3, 4 as common CSS. Suppose I extract the dynamic styles from steps 2 and 4 per each instance as below. How effective is this solution? Does it extract all CSS?
```js
const convert = (str, options) => {
    const node = html.convert(str, options);
    // chtml.setDocument(html); // seems only necessary in setup
    chtml.cssStyles.clear();
    // group 2
    for (const styles of html.getStyles()) {
        chtml.cssStyles.addStyles(styles);
    }
    // group 4
    chtml.cssStyles.addStyles(chtml.font.updateStyles({}));
    return {
        html: adaptor.outerHTML(node),
        css: chtml.cssStyles.cssText,
    };
};
```

**Comment by dpvc** [comment]
I think there is an easier way to do what you are trying to do, without having to know where different kinds of styles come from.  The CHTML output jax already has the ability to produce the new CSS needed to accommodate a newly typeset expression, and you can leverage those to do what you are trying to do.

If you do


``` js
const commonCSS = adaptor.textContent(chtml.styleSheet(html));
```

right after creating the html document, that will give you the CSS that is common to all documents.  Then your convert function could be

``` js
const {CssStyles} = require('mathjax-full/js/util/StyleList.js');

const convert = (str, options) => {
    chtml.clearCache();
    const node = html.convert(str, options);
    const styles = new CssStyles();
    chtml.addWrapperStyles(styles);
    chtml.updateFontStyles(styles);
    return {
        html: adaptor.outerHTML(node),
        css: styles.getStyleRules().join('\n')
    };
};
```

Leave out the `chtml.clearCache()` call if you want the difference from the previously typeset expression(s).

Note that the CSS will contain what is needed for the newly typeset math, and that can include the CSS for the wrappers that are used.  That is, if you used a fraction, it will include the CSS needed for fractions in general.  If you want to force all the wrapper CSS to be in the `commonCSS` value, then you can use

``` js
const {CssStyles} = require('mathjax-full/js/util/StyleList.js');

//
//  Mark all wrappers as used (so their CSS will be included in initial stylesheet)
//
for (const kind of chtml.factory.getKinds()) {
  chtml.wrapperUsage.add(kind);
}
const commonCSS = adaptor.textContent(chtml.styleSheet(html));

const convert = (str, options) => {
    chtml.clearCache();
    const node = html.convert(str, options);
    const styles = new CssStyles();
    chtml.updateFontStyles(styles);
    return {
        html: adaptor.outerHTML(node),
        css: styles.getStyleRules().join('\n')
    };
};
```

(note that the chtml.addWrapperStyles(styles)` call has been removed).  This will get you all the structural CSS in the `commonCSS` variable, and only he character CSS in the return value from the `convert()` function.

> why are you styling delimiters?

These styles are for multi-character assemblies for delimiter sizes that are larger than the largest available fixed size in the font.  These require CSS to lay out the multiple characters that are used to create the large version of the delimiter.  Because different delimiters use different pieces to create the assembly, these have character-specific CSS.

**Comment by josephjohnston** [comment]
@dpvc Thank you so much for a clarified solution. I will include wrapper styles in the initial stylesheet. But what about group 2, that is [`html.getStyles()`](https://github.com/mathjax/MathJax-src/blob/2dd53ce6c8af3c9cceba0baf014ea9b065130774/ts/handlers/html/HTMLDocument.ts#L284), described in comments as 'document-specific styles.' Is that only relevant when typesetting a whole page rather than just math strings?

**Comment by josephjohnston** [comment]
@dpvc Thank you so much for a clarified solution. I will include wrapper styles in the initial stylesheet. But what about group 2, that is html.getStyles(), described in comments as 'document-specific styles.' It's empty in the initial CSS, so I imagine it's instance-dependent. Or is it only relevant when typesetting a whole page rather than just math strings?

**Comment by dpvc** [comment]
The styles from `html.getStyles()` are included in the initial CSS, if there are any.  This is a mechanism for extensions to add CSS if they need it.  For example, the `a11y/assistive-mml` extension adds some CSS, but if you aren't loading that extension, you won't get that CSS.  Currently, I think that is the only one that uses this mechanism.

In any case, if there is any CSS from there, it will be included in the initial stylesheet from `chtml.styleSheet()`.

**Comment by josephjohnston** [comment]
I see. Appreciate your help.
