### ISSUE TITLE
Use physics package would break brackets

### ISSUE THREAD

**Issue by abnerlee** [mathjax/MathJax#2831]
See demo in https://codepen.io/abnerlee/pen/BamQZrp

The size of `()` seems incorrect, but if you remove `physics` package, `()` looks correctly paried.

**Comment by dpvc** [comment]
Thanks for the report.  The code that determines the argument is matching the wrong close parenthesis.

One work-around would be to use additional braces to "hide" the inner parentheses.  For example `\exp({(\frac{a}{a}a)}{a})` would be a way to get the desired result from your codepen expression.

**Comment by abnerlee** [comment]
@dpvc Hi,

If you input $$\mathtt{9(A)3(AB)CCD}$$ on https://codepen.io/abnerlee/pen/BamQZrp you can see the brackets is still in different size.

It renders fine if physics package is not used.

**Comment by dpvc** [comment]
Please don't add a new issue to a closed tracker, as that makes it harder to manage the issue and its history.  I will start a new issue for this.
