### ISSUE TITLE
The minus symbol in MathJax.tex2mml result is different with the symbol in a MathJax rich text editor.

### ISSUE THREAD

**Issue by weihaopeng** [mathjax/MathJax#2857]
### Issue Summary

The minus symbol in MathJax.tex2mml result is different with the symbol in a MathJax rich text editor.

### Steps to Reproduce:

When I use `MathJax.tex2mml('16-9=')`, I get `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">\n  <mn>16</mn>\n  <mo>&#x2212;</mo>\n  <mn>9</mn>\n  <mo>=</mo>\n</math>`.

I noticed that the minus symbol is Hex code `&#x2212;`. In my application, the next step is put the mml in a tinymce editor, then user can edit, and finally search the mml in a database.

If I add a minus symbol using the tinymce editor, I get `&#x002D;`, which is also the symbol `-` , rather than `&#x2212;`.

Is there any config or option or parser to get `&#x002D;` as minus symbol in `MathJax.tex2mml('16-9=')`? Or can I have a map about this?

### Technical details:

* MathJax2 and MathJax3
* Browser: Chrome 29.0.1547.57

### Supporting information:

I use mathtype editor in [wiris demo](https://demo.wiris.com/mathtype/en/developers.php), then I input minus symbol by click the button. The symbol is `- (&#x002D;)`.

**Comment by dpvc** [comment]
As you point out, the minus sign is U+2212, and that is why MathJax TeX input produces that in its MathML output.  The remapping of U+002D to U+2212 is handled through a TeX character map, and you can modify it using the following configuration in v3:

``` javascript
MathJax = {
  startup: {
    ready() {
      const {MapHandler} = MathJax._.input.tex.MapHandler;
      MapHandler.getMap("remap").map.delete('-');
      MathJax.startup.defaultReady();
    }
  }
}
```

The output processors also convert U+002D to U+2212 when used as the only character inside an `<mo>`, so the typeset output will still be the same.
