### ISSUE TITLE
The style `border-spacing` of parent element affects fractions rendering

### ISSUE THREAD

**Issue by kwankyu** [mathjax/MathJax#2861]
This is observed with MathJax3 with CHTML rendering. For example,
```
      <table style="border-spacing:20px">
          <tr><td><span>$\frac{1}{2}$</span></td></tr>
      </table>   
```
display the fraction with too much spacing. SVG rendering is okay.

**Comment by dpvc** [comment]
MathJax uses `display:table` to lay out the fraction, and so the `border-spacing` from your table is affecting that.  A work-around for now is to set

``` css
mix-math {
  border-collapse: collapse
}
```

in your page's CSS.  MathJax resets a number of CSS properties to avoid bleed-through from the rest of the page, but that is not one that gets reset.  I will have to add it to the list of properties that are set for MathJax's output.

**Comment by kwankyu** [comment]
Thank you for the quick comment!

**Comment by kwankyu** [comment]
Thank you for the fix!
