### ISSUE TITLE
Mathjax3 renders slow than expected

### ISSUE THREAD

**Issue by kwankyu** [mathjax/MathJax#2862]
We are moving from mathjax2 to mathjax3 (https://trac.sagemath.org/ticket/25833). 

Betraying our expectations, mathjax3 renders maths sluggish than mathjax2. The following screen shot shows how resources are loaded to the chrome browser (mathjax is local, not from CDN). As I understand it, the woff fonts are loaded lately, and this seems the cause of slow rendering. Is this normal? Is there something that we (or you) can do with this? 
![Screen Shot](https://user-images.githubusercontent.com/1456101/163082034-18e4f7b9-d2f1-4a31-b0d0-0974d86d5a4f.png)

**Comment by dpvc** [comment]
> the woff fonts are loaded lately, and this seems the cause of slow rendering

I suppose it depends on what you mean by "caus[ing] the slow rendering".  The expressions certainly are not fully rendered unto the fonts are loaded, but most of the work for rendering is done before that, and the DOM elements are in place before the fonts are loaded (as I recall, most browsers don't download a font until it is actually called for, even if there is CSS that specifies the `@font-face` declaration).

It is true that MathJax v3 does insert the CSS for the expressions until after they are processed (the CSS is dependent on the content of the expressions), and so the fonts won't load until after that.  Your waterfall diagram does show that, but it doesn't suggest to me that the font loading is the issue.  Under normal circumstances, MathJax will not do any typesetting until after the DOMContentLoaded event occurs, so its typesetting should be occurring between the blue line at 773ms and the beginning of the font loading at just after 819ms.  The real question is what is happening in the large gap between the end of your index.js processing, and the DOMContentLoaded event (perhaps there are other items not shown in your image?).  That seems to be what is holding things up.  The fonts seem to be loaded relatively quickly after they are requested, and MathJax's typesetting should be happening between the blue and red vertical lines.

It is also true that MathJax v2 would typeset a few expressions and then display them, and then typeset more, while MathJax 3 typesets the entire page before anything is displayed.  That might lead to a slower appearance of the math if the page includes a lot of math (and you are typesetting the whole page at once).  MathJax v3 includes a [lazy typesetting extension](https://docs.mathjax.org/en/latest/output/lazy.html), however, that will only typeset what is on screen and typeset other expressions as they become visible.  That improves the results for most larger pages.  So you may want to try that out on your pages and see if that works better for you.

**Comment by kwankyu** [comment]
> perhaps there are other items not shown in your image?

They are all items shown to me.

> The real question is what is happening in the large gap between the end of your index.js processing, and the DOMContentLoaded event . That seems to be what is holding things up. 

I see. So the large gap (something not related with mathjax) and the difference in typesetting behaviors of the mathjax3 from mathjax2 creates the "slow rendering".   

> MathJax v3 includes a [lazy typesetting extension](https://docs.mathjax.org/en/latest/output/lazy.html), however, that will only typeset what is on screen and typeset other expressions as they become visible. That improves the results for most larger pages. So you may want to try that out on your pages and see if that works better for you.

Thanks for the pointer. And many thanks for having created and maintaining MathJax!

**Comment by dpvc** [comment]
> And many thanks for having created and maintaining MathJax!

You are welcome.  I hope the lazy typesetter resolves your issues.
