### ISSUE TITLE
[SVG] \smash and CSS interference

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2863]
I don't think this qualifies as a bug but I ran into the following edge case and I thought it might be worth documenting.

In a project, the default CSS sets svg width to `auto`. This interferes with the SVG output for something like `$\smash {\overrightarrow {OP}}$`, significantly increasing its dimensions (this reproduces on mathjax.org#demo if you add `svg {width:auto}` to the styles).

In my case, it's easy enough to adjust the TeX source. But I wonder how to best handle this on the CSS end (in the case where changing the svg-width-auto rule is not feasible), i.e., adding a rule to set the width for the SVG output. Both max-content and fit-content help (and max-content seems the better fit to me). But perhaps you would suggest something else?

**Comment by dpvc** [comment]
Well, the only value for width that seems to work for me in Firefox is `revert-layer`.  I'm not very experienced with these special values that reset the properties, so I don't know if that would resolve the issue in all cases and browsers, but adding

``` css
mjx-container[jax="SVG"] > svg {
  width: revert-layer;
}
```

seems to do it for me in Firefox and Chrome.  

There is undoubtedly lots of CSS settings like this that will mess up MathJax output.  It seems to me that someone who uses CSS that sets global properties for SVG element and is using MathJax's SVG output, needs to be careful about that.  One could, for example, use

``` css
:not(mjx-container) > svg {
  width: auto;
}
```

to not apply the rule to MathJax output, for example.  But thanks for making a note of this particular issue; others may find it useful.

**Comment by pkra** [comment]
> Well, the only value for width that seems to work for me in Firefox is revert-layer. 

Right, the other default css makes the other ones work for me. I should've mentioned revert-layer but layers are so incredibly new and unsupported https://caniuse.com/?search=revert-layer that I didn't consider them (it will be hugely useful for MathJax to specify its own layer down the line, I suspect).

I realize that it's really a bit weird that the width attribute on the SVG is overruled. So another workaround is to add the width to the SVG output's style attribute.

Anyway, it's a weird edge case and it's extra unlucky not to control the other CSS. 

Thanks for taking the time to respond.
