### ISSUE TITLE
My website cannot use {1 - q}

### ISSUE THREAD

**Issue by hiepsocool** [mathjax/MathJax#2867]
**My website cannot use {1 - q}**
_Hi MathJax,_
I thank you guys for the awesome add-ons, I used yours via a plugin "MathJax-LaTeX Version 1.3.11" for WordPress Version 5.9.3 website.
But today I checked that my website when using {1 - q} or similar functions does not give the result "1 - q", instead the result "1q". So I lost the "-" in the function I wanted to use.
So is there any way to fix the above problem?
I am using "MathJax-LaTeX" plugin and latest version WordPress.
You can see my specific article at website: https://hoctaphay.com/bai-tap-5-trang-122-sgk-dai-giai-tich-lop-11.html
I look forward to hearing from you soon.
Sincerely thanks,

**Comment by dpvc** [comment]
The site you link to displays correctly for me (though the URL contained a misspelling, which I have corrected).

The email you sent included a screen shot that showed the minus sign was missing from the original TeX commands, so naturally, MathJax didn't display one.  It seems that you may have corrected the original source, and that things are working now, so I'm closing the issue.  If you are still having problems, I will reopen, but you will need to give more information about the browser and OS versions that you are using.
