### ISSUE TITLE
Section Number appearing in Equation Number

### ISSUE THREAD

**Issue by parhizkari** [mathjax/MathJax#2868]
Hi Davide
your example code above works in Mathjax 3.1.4 but not as expeted in v. 3.2.0.
When I use `<script src="https://cdn.jsdelivr.net/npm/mathjax@3.1.4/es5/tex-chtml.js"></script>` it is fine, but using `<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>` it writes in the console that "MathJax: Invalid option "tagFormat" (no default value)." So it resets the numbering at each section, but the section number disappear from equation number.

_Originally posted by @parhizkari in https://github.com/mathjax/MathJax/issues/2427#issuecomment-1120108244_

**Comment by dpvc** [comment]
I have answered your original comment.
