### ISSUE TITLE
MathJax.org hanging browser

### ISSUE THREAD

**Issue by drlippman** [mathjax/MathJax#2872]
### Issue Summary

When accessing MathJax.org or my own websites using MathJax via jsdelivr, I'm getting this error in the javascript console:

```
Uncaught TypeError: MathJax.loader.checkVersion is not a function
    <anonymous> https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/asciimath.js:1
    <anonymous> https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/asciimath.js:1
    <anonymous> https://cdn.jsdelivr.net/npm/mathjax@3/es5/input/asciimath.js:1
```

In Firefox, the error occurs but the page still works.  In Chrome (with a clear cache), the browser hangs and is inoperable. 

### Steps to Reproduce:

1. Visit mathjax.org

### Technical details:

* MathJax Version: 3.2.0 (jsdelivr still seems to still be sending 3.2.0 at the time of reporting)
* Client OS: Windows
* Browser: Chrome 101.0.4951.67

**Comment by drlippman** [comment]
I've noticed on my own pages this only happens if I use `https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js`, without a specific version number.  If I change it to https://cdn.jsdelivr.net/npm/mathjax@3.2.0/es5/startup.js` or `https://cdn.jsdelivr.net/npm/mathjax@3.2.1/es5/startup.js` it works fine.    

I can only guess maybe because 3.2.1 was just recently released, jsdelivr is mixing versions with the general `@3` designator or something?

**Comment by dpvc** [comment]
Yes, this is likely due to v3.2.1 migrating to the various end-node servers for jsdelivr, where some components are loading as 3.2.0 and some as 3.2.1.  It usually takes about 24 hours for everything to catch up.  I'm still getting version 3.2.0 for startup.js, and it looks like you are, too.  I don't know of any way to speed up the propagation to end nodes.

See the [announcement](https://www.mathjax.org/MathJax-v3.2.1-available/#availability-of-version-321) for more on this.

**Comment by jeffsims14** [comment]
I just started seeing Chrome and Safari hang on pages using the script `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js` together with: `MenuOptions: { settings: { explorer: true } }`. Setting explorer to `false` works fine. 
The console error is thrown in `a11y/semantic-enrich.js` and `a11y/explorer.js`. The error is `Uncaught TypeError: Cannot read properties of undefined (reading 'Sre')`

Not sure if it could be related to this issue? But if I target a specific version with `https://cdn.jsdelivr.net/npm/mathjax@3.2.1/es5/tex-mml-chtml.js` it works fine, even with the explorer menu option set to `true`.

**Comment by dpvc** [comment]
It is likely the same issue: mixed versions either in the browser cache or coming from jsdeliver as all the MathJax v3.2.1 files migrate to the various servers.

**Comment by joshhansen** [comment]
Specifically requesting version 3.2.1 resolved this for us, thanks

**Comment by Funfound** [comment]
Windows10/edge:
GET /MathJax-3.2.1/es5/sre/mathmaps/base.json net::ERR_FAILED

Uncaught (in promise) SyntaxError: Unexpected end of JSON input 
at JSON.parse (<anonymous>) 
at N (/MathJax-3.2.1/es5/a11y/sre.js:1:287648) 
at t.then.o.EnginePromise.loaded.<computed> (/MathJax-3.2.1/es5/a11y/sre.js:1:287387)

**Comment by dpvc** [comment]
@Funfound, this is not the same issue as the one in the original post.  Please start a separate issue tracker for it.

Can you verify that `/MathJax-3.2.1/es5/sre/mathmaps/base.json` exists on your server?  It sounds like it may be missing.

How did you obtain your MathJAx-3.2.1 directory?  is it from `npm install mathjax` or some other method?

**Comment by Funfound** [comment]
@dpvc
I use MathJax-3.2.1 at local directory and static html file：
C:\Python\MathJax-3.2.1\……
d:\……***.html
--------------
MathJax-3.2.1 is dowload from this site, and all file is ok! has checked!

**Comment by Funfound** [comment]
@dpvc
I use MathJax-3.2.1 at local directory and static html file：
C:\Python\MathJax-3.2.1\……
d:\……***.html
MathJax-3.2.1 is dowload from this site, and all file is ok! has checked!
and is ok when use C:\Python\MathJax-3.2.0\……

**Comment by Funfound** [comment]
\begin{pmatrix} -1&0&0&0\\ 0&1&0&0\\ 0&0&1&0\\ 0&0&0&1\\ \end{pmatrix}
write a "pmatrix". but it show me as this pic when use MathJax-3.2.0.
![Uploading image.png…]()
I don't known why.
so dowload MathJax-3.2.1, but it not work at all.

**Comment by Funfound** [comment]
@dpvc
and at online site: MathJax.org is not work too,
maybe are the same problems,
so reply here

**Comment by Funfound** [comment]
\begin{pmatrix} -1&0&0&0\ 0&1&0&0\ 0&0&1&0\ 0&0&0&1\ \end{pmatrix}
write a "pmatrix". when use MathJax-3.2.0，it show me as this pic
[Uploading image.png…](https://github.com/Funfound/test/blob/main/matrix.jpg)
Missing the middle part of "bracket" 
I don't known why. so dowload MathJax-3.2.1, but it not work at all.

**Comment by zorkow** [comment]
> I use MathJax-3.2.1 at local directory and static html file： C:\Python\MathJax-3.2.1\…… d:\……***.html MathJax-3.2.1 is dowload from this site, and all file is ok! has checked! and is ok when use C:\Python\MathJax-3.2.0\……

@Funfound  Are you using `file:///` protocol or `http://localhost`? 

`file` will not work as the `json` files are fetched via XML-Http-Request, which will give you a CORS error.

**Comment by Funfound** [comment]
> 
@zorkow
'file:///C:/Python/MathJax-3.2.0/es5/tex-chtml.js'
Don't worry about how to use，
because MathJax-3.2.0 work，Only the brackets of the matrix are not displayed normally，so I download and use MathJax-3.2.1

and MathJax.org is ok a few days ago

**Comment by Funfound** [comment]
@zorkow
I format the file base.json file and check. it seems ok!
mabe the javascript  json parse engine of sre.js has some problem，Or related to the version of json engine .

**Comment by Funfound** [comment]
mathjax.org
 is ok now
and 
https://mathjax.github.io/MathJax-demos-web/tex-chtml.html 
is ok too
-----------
they all not ok a few hours ago.

**Comment by Funfound** [comment]
"file:///C:/Python/MathJax-3.2.0/es5/tex-chtml.js"
