### ISSUE TITLE
Lazy typesetting in version 3.2.1 may create repeated labels

### ISSUE THREAD

**Issue by cebola2** [mathjax/MathJax#2873]
This a preliminary report (no minimal example) on a possible anomaly in version 3.2.1: in particular circumstances lazy typesetting may create error messages about repeated labels.

To see an example go to https://cdi2.palhoto.pt/test_1

Near the bottom of the page there are two equations labeled (2) and (3) and a few lines afterwards there is a collapsed section labeled "Mais detalhes".

On opening the page and waiting a bit no anomalies are detected. But then, if you open the collapsed section, duplicate label messages appear (also if you open the page and quickly slide to the bottom).

Cache cleaning has no effect on this behavior.

This is not present on version 3.2.0 as can be checked in https://cdi2.palhoto.pt/test

Reproduced both on Firefox 100.0 and Chrome 101.0.4951.64 on
System:    Kernel: 5.13.0-37-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal

**Comment by dpvc** [comment]
Thanks for the report.  I'll look into it and see what I can find out.  In the meantime, you might want to revert to version 3.2.0 for now.  I'll let you know what I come up with.

Sorry for the issue!

**Comment by cebola2** [comment]
I have reverted the site to 3.2.0 and edited links in the original report to point to a test page which runs 3.2.1, namely https://cdi2.palhoto.pt/test_1

**Comment by dpvc** [comment]
Sorry for the delay in getting this worked out (I was away for the last week).

It turns out that a reset that is being used to allow reprocessing of some expressions is actually resetting *every* expressions, and so they are being re-typeset when they shouldn't be, and that means the ones with labels are being re-compiled, causing the errors that you are seeing.  I will make a PR to resolve the issue, but in the meantime, you can use

``` js
MathJax = {
  loader: {
    load: ['ui/lazy'],
  },
  startup: {
    ready() {
      MathJax.startup.defaultReady();
      const mathItem = MathJax.startup.document.options.MathItem;
      class myItem extends mathItem {
        state(state, restore = false) {
          if (restore !== null) super.state(state, restore);
          return super.state();
        }
      }
      MathJax.startup.document.options.MathItem = myItem;
    }
  }
};
```

to work around it for now.

**Comment by cebola2** [comment]
I have created https://cdi2.palhoto.pt/test_2.php as a test for 3.2.2

It works!

**Comment by dpvc** [comment]
Thanks for the confirmation!
