### ISSUE TITLE
mathml2svg() throwing error on latest version

### ISSUE THREAD

**Issue by svejdani** [mathjax/MathJax#2879]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.
Mathjax function mathml2svg(mathml) throws an error. This is happening after the latest release. Script that is being used is 
'https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-svg.js'
![image](https://user-images.githubusercontent.com/105304186/170767906-392f3e07-6570-4217-a630-a3bb40ea3410.png)

### Steps to Reproduce:

1. Load Mathjax using latest version script 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-svg.js'
2. Use the mathjax method mathml2svg()
3. mathml2svg throws an error

Downgrading to version 3.1 resolves the issue. Conversion to svg was working fine before latest 3.2.1 release. 

### Technical details:

* MathJax Version: 3.2.1 (latest commit: f3aaf3a2a3e964df2770dc4aaaa9c87ce5f47e2c)
* Client OS: Mac OS X 11.2.3 
* Browser: Chrome 100.0.4896.127

**Comment by dpvc** [comment]
I am not able to reproduce the issue.  The `mathml2svg()` seems to sower for me.  The message you are receiving suggests that you are passing `mathml2svg()` a MathML string that includes a `<div>` tag, which will cause the error that you see.  We do not currently support HTML embedded in MathML, though there is a [pull request](https://github.com/mathjax/MathJax-src/pull/781) to implement it that should be part of the next feature release later this summer.

**Comment by dpvc** [comment]
PS, if that's not it, then can you be more specific about the actual code you are using and the MathML that you are passing to `mathml2svg()`?
