### ISSUE TITLE
Blink when rendering

### ISSUE THREAD

**Issue by gaoyajiang** [mathjax/MathJax#2882]
https://user-images.githubusercontent.com/53201532/171353888-bddc7cc8-c5cf-45af-91e4-b789054990b8.mp4

Can I suppress the display of rendered text?

**Comment by dpvc** [comment]
You do not give any information about how your editor works, so there is not much specific that we can say about how to resolve your problem.  You don't even say which version of MathJax you are using (as requested in the bug report template).

There are at least two general approaches to this.  One would be to use `visibility:hidden` CSS while MathJax renders the expression and then set `visibility:visible` after it is done (how you synchronize with MathJax depends on whether you are suing v2 or v3).  The other is to use "double buffering", which is to use two copies of the output, one being the previous output and one the new output.  Continue displaying the previous output while the new output is rendered off screen or with `visibility:hidden` and then either move the new output into the one the old one, or swap the roles two two areas are using.  This solution produces the nicest result, but is a little more complicated to perform.
