### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by asifmushtaqkp** [mathjax/MathJax#2886]
[This package](https://www.jsdelivr.com/package/npm/mathjax?version=2.7.7) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by dpvc** [comment]
You have referenced version 2.7.7 of MathJax.  That is not the current version, and can't be changed at this point.  Both the current 3.2.2 and the highest version 2 release (2.7.9) have a default file.
