### ISSUE TITLE
Is it possible to use "linebreaks: { automatic: true }," for disp-formula but not for inline-formula?

### ISSUE THREAD

**Issue by jmitsdarfer** [mathjax/MathJax#2891]
### Issue Summary

We've been using "linebreaks: { automatic: true }," for quite a while now, and for the most part, it seems OK. However, we've recently wondered if we could remove that configuration option for inline-formula but leave it as is for disp-formula.

We think we might prefer a scroll bar when needed, e.g.,

![image](https://user-images.githubusercontent.com/82107944/176898967-949858b1-fc12-4fd4-8b80-fdaced02d35c.png)

for a longer inline-formula rather than a line break, e.g.,

![image](https://user-images.githubusercontent.com/82107944/176899215-7e560fd0-1851-4e21-9a46-42eee33dc7d3.png)

However, for disp-formulas, we prefer the look of the line breaks when possible, e.g.,

![image](https://user-images.githubusercontent.com/82107944/176898499-a42684f9-876e-4b9f-8067-c90663520d84.png)

rather than lots of scroll bars, e.g.,

![image](https://user-images.githubusercontent.com/82107944/176898649-475d065f-b7e5-4346-aef7-96fd1637e6f2.png)

### Technical details:

MathJax Version: MathJax.js v2.7.9
Client OS: Windows
Browser: Version 103.0.5060.53 (Official Build) (64-bit)
Renderer: HTML-CSS

**Comment by dpvc** [comment]
Sure, you can use the following as part ofyour configuration:

``` js
MathJax.Hub.Register.StartupHook('HTML-CSS Jax Ready', function () {
  var MML = MathJax.ElementJax.mml;
  MML.mrow.Augment({
    _HTMLlineBreaks: MML.mrow.prototype.HTMLlineBreaks,
    HTMLlineBreaks: function (span) {
      if (this.parent.linebreakContainer && this.Get("display") === "inline") return false;
      return this._HTMLlineBreaks(span);
    }
  });
});
```

That will disable line breaking for in-line expressions, but still break display ones.

**Comment by jmitsdarfer** [comment]
Thank you, Davide!

**Comment by jmitsdarfer** [comment]
@dpvc We have made it so that line breaks don't occur in inline-formulas; however, sometimes larger inline-formulas (especially on smaller screens like cell phones) get cut off on the right side rather than displaying a scroll bar. Is there a way to make a scroll bar appear for inline-formulas if they're too large to fit in the available space? Here's an example from https://pubs.acs.org/doi/10.1021/acs.jctc.1c01044:

Here's the full equation using Chrome on my 14 in. laptop screen (displays in full):
![image](https://github.com/mathjax/MathJax/assets/82107944/ac871f1c-8c4f-4c9b-9989-ed3ba3a37e65)

Here's the same equation on my Samsung Galaxy S23 device (a bit of the equation is cut off on the right; no scroll bar is provided):
![image](https://github.com/mathjax/MathJax/assets/82107944/f8be278b-d229-42cd-a29f-c79d72c56132)

Please let me know if you have any ideas for what we could try to do to fix this. Thanks!

**Comment by dpvc** [comment]
Try adding

``` js
  styles: {
    ".MathJax": {
      overflow: "auto hidden",
      display: "inline-block ! important",
      "max-width": "100% ! important"
    },
    ".MathJax_Display": {
      overflow: "auto hidden",
      "max-width": "100% ! important"
    }
  }
```

to your MathJax configuration (at the top level).  This should add horizontal scroll bars to in-line expressions that are wider than the container.  (It also does this for display equations that are wider than the container, which can happen even with line breaking turned on, as there may not be enough potential breakpoints to make it fit, for example.)

See if that does what you need.

**Comment by jmitsdarfer** [comment]
Yes, thank you, that was helpful!
