### ISSUE TITLE
In mathjax, can we write CSS script on any particular mathematical character? Example as sigma and vector and round brackets

### ISSUE THREAD

**Issue by devganeshchandra** [mathjax/MathJax#2895]
[In mathjax, can we write CSS script on any particular mathematical character? Example as sigma and vector and round brackets](https://mathoverflow.net/questions/422275/in-mathjax-can-we-write-css-script-on-any-particular-mathematical-character-ex)

**Comment by hbghlyj** [comment]
The [html](http://docs.mathjax.org/en/latest/input/tex/extensions/html.html) extension gives you access to some HTML features like styles, classes, element ID’s, and clickable links.
