### ISSUE TITLE
attribute accent="true" in SVG output

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#2898]
I'm seeing `accent="true"` making it to the SVG output. 

It shows up with a custom macro mimicking `\accentset` which does `NodeUtil.setAttribute(accent, 'accent', true);`). I realize it might be a bug on our end (not having updated after a change in MathJax) in which case I'd be grateful for guidance.

This might be affecting just the develop branch and open PRs.

**Comment by dpvc** [comment]
What type of node is `accent` in `NodeUtil.setAttribute(accent, 'accent', true);`?  Note that the `accent` attribute is valid only on `mo`, `msup`, and `msubsup`, so if you are applying it elsewhere, MathJax will think it is a foreign attribute, and preserve it in the output.  It sounds like that may be what is happening for you,.

**Comment by pkra** [comment]
Thanks, Davide! That's what's happening. An `isKind` check should help avoid it, I think.
