### ISSUE TITLE
Types for `chooseAdaptor` and `RegisterHTMLHandler` are not compatible, despite JS demo code suggesting they are

### ISSUE THREAD

**Issue by CharlieMcVicker** [mathjax/MathJax#2908]
**Replace the text below with the details of the issue you are facing.  
DO NOT simply erase the form and type a free-form response.**
-----

### Issue Summary

I am writing a typescript library that depends on MathJax full. Ideally, my library will support both browser and node environments. However, using the built-in `chooseAdaptor` function, I cannot call `RegisterHTMLHandler`.

I'm working on the package `mathjax-react` [npm](https://www.npmjs.com/package/mathjax-react). In particular, I am solving this issue/feature request: https://github.com/CharlieMcVicker/mathjax-react/issues/11.

### Steps to Reproduce:

1. Make a node project
2. Set up typescript (tested with typescript 3)
3. Add `mathjax-full`
4. Try the following code:

```ts
import { chooseAdaptor } from "mathjax-full/js/adaptors/chooseAdaptor";
import { RegisterHTMLHandler } from "mathjax-full/js/handlers/html";

const adaptor = chooseAdaptor();
RegisterHTMLHandler(adaptor);
```

Typescript notices the following discrepancy:
```
Argument of type 'HTMLAdaptor<HTMLElement, Text, Document> | LiteAdaptor' is not assignable to parameter of type 'DOMAdaptor<HTMLElement, Text, Document>'.
  Type 'LiteAdaptor' is not assignable to type 'DOMAdaptor<HTMLElement, Text, Document>'.
    Types of property 'document' are incompatible.
      Type 'LiteDocument' is missing the following properties from type 'Document': URL, alinkColor, all, anchors, and 245 more.
```

I pulled these lines from some demo code in a MathJax repo.
```ts
const adaptor = chooseAdaptor();
RegisterHTMLHandler(adaptor);
```

If this is not the right way to dynamically select and register an adaptor that either uses the DOM in the browser / client environment or LiteDom in a nodejs / server environment, I'd love to know what my other options are.

### Technical details:

* MathJax Version: 3.2
* Client OS: (e.g., Mac OS X 10.8.4)
* Node: v16.16.0
* Typescript: v3.7.7
* Mathjax-full: v3.2.2

I am using the following MathJax configuration: *I am importing MathJax full and developing an npm package*
and loading MathJax via the `mathjax-full` npm package.

**Comment by dpvc** [comment]
Hey, Charlie, nice to see you active on MathJax again.  Hope all is well with you.

You can use

``` js
RegisterHTMLHandler<any, any, any>(adaptor);
```

in this case.  The `chooseAdaptor()` was really only intended for testing purposes, not for deployment.  If you were to webpack a application using it, for example, it would have to include both the HTML and the LiteDOM adaptors, which would make your packed version larger than necessary.  But you can use it with `any` generics this way, if you want.

**Comment by CharlieMcVicker** [comment]
Thanks for the quick response. I will see if I can avoid using `chooseAdaptor`. I am not surprised that to get SSR support I will need to increase the size of the package. I may look into forking or doing something that will tree-shake well. Thanks!
