### ISSUE TITLE
Contextual Menu not available when using convert method (like mathml2chtml)

### ISSUE THREAD

**Issue by Sjiep** [mathjax/MathJax#2909]
### Issue Summary

When using the MathJax convert method, such as `mathml2chtml` to render Math content, the Contextual Menu that MathJax provides on "normally" typeset content is not available. 

Is there a way to have the menu available when using the convert method?

### Steps to Reproduce:

I made a codesandbox to display the issue: https://codesandbox.io/s/nervous-keldysh-sdnfqu?file=/src/index.js

### Technical details:

* MathJax Version: 3.2
* Client OS: Manjaro Ruah 21.3.5
* Browser: Vivaldi 5.3.2679.70

loading MathJax via

``` js
const script = document.createElement("script");
script.src = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/mml-chtml.js";
script.async = true;
document.head.appendChild(script);\
```

**Comment by dpvc** [comment]
Your code sandbox example indicates that your are using that MathJax outputs `outerHTML` to set the `innerHTML` of its new location.  MathJax uses event listeners to implement its contextual menu (and other actions needing interaction), but `outerHMTL` does not retain those, so you are losing the event listeners at that step.  Using

``` js
    document.getElementById("math").appendChild(converted);
```

instead will preserve the menu code, and is more efficient than serializing and re-parsing the math in any case.

**Comment by Sjiep** [comment]
Ok, that make sense. Thank you!
