### ISSUE TITLE
\Alpha doesn't print Capital Alpha, but \alpha prints undercase alpha?? 

### ISSUE THREAD

**Issue by wm2015email** [mathjax/MathJax#2910]
### Issue Summary

I just downloaded the Latest MathJax library  3.2.2. from nodejs.  I noticed thart some of the Capital Greek letters don't work for some reason on my html page in a MathJax Equation, but all of the  undercase greek leters work. See my webbrowser screenshot below:  For example \alpha displays an undercase greek alpha chracter correctly, but \Alpha don't display a capital Greek Alpha character. See Picture below for example:
 
![alphabet](https://user-images.githubusercontent.com/17484682/182033546-28700bc6-e224-4946-be3d-356a8859ebfa.png)

My webbrowser is the WebView2 UI Component in Microsoft .Net...

Any Idea how to fix this?  It works ok in Typora Markdown editor...

### Steps to Reproduce:

Here's my markdown code to produce the image above:

| Name    | Lower      | Upper      | English |
| ------- | ---------- | ---------- | ------- |
| Alpha   | $\alpha$   | $\Alpha$   | A       |
| Beta    | $\beta$    | $\Beta$    | B       |
| Gamma   | $\gamma$   | $\Gamma$   | G       |
| Delta   | $\delta$   | $\Delta$   | D       |
| Epsilon | $\epsilon$ | $\Epsilon$ | E       |
| Zeta    | $\zeta$    | $\Zeta$    | Z       |
| Eta     | $\eta$     | $\Eta$     | H       |
| Theta   | $\theta$   | $\Theta$   | Q       |
| Iota    | $\iota$    | $\Iota$    | I       |
| Kappa   | $\kappa$   | $\Kappa$   | K       |
| Lambda  | $\lambda$  | $\Lambda$  | L       |
| Mu      | $\mu$      | $\Mu$      | M       |
| Nu      | $\nu$      | $\Nu$      | N       |
| Xi      | $\xi$      | $\xi$      | X       |
| Omicron | $\omicron$ | $\Omicron$ | O       |
| Pi      | $\pi$      | $\Pi$      | P       |
| Rho     | $\rho$     | $\Rho$     | R       |
| Sigma   | $\sigma$   | $\Sigma$   | S       |
| Tau     | $\tau$     | $\Tau$     | T       |
| Upsilon | $\upsilon$ | $\Upsilon$ | U       |
| Phi     | $\phi$     | $\Phi$     | F       |
| Chi     | $\chi$     | $\Chi$     | C       |
| Psi     | $\psi$     | $\Psi$     | Y       |
| Omega   | $\omega$   | $\Omega$   | W       |

### Technical details:

I'm using MathJax 3.2.2 downloaded with nodejs...

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and include them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by dpvc** [comment]
The capital Greek letters that are the same as Latin letters, like capital Alpha, do not get their own macros in standard LaTeX.  So MathJax doesn't have `\Alpha`, `\Beta` or the other macros that are shown in red in your images.  So this is the expected behavior for MathJax.  You can, of course, define your own macros for `\Alpha` and the others.

See the [documentation](https://docs.mathjax.org/en/latest/input/tex/macros.html) for how to define new commands from within the mathematics of your page, and the [configmacros](https://docs.mathjax.org/en/latest/input/tex/extensions/configmacros.html) documentation for how to pre-defined them in your MathJax configuration.
