### ISSUE TITLE
MathJax.Hub.Register.StartupHook("End", function () {} in version 3.

### ISSUE THREAD

**Issue by apatel401** [mathjax/MathJax#2913]
Hi I am working in a project where we use brightspace and brightspace is injecting math script which is not needed because we are already hosting it on our end. The problem is brightspace is injecting v3 and we have hosted version of 2.7.5 and there is conflict in the version and v3 takes over v2 and some of our dynamic widgets are not loading math and the one that are loaded are very gigantic size font compare to regular text.
<img width="557" alt="image" src="https://user-images.githubusercontent.com/51169932/183683577-9e6a501b-9760-45ea-b8e7-6e790a22d4a7.png">
![image](https://user-images.githubusercontent.com/51169932/183685409-eb9d55dd-c6d5-4ce9-8c43-bae19cafd3d1.png)

Now the problem is we had a script running after math was loaded using MathJax.Hub.Register.StartupHook("End", function () {} but not sure what to use in version 3. I have tried this but it doesn't work either

``` js
window.MathJax = {
    options: {
      menuOptions: {
        settings: {
          inTabOrder: false
        }
      },
      ignoreHtmlClass: 'tex2jax_ignore',
      processHtmlClass: 'tex2jax_process'
    },
    startup: {
      ready: () => {
          MathJax.startup.defaultReady();
          console.log('MathJax initial typesetting complete');
          const mathElements = document.getElementsByTagName("mjx-container"); // getting math element
      //   var brightspace_check = document
      //     .getElementsByTagName("img")[0]
      //         .getAttribute("src"); //checking the src tag of image
        var another_check = window.location.href;
      var not_local = another_check.includes("https"); // checkingif the srclink has d2lSession included or not. When in brightspace it will have that d2lSession in the src tag
      if (
        ( not_local === true ) &&
        parseFloat(
          window
            .getComputedStyle(mathElements[0], null)
            .getPropertyValue("font-size")
        ) /
          (parseFloat(
            window
              .getComputedStyle(document.getElementsByTagName("p")[0], null)
              .getPropertyValue("font-size")
          ) >
            0.9)
      ) {
        var style = document.createElement("style");
        style.type = "text/css";
        style.innerHTML = ".MathJax, mjx-container { font-size:1.3rem !important}";
        document.getElementsByTagName("head")[0].appendChild(style);
      };
      $('.MathJax').removeAttr('tabindex');
      $('mjx-container').removeAttr('tabindex');
    }
  }}
```

I want to run this similar script in version 3 which I can use

**Comment by dpvc** [comment]
The `ready()` function isn't for when the typesetting is done, it is for when all MathJax components are loaded and it is ready to go (this occurs before typesetting).  See the [documentation](https://docs.mathjax.org/en/latest/web/configuration.html#performing-actions-after-typesetting) for information about how to synchronize with MathJax's initial typesetting.

**Comment by apatel401** [comment]
Thank you for taking time to respond. I know this is not the right place to ask question. As I already write my issue here. I am trying to render dynamic content in multiple-choice quiz which is made in angular 1.5 pretty outdated. which works fine for the first question. it renders the math correctly for the first question but after that it doesn't render the second question. we used to use 2.7.5 which was using this code on controller. its not passing any array in this component.
```js
 MathJax.Hub.Queue(["Typeset", MathJax.Hub]);

```
now in version 3 I am using 
```js
MathJax.typeset();
```
But when I click the next button to go to the next question it gives me an error typeset is not a function.
why is this happening and what am I doing?

Note: on my main app.js I am using watch function where there is element is passed and this works fine
```js
MathJax.typeset([$element[0]]);
```

**Comment by dpvc** [comment]
You have not provided enough information to diagnose your problem, for example the code that is attached to the button press, or the actual error message that is produced (with its traceback).  The `MathJax.typeset()` (or probably better `MathJax.typesetPromise()`) is the correct command to use, so if it is telling you that this is not a function, then perhaps you have overwritten the `MathJax` variable somewhere after the math is initially typeset?

Without seeing more of the code in question, there is not much I can tell you.
