### ISSUE TITLE
Wiki cloning gives error

### ISSUE THREAD

**Issue by garawaa** [mathjax/MathJax#2914]
Cloning into 'MathJax.wiki'...
remote: Enumerating objects: 2495, done.
Receiving objects:  97% (2421/2495)used 0 (delta 0), pack-reused 2495
Receiving objects: 100% (2495/2495), 488.41 KiB | 1006.00 KiB/s, done.
Resolving deltas: 100% (1518/1518), done.
error: invalid path 'Mathjax-v2.x-potential-feature:-localization.rest'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by dpvc** [comment]
I've changed the name of that page, so see if that helps.

**Comment by dpvc** [comment]
Note: most of that stuff is pretty old, and doesn't relate to the current version (v3) of MathJax.
