### ISSUE TITLE
Error when render \sqrt

### ISSUE THREAD

**Issue by geordo** [mathjax/MathJax#2916]
### Issue Summary

Google Chrome doesn't render good \sqrt. 

### Technical details:

* MathJax Version: 3.2.2
* Client OS: Windows 11 
* Browser: Chrome 104.0.5112.102

I am using the following MathJax configuration:

``` js
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

### Image

![sss](https://user-images.githubusercontent.com/96908409/186393545-b65dfc46-56c6-4690-b327-623b1539ba9f.png)

**Comment by dpvc** [comment]
It looks like some of the fonts may not have been loaded (in particular, MathJax_Main-Regular).  The no-equal, plus, equal, plus-minus, the numbers, and the surd for the square root are not being rendered in the correct font.  Do you see any messages about MathJax fonts in the browser console?

If you are having trouble with the output, you might consider switching to the SVG output using the MathJax contextual menu.  That might give you better results.
