### ISSUE TITLE
Bengali font does not render properly

### ISSUE THREAD

**Issue by DerivedSkill** [mathjax/MathJax#2919]
### Issue Summary
I've tried [this link](https://saxarona.github.io/mathjax-viewer/) to view a latex equation. Which does not render properly, it rendered like [this](https://drive.google.com/file/d/18hyQtPdIzH8J0Igz-CQDHKiCFxmVVeGV/view?usp=sharing), but it should render like [this](https://drive.google.com/file/d/1NRn1h1UyJYdUT_gxiWGW3Xn2pyByar16/view?usp=sharing).
I've also tried using MathJax version 3 by using below cdn, same things also happen there.

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

The latex was: \frac{CC{l}_{4}\ সাদা}{পানিতে}

### Steps to Reproduce:

1. Use above mentioned CDN.
2. Render "\frac{CC{l}_{4}\ সাদা}{পানিতে}" this latex.

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Firefox, Chrome, Microsoft Edge
* Bengali Software: [Avro ](https://www.omicronlab.com/avro-keyboard-download.html) Version: 5.6.0 
* Bengali Font: [Siyam-Rupali](https://www.wfonts.com/download/data/2016/06/15/siyam-rupali/siyam-rupali.zip)

I've not used any MathJax configuration, default configuration was used and loading MathJax via

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
You should use 

``` latex
\frac{CC{l}_{4}\text{ সাদা}}{\text{পানিতে}}
```

to have the Bengali treated as text rather than math, and use the configuration 

``` js
MathJax = {
  chtml: {
    mtextInheritFont: true
  }
};
```

so that the surrounding text font is used for the contents of `\text{}`.   That should do it.

**Comment by DerivedSkill** [comment]
It works, Thanks a lot.

**Comment by dpvc** [comment]
Great, glad it worked.
