### ISSUE TITLE
"‖" not rendered when used like bracket

### ISSUE THREAD

**Issue by DerivedSkill** [mathjax/MathJax#2942]
### Issue Summary
I've tried [this link](https://www.mathjax.org/#demo) to view a latex equation. Which does not rendered, error message was "Missing or unrecognized delimiter for \right". But it should render like [this](https://drive.google.com/file/d/1PWTLvxlQaocCp7yxb6tNlVJtjrKTkAuD/view?usp=sharing).
I've also tried using MathJax version 3 by using below cdn, same things also happen there.

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

The latex was: \left.\begin{matrix}\ -5\ &\ 1\ &\ 1\ \\ 4\ &\ 5\ &\ 1\ \\ 7\ &\ -4\ &\ 1\ \\ \ \end{matrix}\right‖

### Steps to Reproduce:

1. Use above mentioned CDN.
2. Render above mentioned latex.

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Firefox, Chrome, Microsoft Edge

### MathJax Configuration:
MathJax = {
    chtml: {
        mtextInheritFont: true, 
    }
};

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by LingrenKong** [comment]
Maybe you can use `\Vert` for double verticle line,this also seems to be a simple way in tex
$$
\left.\begin{matrix}-5 &1&1\\ 4&5&1\\ 7&-4&1\\ \end{matrix}\right\Vert
$$

**Comment by dpvc** [comment]
MathJax's TeX input jax has a list of valid characters/control-sequences that can be used with `\left` and `\right`, and it only includes the standard TeX ones.  If you want to add more delimiters, you can do so using a configuration like

``` javascript
MathJax = {
  startup: {
    ready() {
      const {Configuration} = MathJax._.input.tex.Configuration;
      const ParseMethods = MathJax._.input.tex.ParseMethods.default;
      const {DelimiterMap} = MathJax._.input.tex.SymbolMap;
      //
      // Create a delimimter map for the new delimiter(s)
      //
      new DelimiterMap('my-delimiters', ParseMethods.delimiter, {
        '\u2016': '\u2016'
      });
      //
      // Create a package configuration that handles the new delimiters
      //
      Configuration.create('my-delimiters', {
        handler: {delimiter: ['my-delimiters']}
      });
      //
      // Do the rest of the usual startup
      //
      MathJax.startup.defaultReady();
    }
  },
  tex: {
    packages: {'[+]': ['my-delimiters']}  // tell TeX to use the new package
  }
};
```

You can list as many delimiters are you want in the `DelimiterMap()`, and if the font in use has stretchy versions of the character, they will stretch when used with `\left` and `\right`.
