### ISSUE TITLE
`mathjax@4.0.0-alpha.1` should not be tagged as `latest`

### ISSUE THREAD

**Issue by tamuratak** [mathjax/MathJax#2947]
### Issue Summary

`mathjax@4.0.0-alpha.1` is tagged as `latest` at the `npmjs.com` registry:

- https://www.npmjs.com/package/mathjax?activeTab=versions

 It should be tagged as `beta` or `dev`. Now, executing `npm i mathjax` installs `mathjax@4.0.0-alpha.1`.

See:

> By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. 

- https://docs.npmjs.com/cli/v7/commands/npm-dist-tag#purpose

### Technical details:

* MathJax Version: `mathjax@4.0.0-alpha.1`

**Comment by dpvc** [comment]
I believe I have reset the tags so that 3.2.2 is latest.  Thanks for the report and links.
