### ISSUE TITLE
Double bracket got broken when matrix inside

### ISSUE THREAD

**Issue by DerivedSkill** [mathjax/MathJax#2950]
### Issue Summary
I've tried [this link](https://www.mathjax.org/#demo) to view a latex equation. Which does not render properly, it rendered like [this](https://drive.google.com/file/d/1XIgC_rbMh0z-MLw_y50MthPb795WaJOZ/view?usp=sharing), but it should render like [this](https://drive.google.com/file/d/1V3AZiPfKO4iGnwzjPfXsJjAb_0Y_fTOI/view?usp=sharing).
I've also tried using MathJax version 3 by using below cdn, same things also happen there.

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

The latex was: `\left[\![ \begin{matrix}a\\b\\c\\\end{matrix}\right]\!]`
The latex that generate perfectly: `\left[\![ abcd\right]\!]`

### Steps to Reproduce:

1. Use above mentioned CDN.
2. Render `\left[\![ \begin{matrix}a\\b\\c\\\end{matrix}\right]\!]` this latex.

### Technical details:

* MathJax Version: 3
* Client OS: Windows 10
* Browser: Firefox, Chrome, Microsoft Edge

### MathJax Configuration:
```
MathJax = {
    chtml: {
        mtextInheritFont: true, 
    }
};
```

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
This is the correct rendering for the LaTeX that you have used.  You are using a multi-character sequence to "fake" a double bracket, and `\left` and `\right` only work with single-character delimiters, and so they stretch only the first of the two brackets in each case..  So the output you show is the correct output, and what actual LaTeX would produce as well.

The MathJax TeX fonts don't include the double-bracket character, either as a single character, or as the parts needed to make a multi-character assembly.  Some of the fonts in v4.0 do, however, so you may be able to do better with that.

Alternatively, you could use

``` latex
\left[\!\!\!\left[ \begin{matrix}a\\b\\c\\\end{matrix}\right]\!\!\!\right]
```

to get the effect you are looking for.

**Comment by DerivedSkill** [comment]
I got it, Thank you for this reply.
