### ISSUE TITLE
v4: line-break horizontal alignment

### ISSUE THREAD

**Issue by woody-li** [mathjax/MathJax#2951]
Thanks for line break implements.

### Issue Summary
The default horizontal alignment is "center" in v4.
But it is "left" in v2.

test latex:
`
abc \\ 123456789
`

Is there any config to change it?

**Comment by dpvc** [comment]
The default alignment for display equations in both versions is "center".  Perhaps your v2 configuration changes that?

You can set the display alignment via

``` javascript
MathJax = {
  output: {
    displayAlign: 'left'
  }
}
```

in version 4.  Note that there is a [configuration converter](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) that can be used to convert your v2 configurations to ones that can be used in v3 and v4.
