### ISSUE TITLE
\hspace.5cm have NO horizontal shift effect but \hspace3em DO have shift effect in some scenario

### ISSUE THREAD

**Issue by hjy1210** [mathjax/MathJax#2960]
**Replace the text below with the details of the issue you are facing.  
DO NOT simply erase the form and type a free-form response.**
-----

### Issue Summary

I encounter a scenario :  \hspace.5cm have NO horizontal shift effect but \hspace3em DO have shift effect

### Steps to Reproduce:

1. This is the simple html

  ```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

</head>
<body>
    <p id="p"></p>
    <button onclick="typeset('\\(A\\hspace.5cm B\\)')"><code>\(A\hspace.5cm B\)</code></button>
    <button onclick="typeset('\\(A\\hspace3em B\\)')"><code>\(A\hspace3em B\)</code></button>
    <script>
        async function typeset(texStr) {
            let element = document.createElement("div");
            element.innerHTML = texStr;
            await MathJax.typesetPromise([element]);
            document.getElementById("p").innerHTML = element.innerHTML;
            console.log(element.innerHTML);
        }
    </script>
</body>
</html>
```
2. It appear as:
<img width="244" alt="1" src="https://user-images.githubusercontent.com/7498709/199191115-3454589a-e82c-4390-b866-1e140cac258d.png">
3. After press the left button, it appear
<img width="237" alt="2" src="https://user-images.githubusercontent.com/7498709/199191756-8d4ff969-bb41-4e96-8d62-54247a2591a2.png">
4. console.log report:
 &lt;mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" tabindex="0" ctxtmenu_counter="2" style="position: relative;">&lt;mjx-math class="MJX-TEX" aria-hidden="true">&lt;mjx-mi class="mjx-i">&lt;mjx-c class="mjx-c1D434 TEX-I">&lt;/mjx-c>&lt;/mjx-mi>&lt;mjx-mspace>&lt;/mjx-mspace>&lt;mjx-mi class="mjx-i">&lt;mjx-c class="mjx-c1D435 TEX-I">&lt;/mjx-c>&lt;/mjx-mi>&lt;/mjx-math>&lt;mjx-assistive-mml unselectable="on" display="inline">&lt;math xmlns="http://www.w3.org/1998/Math/MathML">&lt;mi>A&lt;/mi>&lt;mspace width=".5cm">&lt;/mspace>&lt;mi>B&lt;/mi>&lt;/math>&lt;/mjx-assistive-mml>&lt;/mjx-container>

5. After press the right button, it appear
<img width="234" alt="3" src="https://user-images.githubusercontent.com/7498709/199192079-9b884765-0068-490d-ae85-aec23961559e.png">
6. console.log report:&lt;mjx-container class="MathJax CtxtMenu_Attached_0" jax="CHTML" tabindex="0" ctxtmenu_counter="3" style="position: relative;">&lt;mjx-math class="MJX-TEX" aria-hidden="true">&lt;mjx-mi class="mjx-i">&lt;mjx-c class="mjx-c1D434 TEX-I">&lt;/mjx-c>&lt;/mjx-mi>&lt;mjx-mspace style="width: 3em;">&lt;/mjx-mspace>&lt;mjx-mi class="mjx-i">&lt;mjx-c class="mjx-c1D435 TEX-I">&lt;/mjx-c>&lt;/mjx-mi>&lt;/mjx-math>&lt;mjx-assistive-mml unselectable="on" display="inline">&lt;math xmlns="http://www.w3.org/1998/Math/MathML">&lt;mi>A&lt;/mi>&lt;mspace width="3em">&lt;/mspace>&lt;mi>B&lt;/mi>&lt;/math>&lt;/mjx-assistive-mml>&lt;/mjx-container>

7. Why \hspace.5cm have no shift effect, but  \hspace3em HAVE shift effect

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version: 3.2
* Client OS: (e.g., Windows 10 21H2)
* Browser: (e.g., Chrome 106.0.5249.119)

I am using the following MathJax configuration:

``` js
```

and loading MathJax via

``` html
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

### Supporting information:

 * Please supply a link to a (live) minimal example page, when possible.
 * If your issue is with the display of the mathematics produced by MathJax, include a screen snapshot that illustrates the problem, when possible.
 * Check your browser console window for any error messages, and include them here.
 * Include the MathJax configuration you are using, and the script tag that loads MathJax itself.

**Comment by dpvc** [comment]
MathJax converts all units to `em`s internally, and in order to do that, MathJax must determine the size of the `em` unit where the math is being typeset.  You are creating an isolated `div` that is not part of the active DOM, and that means that the browser will not perform any layout, and in particular, all elements return a width and height of 0.  So when MathJax tries to determine the `em` size, it gets back 0.  So converting `cm` to `em` will end up with zero.  Units of `emus work because these don't have to be converted, and are used verbatim.

One solution would be to add the `div` to the DOM before typesetting it (you could use `visibility: hidden`, but should not use `display:none` as that has the same problem).  Alternatively, you could use `MathJax.tex2chtmlPromise()` to do the typesetting (though you would have to remove the delimiters).
