### ISSUE TITLE
how do i customize the the latex defined by myself, and change it to mathml defined by myself

### ISSUE THREAD

**Issue by jaylenchan** [mathjax/MathJax#2961]
1. How can I convert my custom latex symbols to custom mathml

Cause: Now the server storage format is as follows:
`<?xml version="1.0" encoding="utf-8"?>
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <mrow>
    <munderover>
      <mo>⇌</mo>
      <mi>A</mi>
      <mi>B</mi>
    </munderover>
  </mrow>
</math>`

but use mathjax convert `\overset A{\underset B\leftrightharpoons}`will get the result:
`<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mover>
    <munder>
      <mo stretchy="false">&#x21CB;</mo>
      <mi>B</mi>
    </munder>
    <mi>A</mi>
  </mover>
</math>`

the `<munserover>`will replaced by `<mover> <munder>`, I can't replace the store format, how can i do to solve this problem ?

in a word, i want to customize the  mathml from input latex

**Comment by dpvc** [comment]
Also, the code example is for version 3.  If you are using version 2, this would have to be handled differently.
