### ISSUE TITLE
why false when user mathjax in node

### ISSUE THREAD

**Issue by TangsWang** [mathjax/MathJax#2963]
```
import mathjax from 'mathjax'
.....
      mathjax.init({
        loader: {
          load: ['input/tex'],
        }
      })
        .then(mj => {
          if (!mj) {
            reject(`mathjax instance is undefined.`)
          } else {
            mj.tex2mmlPromise(math).then(mml => resolve(mml))
          }
        })
        .catch(err => reject(err.message))
```

will report error:  mathjax instance is undefined.

i was using nuxt3.   it is ok on local, but error on vercel. i don't know why?

**Comment by TangsWang** [comment]
@dpvc  could you help me? thanks a lot!!!

**Comment by dpvc** [comment]
Using MathJax in a browser versus in a server-side node application has some differences, and the mechanism you are using (importing mathjax and calling `mathjax.init()`) is set up as a quick way to get MathJax running in a command-line node application, but is not set up for browser use.  The "note" at the bottom of [this section](https://github.com/mathjax/MathJax-src#using-mathjax-components-in-node-applications) of the MathJax README file points this out.

To use MathJax in a browser you could import one of the MathJax combined components (e.g., 'tex-chtml.js'), which is set up for browser use, and then call the global variable `MathJax.tex2mmlPromise()` method.  Or you can look at the examples in the [MathJax node demos](https://github.com/mathjax/MathJax-demos-node) repository for examples of other ways to call MathJax.  For example, the "components" directory shows how to load component-based MathJax files, and the "direct" directory shows how to import that MathJax modules directly.  

For the component examples, you would want to leave out the `source` and `require` properties in the `loader` block of the configuration, and remove the `adaptors/LiteDOM` from the `load` array.  The "preload" directory might also be a good place to start.  

You can also look at the the [custom-component](https://github.com/mathjax/MathJax-demos-web/blob/master/custom-component/custom-component.html.md) example in the [MathJax web demos](https://github.com/mathjax/MathJax-demos-web) repository for an example of loading MathJax components into a custom application setting.
