### ISSUE TITLE
accents disappearing at certain zoom levels

### ISSUE THREAD

**Issue by xworld21** [mathjax/MathJax#2986]
### Issue Summary

(Edit: actually Firefox is not affected. This may be a Blink/WebKit bug after all, quite possibly duplicate of others that have been reported here.)

Noticed on Windows, in Chrome, Edge and ~Firefox~. At certain zoom levels, at least one accent disappears (the overline one in my case):

At default zoom level, on a standard DPI screen (i.e. 96dpi, 100% system scaling, 100% browser zoom)
![image](https://user-images.githubusercontent.com/1962985/211564197-0a3fb3de-42b5-4bd6-bb2a-29b41b86fa21.png)

It reappears when zooming out (same screen, 80% browser zoom)
![image](https://user-images.githubusercontent.com/1962985/211564396-939bdd60-3289-4cae-8015-0fdd742cc946.png)

The screen scaling settings affect which zoom values show the accent.

### Steps to Reproduce:

1. In the MathJax demo page, type
```xml
<math><mover accent="true"><mi>z</mi><mo mathvariant="normal">¯</mo></mover></math>
```
2. Zoom in/out in the browser.

### Technical details:

* MathJax Version: 3.2.2
* Client OS: Windows 10 22H2
* Browser: Chrome 108.0.5359.125

**Comment by dpvc** [comment]
We have seen this issue before (e.g., #2701), and thought we had fixed that earlier, but apparently not.  I don't have a Windows 10 installation to check this.  I am unable to reproduce the problem in Windows 11, so perhaps it is a Windows 10 rendering issue.

We are preparing a v4 release that includes an updated font set (and 11 new fonts), and I'm hoping that that will resolve a number of these zoom-related display issues.

**Comment by xworld21** [comment]
And today, I cannot reproduce it in the just released Chrome 109, Windows 10. Excellent timing on my part! I can still see this on Edge 108, but that will update very soon too. I'll keep an eye on this and close the issue once I am convinced it does not happen any more.

**Comment by dpvc** [comment]
OK, thanks for the additional information.  Good to know.
