### ISSUE TITLE
when appear attribute data-mjx-error, how to catch error and use fallback way, for example server render

### ISSUE THREAD

**Issue by xiayali** [mathjax/MathJax#2992]

**Comment by dpvc** [comment]
Here is a configuration that you can use as a starting point for your process.  This inserts a render action into the MathJax rendering chain that occurs right before the math is inserted into the page.  It looks to see if the math is marked as an error via the `data-mjx-error` attribute, and if so, replaces the typeset version with other content of your choice.  Here is is just a message indicating the content is replaced, but you could have it do something more significant, like send the original LaTeX (stored in `math.math`) to a server for processing by actual LaTeX, and then insert the resulting image into the `typesetRoot` instead.  What you do and how you do it is up to you.

``` js
MathJax = {
  options: {
    renderActions: {
      handleErrors: [199,
        (doc) => {for (const math of doc.math) MathJax.config.handleError(math)},
        (doc, math) => MathJax.config.handleError(math)
      ]
    }
  },
  handleError(math) {
    const node = math.root.childNodes[0];
    if (node && node.childNodes[0] && node.childNodes[0].attributes.get('data-mjx-error')) {
      const div = math.typesetRoot = document.createElement(math.display ? 'div' : 'span');
      div.innerHTML =
        '<span style="border:2px solid red; color:blue; padding: 3px">Replaced content</span>';
    }
  }
};
```
