### ISSUE TITLE
Column Vector Display Issue

### ISSUE THREAD

**Issue by PhilipYip1988** [mathjax/MathJax#2995]
### Column Vector not rendering properly without spacing

A summary of the issue and the browser/OS environment in which it occurs. If
suitable, include the steps required to reproduce the bug.

### Steps to Reproduce:

1. Input the following equation on GitHub  ```$$\left[\begin{matrix}a\\b\\c\\\end{matrix}\right]$$```
2.  It does not render properly unless new lines are added after every row.

### Technical details:

* MathJax Version: ? Version on GitHub
* Client OS: Windows 11 22H2 and Ubuntu 23.04
* Browser: Chrome 109.0.5414.76, Chromium and Edge

### Supporting information:

Column vector:

```
$$\left[\begin{matrix}a\\b\\c\\\end{matrix}\right]$$
```

Rendering issue... ```Missing \left or extra \right```

$$\left[\begin{matrix}a\\b\\c\\\end{matrix}\right]$$

Same code but new lines added after every row:

```
$$\left[\begin{matrix}a\\
b\\
c\\
\end{matrix}\right]$$
```

Renders as expected:

$$\left[\begin{matrix}a\\
b\\
c\\
\end{matrix}\right]$$

This seems to be an issue recognising the ```\\``` to end the row and begin a new one. This works if the new row is on a new line.

**Comment by dpvc** [comment]
This is actually an issue with how GitHub has integrated MathJax into their markdown processing, which has a number of serious problems, this among them.  It is not a MathJax issue, and should be reported to the GitHub team using their [bug report system](https://support.github.com/contact/bug-report).
