### ISSUE TITLE
`\middle|` doesn't have MathML attribute `stretchy="true"`

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#2996]
**Is your feature request related to a problem? Please describe.**
Convert `\left\{x\middle|x>\sqrt{\frac1n}\right\}` to MathML by MathJax, and render in Firefox, the vertical bar won't stretch.
![image](https://user-images.githubusercontent.com/53823634/216485997-8af53e52-9c3b-41c4-89e5-17bef30a5f3a.png)

**Describe the solution you'd like**
Add MathML attribute `stretchy="true"` to `\middle|`
Convert `\left\{x\mmlToken{mo}[stretchy="true"]{|}x>\sqrt{\frac1n}\right\}` to MathML by MathJax, and render in Firefox, the vertical bar will stretch.
![image](https://user-images.githubusercontent.com/53823634/216486671-818973c8-5519-4784-979c-858e1fc5636a.png)
Or add MathML attribute `form="prefix"` as [temml](https://temml.org/#%5Cleft%5C%7Bx%5Cmiddle%7Cx%3E%5Csqrt%7B%5Cfrac1n%7D%5Cright%5C%7D).

**Comment by dpvc** [comment]
According to [appendix C](https://www.w3.org/TR/MathML3/appendixc.html#oper-dict.entries-table) of the MathML3 specification (on which MathJax is based), the vertical line U+007C is stretchy by default in infix position (it is marked as "fence, stretchy, symmetric").  MathJax does not include attributes if they are the default value in the operator dictionary.  You do not indicate which browser you are using, but I suspect it may be Chrome, which implements [MathML-Core](https://www.w3.org/TR/mathml-core/), which is still a draft specification.  It appears that they have removed the stretchy and symmetric properties for U+007C in infix mode for some reason.  That is a non-backward-compatible change with MathML3.

It would be possible to add a TeX post-filter to look for this situation and add back the stretchy attribute.

**Comment by hbghlyj** [comment]
>  You do not indicate which browser you are using, but I suspect it may be Chrome
I was using Firefox

> It appears that they have removed the stretchy and symmetric properties for U+007C in infix mode for some reason.
I think it is related to [this](https://github.com/w3c/mathml-core/issues/104#issuecomment-1022983991)

> It would be possible to add a TeX post-filter to look for this situation and add back the stretchy attribute.
Yes. Thanks.
