### ISSUE TITLE
Broken text layout on IOS devices when using \textbf{} in math environment

### ISSUE THREAD

**Issue by cjohn001** [mathjax/MathJax#3004]
### Issue Summary

The problem occurs on IOS devices, default Safari browser/webview. Problem can be seen from image below. The bold black texts were set in math environments. It looks like the relative height of the characters to each other get messed up for some words. See image below. "Tägl. Bewegung" looks correct, but "Aktiv" looks wrong.

<img width="374" alt="Bildschirm­foto 2023-02-19 um 11 01 18" src="https://user-images.githubusercontent.com/43253483/219941444-5c99a548-b777-4dde-b0fe-34b2eb46f559.png">

I am trying to set bold text in a math mode environment. On the desktop computer this looks ok but not on iPhone. Maybe in issue with the font?

### Steps to Reproduce:
```

$$ \textbf{E} = \textbf{BMR} + \textbf{Anpassung} + \textbf{Aktiv} $$

Beide zusammengefasst bilden die \(\textbf{Aktiv}\)-Kalorien.

\(\textbf{T\"agl. Bewegung}\): 

\(\textbf{Aktivit\"at}\):
```

Any other information you want to share that is relevant to the issue
being reported. Especially, why do you consider this to be a bug? What
do you expect to happen instead?

### Technical details:

* MathJax Version:  
"mathjax-full": "4.0.0-alpha.1",
"mathjax-modern-font": "^1.0.0-alpha.1"

I am using the following MathJax configuration:

``` js
		<script type='text/javascript'>
			MathJax = {
				loader: { load: ['[tex]/textmacros'] },
				tex: {
					packages: { '[+]': ['textmacros'] }
				},
				output: {
					linebreaks: {
						inline: true,
					}
				},
				options: {
					menuOptions: {
						settings: {
							assistiveMml: false,
							collapsible: false,
							explorer: false
						}
					}
				}
			};
		</script>
```

and loading MathJax via

``` html
<script type='text/javascript' src='../mathjax/tex-mml-chtml.js' async></script>
```

### Supporting information:

The attached file shows the generate HTML from the debug console of the webview (iOS Simulator):

[test.txt](https://github.com/mathjax/MathJax/files/10776610/test.txt)

Woud be great if someone could comment on a workaround if one exists. Maybe using different latex package for text in math environment?

**Comment by dpvc** [comment]
This is a long-standing issue with WebKit.  See, for example, #2866 and #1498.  One work-around suggested in #2866 would be to use a system font for the contents of `\text{}` rather than the MathJax math fonts.  You can either inherit the surrounding text font or force a specific one.  E.g.,

``` js
MathJax = {
  chtml: {
    mtextInheritFont: true
  }
}
```

or

``` js
MathJax = {
  chtml: {
    mtextFont: Times
  }
}
```

A last-ditch alternative would be to add the following CSS to your page:

``` css
mjx-mtext > mix-c {
  padding-top: .75em ! important;
}
```

so that all the text characters are forced to the same height, but this can cause poor display of things like square roots or fractions if they contain `\text{}` macros.

**Comment by cjohn001** [comment]
@dpvc, thank you very much for the directions.
