### ISSUE TITLE
$$0.07m^3=(70000)cm^3$$. this formula fails to show error on iOS. cannot be reproduced stably.

### ISSUE THREAD

**Issue by cbsunny** [mathjax/MathJax#3009]
### Shown on iOS as follows：
<img width="175" alt="mathjax" src="https://user-images.githubusercontent.com/16752643/221816160-0db0fec0-841b-46f0-8a66-f5b0f7e9d643.png">

**Comment by dpvc** [comment]
You have not provided the information needed to diagnose your issue.  Please fill out the form that is in place when you start a new issue (don't just erase it).  In particular, we need to know the version of MathJax that you are using, and the browser involved.  if you are using a content management system (something that lets you edit your web pages), you should indicate that as well.

In your case, it looks like the `^` characters are being removed by content management system, so it may be that those have some particular meaning to the system.  If you can view the source of the page and check that the `^` characters are actually in the HTML file, that would be a help.

**Comment by cbsunny** [comment]
@dpvc

**Comment by cbsunny** [comment]
Please ignore this question,this problem is caused by page layout changes.
