### ISSUE TITLE
Custom equation numbering with appendix letters

### ISSUE THREAD

**Issue by sciarraseb** [mathjax/MathJax#3013]
I have been experimenting with MathJax to try to get Equations in the main text to get the format of s.eq, where 's' indicates the section number and 'eq' indicates the equation number. I have successfully implemented this formatting with the following code: 

```
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>

window.MathJax = {
  section: -1,
   loader: {load: ['[tex]/tagformat']},
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']], //allow inline math
    displayMath: [['$$','$$']],
    tagSide: 'right', //location of equation numbers
    tags: 'all',
    packages: {'[+]': ['tagformat', 'sections', 'autoload-all']},
    tagformat: {
      number: (n) => MathJax.config.section + '.' + n
    }
  },
  startup: {
    ready() {
      const Configuration = MathJax._.input.tex.Configuration.Configuration;
      const CommandMap = MathJax._.input.tex.SymbolMap.CommandMap;
      new CommandMap('sections', {
        nextSection: 'NextSection',
        setSection: 'SetSection',
      }, {
        NextSection(parser, name) {
          MathJax.config.section++;
          parser.tags.counter = parser.tags.allCounter = 0;
        },
        SetSection(parser, name) {
          const n = parser.GetArgument(name);
          MathJax.config.section = parseInt(n);
        }
      });
      Configuration.create(
        'sections', {handler: {macro: ['sections']}}
      );
      MathJax.startup.defaultReady();
    }
  }
};


<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
```

I would like the formatting for the Equation to change to a format of L.eq, where L is the letter of the corresponding appendix and eq is the equation number (e.g., A.1, A.2, B.1, B.2, etc.). I have not succeeded so I figured I would try asking here.

**Comment by dpvc** [comment]
Here is an implementation that uses letters rather than numbers for the sections.  You can set the sequence of letters that you want to use, but I've set upper-case letters from A to Z.

``` javascript
window.MathJax = {
  sectionLetters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  section: 0,
  loader: {load: ['[tex]/tagformat']},
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']], //allow inline math
    displayMath: [['$$','$$']],
    tagSide: 'right', //location of equation numbers
    tags: 'all',
    packages: {'[+]': ['tagformat', 'sections', 'autoload-all']},
    tagformat: {
      number: (n) => (MathJax.config.sectionLetters[MathJax.config.section] || '??') + '.' + n
    }
  },
  startup: {
    ready() {
      const Configuration = MathJax._.input.tex.Configuration.Configuration;
      const CommandMap = MathJax._.input.tex.SymbolMap.CommandMap;
      new CommandMap('sections', {
        nextSection: 'NextSection',
        setSection: 'SetSection',
      }, {
        NextSection(parser, name) {
          MathJax.config.section++;
          parser.tags.counter = parser.tags.allCounter = 0;
        },
        SetSection(parser, name) {
          const c = parser.GetArgument(name);
          MathJax.config.section = MathJax.config.sectionLetters.indexOf(c);
        }
      });
      Configuration.create(
        'sections', {handler: {macro: ['sections']}}
      );
      MathJax.startup.defaultReady();
    }
  }
};
```

I think that should do what you are asking for.

**Comment by sciarraseb** [comment]
Thank you for the quick response! This works on my end. I just have one more question. Since my appendices are at the end of my document, should I just insert the above code into another Javascript file and then call it before the appendix to change the equation numbering format? Or is there a more effective way to accomplish this output such that equations are numbers 1.1., 1.2, 2.1, etc., throughout the document and then A.1, A.2, B.1, etc., in the appendix?

**Comment by dpvc** [comment]
> should I just insert the above code into another Javascript file and then call it before the appendix

That won't do any good, as the configuration is used as MathJax starts up, and your changes would not be applied (indeed, you would just wipe out MathJax, since it would have redefined the `MathJax` variable when it is loaded).  Also, MathJax locates all the equations in one pass, then processes them all in a single pass.  That all happens after the page is parsed by the browser, so you can't easily intersperse javascript calls with the processing of the math.

Instead, use this new version:

``` javascript
window.MathJax = {
  section: {
    n: 0,
    useLetters: false,
    letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  loader: {load: ['[tex]/tagformat']},
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']], //allow inline math
    displayMath: [['$$','$$']],
    tagSide: 'right', //location of equation numbers
    tags: 'all',
    packages: {'[+]': ['tagformat', 'sections', 'autoload-all']},
    tagformat: {
      number: (n) => {
        const section = MathJax.config.section;
        return (section.useLetters ? section.letters[section.n] : section.n) + '.' + n;
      }
    }
  },
  startup: {
    ready() {
      const Configuration = MathJax._.input.tex.Configuration.Configuration;
      const CommandMap = MathJax._.input.tex.SymbolMap.CommandMap;
      new CommandMap('sections', {
        nextSection: 'NextSection',
        setSection: 'SetSection',
      }, {
        NextSection(parser, name) {
          MathJax.config.section.n++;
          parser.tags.counter = parser.tags.allCounter = 0;
        },
        SetSection(parser, name) {
          const section = MathJax.config.section;
          const c = parser.GetArgument(name);
          const n = section.letters.indexOf(c);
          if (n >= 0) {
            section.n = n;
            section.useLetters = true;
          } else {
            section.n = parseInt(c);
            section.useLetters = false;
          }
        }
      });
      Configuration.create(
        'sections', {handler: {macro: ['sections']}}
      );
      MathJax.startup.defaultReady();
    }
  }
};
```

This allows you to use `\setSection{1}` to set the section number to 1, and `\setSection{A}` to set it to the letter `A`.  After that, `\nextSection` will move to the next numeric or letter, depending on which is in play at the time.  You can go back and forth between the two as often as you wish.

**Comment by sciarraseb** [comment]
Works perfectly for me! I noticed a peculiar behaviour in the numbering in that the letters and numbers are not vertically aligned. There is a slight vertical shift that causes the letter to be aligned a bit above the number (see attached examples). 
<img width="58" alt="letter_number_offset_ex1" src="https://user-images.githubusercontent.com/85191660/222925986-72aca891-21d3-4485-a4a2-0666172102de.png">


<img width="55" alt="letter_number_offset_ex2" src="https://user-images.githubusercontent.com/85191660/222925979-2d376f64-5792-45bb-8edf-219b093fbd61.png">

**Comment by dpvc** [comment]
Are you using a WebKit-based browser, like Safari or Chrome?  Does it change if you zoom in and out?  There are some round-off bugs in WebKit that cause some characters to not fall on the baseline properly.

There are two approaches that you can use to overcome this.  The first is to specify a font to use for `<mtext>` elements (which are used for the tags).  Either set `mtextInheritFont: true` or `mtextFont: 'Times'` (or some other font) in the `chtml` block of your configuration.  That should get you good baselines, but the size may not match the rest of the math just right.  You could even use `mtextFont: 'MJXTEX'`, though it will usually be a little smaller.

Or you could use the following CSS styles:

``` css
mjx-mtext > mjx-c::before {
  padding-top: .75em ! important;
  padding-bottom: .25em ! important;
}
```

This is a terrible hack and may cause layout issues if you use `\text{}` inside square roots or some other places, but it will make the tags line up better.  You may be able to get away with it if you don't use too many other `\text{}` macros.

The v4 fonts work better, but still do have some alignment issues like this.

**Comment by sciarraseb** [comment]
Perfect! Yup, this works out for me. Although I use `\text{}` in some instances, it doesn't seem to have any effect. If I may ask one more follow-up question, is it possible to modify the line spacing of multiline `\{align}` environments or do I have to add  `\\[_pt]` at the end of each line (e.g., `\\[5pt\`?  As an example, here is what of my `\{align}` environments looks like: 
```
\begin{align}
\Gamma(x)\Gamma(y) &= \int_0^1 \int_0^\infty  u^{x+y-1} e^{-u} v^{x-1} (1 - v)^{y-1} \text{ } du\text{ }dv \nonumber \\\\
&=  \int_0^\infty  u^{x+y-1} e^{-u}\text{ } du \int_0^1v^{x-1} (1 - v)^{y-1} \text{ }dv \nonumber \\\\
&=  \Gamma(x + y)\mathrm{B}(x,y) \nonumber \\\\
\mathrm{B}(x,y) &= \frac{\Gamma(x)\Gamma(y)}{ \Gamma(x + y)}   \nonumber \\\\
\end{align}
```

**Comment by sciarraseb** [comment]
Ok perfect! I just had to use `load: ['tex]/mathtools']` and it worked. I am also trying to use the line breaking capabilities of MathJax 4.0.0 with the following code but am not able to get it to work. Any help is appreciated. 


```
window.MathJax = {
  section: {
    n: -1,
    useLetters: false,
    letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
  },
  loader: {load: ['[tex]/tagformat', '[tex]/mathtools']},
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']], //allow inline math
    displayMath: [['$$','$$']],
    tagSide: 'right', //location of equation numbers
    tags: 'all',
    packages: {'[+]': ['tagformat', 'sections', 'autoload-all', 'mathtools']},
    tagformat: {
      number: (n) => {
        const section = MathJax.config.section;
        return (section.useLetters ? section.letters[section.n] : section.n) + '.' + n;
      }
    }
  },
  displayOverflow: 'linebreak',
    linebreaks: {                  // options for when overflow is linebreak
      inline: true,                   // true for browser-based breaking of inline equations
      width: '100%',                  // a fixed size or a percentage of the container width
      lineleading: .2,                // the default lineleading in em units
      LinebreakVisitor: null,         // The LinebreakVisitor to use
    },

  startup: {
    ready() {
      const Configuration = MathJax._.input.tex.Configuration.Configuration;
      const CommandMap = MathJax._.input.tex.SymbolMap.CommandMap;
      new CommandMap('sections', {
        nextSection: 'NextSection',
        setSection: 'SetSection',
      }, {
        NextSection(parser, name) {
          MathJax.config.section.n++;
          parser.tags.counter = parser.tags.allCounter = 0;
        },
        SetSection(parser, name) {
          const section = MathJax.config.section;
          const c = parser.GetArgument(name);
          const n = section.letters.indexOf(c);
          if (n >= 0) {
            section.n = n;
            section.useLetters = true;
          } else {
            section.n = parseInt(c);
            section.useLetters = false;
          }
        }
      });
      Configuration.create(
        'sections', {handler: {macro: ['sections']}}
      );
      MathJax.startup.defaultReady();
    }
  }
};
```
```
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-alpha.1/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
Thanks for the correction on the loader configuration.  I have updated the code sample above.  I'm glad it worked for you.

As for the line breaking, that can also be controlled by the contextual menu, and that overrides the document setting, so check that you haven't changed that to something other than linebreaking.

**Comment by sciarraseb** [comment]
I've tried modifying the contextual menu but have had no success. I likely do not understand correctly, but I have tried inserting the following code into `window.MathJax`

```
 options: {
    enableMenu: true,          // set to false to disable the menu
    menuOptions: {
      settings: {
        displayOverflow: 'linebreak'
        }
      }
   }

```
