### ISSUE TITLE
Web-Font TeX/Main/Italic fails to load in QTWebKit

### ISSUE THREAD

**Issue by mitya57** [mathjax/MathJax#302]
Hi!

I'm trying to add MathJax support to my text editor ([ReText][]), which uses [Qt version of WebKit engine][QtWebKit]. When the page has `\imath` symbol, it prints:

> Loading Web-Font TeX/Main/Italic

(this takes a few seconds) and then prints

> Web-Fonts not available -- using image fonts instead

and I get an ugly PNG image as a result.

I can't reproduce this problem with Gtk-based WebKit browsers and Firefox.

P.S: example of page I try to load:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
</head>
<body>
<p><mathjax>$$
\imath
$$</mathjax></p>
</body>
</html>
```

[ReText]: http://retext.sourceforge.net/
[QtWebKit]: http://trac.webkit.org/wiki/QtWebKit

**Comment by pkra** [comment]
Closing this as abandoned.
