### ISSUE TITLE
.MJX_LiveRegion causing visual interference

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#3026]
I (sometimes) get visual interference from for `.MJX_LiveRegion` (both v3 and v4) when the top of the body has a background color, 

E.g, https://jsbin.com/fiwematoyo/edit?html,css,output (sometimes) gives me 

![image](https://user-images.githubusercontent.com/426686/226377085-416a955b-61d4-4680-811b-884a7a1b1043.png)

I'm not sure if there's additional JS magic to detect the background color but looking at the styles at https://github.com/mathjax/MathJax-src/blob/1effea2c50f563e2b6cb730d4d251b423cb4e5be/ts/a11y/explorer/Region.ts#L337-L355, it seems they lack clipping or a shift off-screen (for some good suggestions, see https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html#hiding-content-visually)

**Comment by pkra** [comment]
For completeness, the white pixels in the screenshot are due to the live region DOM nodes.

**Comment by pkra** [comment]
Oh! Thanks for pointing that out. Sorry for the noise.

**Comment by dpvc** [comment]
Not at all; you gave more information, so that was useful.
