### ISSUE TITLE
MathJax v4: Line breaking does not work

### ISSUE THREAD

**Issue by netw0rkf10w** [mathjax/MathJax#3027]
### Issue Summary

When resizing the window to minimum width and refresh the page, line breaking does not work. For a demo, please visit this page: https://beta.diendantoanhoc.org/forum/250-b%C3%A2%CC%81t-%C4%91%C4%83%CC%89ng-th%C6%B0%CC%81c-va%CC%80-c%C6%B0%CC%A3c-tri%CC%A3/

### Technical details:

* MathJax Version: 4.0
* Client OS: (e.g., Mac OS X 10.15)
* Browser: (e.g., Safari and Chrome)

I am using the following MathJax configuration:

``` js
MathJax = {
  options: {
    enableMenu: true,          // set to false to disable the menu
    menuOptions: {
      settings: {
        displayOverflow: 'linebreak'
        }
      }
   },
  loader: {
    load: ['[tex]/colorV2', '[custom]/xypic.js'],
    paths: {custom: 'https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/'}
  },
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']],
    tags: 'ams',
    packages: {'[+]': ['color', 'xypic']}
  },
  svg: {
    fontCache: 'global',
    displayOverflow: 'linebreak'
  },
  chtml: {
    displayOverflow: 'linebreak'
  },
  linebreaks: {                  // options for when overflow is linebreak
    inline: true,                   // true for browser-based breaking of inline equations
    width: '100%',                  // a fixed size or a percentage of the container width
    lineleading: .2,                // the default lineleading in em units
    LinebreakVisitor: null,         // The LinebreakVisitor to use
  },
  startup: {
    ready() {
      //  Create the usual MathJax objects
      //
      MathJax.startup.defaultReady();
      //
      //  Add a TeX jax pre-filter to add \displaystyle{...} around in-line material
      //
      MathJax.startup.document.inputJax[0].preFilters.add((data) => {
        if (!data.math.display) {
          data.math.math = '\\displaystyle{' + data.math.math + '}';
        }
      });
    }
  }
};
```

and loading MathJax via

``` html
<script type="text/javascript" id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-alpha.1/es5/tex-chtml.js"></script>
```

**Comment by netw0rkf10w** [comment]
FYI the `Scroll` option doesn't seem to work either...

**Comment by netw0rkf10w** [comment]
@dpvc Thanks for your reply. I have tried:
- Remove the automatic addition of `\displaystyle{...}`.
- Replace `linebreak` in the above configuration with `scroll` (I believe that the latter gives aesthetically better results).

But there's no scrolling in the results: https://beta.diendantoanhoc.org/topic/192763-test-mathjax-wide-expressions/

I would have loved to have something similar to this one: https://codepen.io/pkra/pen/XXrQvG/

Please let me know what you think. Thanks a lot!

**Comment by dpvc** [comment]
> there's no scrolling in the results

It looks like when there are equation numbers, the `mjx-container` element gets a `min-width` that is disrupting the scrolling.  Try adding

``` css
mix-container {
  min-width: initial !important;
}
```

to your site CSS and see if that helps.

**Comment by dpvc** [comment]
> You've probably had an auto-correction that converted `mjx` to `mix` :D

Yes, it is quite annoying.  I don't always catch it.

> This scrolling feature is not available in MathJax v3, is that correct?

Not directly, but you can probably use

``` css
mjx-container {
  overflow-x: auto;
  min-width: initial !important;
}
```

to implement it in v3 (though it will not be under the control of the MathJax menu).  That would be easier than trying to use two copies of MathJax on the same page.

**Comment by netw0rkf10w** [comment]
@dpvc Thanks, it works!!

For the line breaking, it doesn't seem to work all the time. For example, I create two test topics in [this forum](https://beta.diendantoanhoc.org/forum/413-thử-các-chức-năng-của-diễn-đàn/), but it only works for the second (bottom) one:

<img width="361" alt="Screen Shot 2023-03-22 at 11 44 33" src="https://user-images.githubusercontent.com/8569515/226879733-46b6686b-eb24-42d1-88f6-a73874eb9f26.png">

Any ideas please? Thank you again for your help

**Comment by dpvc** [comment]
I looked into this, and it is due to the semantic enrichment that is part of the accessibility feature that is on by default.  It sometimes introduces groupings that are not in the original LaTeX, so that something like `$a+b+c > x+y$ can become the equivalent of `${a+b+c} > {x+y}$`.  Because MathJax uses rules based on TeX's in-line breaking rules, which allow breaks only a top-level (not braced) binary operators and relations, these extra braces prevent breaking at those points.  The top expression needs up having no valid breakpoints due to this.

I don't currently have a work-around for you for that, but we are looking into how best to resolve the issue in the next release.
