### ISSUE TITLE
equation extend over floating environment

### ISSUE THREAD

**Issue by svigerske** [mathjax/MathJax#3034]
### Issue Summary

We have a page with an equation in the main text and a floating element with a table-of-contents on the right. We use the SVG output.
Sometimes, the equation prevents links in the table-of-contents to be clickable. I think this is similar for #77, but now the problem appears when there are no equation tags. For MathJax 2 we used [a workaround](https://github.com/mathjax/MathJax/issues/77#issuecomment-140692137), but now we try to upgrade to MathJax 3.

This happens, for example, with Firefox 111.0 on ArchLinux (x86_64).

### Steps to Reproduce:

The files [main.html.txt](https://github.com/mathjax/MathJax/files/11234391/main.html.txt) and [stylesheet.css.txt](https://github.com/mathjax/MathJax/files/11234392/stylesheet.css.txt) illustrate the problem (remove the .txt extension).
Also online at http://www.gams.com/~svigerske/mathjaxbug/main.html

This renders as
![page](https://user-images.githubusercontent.com/10905411/232086606-c439871a-324a-4770-8b0a-92d6dea8ca61.png)

The link "Options for chance constraint models" on the right is not clickable.

### Technical details:

* MathJax Version: 3.2.2
* Client OS: ArchLinux
* Browser: Firefox 111.0

I am using the following MathJax configuration:

``` js
window.MathJax = {
  options: {
    ignoreHtmlClass: 'tex2jax_ignore',
    processHtmlClass: 'tex2jax_process'
  }
};
```

and loading MathJax via

``` html
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script type="text/javascript" id="MathJax-script" async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js"></script>
```

### Supporting information:

Included above.
No error message in the browser console.

**Comment by dpvc** [comment]
Adding

``` css
position: relative;
z-index: 100;
```

to the styles for class `.toc` should do the trick.

Alternatively, you could try

``` css
mjx-container[jax="SVG"][display="true"] {
  display: table ! important
}
```

but I'm not sure that won't have adverse consequences.

**Comment by svigerske** [comment]
Ah yes, we tried the first one and that works fine.

**Comment by dpvc** [comment]
OK, great.  Glad it worked.
