### ISSUE TITLE
Close the context menu programmatically

### ISSUE THREAD

**Issue by msharkeyiii** [mathjax/MathJax#3044]
Hi, this is going to be a really quick question. Is it possible to close a MathJax context menu programmatically?

Basically trying to simulate what happens when I hit the Escape key on my keyboard, but through an external control. I tried simulating it with new KeyboardEvent() for "Escape" but didn't do anything.

If there is a utility to do it through the window.MathJax object would be ideal.

Thank you!

**Comment by dpvc** [comment]
You can use

``` js
MathJax.startup.document.menu.menu.unpost()
```

to remove the menu from javascript.

**Comment by msharkeyiii** [comment]
Awesome sauce, thank you!
