### ISSUE TITLE
Unicode ɛ causes error

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#3048]
### Issue Summary

ɛ (Open-mid front unrounded vowel) will cause MathJax input error

### Steps to Reproduce:
![image](https://github.com/mathjax/MathJax/assets/53823634/9eb9929a-c971-417b-9580-5fd0649eaced)

1. Open MathJax demo
2. Type `$ɛ$`
3. See the error

**Comment by dpvc** [comment]
This is a duplicate of #3033.  See my first comment there for a work-around until v4 comes out.
