### ISSUE TITLE
use } in mmlToken

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#3053]
**Is your feature request related to a problem? Please describe.**
`}` cannot be used in mmlToken: as `\mmlToken{mo}{}}` will produce extra brace error
I was using `\mmlToken` to add a MathML attribute `minsize` `maxsize`

**Describe alternatives you've considered**
I tried `\mmlToken{mo}{\}}`, `\mmlToken{mo}\}`, `\mmlToken{mo}{\rbrace}`, `\mmlToken{mo}{&#125;}` and `\mmlToken{mo}{&amp;#125;}` but they display in verbatim.
I can use `\left.\right\}` to produce `<mo>}</mo>` but cannot add a MathML attribute

**Technical details**
MathJax Version: 3.2.2

**Comment by dpvc** [comment]
Yes, the text argument to mmlToken is not processed and is used verbatim.  In v4, there is a new macro `\U{...}` that lets you enter characters in `\mmlToken` (and other places) as raw unicode character (unlike `\unicode`, which places them in an `<mi>`).  So you could use that to get the needed character once the next version of v4 is released.

For now, you could define your own macro that allows escaped characters.  Something like

``` js
MathJax = {
  tex: {
    packages: {'[+]': ['mml-mo']}
  },
  startup: {
    ready() {
      const Configuration = MathJax._.input.tex.Configuration.Configuration;
      const CommandMap = MathJax._.input.tex.SymbolMap.CommandMap;
      new CommandMap('mml-mo', {
        mmlMo:   'MmlMo'
      }, {
        MmlMo(parser, name) {
          const text = parser.GetArgument(name).replace(/\\(.)/g, '$1');
          const mo = parser.create('token', 'mo', {}, text);
          parser.Push(mo);
        }
      });
      Configuration.create('mml-mo', {
        handler: {macro: ['mml-mo']}
      });
      MathJax.startup.defaultReady();
    }
  }
};
```

should do it.
