### ISSUE TITLE
MJ4 mathjax-tex: ⎵ in munder is typeset with horizontal line too high

### ISSUE THREAD

**Issue by AlexEdgcomb** [mathjax/MathJax#3060]
### Issue Summary

munder in ⎵ with MJ4's mathjax-tex typesets the horizontal line too high

### Steps to Reproduce:

1. Go to https://codepen.io/alexedgcomb/pen/xxQbBNK

Observed: The horizontal line is too high
<img width="37" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/4c0ebe31-4b40-4546-9c85-a36a0a553b4c">

Expected: The horizontal line to align with the right angle'd lines, like in mathjax-modern
https://codepen.io/alexedgcomb/pen/JjeozQo
<img width="33" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/afe1c4cb-36e5-4154-8804-7d50b0d8b444">

### Technical details:

* MathJax Version: 4.0.0-alpha.1
* Client OS: MacOS 13.4
* Browser: Firefox 114

I am using the following MathJax configuration:

``` js
MathJax = {output:{font:'mathjax-tex'}};
```

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax-full@4.0.0-alpha.1/es5/tex-mml-svg.min.js"></script>
```

### Supporting information:

Maybe the inverse issue of https://github.com/mathjax/MathJax/issues/3011 ?

**Comment by dpvc** [comment]
Yes, there were several stretchy characters that came from hacks used in v2 to fake the needed characters for the stretchy assembly.  In v2, the stretchy data allowed character positions to be adjusted when used in an assembly, but v3 and v4 don't have that (the adjustments are made in the glyphs in the fonts themselves).  When the v3 fonts were constructed, I didn't have time to make the moved characters, so those stretchy characters where not fully correct.  

This is also a duplicate of #2415.  See the discussion there for some work-arounds for CHTML and SVG output.

**Comment by dpvc** [comment]
PS, this is fixed in the next release of v4.

**Comment by AlexEdgcomb** [comment]
@dpvc , thank you! The CSS in https://github.com/mathjax/MathJax/issues/2415#issuecomment-616763411 resolved for me
