### ISSUE TITLE
Is pseudocode possible?

### ISSUE THREAD

**Issue by sebsciarra** [mathjax/MathJax#3071]
Is it possible for MathJax to process pseudocode? As an example, would MathJax be able to process the below LaTeX code: 

```tex
\usepackage{algpseudocode}

\begin{algorithmic}
\State $i \gets 10$
\If{$i\geq 5$} 
    \State $i \gets i-1$
\Else
    \If{$i\leq 3$}
        \State $i \gets i+2$
    \EndIf
\EndIf 
\end{algorithmic}
```

**Comment by dpvc** [comment]
MathJax doesn't process arbitrary LaTeX packages; they have to be converted to javascript for use with MathJax, and `algpseudocode` isn't one that has been ported.  So no, you can't do this directly.

Of course, you can use HTML mixed with MathJax to get the same result without too much effort:

``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>Pseudo code example</title>
<script>
MathJax = {
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
}
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" defer></script>
<style>
.pseudocode {
  white-space: pre;
  font-weight: bold;
}
</style>
</head>
<body>

<div class="pseudocode">
$i \gets 10$
if $i\geq 5$ then
    $i \gets i-1$
else
    if $i\leq 3$ then
        $i \gets i+2$
    end if
end if 
</div>

</body>
</html>
```

yields

<img width="153" alt="psuedocode" src="https://github.com/mathjax/MathJax/assets/432782/2cb93791-7be1-450b-9001-0ffd4652a6ad">

which is pretty close.

Alternatively, if you have existing LaTeX code that you re trying to use, you could probably implement the `algorithmic` environment with a little work.

A third option would be to write some javascript that works outside of MathJax to find this environment in the page, modify it to the format in my HTML example above, and have that run before MathJax does.

Those are the options as I see it.

**Comment by pkra** [comment]
FYI there's https://github.com/SaswatPadhi/pseudocode.js

**Comment by dpvc** [comment]
Thanks @pkra.  Good to know there is already a potential solution.

**Comment by sebsciarra** [comment]
Hmm, I tried using it with MathJax 4.0 but it does not work. Specifically, the pseudocode renders if I use 
```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js?config=TeX-AMS_CHTML"
        integrity="sha256-DViIOMYdwlM/axqoGDPeUyf0urLoHMN4QACBKyB58Uw="
        crossorigin="anonymous" referrerpolicy="no-referrer">
</script>
```
but not render if I use the most recent version of MathJax 
```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-alpha.1/es5/tex-mml-chtml.js"></script>
```

**Comment by dpvc** [comment]
Use 4.0.0-beta.3 rather than 4.0.0-alpha.1.  The font packages have changed for the beta release, and so don't work with the older alpha release.  If you want to use the alpha version, then you need to add

``` js
   output: {
    fontPath: 'https://cdn.jsdelivr.net/npm/%%FONT%%-font@1.0.0-alpha.1/es5/output/fonts/%%FONT%%'
  }
```

to the MathJax configuration in order to force the older version of the fonts.

**Comment by dpvc** [comment]
Also, you don't say which approach you were taking.  My comment above is about the example file that I posted above.  If you use the javascript package suggested by Peter, then the configuration in the README file for that package should work for v4 as well (but you will need to change the URL and SHA to the ones for v4.0).

**Comment by sebsciarra** [comment]
Sorry about that. Hmm, I've tried to use the four-step approach mentioned in [ https://github.com/SaswatPadhi/pseudocode.js]( https://github.com/SaswatPadhi/pseudocode.js) but I can only get it to work with MathJax 3. I'll open an issue in that directory.

**Comment by sebsciarra** [comment]
Just as a follow, the issue report continues here: [https://github.com/SaswatPadhi/pseudocode.js/issues/44](https://github.com/SaswatPadhi/pseudocode.js/issues/44)
