### ISSUE TITLE
[v4 beta 3] \begin{equation} leading to "Erroneous nesting of equation structures"

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#3081]
Something as simple as  `\begin{equation} a = 0. \end{equation}` is giving me an erroneous nesting error (using `https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-mml-chtml.js`).

**Comment by dpvc** [comment]
This is a duplicate of #3070.  There is a work-around listed there.

**Comment by pkra** [comment]
Oh, sorry for missing that one. Thanks for the pointer.
