### ISSUE TITLE
Scroll Position corruption

### ISSUE THREAD

**Issue by thx1111** [mathjax/MathJax#3094]
When, first, saving a scroll position in a MathJax document, second, closing and reloading the same document, and third, restoring the same scroll position in that document, the resulting scroll position in the document displayed is being changed.  The resulting position can be "nearby" to the original position, but is generally displaced further "up" or "down" and can easily be distant by more than a full display screen.

This behavior is unexpected and can only be explained as a consequence of some scroll position corruption by MathJax.  In particular, the left-right scroll position is sometimes, but not always, being reset to "zero", no matter the original scroll position.  These effects are seen when the 'ui/lazy' module is *not* loaded, since it might be expected that the proper restored scoll position resulting *while* the 'ui/lazy' module is operating could be difficult to determine.  The 'ui/lazy' module is not a factor here.

The change in the top-bottom scroll position might be the result of some attempt by MathJax to adjust the "current" scroll position from "before" to "after" the typesetting operation executes, but that is only a guess.  "Something" is corrupting the final scroll position in the Document Object Model.

The saved scroll position is taken with javascript:
```
        let myIframe = document.querySelector('iframe');
        let xscroll = myIframe.contentWindow.scrollX;
        let yscroll = myIframe.contentWindow.scrollY;
```
The restored scroll position is applied after the MathJax document is reloaded into an iframe, with:
```
        document.querySelector('iframe').contentWindow.scrollTo({
          left: xscroll,
          top: yscroll,
          behavior: "instant",
        });
```
These functions work as would be expected when MathJax is not being used in a document.

This corruption of the restored scroll position is being observed while using a simple "real-time" html editor, derived from a version by "Mori" at stackexchange, which does not save or restore the scroll position.  The version of the editor including scroll position restoration is attached here, for testing with MathJax.
[sparseRTEdit.zip](https://github.com/mathjax/MathJax/files/12422789/sparseRTEdit.zip)

Of course, the scroll position displacement is only apparent with a displayed document which includes, for instance, extensive sequences of equations.  Running MathJax over a short document with little embedded typesetting does not show this corruption of the scroll position.  Repeatedly loading the MathJax document being edited, by making insignificant changes, for instance by adding white-space into the html, usually produces repeated offsets, up or down, to the resulting scroll position.  There also can be various "convergent" scroll positions within the displayed document.  Cobble together a long document with a random mix of vector equations and plain text to see these effects.

mathjax 3.2.2-1
Arch Linux
various Firefox and Chromium based web browsers
```
<script>
MathJax = {
//  loader: {load: ['ui/lazy']},
  tex: {
    inlineMath: [['$', '$'], ['\\(', '\\)']]
  }
};
</script>
<script>
  document.querySelector('html').onmouseenter = function() {
   var scriptx = document.createElement('script');
//   scriptx.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js';
   scriptx.src = 'mathjax/tex-chtml-full.js';
   scriptx.async = true;
   document.head.appendChild(scriptx);
  };
</script>
```

**Comment by lucasvreis** [comment]
I think this is just a matter of using `promise` properly for scrolling after the math is typeset. See this fiddle:
https://jsfiddle.net/jun0oq7w/3/

**Comment by thx1111** [comment]
Can you show how to use that in context?  Just naively wrapping `scrollTo()` in this function simply breaks `scrollTo()`.
```
        MathJax.startup.promise.then(() => document.querySelector('iframe').contentWindow.scrollTo({
          left: xscroll,
          top: yscroll,
          behavior: "instant",
        }));
```
And, this MathJax function wrap has to be disabled conditionally when MathJax is not available or when the document does not use MathJax.

**Comment by lucasvreis** [comment]
You are probably loading MathJax _inside_ the `iframe`, so the `MathJax` object is inside there too. Perhaps something like this would work:
```js
iframeWindow = document.querySelector('iframe').contentWindow;
iframeWindow.pageshow = () => {
  iframeWindow.MathJax.startup.promise.then(() => {
    iframeWindow.scrollTo({
          left: xscroll,
          top: yscroll,
          behavior: "instant"
    });
  );
};
```

**Comment by thx1111** [comment]
Hmm - there was another closing brace needed there, but no, the iframe does not display with the function like that.

**Comment by lucasvreis** [comment]
@thx1111 perhaps you can share a full example of what you are trying to do in a JSFiddle? When manipulating `iframe`s there are multiple things you should be aware of, including same-origin policy.

**Comment by dpvc** [comment]
The problem is what @lucasvreis suggests, that you are scrolling the iframe before MathJax typesets its mathematics. Typesetting the math changes the size of the content above the scroll point, moving the window to a new position, since the LaTeX is rarely the same size as the typeset mathematics, especially for displayed equations.  He is right that you need to wait for the math to be typeset before scrolling to the location within the iframe.

To do this, you could use something like the following.  Add

``` js
iframex.contextWindow.mjx = {xscroll, yscroll};
```

to the bottom of your `preview()` function, in place of (or just after) the current `toScroll()` call, and then use

``` js
  MathJax = {
    startup: {
      ready() {
        MathJax.startup.defaultReady();
        MathJax.startup.promise.then(() => {
          scrollTo({
            left: mjx.xscroll,
            top: mjx.yscroll,
            behavior: "instant",
          });
        });
      }
    }
  };
  document.querySelector('html').onmouseenter = function() {
   var scriptx = document.createElement('script');
   scriptx.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js';
//   scriptx.src = 'mathjax/tex-chtml-full.js';
   scriptx.async = true;
   document.head.appendChild(scriptx);
  };
```

instead of your current header script.

You won't like this, however, as it requires the browser to redraw the page before the scrolling is performed, and that will show a visible flash of the initial position.

An alternative would be to make the body of the iframe have `visibility:hidden` and have the MathJax promise remove that after scrolling.  That will still flash, but it will flash a white background rather than the top position of the window.

Better would be to use a "double-buffered" approach, where your new iframe is inserted before the current one (so that it appears "behind" it in the container `div`), then it is typeset and scroll, and then after that, you remove the original iframe.  That takes a little more work, and requires the iframe to call back to the parent window after it is finished being typeset, but that gives the smoothest result.  It is also a good idea to keep track of when MathJax is running so that if the user is typing quickly and MathJax hasn't finished typesetting when they type the next character, you don't get several MathJax instances running simultaneously in several stacked iframes.  Instead, keep a variable that indicates that MathJax is running, and if `preview()` is called while that is true, use a second variable to indicate that a preview needs to be run after MathJax finishes.  Then when the first MathJax is done, you can update the preview again to get the changes that the user has made in the meantime.

For example, use

``` js
    function preview() {
      if (run.checked) {
        if (!running) {
          running = true;
          let myIframe = frameWrap.lastChild;
          let xscroll = myIframe.contentWindow.scrollX;
          let yscroll = myIframe.contentWindow.scrollY;

          const iframex = document.createElement('iframe'); // a fresh iframe to delete JavaScript variables
          iframeWrap.insertBefore(iframex, frameWrap.firstChild);

          const iframeDoc = iframex.contentDocument;
          iframeDoc.write(textarea.value);
          iframeDoc.close();

          iframex.contentWindow.mjx = {xscroll, yscroll};
        } else {
          buffered = true;
        }
      } else {
        updatePreview();
      }
    }
    
    function updatePreview() {
      if (running) {
        running = false;
        frameWrap.removeChild(frameWrap.lastChild);
        if (buffered) {
          buffered = false;
          preview();
        }
      }
    }
```

in place of your `preview()`, use

``` js
    const run = document.getElementById('run'),
      textarea = document.querySelector('textarea'),
      download = document.getElementById('download'),
      chooseFile = document.getElementById('chooseFile'),
      frameWrap = document.getElementById('iframeWrap');
    let running = false;
    let buffered = false;
```

for your initialization, change the iframe wrapper div to

``` html
    <div id="iframeWrap"><iframe></iframe></div>
```
so it contains no spaces or newlines (so it's only child is the iframe), and use

``` js
  MathJax = {
    startup: {
      ready() {
        MathJax.startup.defaultReady();
        MathJax.startup.promise.then(() => {
          if (window.parent) {
            scrollTo({
              left: mjx.xscroll || 0,
              top: mjx.yscroll || 0,
              behavior: "instant",
            });
            window.parent.updatePreview();
          }
        });
      }
    }
  };
   var scriptx = document.createElement('script');
   scriptx.src = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js';
//   scriptx.src = 'mathjax/tex-chtml-full.js';
   scriptx.async = true;
   document.head.appendChild(scriptx);
```

as the script in the user's document.  Of course, you could incorporate this into a separate .js file and have them load that script rather than putting it all in-line, but that's up to you.

In any case, I think that will do it for you.

**Comment by thx1111** [comment]
@dpvc

> The problem is what @lucasvreis suggests, that you are scrolling the iframe before MathJax typesets its mathematics.

Ah!

> To do this, you could use something like the following.

You have given me some ideas!

>  It is also a good idea to keep track of when MathJax is running so that if the user is typing quickly and MathJax hasn't finished typesetting when they type the next character, you don't get several MathJax instances running simultaneously in several stacked iframes.

But no, that is not the way that this works.  And, *that* is the thought behind only running MathJax `onmouseenter`.

There is no reason for more complexity.  Since the scroll positions are being read and saved *after* MathJax typesetting, then it is simpler to just run the `scrollTo()` function a *second* time, immediately *after* MathJax typesets its mathematics.  And remember, this whole editing/rendering process must still work even when there is no MathJax being loaded from the user's document.

The difficulty here is with trying to create global variables for `xscroll` and `yscroll`, because the iframe is being treated as a separate document.  Your solution is concise:
```
...
        const iframex = document.createElement('iframe');
        document.querySelector('iframe').replaceWith(iframex);
        iframex.contentWindow.mjx = {xscroll, yscroll};
...
```
And then, from https://docs.mathjax.org/en/latest/web/configuration.html#startup-action, *Performing Actions During Startup*, 
```
...
<script>
  MathJax = {

// run scrollTo() a second time after MathJax typesetting is complete
    startup: {
      pageReady: () => {
        return MathJax.startup.defaultPageReady().then(() => {

          scrollTo({
            left: mjx.xscroll,
            top: mjx.yscroll,
            behavior: "smooth"
          });
          console.log("Second Scroll: " + mjx.xscroll + " " + mjx.yscroll);
          parent.mjax = true;
        });
      },
  ...
  };
...
</script>
...
```
Here, `mjax` is defined in the edit/render *parent* document of the user's document, then set in the *user's* document when MathJax is present, in order to have this edit/render document also work *without* any MathJax document.  Otherwise the MathJax typesetting will "disappear" as soon as the user enters a character in the edit textarea.

The idea is to have the parent edit/render document either run the preview function immediately when MathJax is *not* present, or to only run MathJax after `mouseenter` when MathJax *is* present.  In this way, the MathJax typesetting does *not* "disappear" *when* the user is entering text in the edit textarea.

To enable this, a new "gating" function is added to the edit/render document.  Here, the previous `preview()` function name is taken over by this "gating" function, and the original function is renamed to `ifpreview()`:
```
...
    var mjax = false;

    function preview() {
      if (!mjax) {
        ifpreview();
      } else {
        console.log("mjax = " + mjax);
        document.querySelector('iframe').addEventListener("mouseenter", ifpreview);
      }
    }

    function ifpreview() {
...
```

When the user pauses to view their updates, and moves the mouse cursor into, or outof and into, the render iframe, the MathJax typesetting will "disappear" and scroll immediately to the saved position as it would be without the typesetting, display this way for some moments - which may be long moments when MathJax first loads - until MathJax is ready, and finally scroll *smoothly* to the position associated with the previously saved position as it appears *with* the typesetting.

QED, as that was the intended behavior!  Thanks very much for your help.

BTW, watching the console log, there is a bit of a housekeeping exception being thrown repeatedly by MathJax itself, whenever the mouse cursor enters the iframe:
```
Uncaught TypeError: setting getter-only property "Package"    tex-chtml-full.js:1:13781
```
The formal coding rule is discussed at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only, *TypeError: setting getter-only property "x"*,

>The JavaScript [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode)-only exception "setting [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get)-only property" occurs when there is an attempt to set a new value to a property for which only a getter is specified.
...
