### ISSUE TITLE
Doubt with Typescript type definition

### ISSUE THREAD

**Issue by tbontb-iaq** [mathjax/MathJax#3118]
Hello, I am a newbie. Please forgive me if I've made any mistakes.

I'm using mathjax in my project, and this project uses typescript, so I installed `@types/mathjax`. But I didn't find the type definition I wanted. For example, type definitions for methods like `Mathjax.tex2mml`, `Mathjax.tex2mmlPromise`.

Did I miss something? What should I do?

**Comment by dpvc** [comment]
The `@types/mathjax` definitions seem to be for the v2 API.  That has changed significantly for v3 (e.g., the `MathJax.tex2mml` and `MathJax.tex2mmlPromise()` functions are v3 and not part of v2.

Also note the capitalization of `MathJax` (not `Mathjax`).

**Comment by tbontb-iaq** [comment]
Sorry for the misspelling. So is there a type definition for v3?

**Comment by chriszrc** [comment]
@tbontb-iaq it would appear that with v3, you no longer need the third party typings - https://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#es6-and-typescript

**Comment by tbontb-iaq** [comment]
Nice work.
