### ISSUE TITLE
inlineMath&displayMath property in tex don't work when using init function in node.js

### ISSUE THREAD

**Issue by matto49** [mathjax/MathJax#3147]
### Issue Summary

When using v4 to transform tex,the inlineMath and displayMath can't be recognized thought I have added them to the tex setting.
I'm curious about how to setup tex in 'init' function,as "output" works well but "tex" failed.

### Steps to Reproduce:

1. import init function from 'mathjax'
2. setup init options
3. tex2svg works well but inlineMath can't be recognized

### Technical details:

* MathJax Version: 4.0.0-beta.4
* Client OS: (e.g., Mac OS X 14.1.2 )
* Node:v20.10.0

I am using the following MathJax configuration:

```ts
const { init } = require("mathjax");

init({
  loader: {
    load: [
      "input/tex",
      "output/svg",
    ],
    paths: {
      "mathjax-tex": "mathjax-tex-font",
    },
  },
  output: {
    font: "mathjax-tex",
  },
  SVG: {
    fontCache: "none", // or 'global' or 'local',
  },
  TeX: {
    tagSide: "right", // side for \tag macros
    tagIndent: "0.8em", // amount to indent tags
    multlineWidth: "100%", // width of multline environment
    useLabelIds: true, // use label name rather for ids
    tags: "ams", // or 'ams' or 'all'
    inlineMath: [
      // start/end delimiter pairs for in-line math
      ["$", "$"],
      ["\\(", "\\)"],
    ],
    displayMath: [
      // start/end delimiter pairs for display math
      ["$$", "$$"],
      ["\\[", "\\]"],
    ],
    processEscapes: true, // use \$ to produce a litteral dollar sign
    processEnvironments: true, // process \begin{xxx}...\end{xxx} outside math mode
    processRefs: true, // process \ref{...} outside of math mode,
    maxMacros: 10000, //maximum number of macro substitutions per expression //10000
    maxBuffer: 15 * 1024, // maximum size for the internal TeX string (5K) //5 * 1024
  },
}).then((mathJax) => {
  const tempSvg = mathJax.tex2svg(
    `$x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}$$$x = \\frac { - b \\pm \\sqrt { b ^ { 2 } - 4 a c } } { 2 a }$$\\(y = \\frac { \\sum _ { i } w _ { i } y _ { i } } { \\sum _ { i } w _ { i } } , i = 1,2 \\ldots k\\)\\[y = \\frac { \\sum _ { i } w _ { i } y _ { i } } { \\sum _ { i } w _ { i } } , i = 1,2 \\ldots k\\]`,
    { display: true }
  );
  console.log(mathJax.startup.adaptor.outerHTML(tempSvg));
});
```

get the content under
<img width="670" alt="image" src="https://github.com/mathjax/MathJax/assets/54560462/9da66d97-27f1-4441-89bd-a94dae09710f">
want the content like
<img width="444" alt="image" src="https://github.com/mathjax/MathJax/assets/54560462/0b8b3b3c-add8-4946-a30c-de635dfb799d">

**Comment by dpvc** [comment]
In versions 3 and 4, you need to use `tex` not `TeX` for the configuration for the TeX input jax.  Also, `svg` not `SVG` for the SVG output jax.

Also, the `tex2svg()` function takes a TeX string, not an HTML text string, so you don't include the delimiters, and you can only process a single expression at a time.  To do multiple expressions, you should set the contents of some element and then use `typesetPromise([element])` to typeset the contents of that element.

**Comment by matto49** [comment]
Thanks a lot for answering the problem.It's my fault to misunderstand the use of tex2svg.I will use it to analyse a single expression at a time only.
