### ISSUE TITLE
Extension loaded via autoload may not be available in time when ui/lazy is also loaded

### ISSUE THREAD

**Issue by AlexEdgcomb** [mathjax/MathJax#3161]
### Issue Summary

An extension (e.g., cancel) that is loaded via autoload may not be available in time when ui/lazy is also loaded, leading to the typeset showing the macro name in red, like `\cancel`.

### Steps to Reproduce:

1. Go to https://codepen.io/alexedgcomb/pen/KKEgLOJ
2. Refresh if typesetting worked
Observed: About 1 in 5 page refreshes, the cancel package is not found before typesetting
<img width="82" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/2cccf2d5-59a9-418a-bc51-2170b0762356">

I tried to reduce the config as much as possible. Seems that each of the remaining pieces is necessary to produce the issue.

### Technical details:

* MathJax Version: 4.0.0-beta.3
* Client OS: Mac OS 13.4
* Browser: Firefox 121.0.1

I am using the following MathJax configuration:

``` js
MathJax = {
  loader: { load: [ 'ui/lazy' ] },
  options: { lazyAlwaysTypeset: '.disable-lazy-typesetting' },
  output: { font: 'mathjax-tex' },
};
```

and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.3/tex-mml-svg.js"></script>
```

I am have a delayed call to both add content and typeset: 

```js
async function typeset() {
  document.getElementById('test').innerHTML = '<div class="disable-lazy-typesetting"><p>\\( \\cancel{x} \\)</p></div>';
  await MathJax.startup.promise;
  MathJax.typesetPromise([ document.getElementById('test') ]);
}

setTimeout(typeset, 10);
```

### Supporting information:

* Also sometimes happens in:
    * MJ4.0.0-alpha.1 https://codepen.io/alexedgcomb/pen/zYbKQVY
    * Chrome 120.0.6099.216 (Official Build) (arm64)
* No console errors/warnings
* A simple workaround is to add the needed extensions (e.g., cancel) to the configuration. No less, I thought y'all might appreciate this report :)

**Comment by dpvc** [comment]
This turns out to be an issue with how `MathJax.startup.promise` is resolved, and is a duplicate of #3130.

You can work around it by adding

``` js
    startup: {
      pageReady() {
        const config = MathJax.config.startup;
        const output = MathJax.config.output;
        return (config.loadAllFontFiles && output.font ? output.font.loadDynamicFiles() : Promise.resolve())
          .then(config.typeset && MathJax.typesetPromise ?
                () => MathJax.startup.typesetPromise(config.elements) : Promise.resolve);
      }
    }
```

to your Mathjax configuration for now.

BTW, I do get a console error about `null` not having a `parentNode`, so I'm not sure why you aren't seeing that.

**Comment by AlexEdgcomb** [comment]
@dpvc , thank you! Works wonderfully.

> BTW, I do get a console error about null not having a parentNode, so I'm not sure why you aren't seeing that.

Doh, I do see that. Not sure how I missed that... Definitely would have helped me find https://github.com/mathjax/MathJax/issues/3130 on my own!

**Comment by dpvc** [comment]
> Doh, I do see that. Not sure how I missed that... Definitely would have helped me find #3130 on my own!

No problem.  I'm just glad it wasn't something that I had to fix.  :-)
