### ISSUE TITLE
MJ4.0.0-beta.4: Cannot nest \begin in parens

### ISSUE THREAD

**Issue by AlexEdgcomb** [mathjax/MathJax#3186]
### Issue Summary

beta.4 throws error `Erroneous nesting of equation structures` when a `\begin` macro is nested in parens

### Steps to Reproduce:

1. Go to https://codepen.io/alexedgcomb/pen/jOJJwMe

Observed: Error message
<img width="273" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/7d4acb48-f02d-4b9f-9273-072af169fb91">

Expected: No such error, like in MJ4.0.0-alpha.1
https://codepen.io/alexedgcomb/pen/poYYwEq
<img width="50" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/e1649aa6-aaaa-491a-95d0-82570d963673">

### Technical details:

* MathJax Version: 4.0.0-beta.4
* Client OS: MacOS 13.4
* Browser: Firefox 122.0.1

I am not using a MathJax configuration and loading MathJax via

``` html
<script src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.4/tex-mml-svg.js"></script>
```

### Supporting information:

The following typesets via MacTex
```
\documentclass[11pt, oneside]{article}
\usepackage{amsmath}
\begin{document}
{
    \begin{align*}a = 1 \\ b = 2\end{align*}
}
\end{document}  
```
<img width="73" alt="image" src="https://github.com/mathjax/MathJax/assets/3512898/534d74f0-de58-4c6f-ab5f-16de4f7142c1">

**Comment by dpvc** [comment]
MathJax is correct in its error message.  The LaTeX test document you provide isn't the same as what you have given MathJax; in particular, the `align*` environment in your test document is in text mode, not math mode.  In your codepen example, you have `\(...\)` around the braces, but they are missing from your LaTeX example.  That makes a big difference.

In actual LaTeX, 

``` latex
\(
  {
    \begin{align*}a = 1 \\ b = 2\end{align*}
  }
\)
```

produces the error `Package amsmath Error: \begin{align*} allowed only in paragraph mode` while

``` latex
\[
  {
    \begin{align*}a = 1 \\ b = 2\end{align*}
  }
\]
```
 produces the error `Package amsmath Error: Erroneous nesting of equation structures` that MathJax uses.

So this error is correct.

Perhaps you mean to use the `aligned` environment, which is allowed inside math mode?  That is

``` latex
\[
  {
    \begin{aligned}a = 1 \\ b = 2\end{aligned}
  }
\]
```

is allowed (in MathJax and in LaTeX).

**Comment by AlexEdgcomb** [comment]
@dpvc , thank you for explaining!
