### ISSUE TITLE
Reverse back the Render to Original Source

### ISSUE THREAD

**Issue by jd-inferq** [mathjax/MathJax#3191]
**Is your feature request related to a problem? Please describe.**
Yes, I want to get the original source tex back from MathJax chtml render with tex-mml-chtml.js config

**Describe the solution you'd like**
It would be nice to have an API where you pass rendered html, config used to generate the render and get back source tex.

**Describe alternatives you've considered**
I have considered manual tools, but it's better to have official tool and reverse engineering doesn't seem that easy either.

**Comment by dpvc** [comment]
> It would be nice to have an API where you pass rendered html, config used to generate the render and get back source tex.

In the next beta release of v4, the internal MathML node will be marked with the LaTeX that produced each node, and those attributes will be retained in the HTML output, so the top-level math node will contain the LaTeX that generated it.  But that is not yet in a public release.

For v3 and below, what you are asking for isn't directly possible, unless you are in control of the page that contained the LaTeX source originally.  In that case, you could use a renderAction or a TeX input jax post-filter to attach the original LaTeX as a data attribute on the internal MathML root node.  That attribute will be preserved in the HTML output, and you could get the original LaTeX from that.

**Comment by jd-inferq** [comment]
Hey, I guess we can close the issue as feature will be added in next version.
