### ISSUE TITLE
Does MathJax v3 support explicitly set line breaking?

### ISSUE THREAD

**Issue by khesualdo** [mathjax/MathJax#3201]
In the docs it says that **automatic** line breaking is **not** supported. However, I found some people suggesting to explicitly add `chtml: { linebreaks: { automatic: true } }` to the config object.

```
MathJax = {
  tex: {
    inlineMath: [['$', '$']]
  },
  svg: {
    fontCache: 'global'
  },
  chtml: {
    linebreaks: { automatic: true }
  }
};
```

I don't get the expect result since the MathJax generated elements still go outside the boundaries of the parent element. Is `chtml: { linebreaks: { automatic: true } }` a valid config parameter?

**Comment by dpvc** [comment]
>  I found some people suggesting to explicitly add `chtml: { linebreaks: { automatic: true } }` to the config object.

Those people are wrong  They are suggesting using a v2 configuration option in your v3 configuration, which won't work.  The docs are correct that this is not supported in v3, and no configuration options will change that.  Version 2 did include automatic breaking, and v4 (now in beta release) does, but with a different configuration setting.  If you want to try v4, you can get automatic line breaking in display equations and (unlike v2), inline expressions can be broken as well.

See the [v4-alpha release notes](https://github.com/mathjax/MathJax-src/releases/tag/4.0.0-alpha.1#linebreaking) for details of the v4 line breaking.
