### ISSUE TITLE
Two equals Element with different index don't permit callback of the first invocated

### ISSUE THREAD

**Issue by GabrieleMartino** [mathjax/MathJax#3204]
I source from latest 

'https://polyfill.io/v3/polyfill.min.js?features=es6'
'src=""https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

I have a set of DOM element where I take the text from a text area and i put the formula in a p tag each. They differ only from and index 'next' at end of the id.

Example

textarea id= 'source2'    wrapped in div element
p id ='display2 ' wrapped in div element
all wrapped in div element of index 2.

A finite subset are loaded in the page at start, fixed as guide and the other are not, dinamically created but they differ only on an index taken from a global int variable next than in example is equal to 2.

When I start the istruction for 
```
//line code
var math = MathJax.Hub.getAllJax(idParagraph)[0]; 
```

the procedure fails if the function displayFormula() is invocated first for dinamically inserted : indeed in the first invokation for fixed subset success and then success for dinamically created. Having access to debug F12 command element differ only for index. 

the source code is a function that display or the text area or the formula at click of the mouse and show hide element:

```
//function that displayFormula
function displayFormula(idsourceformula){
            //Control formula is not empty and obtain idDisplay
            ...
            alert(idDisplay + " " + formula); //always correct
            var math = MathJax.Hub.getAllJax(idParagraph)[0]; // here fails for first trigger dinamically
            alert(math);    //On fail result undefined On success report an HTML object
            MathJax.Hub.Queue(["Text", math, "\\displaystyle{"+formula+"}"]);
            MathJax.Hub.Queue(["Typeset", MathJax.Hub]); 
            ...
            //show , hide elements
}
```

error on debug report:

```
//Error Report
Uncaught Error Error: Can't make callback from given data
    at USING (cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:5527)
    at Push (cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:8305)
    at Queue (cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML:19:34894)
    at displayFormula (localhost/comp.html꞉16:13:85:25)
    at onclick (localhost/comp.html:1:1)
```

I have tryed to substitute a p tag with a div always the same problem.
Hoping to have been exaustive.

I'm also tryeng to move to version 3, and I saw i need to define an object MathJax on my own and any way it doesn't find the function window.MathJax.typeset();

I think (my opinion) that documentation in MathJAx lack of concreteness, see for example the w3C school how they make example in the docuementation (try code) whereas in MathJax in all abstract because they try to be too exhaustive in cover all aspect also if concise in each part.

**Comment by GabrieleMartino** [comment]
I solved with upgrading version 3.

Basically the solution constit in configuring the page with
1) a update script of MathJax from where to recover Mathjax v3 (see docuementation [https://docs.mathjax.org/en/latest/web/configuration.html#loading-mathjax]), 
2) configuring a MathJax = ... in a script tag of the page where to put inside the configuration options, defult key to embrace Latex text, and important to put inside ready object function, the tex packages and all (see documentation at Configuring and Loading MathJax [(https://docs.mathjax.org/en/latest/web/configuration.html)]
3) to recall call the MathJax.typePromise() after have put the formula in innerHTML of the object your are looking to display.

I tryed answer because I would have used your time and response; Thank you MathJax.

**Comment by dpvc** [comment]
The key difference between your initial description using version 2 (your first posting), and your three points for version 3 (second post) is step 3, where you can `Mathjax.typesetPromise()`.  Version 2 had a similar call that you need to do in order to typeset the math, and it looks like you never did that.  It would have been something like `MathJax.Hub.Queue(['Typeset', idParagraph])`.  The call to `MathJax.Hub.getAllJax()` will only find items that have been typeset previously, so if you haven't queued the `Typeset` call, this will return no results, as you found.

**Comment by dpvc** [comment]
I'm glad you were able to figure out a solution on your own.  Good work.  I am closing this as completed.
