### ISSUE TITLE
Change MathJax version 2.7.9 to 3.2.2

### ISSUE THREAD

**Issue by f-lambda-z** [mathjax/MathJax#3219]
How do I change the MathJax version in the code below from `v2.7.9` to `v3.2.2`?

```html
<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS_CHTML-full" integrity="sha512-M36RUChWzAh1veeenRZFql7HydLEnkYmoloiCvVrhz402UZgKI93qkV7SsaxtVKdN95Wzajh39ysrXCq34NTsg==" crossorigin="anonymous"></script>
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    CommonHTML: {
      linebreaks: {
        automatic: true
      }
    },
    tex2jax: {
      inlineMath: [ ['$', '$'], ['\\(','\\)'] ],
      displayMath: [ ['$$','$$'], ['\\[', '\\]'] ],
      processEscapes: false
    },
    displayAlign: 'left',
    messageStyle: 'none'
  });
</script>
```

Please help 🙏🏻

**Comment by dpvc** [comment]
Please see the [Upgrading from v2](https://docs.mathjax.org/en/latest/upgrading/v2.html) section of the [MathJax documentation](https://docs.mathjax.org/en/latest) for details about upgrading from version 2 to version 3.

Note in particular, that there is a [configuration conversion tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) that will convert your configuration to a corresponding v3 one.  Note that linebreaking is not available in version 3, but is in version 4 (now out in beta release), if that is necessary for your site.

**Comment by f-lambda-z** [comment]
> Please see the [Upgrading from v2](https://docs.mathjax.org/en/latest/upgrading/v2.html) section of the [MathJax documentation](https://docs.mathjax.org/en/latest) for details about upgrading from version 2 to version 3.
> 
> Note in particular, that there is a [configuration conversion tool](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html) that will convert your configuration to a corresponding v3 one. Note that linebreaking is not available in version 3, but is in version 4 (now out in beta release), if that is necessary for your site.

Oh, I see. Thanks for the answer 🙏🏻
