### ISSUE TITLE
polyfill.io hostile takeover

### ISSUE THREAD

**Issue by alexvoss** [mathjax/MathJax#3247]
### Issue Summary

Polyfill.io was bought by a Chinese company earlier this year and has since then gone on to inject malicious code into the polyfill code it delivers. Polyfill.io should be removed where possible, if not Fastly and Cloudflare have set up mirrors of safe code, see:

* [Polyfill supply chain attack hits 100K+ sites](https://sansec.io/research/polyfill-supply-chain-attack)
* [Polyfill.io JavaScript supply chain attack impacts over 100K sites](https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/)

The section on [Browser Compatibility](https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility) instructs users to use `polyfill.io`, which should be changed either to one of the trustworthy mirrors or the section should be dropped if it is unlikely that people will still need this. 

### Steps to Reproduce:

This concerns the documentation, specifically the section on [Browser Compatibility](https://docs.mathjax.org/en/latest/web/start.html#browser-compatibility).

### Technical details:

none, this is about the documentation

### Supporting information:

see links posted above, also [this issue over at Material for MkDocs](https://github.com/squidfunk/mkdocs-material/issues/7295)

**Comment by dpvc** [comment]
I have updated the documentation, and placed a warning about using the original `polyfill.io` site.

**Comment by alexvoss** [comment]
Superb! Thanks for the prompt action.

**Comment by ensanbinadam** [comment]
هل هناك بديل ؟
