### ISSUE TITLE
How do I configure  MathJax={} when there is a missing error or other error to display original data instead of error.

### ISSUE THREAD

**Issue by guoyutao** [mathjax/MathJax#3254]
How do I configure  MathJax={} when there is a missing error or other error to display original data instead of error.

for example：
![image](https://github.com/mathjax/MathJax/assets/11513385/dd95d6d6-4cfd-4320-a77d-a09de03d69b6)

I want to show original data:$h^2+left(\frac{8}{2}\right)^2=5^2$

**Comment by dpvc** [comment]
Please fill out the template for your issue, as you have not provided crucial information (in particular, the version of MathJax that you are using, your current configuration, the script call that loads MathJax, etc.).  The configuration will depend on those factors.
