### ISSUE TITLE
Faulty display of Sigma Notation

### ISSUE THREAD

**Issue by luis261** [mathjax/MathJax#3260]
### Issue Summary

I'm having trouble with a Sigma Notation in a formula here on GitHub: https://github.com/scikit-learn/scikit-learn/issues/29365#issuecomment-2225692407
(GitHub uses MathJax to render latex according to https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions)

### Steps to Reproduce:

this is the context where the issue occurs:
inline version: $a_{ pts } coredist(x_{ i }) = \left(\frac{ \sum_{ z=2 }^{N_{ i }} { \left(\frac{ 1 }{ KNN(x_{ i }, z) }\right)^{ n } } }{ N_{ i }-1 }\right)^{ -\frac{ 1 }{ n } }$

block version:
$$a_{ pts } coredist(x_{ i }) = 
\left(\frac{ \sum_{ z=2 }^{N_{ i }} { \left(\frac{ 1 }{ KNN(x_{ i }, z) }\right)^{ n } } }
{ N_{ i }-1 }\right)^{
 -\frac{ 1 }{ n } 
}$$

The `N_i` end value should display above the Sigma symbol.
It doesn't though, at least not on my end (both for the block and the inline version): ![image](https://github.com/user-attachments/assets/58b1a7e9-61d2-4fbb-9835-591c771748e6)

the `\sum_` component does work properly in isolation:
$$\sum_{ z=2 }^{N_{ i }}$$

### Technical details:

* Client OS: Windows 10 Enterprise Version 22H2, OS build 19045.4529
* Browser: Firefox 127.0.2 (64-Bit)

### Supporting information:

 * there aren't any error messages or warnings related to this in my browser console
 * the formula renders correctly on other engines: e.g. https://www.quicklatex.com/ (server side rendering)

EDIT:
I also had a look at this from a few other environments:
- same host, also Windows but Chrome: same issue
- different host, same OS with different architecture, Chrome: same issue
- Debian OS on yet another host, Firefox: same issue
- Chrome on Android: same issue

Also for some reason the block version above isn't rendering at all now even though it is 100% identical to the one [here](https://github.com/scikit-learn/scikit-learn/issues/29365#issuecomment-2225692407), which is rendering?! ... very strange

---

Sorry for just "chucking this over the fence" without looking too deep into it, but maybe the issue is obvious?
Probably there's something wrong in the formula after all -- some MathJax implementation specific syntax I need to adjust? Or maybe I should report this to GitHub instead?

Unsure if this is the right place to report this, but thank you in advance anyway!

**Comment by dpvc** [comment]
This is a bug with the way GitHub has handled their MathJax implementation.  They are removing some attributes from the tags that MathJax produces, and those are needed in order to trigger the CSS needed to style the elements properly.  This was reported in [bug list](https://github.com/orgs/community/discussions/17051) over a year ago, so it looks like they not be interested in doing anything about it.  Unfortunately, that is outside our hands.

**Comment by luis261** [comment]
Oh ok - interesting, sad to hear that there isn't any real recourse for me to get it fixed/low likelihood of the fix moving forward.

Thank you so much anyway for the information you've provided though! Very helpful, especially with you having a direct reference to the bug in store, now I at least know for sure there isn't anything wrong with the formula source itself (:
