### ISSUE TITLE
When will ES6 be released?

### ISSUE THREAD

**Issue by dragonliuhu** [mathjax/MathJax#3262]
When will ES6 be released?

**Comment by dpvc** [comment]
Note that this issue tracker is designed for reporting bugs in MathJax or for requesting new features.  Questions like this one are better asked in the [MathJax user's forum](https://groups.google.com/g/mathjax-users).

mathJax v4.0.0, now out in beta release, has both MJS (ES6) and CJS (ES5) versions.  The 4.0.0-beta.7 version is the current release candidate for 4.0.0, and is feature complete.  We are in the process of a code clean-up which should lead to the official 4.0 release later this year.

**Comment by dragonliuhu** [comment]
Sorry, I'm not very good at English.

Now, my project installed 'mathjax@beta', but I don't know how to import the MathJax.

I don't know which file to import so that I can use MathJax in es6 mode.

**Comment by dragonliuhu** [comment]
> Note that this issue tracker is designed for reporting bugs in MathJax or for requesting new features. Questions like this one are better asked in the [MathJax user's forum](https://groups.google.com/g/mathjax-users).
> 
> mathJax v4.0.0, now out in beta release, has both MJS (ES6) and CJS (ES5) versions. The 4.0.0-beta.7 version is the current release candidate for 4.0.0, and is feature complete. We are in the process of a code clean-up which should lead to the official 4.0 release later this year.

Sorry, I'm not very good at English.

Now, my project installed 'mathjax@beta', but I don't know how to import the MathJax.

I don't know which file to import so that I can use MathJax in es6 mode.

**Comment by dpvc** [comment]
Closing this in favor of #3263.
