### ISSUE TITLE
Unexpected c201C and c201D characters surrounding string literal <ms> content

### ISSUE THREAD

**Issue by brichwin** [mathjax/MathJax#3264]
### Issue Summary

When rendering string literal content MathJax is unexpectedly adding quotation marks (c201C ... c201D) around it. For example, when rendering this example from [3.2.6 String Literal <ms>](https://www.w3.org/TR/mathml-core/#string-literal-ms) in [MathML Core](https://www.w3.org/TR/mathml-core/):
```xml
<math>
  <mi>s</mi>
  <mo>=</mo>
  <ms>"hello world"</ms>
</math>
```
MathJax version: 4.0.0-beta.6 renders it as follows (note the dueling quotation marks):
![image](https://github.com/user-attachments/assets/14e2f263-ba63-4b57-b5cc-e8dd35a167e3)
#### Expected Result
I'm guessing that the expected result is to render it as shown in the MathML Core spec (Where only one
set of quotes are shown - those supplied as part of the string literal):
![image](https://github.com/user-attachments/assets/7b32a15f-e864-4be0-b8b5-2f3cb8b98862)
Also, here is how the above mathML renders natively in Edge which behaves as the example in the MathML Core spec:
![image](https://github.com/user-attachments/assets/ebf56068-0149-4349-87a2-147da9162392)

### Steps to Reproduce:

1. Create MathML content with a string literal <ms>....</ms>
2. Render it in a web page using MathJax 4.0.0-beta6
3. Note that MathJax adds double quotes to the string literal when it renders it.

#### Why do you consider this to be a bug? 
MathJax's output looks sloppy if the expression author included beginning/ending quotation marks as part of the string literal and the result is a doubly quoted string. Also, MathJax appears to remove the author's ability to have a string literal displayed w/o quotation marks.

### Technical details:

- MathJax Version: 4.0.0-beta.6
- OS Version:
-- OS Name: Microsoft Windows 11 Home
-- Version: 10.0.22631 Build 22631
-- Locale: United States
- Browser: Microsoft Edge Version 126.0.2592.113 (Official build) (64-bit)

I am not manually configuring MathJax. I am loading MathJax via:

``` html
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.6/tex-mml-chtml.js"></script>
```

### Supporting information:

Here are two simple pages demonstrating the issue (one with MathJax, one without MathJax):
- [string_literal_ms_mathjax_4](https://brichwin.pages.iu.edu/tests/mathJax/string_literal_ms_mathjax_4.html)
- [string_literal_ms_no_mathjax](https://brichwin.pages.iu.edu/tests/mathJax/string_literal_ms_no_mathjax.html)

**Comment by dpvc** [comment]
MathJax implements the [MathML3](https://www.w3.org/TR/MathML3) specification, whose description of the `<ms>` element [states](https://www.w3.org/TR/MathML3/chapter3.html#presm.ms)

> By default, string literals are displayed surrounded by double quotes, with no extra spacing added around the string. ... For example, `<ms>double quote is "</ms>` might be rendered as `"double quote is \""`.

MathML Core is a newer, but more limited, standard, and it does not include a number of features from MathML3 that MathJax relies on.  It is unlikely that MathJax will implement MathML Core; instead, we are more likely to move to [MathML4](https://www.w3.org/TR/MathML4), whose description of `<ms>` is [the same](https://www.w3.org/TR/mathml4/#presm_ms) as that in MathML3.  

The MathML Core section you link to above is followed by a note that indicates

> In MathML3, it was possible to use the `lquote` and `rquote` attributes to respectively specify the strings to use as opening and closing quotes. These are no longer supported and the quotes must instead be specified as part of the text of the `<ms>` element.

But the MathML4 spec says that it should be a superset of MathML Core, so this seems to be an inconsistency with that statement.  I'm not sure which is to be considered authoritative for this.

You say that 

> MathJax appears to remove the author's ability to have a string literal displayed w/o quotation marks.

but you can use the `lquote` and `rquote` attributes of the `<ms>` element (available in MathML3 but not MathML Core) to specify empty strings for the quotes, as in

``` xml
<math>
  <mi>s</mi>
  <mo>=</mo>
  <ms lquote="" rquote="">"hello world"</ms>
</math>
```

for example.  Using these attributes in MathML Core should not hurt anything, if you need to be compatible with both.

It is also possible to set the default values for the `lquote` and `rquote` attributes in MathJax to be empty strings with the following MathJax configuration:

``` js
MathJax = {
  startup: {
    pageReady() {
      const {MmlMs} = MathJax._.core.MmlTree.MmlNodes.ms;
      MmlMs.defaults.lquote = "";
      MmlMs.defaults.rquote = "";
      MathJax.startup.defaultPageReady();
    }
  }
};
```

**Comment by brichwin** [comment]
Ah! Thanks for the in-depth and timely reply! I was told by someone (not a MathJax dev) to keep to MathML Core and I apparently grew lazy and forgot to go back and look at the MathML3 specification.

And, thanks for the info about the MathJax config and the lquote/rquote attributes.

Best regards,
  Brian

**Comment by dpvc** [comment]
Just FYI, I mistakenly used `pageReady()` rather than `ready()` and `deafultPageReady()` rather than `defaultReady()` in my configuration.  I've changed it above for anyone looking at this in the future.  The `pageReady()` would work, but one should use `return MathJax.startup.defaultPageReady()` in that case.
