### ISSUE TITLE
Subscript notation issue

### ISSUE THREAD

**Issue by fonnesbeck** [mathjax/MathJax#329]
When I try to use the grouped subscript notation ("_{<something>}"), Mathjax does render it. For example:

```
$\mathbf{X}_i = (X_{1i}, \ldots, X_{ki})$
```

does not work because of the "_{1i}" subscripts. If I just use a single subscript, like "X_i", it works fine.

**Comment by jay3sh** [comment]
I ran into another variant of the issue. Sometimes the underscores work without escaping them. But then they stop working when there are multiple underscores in the expression. The solution is to escape all occurences of underscores. In case of markdown add `\` before underscore.

**Comment by bergercookie** [comment]
FYIW the backslashing solution provided by @fonnesbeck is relevant to other Markdown presentation projects such as [Gitpitch](https://github.com/gitpitch/gitpitch)

**Comment by vman049** [comment]
Escaping the underscore with backslash works well for `inlineMath` but doesn't work for `displayMath` (text doesn't get subscripted). Is there a solution that is consistent across both `inlineMath` and `displayMath`? Related links: [1](https://stackoverflow.com/a/50004449/424306), [2](https://pennbay.github.io/tech/mathjax.with.hugo/), [3](https://gohugo.io/content-management/formats/#mathjax-with-hugo), [4](https://stackoverflow.com/q/56890970/424306).

**Comment by dpvc** [comment]
@vman049, you don't say which content management system (CMS) you are using, and since this is really a question about the CMS more than it is about MathJax, that is probably going to make a difference.  You have referenced Jekyll and Hugo posts, so it is not clear which you are using.  Your third reference is to the official recommendation of how to handle MathJax in Hugo, so if you are using Hugo, that shows how to be able to use the same notation within inline and display math.

You also don't say what the actual result is in displayed equations, e.g., whether the underscore is displayed as a literal underscore, for example.  If so, it is probably also possible to define `\_` as `_` in your Mathjax configuration via

```
MathJax.Hub.Config({
  TeX: {
    Macros: {
      '\\_': '_'
    }
  }
});
```

so that `\_` and `_` both do the same thing, and you will be able to use `\_` in in-line mode (where Markdown will remove the`\`) and also `\_` in display mode (where it will be a macro equivalent to `_`).  So that would mean you could use `\_` for subscripts in both situations.

**Comment by lukesalamone** [comment]
Just wanted to mention for anyone coming here from Google, I was able to solve this issue in hugo by wrapping my mathjax in `<p>` tags.

**Comment by tqch** [comment]
Instead of appending an awkward backslash `\` in front of an underscore `_`, it seems that we can consistently avoid this kind of behavior by simply breaking the parity of underscores (i.e. forcing each split of an equation to only contain odd number of underscores).

**Comment by HinnyTsang** [comment]
In my case, the `\_` is work for your reference.

**Comment by prasanth-ntu** [comment]
**Inline math expression:** `$\sum_{i=1}^{m}$` $\sum_{i=1}^{m}$ Summation superscript rendering is bad!
Another e.g., `$\frac{1}{2m}\sum_{i=1}^{m}{(\hat{y} _{i} - y _{i})}^{2}$` $\frac{1}{2m}\sum_{i=1}^{m}{(\hat{y} _{i} - y _{i})}^{2}$

**Block math expression:** Summation superscript is okay!
`$$\sum_{i=1}^{m}$$` $$\sum_{i=1}^{m}$$
Another e.g., 
$$\frac{1}{2m}\sum_{i=1}^{m}{(\hat{y} _{i} - y _{i})}^{2}$$

Any workarounds?

**Comment by dpvc** [comment]
@prasanth-ntu, if you are workin in GitHub, their implementation of MathJax has a number of serious issues, and if I recall correctly, this is one of them.  If you are not using Mathjax on GitHub, then can you point us to a page that exhibits the problem?

**Comment by prasanth-ntu** [comment]
@dpvc I am relatively new to writing/rendering math expressions in GitHub Markdown, as so far I have been either using Jupyter Markdowns or Latex directly to render them.
So, I believe I am using the GitHubs default implementation (MathJax). Are there any other implementations that we can use that can overcome these issues?

**Comment by dpvc** [comment]
> Are there any other implementations that we can use to render inline math expressiosn in GitHub markdown that can overcome the issues with MathJax?

It is not an issue with MathJax, it is an issue with how GitHub connects their markdown to MathJax.  In this case, they are filtering attributes from the MathJax output, and have removed ones that are critical to the layout.  That is not MathJax's fault, and is out of our control.  Unfortunately, users don't have the ability to change how GitHub Markdown handles that.  The only option I know of is to petition GitHub to correct their implementation.  There is a [discussion board](https://github.com/community/community/discussions?discussions_q=mathjax) where issues are listed, and a [bug report](https://support.github.com/contact/bug-report) system that you can use.  This is something that GitHub will have to address, not MathJax.
