### ISSUE TITLE
Chrome latest version: Text child nodes of <details> are invisible between two MathJax containers

### ISSUE THREAD

**Issue by hbghlyj** [mathjax/MathJax#3315]
### Issue Summary

Using Chrome 131.0.6778.140, text child nodes of &lt;details> are invisible between two MathJax containers.

### Steps to Reproduce:

1. Goto https://jsbin.com/xunedamilu/edit?html,output
2. Click "Details" to expand it
3. Using Chrome, some text nodes are invisible:
![image](https://github.com/user-attachments/assets/5c39c5c1-d452-47e4-98a0-d2761a43596d)
4. Repeat using Firefox, the output is normal:
![image](https://github.com/user-attachments/assets/ab745de6-c31e-4e7d-9515-3f20cef42617)
5. Replace "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js" with "https://cdn.jsdelivr.net/npm/mathjax@4.0.0-beta.7/tex-svg.js" and repeat.

### Technical details:

* MathJax Version: 3.2.2 and 4.0.0-beta.7
* Client OS: Windows 11
* Browser: Chrome 131.0.6778.140 (latest version)

**Comment by hbghlyj** [comment]
The text nodes are present in DOM, but not displayed.
![image](https://github.com/user-attachments/assets/d5e84224-9af2-4571-83be-434db5361376)

**Comment by hbghlyj** [comment]
Maybe related to "Improvements to <details> and <summary>" in Chrome 131: https://developer.chrome.com/blog/new-in-chrome-131#styling-details

**Comment by marcobaez-zybooks** [comment]
Seeing the same problem on Chrome v130 and v132 (Beta). Created this super simple example: 
[https://codepen.io/marcobaez21/pen/raBMMNW](https://codepen.io/marcobaez21/pen/raBMMNW)

**Comment by marcobaez-zybooks** [comment]
@hbghlyj Have you also reported this to the google chrome issues? Thank  you!

**Comment by marcobaez-zybooks** [comment]
In the Chromium bug report they confirmed that it was an issue on their end. Link here:
[https://issues.chromium.org/issues/383593255](https://issues.chromium.org/issues/383593255)

**Comment by dpvc** [comment]
For others seeing this, it appears that placing the contents of the `<details>` inside a `<div>` or `<p>` works around the problem.  E.g.

``` html
<details>
<div>
text $math$ text $math$ text
</div>
</details>
```

works as expected, while without the `<div>`,  the middle text doesn't appear.
