### ISSUE TITLE
Make MathJax class names unique [was: HTML-CSS output's classnames conflict with Google+'s]

### ISSUE THREAD

**Issue by christianp** [mathjax/MathJax#370]
Google+ uses classnames like `mi` and `mo` for various page elements (I don't think they're permanent names - the page is minified)

Since MathJax uses names like `mi` and `mo` for the corresponding MathML elements (that's right, isn't it?), Google+'s styles end up getting applied to MathJax elements if you use the bookmarklet to run MathJax on the page.

Prepending all MathJax's classnames with something like `MathJax-` would avoid the problem. Since the problem seems to be caused by minified CSS, it's likely to pop up on "real" pages elsewhere where you might expect MathJax to work with no problems.

Some discussion of this in a thread started by @pkra on Google+: https://plus.google.com/102694188490946876191/posts/RGM7xKzv871

**Comment by dpvc** [comment]
This was resolved in v3.
