### ISSUE TITLE
Parsing of \verb

### ISSUE THREAD

**Issue by fred-wang** [mathjax/MathJax#375]
Not sure these issues are too serious, but just for the record...

The following command is allowed in LaTeX but not accepted by MathJax:

\sqrt{\verb!}!}

The following command does not work either in MathJax. When I try it with a latex program I get "LaTeX Error: \verb illegal in command argument."

\sqrt[\verb!]!]

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/issue375.html
