### ISSUE TITLE
Mathjax not rendering in an SVG file

### ISSUE THREAD

**Issue by gsim** [mathjax/MathJax#394]
After a whole week of trying to get mathjax to work in an svg file I finally asked for help on stackoverflow.com.

I got one response suggesting it was a bug with mathjax. The relevent thread is http://stackoverflow.com/questions/14862410/render-mathjax-in-an-svg-file/14864156#14864156

The code I need is as follows:

    <svg width="1960" height="1080" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
      <script xlink:href="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
      <g>
        <title>Layer 1</title>
        <text xml:space="preserve" text-anchor="middle" font-family="serif" font-size="50" id="svg_1" y="223" x="636" stroke-opacity="0.8" stroke-width="0" stroke="#007FFF" fill="#000000">Hello World</text>
         <foreignObject x="100" y="100" width="200" height="200">
           <body xmlns="http://www.w3.org/1999/xhtml">
             <div>
               \[\frac{-b\pm\sqrt{b^2-4ac}}{2a}\]
             </div>
           </body>
         </foreignObject>
      </g>
    </svg>

The firefox error report says "'this.head' is undefined"

The expert at stackoverflow suggested I contact the Mathjax developers to fix the bug. As I had tried the code the expert suggested, together with many variations, I am really stuck on this.

Thank you

**Comment by woocommerce-themingcarst** [comment]
@gsim https://opencodes.space/questions/issue-with-distinguishing-javascript-code-from-an-svg-file
