### ISSUE TITLE
speeding up MathJax considerably by using localStorage

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax#411]
It would be nice if MathJax took advantage of localStorage by, when converting math blocks, storing the conversion result keyed on the original text in it. That way, when a page is reloaded, it won't need to run the conversion again, it can simply grab the fragment it already computed last time, and inject that directly into the page. For blocks that don't change (which is most page content) this would considerably speed up page load on reloads as well as revisits (my page, http://processingjs.nihongoresources.com/bezierinfo, would greatly benefit from this. It spends a long time in the MathJax conversion simply because it has a lot of separate blocks of math).

**Comment by qbolec** [comment]
From reading https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance I understand that one of the slowest parts of the process is measuring text as it by definition requires reflows. How about caching only that part: that is: what are the dimensions of a particular subexpression given font/size (and other things that affect the measurement).

**Comment by pkra** [comment]
That document is outdated (last edit Aug 2013). Especially the CommonHTML output requires very few measurements and the HTML-CSS output has significantly reduced its measurements. Caching those would not have been very effective though as the CSS of the context can influence them too.

**Comment by dpvc** [comment]
With v3's increased rendering speed, and the lazy-typesetting extension, it is unlikely that a caching mechanism like this will be implemented.

**Comment by Pomax** [comment]
it's also a seven year old request, closing it out is good triaging =D

**Comment by dpvc** [comment]
I've been going through all the old issues and closing what I can.  I know it has been a long time.
