### ISSUE TITLE
SVG fontdata.js can't be included in a combined configuration file

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#413]
Since SVG only has one font data file (currently) it would be nice to include that in the combined configuration files for SVG (a sponsor requested this).  But there is a timing problem with if if you do.  The `SVG.fontDir` is set in the SVG jax's `Config` method, so when the `fontdata.js` file is preloaded, that value is incorrect, and you don't get the proper `loadComplete()` call, and the SVG output hangs waiting for the file to load.

This can be fixed by using a signal to check for the SVG Config before doing the `loadComplete()`.

**Comment by AleksLife** [comment]
<span class="MathJax_Error" id="MathJax-Element-1-Frame" tabindex="0" data-mathml="<math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;><mi>l</mi><mi>a</mi><mi>t</mi><mi>e</mi><mi>x</mi><mfrac><mrow><mi>d</mi><mi>y</mi></mrow><mrow><mi>d</mi><mi>x</mi></mrow></mfrac><mo>=</mo><mi>f</mi><mrow><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo></mrow></math>" role="presentation" style="position: relative;"><span aria-hidden="true">[Math Processing Error]</span><span class="MJX_Assistive_MathML" role="presentation"><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>l</mi><mi>a</mi><mi>t</mi><mi>e</mi><mi>x</mi><mfrac><mrow><mi>d</mi><mi>y</mi></mrow><mrow><mi>d</mi><mi>x</mi></mrow></mfrac><mo>=</mo><mi>f</mi><mrow><mo>(</mo><mi>x</mi><mo>,</mo><mi>y</mi><mo>)</mo></mrow></math></span></span>

**Comment by pkra** [comment]
Please provide a (ideally minimal) live example exhibiting the problem.

**Comment by AleksLife** [comment]
I have solved the problem. It was that I had duplicated or even triplicated the script used to enable mathjax on web platforms, because I activated the simple mathjax plugin without erasing some scripts I had put in the comments before.
Anyway, thank you

**Comment by AleksLife** [comment]
I have solved the problem. It was that I had duplicated or even triplicated
the script used to enable mathjax on web platforms, because I activated the
simple mathjax plugin without erasing some scripts I had put in the
comments before
Thak you anyway
AVR

2016-02-18 3:22 GMT-05:00 Peter Krautzberger <notifications@github.com>:
