### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by Pomax** [mathjax/MathJax#419]
Does MathJax support lazy loading through any config option? I tried searching the documentation but it didn't mention anything about this. I have so much math on a page that MathJax actually stalls the page for a while when it's running a full processing parse, so if it's possible to lazy-load blocks (only when they scroll into view), that'd be very welcome =)

**Comment by Pomax** [comment]
cloisng this four year old request because there is no other way to get rid of it in my github.com/issues/mentioned list

**Comment by pkra** [comment]
Please don't close issues that the maintainers marked as feature requests.

**Comment by Pomax** [comment]
this is a feature request from **four years ago**. No one's worked on it, not one's going to work on it, and the person who marked it as feature request was you, after saying that it was impossible so this is pretty much irrelevant by now. I retract my feature request. If you still think this is a good idea, feel free to file a new issue that requests as from you but in the mean time there is no way to get this issue out of my github.com/issues/mentioned list without closing it. So I'm closing it.

**Comment by pkra** [comment]
You seem to be closing this issue not because it has been resolved or because it is no longer interesting but because you have an issue with GitHub's UI. I would kindly suggest to complain to GitHub about their UI instead.
