### ISSUE TITLE
A way to limit size of math to be processed

### ISSUE THREAD

**Issue by ghost** [mathjax/MathJax#425]
Is there a way to limit the length of MathML to be processed by MathJax?

Large amounts of MathML can result in browser hanging or becoming unresponsive (output as HTML+CSS).  It would be good to have a way to configure MathJax to not typeset MathML that exceeds some configured size/length.  Instead, display some configured HTML or message.

**Comment by dpvc** [comment]
With v3's increased typesetting speed and the lazy-typesetting extension, the need for such a limitation seems less compelling.
