### ISSUE TITLE
Why not add "Copy as TeX code" on the right-click menu?

### ISSUE THREAD

**Issue by haoyun** [mathjax/MathJax#442]
If I want to copy the formula, the following proess is need:

 `right-click` - `show math as` - `TeX commands` - `Copy the code in a new window`

Why not simplify the process, i.e., just add "Copy as TeX code" on the right-click menu?

**Comment by Yaffle** [comment]
Seems, Chrome 42 (or 43) supports this - see https://code.google.com/p/chromium/issues/detail?id=424968 - `document.execCommand("copy");` from "click" handler

**Comment by pkra** [comment]
Thanks for the pointer. IIUC, then `execCommand` is for documents in design mode so it's strange to see Chromium generalize it (there are obvious security concerns). 

Since it's currently only working in Chrome, it's not yet an option. We'll keep an eye on it.
