### ISSUE TITLE
\overline does not cope well with text-style limits on operators

### ISSUE THREAD

**Issue by EmilJ** [mathjax/MathJax#490]
`$\overline{\lim_{n\to\infty}}$` or `$\overline{\sum_{n=0}^N}$` are rendered with a short line in a superscript position after the main expression instead of an overline. (Yes, I know about \varlimsup, that’s not the point.) The bug seems to affect only named operators with \nolimits-style subscripts or superscripts, but without an explicit \nolimits declaration. The following all render corerctly:  `$\overline{\lim}$`, `$$\overline{\lim_{n\to\infty}}$$`, `$\overline{\lim\limits_{n\to\infty}}$`, `$\overline{\lim\nolimits_{n\to\infty}}$`,  `$\overline{\operatorname{lim}_{n\to\infty}}$`, `$\overline{X_{n\to\infty}}$`, `$\overline{\int_n}$`.

I’ve been testing it with the HTML–CSS output of MathJax versions 2.2 and 2.0, using local TeX fonts, in Firefox 14.0.1 and Opera 11.61 on Linux.

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/above-below/issue490.html
