### ISSUE TITLE
\not does not work on some relation symbols (Chrome, HTML/CSS, STIX)

### ISSUE THREAD

**Issue by LordFarin** [mathjax/MathJax#543]
One of the problems that I have been encountering persistently, and that I've now gotten fed up with, is the following:

I am using Chrome, HTML/CSS and local STIX fonts, and sometimes (e.g. in this Maths.StackExchange answer: http://math.stackexchange.com/a/450968) I am confronted with the fact that the \not operator does not render properly on all relation symbols (in ref'd case, the \succeq command), moreover, it does not render *at all*.

Switching to SVG solves the problem but is evidently an inferior solution. Your time is duly appreciated.

**Comment by pkra** [comment]
Cannot reproduce with newer versions of Chrome.
