### ISSUE TITLE
Implement a LaTeX command to draw over arc

### ISSUE THREAD

**Issue by fred-wang** [mathjax/MathJax#567]
We don't seem to have any command to draw an over arc.
See

https://groups.google.com/forum/#!searchin/mathjax-users/arc/mathjax-users/1cmdK1pJqeg/iEI4yMgcZdQJ
https://groups.google.com/forum/#!searchin/mathjax-users/arc/mathjax-users/OQ5abHvfHOI/sIYs73G5HKAJ
https://groups.google.com/forum/#!searchin/mathjax-users/arc/mathjax-users/x0nbdr9c47o/mwcTCudgV-MJ

and on Wikipedia:
https://bugzilla.wikimedia.org/show_bug.cgi?id=30215

Possible candidates seem to be \overarc, \widearc or \wideparent:
http://tex.stackexchange.com/questions/15468/frown-and-mathop-stackrel-overset

**Comment by dpvc** [comment]
I've moved this to v2.6 since I inadvertently did it thinking I was fixing #928.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
I've marked it "Test Not Needed" since the stretchy character is tested elsewhere.  The only real test would be whether the macro exists or not, and that doesn't really seem necessary.

**Comment by pkra** [comment]
:+1:

**Comment by eMPee584** [comment]
In the meantime, `\overarc` could be made an alias for `\overparen`, no?
