### ISSUE TITLE
greek characters in 'mi' with mathvariant="normal" are italicized when using the svg renderer 

### ISSUE THREAD

**Issue by svacha** [mathjax/MathJax#592]
Testing the following MathML content on the MathJax demo page (http://www.mathjax.org/demos/ ):

```
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mi>θ</mi>
<mi mathvariant="normal">θ</mi>
<mi mathvariant="italic">θ</mi>
<mtext>θ</mtext>
<mi mathvariant="sans-serif">θ</mi>
<mi mathvariant="sans-serif-italic">θ</mi>
</math>
```

Choosing the SVG math renderer, there is no difference between the display of the first four thetas (all as italics), but I would expect the second and fourth to be not italics. The HTML-CSS renderer does show the second and fourth as not italics. 

Does the SVG renderer not have the glyphs for the non-italicized greek characters?

Tested on Chrome Version 29.0.1547.76.

**Comment by dpvc** [comment]
MathJax now maps the Greek letters to their Math Alphanumerics positions, when there are one for the given mathvariant. If the fonts don't include the needed character, they are taken from a system font (when possible). I think this was in v3.0.4.
