### ISSUE TITLE
equation labels overlap equation in SVG output 

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#596]
Test case at http://jsfiddle.net/BABmX/

This doesn't happen with HTML-CSS output.

**Comment by dpvc** [comment]
This is resolved in the `issue596` branch of my fork of MathJax.  The corresponding behavior still needs to be checked in HTML-CSS and CommonHTML output.

**Comment by dpvc** [comment]
Resolved in HTML-CSS and CommonHTML output as well.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> in testsuite

**Comment by pkra** [comment]
:+1: :fireworks: 

:astonished: https://github.com/mathjax/MathJax-test/commit/8e80f37b16ea750996ce23bf7863a1eeae4191e8
