### ISSUE TITLE
Loading MathJax in IE causes javascript error if the document contains 30 or more stylesheets 

### ISSUE THREAD

**Issue by Androgenes** [mathjax/MathJax#60]
Platform: Win7 IE8

Create a sample file in the test directory, containing 30 (or more) style tags, like the following:

	<html>
	<head>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	<style type="text/css"></style>
	</head>
	<body>
	
	<script src='../MathJax.js'>MathJax.Hub.Config({ extensions: ['mml2jax.js'], jax: ['input/MathML','output/HTML-CSS']});</script>
	
	<math>
	</math>
	
	</body>
	</html>

Load this file in internet explorer. Javascript error will occur on the line containing the code 'i.styleSheet.cssText=h', because i.styleSheet's disabled property is set to true once it is inserted into the document.

**Comment by pkra** [comment]
Can we close this?

**Comment by dpvc** [comment]
Sure.
