### ISSUE TITLE
Switch from browser to rendering engines detection [was: Opera Blink is recognized as Chrome]

### ISSUE THREAD

**Issue by fred-wang** [mathjax/MathJax#620]
Follow-up the discussion about the future of Opera here:

https://groups.google.com/forum/#!searchin/mathjax-dev/future/mathjax-dev/pvJTgrhwB-M/UJNjdHQG0FAJ

Opera will use Blink in future versions, so all the Opera hacks should be replaced by Chrome hacks. The good news is that the MathJax sniffing detects Opera Blink as Chrome, so this is done automatically.

However, this means that things like MathJax.Hub.Browser or the about box now give the wrong information.

As mentioned in the Gecko sniffing issue, it could be better to have a rendering engine detection (Gecko, Blink, WebKit, Trident) that would be used for the rendering hacks. Probably the MathJax.Hub and about box should keep the browser detection.

**Comment by dpvc** [comment]
This is no longer relevant in v3, which doesn't do browser detection of any kind.
