### ISSUE TITLE
Put the loading box on the right side for RTL languages

### ISSUE THREAD

**Issue by amire80** [mathjax/MathJax#628]
As suggested by @fred-wang in #601, the loading box should be on the right side in RTL languages.

It's generally right to move things to other side for RTL. In the particular case of Wikipedia, where MathJax is probably going to be used heavily soon, it's definitely the right thing to do, because then it will be on the sidebar rather than hiding the article text.

**Comment by dpvc** [comment]
This is no longer relevant in v3, since it does not use a status indicator.
