### ISSUE TITLE
Nested align environments don't work

### ISSUE THREAD

**Issue by the-it** [mathjax/MathJax#698]
I'm using MathJax as a package in the wikimedia programm. In our project occurs sometimes nested align environments like this

```
<math>\begin{align}x \\\begin{align}y\\z \end{align}\end{align}</math>
```

Unfortunately these aren't processable by MathJax. The Error Message is 
"Incorrect nesting of equations"

**Comment by marnix** [comment]
For future reference: the latexMath_align.pdf document original has disappeared, here is an archived copy: http://wayback.archive.org/web/20120617014306/http://www.st.fmph.uniba.sk/~kiselak1/pdfka/tex/latexMath_align.pdf
