### ISSUE TITLE
Horizontal operator doesn't stretch in table in NativeMML output in FF

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#702]
In NativeMML output in Firefox,

    \begin{array}{c}
      \mmlToken{mo}[stretchy="true"]{_}\\
      \Rule{2em}{.5em}{0em}
    \end{array}

should have the underline stretch to the width of the rule in the second row, but it doesn't.

**Comment by pkra** [comment]
Closing this as `won't fix`.
