### ISSUE TITLE
Enabling MathML on Demos page can cause renderer choice to be sticky

### ISSUE THREAD

**Issue by Blaisorblade** [mathjax/MathJax#745]
If I enable MathML in the [MathML demos](http://www.mathjax.org/demos/mathml-samples/), I can't switch back — not without manually clearing a cookie.

When I enabled MathML rendering, I got a warning that it was not supported on my browser (Chrome 32). I was curious, so I enabled it anyway, but it turned out that the warning was right. So I switched back to HTML+CSS, and then reloaded the page. But on reloading, the page was rendering again through MathML! Even though there's a selector on that page, on every reload both the selector and the rendering mode were reset to MathML.

The same happened on the TeX demos, and I started fearing I broke MathML also for other websites (which was probably irrational).

Without an option to clear the default (I had changed the default? Nobody told me!), I had to manually remove the offending cookie*. This worked, but I shouldn't be required to take such measures.

*I found a cookie named `mjx.menu` with content `renderer%3ANativeMML%26%3Bwarned%3Atrue`, and removing it fixed the issue for me.

**Comment by pkra** [comment]
Closing this in favor of https://github.com/mathjax/MathJax-website/issues/19
