### ISSUE TITLE
parameter priorities for TeX commands (e.g., \sqrt\frac{}{})

### ISSUE THREAD

**Issue by nageh** [mathjax/MathJax#75]
As discussed on the mailing list it would be good if MathJax could correctly handle TeX commands taking a double-argument command as argument, such as in \sqrt\frac{3}{4}. This is because users will expect things to that they are used to as being acceptable in TeX.

As a quick fix it might be possible to special-case those few multi-argument commands such as \frac.

-nageh

**Comment by hbghlyj** [comment]
Hello,

If the macro is redefined: `$\let\myfrac=\frac   \sqrt\myfrac12$` works in LaTeX (see [TeXLive.net](https://texlive.net/run?%5Cdocumentclass%7Barticle%7D%0A%5Cbegin%7Bdocument%7D%0A$%5Clet%5Cmyfrac=%5Cfrac%20%20%20%5Csqrt%5Cmyfrac12$%0A%5Cend%7Bdocument%7D)), but throws error “Missing argument for `\myfrac`” in MathJax.

**Comment by dpvc** [comment]
@hbghlyj, yes, the special-case handling for `\sqrt\frac` is based on the specific name `\frac`.  The situation you are referring to is basically a quirk of LaTeX, not a true intended feature.  There is a lengthy discussion of this on the [user's forum](https://groups.google.com/g/mathjax-users/c/aCj-qkCp3hY/m/3gy72ZdZVzAJ) from way back in v1.0 that describes the situation in more detail.  It is unlikely that anything will be done about emulating this edge case.
