### ISSUE TITLE
various accent problems

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#764]
This example looks bad with TeX fonts

```
    <mover>
      <mi>H</mi>
      <mo>&#x02DD;</mo>
    </mover>
```

This example looks bad with STIX on HTML-CSS (no accent -- SVG is fine),

```
    <mover>
      <mi>H</mi>
      <mo>&#x0302;</mo>
    </mover>
```

**Comment by pkra** [comment]
Just for the record. Latin Modern seems to have more accents; perhaps we could re-use them for the MathJax fonts at some point.

**Comment by dpvc** [comment]
If we want to augment the MathJax TeX fonts, Latin Modern is a natural place to borrow from (if the license allows that).  One question is how large do we want to make the fonts?
