### ISSUE TITLE
SVG output can lose \text{} content

### ISSUE THREAD

**Issue by sam-pf** [mathjax/MathJax#775]
I may have found an odd issue with the SVG output, and I would like to report it.  Basically, `p \left(L_n \left| \text{evidence} \right.\right)` does not render well in the SVG output mode, while `p \left(\left. L_n \right| \text{evidence} \right)` works fine.  Both expressions render fine in the HTML-CSS mode.  It appears that  problem occurs when `\left` and `\right` encloses a pure text.  You can see it for yourself in the following link.

http://jsfiddle.net/SamG/w93vc/

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/delimiters/issue775.html
MathMLToDisplay/Presentation/GeneralLayout/mfenced/issue775.html
