### ISSUE TITLE
No subpixel hinting

### ISSUE THREAD

**Issue by Anixx** [mathjax/MathJax#782]
I have no subpixel smoothing in MathJax, in FireFox 28, 29 and IE 11 under Windows 7. Prevuously all was OK. I suspect this happened due to a Windows update. In other texts in FireFox and systemwide the smoothing is OK. What should I do to fix MathJax appearance?

I have this problem both in StackExchange and in Wikipedia as well as on the official MathJax site.

**Comment by dpvc** [comment]
Closing this as these are very old versions of browses and OS.
