### ISSUE TITLE
Implement Inline Source Renderer for Accessibility

### ISSUE THREAD

**Issue by camlorn** [mathjax/MathJax#788]
I am a visually impaired computer science student close to graduation who is attempting to self-study mathematics, particularly linear algebra and differential equations.  As it currently stands, MathJax is inaccessible to me due to the basically nonexistent support for MathML.  The upshot of this is that all the pages written with MathJax are inaccessible.  I am aware of my options including mathPlayer, and if necessary I will explain exactly why it fails to work for advanced mathematics.
Regardless, MathJax can display source for me.  Unfortunately, the process to get to this source must be done per-equation and involves at least 3 advanced functions of my screen reader and at least 10 keystrokes.  I would like to be able to set MathJax to display source instead of rendered content inline so that I can actually make progress on such sites as [this linear algebra textbook](http://linear.ups.edu/html/section-SSLE.html) and Stack Exchange.  My preferred format is LaTeX, and it is my understanding that it is a somewhat common skill among blind STEM majors to be able to at least read it (Wikipedia alt text/article source for example is a great resource for us).
I believe that implementing a renderer that simply displays the source is not a major change; the time it takes to start showing up on actual web sites obviously might be.  MathML might *finally* be going somewhere, but I don't expect to see good support for it for another year at least. Advanced mathematics will be the last to be made fully functional.  This would make a very wide variety of things accessible that are not currently, opening all sorts of avenues for me and other people in my situation.  It should work on all platforms, regardless of MathML support: I don't expect linux will have it for a while, for example, and some phones probably will never will.  I would like to at least discuss doing this.  I am open to attempting to implement this myself and probably have the programming skill required, but I am clearly unable to test any visual aspects that I might or might not break in the process.
The above is clearly useful for accessibility, but may also be useful for debugging.  I am not sure on this, but it might be useful to some for that alone.
If this is the inappropriate venue for this discussion, I would appreciate being pointed in the right direction.

**Comment by pkra** [comment]
This was fixed in v2.6 via the new PlainSource output, https://github.com/mathjax/MathJax/pull/1329
