### ISSUE TITLE
uneven subscripts

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#804]
I saw this [on TeX.SE](http://tex.stackexchange.com/questions/174107/stubscripts-on-variables-uneven) -- I was not sure if that's expected behavior or not.

`$|x_n y_n - xy|<\epsilon$` in TeX has slightly uneven subscripts (as opposed to TeX).

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/issue804.html
