### ISSUE TITLE
Empty annotation elements trigger Math Processing Error

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#805]
See also https://github.com/mathjax/ctop/issues/29.

I'm wondering if MathJax can be more graceful than a full Math Processing Error for the entire equation? The way I read the spec, empty annotation elements are valid (but I might be wrong).

```
  <math>
       <semantics> 
          <annotation> 
          </annotation> 
        </semantics> 
   </math>
```

**Comment by pkra** [comment]
I was writing a test when I noticed that the issue affects the CommonHTML output as well. Should I open a new item?

**Comment by pkra** [comment]
On second thought, perhaps #1006 is already suitable.

**Comment by dpvc** [comment]
I'm not sure I see the connection to 1006.  In any case, I've pushed a commit that resolves the issue for semantics.

**Comment by pkra** [comment]
Works for me. (I mentioned #1006 because that's also an issue about dealing with invalid MathML so I wasn't sure if they're related.)

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/ErrorHandling/issue805.html
