### ISSUE TITLE
Table columns are clipped to column width in HTML-CSS but not SVG

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#807]
http://www.w3.org/Math/testsuite/build/main/Presentation/TablesAndMatrices/mtable/mtable2-full.xhtml renders quite differently for me.

On Chrome 34, the bottom-center cell overlaps with bottom-left

On FF 29, the bottom-center cell "underlaps", i.e., disappears at the edge of the cell.

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue807.html
