### ISSUE TITLE
Refactor API

### ISSUE THREAD

**Issue by jmeas** [mathjax/MathJax#808]
Right now the API of MathJax is pretty unusual for a Javascript library, I think.

Wouldn't it be nice...

```js
// Store your MathJax config anywhere...
var myConfig = {};

// Oh, hey, you've got MathJax installed!
// Well, as you've come to expect as a Javascript developer,
// MathJax doesn't do anything on its own. So it's just
// sitting around waiting for you to command it.
window.MathJax;

// Let's start by configuring it
MathJax.configure( myConfig );

// Alright, MathJax is finally ready...let's process the whole page!
MathJax.process();
```

I just made up the API here, but something like this:

1. Should be more familiar to developers
2. Prevents unusual practices like [this whole page](http://docs.mathjax.org/en/latest/dynamic.html)
3. Gives more control to the developer

This would be a huge refactor, no doubt, but I think it's worthwhile.

The current configuration works great for non-programmers who just want to throw the code up on their page, but at too great a cost, I think. To bundle Mathjax in an app and give it custom configuration is almost comically unusual.

Plus, supporting the current behavior with this updated API would be simple, I think. You could just make a bundle with some reasonable defaults (presumably the same defaults that are there now, like showing the loading bubbles in the lower left and processing the whole page automatically). This could be packaged alongside the developer-friendly library. And everyone is happy.

:dancers:

**Comment by pkra** [comment]
=> closed as abandoned.
