### ISSUE TITLE
\alignat and \alignedat spacing with relations

### ISSUE THREAD

**Issue by orangeplanet** [mathjax/MathJax#811]
When using \alignat or \alignedat, if the first marker (&) is set on =, <, >, \le, \ge, etc., then the space to the left of the relation disappears.  Example:

``` latex
$$
\begin{alignat}{2}
-\nabla\cdot(\alpha(x,\nabla u)\nabla u)&=f(x)&&\quad{\rm in}\
\Omega\subset \Bbb R^2,\\
u&=0&&\quad{\rm on}\ \partial\Omega,
\end{alignat}
$$
```

Tested with Firefox 28, using MathJax 2.3 and 2.4 beta.

**Comment by dpvc** [comment]
==> tests moved 

LaTeXToMathML/environments/issue811.html
