### ISSUE TITLE
The TeX input Jax should add an application/x-tex annotation

### ISSUE THREAD

**Issue by fred-wang** [mathjax/MathJax#814]
This change was done in MediaWiki, but it does not seem to have been integrated upstream (I could not find an issue): https://github.com/mathjax/MathJax/blob/develop/unpacked/jax/input/TeX/jax.js#L2090

This is necessary to allow copy & paste by other means than the MathJax context menu (e.g. with https://addons.mozilla.org/en-US/firefox/addon/mathml-copy/ or MathPlayer context).

If this is to be an option, it should not be an author config but a menu option, so that any user can decide whether or not he wants the TeX source to be exposed. In particular, such a menu option could be easily controlled by https://addons.mozilla.org/en-US/firefox/addon/mathjax-native-mathml/, without having to redefine MathJax's code.

**Comment by dpvc** [comment]
==> In Testsuite

UI/issue814.html
