### ISSUE TITLE
strikeout the text

### ISSUE THREAD

**Issue by MasaYan24** [mathjax/MathJax#819]
Hi I'm new using MathJax and sorry for silly question:

Can one use \sout or something like that to strikeout the text/equations?

**Comment by linusjf** [comment]
Does this work when converting Mathjax documents to pdf files? I seem to have a problem with Jupyter Lab not doing it.

```
! Undefined control sequence.
<argument> 1 \xcancel 
                      {+ exp(\hat {\beta _0} + \hat {\beta _1}x)} \bcancel {...
l.1199 ...1 + exp(\hat{\beta_0} + \hat{\beta_1}x)}
                                                   \\
? 
! Emergency stop.
<argument> 1 \xcancel 
                      {+ exp(\hat {\beta _0} + \hat {\beta _1}x)} \bcancel {...
l.1199 ...1 + exp(\hat{\beta_0} + \hat{\beta_1}x)}
                                                   \\
```
Same with cancel.

I'd like to retain the MathJax Look (if not the feel) in the pdf document as well.

**Comment by dpvc** [comment]
@linusjf, since these are LaTeX error messages, that suggests that you may have to add

``` latex
\usepackage{cancel}
```

to your `.tex` file.  I'm not sure how that is done in Jupyter Lab, so you may have to ask the Jupyter community for the details on how to do that.

**Comment by linusjf** [comment]
@dpvc That seems like a good idea. I'm not too familiar with Jupyter Lab config. It does seem that Jupyter has a macro cancel that works in the browser but not through latex where your suggestion comes in. I'm not sure where to make those updates, though. 

Maybe this might help me
<https://github.com/jupyterlab/jupyterlab-latex>

**Comment by linusjf** [comment]
<https://discourse.jupyter.org/t/has-anyone-figured-out-how-to-use-a-latex-package-like-cancel-in-a-markdown-cell/11637>

There seems to be the above but I haven't tested it out as yet
