### ISSUE TITLE
Scaling doesn't apply to characters in fallback text font

### ISSUE THREAD

**Issue by Herst** [mathjax/MathJax#826]
Let's say you have something like "\text{Gauß}" in your TeX input and you are rendering it in the HTML-CSS format output using the TeX font, then the "ß" is going to be rendered in a fallback font but the "scaling all math"  setting is apparently not respected for that character.

From the DOM I see that the "ß" gets puts into its own span but why is the font-size explicitly reduced there? (e.g. to 40% in the case of a global scale factor of 200% on my test page)

Reproducible with the 2.3 and 2.4 beta in different browsers.

DOM snippet:

``` html
<span style="font-family: MathJax_Main;" id="MathJax-Span-6" class="mtext">Gau<span style="font-family: STIXGeneral,'Arial Unicode MS',serif; font-size: 40%; font-style: normal; font-weight: normal;">ß</span></span>
```

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Characters/issue826-1.html
MathMLToDisplay/Characters/issue826-2.html
