### ISSUE TITLE
MathJax as composer package

### ISSUE THREAD

**Issue by nineff** [mathjax/MathJax#844]
Hello!

Currently, MathJax only provides a bower.json file for Node.js environments.
I think it would be beneficial to also provides a composer.json file to be [composer](https://getcomposer.org) package.
I'd create one my self, but I don't want to fork it for just one small file.

**Comment by christianhueser** [comment]
Hi, 
I tried to install mathjax with composer. I just created a composer.json file containing the required dependency "mathjax/mathjax". Unfortunately, the install process said that there is no such package called mathjax to install. Is version 2.5 of mathjax already available on Packagist https://packagist.org/ ? Thanks. Best regards, Christian

**Comment by pkra** [comment]
IIRC, you can specify git repositories directly. 

We'd be happy if somebody from the Composer community wanted to maintain a MathJax submission on Packagist.

**Comment by Gefrierbrand** [comment]
IIRC, the mathjax version numbering here on GitHub is not directly compatible with the one for composer/packagist. Mainly because of the added "-latest" avter the v2.x
However, adding this repo manually in your composer project should work. Some fiddling with configs might be required ;)

**Comment by christianhueser** [comment]
Alright, many thanks for the quick response. I will figure out how to do this. A short description in the documentation would be nice, though.

**Comment by pkra** [comment]
@Gefrierbrand from https://packagist.org/about it seems packagist would solve the problem since it looks for the tags (and those are semver-style)

Anyway, I've created an account for MathJax at Packagist and [submitted MathJax](https://packagist.org/packages/mathjax/mathjax). It picks up on both tags (though strangely only the latest two) and branches. Hope this helps.
