### ISSUE TITLE
Bug: line breaks in annotations are lost

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#847]
### Issue Summary

Reported on the [MathJax user group](https://groups.google.com/forum/#!topic/mathjax-users/3j3AlkBA1CA).

If MathML annotations contain linebreaks, these are lost during processing. 
### Steps to Reproduce
1. Let the following render with MahJax
   
   ```
   <math>
   <semantics xref="p1.1.m1.1.cmml"><mo>Test</mo>
   
       <annotation encoding="application/x-tex">{\displaystyle{\displaystyle\sum_{k=1}^{\infty}\frac{\mathop{\zeta\/}\nolimits%
   \!\left(2k\right)}{k}z^{2k}=\mathop{\ln\/}\nolimits\!\left(\frac{\pi z}{%
   \mathop{\sin\/}\nolimits\!\left(\pi z\right)}\right)}}</annotation>
     </semantics>
   </math>
   ```
2. Check that Show Math => annotation => TeX gives
   
   {\displaystyle{\displaystyle\sum_{k=1}^{\infty}\frac{\mathop{\zeta\/}\nolimits% !\left(2k\right)}{k}z^{2k}=\mathop{\ln\/}\nolimits!\left(\frac{\pi z}{% \mathop{\sin\/}\nolimits!\left(\pi z\right)}\right)}}

Similarly for showing the (non-original) MathML source.

This is a bug because it makes the annotations unusable.
### Technical details
- MathJax Version: 2.3+

**Comment by pkra** [comment]
Trying to write a test, I noticed that the minimal example above 

```html
<math>
  <semantics>
    <mrow>
      <mi>x</mi><mo>+</mo><mn>1</mn>
    </mrow>
    <annotation encoding="LaTeX">
    x+
    1
    </annotation>
  </semantics>
</math>
```

gets converted to 

```html
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
      <mi>x</mi>
      <mo>+</mo>
      <mn>1</mn>
    </mrow>
    <annotation encoding="LaTeX">
      &#xA;    x+&#xA;    1&#xA;    
    </annotation>
  </semantics>
</math>
```

**Comment by pkra** [comment]
This seems not ideal as the ShowSource window wraps the MathML in a pre tag.

**Comment by dpvc** [comment]
Anything outside the range U+0020 to U+007E was being translated to numeric entities.  I've excluded U+000A (newline), U+000D (return), and U+0009 (tab).  That should take care of the problem.

**Comment by pkra** [comment]
Great. I'll modify my test to fit.

**Comment by dpvc** [comment]
==> In Testsuite

UI/issue847.html
