### ISSUE TITLE
Typo in (English) message

### ISSUE THREAD

**Issue by lokal-profil** [mathjax/MathJax#852]
The `MaxMacroSub2` message in `/MathJax/localization/en/TeX.js` should read "LaTeX" instead of "latex".

Unsure if that is done here or at [mathjax/mathjax-i18n](https://github.com/mathjax/MathJax-i18n) though since English is the source language.

**Comment by pkra** [comment]
@dpvc I think the `QA - Testcase Wanted` label was misplaced here. Removing it.

**Comment by dpvc** [comment]
Agreed.
