### ISSUE TITLE
comma for "decimal point" not recognized in \hspace

### ISSUE THREAD

**Issue by davidfarmer** [mathjax/MathJax#856]
I was processing a LaTeX file that contained
\hspace{0,5cm}
in an equation.  This gave a MathJax error: Missing dimension or its units for \hspace.

The answer to issue #169 described a way to switch from US to European notation
for numbers.  I couldn't tell if that would make a difference in my case, but what I would
really like is for either notation to work in all cases, because it is nontrivial for me to
detect which notation is used be a particular author (I am using MathJax to display the
math in papers written by other people).

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/issue856.html
