### ISSUE TITLE
Preserving RDFa, microdata etc on MathML source

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#860]
A [feature request via SO](http://stackoverflow.com/questions/24514895/how-to-keep-rdfa-attributes-in-mathml-using-mathjax/24528090#24528090).

We should preserve microdata, RDFa etc. from the MathML source. In particular now that search engines are running more and more JavaScript.

**Comment by pkra** [comment]
=> in documentation https://github.com/mathjax/MathJax-docs/issues/78

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/issue860-1.html
MathMLToDisplay/issue860-2.html
