### ISSUE TITLE
IE 7/8 with STIX-Web fonts

### ISSUE THREAD

**Issue by drlippman** [mathjax/MathJax#869]
I am finding that IE7 and IE8 are having issues loading the STIX-Web fonts. They freeze during the font load, and trigger the error in the console along the lines of:

```
CSS3111: @font-face encountered unknown error.
File: STIXMathJax_Main-Regular.eot
```

Here is a quick test file that triggers the error:

```
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<script type="text/x-mathjax-config">
MathJax.Hub.Config({ 
  "HTML-CSS": {webFont: "STIX-Web"}
});
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=AM_HTMLorMML"></script>
</head>
<body>
`sin(2/3 x + pi/2)`
</body>
</html>
```

This was tested on two systems, neither having the STIX fonts installed locally.  Removing the STIX-Web config and using the default webfonts does not trigger the issue.

**Comment by dpvc** [comment]
Support for IE7 and IE8 has been dropped.
