### ISSUE TITLE
Add some delays into the typesetting sequence

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#872]
Add some delays into the typesetting sequence to allow the browser to respond to user interaction, and update the message box.  For example, when measuring the ex and em sizes, if the math must be moved to the hidden div, this can cause performance degradation, and a previous message may not be able to be removed, giving the wrong impression about what is taking so long.  It would also help if multiple typeset calls are pushed on the queue, since this will make for slower typesetting, and it would be good to allow the browser to react between typesets.

**Comment by kwkbtr** [comment]
It seems that authors cannot override `processSectionDelay` by `MathJax.Hub.Config` since the parameter is not under `MathJax.Hub.config` object.

**Comment by pkra** [comment]
That's correct. Instead, use `MathJax.Hub.processSectionDelay` outside the configuration block.

**Comment by kwkbtr** [comment]
I see, thanks!
