### ISSUE TITLE
two vector symbols above symbol (tensor notation)

### ISSUE THREAD

**Issue by kapet3** [mathjax/MathJax#877]
I have problems with two vector symbols which I frequently use to denote a tensor quantity, for example \vec{\vec{a}} . The second vector arrow above the symbol is substantially larger and it does not look good, especially when compared to the TeX/LaTeX result. Tested with Firefox 24, 30, and Chrome 35.

MathJax:  
![vec2](https://cloud.githubusercontent.com/assets/8223946/3643615/303b10c6-10d6-11e4-8cda-10d889623344.png)

LaTeX: 
![vec2latex](https://cloud.githubusercontent.com/assets/8223946/3643636/91ffe16a-10d6-11e4-8fbb-f0c52d74a2b3.png)

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/above-below/issue877.html
