### ISSUE TITLE
px dimensions in \\[...] in TeX input

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#890]
From MediaWiki https://bugzilla.wikimedia.org/show_bug.cgi?id=69554

Something like

```
\begin{align}
    1+1=1 \\[5px]
    2+2=4
\end{align}
```

works in LaTeX but not in MathJax's TeX input. 

I don't know if this is expected behavior.

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/matrices/issue890.html
