### ISSUE TITLE
SVG output generating invalid SVG when using `&#x2006; `, e.g., in`\liminf`

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#898]
First reported at https://github.com/mathjax/MathJax-node/issues/6:
- Converting TeX input `\liminf` to SVG will contain`<text transform="scale(53.81925) matrix(1 0 0 -1 0 0)" stroke="none" font-weight="" font-style="" font-family="STIXGeneral,'Arial Unicode MS',serif"> </text>` which is invalid since `font-weight` and `font-style` are empty.
- Removing the empty attributes fixes this.

IIUC, the problem is that converting TeX input `\liminf` to MathML produces `u+2006` which is not covered by the MathJax TeX fonts (at least according to the error message of the SVG output) but also (in the output) not converted into characters that are covered. In turn, this unknown characters is causing the `text` tag.

E.g., `$a &#x2006; b$` also produces the problem.

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Characters/issue898.html
