### ISSUE TITLE
Spacing following \tfrac in superscript is wrong

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#911]
The spacing between the fraction and plus is too big for

    e^{\tfrac{1}{2} + c}

This is due to the check for `prevLevel > 0` in the `texSpacing` method.  Probably checking the operators `scriptlevel` is sufficient (or using an "or" rather than "and" for the check).

**Comment by pkra** [comment]
Just adding this to the milestone so that it's on some milestone. Feel free to move it to another milestone.

**Comment by dpvc** [comment]
The `issue911` branch of my fork of MathJax resolves this.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/issue911.html
