### ISSUE TITLE
\boldsymbol malfunction for local mathjax font in firefox

### ISSUE THREAD

**Issue by daegunlee** [mathjax/MathJax#923]
Local font is installed on Windows from MathJax/fonts/HTML-CSS/TeX/otf.
If \boldsymbol is used, then all normal font is displayed same as \boldsymbol in firefox.
![sample1](https://cloud.githubusercontent.com/assets/8838551/4343722/d86f90f6-405f-11e4-946c-baf135646257.png)

The \boldsymbol and normal font displays correctly for web font, stix local font, IE, or chrome.
![sample2](https://cloud.githubusercontent.com/assets/8838551/4343723/ee9dd0ea-405f-11e4-9ec7-49841a6ec5f9.png)

Thanks.

**Comment by pkra** [comment]
@daegunlee could you let us know if you still see this?
