### ISSUE TITLE
No LaTeX command \mathbfit

### ISSUE THREAD

**Issue by jkm** [mathjax/MathJax#929]
The command `\mathbfit` is not supported by MathJax (see http://docs.mathjax.org/en/latest/tex.html#tex-commands). `\mathbfit` is like `\mathbf` but additionally italicizing. Even though this command is rarely used you may consider it for completeness reasons.

If adding it is not an option: Any idea how to define a macro that results in similar output to `\mathbfit`?

**Comment by cben** [comment]
AFAICT the only BoldItalic fonts are STIXMathJax_* with lots of coverage and MathJax_Math-BoldItalic with only 100 glyphs — latin full lower+upper, greek full lower+11 upper and a handful of others.
In other words, STIX is the only choice.

**Comment by toogy** [comment]
How can I display a nice `\mathds{1}` with MathJax?

**Comment by pkra** [comment]
As mentioned, MathJax's mathbb does actually do what mathds does if the configured font supports it. In MathJax's case, you'll need to use STIX.

**Comment by toogy** [comment]
Ah right, thanks :)

**Comment by dpvc** [comment]
The `\mathbfit` and other similar macros are available in v3.2.
