### ISSUE TITLE
TeX annotation in MathML output mode should be XML escaped

### ISSUE THREAD

**Issue by physikerwelt** [mathjax/MathJax#935]
It would be nice if the TeX annotation generted in the MathML output would be XML escaped.
Otherwise, XML validation tools might cosinder the characters `& < >...` to be invalid.
In https://gerrit.wikimedia.org/r/#/c/166556/ provides a workaround for most cases, but if the TeX string contains "</annotation>" we could have a problem with the woraround.
As far as I know this is a MathJax and not a MathJax node bug, but feel free to move the bug if I'm wrong.

**Comment by dpvc** [comment]
==> In Testsuite

UI/issue935.html
