### ISSUE TITLE
Double underline problem

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#937]
This issue sees to be similar to #877.

Something like `\underline{\underline a}` has a longer second underline compare to TeX rendering.

See also https://bugzilla.wikimedia.org/show_bug.cgi?id=35189 and renderings at https://www.mediawiki.org/wiki/Extension:Math/bug/35189.

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/above-below/issue937.html
