### ISSUE TITLE
Unicode fallback and combined characters

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#952]
[Via Wikipedia / MediaWiki](https://bugzilla.wikimedia.org/show_bug.cgi?id=48032).

Something like `ത്ര` will be represented as `&#xD24;&#xD4D;&#xD30;` but in the MathJax output, these three will be split across span's (or g's) which breaks the rendering of a combined character into the two characters and the combining mark.

**Comment by pkra** [comment]
Closed as duplicate.

**Comment by jbbpatel94** [comment]
@pkra did you get any alternative solution for this one ?

**Comment by dpvc** [comment]
We are working on the font support for MathJax version 3 this summer, and this could fit into that project.  I have not forgotten about it, and have ideas about it, but nothing has yet been done to address it directly.  The current solution is to use `\text{}`around the non-math characters together with `mtextInheritFont: true` in the configuration for the output being used.
