### ISSUE TITLE
mhchem improvements / prescripts and multiscripts in TeX

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#956]
Just so that I don't forget about it. I noticed that mhchem doesn't produce particularly nice MathML, e.g., it seems it could produce multiscripts for isotopes like `\ce{^{227}_{90}Th+}`. I realize this is due to how mhchem itself works but perhaps we can do better next year.

**Comment by dpvc** [comment]
This is resolved in the `issue956` branch of my fork of MathJax.

**Comment by dpvc** [comment]
=> Merged

**Comment by dpvc** [comment]
=> in testsuite

LaTeXToMathML/mhchem/issue956.html
