### ISSUE TITLE
Published iOS app doesn't render MathJax

### ISSUE THREAD

**Issue by ajhalls** [mathjax/MathJax#960]
We created a quiz software (https://itunes.apple.com/us/app/coursesaver-college-quiz/id917396757?mt=8) that uses MathJax to render our equations. When it was built in Xcode and loaded onto iPad, everything worked great, but after publishing through the app store it doesn't parse the inline latex.

Here is a picture, it is kind of hard to see, but in the answer choices there are supposed to be a \(^{\circ}\) for a degree symbol.

We set it up for inline parsing like you suggested here: https://github.com/mathjax/MathJax/issues/895#issuecomment-53052115

Any idea why it works when installed locally, but not after being published?

![img_0094](https://cloud.githubusercontent.com/assets/5520815/5111455/e1d55100-6fdd-11e4-91d6-103a2fb4ac3a.jpg)

**Comment by tiborsimon** [comment]
I have managed to make MathJax work locally in an iOS app. https://tiborsimon.io/ios/local-mathjax-in-ios-apps/ Not published it yet though. I will report my experiences.

**Comment by pkra** [comment]
Thanks for sharing this here, too, @tiborsimon.
