### ISSUE TITLE
Improve HTMLorMML configuration [was: Support for SVG or native MathML]

### ISSUE THREAD

**Issue by scaljeri** [mathjax/MathJax#965]
Is it possible to have formulas in SVG or (if supported) MathML. I've tried a zillion configuration combinations to get this to work. My findings are:

   1) its SVG for all browser (TeX-AMS-MML_SVG.js)
   2) its MathML for FireFox and HTML-CSS for the others (MMLorHTML.js)

[DEMO](http://jsfiddle.net/zggLo599/6/) 

I think that the documentation is not clear about this. 

If what I want is not possible it would be a nice feature to have!

**Comment by pkra** [comment]
The following is planned.

* for v2.6: document how this can be done today via a configuration.
* THEN move this to the 3.0 milestone since the fix we have in mind requires some breaking changes.

**Comment by pkra** [comment]
One more update. We have decided to effectively deprecate the HTMLorMML "extension" (which is actually rather atypical for an extension).

Instead, we will document how to set things up more generally, in particular how to set any output. This will be part of our documentation, cf. https://github.com/mathjax/MathJax-docs/issues/109. Leaving this issue open until that mathjax-docs issue is resolved.

**Comment by episodeyang** [comment]
I am running into a similar issue. What is the best way to set it up? I can wait for the documentation if you are busy. Thanks!

**Comment by dpvc** [comment]
The output renderer must now be selected explicitly (the `HTMLorMML` configurations always selects HTML).
