### ISSUE TITLE
SVG output: munder with form=prefix overlap

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#966]
From http://jsbin.com/laroje/5/edit:

``` html
<munder>
  <mo movablelimits="true" form="prefix">max</mo>
  <mi mathvariant="normal">&#x3A3;</mi>
</munder>
```

overlaps in SVG but not in HTML-CSS output. (Oddly, the TeX equivalent is ok.)

**Comment by dpvc** [comment]
=> In Testsuite

MathMLToDisplay/Presentation/ScriptsAndLimits/munder/issue966.html
