### ISSUE TITLE
Image sometimes show and sometimes not

### ISSUE THREAD

**Issue by MassD** [mathjax/MathJax#967]
Here is the page where I am using MathJax

http://typeocaml.com/2014/11/26/height-depth-and-level-of-a-tree/

Internally, I did this inside \<head\>

```javascript

{{! Mathjax configuration}}
	<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    	<script type="text/x-mathjax-config">  
      	MathJax.Hub.Config({
      	tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
      	});
    	</script> 

```

So if you go to that page directly, you can see that the image for `2^h` showed for 0.5 sec and then disappear.

![mathjax](https://cloud.githubusercontent.com/assets/1250103/5221852/29691182-767d-11e4-80f7-6f1a80b112c1.png)

but if you load up chrome's developer tool, and then refresh the page, the complete equation is shown and fine.

Why is this?

**Comment by pkra** [comment]
Closing this as abandoned.
