### ISSUE TITLE
spacing with \frac

### ISSUE THREAD

**Issue by Alex-Jordan** [mathjax/MathJax#969]
`$-\frac12$` appears to treat the minus sign like a subtraction sign, putting more space between the minus sign and the fraction than I would expect. `$-{\frac12}$` treats the minus sign like a negative sign with less space, and it's how I bypass the issue in practice. Similar things happen if you want to make a mixed number: `$1\frac12$` versus `$1{\frac12}$`.

I see these issues in HTML-CSS and SVG output modes, but not in MathML with Firefox 33.1. Maybe this is expected behavior, but I couldn't find any discussion of it anywhere so I thought I would open this issue.

**Comment by dpvc** [comment]
==> In Testsuite

LaTeXToMathML/frac/issue969.html
