### ISSUE TITLE
CHTML-preview leaves preview if custom script tags are used directly

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#975]
Live example at http://jsbin.com/pakoxe/2/edit

**Comment by dpvc** [comment]
=> In Testsuite

Parsing/issue975.html

**Comment by pkra** [comment]
I think I marked this as Needs Documentation to remember to document the CHTML-preview extension; this has been done as part of https://github.com/mathjax/MathJax-docs/pull/83 so I'm removing the tag.
