### ISSUE TITLE
Negative sign in <mn> doesn't use the math minus sign

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#989]
The HTML-CSS and SVG output display `<mn>-1</mn>` using the dash U+002D rather than the minus sign U+2212.  It would be nice to convert that to the correct character.

Firefox's native MathML rendering also uses U+002D for `<mn>-1</mn>`.  Should we tweak that as well?

**Comment by davidcarlisle** [comment]
On 3 January 2015 at 16:59, Davide P. Cervone <notifications@github.com>
wrote:

> The HTML-CSS and SVG output display <mn>-1</mn> using the dash U+002D
> rather than the minus sign U+2212. It would be nice to convert that to the
> correct character.
>
> Firefox's native MathML rendering also uses U+002D for <mn>-1</mn>.
> Should we tweak that as well?
>

we added specific notes to the mathml spec telling people to code negative
numbers as
<mrow><mo>-</mo><mn>123</mn></mrow>
but it's not at all uncommon to see <mn>-123</mn> so making it use &minus;
of it doesn't contort the code to much is probably the pragmatic thing to
do, although I think 2D is "more correct mathnml rendering" it's almost
certainly not what the author intended.

David

**Comment by dpvc** [comment]
Thanks, David.  The issue actually car up because the new content-mathml output produces `<mn>-1</mn>` rather than `<mrow><mo>-</mo><mn>1</mn></mrow>`.  That should probably be fixed, but I thought it would be good to handle `<mn>-1</mn>` as though it were the recommended form.

**Comment by davidcarlisle** [comment]
On 3 January 2015 at 21:16, Davide P. Cervone <notifications@github.com>
wrote:

> Thanks, David. The issue actually car up because the new content-mathml
> output produces <mn>-1</mn> rather than <mrow><mo>-</mo><mn>1</mn></mrow>.
> That should probably be fixed, but I thought it would be good to handle
> <mn>-1</mn> as though it were the recommended form.
>
>

oops I should definitely fix that!

(I can be relaxed about other people not following the spec but me not
following the spec doesn't look too good:-)

David

**Comment by dpvc** [comment]
Since Christian made the version of your code that we are using, it may be that we need to do the change.  Can you suggest where that location might be?  I haven't looked closely at the code, but will go through it if necessary.

**Comment by davidcarlisle** [comment]
On 3 January 2015 at 21:36, Davide P. Cervone <notifications@github.com>
wrote:

> Since Christian made the version of your code that we are using, it may be
> that we need to do the change. Can you suggest where that location might
> be? I haven't looked closely at the code, but will go through it if
> necessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mathjax/MathJax/issues/989#issuecomment-68610569>.
>



yes must admit that when I replied I was thinking of the mml3 to mml2 stuff
and forgot
that Christian had re-engineered it. So I can go back to "relaxed" mode:-)

the bug's inherited from the original xslt really (sorry) but I was just
looking at the js now.
It's a bit awkward as all the token element handling is unified and this is
a special case
for cn or more specifically for each text node in cn <cm>-2<sep/>-3</cn>...
as such it may be easiest to hook in here


    /* Add an element with given name and text content
     */
    appendToken: function(parentNode,name,textContent) {
        var element = CToP.createElement(name);
        element.textContent = textContent;
        parentNode.appendChild(element);
        return element;
    },


and then

 if name=mn and textContent matches /\s*-/ then instead generate
an <mrow><mo>-</mo><mn>text content with - removed</mn>

**Comment by dpvc** [comment]
Thanks for the analysis.  Your suggestion is about what I expected would be needed.  I will take care of it.

**Comment by davidcarlisle** [comment]
thanks

On 3 January 2015 at 22:14, Davide P. Cervone <notifications@github.com>
wrote:

> Thanks for the analysis. Your suggestion is about what I expected would be
> needed. I will take care of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mathjax/MathJax/issues/989#issuecomment-68611703>.
>



-- 
http://dpcarlisle.blogspot.com/

**Comment by dpvc** [comment]
The `issue989` branch of my fork of MathJax includes the fixes for these, including one for the NativeMML output.

**Comment by dpvc** [comment]
==> Merged.

**Comment by dpvc** [comment]
==> In testsuite

MathMLToDisplay/Content/reftest.list
MathMLToDisplay/Presentation/TokenElements/mn/issue989.html
