### ISSUE TITLE
NativeMML doesn't handle \tag properly in Firefox

### ISSUE THREAD

**Issue by dpvc** [mathjax/MathJax#993]
Now that Firefox doesn't process `style` attributes any longer, the current work-around for tags doesn't work.  The `<mrow style="width:100%">` is not getting to be the correct width.  Technically, this is a browser bug, since `<mrow><mtable width="100%">...</mtable></mrow>` is supposed to operate exactly like `<mtable width="100%">...</mtable>`, but it doesn't.

The solution is either to not include the outer `<mrow>` when the content is table with `width` set, or to make a CSS class setting for `width:100%` and use that instead of explicit `style`.

**Comment by pkra** [comment]
Do you have a minimal example of the FF bug that we can use to file an upstream bug?

**Comment by dpvc** [comment]
OK, it turns out not to be the reason that I thought.  The `<mrow>` with `style` is fine, it is the additional `<semantics>` element that is causing the problem.  For example

``` html
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mtable width="100%" mathbackground="red">
      <mtr> <mtd><mi>x</mi></mtd> </mtr>
    </mtable>
    <annotation encoding="application/x-tex">x</annotation>
  </semantics>
</math>
```

does not produce the same result as

``` html
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <mtable width="100%" mathbackground="red">
    <mtr> <mtd><mi>x</mi></mtd> </mtr>
  </mtable>
</math>
```

though I believe it should.  A work-around is to use `style="width:100%"` on the `<semantics>` element, as in

``` html
<math display="block" xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics style="width:100%">
    <mtable width="100%" mathbackground="red">
      <mtr> <mtd><mi>x</mi></mtd> </mtr>
    </mtable>
    <annotation encoding="application/x-tex">x</annotation>
  </semantics>
</math>
```

though that should not be necessary.  In any case, I can use this for now to get around the problem.

**Comment by dpvc** [comment]
The work-around is in the `issue993` branch of my fork of MathJax.

**Comment by pkra** [comment]
Thanks for the example. I've asked the MathWG to comment.

**Comment by dpvc** [comment]
==> Merged

**Comment by dpvc** [comment]
My previous commit only fixed the problem for the situations generated by the TeX input jax.  If the input is directly from MathML and output is NativeMML, this is still a problem.  The NativeMML output jax should tweak the output in this case as well.

**Comment by dpvc** [comment]
==> In Testsuite

MathMLToDisplay/Presentation/TablesAndMatrices/issue993-1a.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-1b.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-1c.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-1d.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-1e.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-2.html
MathMLToDisplay/Presentation/TablesAndMatrices/issue993-3.html

**Comment by pkra** [comment]
I think this Gecko bug is a case of https://bugzilla.mozilla.org/show_bug.cgi?id=468059

**Comment by pkra** [comment]
Great.. the workaround renders very badly on WebKit... http://jsbin.com/gimevacori/1/edit
