### ISSUE TITLE
Revisit blacker settings [was SVG output: revisit blacker settings]

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax#994]
I was playing around with the blacker setting and it seems to me that setting it to 1 got consistently better results across current browsers (better as in: closer to HTML-CSS rendering). Some spacing semed tighter though (overlines etc).

Let's investigate after 2.5 is out

**Comment by pkra** [comment]
Extended to all blacker settings, i.e., revisit the MathJax TeX fonts conversion.

**Comment by pkra** [comment]
I've sent a PM with screenshots (GitHub didn't like that many files or zips). 

The shots were produced from http://codepen.io/pkra/full/MYRbbG. 

They look good to me.

**Comment by dpvc** [comment]
> Extended to all blacker settings, i.e., revisit the MathJax TeX fonts conversion.

That is bigger than I think we want to tackle in v2.6.  I'm thinking that should go into the "font release" milestone (or perhaps 3.0).

**Comment by pkra** [comment]
> That is bigger than I think we want to tackle in v2.6. I'm thinking that should go into the "font release" milestone (or perhaps 3.0).

Agreed -- moved this part to #1232.

**Comment by dpvc** [comment]
This is fixed in the `issue994` branch of my fork of MathJax.
